Makefile

We don't use Travis anymore so this work-around is not required anymore.
Cherry picked from #3185.

Remove Travis work-around

---

contrib/core/actions/local.yaml

Self-explanatory - just a minor fix of the description (mistakenly refers to remote host)

Fixed typo in description of core.local action

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionalias.py
st2api/tests/unit/controllers/v1/test_action_alias.py

This fixes bug reported in https://github.com/StackStorm/st2/issues/3170.
It looks like this regression was introduced as part of https://github.com/StackStorm/st2/pull/2841, but we didn't have any tests for this API endpoint so the regression wasn't caught earlier.

Fix action alias update API endpoint

---

CHANGELOG.rst
st2client/st2client/base.py
st2client/tests/unit/test_app.py

This should fix the issue reported in https://github.com/StackStorm/st2/issues/3186.

Make config file paths which are relative to the user's home directory work inside st2 CLI

---

CHANGELOG.rst
contrib/runners/action_chain_runner/action_chain_runner.py
contrib/runners/action_chain_runner/tests/unit/test_actionchain.py
st2actions/st2actions/notifier/notifier.py
st2common/st2common/util/param.py
st2common/st2common/util/templating.py
st2common/tests/unit/test_param_utils.py
st2common/tests/unit/test_util_templating.py
st2reactor/st2reactor/rules/datatransform.py
st2reactor/tests/unit/test_data_transform.py
st2reactor/tests/unit/test_filter.py
st2tests/st2tests/fixtures/generic/actionchains/chain_with_system_vars.yaml

Redo https://github.com/StackStorm/st2/pull/3164 after we decided to only deprecate {{system}} and {{user}} jinja notations. 
Deprecation notice in Upgrade Notes - https://github.com/StackStorm/st2docs/pull/367

Deprecate {{system}} and {{user}} jinja notations

---

CHANGELOG.rst
contrib/packs/actions/pack_mgmt/download.py
contrib/packs/tests/test_action_download.py

packs.download and as such `pack install` command would not work if git repository uses a default branch which is not master.
The whole gitref and checkout code is quite convoluted so I won't accept this as done until we have good coverage for all the ref edge cases - it's possible that there are more bugs lurking in that code.
I understand the reason why the code is doing what is doing (we try to determine if ref / commit is part of a branch, but ref could also be a branch), but I will also think about it some more and see if I can simply some of that logic. Simpler logic means less chance for bugs.
This fixes a bug reported by a user in the community - https://github.com/StackStorm/st2/issues/3200.

Fix packs.download action so it works if default repo branch is not master

---

circle.yml
st2common/st2common/models/db/__init__.py

This pull request updates the code to ignore the errors about which we can't do anything right now.
Correct solution we should eventually do is to re-creating offending indexes. The problem with re-creation is that the operation is blocking and depending on the dataset size, it could take a very long time.

Ignore "index with different options already exists" mongoengine errors

---

st2client/st2client/commands/auth.py
st2client/tests/base.py
st2client/tests/unit/test_auth.py
st2debug/st2debug/processors.py

Randomly noticed it's not working while testing it - https://gist.github.com/Kami/f03360208e2e8599f42d3152df054842
It looks like the problem is that code tries to work with the `ConfigParser` object as a dictionary, but `ConfigParser` object doesn't behave and support dictionary-like access notation.
Edit: Looked at the tests and it looks like they didn't catch this issue because the hide it because they mock `ConfigParser` instance. I know that's not always possible, but we should try to avoid mocking as much as possible because many times we end up mocking too much and we actually end up testing mocks and not the actual code...

Fix st2 login and st2 whoami commands to work

---

Makefile
contrib/packs/actions/pack_mgmt/download.py
st2api/st2api/controllers/resource.py
st2client/st2client/commands/action.py
st2common/bin/migrations/v1.5/st2-migrate-datastore-to-include-scope-secret.py
st2common/bin/migrations/v2.1/st2-migrate-datastore-scopes.py
st2common/st2common/content/bootstrap.py
st2common/st2common/log.py
st2common/st2common/models/db/action.py
st2common/st2common/models/db/executionstate.py
st2common/st2common/models/db/marker.py
st2common/st2common/models/db/rbac.py
st2common/st2common/models/db/rule.py
st2common/st2common/models/db/rule_enforcement.py
st2common/st2common/models/db/runner.py
st2common/st2common/models/db/sensor.py
st2common/st2common/models/db/trace.py
st2common/st2common/operators.py
st2common/tests/unit/test_db_model_uids.py
st2reactor/st2reactor/garbage_collector/config.py
test-requirements.txt
tools/diff-db-disk.py
tools/migrate_rules_to_include_pack.py
tools/visualize_action_chain.py

I noticed it was broken when I was upgrading pylint as part of #3189.
We passed invalid (in-existent) path to pylint but older versions simply silently ignored that.
For example, it got passed in `contrib/runners/action_chain_runner/contrib/runners/action_chain_runner/` instead of `contrib/runners/action_chain_runner/` so files in those directories were not actually pylinted.

Fix pylint on runner Python modules

---

.codecov.yml

Avoid Codecov spammy behavior with inaccurate coverage% comments and wrong red GitHub PR statuses.
See https://docs.codecov.io/docs/commit-status

Adjust Codecov behavior

---

st2client/st2client/base.py

https://github.com/StackStorm/st2/pull/3219 changed the logic of when a token is retrieved from the API by looking for the 'credentials' field of the configuration.
However, when this section is missing (or when the config is omitted entirely, like it is in CI), this field is set to an empty dictionary, and then because both `username` and `password` default to None and then are added to this dict, the statement `if credentials:` will never evaluate to False, because this dict will never be empty.
In CI, this causes problems We want to skip this step when the config is missing, because in CI this is expected and other API methods will work just fine because auth is disabled. This change proposes looking at just specifically the `username` field, because even though `st2 login` omits the …

Change conditional to point to username field in client config

---

CHANGELOG.rst
st2client/st2client/commands/pack.py

This pull request fixes a bug with ``--token`` and other CLI argument propagation in the ``st2 pack install``, ``st2 pack remove`` and ``st2 pack config`` commands.
Those commands consist of multiple API calls and previously those CLI arguments / options were only correctly propagated to the first API call and not others which means using option such as ``--token`` / ``-t`` wouldn't work correctly - only first API call would succeed, other would fail due to token not being provided.
Note: Client refactor and getting rid of all this nasty kwargs abuse can't come soon enough (some of the internal methods which manipulate kwargs even manipulate dict in place so I'm pretty sure there are other bugs related to that in the code, a ticking time bomb).
Resolves #3212.

Fix a bug with CLI argument propagation in the st2 pack install, st2 pack remove and st2 pack config commands

---

CHANGELOG.rst
st2common/st2common/models/api/rbac.py
st2common/st2common/rbac/types.py
st2common/tests/unit/test_rbac_loader.py
st2tests/st2tests/fixtures/rbac/roles/role_seven.yaml

The code incorrectly assumed that the only global permission types (the ones which are global and don't apply to a specific resource) are just _list permissions.
This pull request fixes that. It was originally reported by a community member saying that they can't apply "pack_install" and some other pack-related global permissions using `st2-apply-rbac-definitions`.

Fix handling of global RBAC permission types

---

st2client/st2client/commands/auth.py
st2client/tests/unit/test_auth.py

Small fix so we don't print "Logged in as x" on failed log in attempt.

Don't print "Logged in as x" on failed st2 login attempt

---

st2common/bin/st2-run-pack-tests

This pull request fixes two issued I discovered while testing the packages:
1. Make sure we activate virtualenv before we try to upgrade pip (previously it would try to install it into global namespace).
2. Make sure we add /opt/stackstorm/st2/bin to $PATH so it works on package installations (previously this wasn't added to $PATH so the script wouldn't work out of the box on package based installations)/

Fix st2-run-pack-tests script

---

CHANGELOG.rst
st2common/tests/unit/test_pack_action_alias_unit_testing_utils.py
st2tests/st2tests/action_aliases.py
st2tests/st2tests/fixtures/packs/pack_dir_name_doesnt_match_ref/aliases/alias1.yaml
st2tests/st2tests/fixtures/packs/pack_dir_name_doesnt_match_ref/pack.yaml

This pull request fixes a bug which would cause action alias tests to fail when local pack directory name doesn't match `pack` attribute in different resource metadata files.
This can be the case with the new pack management when you are locally developing a pack and local git repository directory name is not the same as `pack` / `ref` attribute (e.g. `stackstorm-network_utils` vs `network_utils`).
Again, this only affects local development and not actual StackStorm installations when packs are installed into `/opt/stackstorm/packs`. When pack is downloaded (git clone), correct directory name is used (one which matches `pack` / `ref` attribute) - if you run tests on `/opt/stackstorm/packs/<pack>` directory, they will work just fine.
Resolves https://github.com/StackStorm/st2/issues/3250 …

Fix base action alias test case so it works if local pack directory name doesn't match the pack name

---

CHANGELOG.rst
st2common/bin/st2ctl
st2common/st2common/content/bootstrap.py

There was an inconsistency between default `st2-register-content` script and `st2ctl reload` command behavior.
The former would correctly exit on failure by default, but `st2ctl reload` wouldn't because it didn't correctly preserve and propagate the exit code from the `st2-register-content`.
Issue originally reported by tanya on Slack (good catch!)

Fix st2ctl reload so it preserves exit code from "st2-register-content" script and fails on failure by default

---

CHANGELOG.rst
st2common/st2common/util/config_loader.py
st2common/tests/unit/test_config_loader.py

Before this fix, default values from pack config schema would not get applied (and as such, not passed to Python runner actions and sensors via config) if pack didn't have a config in `/opt/stackstorm/configs/` directory.
Thanks to @jjm for catching and reporting this.
Resolves #3258.

Fix a bug with default values from config schema not being used if pack doesn't have a config

---

st2tests/MANIFEST.in
st2tests/Makefile
st2tests/dist_utils.py
st2tests/in-requirements.txt
st2tests/setup.py
st2tests/st2tests/__init__.py

This is a first step needed which will allow us to create Python package from `st2tests` and include it in the rpm / deb distributions.
Including it in those distributions, will among other things, allow users to run `st2-run-pack-tests` directly on StackStorm package based installations.

Make st2tests directory a proper Python package

---

st2tests/setup.py

Instead of importing `__version__` from `__init__` module we now read version by parsing the file as text.
Because of the aliased imports inside `__init__.py` we can't import version from there directly. If we import it, this will require all the st2common dependencies to be installed for every invocation of `setup.py` which is undesirable - those dependencies are only required during run-time, but not during "compile" time aka during setup.py invocation phase (see https://circleci.com/gh/StackStorm/st2-packages/2014?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
I actually wanted to refactor the code to get rid of the aliased imports in st2tests.__init__.py, but after wasting 2 hours of my precious time I decided to give up and go with this approach. …

Don't import module to read version string inside st2tests setup.py

---

CHANGELOG.rst
contrib/runners/mistral_v2/tests/unit/test_mistral_v2_policy.py
st2actions/st2actions/handlers/mistral.py
st2common/st2common/util/action_db.py
st2common/tests/unit/test_action_db_utils.py
st2tests/integration/mistral/base.py
st2tests/integration/mistral/test_wiring.py

Fix Mistral workflow status when task is canceled. Currently, when a task is canceled, the workflow status is set to error. The workflow status should be set to canceled. Also, when a canceled action execution completes, the action execution will be updated from canceled to its new status. This should not be the case because the action execution has already been canceled. Before merging this patch, please ensure mistral fork is caught up with mistral upstream master. This requires another fix from mistral upstream.

Fix workflow status when task is canceled

---

CHANGELOG.rst
st2auth/st2auth/handlers.py
st2auth/tests/unit/test_handlers.py

This pull request works on top of https://github.com/StackStorm/st2/pull/3262 and adds a test-case for it so we can merge it.

Fix a bug with authentication not working if password contained a colon (:)

---

st2auth/st2auth/handlers.py

When a user password contains `:` the authorisation fails because the split breaks the string into list with more than 2 elements.  Adding 1 to the split constrains it to the first occurrence of the `:`.  Caveat, this will still break if the users name contains a `:`.
Thanks to @ftoussenel for finding this bug.

st2auth handler - Constrain split on : to first instance

---

st2common/bin/st2-run-pack-tests

This pull request updates `st2-run-pack-tests` script to only install global pack test dependencies when `ST2_REPO_PATH` environment variable is set.
When this variable is set, it means the script is likely running standalone outside of StackStorm package installation environment.
With recent changes and improvements to this script, the script now runs out of the box on new StackStorm package based installations where those global pack test dependencies are already available (they are installed and provided by `st2tests` package).
This change speeds things up when running multiple pack tests on a box where global pack test dependencies are available (e.g. `make .pack-tests` is now 10 seconds or so faster).

Update st2-run-pack-tests to only install global test dependencies when ST2_REPO_PATH variable is set

---

st2common/st2common/util/loader.py

Noticed it while reviewing #3277 - https://github.com/StackStorm/st2/pull/3277/files#r105350016.
We joined a path using string formatting and passed that already formatted string to `os.path.join` so `os.path.join` didn't actually perform any joining (we should pass multiple arguments of paths to be joined to `os.path.join`).

Fix os.path.join calls

---

CHANGELOG.rst
st2api/st2api/controllers/v1/pack_configs.py
st2api/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
st2common/st2common/rbac/resolvers.py
st2common/st2common/rbac/types.py

When we introduced pack configs related API endpoints (#2964) we didn't add corresponding API RBAC tests we have for every other API endpoint (`st2api/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py`) so we didn't catch an issue with pack config API endpoint not working when RBAC is enabled.
The issue has been fixed by introducing new global "pack_config" permission type which is needed to configure a pack instead of (incorrectly) using existing "pack_create".
Resolves #3283.
Thanks again to @efenian for reporting it and @LindsayHill for confirming.

Fix "PUT /v1/configs" API endpoint not working when RBAC is enabled

---

CHANGELOG.rst
contrib/linux/sensors/file_watch_sensor.yaml

These errors in a default installation get tedious
```
2017-03-16 02:16:11,449 140717658023568 ERROR (unknown file) [-] Traceback (most recent call last):
2017-03-16 02:16:11,449 140717658023568 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 357, in <module>
2017-03-16 02:16:11,450 140717658023568 ERROR (unknown file) [-]
2017-03-16 02:16:11,450 140717658023568 ERROR (unknown file) [-] obj.run()
2017-03-16 02:16:11,450 140717658023568 ERROR (unknown file) [-]   File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2reactor/container/sensor_wrapper.py", line 214, in run
2017-03-16 02:16:11,450 140717658023568 ERROR (unknown file) [-]
2017-03-16 02:16:11,450 140717658023568 ERROR (unknown file) [-] …
```

Disable filewatch sensor by default

---

st2common/st2common/middleware/error_handling.py

`LOG.exception` already includes a traceback. No need to log it a second time.

Fix traceback duplication in ErrorHandlingMiddleware

---

st2api/st2api/controllers/resource.py
st2api/st2api/controllers/v1/actionalias.py
st2api/st2api/controllers/v1/actionexecutions.py
st2api/st2api/controllers/v1/actions.py
st2api/st2api/controllers/v1/actionviews.py
st2api/st2api/controllers/v1/auth.py
st2api/st2api/controllers/v1/keyvalue.py
st2api/st2api/controllers/v1/pack_config_schemas.py
st2api/st2api/controllers/v1/pack_configs.py
st2api/st2api/controllers/v1/packs.py
st2api/st2api/controllers/v1/packviews.py
st2api/st2api/controllers/v1/policies.py
st2api/st2api/controllers/v1/rule_enforcements.py
st2api/st2api/controllers/v1/rules.py
st2api/st2api/controllers/v1/ruletypes.py
st2api/st2api/controllers/v1/ruleviews.py
st2api/st2api/controllers/v1/runnertypes.py
st2api/st2api/controllers/v1/sensors.py
st2api/st2api/controllers/v1/traces.py
st2api/st2api/controllers/v1/triggers.py
st2api/st2api/controllers/v1/webhooks.py
st2common/st2common/openapi.yaml

As @Kami pointed in https://github.com/StackStorm/st2/pull/2727#discussion_r103643612, using `**kwargs` in controllers require user to constantly keep in mind the list of parameters available for the particular controller or get back and forth between code and spec.
Luckily, as it turns out, we no longer need to use `**kwargs` in most cases and it's just a matter of refactoring.
The point of this PR is to replace the use of kwargs in every controller it is possible to do and justify it's use in the rest of them.

Refactor endpoints to get rid of kwargs

---

st2common/st2common/router.py

That was the initial intention, but it somehow slipped through the cracks.
If you don't import controller modules during server initialization, it would happen on the first request to the controller within the module. It would a) create a delay on this first request and b) cause a race on endpoints like `/webhooks` or `/stream` which require more time to properly initialize.

Preinitialize modules during route registration

---

st2api/tests/base.py
st2common/st2common/router.py

Auth service were raising 500 on endpoint with no security definition (`/auth/v1/tokens`) when RBAC is enabled.
Since RBAC always require auth to be enabled, no reason to check RBAC and authentication flags independently.
Also, all RBAC related tests should now flip auth flag too.

Fix router to only check rbac on endpoints with security

---

st2common/bin/st2-run-pack-tests

Noticed a small issue while testing latest v2.2.1 packages.
The issue would only affect people who directly use this tool from git master, but not people who run it on a system where StackStorm was installed using packages.
In any case, I would still propose to include this in v2.2.1.

Fix dependency version specified in st2-run-pack-tests-tool

---

CHANGELOG.rst
st2actions/st2actions/container/base.py
st2common/st2common/models/db/auth.py
st2common/st2common/services/access.py
st2common/tests/unit/services/test_access.py
st2reactor/st2reactor/container/process_container.py

This pull request introduces a concept of "service" (system) tokens which can have arbitrary TTL associated with them.
In addition to that it also stores some metadata with service tokens so it's easier to distinguish between service and user-level access tokens.
Previously only way to distinguish between user and service tokens in the database was by the "user" field and that approach was very fragile.
Now that we have additional metadata and "service" attribute on the token model it's easy to, for example, just purge all the user access tokens (e.g. to force all the users to re-authenticate), but leave service tokens untouched.
It resolves "issue" reported in #3314.

Support arbitrary TTLs for service (system) access tokens, associate some metadata with service tokens

---

st2common/bin/st2-self-check

Without correct `root:st2pack` pack permissions running workflow `examples` in `BWC` fails with API 500 error:
```sh
2017-03-30 17:22:00,115 140522965661968 ERROR hooks [-] API call failed: [Errno 13] Permission denied: u'/opt/stackstorm/packs/examples/actions/workflows/mistral-error-bad-task-transition.yaml'
File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 631, in __call__
self.invoke_controller(controller, args, kwargs, state)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/pecan/core.py", line 531, in invoke_controller
result = controller(*args, **kwargs)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/rbac/decorators.py", line 122, in func_wrapper
return func(*args, **kwargs)
File …
```

Fix pack permissions when running 'st2-self-check'

---

CHANGELOG.rst

Small formatting issue which could cause documentation build to fail when strict mode is enabled.

Fix heading underline

---

st2common/st2common/rbac/types.py

Same as #3324, but for v2.2. Adds missing API descriptions.

Add missing API descriptions to v2.2

---

CHANGELOG.rst
st2common/st2common/config.py
st2common/st2common/logging/formatters.py
st2common/tests/unit/test_logger.py

By default we use a static blacklist of parameter names (password, token, etc.) which are masked in the log message `extra` if `log.mask_secrets` config option is set to `True`.
This pull request allows administrator to define an additional custom list of attributes which are masked in the log messages.
Related PR https://github.com/StackStorm/st2docs/pull/459.

Allow user to specify a blacklist of attributes which are masked in the log messages

---

st2api/st2api/app.py
st2auth/st2auth/app.py
st2common/st2common/middleware/cors.py
st2common/st2common/middleware/error_handling.py
st2common/st2common/middleware/logging.py
st2common/st2common/middleware/request_id.py
st2stream/st2stream/app.py
st2tests/st2tests/api.py

The PR solves a number of problems introduced by #2727.
First, logging middleware fails during OPTIONS preflight request due to us not defining OPTIONS requests in spec. As far as logging concerned, every request to non-existing endpoint still needs to be logged.
Second, cors and error_handling middleware both depends on each other. CORS intercepts and reraises the NotFoundException, but don't provide its headers for endpoints that don't exist (preventing browser from properly handling the error) and error_handling middleware intercepts all the errors making it impossible for cors middleware to properly handle OPTIONS requests.

Fix cors middleware conflicting with logging and error handling

---

CHANGELOG.rst
st2api/st2api/controllers/v1/executionviews.py
st2api/tests/unit/controllers/v1/test_executions_filters.py
st2tests/st2tests/fixtures/history_views/filters.yaml

This pull request works on top of #3193 and adds tests so we can merge that change.

Filter out null from /executions/views/filters results (with tests)

---

CHANGELOG.rst
st2common/st2common/rbac/syncer.py
st2common/tests/unit/test_rbac_syncer.py

This pull request fixes a bug in `st2-apply-rbac-definitions` tool.
Previously, if an existing assignment file for a user in `/opt/stackstorm/rbac/assignments/` directory was deleted and `st2-apply-rbac-definitions` tool was ran afterwards, this wasn't correctly reflected in the database - previous / old assignments would still stay in the database instead of being deleted.
Found this bug while working on #3351.

Fix RBAC syncer so it correctly removes assignments for users with no assignment file on disk

---

st2client/st2client/models/core.py
st2client/tests/unit/test_client_liveaction.py

If no parameters is provided, NoneType is passed to the server side resulting in error.

Fix liveaction rerun with no parameters

---

st2common/st2common/cmd/apply_rbac_definitions.py
st2common/st2common/script_setup.py

Closes: https://github.com/StackStorm/st2/issues/3323
```(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ st2common/bin/st2-apply-rbac-definitions -h                issue_3323/rbac_apply_debug_mode ✭ ✱ ◼
usage: st2-apply-rbac-definitions [-h] [--config-dir DIR] [--config-file PATH]
[--debug] [--nodebug] [--noprofile]
[--nouse-debugger] [--profile]
[--use-debugger] [--verbose] [--version]
[--noverbose]
optional arguments:
-h, --help          show this help message and exit
--config-dir DIR    Path to a config directory to pull *.conf files from.
This file set is sorted, so as to provide a predictable
parse order if individual options are over-ridden. The
set is parsed after the file(s) specified via previous
--config-file, arguments hence over-ridden options in
the directory take precedence. …
```

Fix st2-apply-rbac-definitions debug mode

---

CHANGELOG.rst
contrib/examples/rules/sample_rule_file_watch.yaml
contrib/linux/config.yaml
contrib/linux/sensors/file_watch_sensor.py
contrib/linux/sensors/file_watch_sensor.yaml

Cherry-picked https://github.com/StackStorm/st2/pull/1291
Then, I made the following changes:
* I enabled the file_watch_sensor by default. 
* I edited the sensor YAML file to reflect pack name explicitly
* I added a sample rule which would register a trigger with parameter (file_path). Sensor automatically picks up the file name from rule and starts to listen to file and emit lines from file.
To test, do the following:
* Spin st2 up and place the linux pack from this branch to /opt/stackstorm/packs
* Register contents of linux pack - st2ctl reload --register-all
* Restart st2 so file_watch_sensor is run - st2ctl restart
* Verify file_watch_sensor is running and enabled
```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ ps auxww | grep file_watch | grep -v grep …
```

File watch sensor to utilize trigger with parameters

---

CHANGELOG.rst
contrib/examples/actions/mistral-basic.yaml
contrib/examples/actions/mistral-test-cancel-subworkflow-action.yaml
contrib/examples/actions/workflows/mistral-basic.yaml
contrib/examples/actions/workflows/mistral-test-cancel-subworkflow-action.yaml
contrib/runners/mistral_v2/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_v2_cancel.py
st2tests/integration/mistral/test_wiring.py
st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflow_v2_call_workflow_action.yaml
st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/workflow_v2_call_workflow_action.yaml
st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workflow_v2_call_workflow_action.yaml

When a Mistral workflow is cancelled, any actions that is a Mistral workflow is also cancelled.

Cancel subworkflow actions

---

st2common/st2common/models/db/auth.py
st2common/st2common/services/rbac.py
st2common/tests/unit/services/test_rbac.py

Recently a branch introduced a new `is_remote` field on the `UserRoleAssignmentDB` model.
To accommodate for this field and change, existing service functions were updated to handle local (non-remote) and remote role assignments.
This new field has a default value of false, but mongoengine doesn't lazily populate this field for existing documents which don't contain this field with a default value. This means that the queryset filter and service function didn't work correctly - it didn't correctly return old / existing documents without this field.
This would only affect users upgrading from older release to v2.3.0 (not released yet).
On a related note - I'm sure we made similar changes in the past and we were probably just lucky we haven't encountered …

Fix get_roles_for_user and get_role_assignments_for_user

---

st2common/st2common/rbac/syncer.py
st2common/tests/unit/test_rbac_syncer.py

Small addition to https://github.com/StackStorm/st2/pull/3381
I noticed local role assignments without `is_remote` field were still not getting deleted when syncing role assignments because I missed a spot.

Fix RBAC syncer to correctly delete local role assignments without `is_remote` field

---

CHANGELOG.rst
st2reactor/bin/st2rulesengine

The entry points for all of the st2 processes `sys.exit()` except for `st2rulesengine`. If `st2rulesengine` currently fails and exits it will exit successfully and won't be restarted by systemd. This change makes  `st2rulesengine` consistent with the entry points for all of the other st2 processes.

Add sys.exit() to rulesengine

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/tests/unit/policies/test_concurrency.py

Various dependencies upgrades again to get the latest changes and bug fixes:
* pyyaml,
* requests
* appscheduler
* gitpython
* paramiko
* mongoengine
* tooz

Upgrade dependencies

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/tests/unit/policies/test_concurrency.py

Reverts StackStorm/st2#3372
For now just a PR to experiment if `pip` packages might be related to re-appeared Ubuntu16 regression (even with timeouts) https://github.com/StackStorm/st2-packages/issues/445.

Revert mongoengine dependency upgrade

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_rules.py
st2common/st2common/config.py
st2reactor/tests/unit/test_sensor_service.py
st2tests/st2tests/fixtures/generic/rules/rule_invalid_trigger_parameter_type_default_cfg.yaml

This PR fixes the bug found in https://github.com/StackStorm/st2/issues/3385 by converting the trigger payload and parameter validation configuration parameters from `StrOpt` to `BoolOpt`, as well as adding unit tests for both to ensure the default configuration allows validation for both to be bypassed (which is the behavior we currently advertise).
Closes https://github.com/StackStorm/st2/issues/3385

Fix trigger parameter and payload validation bug

---

fixed-requirements.txt
requirements.txt

As per https://github.com/StackStorm/st2/pull/3372#discussion_r115702199 (thanks)
Should fix the https://github.com/shazow/urllib3/issues/1104 and broken Githubwebhooks on `st2cicd`.

Pin requests to the latest version (v2.14.1)

---

test-requirements.txt

Updated the sphinx and sphinx-autobuild versions in `test-requirements.txt` to match what we currently use in st2docs. 
We don't need to track our own version of sphinx-autobuild anymore, and we should pin the sphinx version.

make sphinx vers match st2docs

---

st2api/tests/unit/controllers/v1/test_triggertypes.py
st2common/st2common/openapi.yaml

It looks like a small regression introduced during move to OpenAPI and we didn't have any tests for this functionality.
Resolves #3405

Fix ?pack query param filter in /v1/triggertypes API endpoint

---

circle.yml

Removed webhook reference to old build node, as it is not working, and generates these warnings on CircleCI:
`webhook returned http status 503, connecting to https://webhooks.stackstorm.net:8531/webhooks/build/events`

Remove old CI webhook

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionviews.py
st2api/st2api/controllers/v1/policies.py
st2api/st2api/controllers/v1/rbac.py
st2api/st2api/controllers/v1/timers.py
st2api/tests/unit/controllers/v1/test_action_views_rbac.py
st2api/tests/unit/controllers/v1/test_executions_filters_rbac.py
st2api/tests/unit/controllers/v1/test_policies_rbac.py
st2api/tests/unit/controllers/v1/test_rbac.py
st2api/tests/unit/controllers/v1/test_timers_rbac.py
st2common/st2common/constants/types.py
st2common/st2common/models/api/policy.py
st2common/st2common/models/db/policy.py
st2common/st2common/models/db/timer.py
st2common/st2common/openapi.yaml
st2common/st2common/rbac/resolvers.py
st2common/st2common/rbac/types.py
st2common/tests/unit/test_db_model_uids.py
st2tests/st2tests/fixtures/generic/actions/a1.yaml
st2tests/st2tests/fixtures/generic/policies/policy_8.yaml
st2tests/st2tests/fixtures/rbac/roles/role_seven.yaml

This pull request implements RBAC for rest of the API endpoints which were missing it:

RBAC for rest of the API endpoints

---

CHANGELOG.rst
Makefile
st2actions/tests/integration/test_resultstracker.py
st2common/st2common/query/base.py
st2common/st2common/runners/utils.py
st2common/st2common/services/executions.py
st2common/tests/unit/test_executions_util.py
st2common/tests/unit/test_runners_utils.py

When action runner is shutdown, any liveactions that are still running will be abandoned. On abandon, the runner's post run method is not called so operations such as callback is not performed. In the case of Mistral, since callback is not performed, Mistral does not know that the task has completed and so the workflow is stuck in running state.

Fix mistral abandoned tasks

---

CHANGELOG.rst
contrib/runners/action_chain_runner/tests/unit/test_actionchain_params_rendering.py
st2common/st2common/util/jinja.py
st2common/tests/unit/test_util_jinja.py

This fixes the issue reported in https://github.com/StackStorm/st2/issues/3421.
```bash
st2 run examples.echochain -d
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 591ef4590640fd4e3d661fc8                                     |
| action.ref      | examples.echochain                                           |
| context.user    | stanley                                                      |
| parameters      |                                                              |
| status          | succeeded …
```

Fix action chain runner so vars and action parameter values support unicode characters

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/unit/controllers/v1/test_executions_simple.py

This pull request updates action executions handler to include user RBAC related information (username and roles) when an execution is scheduled through the API.
It was already previously possible to retrieve user roles inside the action / workflow, but it was more convoluted and involved more steps since user needed to write a custom action which hits StackStorm API to retrieve current user roles.
This also meant one additional task / action inside the workflow chain now it's possible to reference it using ``action_context`` context (e.g. ``action_context.rbac.roles``) which is available to actions and action parameters.
Example action execution context when RBAC is enabled:
```json
{
"user": "multiple_roles",
"rbac": {
"user": "multiple_roles",
"roles": ["admin", "role_1", "role_2", …
```

Include RBAC related info in action context when running action through the API

---

st2common/st2common/rbac/syncer.py
st2common/tests/unit/test_rbac_syncer.py

This pull request fixes a bug in the RBAC remote group to StackStorm role syncer feature which is to be released in v2.3.0.
We didn't correctly handle an edge case where there are no mappings for groups a particular user is a member of. If this user had some previous remote assignments based on the mappings and the mapping has been deleted, previous / existing role assignments wouldn't get deleted on next sync because we incorrectly bailed out early in the code.
Note: This has been caught and reported one of our users who tested this feature in an early stage before the release.

Fix a bug with RBAC remote role assignments syncer when no local mappings exist

---

CHANGELOG.rst
conf/st2.dev.conf
conf/st2.tests.conf
contrib/runners/mistral_v2/query/mistral_v2.py
st2common/st2common/config.py
st2common/st2common/query/base.py
st2common/tests/unit/test_query_base.py
st2tests/integration/mistral/test_wiring.py
st2tests/st2tests/config.py
st2tests/st2tests/fixtures/packs/runners/test_querymodule/query/test_querymodule.py

This issue came up in st2cicd003 box where a bunch of workflows are stuck in RUNNING state (mistral <-> st2 integration bug, suspected to be addressed by https://github.com/StackStorm/st2/pull/3412). The results tracker keep querying the status of these workflows forever and doesn't bail. The CPU is constantly at 100% on the box. 
We seem to be querying mistral state over and over again for 9 workflows stuck in RUNNING. On an average, it takes some queries 3s to complete. We make a query every 1s i.e. if I query and I realized that the query didn’t clear the state, it goes back to the queue and we check if current_time - last_query_time > 1 (query_interval). If yes, we re-query. So we were constantly chugging CPU. Unfortunately, the query_interval is hard coded to 1. When I set that to …

Some changes to Mistral querier to get better CPU performance

---

CHANGELOG.rst
st2common/st2common/util/compat.py
st2common/st2common/util/virtualenvs.py
st2common/tests/unit/test_util_compact.py

This pull request works on top of #3338 and adds / changes:
* Moves utility function into `st2common.util.compat` module
* Adds test case for it
* Adds changelog entry

Prevent UnicodeDecodeErrors on stdout/stderr when packs.setup_virtualenv fails

---

CHANGELOG.rst
st2common/st2common/rbac/syncer.py
st2common/st2common/services/rbac.py
st2common/tests/unit/services/test_rbac.py
st2common/tests/unit/test_db_rbac.py
st2common/tests/unit/test_rbac_syncer.py

This pull request updates `st2-apply-rbac-definitions` tools so it also removes role assignments from the database for users which don't exist in the database.
Before that change we already supported pre-creation of role assignments, meaning user could write role assignments for users which don't yet exist in the database and those assignments would get stored in the database (StackStorm user accounts are lazy created on first successful authentication with st2auth).
We didn't do that for removal (we only removed assignments for users which exist in the database) so the behavior was inconsistent (there are no negative security implications because assignments existing in the database for non-existent user is basically the same as if assignments wouldn't exist).

Update st2-apply-rbac-definitions to remove assignments from database for users which don't exist in the database

---

contrib/examples/actions/chains/forloop_chain.yaml
contrib/examples/actions/forloop_chain.yaml
contrib/examples/actions/forloop_get_github_page.yaml
contrib/examples/actions/forloop_increase_index_and_check_condition.yaml
contrib/examples/actions/forloop_parse_github_repos.yaml
contrib/examples/actions/forloop_push_github_repos.yaml
contrib/examples/actions/pythonactions/forloop_get_github_page.py
contrib/examples/actions/pythonactions/forloop_increase_index_and_check_condition.py
contrib/examples/actions/pythonactions/forloop_parse_github_repos.py
contrib/examples/actions/pythonactions/forloop_push_github_repos.py
contrib/examples/requirements.txt

This is an example chain for a job that needs to be done in several steps because the bulk of each of the passes is bottlenecked (in the case I found, arguments between python calls cannot exceed 131072 characters). The "get_data" and the "push_data" actions can be from different packs if need be if they have support for "paging" on their requests.
If this feels valuable I could write something up more detailed as a blogpost to show how each of the steps work and post an example run and why anyone would want to use it. In this case, this is how it looks for now:

Create forloop chain in the example pack

---

st2tests/integration/mistral/test_errors.py
st2tests/integration/mistral/test_wiring.py

Increase sleep time in one of the test to ensure there's enough time for the test to cancel the sub-workflow.

Minor fix to mistral itests

---

CHANGELOG.rst
st2actions/st2actions/worker.py
st2actions/tests/unit/test_worker.py

On action runner shutdown, item in the _running_liveactions set is removed twice, once during the abandon process and a second time on completion of _run_action.

Fix duplicate remove from running liveactions set

---

Makefile
circle.yml

@lakshmi-kannan added timing related stuff a while ago, but it wasn't enable on Circle CI so we didn't get any per test-case timing.
This should make it easier to debug some test slowness on Circle CI.

Display per test-case timing information on Circle CI

---

.circle/install-and-run-mongodb.sh
circle.yml
st2api/tests/integration/test_gunicorn_configs.py
st2api/tests/unit/controllers/v1/test_packs.py
st2common/st2common/util/virtualenvs.py
st2common/tests/unit/test_virtualenvs.py
st2tests/st2tests/fixtures/packs/dummy_pack_2/requirements.txt

This pull request contains speed ups for various "offensive" tests which took a long time.
For information on how speed ups were achieved, please refer to the actual git commit messages and code changes (and ask for clarification, if needed).
Before
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ nosetests --with-timer --nocapture -v st2common/tests/unit/test_virtualenvs.py
test_setup_pack_virtualenv_already_exists (tests.unit.test_virtualenvs.VirtualenvUtilsTestCase) ... ok (8.5302s)
test_setup_pack_virtualenv_doesnt_exist_yet (tests.unit.test_virtualenvs.VirtualenvUtilsTestCase) ... ok (5.0522s)
test_setup_virtualenv_invalid_dependency_in_requirements_file (tests.unit.test_virtualenvs.VirtualenvUtilsTestCase) ... ok (10.7242s)
test_setup_virtualenv_update …
```

Various test speed ups

---

.circle/install-and-run-mongodb.sh
CHANGELOG.rst
st2common/st2common/models/db/action.py
st2common/st2common/models/db/actionalias.py
st2common/st2common/models/db/execution.py
st2common/st2common/models/db/keyvalue.py
st2common/st2common/models/db/liveaction.py
st2common/st2common/models/db/policy.py
st2common/st2common/models/db/rbac.py
st2common/st2common/models/db/rule.py
st2common/st2common/models/db/rule_enforcement.py
st2common/st2common/models/db/sensor.py
st2common/st2common/models/db/trigger.py
st2common/tests/unit/base.py

I was looking into speeding up tests and decided to run mongodb with `--notablescan` option to find out if we have any queries which result in table scans (aka index not being used).
It turns out we do indeed have such offenders.
This pull request adds missing indexes which should speed up some queries in production installations with a lot of data.
Going forward, I would propose running MongoDB on Circle CI with `--notablescan` option. This will immediately let us know if we are missing an index since a query which would result in a table scan and as such the test case itself will fail.
Based on top off #3465 (once that PR is approved and merged the diff will look much saner).

Add missing indexes

---

CHANGELOG.rst
st2common/st2common/util/config_loader.py
st2common/tests/unit/test_config_loader.py
st2tests/st2tests/fixtures/packs/configs/dummy_pack_5.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_5/config.schema.yaml

This pull request updates config loader to use a default value from config schema for a particular config item is used and set even if that item is not required (``required: false``).
For more details and context, see #3468.
I believe this should have no negative / breaking impact. 
Resolves #3468.

Use default value from config schema even if config item is not required

---

CHANGELOG.rst
Makefile
test-requirements.txt

I also added rstcheck Make target which runs on Circle CI on every build.
This will prevent such issues from happening in the future - https://github.com/StackStorm/st2docs/pull/521#issuecomment-308170615.

Fix syntax in changelog.rst, validate changelog rst file syntax on CI

---

CHANGELOG.rst

Same as https://github.com/StackStorm/st2/pull/3483, but for v2.3 branch.

Update release date (v2.3)

---

CHANGELOG.rst
st2client/st2client/commands/action.py

This pull request updates `st2 run` / `st2 execution run` CLI command to display a result of workflow actions when execution finishes.
In this case result refers to the result of the last task (action) inside the workflow.
This saves some typing because before that you need to do something like that to retrieve result of a workflow:
```bash
st2 run examples.workflow
.... wait
st2 execution get <execution id of last task in the workflow>
```
Before:
After:
Resolves #3476

Display result for workflow actions on completion when using st2 run command

---

st2common/st2common/models/db/liveaction.py
st2common/st2common/models/db/rbac.py

This field can contain more than 1024 bytes of data so regular index won't work - we need to use a hashed one.

Fix context field index

---

CHANGELOG.rst
contrib/runners/python_runner/python_runner.py
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2tests/st2tests/resources/packs/pythonactions/actions/non_simple_type.py

@tonybaloney reported this issue (user unfriendly behavior) on Slack.
Right now, if Python runner actions returns a result which can't be serialized (e.g. non complex type such as class instance, datetime object or similar), Python runner will "silently" swallow this issue and simply return `None` as the result.
This is obviously very unfriendly and confusing.
The code change I included just logs a message and still returns `None`, but I think a better and more user-friendly approach is to simply throw a very explicit and user-friendly error message - something along the lines of "Failed to de-serialize action result, it most likely contains a non-simple type or similar, see docs at YYY on info on Python runner action results".
The thing is if we can't serialize and de-serialize the …

Python runner should throw / log an error when failing to de-serialize action result

---

st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/base.py
st2api/tests/unit/controllers/v1/test_executions.py
st2api/tests/unit/controllers/v1/test_executions_auth.py
st2api/tests/unit/controllers/v1/test_executions_descendants.py
st2api/tests/unit/controllers/v1/test_executions_rbac.py
st2api/tests/unit/controllers/v1/test_executions_simple.py
st2common/st2common/openapi.yaml

Allow action executions to be updated over API. The API will only allow status and result to be updated for incomplete action executions. This patch is required for 1) mistral->st2 callback on workflow completion and 2) st2 response to update st2.ask action execution.

Add PUT method to action executions API

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_action_alias.py
st2common/st2common/openapi.yaml
st2tests/st2tests/fixtures/generic/aliases/alias7.yaml

While working on that, I also noticed a bunch of other OpenAPI definitions for query parameter filters are wrong. They declare param type as array, but it should actually be a string (it's probably due to copy and paste because in one place we support an array, but in others we don't).
It works out of pure luck because we don't do strict query param validation in all the places.  This needs to be fixed in a separate PR.
For example:
```yaml
- name: name
in: query
description: Entity name filter
type: array
items:
type: string
```
Reported by @LindsayHill.

Fix name query param filter for /v1/actionalias API endpoint

---

CHANGELOG.rst
st2api/st2api/controllers/resource.py
st2api/st2api/controllers/v1/auth.py
st2api/tests/unit/controllers/v1/test_auth_api_keys.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/openapi.yaml
st2common/st2common/persistence/auth.py

Addresses: https://github.com/StackStorm/st2/issues/3369
```
$  curl -v -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.14.2' -H  'X-Auth-Token: <token>' 'http://127.0.0.1:9101/v1/apikeys/?limit=1'
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9101 (#0)
> GET /v1/apikeys/?limit=1 HTTP/1.1
> Host: 127.0.0.1:9101
> Connection: keep-alive
> Accept-Encoding: gzip, deflate
> Accept: */*
> User-Agent: python-requests/2.14.2
> X-Auth-Token: <token>
>
< HTTP/1.1 200 OK
< Server: gunicorn/19.6.0
< Date: Fri, 16 Jun 2017 16:15:07 GMT
< Connection: keep-alive
< Content-Type: application/json
< Content-Length: 245
< X-Total-Count: 2
< X-Limit: 1
< Access-Control-Allow-Origin: http://127.0.0.1:3000
< …
```

Add pagination support for /api/v1/apikeys endpoints

---

CHANGELOG.rst
contrib/runners/action_chain_runner/action_chain_runner.py
contrib/runners/action_chain_runner/runner.yaml
contrib/runners/action_chain_runner/tests/unit/test_actionchain.py
st2tests/st2tests/fixtures/generic/actionchains/chain_with_publish_2.yaml

We added functionality to the action-chain runner to store and displayed intermediate published variables quite a while ago.
This functionality was controlled via `display_published` runner parameter which had a default value of `False`.
It looks like default Mistral runner behavior is to display published variables (#3518) so it makes sense to also make action-chain runner store and display it by default for consistency reasons.

Update action-chain runner to display published variables by default

---

CHANGELOG.rst
contrib/runners/remote_script_runner/runner.yaml
st2actions/tests/unit/test_paramiko_ssh_runner.py

It looks like remote shell script runner was missing `passphrase` parameter and as such, password / passphrase supported private SSH key files were not supported (remote command runner supports it just fine).

Add missing passpharse argument to the remote script runner

---

CHANGELOG.rst
st2common/st2common/util/config_loader.py
st2common/tests/unit/test_config_loader.py
st2tests/st2tests/fixtures/packs/dummy_pack_17/config.schema.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_17/config.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_17/pack.yaml

This pull request works on top of #3504.
I decided to start with the test approach (failing test) and work from there to be sure we don't introduce any regressions.
Instead of using `setdefault` which caused a bunch of other issues with tests I decided to go with a "magic" value which is very unlikely to appear in the config as a default value or otherwise.

Update config loader to correctly handle default values which are falsey (None, False, {}, etc.)

---

CHANGELOG.rst
st2common/st2common/content/bootstrap.py
st2common/st2common/script_setup.py
st2common/st2common/triggers.py

The should fix the race issue described in https://github.com/StackStorm/st2-packages/issues/445.
Previously we didn't register internal trigger types inside this script so if user ran this script before any of the service which register them was started (e.g. st2api, st2stream, etc.) and rules were to be registered, the script would fail with "Failed to create trigger" error.
More context and explanation in https://github.com/StackStorm/st2-packages/issues/445 and https://github.com/StackStorm/st2/pull/3538#discussion_r125071929.

Register internal trigger types in the init / setup phase of st2-register-content script

---

CHANGELOG.rst
st2client/st2client/commands/action.py
st2client/st2client/commands/policy.py
st2client/st2client/commands/rbac.py
st2client/st2client/commands/resource.py
st2client/st2client/commands/rule.py
st2client/st2client/commands/rule_enforcement.py
st2client/st2client/commands/timer.py
st2client/st2client/commands/trace.py
st2client/st2client/commands/triggerinstance.py
st2client/st2client/formatters/table.py
st2client/st2client/models/core.py
st2client/tests/base.py
st2client/tests/unit/test_commands.py
st2client/tests/unit/test_formatters.py
st2client/tests/unit/test_models.py
st2client/tests/unit/test_shell.py

Changes:
```
$ st2 rule list
+---------------------------------+--------+---------------------------------+---------+
| ref                             | pack   | description                     | enabled |
+---------------------------------+--------+---------------------------------+---------+
| github.deploy_pack_on_deploymen | github | Trigger an ST2 pack.install     | False   |
| t_event                         |        | when receiving a deployment     |         |
~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~
| st2cd.st2_pkg_test_stable_u16_e | st2cd  | Test stable packages            | True    |
| nterprise                       |        |                                 |         |
+---------------------------------+--------+---------------------------------+---------+ …
```

Add "Note" in the CLI if API has default query "limit=50" and update rule endpoint help

---

CHANGELOG.rst
st2common/st2common/middleware/logging.py

When moving to API v2.0 we changed the code to always log whole API responses (raw data returned by the controller method) if API endpoint doesn't explicitly declare `x-log-result: True` attribute (we did this for API endpoints which return a lot of data).
I think better way to handle that is to log responses under `DEBUG` level. That's what we did in the past and logging it under `INFO` causes too much log clutter and makes it easier to miss more important messages.

Log API responses under DEBUG log level instead of INFO

---

st2api/st2api/cmd/api.py
st2common/st2common/log.py
st2common/st2common/service_setup.py
st2common/tests/unit/test_service_setup.py

This pull request updates logging code to print a more user-friendly error message in case user selected an invalid log message.
In addition to that, I noticed existing code overwrote original exception class and always re-threw `Exception`. This pull request fixes that and preserves class of the original exception.
Resolves #3513.

Print more user-friendly exception on invalid log level

---

CHANGELOG.rst
st2actions/st2actions/container/base.py
st2common/st2common/config.py
st2common/st2common/services/datastore.py
st2reactor/st2reactor/container/process_container.py

Fixes #3523 
Datastore should get its TTL from the configured max instead of hard-coded value. Without this change if `token_ttl` is set to a value `<` the default any python action that access the data service will throw an error.

Datastore Service - Get Token TTL from configured max

---

CHANGELOG.rst
st2client/st2client/formatters/execution.py
st2client/st2client/formatters/table.py
st2client/st2client/utils/strutil.py
st2client/tests/unit/test_util_strutil.py

Fixes: https://github.com/StackStorm/st2/issues/3510
See https://mail.python.org/pipermail/python-list/2006-January/411909.html. 
TODO
Test cases without any code change:
```
======================================================================
ERROR: test_unicode_with_line_feed_like_chars (tests.unit.test_util_strutil.StrUtilTestCase)
----------------------------------------------------------------------
File "/mnt/src/storm/st2/st2client/tests/unit/test_util_strutil.py", line 38, in test_unicode_with_line_feed_like_chars
out_str = unescape(in_str)
File "/mnt/src/storm/st2/st2client/st2client/utils/strutil.py", line 20, in unescape
if isinstance(s, basestring) else s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 0: …
```

Support unicode with line feed in CLI print 

---

CHANGELOG.rst
contrib/packs/actions/pack_mgmt/download.py
contrib/packs/tests/test_action_download.py
st2common/tests/unit/test_pack_management.py

Fixes https://github.com/StackStorm/st2/issues/3534
Closes https://github.com/StackStorm/st2/pull/3544
This pull request works on top oif #3544 and adds a changelog entry and updates affected tests so the change will be ready in time for v2.3.2 release.

Fix git url mangling in packs.download action

---

.travis.yml
Makefile
circle.yml
test-requirements.txt

> Related to https://github.com/StackStorm/st2ci/issues/94
Resulting config from the https://github.com/armab/st2/pull/3 prev. week experiments to improve the unit+integration test timing.
The build timing is now `7-10mins` for unit + integration + lint checks, comparing to old `25-30mins`.
As suggested 1yr. ago https://github.com/StackStorm/discussions/issues/143#issuecomment-184856516  avoid putting all eggs in Circle which was there only for packaging because of really advanced and unique features. But we don't need all that + cryptic UI for unit + integration tests. Also we'll suffer from the queue.
---
This change is the part of the bigger game/plan, but for now it's experimental and I'm not changing any workflows yet. Just seeing how it behaves under the load. We'll see just another …

Incorporate unit + integration test experiments (timing improvement)

---

circle.yml

Experimenting with CircleCI2.0.
With the other timing experiments https://github.com/StackStorm/st2/pull/3545, we're trying to understand if Circle2.0 would work somehow faster/easier.
With 2.0 hope to get: 
Respective `docker-compose` workarounds: https://github.com/StackStorm/st2-packages/pull/467 to make 2.0 working.

Experimental/circle 2.0 st2-packages (timing improvements) (executorType: Docker)

---

CHANGELOG.rst
lint-configs/python/.pylintrc

Ignore `mistralclient.api.v2.executions` module to prevent `no-member` error on later versions of python (as used in u16)

pylint ignore mistralclient.api.v2.executions

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_rules_rbac.py
st2common/st2common/rbac/resolvers.py
st2common/st2common/rbac/types.py
st2common/st2common/rbac/utils.py
st2tests/st2tests/fixtures/generic/rules/rule_action_doesnt_exist.yaml

This pull request fixes a bug which didn't allow users to create rules via API which reference actions which don't exist in the system.
In theory, we didn't really have any hard defined rules around that (allowing user to create rules which reference actions which don't exist in the system), but since when RBAC is not enabled, we allow user to do that, we should also allow that when RBAC is enabled.
Either that, or we shouldn't allow rules which reference an action which doesn't exist in the system to be created in both scenarios.
Resolves #3572.

Allow users to create rules which reference actions which don't exist in the system when RBAC is enabled

---

.travis.yml

A few days ago Travis moved from `precise` to `trusty` as a base distro OS for environment we use.
After a quick look Unit tests were running x2 slower in new distro.
NEW `trusty` (slower, `12-15mins`):
https://travis-ci.org/StackStorm/st2/jobs/254995061
OLD `precise` (faster, `6-7mins`):
https://travis-ci.org/StackStorm/st2/jobs/254770338
Switching back to `precise`.
----
On related note, this could be a reason why CircleCI was slower for Unit tests, - because of base distro.
I'll need to try CircleCI Unit tests in Precise env to see if that improves the timing.

Use 'precise' distro for Travis, which runs x2 faster to Trusty

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_policies_rbac.py
st2api/tests/unit/controllers/v1/test_rules.py
st2common/st2common/router.py
st2tests/st2tests/fixtures/generic/policytypes/fake_policy_type_3.yaml

This is a stop gap for regression described in #3575 until we implement a long term solution described in that issue (making sure each openapi entity definition contains corresponding JSON schema which is generated and copied over from API model schema attribute).
It should fix the regression (we didn't perform any API validation for endpoints which didn't have entity json schema defined in openapi.yaml).
The code basically does what we did before move to API v2, but we still need to be careful it doesn't break something.
While working on that, I thought we should actually still call `model.validate()` inside the router when performing API input data validation, even when we automatically generate and move all JSON schema definitions to openapi.yaml.
The reason for that is that …

Perform API input data validation using API model definitions

---

st2client/tests/unit/test_app.py

Pulling a small Unit tests fix from the https://github.com/StackStorm/st2/pull/3587
Wrong assumption that user's home would be always '/home/username/'.
```
AssertionError: '/root/.st2/config.ini' != '/home/root/.st2/config.ini'
```

Fix 'test_cli_config_file_path' unit test for 'root' user

---

st2client/st2client/utils/interactive.py

I found a very trivial problem with the processing to show a message in the st2client, and fixed it.
I got following message which is (maybe) not intended format by the configuration command in some pack (e.g. `acos`).
```
$ st2 pack config acos
('%s. Skipping...', 'Interactive mode does not support arrays of object type yet')
```
I fixed it to substitute variable. By this change, the above output message will be as follows.
```
$ st2 pack config acos
Interactive mode does not support arrays of object type yet. Skipping...
```

Fixed a very trivial problem with the processing to show a message

---

st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/router.py

This resulted in unit tests not catching a number of obvious validation errors.

Fix Error definition being too lax

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/unit/controllers/v1/test_executions.py

When liveaction reference an action that does not exists, the POST to action execution results in a 500 internal server error. The error should be 400 bad request. A check is added to check that the action_db is not type of NoneType before proceeding.

Fix post to action execution with nonexistent action

---

circle.yml

Share the `st2` package logs, even if Packaging Test failed.
Helps in troubleshooting failed builds like https://github.com/StackStorm/st2/pull/3597 by sharing `st2` logs as CircleCI artifacts.

Share the st2-package smoketests logs, even if Test failed

---

st2client/st2client/utils/interactive.py
st2client/tests/unit/test_interactive.py

I implemented a ArrayObjectReader for InteractiveForm in the st2client to set configuration from the schema of array which has elements of dicts interactively.
As [enykeev said](https://github.com/StackStorm/st2/pull/2964#issuecomment-254734078), the InteractiveForm of st2client has a restriction that couldn't set configuration from the `array of objects` type.
By this restriction, some pack (e.g. [git](https://github.com/StackStorm-Exchange/stackstorm-git), [napalm](https://github.com/StackStorm-Exchange/stackstorm-napalm) and [acos](https://github.com/StackStorm-Exchange/stackstorm-acos)) couldn't interactively set complete configuration by `st2 pack config` command.
I implemented another Reader that dedicate to set configuration sets continuously from the schema of `array of objects` …

[st2client] Implemented ArrayObjectReader to set configuration interactively from the schema of array which has elements of object type.

---

CHANGELOG.rst
contrib/examples/actions/chains/invoke_mistral_with_jinja.yaml
contrib/examples/actions/invoke_mistral_with_jinja.yaml
contrib/runners/mistral_v2/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_v2.py
st2common/st2common/util/jinja.py
st2common/st2common/util/workflow/mistral.py
st2common/tests/unit/test_util_jinja.py
st2tests/integration/mistral/test_wiring.py

If the parent action chain contains jinja expression in the execution parameters, the jinja expression will be included in the context begin passed into the Mistral subworkflow. Mistral will try to evaluate the expression when it is evaulating input args and if the expression contains references to local data context, the evaulation fails because the data context is already out of scope. This patch converts the jinja expression into raw jinja blocks when passing thru the context.

Fix invocation of Mistral workflow from Action Chain

---

contrib/runners/mistral_v2/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_v2.py

When converting the jinja expression in the raw blocks in Mistral runner for a parent Action Chain, check for NoneType in the context dictionary.

Check for NoneType when converting Jinja to raw blocks in Mistral runner

---

conf/st2.conf.sample

The `[resultstracker] query_interval` option was added st2. It was documented in the changelog but was not added to `st2.conf.sample`. This adds it to `st2.conf.sample`

Added [resultstracker] query_interval to st2.conf.sample

---

CHANGELOG.rst
conf/logrotate.conf

This is a fix for https://github.com/StackStorm/st2/issues/3633
The following updates have been made:
1. Redirect `stdout` to `/dev/null` for every `st2ctl reopen-log-files` command
2. Added `missingok` to `/var/log/st2/st2web.log` because this file does not seem to be created (at least on my Red Hat test box)

Quieted logrotate script

---

CHANGELOG.rst
st2common/st2common/transport/bootstrap_utils.py

Various transport util fixes:
1. Fix usage of `retrying` library inside `register_exchanges_with_retry` function. We incorrectly passed in an exception for `retry_on_exception` argument which actually expects a callable.
Part of #3635.

Transport util fixes

---

CHANGELOG.rst
conf/st2.conf.sample
st2common/st2common/config.py
st2common/st2common/transport/bootstrap_utils.py
st2common/tests/unit/test_service_setup.py

This pull request adds ability to predeclare all the used message bus queues (and as such, exchanges) on service startup and allows users to use other non-RabbitMQ kombu transports which are not officially supported.
#3635 inspired me to dig in a little to try to find out what is going on. After spending whole morning digging in and tracking what is going on, I managed to track down the root cause on why Redis kombu transport doesn't work.
#3638 fixed a small issue which was just related to retrying and error propagation, but the fix for the actual root cause of things not working is included in this PR.
When trying to use Redis kombu transport instead of RabbitMQ one, you got an error like this on each service start up:
```bash
2017-08-02 10:35:44,107 ERROR [-] Rabbitmq connection error: …
```

Add ability to pre-declare all the used message bus queues on service startup (allow users to use non RabbitMQ kombu transports)

---

circle.yml

Fixes https://github.com/StackStorm/st2ci/issues/94
Related changes:
Remove Unit + Integration tests from CircleCI, - after experiment we decided to go with Travis due to timing reasons for such tests.
Check what's needed from https://github.com/stackstorm/st2ci to trigger `e2e` stackstorm tests once the packages are ready.

Trigger e2e tests for PRs

---

st2common/st2common/log.py
st2common/st2common/logging/filters.py
st2common/st2common/logging/misc.py
st2common/st2common/util/debugging.py

This pull request improves various debug mode related logging:
1. When debug mode is enabled, also set paramiko and kombu logger level to `DEBUG`
2. When `disable_logging` function is called, actually reset logger levels back to `INFO`
3. When debug mode is enabled, don't filter out all log messages using level `DEBUG` generated by `pyamqp`, but only the ones generated by `heartbit_tick` function which is called every 2 seconds. Disabling all the DEBUG messages means we lose some valuable debugging information.

Various debug mode logging improvements

---

CHANGELOG.rst
conf/logrotate.conf

In #2898 we modified the logrotate configuration to be more specific about the stale st2actionrunner log files we were deleting. This was good, because it fixed the problem with mysteriously disappearing st2actionrunner-related files.
However we are now too specific. 
This line:
```sh
find /var/log/st2/ -type f -name "st2actionrunner*.log" -mtime +30 -exec rm -f {} \;
```
will delete stale st2actionrunner.<pid>.log files that might have been left behind after an ST2 restart.
However if there are older compressed files that logrotate had previously created, such st2actionrunner.<oldpid>.log.gz, then they will not be matched by the `find` statement. Any <newpid> files will be maintained by logrotate, rotated daily, with files older than 5 days deleted. But if ST2 is restarted, we get …

Also delete compressed stale actionrunner logs

---

circle.yml

Associated change in st2-packages: https://github.com/StackStorm/st2-packages/pull/481
Recently we got more failed builds. After more investigation it was "No space left on device" errors which resulted that `mongodb`, `rabbitmq`, `postgresql` failed to start.
See: https://discuss.circleci.com/t/no-space-left-on-device-while-creating-mongo/11532/13 for more context.
Fixing "No space left on device" in CircleCI infrastructure via additional Cleanup, caused by volumes persisting between the builds.

Fix CircleCI docker volumes cleanup

---

st2common/st2common/transport/bootstrap_utils.py

Exporter is an optional service which is off / disabled by default. This means there are no consumers by default and having a queue pre-declared means it will grown until someone starts consuming from it.
In short - not pre-declaring this queue is not a problem as long as we only have exporter consuming from that queue.
Resolves #3651.

Don't pre-declare exporter queue on service startup.

---

CHANGELOG.rst
st2api/st2api/controllers/v1/traces.py
st2api/tests/unit/controllers/v1/test_traces.py
st2client/st2client/commands/trace.py

Fixes https://github.com/StackStorm/st2/issues/3237
Before:
```
$ st2 trace list -n 8 -s desc
+--------------------------+-------------------------------------+-------------------------------------+-------------------------------+
| id                       | uid                                 | trace_tag                           | start_timestamp               |
+--------------------------+-------------------------------------+-------------------------------------+-------------------------------+
| 598de263909a50671f647460 | trace:ce4402928eaaf5d73b726c9e6f93c | trigger_instance-                   | Fri, 11 Aug 2017 16:59:15 UTC |
|                          | fcf                                 | 598de263909a50671f64745f            |                               |
| …
```

Fix: Sort order for trace API endpoint

---

st2api/tests/base.py
st2common/st2common/constants/types.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/rbac/resolvers.py
st2common/st2common/rbac/types.py
st2stream/st2stream/controllers/v1/stream.py
st2stream/tests/unit/controllers/v1/base.py
st2stream/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
st2stream/tests/unit/controllers/v1/test_stream.py
st2tests/st2tests/api.py

I decided to pick some fixes and improvements from #3657, base them on top of master and include them as separate PRs.
This will make #3657 a bit small and easier to review. This way I can also ensure some of those changes make it in v2.4.0 in case #3657 won't be merged in time for v2.4.0.
This pull request fixes a bug and adds missing RBAC check to `/v1/stream` API endpoint. In addition to that, it also includes some tests refactoring to reduce code duplication and make some base test classes possible to re-use between different packages.

Add missing RBAC check to /v1/stream API endpoint

---

CHANGELOG.rst
st2client/st2client/models/core.py
st2stream/st2stream/controllers/v1/stream.py
st2stream/st2stream/listener.py
st2stream/tests/unit/controllers/v1/test_stream.py

I decided to pick some fixes and improvements from #3657, base them on top of master and include them as separate PRs.
This will make #3657 a bit small and easier to review. This way I can also ensure some of those changes make it in v2.4.0 in case #3657 won't be merged in time for v2.4.0.
This pull request adds server side filtering based on the event name, action ref and execution id to the ``/v1/stream`` endpoint. In addition to that, it updates st2client to use server-side filtering instead of doing client side based filtering.
As mentioned above, this change was originally added because it was needed in #3657, but it's something which is generally useful outside of #3657 and this way it's also easier to review it.
As mentioned and discussed on Slack - more efficient way to do server …

Server side event filtering for /v1/stream API endpoint

---

CHANGELOG.rst
st2common/st2common/bootstrap/base.py
st2common/st2common/util/config_loader.py
st2common/tests/unit/test_config_loader.py

The feature to use the local config.yaml in packs is removed. The config.yaml is deprecated and replaced by the config schema in earlier version.
On content loading in bootstrap, the warning message is replaced with the following error message.
2017-08-17 19:48:50,326 ERROR [-] Pack "demo" contains a deprecated config.yaml file (/opt/stackstorm/packs/demo/config.yaml). Support for "config.yaml" files has been deprecated in StackStorm v1.6.0 in favor of config.schema.yaml config schema files and config files in /opt/stackstorm/configs/ directory. Support for config.yaml files has been removed in the release (v2.4.0) so please migrate. For more information please refer to https://docs.stackstorm.com/reference/pack_configs.html

Remove local pack config

---

CHANGELOG.rst
contrib/packs/actions/load.yaml

Our [AWS pack](https://github.com/stackstorm-exchange/stackstorm-aws) ballooned into `3581` actions which sometimes results in `st2 pack install aws` failures on slower systems (reported in #community).
For now "temporary" increasing pack register timeout.
The proper fix is to investigate the performance and research the pack content registration optimizations 
StackStorm by design should handle big packs https://github.com/StackStorm/st2/issues/3686.
Also there is a related cosmetic enhancement https://github.com/StackStorm/st2/issues/3586 which helps to additionally signalize if there is a *huge* amount of content in a pack.

Increase 'pack register content' timeout

---

st2client/st2client/models/core.py

On pack install, the command listens for event from the API server. If the execution takes too long, the SSEClient which listens for events on the client side returns an empty string which leads to JSON load error.

Fix timeout listening for events with client side async execution

---

CHANGELOG.rst
st2api/st2api/controllers/v1/packs.py
st2api/tests/unit/controllers/v1/test_packs_rbac.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

This pull request fixes a bug with not honoring the user which performed the API operation when scheduling an execution for pack install and pack uninstall in those two corresponding API endpoints.
This means that instead of the user which performed API operation, system user (stanley) was used for those scheduled executions.
This is a regression which was introduced when we moved from scheduling executions directly for pack install and uninstall to the new API.
Thanks to @theuiz for catching and reporting this.
Resolves #3693.

Fix a bug with API user not being honored in /v1/packs/install and /v1/packs/uninstall API endpoints

---

CHANGELOG.rst

- Syntax fixes (Markdown style single backquote switched to RST double backquote)
- Minor language improvements/clarifications
- Moved a couple of recent items to appropriate sub-heading (Changed/Deprecated)

Changelog formatting and language tidyup

---

CHANGELOG.rst
st2client/st2client/shell.py
st2client/tests/unit/test_shell.py

Before:
```bash
st2
usage: shell.py [-h] [--version] [--url BASE_URL] [--auth-url AUTH_URL]
[--api-url API_URL] [--stream-url STREAM_URL]
[--api-version API_VERSION] [--cacert CACERT]
[--config-file CONFIG_FILE] [--print-config] [--skip-config]
[--debug]
{action,action-alias,auth,apikey,execution,key,login,pack,policy,policy-type,rule,run,runner,sensor,trace,trigger,trigger-instance,webhook,whoami,timer,rule-enforcement,role,role-assignment}
...
shell.py: error: too few arguments
```
After:
```bash
st2
usage: Usage: st2 [options] {command} [options]
For example:
st2 action list --pack=st2
st2 run core.local cmd=date
st2 --debug run core.local cmd=date
CLI for StackStorm event-driven automation platform. https://stackstorm.com
positional arguments: …
```

Update CLI to print more user-friendly help string if no argument is provided

---

st2client/st2client/commands/action.py
st2client/tests/unit/test_command_actionrun.py

This is the correction based on [the suggestion from Kami](https://github.com/StackStorm/st2/pull/3670/files#r134171370).
This patch corrects the `_get_action_parameters_from_args` method, which parses `array of dicts` value from the command-line arguments, to parse each values in the object as the type which is specified in the action metadata.

[st2client] Corrected the implementation of transformer of array to parse the values in object as the type which is specified in the action metadata

---

CHANGELOG.rst
contrib/runners/mistral_v2/callback/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_v2_callback.py

When result of action execution contains unicode, Mistral callback fails and leads to orphaned workflow execution.

Fix mistral callback failure when result contains unicode

---

.travis.yml

This should fix cases when travis caches pip installs from https://github.com/StackStorm/st2/blob/master/requirements.txt#L9 when the target `master` branch code was actually updated (happened in https://github.com/StackStorm/st2/pull/3721).
Pull Request caches rely first on `master` branch: https://docs.travis-ci.com/user/caching/#Pull-request-builds-and-caches  So we won't cache `master` branch anymore. It means first build for every PR comes with no cache.
There is also no way to invalidate the cache at the moment once the content is changed in remote git, except of pip upgrade or version change in pip package. See reports in pip:
- https://github.com/pypa/pip/issues/2837
- https://github.com/pypa/pip/issues/2835
Using --editable pip requirements will fix the issue, but it's not …

Fix Travis caching

---

CHANGELOG.rst
st2actions/tests/unit/test_execution_cancellation.py
st2common/st2common/services/action.py

On cancellation request, if the liveaction has a parent, set the status to canceling to trigger post_run for the liveaction. Currently, the action execution is set to canceled and callback to Mistral is not performed, thus leading to workflows stuck in running state.

Fix cancellation of delayed action execution

---

contrib/runners/mistral_v2/tests/unit/test_mistral_v2_auth.py

The interface for the authenticate method has changed. Fix the unit tests associated with the interface change.

Fix call to keystone auth in mistral runner

---

CHANGELOG.rst

Add a changelog entry for the upstream fix on the Mistral slow shutdown issue with systemd service.

Add changelog entry for the fix to Mistral shutdown issue

---

st2client/st2client/commands/action.py

This pull request updates `st2 execution tail` command to just print raw output by default. This way it's consistent with the `/output` API endpoint.
User can also request metadata (timestamp, output type) to be printed by using `--include-metadata` flag.
Without the flag (default behavior):
```bash
st2 execution tail last
stderr -> Line: 1
stdout -> Line: 2
stderr -> Line: 3
stdout -> Line: 4
stderr -> Line: 5
stdout -> Line: 6
stderr -> Line: 7
stdout -> Line: 8
stderr -> Line: 9
stdout -> Line: 10
Execution 59ba7e5d0640fd4f73312076 has completed.
```
With the flag (previous default behavior):
```bash
st2 execution tail last --include-metadata
[2017-09-14T13:07:07.229150Z][stderr] stderr -> Line: 1
[2017-09-14T13:07:08.234801Z][stdout] stdout -> Line: 2 …
```

Update "st2 execution tail" CLI command to just print raw action output by default

---

st2common/st2common/transport/announcement.py
st2common/st2common/transport/execution.py
st2common/st2common/transport/queues.py

The issue with execution output queues used by stream service never getting deleted was caught by deploying v2.5dev on CI server and by @armab, @enykeev.
The issue was that the queue wasn't exclusive.
This pull request fixes that and on top of that, it also makes all queues used by the stream service auto deletable.
We use random queue names for queues used by the stream service, but we don't have `auto_delete=True`. This means that when stream service restart, existing queue will persist, but we will create a new queue on start which will be used by the consumers. This means old queue will be left around, but nothing will ever consume from it again.
Also, as far as I know, we basically want (almost) always use `exclusive=True` and `auto_delete=True` for queues with random names. If we …

Make sure temporary stream output queues get deleted, make all queues used by the stream service auto deletable

---

CHANGELOG.rst
conf/st2.conf.sample
st2actions/tests/integration/test_resultstracker.py
st2common/st2common/config.py
st2common/st2common/query/base.py
st2tests/st2tests/fixtures/packs/runners/test_querymodule/query/test_querymodule.py

Fix delays in st2resultstracker on querying workflow status from Mistral. Make sleep time for empty queue and no workers configurable. Reduce the default sleep times to 1 second. StackStorm instances that handle more workflows should consider increasing the query interval and jitter interval for better CPU utilization. For reference, `make mistral-itest` is reduced from 800+s to 500+s to complete.

Fix delays in st2resultstracker on querying workflow status

---

CHANGELOG.rst
st2common/st2common/stream/listener.py
st2stream/st2stream/controllers/v1/stream.py
st2stream/tests/unit/controllers/v1/test_stream.py

This pull request adds support for glob based event type / name filtering to the `/v1/stream` API endpoint.
In addition to that, it fixes a bug caught by @nzlosh - changes I added for streaming support accidentally filtered out `st2.announcement__errbot` events.
If we decide to officially support and maintain errbot we also need to add automated tests for it which will catch issues like that.
Note: This iteration over a list and glob based filtering might not be the most performant - if this indeed turn out to be a bottleneck at some point in the future, we can always optimize it.
Thanks to @nzlosh for catching and reporting this.

Add support for glob based event type filtering, fix whitelist for /v1/stream API endpoint

---

CHANGELOG.rst
st2client/st2client/commands/auth.py

This pull request fixes a bug / non-consistent behavior reported in #3748.
It updates ``st2 apikey load`` command so it doesn't throw an updates an existing entry if input file contains `id` attribute for an item and item already exists on the server.
This way behavior is also consistent with ``st2 key load`` command.
See https://gist.github.com/Kami/bc7567c6b2b8a62f7680f64921cbf7fc for example output.
Resolves #3748

Update "st2 apikey load" to update an existing entry if one already exists

---

st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

This is a fix for #3783 where the TTL parameter for PUT /api/v1/keys/{name} was missing.
I added the parameter to `st2common/st2common/openapi.yaml.j2` and updated the main definition using `make .generate-api-spec`.
Is there a way, in the future, to auto-generate `st2common/st2common/openapi.yaml.j2` or does this need to be updated manually?

Fix for #3783 - TTL parameter for PUT /api/v1/keys/{name}

---

Makefile
README.md
st2actions/st2actions/config.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/config.py
st2common/st2common/runners/python_action_wrapper.py
st2common/st2common/services/triggers.py

This removes circular dependency on st2actions inside st2common by moving common action runner options to `st2common.config`.
This means `st2common` is now fully standalone and we can re-use it inside `st2client`, our serverless stuff, etc.

Remove st2actions dependency from st2common

---

st2common/in-requirements.txt

A PR recently added new filter, but we forgot to add dependency to st2common/in-requirements.txt.

Add missing jsonpath-rw to st2common in-requirements.txt

---

Makefile
fixed-requirements.txt
requirements.txt
scripts/dist_utils.py
st2actions/dist_utils.py
st2api/dist_utils.py
st2auth/dist_utils.py
st2client/dist_utils.py
st2common/dist_utils.py
st2common/in-requirements.txt
st2debug/dist_utils.py
st2exporter/dist_utils.py
st2reactor/dist_utils.py
st2stream/dist_utils.py
st2tests/dist_utils.py

* tooz requires newer version of `oslo.utils` so we need to update the version
* Add missing greenlet dependency
* Remove `prance` from component `in-requirements.txt` because it depends on a new version of requests (something we can't fulfill atm) Related to https://github.com/StackStorm/st2/issues/3603 https://github.com/StackStorm/st2/issues/3596
* Update dist_utils to include missing functions

Various fixes to make st2common package work standalone

---

st2common/st2common/models/utils/action_alias_utils.py
st2common/tests/unit/test_action_alias_utils.py

The first commit is a tiny fix for regex mangling - it simply changes a non-raw string into a raw string.
The second commit enables more expressive regular expressions in the action alias parser/mangler.
Instead of blindly adding anchors to action alias format regexes, it now searches the existing regex for anchors and does *not* add anchors if it already contains them.
This allows users to create regexes that already contain anchors
```python
re.compile(r"^jira issue {{ issue_key }}$")
```
or regexes that can match multiple times per string, like when you want to find multiple Jira issues in a Slack message:
```python
re.compile(r"(?:^|\b)(?P<issue_key>[A-Z][A-Z0-9]+-\d+)(?:\b|$")
```
I have included tests for the new parse tree searching function.
I will be working to upstream our …

Better regex anchors for upstream

---

CHANGELOG.rst
st2common/st2common/models/db/__init__.py
st2common/tests/unit/test_db.py

Updates the code to not log the MongoDB password in case password is specified as part of the connection host URI string (e.g. ``database.host = mongodb://username:passwordfoo@host1,127.0.0.2:5555``).
Default scenarios is specifying password as a separate ``database.password`` config option. This is still the recommended approach going forward.
Thanks to @emptywee for reporting this.
Resolves #3797.

Don't log MongoDB password if password is included in the hostname as part of the URI string

---

contrib/examples/actions/mistral-test-func-from-json-string.yaml
contrib/examples/actions/mistral-test-func-from-yaml-string.yaml
contrib/examples/actions/mistral-test-func-jsonpath-query.yaml

Some of the workflows for testing custom filters in the mistral integration test are missing meta files.

Add missing meta files for mistral itest workflows

---

CHANGELOG.rst
requirements.txt
st2actions/tests/integration/test_python_action_process_wrapper.py
st2common/in-requirements.txt
st2common/st2common/runners/base_action.py
st2common/st2common/runners/utils.py
st2common/st2common/util/monkey_patch.py

In the past I spent quite a lot of time working on optimizing the run time of simple and short Python runner actions (there was a lot of overhead added by start up time, mostly by some very slow imports).
I managed to get it down to 0.2 seconds or so, but we recently moved some modules around and added some function definitions to some modules which introduced big performance overheads (run time is now back at ~2 seconds).
The reason for that was a broken test - the test which should ensure that we don't introduce performance regressions didn't work correctly because it didn't actually check that the script it tries to run exists (it broke when we moved wrapper script from `st2actions` to `st2common`).
As a first step, I of course fixed this test so things like that won't happen again - …

Fix performance regressions and overhead for Python runner actions

---

CHANGELOG.rst
fixed-requirements.txt

This pull request updates various Python libraries we use to latest stable versions which mostly include bug-fixes.
(Sadly we are still blocked on upgrading eventlet, mongoengine and requests due to some breaking API changes and performance issues)

Upgrade various Python deps to the latest stable versions

---

st2common/st2common/operators.py
st2common/st2common/util/payload.py
st2common/tests/unit/test_operators.py
st2common/tests/unit/test_util_payload.py
st2reactor/st2reactor/rules/filter.py
st2reactor/tests/unit/test_filter.py

This PR adds a `search` operator to StackStorm's rules engine that searches through arrays and compares each element of the array to the child patterns of this operator. It takes a non-optional `condition` parameter that controls how individual items affect the overall match.
Many things are best explained via examples, so here's a few example usages for you:
```yaml
---
criteria:
trigger.fields:
type: search
condition: any  # or all
pattern:
item.field_name:
type: "equals"
pattern: "Status"
item.to_value:
type: "equals"
pattern: "Approved"
```
This example criteria would search through a trigger's `fields` array for a dictionary:
```json
{
"field_name": "Status",
"to_value": "Approved"
}
```
Because the `search` condition was specified as `any`, the following payload would match:
```json …
```

Add a search operator to rules engine

---

CHANGELOG.rst
st2actions/tests/unit/test_runner_container.py

Just a small test case for bug described in https://github.com/StackStorm/st2/issues/3823#issuecomment-342756557.
We should also look into adding a proper "end to end" st2tests test for this, but it will be quite a bit more involved.

Runner container temporary auth token scoping test case

---

st2common/tests/unit/test_operators.py

In PR #3833 I created a `dict_strict_equal` function to compare two dictionaries by key and value.
However, as @Kami [pointed out](https://github.com/StackStorm/st2/pull/3833#discussion_r149641102), I could just use Python's built-in `==` operator (I thought that just compared the results of `id()` for the two dictionaries. Python's built-in equality operator for dicts already does key and value comparisons properly.
This is the PR [that I said I would create](https://github.com/StackStorm/st2/pull/3833#discussion_r149822156) - it removes my `dict_strict_equal` function, the tests I created for it, and refactors `list_of_dicts_strict_equal` to use the built-in `==` instead.
I'm happy to answer any questions or respond to any comments or critiques.

Use Python's built-in '==' instead of rolling our own

---

CHANGELOG.rst
st2common/st2common/services/datastore.py

audit level is used for other purposes.
Part of those changes were community contributed and we probably overlooked the log level being used during a review.
With this change it's now also possible to filter those messages out from Python runner action output by setting `log_level` runner parameter to `info` (only messages with `info` or above log level will be printed).

Change log level for datastore messages from audit to debug

---

CHANGELOG.rst
st2common/st2common/services/datastore.py

Change from #3845 for master (2.6dev).

Change log level for datastore messages from audit to debug (master)

---

CHANGELOG.rst
contrib/runners/mistral_v2/query/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py

There is an edge case where mistral receives connection error from the st2 API when requesting action execution. When this happens, the action execution is requested twice. The first action execution is requested, the record is written into the MongoDB, but it is not published to the action runners. The second action execution is scheduled and the mistral workflow reach completion. The mistral querier for the st2resultstracker will see the first action execution in a non-completed state and assume the workflow is still running. This patch identifies this specific edge case and ignores the duplicate action execution.

Fix edge case for workflows stuck in running state

---

CHANGELOG.rst
st2api/st2api/controllers/v1/rules.py
st2api/tests/unit/controllers/v1/test_policies_rbac.py
st2api/tests/unit/controllers/v1/test_rules.py
st2common/st2common/exceptions/rbac.py
st2common/st2common/models/api/base.py
st2common/st2common/models/db/stormbase.py
st2common/st2common/models/db/trigger.py
st2common/st2common/rbac/utils.py
st2common/st2common/router.py
st2common/tests/unit/test_db_model_uids.py

This pull request fixes a regression introduced when we were moving to new Swagger based API.
In some scenarios, no API validation was perform and internal server error 500 was incorrectly returned to the user instead of correct and more-user friendly 400 bad request with the actual message which describes what is wrong.
Those scenarios include:
- 500 internal error would be returned in case user provided no request body when request body is mandatory (POST, PUT)
- API validation hasn't been performed which means API model hasn't been instantiated and default model values set which resulted in issues like this #3863. This worked fine in the past and ID is already provided in the URL so no need to provide it again in the body.
Fixes #3863.

Fix a regression with API endpoint not returning 400 and performing no validation in some scenarios

---

contrib/chatops/pack.yaml
contrib/core/pack.yaml
contrib/default/pack.yaml
contrib/examples/pack.yaml
contrib/hello_st2/pack.yaml
contrib/linux/pack.yaml
contrib/packs/pack.yaml

The `author:` field in our core packs was inconsistent with what we use in Exchange packs. This makes it `StackStorm, Inc.`.
Also cleaned up some pack descriptions. 
No changes to packs themselves, so not bothering to bump pack versions.
Related: https://github.com/StackStorm-Exchange/stackstorm-slack/pull/13

Tidied author and description fields in packs

---

CHANGELOG.rst
st2client/st2client/formatters/execution.py
st2client/st2client/utils/strutil.py
st2client/tests/fixtures/execution_get_default.txt
st2client/tests/fixtures/execution_unescape_newline.txt
st2client/tests/fixtures/execution_unicode.json
st2client/tests/fixtures/execution_unicode.txt
st2client/tests/fixtures/execution_with_stack_trace.json
st2client/tests/unit/test_formatters.py

The execution formatter had some bugs that caused some problems with properly representing newline characters. This PR addresses two problems:
- Extra escape characters are added to the output of `yaml.safe_dump`. This means that newline characters `\n` are escaped, and are, as a result, not honored in the final client output. This means that complicated output like stack traces are output as a single line, which makes it wholly unreadable.
- `yaml.safe_dump` also adds a second `\n` to existing instances of `\n`, resulting in `\n\n`. Since we're printing this resulting value, this results in a lot of whitespace in output
As documented in #3855, the client has exhibited some strange behavior showing certain executions - in particular, Python stack traces:
```
~$ st2 run …
```

Fix bugs with newlines and unicode in execution formatter

---

st2common/st2common/util/param.py
st2common/tests/unit/test_param_utils.py

The feature is required for serverless plugin, but might be useful to further extend the variety of contexts during rendering.

Additional contexts for rendering live params

---

CHANGELOG.rst
contrib/runners/local_runner/local_runner/local_runner.py
contrib/runners/local_runner/local_runner/runner.yaml
contrib/runners/local_runner/tests/integration/test_localrunner.py
contrib/runners/remote_command_runner/remote_command_runner/remote_command_runner.py
contrib/runners/remote_command_runner/remote_command_runner/runner.yaml
contrib/runners/remote_script_runner/remote_script_runner/remote_script_runner.py
contrib/runners/remote_script_runner/remote_script_runner/runner.yaml
lint-configs/python/.flake8
st2actions/tests/unit/test_parallel_ssh.py
st2api/st2api/controllers/v1/actionexecutions.py
st2client/st2client/commands/action.py
st2client/tests/unit/test_execution_tail_command.py
st2common/st2common/models/system/action.py
st2common/st2common/models/system/paramiko_command_action.py
st2common/st2common/models/system/paramiko_script_action.py
st2common/st2common/runners/parallel_ssh.py
st2common/st2common/runners/paramiko_ssh_runner.py
st2common/st2common/util/param.py
st2common/tests/unit/test_logger.py
st2common/tests/unit/test_paramiko_command_action_model.py
st2common/tests/unit/test_paramiko_script_action_model.py
st2common/tests/unit/test_shell_action_system_model.py
tools/log_watcher.py

This pull request adds support for sudo password.
As an additional change, I added new ``--tail`` flag to ``st2 run`` and ``st2 execution re-run`` commands. When this flag is provided, new execution is automatically tailed once it's scheduled (it saves typing one command - previously you first need to do run then tail).

Add support for sudo password to the local and remote runners

---

CHANGELOG.rst
contrib/runners/mistral_v2/query/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py

There is an edge case where mistral receives connection error from the st2 API when requesting action execution. When this happens, the action execution is requested twice. The first action execution is requested, the record is written into the MongoDB, but it is not published to the action runners. The second action execution is scheduled and the mistral workflow reach completion. The mistral querier for the st2resultstracker will see the first action execution in a non-completed state and assume the workflow is still running. This patch identifies this specific edge case and ignores the duplicate action execution.

v2.5.1: Fix edge case for workflows stuck in running state

---

CHANGELOG.rst
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2common/st2common/runners/utils.py
st2common/st2common/services/datastore.py
st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py

There was a bug when all the log messages generated by a Python runner action would be duplicated when datastore service was used.
It looks like this issue was present for a very long time, but it only manifested itself when datastore service was also used inside an action (in that scenario two instances of the logger with the same name were created) so we didn't catch it earlier.
This PR fixes that by caching loggers by name and making sure there is always only a single instance of a logger with a particular name. Keep in mind that this function is called inside subprocess (python action wrapper) so there is no potential issue with this cache growing too large because cache is on per Python runner action process basis and not action runner basis.
Before:
```bash …
```

Fix a bug with duplicated log messages in Python runner action stderr output

---

CHANGELOG.rst
contrib/runners/local_runner/tests/integration/test_localrunner.py
st2api/st2api/controllers/v1/actionalias.py
st2api/st2api/controllers/v1/aliasexecution.py
st2api/tests/unit/controllers/v1/test_alias_execution.py
st2common/st2common/models/db/__init__.py
st2common/st2common/models/utils/action_alias_utils.py
st2common/st2common/persistence/execution.py
st2common/st2common/persistence/liveaction.py
st2common/st2common/persistence/trigger.py
st2common/st2common/util/actionalias_helpstring.py
st2common/st2common/util/actionalias_matching.py
st2common/tests/unit/test_resource_registrar.py
st2common/tests/unit/test_util_actionalias_matching.py
st2tests/st2tests/fixtures/aliases/actions/action2.yaml
st2tests/st2tests/fixtures/aliases/aliases/alias_fixes1.yaml
st2tests/st2tests/fixtures/aliases/aliases/alias_fixes2.yaml
st2tests/st2tests/fixtures/aliases/aliases/alias_match_multiple.yaml

This is the server-side implementation of [hubot-stackstorm PR #148](https://github.com/StackStorm/hubot-stackstorm/pull/148) with a few tweaks.
This PR refactors and re-implements the `match_and_execute` API endpoint to match a command to a single alias and execute the associated action multiple times.
That prose is kind of difficult to parse and grok, so here's some [pseudocode](https://stackoverflow.com/a/12076662):
```python
match = [command.match(alias) for alias in action_aliases if not alias.multiple_match]
if match:
return {'results': [match[0].execute()]}
else:
matches = [command.match(alias) for alias in action_aliases if alias.multiple_match]
if matches:
return {'results': [match.execute() for match in matches]}
```
This implementation will only ever match a *single* alias per …

Match and multiple execute

---

st2common/st2common/models/system/action.py
st2common/st2common/models/system/paramiko_command_action.py
st2common/st2common/models/system/paramiko_script_action.py
st2common/tests/unit/test_paramiko_command_action_model.py
st2common/tests/unit/test_paramiko_script_action_model.py

This pull request updates remote command and script runner to explicitly disable bash history when user provides `sudo_password` parameter which is passed to `sudo` binary as a command line (stdin) argument.
As mentioned here (https://github.com/StackStorm/st2/pull/3867#issuecomment-349273078), the way paramiko executes shell commands bash history is not enabled, but it's still better to be on the safe side and also try to explicitly disable it ourselves.
Disabling is done by setting `HISTFILE` (I set it to `/dev/null`, if this would become problematic in some installations where user doesn't have write access to `/dev/null` we can change that approach to try unseting this variable instead) and `HISTSIZE` environment variable and by explicitly calling `set +o history` command before any …

Disable bash history when sudo password is provided as a command line argument

---

contrib/runners/python_runner/python_runner/python_runner.py
st2common/st2common/util/pack.py
st2common/tests/unit/test_util_pack.py
st2reactor/st2reactor/container/process_container.py

Not so long ago, we refactored a bunch of runners and runner container code to make runners fully standalone (they don't depend on MongoDB and RabbitMQ anymore).
We follow "dependency injection" approach and the required parameters are passed to runners by the action container service instead of being retrieved the the runner itself (that's a better abstraction anyway).
It turns out, https://github.com/StackStorm/st2/pull/3658 inadvertently added MongoDB dependency back to the Python runner.
This pull request updates the code to remove this dependency (common libs path is only retrieved if that feature is enabled in the config (off by default) and MongoDB related connection errors are ignored) so the Python runner works on AWS Lambda again.
Slightly better and long term solution is update …

Remove MongoDB database dependency from Python runner

---

Makefile
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

This PR is the companion API documentation for #3884.
I'm not super familiar with how Swagger all works, so please make sure everything looks fine, particularly my use `oneOf` to define a heterogeneous array. My intent here is that items of the `formats` array are either plain strings or objects that match the subschema.
The first commit is tweaking the injected header to make it clear what the actual command is. I tried to run `make .generate-api-spec make target`, which was incorrect.
The second commit is filling out the expected input and output JSON schemas.

Match and multiple execute doc

---

contrib/linux/actions/vmstat.yaml

The linux.vmstat action fails due to the type missing. It expects arguments to be passed as a string. 
Without this fix running linux.vmstat fails with an error:
```
$ st2 run linux.vmstat hosts='localhost' args="3 2"
ERROR: 'type'
```
After the fix the command completes successfully:
```
$ st2 run linux.vmstat hosts='localhost' args="3 2"
..
id: 5a2948d4a44fdf731ec3f18e
parameters: 
args: 3 2
hosts: localhost
result: 
localhost:
failed: false
return_code: 0
stderr: ''
stdout: "procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----\n r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st\n 0  0      0 137056 190248 2092336    0    0     3    47   76  114  1  0 99  0  0\n 0  0      0 136980 190248 2092452    0    0     0 …
```

Add type to vmstat action

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/util/param.py
st2common/tests/unit/test_param_utils.py

Previously only "Cyclic dependency found" error was thrown if a cycle was found (e.g. parameter is referencing itself or similar) which made it quite unfriendly and harder / slower to troubleshoot the issue.
With this change we now reference the actual variable where cycle is found to make the error more obvious and troubleshooting easier.
Before:
```
Cyclic dependency found
```
After:
```
Cyclic dependency found in the following variables: cyclic, morecyclic
```

Throw more user-friendly error on if a cycle is found inside action parameters

---

st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

"user" is a required property for match and execute API endpoint, but API schema doesn't define that so if this property is not included in the request body API will fail with internal server error instead of with user-friendly "bad requests".
```bash
2017-12-08 10:23:53,360 ERROR [-] Failed to call controller function "match_and_execute" for operation "st2api.controllers.v1.aliasexecution:action_alias_execution_controller.match_and_execute": 'AliasMatchAndExecuteInputAPI' object has no attribute 'user'
File "/data/stanley/st2common/st2common/router.py", line 450, in __call__
resp = func(**kw)
File "/data/stanley/st2api/st2api/controllers/v1/aliasexecution.py", line 79, in match_and_execute
'user': input_api.user,
AttributeError: …
```

Update openapi.yaml definition file - user is required property for match and execute API endpoint

---

st2client/st2client/commands/action.py
st2client/tests/unit/test_action.py
st2client/tests/unit/test_command_actionrun.py

https://github.com/StackStorm/st2/pull/3670 introduced a cool new capability to split strings in an array parameter on a colon `:` character in order to specify a dictionary more easily.
However, this breaks a few corner cases, such as those where the user wants to provide an array of strings that all contain `:` and doesn't want them split. For instance, some network interfaces have a colon in their name and it shouldn't be split up.
This kicked off a long discussion internally, and we've decided to go for a more robust, exhaustive method of dealing with more complicated data types, likely to be implemented in the 2.6 release timeframe, perhaps 2.7.
Until that time, we need to take a stopgap measure to retain the functionality for those that need it, while getting things working again …

Add flag to opt-in to dict conversion when colons are detected

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/util/param.py
st2common/tests/unit/test_param_utils.py

#3820 reported an issue that parameter defaults that use Jinja templates that return something other than string, simply don't work.
This is caused by two things:
- The code in the API controller that handles execution scheduling currently makes a call to `action_service.create_request` before the live parameters are retrieved, which is where any templates are rendered into a result value. So if a parameter is an `integer` but the default value is still a template (string) - even if that template is expected to return an int, naturally this will cause problems because it hasn't even rendered yet.
- The call to `param_utils.render_live_params` and the function calls within will render the templates, but will not actually use the resulting value, as the default values for parameters are not …

Retrieve live params first, include template-driven defaults

---

st2common/st2common/query/base.py

https://github.com/StackStorm/st2/issues/3743 reported that the logging in the actionrunner logs wasn't sufficiently showing detail for finished mistral workflows. This is expected due to the asynchronous nature of how workflows are executed.
So, the right place to get this info is straight from the source, which is the results tracker. However, the `st2resultstracker` logs don't contain the necessary liveaction details either, only some high-level info about the workflow. We want to display the full liveaction details in a debug log message, which this PR introduces.
Here's sample output from `st2resultstracker.log` with this change:
```
2017-12-18 21:51:44,054 139983593305904 INFO base [-] Clearing state object: ActionExecutionStateDB(execution_id=5a38386e32ed35015f2f7932, …
```

Add log message for workflow liveaction details in results tracker

---

st2common/st2common/util/param.py
st2common/tests/unit/test_param_utils.py

Regression from: https://github.com/StackStorm/st2/pull/3892
```bash
$ st2 run linux.lsof hosts=localhost
MESSAGE: Override of immutable parameter(s) [u'cmd'] is unsupported. for url: http://127.0.0.1:9101/v1/executions
```

Add step to skip immutable params to be overridden

---

contrib/examples/rules/sample_rule_with_webhook.yaml

`test_quickstart_rules` has been failing intermediately for many months now and we simply can't figure out where the failure / race is coming from..
The main problem with this issue is that it's hard / impossible to replicate locally so fixing it is also hard.
We tried many things already and with this PR I'm going to try another thing.

Update sample rule to flush cached data to disk

---

st2api/tests/unit/controllers/v1/test_webhooks.py
st2common/st2common/router.py
st2common/st2common/util/jsonify.py

This pull request updates router code to throw a more user-friendly exception when invalid type is specified for the API endpoint input data. This only applies to API endpoints which don't explicitly define model schema such as `POST /v1/webhooks`.
Previously internal server error without any context was returned.
This pull request should be merged in any case, even if decide not to go with the approach implemented in #3956.
Before:
```bash
{
"faultstring": "Internal Server Error"
}
````
After:
```bash
{
"faultstring": "Input body needs to be an object, got: array"
}
```
Related #3955 #3956

Throw a more user-friendly exception on invalid API endpoint input type

---

CHANGELOG.rst
st2client/st2client/commands/action.py
st2client/tests/unit/test_execution_tail_command.py

This pull request updates "st2 execution tail" command to support two level deeply nested workflow (e.g. workflow -> workflow -> execution).
Previously only top-level executions and workflows were supported (e.g. execution, workflow -> execution).
Before:
```bash
st2 run --tail examples.mistral-workbook-subflows
Tailing execution "5a688d74e693a751cdf53852"
Child execution (task=print_subject) 5a688d74e693a751cdf53855 has started.
Child execution (task=print_subject) 5a688d74e693a751cdf53855 has started.
StackStorm
Execution 5a688d74e693a751cdf53852 has completed (status=succeeded).
id: 5a688d74e693a751cdf53852
action.ref: examples.mistral-workbook-subflows
parameters: None
status: running
start_timestamp: Wed, 24 Jan 2018 13:43:16 UTC
end_timestamp: …
```

Update "st2 execution tail" command to support two levels nested workflows

---

st2api/tests/unit/controllers/v1/test_executions.py

This pull request should fixes intermediate failures like the one here - https://travis-ci.org/StackStorm/st2/jobs/316638594.
The problem only manifests itself in the tests, because `get_listener` is a non-blocking method, so it's possible that `listener.listen` won't yet be called when we hit API endpoint and as such, we will miss out some messages.
This can't happen outside the tests, because listeners are pre-intialized.

Fix race condition in execution output test case

---

tools/launchdev.sh

Fix relative virtualenv, python, and db cleanup file paths. Activate the virtualenv to execute the cleanup DB script otherwise the script will complain about non-existent module st2common.persistence.cleanup.

Fix cleanup db in launchdev

---

CHANGELOG.rst
contrib/runners/python_runner/python_runner/python_runner.py
st2actions/tests/integration/test_python_action_process_wrapper.py
st2common/st2common/runners/python_action_wrapper.py

This pull request implements small improvements in the Python runner mentioned in #3976:
1. When parameters are passed to the action wrapper process via stdin, time out and throw an exception if no input is received within 2 seconds.
Without that change, we would wait for the input indefinitely when running the wrapper script directly (e.g. for debugging purposes) and up to `timeout` runner parameter seconds when running action under action runner.
2. Update runner to print full command string which can be used to run python wrapper process when using stdin parameters
Before:
```bash
/opt/stackstorm/virtualenvs/examples/bin/python -u /data/stanley/st2common/st2common/runners/python_action_wrapper.py --pack=examples --file-path=/opt/stackstorm/packs/examples/actions/print_to_stdout_and_stde …
```

Small improvements in the Python runner

---

CHANGELOG.rst
contrib/runners/python_runner/python_runner/python_action_wrapper.py
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2common/st2common/runners/base_action.py
st2common/st2common/runners/utils.py
st2tests/st2tests/resources/packs/pythonactions/actions/print_config_item_doesnt_exist.py

This pull request updates Python runner so it throws a more user-friendly exception when a script tries to access a key in ``self.config`` dictionary which doesn't exist.
@LindsayHill did a good job of adding a note to most pack README.md files which says user need to run ``st2ctl reload --register-configs`` after adding / modifying configs, but it's still easy to miss / forget that step so we should throw as user-friendly exception as possible.
Before:
```bash
python ./st2client/st2client/shell.py run examples.print_config
id: 5a9540d60640fd0bc9dbf6b4
status: failed
parameters: None
result: 
exit_code: 1
result: None
stderr: "Traceback (most recent call last):
File "/data/stanley/contrib/runners/python_runner/python_runner/python_action_wrapper.py", line 356, in <module>
obj.run()
File …
```

Update Python runner to throw a more user-friendly exception on missing pack config item

---

CHANGELOG.rst
conf/st2.conf.sample
contrib/packs/actions/install.meta.yaml
contrib/packs/actions/pack_mgmt/setup_virtualenv.py
contrib/packs/actions/setup_virtualenv.yaml
contrib/packs/actions/workflows/install.yaml
st2api/st2api/controllers/v1/packs.py
st2client/st2client/commands/pack.py
st2client/st2client/models/core.py
st2common/st2common/config.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/util/virtualenvs.py
st2common/tests/unit/test_virtualenvs.py
tools/config_gen.py

This pull request adds new `--python3` flag to `st2 pack install`` command.
When this flag is provided, virtual environment which is created for a pack uses python3 binary (based on the value of `actionrunner.python3` config option).
Underneath, it adds ``python3`` parameter to `packs.{install,setup_virtualenv}` actions.
This pull request builds on top of @tonybaloney's idea in #3922.
We couldn't come up to a consensus in that PR. I thought that approach in that PR is still a bit too invasive until we have CI, etc. in place for packs so we can verify end to end that pack also (or only) works with Python 3.
This pull request goes with a more incremental middle of the ground opt-in approach. If user wishes to use Python 3 for a particular pack they can opt-in. And if things don't go well …

Add new --python3 flag to st2 pack install CLI command

---

st2common/st2common/exceptions/db.py
st2common/st2common/models/db/__init__.py
st2common/st2common/models/db/stormbase.py
st2common/tests/unit/base.py
st2common/tests/unit/test_persistence_change_revision.py

Add a base model with a change revision field that is used as save condition in MongoDB for coordinated writes between multiple threads or processes. This is required to support coordinated update of workflow execution by parallel tasks running at multiple processes.

Add database model to support coordinated write

---

CHANGELOG.rst
st2common/bin/st2ctl

This is a fix for #4025 .
It adds the ability for `st2ctl` to load in environment variables from an `/etc/default/st2ctl` (ubuntu) or `/etc/sysconfig/st2ctl` file. This allows deployments to utilize selective component lists and non-default st2.conf  locations.

Fix for #4025 - st2ctl environment variables

---

st2api/st2api/controllers/v1/sensors.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

I'm currently working on Triggers app for st2web and I've noticed our /sensortypes endpoint doesn't confirm with its spec. The PR fixes that. It also allows us to filter sensortypes by triggers they produce, which in turn makes it easier to build trigger objects for the UI.

Ensure parity between SensorType API spec and implementation

---

contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py

This pull request adds a test case which verifies Traceback messages are not duplicated in Python runner action stderr output.
A user reported an issue which says Tracebacks are duplicated in action stderr. I was unable to replicate the issue in {v2.5.0,v2.6.0,master} and I noticed we don't have a test case for it yet, so I added one.
The test case passes, because the issue doesn't seem to exist or it's related to some edge case or a specific action.
(We do have a test case for duplicated logger messages, it was added as part of https://github.com/StackStorm/st2/pull/3893).

Add a test case which verifies tracebacks in Python runner actions are not duplicated in stderr

---

CHANGELOG.rst
st2client/st2client/commands/pack.py
st2client/st2client/models/core.py

A while ago we added a change which displays number of artifacts which are to be registered when running "st2 pack install" command (#3675).
That change inadvertently introduced a regression and dependency of "st2 pack install" command on access to index.stackstorm.org pack index.
This pull request includes two changes / fixes:
* Don't try to access pack index when installing a local pack (pack path starts with "file://")
* Ignore errors related to index access in "st2 pack install" command. This CLI command could run from any host and that host doesn't necessary need access to pack index - only the actual StackStorm instance where action runner runs needs access to index to be able to install a pack.
Now when installing a local pack or remote pack and server where "st2 pack install" is …

"st2 pack install" command shouldn't need access to pack index

---

CHANGELOG.rst
st2common/st2common/content/utils.py
st2common/st2common/models/api/action.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/tests/unit/test_content_utils.py

For security reasons (to avoid directory traversal attacks, writing outside of the pack directory, etc.), we only allow users to write pack data files inside the pack directory.
The error we threw before was a bit ambiguous and not user-friendly so this PR fixes that.
Before:
```bash
Invalid file path: /opt/stackstorm/packs/dummy_pack_2/bar.py
```
After:
```
Invalid file path: /opt/stackstorm/packs/dummy_pack_2/bar.py. File path needs to be relative to the pack actions directory (opt/stackstorm/packs/test/actions). For example "my_action.py".
```
Related issue #4039.

Throw a more user-friendly error on invalid file path when resolving path to a pack resource

---

contrib/packs/tests/test_action_unload.py
st2api/st2api/controllers/v1/sensors.py
st2api/tests/unit/controllers/v1/test_packs.py
st2api/tests/unit/controllers/v1/test_sensortypes.py
st2tests/st2tests/fixtures/packs/dummy_pack_1/sensors/my_sensor_2.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_1/sensors/my_sensor_3.yaml

This pull request fixes `?enabled` query parameter filter added in #4033. 
It was missing a transformation so it didn't actually work. In addition to that, it also adds tests for those filters.
A couple of things (most of them we already talked about in the past):
* Such changes are not much help without the corresponding test cases
* We should utilize correct types for query param filters and not just abuse `type: string` for everything. It's wrong and incorrect (e.g. enabled should have `type: boolean`). I already voiced my opinion about that in the past (especially for arrays), but we should do something about it.
* We should auto-generate tests for all the query param filters using openapi definition file. Previous point is a pre-requisite for this.

Fix, tests for #4033

---

CHANGELOG.rst
contrib/runners/windows_runner/tests/unit/test_windows_runners.py
contrib/runners/windows_runner/windows_runner/windows_command_runner.py
contrib/runners/windows_runner/windows_runner/windows_script_runner.py

This pull request updates a result / output dictionary returned by the Windows runners to match local and remote runner output object.
The change is breaking / partially backward incompatible so it needs to be included in minor / major release (2.7.0) and we need to document that change in changelog and upgrade notes document.
Related issue #4044.

Make windows runners output object be consistent with other runner output objects

---

.travis.yml
st2api/tests/unit/controllers/v1/test_sensortypes.py
st2common/st2common/models/db/sensor.py
st2common/st2common/util/monkey_patch.py

Small issue caught by @enykeev.
I assume this was simply an oversight because all the tests still pass and register-content-script still works as expected.

Add missing "ref" field to SensorTypeDB model

---

st2common/st2common/models/api/rule.py

The `/ruleOverview` endpoint extends rule object with additional information to reduce the number of API calls client has to make. This PR enables client to edit this objects without additional changes.

Allow descriptions in rule trigger and action fields

---

circle.yml

Replace `properle` with `properly`, and `limtation` with `limitation`.

Fix typos found in comments

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_packs_rbac.py
st2common/st2common/rbac/resolvers.py

"pack_search" permission is a read-only / view permission so observer role should also grant that permission.
This fixes an issue originally reported by a user in #4063.
Resolves #4063.

Observer role should also grant "pack_search" view permission

---

st2tests/st2tests/config.py

The encryption key path that is overriding config in st2tests is relative. In certain unit tests, the path is not recognizable. This patch provides an absolute path of the key file instead.

Fix the encryption key path for the key value config in st2tests

---

scripts/dist_utils.py
st2actions/dist_utils.py
st2api/dist_utils.py
st2auth/dist_utils.py
st2client/dist_utils.py
st2common/dist_utils.py
st2debug/dist_utils.py
st2exporter/dist_utils.py
st2reactor/dist_utils.py
st2stream/dist_utils.py
st2tests/dist_utils.py

pip removed "public" `parse_requirements` method in the latest version and this breaks our build in places where we don't pin pip to version `<9.1`.
This pull request fixes that. Eventually we should move away from `parse_requirements` since it not documented / part of the public API anymore (they actually argue it was never part of a public API, but a lot of projects depend on it so I would argue otherwise).
Note: This PR can be merged post v2.7.0 because this repo is fine, builds are only failing in some other repos where we don't pin pip.

Fix dist_utils.py so it works with pip >= 10.0

---

Makefile
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2tests/st2tests/fixturesloader.py

Some of our unit tests now rely on git submodules being checked out.
This pull request includes two changes to make that more user (developer) friendly:
* Check out submodules as part of `requirements` make target. This way submodules will always be checked out for the tests which rely on `requirements` target. This change is not explicitly needed for CI systems because CI systems check out submodules by default, but that's not the case with older git versions when user (developer) checks out the git repo manually.
* Throw a more user-friendly exception is user tries to run a test which relies on git submodules, but submodules are not checked out.
Related docs PR https://github.com/StackStorm/st2docs/pull/720.

Friendlier error message if git submodules are not checked out, check out submodules as part of make target

---

.gitmodules
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2tests/st2tests/fixturesloader.py

This pull request updates content_version tests to use a new pack (https://github.com/StackStorm-Exchange/stackstorm-test-content-version) as a submodule.
This pack is a lot more straight forward and obvious and also makes manual testing easier.

Update content_version tests to use a new pack

---

.travis.yml
Makefile

Merged some changes into master and master build failed even though all the branches / PR builds passed.
It's likely related to Travis dependencies cache and old version od virtualenv being used for master builds. I believe this change should fix it.

Make sure latest version of virtualenv is used on Travis and everywhere

---

CHANGELOG.rst
st2client/st2client/shell.py
st2client/tests/unit/test_shell.py

This pull request updates ``st2 --version`` CLI command to also include git revision of the release when running a dev release and when file with package metadata is available.
Before:
```bash
$ st2 --version
st2 2.8dev, on Python 2.7
```
After:
```bash
$ st2 --version
st2 2.8dev (5f89c1f), on Python 2.7.6
```
This saves some typing since you don't need to manually check the package metadata file (`/opt/stackstorm/st2/package.meta`).
If others think it makes sense, we could also include git revision when running a stable (non dev) release, but I personally think that's not needed and it would just make it confusing (we have a corresponding git tag for each final release which is not the case for dev releases).

Include git revision of StackStorm release in the st2 --version output when running a dev release

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/st2common/util/monkey_patch.py
st2reactor/st2reactor/container/sensor_wrapper.py
st2reactor/tests/unit/test_sensor_wrapper.py

In v2.7.0 we upgraded eventlet to the latest stable version. That stable version removed `select.poll()` which was available in previous releases (but it was blocking) to make it harder for users to "accidentally" use blocking code.
That change broke some sensors which rely on `select.poll()` functionality.
Users would see an error similar to one below:
```bash
2018-05-09 07:57:29,425 ERROR [-] AttributeError
2018-05-09 07:57:29,425 ERROR [-] : 
2018-05-09 07:57:29,425 ERROR [-] 'module' object has no attribute 'poll'
2018-05-09 07:57:29,425 ERROR [-] 
```
This PR adds `select` module which includes blocking version of `poll()` back to `sys.modules` so it can be used by the sensors which need it.
The behavior will now be the same as in releases prior to v2.7.0. Blocking code is not great …

Fix for a regression which broke sensors which rely on select.poll() functionality

---

CHANGELOG.rst
st2common/bin/st2-track-result

We didn't declare `id` argument as required so script exited with a confusing error if id wasn't provided.
Before:
```bash
$ st2-track-result
2018-05-07 14:38:58,249 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2018-05-07 14:38:58,336 INFO [-] Retrieving action execution record...
File "/usr/bin/st2-track-result", line 113, in <module>
add_result_tracker(cfg.CONF.id)
File "/usr/bin/st2-track-result", line 48, in add_result_tracker
exec_db = ActionExecution.get_by_id(exec_id)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/base.py", line 87, in get_by_id
return cls._get_impl().get_by_id(value)
File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line …
```

id is a required argument for st2-track-result command

---

Makefile
contrib/runners/action_chain_runner/dist_utils.py
contrib/runners/announcement_runner/dist_utils.py
contrib/runners/cloudslang_runner/dist_utils.py
contrib/runners/http_runner/dist_utils.py
contrib/runners/inquirer_runner/dist_utils.py
contrib/runners/local_runner/dist_utils.py
contrib/runners/mistral_v2/dist_utils.py
contrib/runners/noop_runner/dist_utils.py
contrib/runners/python_runner/dist_utils.py
contrib/runners/remote_runner/dist_utils.py
contrib/runners/windows_runner/dist_utils.py

We've apparently missed updating dist_utils.py files in runners the same way we do it in components. This resulted in #4069 fix not propagating there and as a result, serverless plugin being broken in pip 10 environments.

Add missing pip 10 fix to runners

---

st2common/st2common/router.py

Minor debug log typo.
Skimmed through the rest of the debug logs, they look OK at first glance.

Very minor debug log typo

---

st2actions/st2actions/container/base.py
st2common/st2common/metrics/base.py
st2common/st2common/metrics/drivers/statsd_driver.py
st2common/tests/unit/test_metrics.py

Original metrics PR had some missing pieces. Chiefly incorrect naming generated by the metrics formatter. Wrote some tests to cover that from happening again. Also had to move decorator to the context manager for `_do_run` because we're accessing it by placing it into a dictionary and apparently that has some interesting side effects on decorators that I'll be interested to explore when I have some more time.

Metrics Fixup

---

CHANGELOG.rst
st2api/st2api/controllers/resource.py
st2api/st2api/controllers/v1/triggers.py
st2api/tests/unit/controllers/v1/test_triggerinstances.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

This pull request adds TriggerType reference based filtering to the `/v1/triggerinstances` API endpoint as discussed with @enykeev.
Example usage - `curl http://127.0.0.1:9101/v1/triggerinstances?trigger_type=core.st2.generic.actiontrigger`.
Note on the implementation detail - We only store Trigger reference on the TriggerInstance object so to be able to filter on TriggerType reference we need to do that via Trigger reference on the TriggerInstance object.
In relational database that would be a simple join and in non-relational database that would be a simple query in case Trigger is correctly denormalized and trigger reference also stored on the TriggerInstance object (that's not the case for our schema right now).
Recent versions of MongoDB also support simple aggregate queries and …

Add trigger type reference based filtering to the /v1/triggerinstances API endpoint

---

CHANGELOG.rst
contrib/runners/action_chain_runner/action_chain_runner/action_chain_runner.py
contrib/runners/mistral_v2/callback/mistral_v2.py
contrib/runners/mistral_v2/tests/unit/test_mistral_v2_callback.py
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2actions/st2actions/container/base.py
st2actions/tests/unit/test_runner_container.py
st2client/st2client/commands/action.py
st2common/st2common/callback/base.py
st2common/st2common/runners/base.py
st2common/st2common/runners/utils.py

Refactor the callback module for runner post run to be more generic. Currently, the callback takes a REST endpoint as input argument. The callback module is abstracted to take other input arguments. In this patch, the entire liveaction database object is passed to avoid overcrowding the method signature. Unfortunately, the liveaction object that the runner reference to is out dated by the time the runner makes the post run and there are more than one references of the object in the runner container. The runner container and runner is refactored to ensure references objects are used and updated.

Refactor the callback module for post run to be more generic

---

CHANGELOG.rst
contrib/examples/actions/python_runner_print_python_version.yaml
contrib/examples/actions/pythonactions/print_python_version.py
contrib/runners/python_runner/python_runner/python_runner.py
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2client/st2client/commands/pack.py
st2common/st2common/constants/pack.py
st2common/st2common/util/sandboxing.py
st2common/st2common/util/virtualenvs.py
st2common/tests/unit/test_util_sandboxing.py
st2common/tests/unit/test_virtualenvs.py
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume.yaml

This pull request adds experimental and opt-in support for using Python 3 for pack actions.
It continues work from other PRs - https://github.com/StackStorm/st2/pull/3922, https://github.com/StackStorm/st2/pull/4016, https://github.com/StackStorm/st2/pull/4075.
Our code changes in the past were a bit too optimistic and it turned out a lot more work is still needed to get that feature working.
The scope and target audience for this feature didn't change - it's still intended for advanced users and it's opt in - user needs to pass in ``--python3`` flag to ``st2 pack install <pack name>`` CLI command and Python 3 binary will be used when creating virtual environment for that pack and for all the subsequent pack action executions.
As mentioned before, this feature is mostly meant as an …

Experimental and opt-in Python 3 support for Python runner actions

---

circle.yml

When CircleCI Tests task failed it exits immediately, so the command to grab the st2 logs from Docker container didn't run.
Fix this behavior, by running the "grab the st2 logs" command with `when: always`.
This helps in debugging.

Fix sharing st2 logs when CircleCI task failed

---

st2common/st2common/jinja/filters/data.py
st2common/tests/unit/test_jinja_render_data_filters.py
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume.yaml

This pull request makes the following example work:
```yaml
---
description: Run a local linux command
enabled: true
runner_type: mistral-v2
entry_point: workflows/render_test.yaml
name: render_test
pack: default
parameters:
cmd:
required: true
type: string
timeout:
type: integer
default: 60
kv_array:
type: array
default: "{{ st2kv.system.kv_array | from_json_string }}"
kv_object:
type: object
default: "{{ st2kv.system.kv_object | from_json_string }}"
```
As mentioned in #4153, `from_json_string` filter cast call is not really needed since the value is already automatically cast based on the parameter type definition, but it doesn't hurt either.
This way both approaches are supported (one without a cast and one without explicit cast).

Improvements to the rendering of default parameter values which contain Jinja expression and filters

---

CHANGELOG.rst
st2common/st2common/util/pack.py
st2common/tests/unit/test_configs_registrar.py
st2tests/st2tests/fixtures/packs/configs/dummy_pack_19.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_19/config.schema.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_19/pack.yaml

This pull request fixes an issue reported in #4166.
If config validation failed against the config schema and the item was an array, an unrelated exception was thrown instead of throwing a user-friendly error message.
Before:
> Failed to register config "/data/stanley/st2tests/st2tests/fixtures/packs/configs/dummy_pack_19.yaml" for pack "dummy_pack_19": sequence item 1: expected string or Unicode, int found
After
> Failed to register config "/data/stanley/st2tests/st2tests/fixtures/packs/configs/dummy_pack_19.yaml" for pack "dummy_pack_19": Failed validating attribute "instances.0.alias" in config for pack "dummy_pack_19" (/data/stanley/st2tests/st2tests/fixtures/packs/configs/dummy_pack_19.yaml): {'not': 'string'} is not of type u'string
Resolves #4166.

Fix an issue with friendly error not being thrown if validation failed on config item of type array

---

conf/nginx/st2.conf

Using regex for location doesn't allow to specify full URI for  `proxy_pass` (with trailing slash).
During Docker/K8s work we need to substitute the API_URL, AUTH_URL and STREAM_URL in nginx `st2.conf` replacing existing proxy endpoints.
And so we can't use dynamic URIs like `http://random-ip-or-domain:maybe-port/` because:
```
nginx: [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/conf.d/st2.conf:87
```
This small nginx config adjustment removing regex from `st2stream` location makes var substitution easier.
More on this:
* https://stackoverflow.com/questions/21662940/nginx-proxy-pass-cannot-have-uri-part-in-location
* …

Fix nginx 'proxy_pass' directive can't use URI in regex location

---

st2common/bin/st2-run-pack-tests

`pip` is going to change the format for `pip list` in future. 
Using current versions of `pip`, we get this DEPRECATION warning:
```shell
lindsaysmacbook:st2 lhill$ pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)
lindsaysmacbook:st2 lhill$ pip list > /dev/null
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
lindsaysmacbook:st2 lhill$
```
This can be seen when running `st2-run-pack-tests`
```shell
Running tests for pack: repo
Installing dependencies from st2 …
```

Remove pip list warning

---

CHANGELOG.rst
st2client/st2client/commands/action_alias.py

Adds help for `st2 action-alias match` and `st2 action-alias execute`.
Fixes #3171 
Before:
```shell
extreme@EWC:~$ st2 action-alias match -h
usage: st2 action-alias match [-t TOKEN] [--api-key API_KEY] [-j] [-y] [-h]
[-a ATTR [ATTR ...]] [-w WIDTH [WIDTH ...]]
command
st2 action-alias match: error: too few arguments
extreme@EWC:~$ st2 action-alias execute -h
usage: st2 action-alias execute [-t TOKEN] [--api-key API_KEY] [-j] [-y] [-h]
[-u USER]
command
st2 action-alias execute: error: too few arguments
extreme@EWC:~$
```
After:
```shell
extreme@EWC:~$ st2 action-alias match -h
usage: st2 action-alias match [-h] [-t TOKEN] [--api-key API_KEY] [-j] [-y]
[-a ATTR [ATTR ...]] [-w WIDTH [WIDTH ...]]
command
Get the list of action aliases that match the command text.
positional arguments: …
```

Added help for action-alias match & execute

---

conf/st2.conf.sample
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
fixed-requirements.txt
requirements.txt
st2common/bin/st2-generate-symmetric-crypto-key
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/config.py
st2common/st2common/util/crypto.py
st2common/tests/unit/test_crypto_utils.py
st2tests/st2tests/fixtures/keyczar_keys/five.json
st2tests/st2tests/fixtures/keyczar_keys/four.json
st2tests/st2tests/fixtures/keyczar_keys/one.json
st2tests/st2tests/fixtures/keyczar_keys/three.json
st2tests/st2tests/fixtures/keyczar_keys/two.json
test-requirements.txt
tox.ini

This pull request moves our code for handling symmetric AES encryption and decryption from `keyczar` to `cryptography` library.
The change is fully backward and forward compatible as it's an implementation detail so it should in no way affect end users (and they shouldn't notice it either).
When python-keyczar library was released, it was one of the best and most user-friendly crypto library with sane and safe defaults in the Python world.
Over the years the crypto world moved on (one of the notable moves forward was development of the cryptography library which was meant to be a more portable and safer / saner higher level replacement for PyCrypto, M2Crypto and other crypto libraries in the Python world).
Python-keyczar is still a relatively safe and good choice in the Python world, but …

Move from keyczar to cryptography library for symmetric encryption / decryption

---

st2common/st2common/models/db/__init__.py
st2common/tests/unit/test_db.py

#4141 introduced logging of "successfully connected to MongoDB" messages.
While troubleshooting an unrelated issue today, I noticed those messages are always logged even if connection fails later on so those messages were confusing and not correct.
The reason for that is that `.connect()` method is lazy and not-blocking. It always returns immediately because connection is only established (and error thrown if that fails) on first query / command being issued.
From mongoengine docs (http://api.mongodb.com/python/current/api/pymongo/mongo_client.html):
> Note Starting with version 3.0 the MongoClient constructor no longer blocks while connecting to the server or servers, and it no longer raises ConnectionFailure if they are unavailable, nor ConfigurationError if the user’s credentials are …

Fix MongoDB successful connection logging

---

.coveragerc
Makefile
contrib/runners/action_chain_runner/tests/unit/test_actionchain_pause_resume.py

Adds tests directories to coverage results, and reworks the coverage handling in the root `Makefile` to (try to) avoid rerunning tests if they've already been run.
WIP because I may have broken everything since it's a subtantial rewrite of the make logic, but other than that I'm pretty happy with it.
When I ran everything manually and gathered coverage result I got about 80% coverage throughout the entire codebase (tests included), which (in my experience) is very good for a project this size.
Questions:
* Some covered files might be considered noise in coverage results (`wsgi.py`, `setup.py`, `dist_utils.py`) - do we want to ignore those in our reports? I kinda do.
* Do we care about coverage in `*/tests/`? Some projects like it ([pynacl](https://github.com/pyca/pynacl/pull/290)), some …

Rewrite coverage handling in the root Makefile

---

.travis.yml
Makefile
conf/st2.conf.sample
conf/st2.tests.conf
conf/st2.tests1.conf
st2common/st2common/constants/scheduler.py
st2common/st2common/router.py
st2common/tests/integration/test_register_content_script.py
st2debug/st2debug/cmd/submit_debug_info.py
st2debug/tests/integration/fixtures/configs/st2.conf
st2exporter/st2exporter/exporter/dumper.py
st2exporter/st2exporter/worker.py
st2exporter/tests/integration/test_dumper_integration.py
st2exporter/tests/integration/test_export_worker.py
st2exporter/tests/unit/test_dumper.py
st2exporter/tests/unit/test_json_converter.py
st2reactor/st2reactor/cmd/sensormanager.py
st2reactor/st2reactor/container/manager.py
st2reactor/st2reactor/container/partitioner_lookup.py
st2reactor/st2reactor/container/process_container.py
st2reactor/st2reactor/sensor/config.py
st2reactor/tests/integration/test_garbage_collector.py
st2reactor/tests/integration/test_sensor_container.py
st2tests/st2tests/config.py
tox.ini

This pull request adds single sensor mode to the sensor container service (enabled via ``sensorcontainer.single_sensor_mode`` config option).
When this flag is set, sensor container process doesn't manage lifecycle of a sensor processes and respawn them if a sensor exits / crashes, but it exits itself and propagates sensor exit code to the parent sensor container process.
This comes handy in scenarios when a sensor life cycle and failover is handled by an external service such as Kubernetes / Mesos / monitoring + bash scripts / ...
Note: This flag needs to be used in combination with ``--sensor-ref`` CLI option since without it it doesn't make sense.

Add single sensor mode to the sensor container service / process

---

conf/st2.package.conf
conf/st2.prod.conf

Add the st2workflowengine logging configuration path to the st2.conf for packaging and production.

Add st2workflowengine logging conf to appropriate st2 conf files

---

st2common/bin/st2ctl

Add st2workflowengine to the list of service components in st2ctl.

Add st2workflowengine to st2ctl

---

CHANGELOG.rst
st2common/st2common/jinja/filters/path.py
st2common/st2common/util/jinja.py
st2common/tests/unit/test_jinja_render_path_filters.py

This pull request adds entry for dictionary in `st2common.util.jinja.get_filters` and also adds a corresponding changelog entry on top of #4184.
I decided to base this new PR on top of the existing one so we can merge that today and include it in v2.8.0.
Resolves #4184.

Add jinja filter to manipulate paths (with changelog entry)

---

st2common/st2common/service_setup.py

This pull request updates service startup code to log which Python version and executable is used by that service (it uses DEBUG log level).
This will come handy in the future when we will support Python 2 and Python 3 (it will allow us to see which version of Python is used and also assert on it in the tests).

Log which Python version and executable is used on service startup

---

contrib/examples/actions/orchestra-basic.yaml
contrib/examples/actions/workflows/orchestra-basic.yaml

Add a basic workflow examples.orchestra-basic which is equivalent to the examples.mistral-basic.

Add a basic example for orchestra runner

---

tox.ini

This pull request removes old and used tasks from tox.ini.
Right now only `py3-unit` and `py3-integration` tasks are used. For Python 2.7 we mostly use make targets.
For consistently reasons we should probably move other Python 2.7 lint and test targets into tox.ini (or vise versa).

Remove unused and obsolete tasks from tox.ini

---

conf/logrotate.conf

We were missing a logrotate entry for the new `st2workflowengine` service.

Add missing logrotate entry for new st2workflowengine service

---

st2api/st2api/controllers/v1/pack_configs.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

Rename pack_uninstall_request variable to pack_config_values as it was confusing.

Rename a misleading variable name

---

st2actions/st2actions/workflows/workflows.py
st2common/st2common/services/workflows.py

Add more logging in st2workflowengine and st2notifier to be able to trace workflow execution from log messages.
Note: The root action execution ID is used for the identifier to grep from logs.
```
ubuntu@cadmus:~/projects/stackstorm/st2$ st2 run examples.orchestra-fail-input-rendering
.
id: 5b3296148006e62048ad4525
action.ref: examples.orchestra-fail-input-rendering
parameters: None
status: failed
start_timestamp: Tue, 26 Jun 2018 19:37:55 UTC
end_timestamp: Tue, 26 Jun 2018 19:37:56 UTC
result: 
errors:
- message: Unknown function "#property#value"
output: null
ubuntu@cadmus:~/projects/stackstorm/st2$ tail -n 100 ./logs/st2workflowengine.log | grep 5b3296148006e62048ad4525
2018-06-26 19:37:56,349 139832784608144 INFO workflows [-] [5b3296148006e62048ad4525] Processing request for …
```

Add more logging for the workflow engine

---

st2api/conf/logging.gunicorn.conf
st2auth/conf/logging.gunicorn.conf
st2stream/conf/logging.gunicorn.conf

While testing the release, I encountered an edge case with gunicorn worker log messages.
We don't specify a special logging config which is to be used by gunicorn worker processes. This means that if an error or similar occurs in a worker process during start up, those errors are ignored in production and not logged to the corresponding service log file.
This makes a lot of config file related troubleshooting hard since error messages are simply not logged anywhere.
It looks like this issue has existed for a while and it only affects production (and not dev environment) which API services run under gunicorn process.
I personally view this as a blocker and need to merge for v2.8.0 release.
Corresponding st2-packages pull request / change is work in progress.
Example log file before this …

Add gunicorn logging config for all the API services which run under gunicorn

---

CHANGELOG.rst
st2client/st2client/base.py
st2client/st2client/commands/auth.py
st2client/st2client/config_parser.py
st2client/st2client/shell.py
st2client/tests/unit/test_auth.py
st2client/tests/unit/test_config_parser.py
st2client/tests/unit/test_shell.py

Fixes #4144.
This ensures that we create the config directory and file with the proper permissions.
It also tweaks the `st2 login` command to check the permissions on the config file (`~/.st2/config`) and directory (`~/.st2`) every time it is run, and then automatically fix permissions if they are too permissive. It does use the `warnings` module to warn the user about this, but does not give them a chance to opt out or turn the behavior off.
Automatically fixing the directory/file permissions assumes that there is no good reason for a process owned by another user or group to need read access to the config file. That is a very large assumption, so I'm inviting discussion about that.
The options are:
1. simply "warn the user" into fixing the config permissions, but not automatically fix …

Fix config permissions on the config directory and the config file

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

This pull request includes two changes:
1. It fixes regression with `?include_attributes` query param filter in the `GET /v1/executions` API endpoint
2. Updates out of sync openapi.yaml file (it was missing some new orchestra related attributes on the Execution object)

?include_attributes regression fix for /v1/executions API endpoint, update openapi.yaml

---

st2common/st2common/router.py

This is a small issue I noticed while working on https://github.com/StackStorm/st2/pull/4224.
We only want to set `req.body` to empty JSON object when content type is `application/json`. This way it will work correctly / as expected for `text/plain` and other content types where no JSON schema validation is performed.

Only set req.body to an empty JSON object when content type is application/json

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actions.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

This PR adds the functionality to filter actions on `/api/v1/actions` endpoint by tags.
For example:
https://{host}/api/v1/actions?tags=test
Will return all actions that are tagged with the name test.

Add filter actions by tag

---

README.md
contrib/runners/orchestra_runner/in-requirements.txt
contrib/runners/orchestra_runner/requirements.txt
contrib/runners/winrm_runner/dist_utils.py

#4169 changed how we handle runner `requirements.txt` files - we now generate them based on the `in-requirements.txt` file inside the runner package directory and based on the pinned dependency versions in `fixed-versions.txt` file.
This way it's consistent with other StackStorm components.
#4169 predated Orchestra changes so it was missing `in-requirements.txt` for the new orchestra runner Python package.

Add missing in-requirements.txt to orchestra runner

---

CHANGELOG.rst
st2common/st2common/util/secrets.py
st2common/tests/unit/test_util_secrets.py

Most likely due to the re-work of secret masking here https://github.com/StackStorm/st2/pull/4140 `objects` and `arrays` that were marked with `secret: true` were not being masked. See https://github.com/StackStorm/st2/issues/4235 for details on the symptoms. 
This PR addresses this by looking for the `secret` property on `object` and `array` types. It then treats all data within the `object` or `array` as secret, returning a single masked value.
Example of the fixed version:
```
$ st2 run default.secret_objects secret_object='{"abc": "123"}' secret_array='[1, 2, 3]'
.
id: 5b44de76a814c004961c020e
parameters: 
secret_object: '********'
secret_array: '********'
result: 
failed: false
return_code: 0
stderr: ''
stdout: ''
succeeded: true
```
FYI, i create a unit test for …

Fix bug where objects and arrays marked as secret weren't being masked

---

CHANGELOG.rst
st2client/st2client/formatters/table.py
st2client/st2client/utils/terminal.py
st2client/tests/unit/test_util_terminal.py

Right now, we try various approaches to obtain terminal size used by the CLI for table formatting purposes.
If none of that approaches work, we fall back to a default hard coded size (10 lines, 20 columns).
This pull request improves on that in two ways:
1. It uses a more reasonable default size. `20` columns for a total terminal width is simply a bad default. It means pretty much every table cell / column will wrap at couple of characters which will make output unreadable when we are unable to retrieve a terminal size.
2. Allows user to force terminal size using `ST2_CLI_FORCE_TERMINAL_SIZE=<lines,columns>` environment variable.
We have experienced this "issue" a lot in our end to end tests for a long time. Since those test commands don't run using shell, we fail to obtain a terminal …

Allow user to force terminal size used by the CLI formatters by setting environment variable

---

CHANGELOG.rst
contrib/runners/http_runner/http_runner/runner.yaml

Resolves #4244.
Thansk to @daniel-mckenna for reporting it.

Mark "password" http-runner parameter as secret (v2.8)

---

requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Pin the orchestra dependency to v0.1 release so changes to orchestra will not break future v2.8.x patch releases.

Pin orchestra to v0.1 release

---

contrib/runners/action_chain_runner/action_chain_runner/__init__.py
contrib/runners/action_chain_runner/setup.py
contrib/runners/announcement_runner/announcement_runner/__init__.py
contrib/runners/announcement_runner/setup.py
contrib/runners/cloudslang_runner/cloudslang_runner/__init__.py
contrib/runners/cloudslang_runner/setup.py
contrib/runners/http_runner/http_runner/__init__.py
contrib/runners/http_runner/setup.py
contrib/runners/inquirer_runner/inquirer_runner/__init__.py
contrib/runners/inquirer_runner/setup.py
contrib/runners/local_runner/local_runner/__init__.py
contrib/runners/local_runner/setup.py
contrib/runners/mistral_v2/mistral_v2/__init__.py
contrib/runners/mistral_v2/setup.py
contrib/runners/noop_runner/noop_runner/__init__.py
contrib/runners/noop_runner/setup.py
contrib/runners/orchestra_runner/orchestra_runner/__init__.py
contrib/runners/orchestra_runner/setup.py
contrib/runners/python_runner/python_runner/__init__.py
contrib/runners/python_runner/setup.py
contrib/runners/remote_runner/remote_runner/__init__.py
contrib/runners/remote_runner/setup.py
contrib/runners/windows_runner/setup.py
contrib/runners/windows_runner/windows_runner/__init__.py
contrib/runners/winrm_runner/setup.py
contrib/runners/winrm_runner/winrm_runner/__init__.py

This pull request updates all the runner packages to they read their version from the runner package local `__init__.py` file.
Sadly we can't go with approach in #4211 due to a cyclic dependency issue (which right now only exists for orchestra runner, but once we move to dynamic stevedore loading will exist for every runner package if we make runners depend directly on st2common) - https://github.com/StackStorm/st2/pull/4211#issuecomment-404437539.
This way it's consistent with `st2client`.
Second part of this change is updating st2cd release workflow so it also updates version for all the runner packages (in the same place where we set version for st2common and st2client).

Update runner packages to read version from runner package local __init__.py file

---

contrib/runners/action_chain_runner/action_chain_runner/__init__.py
contrib/runners/action_chain_runner/setup.py
contrib/runners/announcement_runner/announcement_runner/__init__.py
contrib/runners/announcement_runner/setup.py
contrib/runners/cloudslang_runner/cloudslang_runner/__init__.py
contrib/runners/cloudslang_runner/setup.py
contrib/runners/http_runner/http_runner/__init__.py
contrib/runners/http_runner/setup.py
contrib/runners/inquirer_runner/inquirer_runner/__init__.py
contrib/runners/inquirer_runner/setup.py
contrib/runners/local_runner/local_runner/__init__.py
contrib/runners/local_runner/setup.py
contrib/runners/mistral_v2/mistral_v2/__init__.py
contrib/runners/mistral_v2/setup.py
contrib/runners/noop_runner/noop_runner/__init__.py
contrib/runners/noop_runner/setup.py
contrib/runners/orchestra_runner/orchestra_runner/__init__.py
contrib/runners/orchestra_runner/setup.py
contrib/runners/python_runner/python_runner/__init__.py
contrib/runners/python_runner/setup.py
contrib/runners/remote_runner/remote_runner/__init__.py
contrib/runners/remote_runner/setup.py
contrib/runners/windows_runner/setup.py
contrib/runners/windows_runner/windows_runner/__init__.py

This pull request backports changes from https://github.com/StackStorm/st2/pull/4239.
As discussed in https://github.com/StackStorm/st2cd/pull/340, we decided to backport those changes into v2.8. This way we keep things simple and don't need any special cases in the workflow if we need to do another 2.8.x patch release.

Update runner packages to read version from runner package local __init__.py file (v2.8)

---

Makefile

The st2client.egg-info is included in the list of components and that caused errors when making requirements and running pylints on the components. The make tests command would abort at the pylint step and stop running unit tests. The wildcard function to identify the list of st2 components is replaced with a shell command to run ls and grep the entries that start with st2 but not end with .egg-info.
The itests step requires ci-prepare-integration so the currently pytests fail on itests. This patch reduce the scope of pytests to only run unit tests but expand the scope of make tests to cover specific steps from pytests, ci-unit, and ci-integration.

Fix make tests

---

CHANGELOG.rst

Mark CloudSlang runner as Deprecated in Changelog. 
Note: Will not remove runner from core until version 3.1, when pluggable runner work is complete.
Part of https://github.com/StackStorm/st2/issues/4199

Changelog only: Deprecate CloudSlang

---

.gitignore
.travis.yml
Makefile

Separated out from #4264 to ensure the CircleCI tests pass.

Dont do coverage for PRs

---

.travis.yml
Makefile

This pull request fixes a regression introduced in https://github.com/StackStorm/st2/pull/4147 and updates the code so we again submit coverage reports to coveralls.io on merge to master.

Submit coverage reports to codecov.io on master merge

---

st2client/st2client/commands/action.py

In 3.7 'async' becomes a reserved keyword.  Rename the variable.
https://docs.python.org/3/whatsnew/3.7.html

Remove use of async in args for python 3.7 support

---

.travis.yml
Makefile
st2client/tests/unit/test_util_terminal.py

Fixes typo in the script path in travis config file.

Fix typo in travis.yml

---

fixed-requirements.txt

The version were used had a reported security vulnerability recently - https://cryptography.io/en/latest/changelog/#v2-3

Update cryptography library to v2.3.0

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/router.py
st2common/st2common/service_setup.py
st2common/st2common/transport/bootstrap_utils.py
st2common/st2common/transport/publishers.py
st2stream/st2stream/controllers/v1/executions.py
st2stream/tests/unit/controllers/v1/test_stream_execution_output.py

This pull request adds new ``?output_type=[raw|event_source]`` and ``?existing_only=[true|false]`` query parameter filters to the ``/v1/api/executions/<id>/output`` API endpoint.
With this query parameters, user can control two things:
1. What type of output to receive
* ``raw`` for raw output data produced by the execution (default). This works well when user just wants to curl this endpoint, embed the output directly in a webpage or similar.
* ``event_source`` - for event source compatible format (new line delimited JSON). This comes handy when user is also interested in metadata such as timestamp and output type.
NOTE: ``event_source`` format can result in a slow response for actions which produced a lot of data because it means we need to format and JSON serialize every …

Add new ?output_type and ?existing_only query param filter to /v1/api/executions/<id>/output API endpoint

---

.travis.yml
CHANGELOG.rst
contrib/examples/actions/python_runner_print_python_environment.yaml
contrib/examples/actions/python_runner_print_python_version.yaml
contrib/examples/actions/pythonactions/print_python_environment.py
fixed-requirements.txt
requirements.txt
scripts/travis/time-command.sh
st2api/in-requirements.txt
st2api/tests/unit/controllers/v1/test_auth_api_keys.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/in-requirements.txt
st2common/requirements.txt
st2stream/in-requirements.txt

This pull request updates `mongoengine` to the latest version (0.15.3) from our fork (https://github.com/MongoEngine/mongoengine/pull/1833) which contains a work-around for a large regression in memory usage introduced in mongoengine v0.13.0.
I confirmed reverting that commit fixes an issue with increased memory usage.
Using our fork with a reverted commit:
```bash
(virtualenv) vagrant@ubuntu-xenial:/data/stanley$ python test_mongoengine.py 
Python: 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on Linux-4.4.0-130-generic-x86_64-with-Ubuntu-16.04-xenial
mongoengine: 0.15.3
sleeping...
(virtualenv) vagrant@ubuntu-xenial:/data/stanley$ ps -eo rss,pid,euser,args:100 --sort %mem | grep -i 'test_mongoengine' |grep -v grep | awk '{printf $1/1024 "MB"; $1=""; print }'
18.3281MB …
```

Upgrade mongoengine to the latest version (0.15.3)

---

st2client/st2client/shell.py

Latest version of `cryptography` started warning if `hmac` module doesn't have `compare_digest` function.
This is the case for one of our Ubuntu build servers which likely runs old 2.7.x version. This pull request silences those warnings for now, since they are not fatal yet.
This should fix the failing Ubuntu daily build.
Eventually we should also look into ensuring that our Ubuntu build slave host runs latest 2.7.x release.

Ignore CryptographyDeprecationWarning deprecation warning in st2 CLI

---

.travis.yml

I'm disabling running tests under MongoDB 3.6 until we figure out why tests are 30%-40% slower compared to 3.4.
See https://github.com/StackStorm/st2/issues/4098#issuecomment-410712729 for details.

Don't run tests under MongoDB 3.6

---

contrib/hello_st2/actions/greet.yaml

Somehow our example `hello_st2.greet` action had the wrong runner type, and no-one noticed for years.
Fixes https://github.com/StackStorm/st2/issues/4296

Fix hello_st2 greet action

---

tools/st2-inject-trigger-instances.py

Various improvements to the `st2-trigger-instances` script which is used to benchmark StackStorm (rules engine).
1. Specify duration in seconds
2. Reduce `random.expovariate` sleep by 55% to allow script to actually achieve rate requested by the user (that is, when requested rate is smaller than the max possible rate on that configuration). Previously actual achieved rate was always 50% or so less than the requested one, due to the overhead of `dispatcher.dispatch` call. (`eventlet.sleep(delta)` would only work correctly if duration of `dispatcher.dispatch` was zero aka no op). Keep in mind that the actual achieves rate might still be a bit less or a bit more than the requested one, but it will be much closer than before.
3. Add ``--max-throughput`` option which allows user to achieve …

Improvements to the st2-inject-trigger-instances script

---

CHANGELOG.rst
conf/metrics/carbon/storage-aggregation.conf
st2actions/st2actions/workflows/workflows.py
st2common/st2common/util/action_db.py
st2reactor/st2reactor/rules/worker.py

Noticed that per execution status graphs are off, then I found this typo in the code.
As discussed on Slack yesterday, this PR also changes rules engine per trigger instance metric to per trigger metric.
Each trigger instance is unique and having many unique metrics is an anti-pattern. And since we are talking of potentially many, many trigger instances total, this would have a big negative performance overhead on any metrics backend.
And while at it, I also added some basic instrumentation to the new workflow engine service.

Fix a typo, we should increment a counter

---

conf/st2.conf.sample
st2common/st2common/config.py
st2common/st2common/metrics/drivers/statsd_driver.py
st2common/st2common/middleware/instrumentation.py
st2common/tests/unit/test_metrics.py

I went over the metrics and noticed that some stream service metrics are not accurate.
The reason for that is that stream endpoint reqiests are long running and middleware returns immediately instead of when connection is closed (when either server or client closes it). With those changes we will now have correct timing and request count information.
To be able to get accurate numbers, I needed to utilize eventlet posthook (there is no other way to achieve that - http://eventlet.net/doc/modules/wsgi.html#non-standard-extension-to-support-post-hooks).
I also added some other changes:
1. Allow user to specify sample rate. Comes handy in environments with tons of request where you want to reduce the load on metrics backend server and not send every single operation metrics to the backend.
2. …

Instrumentation improvements

---

contrib/examples/actions/orquesta-fail-inspection-task-contents.yaml
contrib/examples/actions/workflows/tests/orquesta-fail-inspection-task-contents.yaml
contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
st2api/st2api/controllers/v1/workflow_inspection.py
st2api/tests/unit/controllers/v1/test_workflow_inspection.py
st2client/st2client/client.py
st2client/st2client/commands/workflow.py
st2client/st2client/models/core.py
st2client/st2client/shell.py
st2client/tests/unit/test_client.py
st2client/tests/unit/test_shell.py
st2client/tests/unit/test_workflow.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/router.py
st2common/st2common/services/workflows.py
st2common/tests/unit/services/test_workflow.py
st2tests/integration/orquesta/test_wiring_error_handling.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-inspection-action-db.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-inspection-action-ref.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-inspection-missing-required-action-param.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-inspection-unexpected-action-param.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-inspection-action-db.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-inspection-action-ref.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-inspection-missing-required-action-param.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-inspection-unexpected-action-param.yaml

Add `/v1/workflows/inspect` endpoint in the API and a POST method to inspect workflow definition and return errors found. Add a `st2 workflow inspect` command that uses the API endpoint for workflow inspection.

Add API endpoint and CLI command for orquesta workflow inspection

---

.travis.yml

No need to run `apt-get update` twice.
Caught by @armab.

Remove duplicated apt-get update from .travis.yml

---

CHANGELOG.rst

Deprecate winexe-based Windows runners, in favor of the new pywinrm-based runners. 
Not yet removing the old runners - will do that in version 3.1.

Deprecate winexe-based Windows runners

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/tests/unit/test_runner_container.py
st2api/st2api/controllers/v1/actionexecutions.py
st2api/st2api/controllers/v1/auth.py
st2api/st2api/controllers/v1/keyvalue.py
st2api/tests/unit/controllers/v1/test_executions.py
st2api/tests/unit/controllers/v1/test_triggerinstances.py
st2client/st2client/models/keyvalue.py
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/models/api/base.py
st2common/st2common/models/db/__init__.py
st2common/st2common/persistence/auth.py
st2common/st2common/persistence/base.py
st2common/st2common/persistence/keyvalue.py
st2common/st2common/services/action.py
st2common/st2common/services/executions.py
st2common/st2common/util/action_db.py
st2common/st2common/util/isotime.py
st2common/st2common/util/misc.py
st2common/st2common/util/mongoescape.py
st2common/st2common/util/schema/__init__.py
st2common/st2common/util/ujson.py
st2common/tests/unit/test_logger.py
st2common/tests/unit/test_misc_utils.py

This pull request optimizes performance of ``POST /v1/executions`` API endpoints by doing various things:
We are trading a bit of code readability and maintainability for performance, but that's needed here because the code was / is very wasteful and the performance is really bad. And this bad performance has cascading effect on Mistral and everything else which schedules executions through the API.
Related issue #4030.

Optimize performance of POST /v1/executions API endpoint

---

CHANGELOG.rst
st2client/st2client/commands/action.py
st2client/tests/unit/test_execution_tail_command.py

This pull request includes various improvements to the ``st2 execution tail`` CLI command:
1. Support for Orquesta workflows
2. Support for arbitrary nested workflows
3. Correct filtering - previously if user was tailing execution "X" and other executions were also running, data from other executions would incorrectly be included in the output
Resolves #4267.

"st2 execution tail" CLI command improvements

---

CHANGELOG.rst
conf/st2.conf.sample
st2actions/st2actions/notifier/notifier.py
st2actions/tests/unit/test_notifier.py
st2common/st2common/config.py

This pull request adds a changelog entry for #4315.
In addition to that, it defaults ``action_sensor.emit_when`` config option to live action completed states. 
This way the default value is explicit and user doesn't need to dig through the code to figure out what happens if no value is specified.

Changelog entry for #4315

---

CHANGELOG.rst
conf/nginx/st2.conf

Our default NGINX configuration redirects `http://` requests to `https://`. This uses a 301 redirect. When clients see this, they will either switch PUT/POST requests to GET, or they may continue with PUT/POST, but with no payload.
This change uses [HTTP 308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) instead. The request method and body will be unchanged.
This will reduce confusion for people using custom code that targets `http://<ST2>/`, rather than `https://<ST2>`

NGINX: Use 308 redirect rather than 301

---

CHANGELOG.rst
contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-task-execution.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-task-execution.yaml

Add unit test to ensure that the error and result of an action execution failure for a task is logged in the orquesta workflow result.

Add log entry in workflow result on action execution failure

---

st2client/st2client/commands/action.py
st2client/st2client/config_parser.py
st2client/st2client/formatters/execution.py
st2client/tests/fixtures/execution_get_attributes.txt
st2client/tests/fixtures/execution_get_default.txt
st2client/tests/fixtures/execution_unescape_newline.txt
st2client/tests/fixtures/execution_unicode.txt
st2client/tests/fixtures/execution_unicode_py3.txt
st2client/tests/unit/test_config_parser.py

Various changes based on the testing feedback:
* Don't print "action doesn't have an output schema" warning when user passed ``--yaml`` flag to ``st2 run`` command - when ``--yaml`` is flag is used, user wants a machine readable format.

Various v2.9.0 changes

---

CHANGELOG.rst
st2common/bin/st2-self-check

Provide CLI options to skip Orquesta and/or Mistral tests in `st2-self-check`.
Default is still to **run** Orquesta & Mistral tests, and to **not** run Windows tests.
UX is not great, but it keeps defaults same as existing.
Resolves #4311

st2-self-check Option to skip Mistral & Orquesta tests

---

CHANGELOG.rst
st2actions/tests/unit/test_actions_registrar.py
st2api/st2api/controllers/v1/packs.py
st2common/st2common/bootstrap/actionsregistrar.py
st2common/st2common/bootstrap/base.py
st2common/st2common/bootstrap/configsregistrar.py
st2common/st2common/validators/api/action.py

This pull request speeds up registering pack actions through the ``/v1/packs/register`` API endpoint (e.g. when using `st2 pack install` command).
We do that by caching `RunnerTypeDB` objects in memory for each "register session" (aka each time user hits ``/v1/packs/register`` API endpoint). Since we re-initialize the cache on each API request, this means there are no issues with potential stale cache, but we still see benefits when registering packs with a lot of resources.
This helps in situations where pack has a lot of actions such as the ``aws`` pack. Previously RunnerTypeDB was retrieved from the database ``N`` times where ``N`` is number of actions in a pack and now it's only retrieved ``M`` times where ``M`` is number of unique runners referenced by actions in a particular pack …

Speed up pack action registration through the /v1/packs/register API endpoint

---

contrib/packs/aliases/pack_install.yaml
contrib/packs/pack.yaml
contrib/packs/tests/test_action_aliases.py

Added missing tests for for `packs` pack ChatOps aliases.
Resolves #3056 
Minor change needed to pack_install alias.

Added tests for packs aliases

---

CHANGELOG.rst
st2api/st2api/controllers/v1/triggers.py

Trigger types were not sorted by default. 
Output could look like this:
```shell
+--------------------------------------+----------+-----------------------------------------------------+
| ref                                  | pack     | description                                         |
+--------------------------------------+----------+-----------------------------------------------------+
| core.st2.generic.actiontrigger       | core     | Trigger encapsulating the completion of an action   |
|                                      |          | execution.                                          |
| core.st2.generic.notifytrigger       | core     | Notification trigger.                               |
| core.st2.action.file_writen          | core     | Trigger encapsulating action …
```

Add default sorting to trigger types API

---

CHANGELOG.rst
st2common/st2common/constants/error_messages.py
st2common/st2common/util/sandboxing.py
st2common/tests/unit/test_util_sandboxing.py
st2reactor/st2reactor/container/process_container.py

This pull request updates sensor container to fail and throw an exception if user runs StackStorm installation under Python 2 but creates a pack virtualenv using Python 3 and wants to run sensor from that pack.
We only support Python runner actions in such "mixed environments" and getting sensors to also work is simply too complicated for too little gain (I started on it in #4353, but gave up since it includes too many edge cases and it's simply fragile - sensors are much more complex than Python runner actions and depend on more StackStorm components code).
Supersedes #4353.

Throw an exception if user wants to run a sensor from a pack which uses Python 3 virtual environment

---

CHANGELOG.rst
contrib/packs/tests/test_action_download.py
st2common/st2common/util/pack_management.py

This pull request updates ``st2-pack-install`` command to allow users install packs from a local directory on disk (`file:///<path>`) which are in a detached head state - aka user already checked out a specific commit / revision.
Fixes https://github.com/StackStorm/st2packs-dockerfiles/issues/4.

Update st2-pack-install command so it allows users to install packs from local git repos in a detached head state

---

st2common/bin/st2-self-check

This pull request updates `st2-self-check` script to include timing info for each action we run.
People complained this script is taking a long time and this will allow us at a glance to identify tasks which take a long time and refactor / improve them.
```bash
~
Attempting Test tests.test_inquiry_chain...OK! (37s)
Attempting Test tests.test_inquiry_mistral...OK! (36s)
Attempting Test tests.test_key_triggers...OK! (33s)
Attempting Test tests.test_pack_install_tool...OK! (11s)
Attempting Test tests.test_packs_pack...OK! (72s)
Attempting Test tests.test_quickstart...OK! (19s)
Attempting Test tests.test_quickstart_key...OK! (7s)
Attempting Test tests.test_quickstart_local_script_actions...OK! (12s)
Attempting Test tests.test_quickstart_passive_sensor...OK! (7s)
Attempting Test …
```

Update st2-self-check to include task timing information

---

st2common/bin/st2-self-check

While cherry picking changes into #4365, I noticed I inadvertently introduced a bug in self check script (already fixed in that branch).
This pull request fixes the bug to correctly use exit code from ``st2 run...`` command line instead of using exit code from variable assignment line.

Use correct exit code in st2-self-check script

---

CHANGELOG.rst
Makefile
contrib/packs/tests/test_action_download.py
st2actions/tests/unit/test_actions_registrar.py
st2api/st2api/controllers/v1/packs.py
st2common/bin/st2-self-check
st2common/st2common/bootstrap/actionsregistrar.py
st2common/st2common/bootstrap/base.py
st2common/st2common/bootstrap/configsregistrar.py
st2common/st2common/cmd/generate_api_spec.py
st2common/st2common/cmd/validate_api_spec.py
st2common/st2common/constants/error_messages.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/util/pack_management.py
st2common/st2common/util/sandboxing.py
st2common/st2common/util/spec_loader.py
st2common/st2common/validators/api/action.py
st2common/tests/unit/test_util_sandboxing.py
st2reactor/st2reactor/container/process_container.py
st2reactor/tests/integration/test_sensor_watcher.py

Included changes:
* Speed up pack action registration through the /v1/packs/register API endpoint - #4342
* Fixing openapi definition - #4357 
* Throw an exception if user wants to run a sensor from a pack which uses Python 3 virtual environment - #4354 
* Update st2-pack-install command so it allows users to install packs from local git repos in a detached head state - #4366 
* Update st2-self-check to include task timing information - #4359

Changes for v2.9.1 release

---

st2common/st2common/services/workflows.py
st2tests/integration/orquesta/base.py
st2tests/integration/orquesta/test_wiring_inquiry.py

When a workflow is paused and there are multiple requests to resume the workflow, there is a race and one of the request fails because the workflow is already in an active state. Instead of erroring, log the situation and there is no need to resume since the workflow is already active.

Fix race when parallel inquiries set the execution status

---

CHANGELOG.rst
st2common/st2common/services/workflows.py
st2tests/integration/orquesta/base.py

This pull request cherry picks change from #4369 into v2.9 branch for inclusion in v2.9.1.

Fix race when parallel inquiries set the execution status (v2.9.1)

---

st2client/st2client/models/core.py
st2client/tests/unit/test_models.py

This fixes #4361. The summary of this changes are below.
- Setting default parameter at 'cacert' and 'debug' of the StreamManager parameter to keep a consistency with other ResourceManagers.
- Adding a processing to pass 'cacert' parameter of StreamManager to the 'verify' parameter of SSEClient object to be able to specify a CA bundle for TLS certification.
We can confirm that #4361 will be solved by this change, which means we can activate 'cacert' option which is defined in the configuration, like following.
```bash
(virtualenv) ubuntu@ubuntu0:~$ cat .st2/config
[general]
silence_ssl_warnings = True
cacert = /etc/ssl/st2/st2.crt
[stream]
url = https://ubuntu0/stream/v1
(virtualenv) ubuntu@ubuntu0:~$ st2 pack remove zabbix
[ succeeded ] unregister packs
[ succeeded ] delete packs
```

Changed to activate cacert parameter when st2client sends requests to st2stream

---

fixed-requirements.txt
requirements.txt
st2common/requirements.txt

Current paramiko version has known vulnerability. This PR upgrades to non-vulnerable version.

Update paramiko from vulnerable version

---

CHANGELOG.rst
st2client/st2client/commands/auth.py
st2client/tests/unit/test_auth.py

closes: https://github.com/StackStorm/st2/issues/4338
```
(virtualenv) root@aca37a80cae2:/st2# st2 login testu -p testp
Logged in as testu
Note: You didn't use --write-password option so the password hasn't been stored in the client config and you will need to login again in 24 hours when the auth token expires.
As an alternative, you can run st2 login command with the "--write-password" flag, but keep it mind this will cause it to store the password in plain-text in the client config file (~/.st2/config).
(virtualenv) root@aca37a80cae2:/st2# echo $?
0
(virtualenv) root@aca37a80cae2:/st2# 
```
```
(virtualenv) root@aca37a80cae2:/st2# st2 login kanye -p 00000 
ERROR: Failed to log in as kanye: 401 Client Error: Unauthorized
MESSAGE: Invalid or missing credentials for url: …
```

Exit with exit code 1 when st2 login fails

---

CHANGELOG.rst
st2client/st2client/commands/keyvalue.py
st2client/tests/unit/test_keyvalue.py

> A small bug, found during the https://github.com/StackStorm/stackstorm-ha/pull/30 K8s work
Loading K/V from an empty file throws an error and fails with non-zero exit code.
```
$ touch st2kv.yaml
$ st2 key load st2kv.yaml 
ERROR: 'NoneType' object has no attribute '__getitem__'
$ echo $?
1
```
```
$ st2 key load st2kv.yaml 
No matching items found
```

Fix 'st2 key load' that errors when importing an empty file

---

st2actions/tests/unit/policies/test_concurrency.py
st2actions/tests/unit/policies/test_concurrency_by_attr.py

Just testing a change to see if it will help with a lot of intermediate failures of concurrency tests.

Workaround for intermediate failures

---

st2actions/tests/unit/policies/test_concurrency.py
st2api/tests/unit/controllers/v1/test_executions_auth.py

This pull request fixes another one of those tests which fail every now and then.
This time I finally managed to track down the root cause. We create token and assign ``EXPIRY`` variable in a module level context.
This means that the variable will get assigned and evaluated when module is imported (either by some test case or by nosetests runner).
Test modules are imported by nosetests before running the tests and all the tests run inside the same process. This means that depending on when the nose imports the module and before the tests inside that module actually run, token could already expire by then.
Fix uses a much larger expiry time which means this won't happen anymore.

Fix for intermediate test failure

---

tools/launchdev.sh

Fix the name of the screen session for st2-timersengine otherwise launchdev complains that st2timersengine did not start.

Fix st2timersengine screen session typo in launchdev

---

st2api/tests/unit/controllers/v1/test_executions.py
st2common/st2common/services/action.py

Update the running states and include current execution state in the debug message.

Minor edit to request_resume to help troubleshoot CI failure

---

contrib/runners/orquesta_runner/tests/unit/test_basic.py
st2common/st2common/services/workflows.py

The orquesta workflow user context is not cascaded down to the tasks which lead to failure in accessing user content via the action service in python actions. This fix takes the user context from the workflow execution and pass it to the task execution and subsequently setting the user context in the liveaction.

Fix cascade of workflow user context to orquesta tasks

---

contrib/runners/orquesta_runner/tests/unit/test_basic.py
st2common/st2common/services/workflows.py

The runner post_run contains additional logic to process completion of action execution. Usually for runner that is blocked until the action execution is complete, the post run is handled by the runner container. For runner that is asynchronous, that post run needs to be invoked separately and specifically per runner.

Invoke runner post run on completion of orquesta workflows

---

CHANGELOG.rst
Makefile
conf/st2.conf.sample
contrib/packs/tests/test_action_download.py
st2actions/st2actions/notifier/scheduler.py
st2common/st2common/config.py
st2common/st2common/models/db/trace.py
st2common/st2common/util/pack_management.py
st2reactor/st2reactor/garbage_collector/base.py
st2reactor/st2reactor/timer/config.py
tools/launchdev.sh
tox.ini

I uncovered some more Python 3 related issues while working on Bionic pacakges.
This pull request includes the following changes / fixes:
1. Add missing ``st2garbagecollector`` service to launchdev script
2. Fix launchdev script so it actually uses `VIRTUALENV` environment variable - this allows people to use it with a Python 3 virtual environment
3. Fix ``st2-pack-install`` so it works under Python 3
4. Make sure we run pack tests on Travis under Python 3
5. Correctly pass ``timezone`` kwarg to ``BlockingScheduler`` class constructor

Various Python 3 related fixes and changes

---

contrib/chatops/CHANGES.md
contrib/chatops/actions/format_execution_result.py
contrib/chatops/actions/post_result.yaml
contrib/chatops/actions/workflows/post_result.yaml
contrib/chatops/pack.yaml

The ChatOps pack is used to format execution results.  When the action-alias metadata is configured to disable execution result being returned to the chat backend, an exception is raised in `format_execution_result` which causes the action to be marked as failed.
The failed task and back track are unexpected and confusing because the action is following the requested behaviour of the user.  It seems more logical to have the action succeed even when execution_results are disabled in the action-alias metadata and simply not post the result back to the chat backend in this case.
This PR implements this behaviour with the following changes:
- Stop raising Python exception when execution result is disabled in action-alias.
- Port post_result to orquesta for conditional branching to decide to …

Stop raising Python exception when execution result is disabled.

---

Makefile
contrib/examples/requirements.txt
contrib/examples/sensors/echo_flask_app.py
contrib/examples/sensors/fibonacci_sensor.py
st2common/bin/st2-run-pack-tests
st2common/bin/st2-self-check
st2common/bin/st2ctl
st2common/st2common/util/monkey_patch.py

Python 3 related fixes for various issues which were discovered by new Ubuntu Bionic packages which use Python 3.
* Fix st2-run-pack-tests so it works under Python 3
* Fix various code so it works under Python 3
* Disable threaded mode for flask dev server in example sensor since it blocks the event loop (I noticed this via other sensor which also uses flask dev server which is used by self check)
* Update ``st2ctl`` and ``st2-self-check`` to take into account that Mistral is not present on Ubuntu Bionic. Per our discussion with Slack, I decided to go with a simple distro check. We can adjust / improve that in the future, when we drop support for Mistral in other distros.

More Python 3 fixes

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
contrib/runners/orquesta_runner/tests/unit/test_basic.py
contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
contrib/runners/orquesta_runner/tests/unit/test_functions_task.py
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2tests/integration/orquesta/test_wiring_data_flow.py
st2tests/integration/orquesta/test_wiring_error_handling.py
st2tests/integration/orquesta/test_wiring_functions_task.py
tox.ini

Add tests to ensure input with unicode data is processed and output correctly in Orquesta workflows.

Add tests for unicode input to Orquesta workflows

---

contrib/runners/mistral_v2/mistral_v2/query.py
st2client/st2client/commands/action.py
st2client/st2client/commands/keyvalue.py
st2client/st2client/commands/pack.py
st2common/st2common/metrics/base.py
st2common/st2common/runners/paramiko_ssh_runner.py
st2common/st2common/services/datastore.py
st2common/st2common/util/action_db.py
st2common/st2common/util/reference.py
st2reactor/st2reactor/container/partitioners.py
st2reactor/st2reactor/container/utils.py

We had a few instances where we did not properly format our Exception messages, leading to a literal `%s` in the raised Exception.
I used `pylint -s n --disable=all -e W0715` against all our code to identify all places where this happened.

Fix Exception messages

---

CHANGELOG.rst
st2client/README.rst
st2client/st2client/client.py
st2client/st2client/commands/action.py
st2client/st2client/commands/pack.py
st2client/st2client/commands/trace.py
st2client/st2client/models/action.py
st2client/st2client/models/core.py
st2client/tests/unit/test_client_executions.py
st2tests/integration/mistral/base.py
st2tests/integration/mistral/test_wiring_cancel.py
st2tests/integration/mistral/test_wiring_pause_resume.py
st2tests/integration/mistral/test_wiring_rerun.py
st2tests/integration/orquesta/base.py
st2tests/integration/orquesta/test_wiring_cancel.py
st2tests/integration/orquesta/test_wiring_pause_and_resume.py
st2tests/integration/orquesta/test_wiring_with_items.py

This pull request updates Python st2client resource manager name from ``st2client.liveactions`` to ``st2client.executions``.
``st2client.liveactions`` manager already represented operations on execution objects, but it was incorrectly named (leftover from a long time ago when we introduced a concept of LiveActions).
For backward compatibility reasons, ``st2client.liveactions.{method name}`` will continue to work for a while until it's fully removed in a future release (v3.2.0).
Thanks to @trstruth for bringing this up in #4444. This should have been done a long time ago.

Rename st2client.liveactions to st2client.executions

---

st2actions/tests/unit/policies/test_concurrency.py
st2actions/tests/unit/policies/test_concurrency_by_attr.py
st2tests/st2tests/config.py
st2tests/st2tests/mocks/liveaction.py

Fix race and random failures with unit tests for concurrency policy by using the scheduling only mock publisher and handling the processing of the scheduling queue manually. Use the noop coordinator driver to prevent blocking in the process. The lock mechanism should be unit tested elsewhere. The separation of concerns should improve the robustness of these tests.

Fix race and random failures with unit tests for concurrency policy

---

CHANGELOG.rst
st2common/bin/st2-run-pack-tests

This pull request adds new ``-f`` flag to the ``st2-run-pack-tests`` script which allows users to run a subset of tests from a particular file.
For example:
1. Run all tests in a test file (module):
```bash
st2-run-pack-tests -j -x -p contrib/packs/ -f test_action_download
```
2. Run a single test class
```bash
st2-run-pack-tests -j -x -p contrib/packs/ -f test_action_download:DownloadGitRepoActionTestCase
```
3. Run a single test class method
```bash
st2-run-pack-tests -j -x -p contrib/packs/ -f test_action_download:DownloadGitRepoActionTestCase.test_run_pack_download
```
Before those change it was only possible to run all the tests from a particular pack which was rather slow and time consuming when working on a specific test.

Allow user to run a subset of pack tests using st2-run-pack-tests script

---

contrib/examples/actions/workflows/tests/orquesta-test-jinja-data-functions.yaml
contrib/examples/actions/workflows/tests/orquesta-test-yaql-data-functions.yaml
contrib/runners/orquesta_runner/setup.py
contrib/runners/orquesta_runner/tests/unit/test_functions_common.py
st2common/st2common/expressions/functions/data.py
st2common/st2common/util/casts.py
st2common/st2common/util/jinja.py
st2reactor/tests/unit/test_enforce.py
st2tests/integration/orquesta/test_wiring_functions.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/jinja-data-functions.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/yaql-data-functions.yaml

Move the use_none function to the common functions module. Register the use_none function in Orquesta. Add unit and integration tests for the use_none function.

Add the use_none function for Orquesta workflows

---

st2common/st2common/rbac/loader.py
st2common/st2common/util/misc.py
st2common/tests/unit/test_rbac_loader.py

This pull request fixes Python 3 compatibility in the RBAC definitions loader.
I found this issue while testing new enterprise packages on Ubuntu Bionic.
I also added tests so such issue will be caught autocratically in the future.

Fix Python 3 compatibility issue in the RBAC definitions loader

---

contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
contrib/runners/orquesta_runner/tests/unit/test_with_items.py
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/models/db/workflow.py
st2common/st2common/services/workflows.py

If the items list is empty, on transition to the task with items, orquesta fails to render the action specs correctly. For this use case, the orquesta conductor will now return the task spec with the list of action specs empty. The st2 workflow engine will recognize and handle this appropriately to set the task execution to completion in the conductor as well as the database records to progress the workflow execution to the next task(s).

Fix task with items but items list is empty for orquesta workflows

---

fixed-requirements.txt
requirements.txt
st2common/requirements.txt

The Kombu team had a release issue, and accidentally published the wrong code as 4.2.2 to PyPi. They have fixed this, and pulled 4.2.2. 
https://github.com/celery/kombu/issues/966

Fix kombu release version

---

st2common/st2common/transport/connection_retry_wrapper.py
st2common/tests/unit/test_connection_retry_wrapper.py

After spending a lot of time on Saturday and today I believe I managed to finally track down the issue with very slow tests on Travis.
It turns out that on Travis RabbitMQ throws a non-fatal ``Channel.open: (504) CHANNEL_ERROR - second 'channel.open' seen`` error when using our connection retry wrapper code which causes the code to "hang" and sleep for 10 seconds here https://github.com/StackStorm/st2/blob/master/st2common/st2common/transport/connection_retry_wrapper.py#L130 (the issue can be reproduced 100% of the time on Travis).
This happens very often so tests are up to 20 times and more slower on Travis than locally.
For example:
```bash
Local VM:
(virtualenv) vagrant@ubuntu-xenial:/data/stanley$ nosetests --with-timer --rednose --immediate -sv st2actions/tests/unit/test_scheduler.py …
```

Fix (workaround) for very slow test runs and timeouts on Travis CI

---

requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

This PR adds the AMQP package to st2common. In a recent update to
py-amqp (https://github.com/celery/py-amqp/pull/214) there was an
additional check added that uses a rabbit capability that is not
available in the rabbit version shipped in RHEL 6. Even though we pin
the correct version of py-amqp in our fixed-requirements.txt the lack of
any package directly requiring it allowed it to be skipped when building
final requirements.txt. Adding the requirement to st2common will make
the correct pinned version show up in requirements.txt.

Add amqp package to st2common

---

st2common/st2common/transport/connection_retry_wrapper.py

This pull request includes two improvements to our RabbitMQ connection retry code:
1. Fix the code so we don't try to re-establish a connection for indefinitely in a place where we are calling ``connection.ensure_connection``. Previously we didn't pass ``max_retries`` argument to that method so the connection was tried to be re-established for indefinitely and we didn't log any error.
2. Log an error which is received when failing to re-establish a connection on each retry attempt. This is intentionally logged as DEBUG because it's only fatal if we exhaust all the retry attempts and still fail to re-establish a connection (in that case we re-throw the exception and issue is considered as fatal).
This should help and give more insight in #4508 (it's likely that RabbitMQ server is not …

Improve RabbitMQ connection retry code

---

CHANGELOG.rst
contrib/packs/aliases/pack_install.yaml
st2client/st2client/commands/action_alias.py

Closes #4511 
This removes the redundant `pack install {{ packs }}` action-alias and instead replaces it with a single pattern.
After this fix, it is now possible to run the following:
```
$ st2 action-alias match 'pack install vsphere'
$ st2 action-alias execute -u st2admin 'pack install vsphere'
```
Also fixed the help text on `st2 action-alias match` to not imply that a list of matches is returned when in fact only a single match is returned.

Remove redundant action-aliases for pack install

---

st2reactor/st2reactor/container/sensor_wrapper.py
test-requirements.txt

This pull request fixes an issue with statsd debug log messages ending up in st2sensorcontainer log even when debug mode was disabled.
#4441 fixes that for majority of the services and scripts, but not for st2sensorcontainer. Sensor container is a bit special because it spawns sensors in a dedicated child processes which means we need to perform that monkey patching again in the child process to avoid those log messages.
Before:
```
2019-01-24 12:35:23,747 DEBUG [-] Using Python: 2.7.12 (/opt/stackstorm/st2/bin/python)
2019-01-24 12:35:23,747 DEBUG [-] Using config files: /etc/st2/st2.conf
2019-01-24 12:35:23,747 DEBUG [-] Using logging config: /etc/st2/logging.sensorcontainer.conf
2019-01-24 12:35:23,753 INFO [-] Connecting to database "st2" @ "127.0.0.1:27017" as user "None".
2019-01-24 …
```

Suppress statsd library debug log messages in sensor container when DEBUG mode is not enabled

---

st2common/st2common/middleware/instrumentation.py
st2common/st2common/util/sandboxing.py

This pull request updates instrumentation middleware so we don't submit any request metrics for all the "get one" API endpoints.
Previously we manually excluded some of the "most offending" API endpoints (get a single execution, etc.), but it's the safest to simply skip submitting metrics for all of "get one" API endpoints.
Submitting metrics for those endpoints results in too many unique metrics which is an anti-pattern and doesn't scale.

Don't submit metrics for any of the "get one" API endpoints

---

tools/submit-per-service-metrics-to-statsd

This pull request adds a simple Python script which sends per StackStorm service (process) level CPU, memory and IO utilization metrics to statsd.
The goal is to deploy to CICD and other servers and submit metrics to statsd via cron job.
Note 1: The script itself could also live in some other repo since it's not really fully coupled to StackStorm, but I decided to put it here because we have various lint and other checks running on Python files inside this repo.
Note 2: Eventually we could add this functionality to each StackStorm service. In fact, that's something I started to work on in the past, but @armab was against it, so that feature didn't move anywhere (the feature is fully configurable via st2.conf and it's disabled by default).

Add script for sending StackStorm service / process level metrics to statsd

---

fixed-requirements.txt
requirements.txt

This pull request updates ``python-gnugpg`` dependency we use to the latest version.
Previous version contains a security vulnerability - https://blog.hackeriet.no/cve-2019-6690-python-gnupg-vulnerability/, https://mail.python.org/pipermail/python-announce-list/2019-January/012154.html.
NOTE: This security vulnerability itself doesn't affect us because we only this library in an isolated scenario (encrypting debug tarball without using a passphrase), but it's still a good idea to upgrade it.
Thanks to @jfunction for reporting this.

Upgrade python-gnupg dependency

---

CHANGELOG.rst
st2common/st2common/util/crypto.py
st2common/tests/unit/test_crypto_utils.py

This pull request fixes an issue reported in #4513.
We didn't correctly handle unicode values so encryption didn't work for unicode values which were not of a correct AES block length (aka when padding was needed).
This pull request fixes that by making sure we convert data to bytes before we pass it to the padding function. It also includes a change in pad function so it handles bytes correctly.
Thanks to @dswebbthg and @nickbaum for reporting and working on this issue.
Resolves #4513.

Fix "cryptography_symmetric_encrypt" function and make sure it handles unicode values correctly

---

tools/submit-per-service-metrics-to-statsd

This pull request adds new ``--cpu-poll-interval`` command line argument to the script which submits service metrics to statsd.
Specifying interval larger than 0.1s will allow us for better accuracy.

Allow user to pass --cpu-poll-interval command line argument to submit metrics to statsd script

---

contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
contrib/runners/orquesta_runner/tests/unit/test_basic.py
contrib/runners/orquesta_runner/tests/unit/test_context.py
st2common/st2common/services/action.py
st2common/st2common/services/workflows.py
st2common/st2common/util/config_loader.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/config-context-action.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/config-context.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/config-context.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/config.schema.yaml

This pull request fixes a bug with ``{{ confix_context.<config item name> }}`` notation not working for action parameter default values for action executions which are scheduled via Orquesta (aka part of an Orquesta workflow).
I was working on some st2community pack changes and improvements and while testing and developing the workflow I noticed "{{ config_context }}" notation doesn't work for executions scheduled via Orquesta (e.g. https://github.com/StackStorm/stackstorm-st2community/pull/1/files#diff-3c8d6de4c078da34b194a061826b147dR13), but it works just fine if those actions are run outside of the Orquesta workflow context.
After some digging in, I found orquesta runner doesn't add ``pack`` value to the execution context so ``get_config`` method will always return an empty dict …

Fix a bug with "{{ config_text.foo }}" not working for executions scheduled via Orquesta workflow

---

contrib/core/actions/send_mail/send_mail

It seems that perhaps it is necessary to change the charset to UTF-8 in two places to get the body correctly encoded (exactly why this is so is a little bit unclear to me, I solved this by trail and error). I also added that the subject should be utf-8 encoded, to make sure that non-ascii characters are allowed there.

UTF-8 encode both body and subject of email

---

CHANGELOG.rst
st2common/st2common/log.py
st2common/st2common/service_setup.py
st2common/tests/integration/test_service_setup_log_level_filtering.py
st2tests/st2tests/fixtures/conf/logging.api.audit.conf
st2tests/st2tests/fixtures/conf/logging.api.debug.conf
st2tests/st2tests/fixtures/conf/logging.api.info.conf
st2tests/st2tests/fixtures/conf/st2.tests.api.audit_log_level.conf
st2tests/st2tests/fixtures/conf/st2.tests.api.debug_log_level.conf
st2tests/st2tests/fixtures/conf/st2.tests.api.info_log_level.conf
st2tests/st2tests/fixtures/conf/st2.tests.api.system_debug_true.conf
st2tests/st2tests/fixtures/conf/st2.tests.conf

This pull request resolves an issue with log messages with log level AUDIT ending up in regular service log file (``<service>.log``) in addition to the service audit log file (``<service>.audit.log``).
We implemented ``AUDIT`` log level by adding a new log level constant which contains the highest log level number (``CRITICAL`` + 10).
Default Python log level filtering works using "include log messages with log level <set> and above" approach. This means messages with ``AUDIT`` log level will always be included in the logs because ``AUDIT`` is the highest level.
In most cases that's not desired. That's especially true for production deployment where default log level is ``INFO`` and we have dedicated log file with audit log messages. We don't want audit log messages to also end up in the …

Don't include log messages with log level "AUDIT" in regular service log file

---

Makefile
fixed-requirements.txt
requirements.txt
scripts/travis/build.sh
st2client/requirements.txt
st2common/requirements.txt

Update requirements files with updated PyYAML and flex constraints.
I also add a make target to run `make requirements` and check that it doesn't change any requirements files (eg: some files were changed but not checked into git), and integrated that into the Travis tests.
H/T: @m4dcoder

Update pyyaml and flex contraints

---

CHANGELOG.rst
st2common/st2common/logging/misc.py
st2common/st2common/service_setup.py
st2common/tests/integration/test_service_setup_log_level_filtering.py
st2tests/st2tests/fixtures/conf/st2.tests.api.system_debug_true_logging_debug.conf

In the past, I opened a change so we ignore kombu ``heartbeat_tick`` debug log messages which are logged every 2 ms by default when either ``--debug`` service command line flag is used or when ``system.debug`` st2.conf config option is set to ``True``.
While troubleshooting release workflows on st2cicd server, I found an edge case.
If ``DEBUG`` log level is set in the service logging config, but ``--debug flag`` / ``system.debug`` config option is not used, those messages won't be ignored.
This is not desired, because those messages will pollute the logs and make it very hard to find other actual important DEBUG and non DEBUG log messages.
Here is an example from st2workflowengine.log on st2cicd:
```bash
...
2019-02-19 08:11:54,608 140494121387664 DEBUG connection [-] heartbeat_tick : for …
```

Always ignore kombu library "heartbeat_tick" debug log messages

---

CHANGELOG.rst

We didn't include an entry for #4476 in the master changelog, only in 2.10 branch

Added 2.10.1 changelog entry to master branch

---

CHANGELOG.rst
contrib/examples/actions/workflows/tests/orquesta-test-jinja-task-functions.yaml
contrib/examples/actions/workflows/tests/orquesta-test-yaql-task-functions.yaml
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/orquesta_functions/runtime.py
contrib/runners/orquesta_runner/requirements.txt
contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
contrib/runners/orquesta_runner/tests/unit/test_functions_task.py
requirements.txt
st2actions/st2actions/workflows/workflows.py
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/models/db/workflow.py
st2common/st2common/services/workflows.py
st2common/tests/unit/services/test_workflow.py
st2common/tests/unit/services/test_workflow_cancellation.py
st2common/tests/unit/services/test_workflow_write_conflict.py
st2common/tests/unit/test_db_task.py
st2tests/integration/orquesta/test_wiring_error_handling.py
st2tests/integration/orquesta/test_wiring_functions_task.py
st2tests/st2tests/base.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/jinja-task-functions.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/yaql-task-functions.yaml

Refactor workflow engine and database to accommodate routing info. Add route to the task execution table and save the route info from the task execution requests from orquesta conductor. Pass route to orquesta conductor when updating task flow. Refactor the custom task function for YAQL and Jinja to identify the correct task and use the task and route info to query the database for the task result and other data.

Apply the orquesta execution graph performance fix

---

CHANGELOG.rst
contrib/examples/actions/orquesta-test-with-items-failure.yaml
contrib/examples/actions/workflows/tests/orquesta-test-with-items-failure.yaml
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
contrib/runners/orquesta_runner/tests/unit/test_with_items.py
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2tests/integration/orquesta/test_wiring_with_items.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/with-items-failure.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/with-items-failure.yaml

When one or more items fail in a with items task in an orquesta workflow, the task will be stuck in running. This patch updates requirement to the commit with the fix. Unit and integration tests are also included to cover the test case. Fixes #4523.

Fix orquesta with items task stuck in running

---

st2api/tests/unit/controllers/v1/test_base.py
st2common/st2common/middleware/cors.py

Prior to this commit if you sent a request from an origin not listed in `allowed_origins` we would respond with `null` for the `Access-Control-Allow-Origin` header. Per [mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Directives) `null` should not be used as some clients will allow the request to go through. This PR returns the first of our allowed origins if the requesting origin is not a supported origin.

Fix improper CORS return

---

contrib/examples/actions/workflows/tests/orquesta-test-jinja-task-functions.yaml
contrib/examples/actions/workflows/tests/orquesta-test-yaql-task-functions.yaml
contrib/runners/orquesta_runner/tests/unit/test_functions_task.py
st2tests/integration/orquesta/test_wiring_functions_task.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/jinja-task-functions.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/yaql-task-functions.yaml

The task function related unit tests are randomly failing because the route ID changes depending on the order of action execution. The workflows are rewritten to be more deterministic.

Fix random failing orquesta unit tests

---

CHANGELOG.rst
st2api/st2api/app.py
st2api/tests/unit/controllers/v1/test_base.py
st2common/st2common/constants/api.py
st2common/st2common/middleware/cache.py

This PR adds cache control header so that clients will always refresh their data from the API instead of favoring cached version. This was encountered in ST2Flow 2.0 development, loading workflows from the API.

Add cache control header

---

CHANGELOG.rst
st2actions/st2actions/notifier/notifier.py
st2actions/tests/unit/test_notifier.py

Change in #4536 inadvertently introduced a regression inside notifier service which would cause generic action notify trigger to only be dispatched for completed states even if custom states were specified using ``action_sensor.emit_when`` config option.
Tests didn't catch this issue, because we only had tests for ``_post_generic_trigger`` method, but not for main ``process()`` one where the issue lived.
Thanks to Shu Sugimoto (@shusugmt) for reporting this issue.

Fix regression with generic action notify trigger in notifier service

---

CHANGELOG.rst
st2common/st2common/middleware/logging.py
st2common/tests/unit/test_logging_middleware.py

Our logging middleware didn't mask / remove auth token and api key values if those were provided via query parameters and not headers.
Keep in mind that providing it as header is still preferred, especially when integrating with 3rd party services, because a lot of services log actual full URL with a query string which could mean leaking those values there. I will add a note about that to the docs.
Resolves #4589.
Also, as commented on #4589, I believe that issue actually talks about token being logged in a loadbalancer log or similar because the log line doesn't look anything like st2api log line. In that scenario we can't do anything about that and that's why I mentioned above, using headers is preferred (and I will also document that).

Make sure we don't log sensitive query params in the st2api log file

---

st2actions/st2actions/notifier/notifier.py

Small addition to #4591.
I've moved the metric instrumentation inside the method, this way we don't submit metrics when method returns early / immediately.
Those values / outliers could also be filtered on the metrics backend side, but it's easier to simply not to send those metrics.

Don't submit notifier metrics when a method returns early

---

CHANGELOG.rst
contrib/examples/actions/orquesta-with-items-concurrency.yaml
contrib/examples/actions/workflows/orquesta-with-items-concurrency.yaml
st2common/st2common/services/workflows.py
st2tests/integration/orquesta/test_performance.py

Acquire a distributed lock, keyed on workflow execution ID, in the workflow engine before handling the action execution completion. This avoids the performance hits from retrying write conflicts for workflows with a lot of parallelism such as a with items task with many items and no concurrency. The coordination service in st2 needs to be setup for the solution to take into effect.

Acquire lock in workflow engine before handling action execution completion

---

st2actions/st2actions/config.py
st2actions/st2actions/scheduler/config.py
st2actions/st2actions/workflows/config.py

Some services (``st2actionrunner``, ``st2scheduler``, ``st2workflowengine``) didn't specify a default path to the config file (``/etc/st2/st2.conf``) so they would fail to start (e.g. in a dev environment) if ``--config-file`` argument was not explicitly provided.
Other services already correctly handle that.
Related to #4111.

Fix default config file location for some services

---

CHANGELOG.rst
st2common/st2common/metrics/drivers/statsd_driver.py
st2common/st2common/util/misc.py
st2common/tests/unit/test_metrics.py

This pull request updates our statsd driver to treat any exception which may be thrown by the driver as non-fatal.
Metrics driver related error should never break or degrade application performance and this pull request ensures that is indeed the case.
One of our users reported an issue with statd driving breaking / hanging the application when a metric backend server goes down. Initially I wasn't able to replicate it (statsd uses UDP so it should be fire and forget and there should be no exceptions).
Today the user provided log files. It turns out the problem lies in DNS resolution errors which can happen when establishing a connection to the backend server.
If a hostname and not IP address is used for metric backend and DNS resolution fails, statsd will propagate this exception all the …

Treat any statsd metric driver related errors as non-fatal (just log the errors)

---

CHANGELOG.rst
st2api/st2api/controllers/resource.py
st2api/st2api/controllers/v1/actionexecutions.py
st2api/tests/unit/controllers/v1/test_executions.py
st2client/st2client/commands/action.py
st2client/st2client/commands/resource.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/router.py

Previously `GET /api/v1/executions/{id}` did not have the `include_attributes` or `exclude_attributes` query parameters, meaning it couldn't filter the output of large executions. This PR adds that ability.
@Kami are any other modifications necessary?
**TODO**

Added include_attributes and exclude_attributes to GET /api/v1/executions/{id}

---

conf/st2.conf.sample
st2common/st2common/config.py
st2common/st2common/service_setup.py

This pull request adds a config option which specifies if a service should be registered in a service registry (and in any case, it's a good idea to have a flag so people can opt-out, if they have a valid reason for it, once it will default to ``True``).
To work around bug / issue in - https://github.com/StackStorm/stackstorm-ha/issues/57 it defaults to ``False``.
I forgot that the etcd ``tooz`` driver we use is old and doesn't support group functionality.
I opened a PR for etcd3gw driver group functionality support in tooz quite a long time ago. I will look into updating version ``tooz`` version we use and once that's done, I will flip that config value to ``True``.

Temporary disable service registry service registration to work around issue in stackstorm-ha

---

contrib/chatops/actions/post_message.yaml
contrib/chatops/actions/post_result.yaml
contrib/chatops/actions/workflows/post_result.yaml
contrib/chatops/rules/notify_hubot.yaml
st2api/st2api/controllers/v1/aliasexecution.py
st2common/st2common/models/api/action.py

This is part of the work to add a Microsoft Teams (via BotFramework) adapter.
Microsoft Teams needs a bit more context other than the requesting user and the channel name.
Instead of adding the minimum amount of context, this PR adds a `context` parameter to the `post_` actions in the chatops pack and adds it to the notify `on_complete` dictionary. The `context` parameter maximizes the amount of information available to the notification mechanism, in the hopes that it can be reused by other adapters.
* st2chatops in StackStorm/st2chatops#121
* hubot-stackstorm changes in StackStorm/hubot-stackstorm#164
* Documentation for configuring Microsoft Teams with BotFramework in StackStorm/st2docs#872

Add chat context to chatops

---

CHANGELOG.rst
st2client/st2client/commands/workflow.py
st2client/st2client/models/core.py

Fixes #4614 
Before:
```shell
lhill@ewcdemo:~$  st2 workflow inspect --action examples.orquesta-with-items
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized - One of Token or API key required. for url: http://127.0.0.1:9101/v1/workflows/inspect
lhill@ewcdemo:~$
```
After:
```shell
lhill@ewcdemo:~$  st2 workflow inspect --action examples.orquesta-with-items
No errors found in workflow definition.
lhill@ewcdemo:~$
```

Add auth token to st2 workflow inspect

---

contrib/examples/actions/workflows/render_config_context.yaml
tools/launchdev.sh

``render_config_context`` action has been moved from ``tests`` to ``fixture`` pack to fix ``st2-self-check`` and to follow the existing layout for end to end tests in ``st2tests/tests`` pack - https://github.com/StackStorm/st2tests/pull/153.
This pull request updates affected code to use ``fixtures`` instead of ``tests`` pack.

Action has been moved from tests to fixtures pack, update affected code

---

CHANGELOG.rst
conf/st2.package.conf

While testing some other changes, I noticed fix in #4538 doesn't appear to be working in production with packages.
It turns out we were not using correct gunicorn logging config with StackStorm packages (gunicorn config makes sure DEBUG and non-audit log messages don't end up in non-audit service log file bi default).
Related PR: https://github.com/StackStorm/st2-packages/pull/607

Use correct gunicorn logging config with st2 packages (don't include AUDIT log messages in non-AUDIT log file)

---

CHANGELOG.rst
st2common/st2common/services/triggers.py
st2common/st2common/triggers.py

This pull request updates the code to log non-fatal errors under ``DEBUG`` log level instead of ``ERROR``.
Previously we logged those under ``ERROR`` which caused a lot of unnecessary confusion.
During service bootstrap phase and when running register content script we register internal trigger types (among other things).
This operation is idempotent and as such, some of the possible errors (not unique and object already exists error) are non-fatal. An error represents a non-fatal race which just means that a particular trigger has already been registered by a different service / process.
NOTE: Adding tests for that would be hard. We would need to replicate the race which means spawning multiple processes (using multiple eventlets won't work here, we need real parallelism to replicate it) …

Log non-fatal errors during service bootstrap phase under DEBUG instead of ERROR

---

CHANGELOG.rst
contrib/examples/actions/chains/decrypt_kv_jinja_filter.yaml
contrib/runners/action_chain_runner/action_chain_runner/action_chain_runner.py
st2common/st2common/expressions/functions/datastore.py
st2common/st2common/services/keyvalues.py
st2common/tests/unit/test_jinja_render_crypto_filters.py

This fixes #4633.
This changes the implementation of custom Jinja filter `decrypt_kv` to be able to handle user scope value.

Fixed a problem not to decrypt user scope data store value in Jinja expression

---

CHANGELOG.rst
contrib/examples/actions/orquesta-streaming-demo.meta.yaml
contrib/examples/actions/workflows/orquesta-streaming-demo.yaml

This pull request adds new example action for testing ``st2 execution tail`` command with Orquesta workflows (it's a clone of the existing action we already have for action-chain and Mistral workflows).
Here (https://github.com/StackStorm/st2tests/pull/152) I noticed we don't have any integration tests for ``st2 execution tail`` command for Orquesta workflows so I'm fixing that (we do have unit ones though).

Add example action for testing "st2 execution tail" functionality with Orquesta workflows

---

CHANGELOG.rst
contrib/examples/actions/orquesta-streaming-demo.meta.yaml
contrib/examples/actions/workflows/orquesta-streaming-demo.yaml
st2api/tests/unit/controllers/v1/test_executions.py
st2api/tests/unit/controllers/v1/test_executions_auth.py

This is a remaining work of #4634. This adds end-to-end tests for it.
The tests in this patch call `/v1/executions` endpoint in the following conditions.
* without user specification (auth.enable = False)
* with specific user (via X-Auth-Token and St2-Api-Key)
* with specific user, but the user-scope value corresponding to the specified key is not registered

Added end-to-end tests to coverage the past correction of decrypt_kv filter

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2client/requirements.txt
st2common/requirements.txt

Just some house keeping before the release.
I noticed we didn't pin ``bcrypt`` dependency so I also fixed that so we have reproducible builds.

Update dependencies to latest versions

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actions.py
st2common/bin/st2-self-check
st2common/st2common/util/pack_management.py

This pull request fixes a small issue I identified while testing latest st2flow packages.
Right now if pack permissions are not configured correctly and st2api doesn't have permission to write to the pack directory / sub-directory, Internal Server Error bubbles up all the way to st2flow.
This pull request fixes so we now throw a more user-friendly (non internal server error) error message.
From st2api.log:
```bash
...
IOError: [Errno 13] Permission denied: u'/opt/stackstorm/packs/fixtures/actions/aaa' (_exception_data={},_exception_class='IOError',_exception_message=u"[Errno 13] Permission denied: u'/opt/stackstorm/packs/fixtures/actions/aaa'")
...
````

Throw a more user-friendly error on permission denied when trying to to write a pack data file

---

conf/HA/nginx/st2.conf.blueprint.sample
conf/HA/nginx/st2.conf.controller.sample

- Fixes #4665 where incorrect rewrite rule was present resulting in non-working `/stream` endpoint.
- Cleans up `rewrite ^/auth/(.*) /auth/$1 break;` nginx rewrite rules that made no sense.
- Updates nginx configs with most recent fixes and additions made to https://github.com/StackStorm/st2/blob/master/conf/nginx/st2.conf
- Improve st2 nginx config for HA controller to better handle switching between upstream backends via [`proxy_next_upstream`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream)
~TODO: st2docs update: https://docs.stackstorm.com/reference/ha.html~ (auto-updated based on `st2` files)

Fix & Update nginx example confings for HA setup

---

CHANGELOG.rst
conf/st2.conf.sample
st2common/st2common/config.py
st2common/st2common/util/sandboxing.py
st2common/tests/unit/test_util_sandboxing.py

This pull request includes additional fixes on top of #4666.
End to end tests on actual distros we support showed that previous approach was not robust enough and didn't work correctly on all the distros.

Improve the approach we use to determine Python 3 system lib path

---

st2common/bin/st2-self-check

This pull request includes a small improvement to ``st2-self-check``.
On test failure, we now print output of ``st2 run`` command. Before that, we didn't include any output so it was impossible to easily trace back some errors (e.g. ones which are related to test not taking the correct parameters or similar).
Before:
```bash
Attempting Test tests.test_inherit_env_python_script_runner...ERROR! (0s)
Attempting Test tests.test_inquiry_chain...OK! (47s)
```
After:
```bash
Attempting Test tests.test_inherit_env_python_script_runner...ERROR! (0s)
Test output: ERROR: 400 Client Error: Bad Request
MESSAGE: Additional properties are not allowed ('token', 'protocol' were unexpected) for url: http://127.0.0.1:9101/v1/executions
Attempting Test tests.test_inquiry_chain...OK! (47s)
```

Update st2-self-check so it prints out output of st2 run on test failure

---

CHANGELOG.rst
st2common/st2common/models/db/execution_queue.py
st2common/tests/unit/test_db.py
st2tests/st2tests/base.py

This pull request limits full database index names to 65 characters.
For the most part we don't explicitly specify index name when we define index in the code. This means MongoDB automatically infer the name from db, collection and field name. For example ``st2.action_execution_d_b.status.action.ref.start_timestamp`` (``<db name>.<collection name>.<all the indexed field names>``.
This pull request explicitly specifies shorter index names for some indexes which don't work with AWS DocumentDB due to the limit (MongoDB itself claims it supports index names up to 128 characters, but that doesn't work with DocumentDB).
We don't officially support AWS DocumentDB, but it's a relatively easy change so it doesn't hurt us to include it.
In addition to that, there is a bigger long term question …

Limit database index field names to 65 characters

---

CHANGELOG.rst
contrib/examples/actions/orquesta-st2kv-default.yaml
contrib/examples/actions/workflows/orquesta-st2kv-default.yaml
contrib/examples/actions/workflows/orquesta-st2kv.yaml
contrib/runners/orquesta_runner/orquesta_functions/st2kv.py
contrib/runners/orquesta_runner/tests/unit/test_functions_st2kv.py
st2common/st2common/persistence/keyvalue.py
st2common/st2common/services/config.py
st2common/st2common/services/keyvalues.py
st2common/st2common/util/keyvalue.py
st2tests/integration/orquesta/test_wiring_functions_st2kv.py

Fix the orquesta st2kv to return empty string and null values correctly and allow st2kv function to return a supplied default value for nonexistent key. Closes #4678

Refactor the orquesta st2kv function

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2client/requirements.txt
st2common/requirements.txt

This PR updates the `requests` package version to the latest (2.22.0) - Closes #4680

Update the requests library version to latest (2.22.0) in requirements

---

CHANGELOG.rst
contrib/examples/actions/orquesta-fail-manually.yaml
contrib/examples/actions/workflows/orquesta-fail-manually.yaml
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/services/workflows.py
st2tests/integration/orquesta/test_wiring_error_handling.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-manually-with-recovery-failure.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/fail-manually.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-manually-with-recovery-failure.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/fail-manually.yaml

The workflow conductor already directs which next tasks to run next, taking into account of workflow status. Remove check for workflow completion status in the workflow service that restricts any more tasks to be executed. Add unit tests to cover use cases where there is a fail in task transition and other recovery/remediation tasks. These other tasks should be allowed to run on failure.

Refactor workflow service to handle tasks that run on fail

---

.travis.yml
Makefile
fixed-requirements.txt

This PR upgrades pip from previously strictly pinned `9.x` to currently latest one which is `19.x`.
Part of StackStorm/st2#4681 and https://github.com/StackStorm/st2-packages/pull/614 and https://github.com/StackStorm/st2packaging-dockerfiles/pull/70

Upgrade pip to latest 19.x version

---

CHANGELOG.rst
contrib/examples/actions/workflows/tests/orquesta-test-jinja-data-functions.yaml
contrib/runners/orquesta_runner/tests/unit/test_functions_common.py
st2common/st2common/expressions/functions/data.py
st2common/st2common/util/db.py
st2common/tests/unit/test_util_db.py
st2tests/integration/orquesta/test_wiring_functions.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/jinja-data-functions.yaml

Refactor the filter to_yaml_string used in YAQL/Jinja expressions to be able to handle mongodb base types such as BaseDict and BaseList. The filter will call a helper function to recursively convert BaseDict and BaseList to python dict and list respectively. Fixes #4700.

Fix expression function to_yaml_string to handle mongodb base types

---

st2tests/integration/orquesta/test_wiring_with_items.py

Fix the orquesta with items concurrency cancelation integration test. After cancelation is requested, delete all the temporary files instead of subset. There could be a race where the subset of files are not the files being picked up for concurrent processing.

Fix orquesta with items concurrency integration test

---

conf/st2.conf.sample
st2common/st2common/config.py
st2common/st2common/services/workflows.py
st2reactor/tests/unit/test_garbage_collector.py

Fix logic in identifying orphaned workflow executions which causes long running workflow executions to be canceled. Disable this garbage collection feature for orphaned workflow executions by default.

Fix the garbage collection for orquesta workflow executions

---

conf/st2.conf.sample
st2common/st2common/config.py
st2common/st2common/services/workflows.py
st2reactor/tests/unit/test_garbage_collector.py

Cherry pick from https://github.com/StackStorm/st2/pull/4733
Fix logic in identifying orphaned workflow executions which causes long running workflow executions to be canceled. Disable this garbage collection feature for orphaned workflow executions by default.

Fix the garbage collection for orquesta workflow executions (v3.1)

---

CHANGELOG.rst
contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
contrib/runners/orquesta_runner/tests/unit/test_cancel.py

Allow the workflow execution cancelation to proceed even if the workflow execution is not found or completed otherwise the method will raise an exception and the workflow execution will be stuck with a canceling status. Fixes #4735

Allow cancel to proceed if workflow execution is not found or completed

---

CHANGELOG.rst
contrib/packs/tests/test_action_download.py
st2common/st2common/util/pack_management.py

First part of Fixes StackStorm/discussions#354.
If pack version is not specified, install the latest version from pack index.json (https://index.stackstorm.org/v1/index.json), otherwise install from master branch as today.
Note: Direct github/repo install is not considered an Exchange index hit, therefore it is not covert by this fix.
Closes #4384

Install pack with the latest tag

---

contrib/examples/actions/orquesta-sequential.yaml

Add the pack explicitly in metadata so when the user follow the instruction to install the action, it will be registered under the examples pack and not under default pack.

Fix orquesta example used in first section of docs

---

CHANGELOG.rst
Makefile
contrib/runners/action_chain_runner/dist_utils.py
contrib/runners/announcement_runner/dist_utils.py
contrib/runners/http_runner/dist_utils.py
contrib/runners/inquirer_runner/dist_utils.py
contrib/runners/local_runner/dist_utils.py
contrib/runners/mistral_v2/dist_utils.py
contrib/runners/noop_runner/dist_utils.py
contrib/runners/orquesta_runner/dist_utils.py
contrib/runners/python_runner/dist_utils.py
contrib/runners/remote_runner/dist_utils.py
contrib/runners/winrm_runner/dist_utils.py
scripts/dist_utils.py
scripts/dist_utils_old.py
st2actions/dist_utils.py
st2api/dist_utils.py
st2auth/dist_utils.py
st2client/dist_utils.py
st2common/dist_utils.py
st2common/tests/fixtures/requirements-used-for-tests.txt
st2common/tests/unit/test_dist_utils.py
st2debug/dist_utils.py
st2exporter/dist_utils.py
st2reactor/dist_utils.py
st2stream/dist_utils.py
st2tests/dist_utils.py

This pull request fixes ``dist_utils.py`` module so it doesn't rely on internal pip functionality and so it works with latest pip version.
While working on another project which has code similar to our ``dist_utils.fetch_requirements`` I noticed it fails with newer versions of pip with the following error:
```bash
Failed to import parse_requirements from pip: cannot import name pep425tags
Using pip: 19.2.1
```
In our case, the error itself could manifest itself when installing ``st2client`` using a specific version of pip.
Main problem is that the code in dist_utils.py depends on internal pip functionality which can change across the pip versions (and it already changed in the past and that caused us quite some trouble back then).
This solution re-implements ``fetch_requirements`` so it …

Fix dist_utils.py so it doesn't rely on internal pip API

---

CHANGELOG.rst
contrib/runners/http_runner/http_runner/http_runner.py
contrib/runners/http_runner/http_runner/runner.yaml
contrib/runners/http_runner/tests/unit/test_http_runner.py

This pull request adds support for blacklisting hosts to the HTTP runner by adding a new ``hosts_blacklist`` attribute.
With this attribute, pack author can specify a list of hosts which will be blacklisted (aka won't work) with the HTTP runner.
For example, if an operator wants to allow StackStorm users to use HTTP runner, without being able to hit some hosts, they could define new ``mypack.http`` action which metadata could look something like this:
```yaml
---
name: http
runner_type: "http-request"
parameters:
hosts_blacklist:
default:
- "localhost"
- "127.0.0.1"
- "::1"
immutable: true
```
NOTE: As with any feature which could be used in a security sensitive context, it's important to know that this feature doesn't cover all scenarios and security is all about layers.
This means that …

Add support for blacklisting hosts to the HTTP runner

---

.travis.yml
CHANGELOG.rst
Makefile
contrib/runners/http_runner/http_runner/http_runner.py
contrib/runners/http_runner/http_runner/runner.yaml
contrib/runners/http_runner/tests/unit/test_http_runner.py
scripts/travis/run-nightly-make-task-if-exists.sh
st2api/st2api/controllers/v1/actionexecutions.py
st2tests/st2tests/api.py
tox.ini

Closes #4758
The error caused in #4758 is because the ldap rbac is expecting the document returned from the ActionExecutionDB to contain action.pack and action.uid, but they are currently not being returned. 
Here is the traceback I got from the rbac
```
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2rbac_enterprise_backend/utils.py", line 120, in assert_user_has_resource_db_permission
permission_type=permission_type)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2rbac_enterprise_backend/utils.py", line 287, in user_has_resource_db_permission
permission_type=permission_type)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2rbac_enterprise_backend/resolvers.py", line 673, in user_has_resource_db_permission
pack_db = …
```

fixing enterprise ldap issue with execution view

---

.travis.yml
Makefile

This pull request fixes nightly build failure in https://travis-ci.org/StackStorm/st2/jobs/569901661.
We didn't correctly use ``nosetests`` binary from the virtualenv.
```bash
...
0.35s$ if [ "${IS_NIGHTLY_BUILD}" = "yes" ]; then ./scripts/travis/run-nightly-make-task-if-exists.sh "${TASK}"; fi
Running the following nightly tasks: ci-unit-nightly
============== ci-unit-nightly ==============
nosetests --rednose --immediate --with-parallel -s -v  contrib/runners/mistral_v2/tests/unit
Usage: nosetests [options]
nosetests: error: no such option: --rednose
make: *** [ci-unit-nightly] Error 2
....
```

Fix nightly build

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actionexecutions.py
st2tests/st2tests/api.py

Fix rbac with execution view where the rbac is unable to verify the pack or uid of the execution because it was not returned from the action execution db. This would result in an internal server error when trying to view the results of a single execution. This fix is cherry picked from selected commits at PR https://github.com/StackStorm/st2/pull/4759.

Fix rbac execution_view unable to verify the pack or uid (v3.1)

---

contrib/core/actions/local_sudo.yaml

Presumably, `core.local_sudo` only runs commands on `localhost`, and _not_ any remote host(s). The `cmd` parameter description should reflect that.

Fix copy/paste typo

---

CHANGELOG.rst
st2client/st2client/models/core.py
st2client/tests/unit/test_client_executions.py

The [executions re_run route](https://api.stackstorm.com/api/v1/executions/#/action_execution_rerun_controller.post) in st2api allows for a user to be specified in the request body.
This PR extends the same functionality to st2client.

Add user field to re_run method

---

st2common/bin/st2-run-pack-tests

The pack CI Makefile runs the st2-run-pack-tests script install the coverage module if the coverage flag is passed.
Previously, if the script was run with the [`-c` and `-j` flags (with coverage and just run the tests)](https://github.com/StackStorm-Exchange/ci/blob/master/.circle/Makefile#L108), the script would skip the section that installs the coverage module. Luckily, nose is smart enough to still run tests without coverage, but when it reports that the coverage module isn't installed, it logs it as [an error](https://circleci.com/gh/StackStorm-Exchange/stackstorm-git/123):
> nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
This erroneous reporting can become a troubleshooting rabbit hole when pack CIs fail.
This PR ensures that at least the …

Ensure that the coverage module is installed if coverage is enabled

---

CHANGELOG.rst
contrib/core/actions/error.yaml
contrib/hello_st2/pack.yaml
contrib/packs/actions/delete.yaml
contrib/packs/actions/download.yaml
contrib/packs/actions/get_pack_dependencies.yaml
contrib/packs/actions/install.meta.yaml
contrib/packs/actions/pack_mgmt/delete.py
contrib/packs/actions/pack_mgmt/download.py
contrib/packs/actions/pack_mgmt/get_pack_dependencies.py
contrib/packs/actions/pack_mgmt/register.py
contrib/packs/actions/pack_mgmt/virtualenv_setup_prerun.py
contrib/packs/actions/virtualenv_prerun.yaml
contrib/packs/actions/workflows/install.yaml
contrib/packs/pack.yaml
contrib/packs/tests/test_action_download.py
contrib/packs/tests/test_get_pack_dependencies.py
contrib/packs/tests/test_virtualenv_setup_prerun.py
st2api/st2api/controllers/v1/packs.py
st2api/tests/unit/controllers/v1/test_packs.py
st2client/st2client/commands/pack.py
st2client/st2client/models/core.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2common/st2common/util/pack_management.py

Fixes https://github.com/StackStorm/discussions/issues/354
Resolves https://github.com/StackStorm/st2/issues/3336
Closes https://github.com/StackStorm/st2/issues/3698
1. `packs.install` workflow changed from `achtion-chain` to `orquesta` for workflow complexity.
2. Download all packs and dependency packs before `install pack requirements` and `register pack`.
3. Register packs in reverse order, it means the last dependency pack will be installed first.
4. Workflow fails on any time if conflict pack is recognized,  downloaded packs will be removed.
5. New option `--skip` (default value is False) for skipping dependencies check:  `st2 install pack --skip`
6. Only case that will check conflict is that if pack was installed and dependency pack has specified pack version.
7. Nested level of …

Pack dependency management

---

CHANGELOG.rst
conf/st2.conf.sample
contrib/runners/python_runner/python_runner/python_runner.py
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
scripts/travis/prepare-integration.sh
st2common/st2common/config.py
st2common/st2common/util/green/shell.py
st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py
st2tests/st2tests/resources/packs/pythonactions/actions/print_to_stdout_and_stderr.py
tools/launchdev.sh
tools/screen-configs/st2actionrunner.conf
tools/screen-configs/st2api.conf
tools/screen-configs/st2auth.conf
tools/screen-configs/st2garbagecollector.conf
tools/screen-configs/st2notifier.conf
tools/screen-configs/st2resultstracker.conf
tools/screen-configs/st2rulesengine.conf
tools/screen-configs/st2scheduler.conf
tools/screen-configs/st2sensorcontainer.conf
tools/screen-configs/st2stream.conf
tools/screen-configs/st2timersengine.conf
tools/screen-configs/st2workflowengine.conf

While testing large datasets in actions, I came across massive CPU spikes for a relatively small dataset (~8MB) being returned from the action. While investigating the issue I found two problems that were consuming the CPU. The first issue was documented in #4798. The second issue was with how the action was created. When the subprocess is created without the buffer size, it defaults to zero (unbuffered). According to the subprocess docs, 
>"If you experience performance issues, it is recommended that you try to enable buffering by setting bufsize to either -1 or a large enough positive value (such as 4096)." https://docs.python.org/2/library/subprocess.html.
The bufsize can be a discussion whether to use the system default or a large value. After making this change on my local machine I …

fixing subprocess to use system buffer instead of being unbuffered

---

st2common/st2common/util/param.py

Add try-catch block to handle unknown errors when getting pack config in render_final_params. Copy the try-catch block from render_live_params.

Add try block to handle get config errors in render_final_params

---

CHANGELOG.rst
st2auth/st2auth/controllers/v1/auth.py
st2auth/tests/unit/controllers/v1/test_token.py

This pull request fixes a bug with ``POST /auth/v1/tokens``API endpoint returning internal server error when running under gunicorn without ``auth.api_url`` config option being set.
NOTE: First I couldn't reproduce the issue, but it turns out it only happens when using gunicorn deployment.
When running st2auh directly, the WSGI implementation simply casts all the "None" header values to empty strings, but that's not the case for gunicorn.
Originally reported here - https://forum.stackstorm.com/t/ldap-error-handling-api-call-failed-expected-string-or-buffer/893.

Fix a bug with authentication API endpoint returning internal server error under gunicorn if auth.api_url config option was not set

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/services/workflows.py

Update orquesta requirements to latest commit with performance fix on handling with items result. Previously, result for each item is stored temporarily in the conductor until the task is completed. If there are a lot of items and/or result size for each item is huge, there is an impact on performance when recording the conductor state to the database. To fix, st2 storees the accumulated result with the task execution record and passes the accumulated result with the action execution event. The conductor does not process the accumuldated result until the task is determined by the conductor to be completed.

Refactor handling of with items result

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/services/workflows.py
st2tests/integration/orquesta/test_wiring_error_handling.py

Remove rendering of workflow output automatically when updating task state for orquesta workflows. This caused workflow output to render incorrectly in certain use case, specifically the `task` function where if the workflow output calls the task function for the last task, the information returned is not accurate. The render_workflow_output function must be called separately.

Remove automatic rendering of workflow output when updating task state

---

CHANGELOG.rst
Makefile
contrib/linux/requirements.txt
fixed-requirements.txt
requirements.txt
st2actions/in-requirements.txt
st2actions/requirements.txt
st2api/requirements.txt
st2auth/requirements.txt
st2client/requirements.txt
st2common/requirements.txt
st2debug/requirements.txt
st2exporter/requirements.txt
st2reactor/requirements.txt
st2stream/requirements.txt
test-requirements.txt

This pull request includes the following changes:
1. Update ``cryptography`` dependency to v2.8 since version of ``requests`` we use depends on that version. As per https://github.com/StackStorm/st2/issues/4818#issuecomment-555545997, that is not actually a fatal issue since pip just prints a warning and doesn't fail on install, but it's still good to get it sorted out.
2. Update various dependencies to latest versions (jinja2, requests and pip, setuptools and pbr for tests)
3. Make sure versions in ``test-requirements.txt`` are in sync with versions in ``requirements.txt``
4. Run ``pip-conflict-checker`` as part of ``make requirements`` step. This command will fail and exit with non-zero if there are any conflicting dependency versions.
Resolves #4818.

Update pip dependencies, fix conflicting dependency version, ensure there are no conflicting dependencies

---

contrib/runners/python_runner/python_runner/python_runner.py
st2common/st2common/runners/base.py
st2common/st2common/runners/parallel_ssh.py
st2common/st2common/runners/paramiko_ssh.py
st2common/st2common/runners/utils.py
st2common/st2common/services/sensor_watcher.py
st2common/st2common/services/triggerwatcher.py
st2common/st2common/transport/connection_retry_wrapper.py
st2common/st2common/transport/consumers.py
st2common/st2common/util/concurrency.py
st2common/st2common/util/shell.py

This pull request updates more code in st2common to utilize ``st2common.util.concurrency`` wrapper instead of calling ``eventlet`` directly.
Some of those changes were already introduced in #4792 and this pull request just builds on that and updates more code in st2common to use that wrapper.
Now 90% of the code in st2common, uses this wrapper and there are only a few places left which call eventlet directly (outside tests).

Utilize st2common.util.concurrency wrapper in st2common

---

CHANGELOG.rst
contrib/core/actions/send_mail/send_mail
contrib/core/pack.yaml

Fixes #4795: add `-w 0` to base64 encoding of subject line to avoid line wrapping
Credit to @guzzijones for finding the fix here https://superuser.com/questions/1225134/why-does-the-base64-of-a-string-contain-n

#4795 fix 'core.sendmail' for subject line wrapping

---

CHANGELOG.rst
conf/st2.conf.sample
st2api/st2api/app.py
st2api/st2api/cmd/api.py
st2api/st2api/wsgi.py
st2auth/st2auth/app.py
st2auth/st2auth/wsgi.py
st2common/st2common/config.py
st2common/st2common/models/db/__init__.py
st2common/tests/unit/test_db.py
st2tests/st2tests/base.py

This pull request fixes #4832  SSL support for MongoD and RabbitMQ when running under Python 3.6.
When running under Python 3 and enabling SSL support for MongoDB, st2api and st2auth would fail with a cryptic error:
```bash
2019-12-15 08:08:45,891 140651884441824 INFO (unknown file) [-] Connecting to database "somedatabase" @ "mongodb-host:27017" as user "someuser".
2019-12-15 08:08:45,892 140651884441824 WARNING (unknown file) [-] Retry on ConnectionError - Cannot connect to database default :
maximum recursion depth exceeded while calling a Python object
```
After some more digging in and manual instrumentation, I managed to track down the original exception / root cause - https://gist.github.com/Kami/ea8e63cdc539fd879fff41271969d650.
The root cause was an SSL error which happened …

Fix SSL support for MongoDB and RabbitMQ under Python 3.x

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2api/requirements.txt
st2auth/requirements.txt
st2common/requirements.txt
st2common/st2common/models/db/__init__.py
st2stream/requirements.txt

This pull request updates pymongo to the latest version.
Issue which has prevent us from upgrading in the past (https://jira.mongodb.org/browse/PYTHON-1966) has been resolved in the latest release.
NOTE: Some of the SSL / TLS related constructor arguments have been renamed, but the old names still work so I skipped renaming those arguments for now - https://api.mongodb.com/python/current/changelog.html#changes-in-version-3-9-0.

Update pymongo to the latest version

---

.travis.yml

Post TravisCI build failures on master or nightly builds to `#development` channel in `stackstorm-community` Slack

Notify #development channel in community Slack about TravisCI failures

---

fixed-requirements.txt
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt

The make .st2client-install-check command is failing because latest more-itertools no longer supports python 2.7. To workaround, pin more-itertools to an older version.  The zipp requirement is pinned to >=0.5,<=1.0.0 because the latest 2.0.0 version is registered as 0.0.0 and causing install check to fail.
Closes #4843

Fix to st2client install check

---

CHANGELOG.rst
st2actions/st2actions/workflows/workflows.py

To pass the SSL params, get_connection() should be used instead.
Related commit: dd4465a266c11e2dfd2fcf97896562ff8a9e8605

Fix the amqp connection for WorkflowExecutionHandler to pass the SSL params

---

contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Update orquesta requirement to version with fix to task rerun to ignore duplicate task rerun requests and detect and ignore tasks that are along the path of executions for another task rerun requests.

Update orquesta requirement to version with fix to task rerun

---

.gitignore
.travis.yml
Makefile
fixed-requirements.txt
requirements.txt
scripts/travis/add-itest-user-key.sh
scripts/travis/prepare-integration.sh
scripts/travis/setup-mistral.sh
st2actions/requirements.txt
st2client/requirements.txt
st2common/requirements.txt
st2debug/requirements.txt

Fixes includes:
Update gitpython requirement (Thanks to @blag for tracking down the bug.)
- gitpython requires gitdb2, but that has removed some things in newer
versions, and 2.11.1 had an open ended dep. So, update gitpython to a
newer version that has more specific version requirements for gitdb2.
- This should fix these errors:
https://github.com/gitpython-developers/GitPython/issues/983
https://travis-ci.org/StackStorm/st2/jobs/652088774#L9416
https://circleci.com/gh/StackStorm-Exchange/stackstorm-sumologic/155
Drop --no-site-packages from virtualenv calls
Make travis use the travis user instead of stanley, and add a restricted permissions workaround for the root user.
Update requests which had a conflicting dep on idna (primary said `idna>=2.5,<2.9` but security extra wanted any …

Fix master builds

---

CHANGELOG.rst

This adds the changelog entries missing from #4869

Add changelog entries for #4869

---

.travis.yml
Makefile
scripts/travis/install-requirements.sh
scripts/travis/permissions-workaround.sh
scripts/travis/rabbitmq.config
st2common/tests/integration/test_rabbitmq_ssl_listener.py
tox.ini

Try to upgrade travis to xenial from precise.
Ensures that mongo is 3.4 not 4.0. mongo 3.4 is not available in bionic so #4862 probably won't work until dependence on 3.4 is gone.
#4772 tried to update and ran into a many issues esp slowness. It also missed downgrading mongodb.
closes #4772
closes #4862

Switch Travis from Precise to Xenial infra

---

conf/HA/st2.conf.sample

The problematic sample here is: `virtualenv_opts = --always-copy` from the st2-ha sample config. 
This caused considerable frustration while following the [ST2-HA setup guide](https://docs.stackstorm.com/reference/ha.html).
```
[actionrunner]
logging = /etc/st2/logging.actionrunner.conf
**virtualenv_opts = --always-copy**
```
`virtualenv_opts` should be set in EL6, but from what I can tell, not in Ubuntu or EL >=7
There's a possibility that this should be comments out here also:
https://github.com/StackStorm/st2/blob/baada1854255ad9b89ab2cba33c5f6205ff4db48/conf/st2.package.conf#L21-L23
but I suspect it may be used in testing.

HA: comment out Action Runner config virtualenv_opts = --always-copy

---

st2actions/st2actions/workflows/workflows.py

not enough parameters for log call

exception was being thrown on logging output

---

contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
st2common/st2common/models/db/workflow.py
st2common/st2common/util/mongoescape.py
st2common/tests/unit/test_mongoescape.py

Rollback workflow DB change on errors field because there are cases where action execution result is included in the detail of the error log and the action execution result can contain dictionary with key that has dot notation such as IP address. Also identified and fix mongoescape bug on handling list of dicts in dynamic field and also multiple iteration on unescape.

Rollback workflow DB change on errors field

---

.travis.yml
CHANGELOG.rst
Makefile
fixed-requirements.txt
requirements.txt
scripts/dist_utils.py
scripts/fixate-requirements.py
st2actions/requirements.txt
st2api/in-requirements.txt
st2api/requirements.txt
test-requirements.txt

I wanted to specify `python_version < '3.4'` for the `singledispatch` dependency in #4894, but the `fixate-requirements.py` script does not support what pip calls "markers". Markers are environment specifications that instruct pip when to install, or more importantly, when _not_ to install a dependency.
Here's what a Python version marker would look like for #4894:
```
singledispatch==3.4.0.3 ; python_version < '3.4'
```
That marker would only install the `singledispatch` dependency if installing for Python < v3.4. The `singledispatch` package is a backport of the same feature for Python 3.4+, available in the standard library in the `functools` package. So installing it for Python 3.4+ is not necessary.
This PR:
I ran `make requirements` after these changes to ensure that the behavior of …

Various requirements fixups

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Update orquesta dependency to version that refactored evaluation of inbound criteria for join task on inbound task completion and not on inbound task transition. This allows for different use cases such as multiple task transition from the same inbound task, inbound task transition on completion or inbound task transition on failure. Include additional check in the state machine to detect case where there is an unreachable join task where inbound criteria is partially satisfied but all inbound tasks have already completed and it will never be satisfied.

Refactor evaluation of inbound criteria of join task in orquesta workflow

---

.circleci/config.yml

Follow up on #4852.
This also deploys the RHEL 8 packages to Packagecloud.

Deploy EL8 packages as well

---

.circleci/config.yml
CHANGELOG.rst

Waiting on StackStorm/st2cd#428 and StackStorm/st2ci#171 to be merged first.

Don't test or build Ubuntu 14 packages

---

CHANGELOG.rst
st2actions/tests/unit/test_paramiko_ssh.py
st2common/st2common/runners/paramiko_ssh.py

Needs confirmation that this is written correctly from @eedgar (-- @punkrokk )
Paramiko has a bug that is not patched, that causes ssh proxy connected to not get closed. 
eg. zombie ssh processes are left from the proxycommand
If I were to modify my st2.conf file as follows:
```more modify-st2-config.sh 
#/bin/bash
crudini --set /etc/st2/st2.conf ssh_runner use_ssh_config True
crudini --set /etc/st2/st2.conf ssh_runner ssh_config_file_path /root/.ssh/config
chown -R root:root /root/.ssh/*
chmod 600 /root/.ssh/config
chmod 600 /root/.ssh/id_rsa
```
```more ssh-config
Host 10.1.*
ProxyCommand ssh -o StrictHostKeyChecking=no bastion nc %h %p
IdentityFile ~/.ssh/id_rsa
User stanley
Host bastion
Hostname bastion.example.com
IdentityFile ~/.ssh/id_rsa
User stanley
```
We end up with zombie ssh …

Close proxycommand socket when its not needed anymore and resolve ssh zombies

---

Makefile

Updating dependencies is not an obvious, straightforward, or documented process, so many people have tried to simply update the root `requirements.txt` files, or the `requirements.txt` in one of our subpackages (eg: runners and st2* packages). While we do have headers on all of those files instructing people how to do it properly, it's very easy to miss them.
To combat this, I have previously added a step in the `ci-checks` that runs the `make requirements` target and uses git to check if there were any changes.
However, when this causes test failures in Travis CI, the error output isn't very helpful. Furthermore, running `make requirements` takes a long time to complete.
This PR splits the `requirements` target into `requirements` and `.requirements` and uses targets to maintain reverse …

Improve test failure directions

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Update orquesta to the commit version with the fix that will not return false positives on variables evaluation for dict method calls on ctx().

Update orquesta to version that has the vars eval fix for ctx() dict methods

---

CHANGELOG.rst
conf/st2.conf.sample
st2actions/st2actions/scheduler/config.py
st2actions/st2actions/scheduler/handler.py
st2tests/st2tests/config.py

Fixes #4887
This stopped my execution queue item from being requested more than once for long running requests.
Is there a config setting for the timing of this?
I am not sure if this is needed since there is retry code in the code base.

Make scheduling timeout constant to be a configurable option

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/expressions/functions/data.py
st2common/st2common/util/db.py

Update orquesta to version with array of dicts fix for YAQL functions. The change also fix regression in JSON/YAML related conversion functions as a result of the orquesta change.

Update orquesta to version with array of dicts fix for YAQL functions

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Pin orquesta to release v1.1.0 for the st2 v3.2 release. Add changelog entry of the change and notify users to review release notes and upgrade notes for potential impact.

Pin orquesta to v1.1.0 for the st2 v3.2 release

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actions.py
st2api/tests/unit/controllers/v1/test_actions.py

This PR fixes the issue I found tonight when testing the tag filter as reported in #4918 and adds unit tests to test the API with actions filtered by the name or tag.

Fix typo in the supported API filters when filtering packs

---

CHANGELOG.rst
conf/nginx/st2.conf

> Spot during the https://github.com/StackStorm/discussions/issues/6
```
Starting nginx: nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/conf.d/st2.conf:28
```
Looks like we're already using `listen ssl` and so `ssl on;` was there just for compatibility with the ancient nginx versions.
The `ssl` directive is deprecated in nginx `0.7.14` and is safe to remove, considering its release date in 2008.

Remove deprecated 'ssl on' nginx config

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Fix issue with orquesta task retry when a task that has a transition on failure will also be traversed on retry. This patch update the orquesta version in appropriate requirements.txt that has the fix.

Update orquesta version with fix for task retry

---

Makefile
st2common/bin/st2-run-pack-tests
st2common/tests/unit/test_dist_utils.py

Recently `pip` release `20.1` and broke our `dist_utils.py` in many of our components.
Since we weren't pinning `pip` this caused builds to fail.
This PR pins `pip` to `20.0.2` and `setuptools` to `44.1.0` until we can roll out a proper fix for all of the `dist_utils.py` across our organization.
**Related:**
- https://github.com/StackStorm/st2/pull/4902
- https://github.com/StackStorm/discussions/issues/2
- https://github.com/StackStorm/st2/pull/4750
- https://github.com/StackStorm/st2/pull/4895

Pinning pip to 20.0.2 to fix build issues introduced in pip 20.1

---

CHANGELOG.rst
Makefile
contrib/examples/actions/orquesta-test-field-escaping.yaml
contrib/examples/actions/python-mock-core-remote.py
contrib/examples/actions/python-mock-core-remote.yaml
contrib/examples/actions/workflows/tests/orquesta-test-field-escaping.yaml
scripts/fixate-requirements.py
st2common/st2common/models/db/workflow.py
st2tests/integration/orquesta/test_wiring.py

Closes #4932 
This is a fix for the bug found in #4932 .
I had to revert 3x fields in the workflow DB model:
1. `WorkflowExecutionDB.spec` for any fields/dict keys that were statically defined in the workflow spec that include a `.` in their name:
Example:
```yaml
vars:
- vars.key.with.periods: "vars.value.with.periods"
- vars.nested.with.periods:
nested.periods: "vars.nested.value.with.periods"
output:
- wf.hostname.with.periods: "{{ ctx()['published.hosts'] }}"
- wf.output.with.periods: "{{ ctx()['published.field'] }}"
```
2. `WorkflowExecutionDB.context` for any dicts/objects that is present in the "context", ie. from a published variable. This can occur, for example, when running `core.remote`. The resulting dictionary has hostnames/IPs as keys in the returned dict.
Example:
```yaml …
```

#4932 - Fixes for field escaping in orquesta workflows

---

CHANGELOG.rst
Makefile
contrib/schemas/action.json
contrib/schemas/alias.json
contrib/schemas/pack.json
contrib/schemas/policy.json
contrib/schemas/rule.json
st2common/bin/st2-generate-schemas
st2common/st2common/models/api/action.py
st2common/st2common/models/api/rule.py

Add the script st2-generate-schemas to autogen schemas for the content models such as pack, action, alias, policy, and rule. The schemas will be used in developer workflow to help with user generated contents.

Add st2-generate-schemas to autogen schemas for the content models

---

OWNERS.md

I'd like to propose adding @winem to the list of StackStorm Contributors.
During the past half year he was helping StackStorm project via bug reports, PR fixes, PR reviews, release testing efforts as well as actively supporting community in Slack and Forums.
Github PRs:
- [Fix tag filter when querying actions #4874](https://github.com/StackStorm/st2/pull/4874) fixing https://github.com/StackStorm/st2/issues/4828 `good first issue`.
- [Add configurable ssh connect timeout #4914](https://github.com/StackStorm/st2/pull/4914) addressing another `good first issue` https://github.com/StackStorm/st2/issues/4715
- [Handle action parameters of type array correctly #4861](https://github.com/StackStorm/st2/pull/4861) closing bug https://github.com/StackStorm/st2/issues/4804
- [Fix bug in the …

Proposal: Add @winem to the StackStorm Contributors [skip ci]

---

CHANGELOG.rst
contrib/linux/actions/netstat.yaml
contrib/linux/actions/netstat_grep.yaml
contrib/runners/orquesta_runner/orquesta_functions/st2kv.py
st2common/st2common/util/monkey_patch.py
st2common/tests/unit/test_dist_utils.py

looks like the `type` attribute is missing for `netstat` action in Linux pack because of which the action in not usable.
```
$ st2 run linux.netstat hosts=172.31.114.68 args="-antp"
ERROR: 'type'
```
closes: #4946

fix netstat action in linux pack

---

.travis.yml
Makefile

`st2docs` build which is based on `st2` makefile started to fail (https://circleci.com/gh/StackStorm/st2docs/2529) due to upstream pip updated to latest `20.1.1`, while we failed to pin it to `20.0.2`. Thanks to @winem for the find.
We should not pin `pip` in files like `.travis.yml`, but instead use single consistent way and not hack across the many places as other systems rely on st2 makefiles for the builds.
Related: https://github.com/StackStorm/discussions/issues/2
This change sets pip version in one Makefile place and fixes st2docs builds.

Pin pip consistently in one place across the targets, fix st2docs build

---

CHANGELOG.rst
contrib/examples/actions/orquesta-test-subworkflow-empty-with-items.yaml
contrib/examples/actions/workflows/tests/orquesta-test-subworkflow-empty-with-items.yaml
contrib/runners/orquesta_runner/tests/unit/test_with_items.py
st2common/st2common/services/workflows.py
st2tests/integration/orquesta/test_wiring_with_items.py
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/with-items-empty-parent.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/with-items-empty.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/with-items-empty-parent.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/with-items-empty.yaml

Fix a bug where passing an empty list to a with items task in a subworkflow causes the parent workflow to be stuck in running status. The workflow engine usually skips execution of the with items task because the list is empty. The issue here is that when the task is marked complete, the status change in the task wasn't published which will triggered additional logic to handle completion and move the parent workflow forward. This patch publishes the completeion status of the task now. Fixes https://github.com/StackStorm/st2/issues/4954.

Fix empty with items list resulting in parent workflow stuck in running

---

GOVERNANCE.md

@armab and I realized with guidance from the Linux Foundation that the wrong version of the Charter had been posted and approved. As a formality we wish to get approval for the new charter that is now linked in GOVERNANCE.md. 
Please approve at your earliest conveinance. 
The new Technical Charter version doesn't change anything significantly, just several wording fixes and links. Please find the diff file attached as [Stackstorm Charter Redlined_DIFF.docx](https://github.com/StackStorm/st2/files/4725666/Stackstorm.Charter.Redlined_DIFF.docx)
New version: [2019-09-03-StackStorm-Project-Technical-Charter.pdf](https://github.com/StackStorm/st2/files/4725742/2019-09-03-StackStorm-Project-Technical-Charter.pdf)

Update the LF Charter to the Correct One

---

.github/FUNDING.yml

Add Github Sponsor button, linked to StackStrom profile in Linux Foundation's Community Bridge platform https://funding.communitybridge.org/projects/stackstorm

Add Github "Sponsor" Button

---

CHANGELOG.rst
conf/HA/nginx/st2.conf.blueprint.sample
conf/HA/nginx/st2.conf.controller.sample

This PR removes:
- the duplicate host header in the Load balancer configs for each API endpoint
- the `ssl on` directive with is deprecated and redundant with ` listen       *:443 ssl;` directive
Tested

remove deprecated ssl and duplicate proxy host header

---

OWNERS.md

I'd like to propose adding @amanda11 to the list of StackStorm Contributors.
She was a great help to the project during the past several months starting from `v3.2.0` pre-release testing (https://github.com/StackStorm/discussions/issues/6), verifying different testing scenarios, finding the bugs (https://github.com/StackStorm/orquesta/pull/200) and regressions in the platform, reporting them and also fixing some of them. Besides of that: 
- Stackstorm-Exchange:
- aws: https://github.com/StackStorm-Exchange/stackstorm-aws/issues/98 and fix https://github.com/StackStorm-Exchange/stackstorm-aws/issues/99, review https://github.com/StackStorm-Exchange/stackstorm-aws/pull/104, fix https://github.com/StackStorm-Exchange/stackstorm-aws/pull/107
- servicenow: bug …

Propose adding @amanda11 to the StackStorm Contributors

---

CHANGELOG.rst
st2actions/tests/unit/test_paramiko_ssh.py
st2common/st2common/runners/paramiko_ssh.py

Closes #4973 
Regression introduced here: https://github.com/StackStorm/st2/pull/4881
The `self.socket` object is not a process and doesn't have a member called `process`, so calling `self.socket.process.xxx` throws an exception when closing the SSH client.
Looks like we were also failing to cleanup the `self.bastion_socket` instance, so added that as well.

Fixed exception during SSH runner socket cleanup

---

.circleci/config.yml
CHANGELOG.rst
Makefile
st2actions/Makefile
st2actions/bin/runners.sh
st2api/Makefile
st2auth/Makefile
st2client/Makefile
st2common/bin/st2ctl
st2debug/Makefile
st2reactor/Makefile
st2stream/Makefile
st2tests/Makefile

EL6 is being deprecated. Remove running of builds in EL6.
Remove rhel-rpm in Makefiles, and keep the rpm for EL7 and above. I was a bit confused with the name rhel-rpm - it seemed to just use the el6 specs - and so I was presuming it was no-longer required - but would need confirmation.

Remove EL6 support

---

contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
contrib/runners/orquesta_runner/tests/unit/test_basic.py
contrib/runners/orquesta_runner/tests/unit/test_context.py
st2actions/st2actions/workflows/workflows.py
st2common/st2common/services/action.py
st2common/st2common/services/workflows.py
st2common/tests/unit/services/test_workflow.py
st2common/tests/unit/services/test_workflow_identify_orphans.py
st2tests/st2tests/base.py

Currently, progress of workflow execution is written to the workflow service and action runner log files. Update the logging in the orquesta runner and workflow service to write the execution progress to the action execution output table which will be available in the streaming API and when tailing execution output.

Update progress of workflow execution to the output stream

---

CHANGELOG.rst
st2reactor/st2reactor/container/manager.py

Updates the sensor error message when a sensor won't be ran if it's assigned to a different partition.

update sensor partitioner error message

---

CHANGELOG.rst
conf/HA/nginx/st2.conf.blueprint.sample
st2actions/st2actions/cmd/actionrunner.py
st2actions/st2actions/cmd/st2notifier.py
st2actions/st2actions/cmd/st2resultstracker.py
st2auth/st2auth/cmd/api.py
st2common/bin/paramiko_ssh_evenlets_tester.py
st2exporter/st2exporter/cmd/st2exporter_starter.py
st2reactor/st2reactor/cmd/garbagecollector.py
st2reactor/st2reactor/cmd/rulesengine.py
st2reactor/st2reactor/cmd/sensormanager.py
st2reactor/st2reactor/cmd/timersengine.py
st2reactor/st2reactor/container/sensor_wrapper.py
st2reactor/tests/unit/test_sensor_wrapper.py

Fixes: #4875 monkeypatch st2 sensor earlier

---

CHANGELOG.rst
scripts/travis/submit-codecov-coverage.sh

We've been seeing repeated build failures for codecov issues: https://travis-ci.org/github/StackStorm/st2/jobs/710376520#L27406
The fix is to upgrade to `codecov-python >= 2.1` per https://community.codecov.io/t/http-400-while-uploading-to-s3-with-python-codecov-from-travis/1428/6
However, we are maintaining our own fork of `codecov-python` and those changes haven't been merged into our fork.
Couple things here:
- It looks like we're maintaining our own fork so that we can get better error outputs: https://github.com/codecov/codecov-python/compare/master...StackStorm:better_error_output
- I've submitted a PR upstream to include these changes so we don't have to maintain our own fork: https://github.com/codecov/codecov-python/pull/288
- Once the PR above is merged we can merge this PR …

Use upstream codecov instead of our own fork

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Recently both `st2-docker` https://circleci.com/gh/StackStorm/st2-docker/2199 and `stackstorm-ha` https://circleci.com/gh/StackStorm/stackstorm-ha/2393 nightly builds started to fail :fire:.
Fixes https://github.com/StackStorm/stackstorm-ha/issues/143
Fixes https://github.com/StackStorm/st2-docker/issues/194
The issue is that st2 services started to fail if mongodb is a host and not an IP, meaning all remote-host scenarios are broken:
```
root@86f87ce3c778:/opt/stackstorm# /opt/stackstorm/st2/bin/st2api --config-file=/etc/st2/st2.conf --config-file=/etc/st2/st2.docker.conf --config-file=/etc/st2/st2.docker.conf
2020-07-19 15:47:53,175 DEBUG [-] Using Python: 3.6.9 (/opt/stackstorm/st2/bin/python)
2020-07-19 15:47:53,176 DEBUG [-] Using config files: …
```

Pin dnspython pip dependency due to regression in v2.0.0

---

scripts/travis/submit-codecov-coverage.sh

Turns out `<` is a special character in bash :P
This properly quotes our installation of the coverage package so the correctly pinned version installs.

Fixed bash issue with travis codecov submissions not working

---

OWNERS.md

Remove Contributors from the list who weren't active in StackStorm Community this year.
We should keep the list up to date according to the LF Analytics data https://lfanalytics.io/projects/stackstorm/dashboard including Slack, Forums, Github and Contributing Activities we expect to be valuable for the project: https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-to-start-contributing

Remove inactive Contributors

---

.travis.yml
Makefile
contrib/runners/orquesta_runner/orquesta_functions/st2kv.py
st2common/st2common/util/monkey_patch.py
st2common/tests/unit/test_dist_utils.py

Cherry-picking changes into `v3.2` branch from the (#4957) which should fix st2docs builds for `stable` branch.
* Pin pip to 20.0.2 consistently across the Makefile targets
* Remove virtualenv and pip installation from Travis yaml
* Fix st2docs build relying on st2 master makefiles
(cherry picked from commit 29ca930)
Also cherry-picking lint changes made by @Sheshagiri in https://github.com/StackStorm/st2/pull/4947
See https://github.com/StackStorm/st2docs/pull/1001 https://github.com/StackStorm/st2docs/pull/999 which are blocked by the CI failures in st2 `v3.2` branch.

Fix stable st2docs builds (v3.2)

---

CHANGELOG.rst
dev_docs/Troubleshooting_Guide.rst
tools/launchdev.sh

This PR prints out the default creds right before completing the `tools/launch_dev.sh` script and adds a FAQ to the [dev docs/Troubleshooting_Guide.rst](https://github.com/StackStorm/st2/tree/master/dev_docs)

better expose default creds for devs

---

OWNERS.md

Looking at the Linux Foundation Contribution Analytics (https://lfanalytics.io/projects/stackstorm/), @amanda11 already outperformed many TSC members showing exceptional dedication to the StackStorm project.
She's active Contributor of StackStorm Community for the past half of year, starting helping with the `v3.2.0` release testing and being a great assistance where it's needed most for StackStorm.
Looking at [Maintainer Responsibilities](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#maintainer-responsibilities) Amanda touched almost every part of the system, starting from the documentation, pre-release testing, good first issues, community help (Slack, Forum, Github) ending with very insightful PR Reviews, contributions to StackStorm core and code fixes, even looked deeper …

Promote Amanda McGuinness (@amanda11) to the StackStorm TSC Maintainers

---

OWNERS.md

I'd like to propose adding @Sheshagiri to the list of [StackStorm Contributors](https://github.com/StackStorm/st2/blob/master/OWNERS.md#contributors).
During the past several months @Sheshagiri was helpful in StackStorm Community by answering Forum questions, reporting issues and actually fixing things, assisting with the roadmap items like EL6 removal, StackStorm API docsgen fixes, K8s, Docker and also PR reviews.
* :+1: Very detailed and helpful assistance on StackStorm Forums:
- https://forum.stackstorm.com/t/how-to-define-data-type-for-action-inputs/1364
- https://forum.stackstorm.com/t/issue-while-calling-first-task-in-workflow-in-stackstorm-v3-1-0/1325
- https://forum.stackstorm.com/t/repeated-execution-of-an-action/1084
- https://forum.stackstorm.com/t/specified-version-of-stackstor …

Propose adding @Sheshagiri to the StackStorm Contributors

---

Makefile
conf/st2.conf.sample
st2auth/setup.py
st2auth/st2auth/app.py
st2auth/st2auth/config.py
st2auth/st2auth/controllers/v1/root.py
st2auth/st2auth/controllers/v1/sso.py
st2auth/st2auth/sso/__init__.py
st2auth/st2auth/sso/base.py
st2auth/st2auth/sso/noop.py
st2auth/tests/unit/controllers/v1/test_sso.py
st2common/st2common/constants/auth.py
st2common/st2common/exceptions/auth.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2
st2tests/st2tests/config.py
tools/config_gen.py
tox.ini

Add SSO endpoints to the st2 API spec. Add API controllers for the SSO redirect and handle Idp callback. Implement scaffolding for the SSO backends. Add unit tests to capture not implemented errors, unknown exception, and also SSO verification errors in the API controllers.

Implement SSO plugin for user authentication in StackStorm

---

.circleci/config.yml
.travis.yml

Update CircleCI and Travis to use mongodb 4.0
Addresses CircleCI/Travis part of https://github.com/StackStorm/st2/issues/4972

Update ST2 CircleCI and Travis to use mongodb 4.0 instead of 3.4

---

Makefile
scripts/travis/install-requirements.sh

py3-unit-nightly was removed as part of mistral deprecation, as it just ran the mistral UTs, but Travis run still called it. Remove call to it from travis runs to stop error on overnight runs.

remove py3-unit-nightly from Travis runs

---

CHANGELOG.rst
contrib/packs/actions/get_pack_warnings.yaml
contrib/packs/actions/pack_mgmt/get_pack_warnings.py
contrib/packs/actions/workflows/install.yaml
contrib/packs/tests/test_get_pack_warnings.py
st2client/st2client/commands/pack.py
st2common/st2common/util/pack.py
st2common/st2common/util/pack_management.py
st2common/tests/unit/test_util_pack.py

packs.download action will log a warning if attempt to install a pack that only supports python 2
packs.install workflow will include an extra step to check if the metadata indicates warnings (and will return a warning_list of any of the packs that had a warning - whereby warnings will only be raised if the pack supports python 2). The warning_list will also be an output of the workflow (similar to conflict_list)
st2 client, when running "pack install" will output to screen any warnings reported in the warning_list from the workflow execution. 
Part of #4938

Add python warning if install a pack that only supports python 2

---

CHANGELOG.rst
contrib/runners/inquirer_runner/inquirer_runner/runner.yaml
st2api/st2api/validation.py
st2api/tests/unit/test_validation_utils.py
st2tests/st2tests/fixtures/generic/runners/inquirer.yaml

The RBAC backend will be named "default" instead of "enterprise" after it has been open sourced. Update the API validation to look for the "default" value instead of "enterprise". Minor update to comments related to the RBAC enterprise feature.

Update the st2 API validation on RBAC configuration

---

CHANGELOG.rst
st2common/bin/st2ctl

Add warning messages in yellow to screen if perform st2ctl start (or restart) and /opt/stackstorm/st2/bin/python is python 2.x
Addresses part of #5041 and #4938

Add deprecation warning on st2ctl start if st2/python is python 2.x

---

CHANGELOG.rst
st2common/st2common/log.py

Closes #5057 
See that issue for description of what the problem was. The fix was simply to ensure our implementation handles both the python 2 version and returns a 3-tuple, along with the python 3 version which returns a 4-tuple and is based on the code here: https://github.com/python/cpython/blob/3.9/Lib/logging/__init__.py#L1502-L1536
I've tested this change both my a python 2.7 (centos7) and python 3.6 (centos8 and ubuntu18) box and the logging modules are returned properly.

Fixed python 3 incompatibility in logging API implemenation of findCaller

---

CHANGELOG.rst
st2common/st2common/log.py

Closes #5057
See that issue for description of what the problem was. The fix was simply to ensure our implementation handles both the python 2 version and returns a 3-tuple, along with the python 3 version which returns a 4-tuple and is based on the code here: https://github.com/python/cpython/blob/3.9/Lib/logging/__init__.py#L1502-L1536
I've tested this change both my a python 2.7 (centos7) and python 3.6 (centos8 and ubuntu18) box and the logging modules are returned properly.

Fixed python 3 incompatibility in logging API implemenation of findCaller (v3.3 cherry pick)

---

.travis.yml
Makefile
test-requirements-py27.txt
test-requirements.txt

The image that travis uses contain both python 2.7 and python 3.6. Explicitly add the PYTHON_VERSION environment variable to instruct which python executable to use. Fix python 2.7 jobs in travis that are failing.

Fix travis jobs after making python3 as default for development

---

st2common/st2common/util/crypto.py

The Travis CI tests are [failing](https://travis-ci.org/github/StackStorm/st2/jobs/739147683#L1572) the lint tests because pylint can't import keyzar.
Luckily, keyczar was phased out in StackStorm 2.8, and support for that was dropped once 2.10 was released (December 2018), so no keyczar code is in production - it is only code for tests.
This PR simply disables pylint import checks for those lines so Travis CI tests can successfully complete.

Disable pylint import checking for keyczar lines (only used for tests)

---

st2client/setup.py

This PR improves the PyPI description of st2client by doing the following:
* Removes the redundant `license` specifier argument to `setup()` (see the official documentation on it [here](https://packaging.python.org/specifications/core-metadata/#license), and why this is a problem [here](https://github.com/diyan/pywinrm/pull/284))
* Adds the content of `README.rst` as the long description for the st2client package on PyPI
* Adds additional URLs to the project, which I think will be rendered in the sidebar of the PyPI project page, giving the links more visibility for users looking at the st2client package on PyPI

Improve st2client homepage

---

.circleci/config.yml
README.md

Remove `py 2.7` from the README, leave `py 3.6` only for the upcoming `v3.4.0` release.
_Side Note:_ PR to test if StackStorm CI webhooks work for triggering the e2e test builds.

Remove py2.7 from the README badges

---

CHANGELOG.rst
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
fixed-requirements.txt
requirements.txt
st2client/requirements.txt
st2common/requirements.txt

Update `cryptography` to > 3.2 to avoid [CVE-2020-25659](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#32---2020-10-25) and to fix the Travis-CI and CircleCI builds.
Closes #5065, #5066, and #5067.

Update cryptography version to 3.2

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/in-requirements.txt
st2actions/requirements.txt
st2api/in-requirements.txt
st2auth/in-requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2debug/in-requirements.txt
st2debug/requirements.txt
st2exporter/in-requirements.txt
st2reactor/in-requirements.txt
st2stream/in-requirements.txt
st2tests/in-requirements.txt

We pin requests[security] but that has a check when running that chardet is < 3.1.0, but chardet is not listed as requirement with a pinned requirement.
Also fix typo in in-requirements.txt comments

Fix chardet as fix requests

---

CHANGELOG.rst
st2common/st2common/content/loader.py

This PR fixes the current issue plaguing the end-to-end tests on Ubuntu 16 when the bootstrap script attempts to install the stackstorm-st2 pack from StackStorm Exchange:
```
20201216T075024+0000 For the \"st2\" pack, the following content will be registered:
20201216T075024+0000 
20201216T075024+0000 actions   |  24
20201216T075024+0000 rules     |  0
20201216T075024+0000 sensors   |  0
20201216T075024+0000 aliases   |  12
20201216T075024+0000 triggers  |  0
20201216T075024+0000 
20201216T075024+0000 Installation may take a while for packs with many items.
20201216T075024+0000 
20201216T075025+0000 \t[ \u001b[93mscheduled\u001b[0m ] init_task
\t[  \u001b[93mrunning\u001b[0m  ] init_task
\t[ \u001b[92msucceeded\u001b[0m ] init_task
20201216T075027+0000 \t[ \u001b[93mscheduled\u001b[0m ] …
```

Decode pack files as utf-8 instead of ascii

---

CHANGELOG.rst
st2common/st2common/content/loader.py

This PR fixes a regression introduced by #5106. That code runs within a pack's virtualenv, and because we are still supporting Python 2 in StackStorm Exchange packs, we also need to support Python 2 in `st2common/content/loader.py`.
Using the `encoding` keyword argument to `open()` works on Python 3, but the native `open()` on Python 2 does not accept the `encoding` argument.
Instead, this PR imports `io.open` when running on Python 2, which should resolve the issue.
Thanks to @nmaludy for tracking down the issue and @armab for pointing [this Stack Overflow post](https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2/56520670#56520670) out [on Slack](https://stackstorm-community.slack.com/archives/CSBELJ78A/p1608318231282400).

Use io.open() when running on Python 2

---

.github/workflows/ci.yaml
st2common/tests/unit/test_action_db_utils.py

Happy new year everyone, 
this PR sends a Slack notification if a GH Action run on the master branch fails. It uses the new Slack Bot API which is the currently recommended way to integrate your apps into Slack (incoming webhooks are "legacy" now).
It relies on 2 GitHub Action services: 
1st) https://github.com/technote-space/workflow-conclusion-action - this one is needed to provide a single status for all the workflows executed so far (otherwise we would get a slack notification for `ci-checks`, `ci-compile`, `ci-packs-tests` and `ci-unit` which is unneeded noise). The workflow conclusion action creates an environment variable `WORKFLOW_CONCLUSION` which is `success` if all the jobs were successful or failure if any of them failed
2nd) …

Slack notification on failed Github Action executions on the master branch

---

OWNERS.md

I'd like to propose adding [Shital Raut](https://github.com/shital-orchestral) to the list of StackStorm Contributors for the work he did on behalf of Orchestral to integrate the Workflow Designer into StackStorm Web UI: 
* https://github.com/StackStorm/st2web/pull/759 (big PR)
This migrates the `st2flow` codebase https://github.com/stackstorm/st2flow, previously StackStorm enterprise feature into `st2web` and PR includes a lot of the changes with the integration, follow-ups and fixes. 
The `v3.4.0` release major feature was tested by the @StackStorm/maintainers and it's a great job. Hope Shital will keep contributing to [StackStorm Web UI](https://github.com/stackstorm/st2web) in the future.

Add @shital-orchestral to the list of Contributors

---

OWNERS.md

I'd like to propose adding @hnanchahal in the list of Contributors for the work he did to help integrating the LDAP/RBAC into the StackStorm core, st2 contributions and being part of K8s and StackStorm community.
LDAP/RBAC:
* [st2: Adding LDAP as auth backend](https://github.com/StackStorm/st2/pull/5082)
* [st2-packages: Adding libldap2-dev, libsasl2-dev to satisfy ldap dependencies](https://github.com/StackStorm/st2-packages/pull/674)
* [st2docs: Update LDAP auth backend documentation](https://github.com/StackStorm/st2docs/pull/1036)
* [st2-packages: ship st2-apply-rbac-defintions binary with the packages](https://github.com/StackStorm/st2-packages/pull/676)
* [st2docs: Update the RBAC documentation](https://github.com/StackStorm/st2docs/pull/1039)
* [st2packaging-dockerfiles: Adding …

Add @hnanchahal to the list of Contributors

---

st2tests/st2tests/__init__.py
test-requirements.txt

Update version of isort to be compatible with pylint.
Also update st2tests to be version 3.4dev

Update versions of st2tests and isort

---

OWNERS.md

Move @bigmstone from Maintainers to StackStorm Friends as he step out from the TSC Maintainers group and not active these days.
Matt, thank you for everything you did for StackStorm during the project hard times, including forming the TSC group we see today!

Add @bigmstone to StackStorm Friends

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_action_alias.py
st2client/st2client/commands/action_alias.py
st2client/st2client/models/core.py
st2client/tests/base.py
st2client/tests/unit/test_action_alias.py
st2tests/st2tests/fixtures/aliases/actions/action1.yaml

I tried to use StackStorm after quite a long time and in the first 5 minutes I encountered two exceptions / bugs (like in the good old days - guess I'm always the "lucky" one :D).
There are two bugs in ``st2 action-alias execute`` command so it doesn't work.
1) If ``user`` query param is not specified, it will fail with the error below due to API returning an error due to type mismatch (out of the box behavior with st2-docker).
```bash
curl -X POST -H  'User-Agent: python-requests/2.23.0' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'Connection: keep-alive' -H  'X-Auth-Token: XXXX' -H  'content-type: application/json' -H  'Content-Length: 61' --data-binary '{"command": "foo=bar", "user": null, "source_channel": "cli"}' http://st2api:9101/aliasexecution/match_and_execute
{ …
```

Fix "st2 action-alias execute" CLI command

---

.github/workflows/ci.yaml
st2common/st2common/models/db/execution.py

Our current GitHub Actions configuration runs tests twice for each push - once when the branch is pushed, and once more when a pull request is opened, reopened, or edited.
This is inefficient and slows down development since people have to wait for more tests to finish.
This PR slightly tweaks the GHA config to only run tests on pushes to:
* `master` - ensure post-merge code is good
* `v*` branches - version branches that track minor versions (eg: `v3.4`)
* `v*` tags - version tags that track bugfix releases (eg: `v3.4.0`), typically are tagged on commits to version branches
I have included comments on the configuration to ensure that everybody who isn't familiar with GHA understands what the intent is.

Adjust GitHub Actions config to avoid double testing on PRs

---

CHANGELOG.rst
st2client/st2client/commands/action.py
st2client/tests/unit/test_command_actionrun.py

I tried to use ``st2 run @param=file_path.json`` notation to specify complex JSON parameter value in a file.
It turns out it's not working correctly. Using ``--debug`` flag it shows it's not correctly converting bytes to unicode which means JSON serialization fails (actual value has``b""`` prefix which indicates that code is incorrectly calling ``str()`` on the value somewhere instead of using ``bytes.decode()``).
```bash
st2 --debug run scalyr.timeseries_queries @queries=1.json
...
ERROR: Object of type 'bytes' is not JSON serializable
....
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2client/utils/httpclient.py", line 98, in post
response = requests.post(self.root + url, json.dumps(data), **kwargs)
File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
return …
```

Fix st2client @key=file_path.json notation for specifying complex objects in a file

---

CHANGELOG.rst
st2api/st2api/controllers/v1/aliasexecution.py
st2api/tests/unit/controllers/v1/test_action_alias.py
st2api/tests/unit/controllers/v1/test_alias_execution.py
st2tests/st2tests/fixtures/aliases/actions/action3.yaml
st2tests/st2tests/fixtures/aliases/actions/action4.yaml
st2tests/st2tests/fixtures/aliases/aliases/alias_with_immutable_list_param.yaml
st2tests/st2tests/fixtures/aliases/aliases/alias_with_immutable_list_param_str_cast.yaml
st2tests/st2tests/fixturesloader.py

This pull request fixes a bug in action alias array parameter value casting when executing an alias.
The code would incorrectly assume value is always a string and try to cast it to an array (the value may very well be a string when executing command from chat, but even then is not always true).
This would not work if value is already a list (e.g. if parameter contains a default value or a default value is specified using ``immutable_parameters`` in action alias definition).
I encountered this bug when trying to define a default value for a parameter in action alias which is a list.
Here is action alias definition in question:
```yaml
---
name: "test"
pack: "scalyr"
action_ref: "scalyr.timeseries_queries"
description: "Get server temps."
formats:
- "temps"
result:
format: |
CPUs: 
Core 0: …
```

Fix a bug in invalid action alias array parameter casting

---

st2common/st2common/models/db/execution.py
st2common/st2common/util/sandboxing.py
st2common/tests/unit/test_util_sandboxing.py

This PR partially reverts the code removed in #5100 and refactors it a bit since we no longer need to deal with Python 2.7 at all.
In StackStorm <= v3.3, when the sandboxing code was generating a `PYTHONPATH` for Python actions, it would prepend the operating system's Python directory (eg: `/usr/lib/python3.5`) in an attempt to provide modules and packages from the Python 3 stdlib _before_ the third party packages (usually backports of the same name) for Python 2.7 (eg: `<st2root>/st2/lib/python2.7/site-packages`).
All of that was over-enthusiastically ripped out when we removed Python 2.7 support, however some of the `PYTHONPATH` handling for Python actions is still necessary.
With this PR, the code once again generates an appropriate `PYTHONPATH` for Python actions:
1. The pack's …

[WIP] Rescue Python path code

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2client/requirements.txt
st2common/requirements.txt

This PR updates cryptography to 3.3.2.
Closes #5147, #5148,  #5149

Update cryptography to 3.3.2

---

.github/workflows/ci.yaml

I noticed "requirements" step takes ~80-90 seconds on CI.
After inspecting the output, I noticed it's not using cached pip dependencies, but downloading all of them from the internet. It turns out, we were not using a correct path for the pip cache directory (``~/.cache/pip``).
This pull request fixes this.
With this change the step now takes ~36 seconds (if cache is populated / unchanged).
Before:
After:

Fix path for pip dir which is used for CI cache to speed up the build

---

fixed-requirements.txt
test-requirements.txt

We have already been using `pip==20.0.2` for testing since st2 v3.2.0. `virtualenv` embeds the wheel for `pip`, so we need to adjust the pinned version of virtualenv to update which version of pip is used to create virtualenvs (eg for packs).
This also clarifies the comment about why we're pinning virtualenv instead of pip directly.

[BUGFIX] Use pip 20.0.2 to build virtualenvs

---

OWNERS.md

Marcel (@winem) was consistently contributing to the project for the past year and being more actively involved recently, helping delivering the roadmap release items, testing, StackStorm core improvements, community support as well as deployment methods like `curl|bash` scripted installer and Docker.
Some examples:
- `v3.2`, `v3.3` and `v3.4` pre-release testing help, finding bugs and actually helping to resolve them, assisting the team.
- 3.4 roadmap: full `st2resultstracker` removal: https://github.com/StackStorm/st2/pull/5108 https://github.com/StackStorm/st2/issues/5070 https://github.com/StackStorm/st2-packages/pull/683 https://github.com/StackStorm/st2docs/pull/1045 https://github.com/StackStorm/st2-dockerfiles/pull/40 https://github.com/StackStorm/st2-docker/pull/204
- 3.4 …

Propose adding @winem as a Maintainer

---

.circle/add-itest-user.sh
scripts/travis/add-itest-user-key.sh

- make add-itest-user scripts more verbose
- use `sudo -E` to preserve env vars
Github Actions has this in their `Default: env_reset` in their sudoers config file. This means that HOME and other vars are set to match the sudo target user. Using `sudo -E` preserves the environment allowing `~` to resolve correctly.
I'm not sure why we didn't hit this earlier. Maybe Github changed their sudoers config? In any case, this should fix it.

Use sudo -E to preserve env vars in CI

---

.circle/add-itest-user.sh
scripts/travis/add-itest-user-key.sh

Backport of #5186
- make add-itest-user scripts more verbose
- use `sudo -E` to preserve env vars
Github Actions has this in their Default: env_reset in their sudoers config file. This means that HOME and other vars are set to match the sudo target user. Using sudo -E preserves the environment allowing ~ to resolve correctly.
I'm not sure why we didn't hit this earlier. Maybe Github changed their sudoers config? In any case, this should fix it.

[v3.4] Backport sudo -E CI fix

---

CHANGELOG.rst
st2common/st2common/log.py
st2common/st2common/service_setup.py
st2common/tests/integration/log_unicode_data.py
st2common/tests/integration/test_logging.py
st2common/tests/integration/test_service_setup_log_level_filtering.py

This PR pulls the changes from #5182 into the `v3.4` branch.

Updates for v3.4.1

---

CHANGELOG.rst
st2client/st2client/utils/types.py
st2common/st2common/util/db.py
st2common/st2common/util/misc.py
st2common/st2common/util/pack.py
st2common/st2common/util/types.py

Import ABC from collections.abc for py 3.10 compatibility

---

CHANGELOG.rst
st2common/st2common/bootstrap/runnersregistrar.py

I was looking at st2api profiling data some more and noticed we spend more time in stevedore code then we should.
It turns on that we were not loading all the extensions just once, but X + 1 times where X is number of runners (stevedore extensions).
This is obviously not the fastest thing since loading extensions requires pkg resources scan for available extensions.
This pull request fixes that. It should now also result in much less DEBUG level noise on service start up time.

Speed up service start up time by reducing runner registration / extension loading time

---

.github/workflows/ci.yaml
.travis.yml
Makefile
contrib/runners/python_runner/python_runner/python_action_wrapper.py
contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
contrib/runners/python_runner/tests/integration/test_pythonrunner_behavior.py
scripts/github/rabbitmq.conf
scripts/travis/prepare-integration.sh
st2common/st2common/config.py
st2common/st2common/util/shell.py
st2common/st2common/util/virtualenvs.py
st2common/tests/integration/test_rabbitmq_ssl_listener.py
test-requirements.txt
tools/launchdev.sh

Move integration tests to GitHub Actions (GHA)
We also have to fix a few tests to make the transition.
List of commits:
- improve CI output
- improve GHA folding
- fix virtualenv lock files issue again
- Switch tests to check w/ CA that is present in GHA
- apt download cache
- use bitnami/rabbitmq service container in GHA
- bust python cache
- Use virtualenv from st2 virtualenv by default
- Installing virtualenv in --user on github
- Add workaround for failing stdin test
- fix check-dependency-conflicts by updating pip-tools

Enable ci-integration tests on GHA (incl fixing a few tests)

---

.github/workflows/ci.yaml

We relied on ~/.local/bin being in PATH, which was added in:
actions/virtual-environments#2982
But, then they reverted that because it wasn't cross-shell consistent:
actions/virtual-environments#2982
So, vars were getting loaded from /etc/profile.d, then they moved it
back into ~/.bashrc. But, by default GHA workflows do not source
~/.bashrc.
Who knows how else they are going to mess with the PATH, so just write
our own.

Workaround modified GitHub Actions PATH var

---

.github/workflows/ci.yaml
scripts/github/prepare-integration.sh
st2common/st2common/service_setup.py
st2common/st2common/services/coordination.py
st2common/tests/integration/test_service_setup_log_level_filtering.py
st2common/tests/unit/services/test_synchronization.py

This pull request configures redis coordination backend for integration tests to see if this will help with various race conditions which cause test failures we see quite often with orquesta integration tests.

Configure redis coordination backend for orquesta integration tests

---

CHANGELOG.rst

This pull request adds a changelog entry for RHEL / CentOS 8 RPM package metadata fix in https://github.com/StackStorm/st2-packages/pull/697.

Add changelog entry for RHEL / CentOS 8 "Provides" package metadata bug fix

---

conf/nginx/st2.conf

The default Nginx configuration can have many vulnerabilities, a fix for a few of them.
1. Disable unwanted HTTP methods - Allowing TRACE or DELETE is risky as it can allow a Cross-Site Tracking attack and potentially allow a hacker to steal the cookie information.
2. HTTP requests with a large byte range in the range header can trigger the crash so have to handle this by using this proxy_set_header Range "";

Fixed Apache range header DOS and proxy disclosure issue

---

CHANGELOG.rst

This pull request adds changelog entry for change at https://github.com/StackStorm/st2web/pull/868.

Add changelog entry for https://github.com/StackStorm/st2web/pull/868.

---

CHANGELOG.rst
st2api/tests/unit/controllers/v1/test_actions.py
st2api/tests/unit/controllers/v1/test_base.py
st2client/st2client/shell.py
st2client/st2client/utils/misc.py
st2client/tests/unit/test_commands.py
st2client/tests/unit/test_shell.py
st2common/st2common/middleware/instrumentation.py
st2common/st2common/router.py
st2common/st2common/util/green/shell.py
st2common/tests/integration/test_util_green.py
st2tests/st2tests/api.py

**Problem:**
Running ST2 actions as subprocesses (`eventlet.green`) spawns zombies on timeout.
**Reproduce:**
1. Spawn process which execution is going to take more than command's timeout.
2. `process.kill()` will be called.
3. Spawned process becomes zombie.
Method `process.kill()` is never handled as well as `process.communicate()`, which calls `process.wait()` - all those methods check `process.returncode` against None and if `returncode` already set, it just will be returned.
Why do I suggest to remove line 170: it doesn't seem to be necessary to set returncode here to avoid race condition for some `kill_func`. Probably additional custom attribute could be used here on `process` to provide that information if it's really necessary, but I don't think ST2 should do that.

Fix subprocess handling when killed on timeout

---

CHANGELOG.rst
conf/st2.dev.conf
fixed-requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

The coordinator service is required in most cases for running workflows. Install redis-server and configure redis as the default coordinator backend used by tooz. This will avoid a number of workflow issues, especially for new StackStorm users.

Make redis the default coordinator backend

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt

`prometheus_client` was part of a metrics driver that was dropped. #4310 (https://github.com/StackStorm/st2/pull/4310/commits/82772cc64026b83792a344561844c4dcb09946e7) #4504 (https://github.com/StackStorm/st2/pull/4504/commits/873c57f8331e29832e17904fd9dbb9494d53c53b) _unused since v2.9.0_
`zipp` and `more-itertools` were py2-only transitive deps. #4843 #4847 (afaict these were transitive deps via `wheel`) _added in v3.2.0; unused since v3.4.0 when we dropped python 2_
`python-gnupg` was dropped with the removal of st2debug. #5103 _unused since v3.4.0_
background: _I discovered this as part of an experiment using [pants](https://pantsbuild.org) in [st2sandbox/st2@pants](https://github.com/st2sandbox/st2/tree/pants) to replace the Makefile and related scripts._

Drop unused dependencies

---

.github/workflows/ci.yaml
CHANGELOG.rst
st2common/st2common/util/config_loader.py
st2common/tests/unit/test_config_loader.py
st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_additional_properties_1/config.schema.yaml
st2tests/st2tests/fixtures/packs/dummy_pack_schema_with_additional_properties_1/pack.yaml

The pack config loader uses "secret: true" in a schema to trigger decrypting a key from the datastore. However, it does not look at the schema under additionalProperties, so those properties can't use encrypted keys.
This issue was first documented in https://github.com/StackStorm-Exchange/stackstorm-jira/pull/19#discussion_r242319464
This PR fixes that so that the pack config loader handles additionalProperties when defined.

Fix decrypting pack config keys under additionalProperties

---

contrib/runners/action_chain_runner/tests/unit/test_actionchain_notifications.py
contrib/runners/orquesta_runner/tests/unit/test_notify.py
st2common/st2common/services/action.py
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_chain_sequential.yaml
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_subworkflow_default_with_notify_task.yaml
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/test_chain_sequential.yaml
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/test_subworkflow_default_with_notify_task.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/sequential-with-notify.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/subworkflow-with-notify-task.yaml
st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/subworkflow-with-notify-task.yaml

This pull request resolves https://github.com/StackStorm/st2/issues/5221

Add support to skip action notifications when executed under workflow context

---

.github/workflows/ci.yaml
.github/workflows/orquesta-integration-tests.yaml

This PR updates integration tests CI jobs so we preserve service logs on test failure.
This may help us troubleshoot various integration tests related failures.
Since service logs are quite large uncompressed (~300 MB) I added a step which compresses them and set a shorter retention policy.

Persist StackStorm service logs on integration tests failure

---

CHANGELOG.rst
st2actions/st2actions/notifier/config.py
st2client/st2client/commands/action.py
st2client/st2client/commands/inquiry.py
st2client/st2client/commands/keyvalue.py
st2client/st2client/commands/resource.py
st2client/st2client/commands/rule_enforcement.py
st2client/st2client/commands/trace.py
st2client/st2client/commands/triggerinstance.py
st2client/st2client/models/reactor.py
st2client/tests/base.py
st2client/tests/unit/test_commands.py
st2client/tests/unit/test_inquiry.py
st2client/tests/unit/test_shell.py
st2exporter/st2exporter/config.py
st2reactor/st2reactor/garbage_collector/config.py
st2reactor/st2reactor/rules/config.py

This pull request addresses one of my biggest minor annoyances with StackStorm CLI.
A lot of times when I'm debugging / troubleshooting things, I need to view multiple resources at once to see what is going on.
This means that currently I need to run more than one command to achieve that.
For example:
```bash
st2 execution get id1
st2 execution get id2
st2 execution get id3
```
This slows things down and means more typing (yes, I can use a bash alias or function, but that's not ideal and it's not available out of the box).
With this change, user can now view more than one resource using the get command.
The same pattern is already available with ``st2 execution cancel`` command (I added it a while ago).
For example:
```bash
st2 execution get id1 id2 id3
```
Example output:
```bash
st2 …
```

Allow user to retrieve more than one resource using "st2 resource get" CLI command

---

.github/workflows/microbenchmarks.yaml
st2api/st2api/controllers/resource.py
st2api/tests/unit/controllers/v1/test_executions.py

This pull request includes a small fix needed for MongoDB 4.4 compatibility issue previously reported here - #5247.
Versions of MongoDB prior to 4.4 automatically and transparently handled overlapping values for projection queries (e.g. ``foo, bar, baz, bar.foo`` would get "translated" to ``foo, bar, baz``), but 4.4 throws if such values are provided for a projection query.
This pull request includes a small change which acts as a compatibility layer. We now perform "sanitization" of the include fields in the API side (aka if we see foo,bar,foo.a, we translate it to foo,bar).
In ideal world, we would throw a validation exception in such scenario, but this would change previous behavior and could break custom scripts or similar if someone is using overlapping values for …

Fix overlapping include field values for compatibility with Mongo DB 4.4

---

fixed-requirements.txt
requirements.txt
st2actions/requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
test-requirements.txt

This PR upgrades more dependencies to the latest stable versions (gitpython, semver + dev / testing deps).
gitpython one was very outdated. I verified that installing packs from git still works correctly.

Upgrade various deps to latest versions

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Update orquesta to v1.4.0 to prepare for StackStorm v3.5.0 release.

Update orquesta to v1.4.0

---

CHANGELOG.rst
st2actions/st2actions/policies/concurrency.py
st2actions/st2actions/policies/concurrency_by_attr.py
st2common/st2common/policies/base.py

The get uid method for the concurrency policies is not used. Remove related methods to avoid confusion.

Clean up unused methods in concurrency policies

---

.circleci/config.yml

Update circleci to run packages for focal and remove xenial

Add focal and remove xenial

---

st2common/setup.py

This PR adds missing setup.py scripts entry so the new migration script gets installed into virtualenv ``bin/`` directory.
https://github.com/StackStorm/discussions/issues/81#issuecomment-863227036

Add missing setup.py entry for the new migration script

---

OWNERS.md

It's been quite sometime since I made active use of StackStorm, and following a recent job change I've come to the realisation that I'm not sure when it'll possible to start making an active contribution to StackStorm again.
So doing the right thing and moving myself from the **Contributors** section to **Friends** in `OWNERS.md`.
- docs: Moving myself (@jjm) to Friends from Contributors.

Moving myself (@jjm) to Friends from Contributors

---

CHANGELOG.rst
contrib/runners/action_chain_runner/action_chain_runner/__init__.py
contrib/runners/announcement_runner/announcement_runner/__init__.py
contrib/runners/http_runner/http_runner/__init__.py
contrib/runners/inquirer_runner/inquirer_runner/__init__.py
contrib/runners/local_runner/local_runner/__init__.py
contrib/runners/noop_runner/noop_runner/__init__.py
contrib/runners/orquesta_runner/orquesta_runner/__init__.py
contrib/runners/python_runner/python_runner/__init__.py
contrib/runners/remote_runner/remote_runner/__init__.py
contrib/runners/winrm_runner/winrm_runner/__init__.py
st2actions/st2actions/__init__.py
st2api/st2api/__init__.py
st2auth/st2auth/__init__.py
st2client/st2client/__init__.py
st2common/st2common/__init__.py
st2reactor/st2reactor/__init__.py
st2stream/st2stream/__init__.py
st2tests/st2tests/__init__.py

GHA [CI is failing](https://github.com/StackStorm/st2/runs/2985686600?check_suite_focus=true) because our [release scripts](https://github.com/StackStorm/st2cd/blob/da810fdfa353a976743b8a16d70f34d63c613957/actions/st2_chg_ver_for_st2.sh#L79) insert single quotes instead of double quotes:
```bash
sed -i -e "s/\(__version__ = \).*/\1'${VERSION}'/" ${INIT_FILE}
```
But black forces us to use double quotes:
```
================== black-check ====================
===========================================================
Running black on st2actions
===========================================================
would reformat /home/runner/work/st2/st2/st2actions/st2actions/__init__.py
Oh no! 💥 💔 💥
1 file would be reformatted, 59 files would be left unchanged.
make: *** [Makefile:372: …
```

Fix version quotes for black

---

CHANGELOG.rst
st2common/st2common/constants/garbage_collection.py

A very simple change to modify the minimum TTL on the garbage collector, pulling it back to 1 day from 7.
It still seems quite reasonable to ensure the user doesn't specify "0".

Change minimum garbage_collection TTL to 1 day from 7

---

st2client/README.rst

Fix README as made in 3.5 release process as fails pypi validation.

Fix README that fails pypi checking

---

Makefile
st2client/README.rst
st2client/setup.py

Add lint checks to st2client README.rst so that catch before do pypi upload during release
Resolves #5191

Add st2client README checks to CI

---

CHANGELOG.rst
st2client/st2client/commands/pack.py

Remove deprecated python3 flag

---

contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
contrib/runners/orquesta_runner/tests/unit/test_policies.py
contrib/runners/orquesta_runner/tests/unit/test_rerun.py
contrib/runners/orquesta_runner/tests/unit/test_with_items.py
st2common/st2common/services/executions.py
st2common/tests/unit/test_executions_util.py

Race condition causing orquesta workflow status to change to running after it completed successfully. To avoid this incorrect status update, skipping execution object update is execution is already in completed state.
More details about issue: https://github.com/StackStorm/st2/issues/5222

5222 - Skip action update if execution already in completed state.

---

.gitignore

I use vim quite a bit, so I end up with a variety of vim temporary files.
I could use my user gitignore, but this could be helpful for other vim users as well, so I'm submitting a quick PR.

Ignore more vim temp files

---

contrib/examples/actions/noop.py
contrib/examples/actions/print_config.py
contrib/examples/actions/python-mock-core-remote.py
contrib/examples/actions/python-mock-create-vm.py
contrib/examples/actions/pythonactions/fibonacci.py
contrib/examples/actions/pythonactions/forloop_get_github_page.py
contrib/examples/actions/pythonactions/forloop_increase_index_and_check_condition.py
contrib/examples/actions/pythonactions/forloop_parse_github_repos.py
contrib/examples/actions/pythonactions/forloop_push_github_repos.py
contrib/examples/actions/pythonactions/isprime.py
contrib/examples/actions/pythonactions/json_string_to_object.py
contrib/examples/actions/pythonactions/load_and_print_fixture.py
contrib/examples/actions/pythonactions/object_return.py
contrib/examples/actions/pythonactions/print_python_environment.py
contrib/examples/actions/pythonactions/print_python_version.py
contrib/examples/actions/pythonactions/yaml_string_to_object.py
contrib/examples/actions/ubuntu_pkg_info/lib/datatransformer.py
contrib/examples/actions/ubuntu_pkg_info/ubuntu_pkg_info.py
contrib/examples/lib/environ.py
contrib/examples/sensors/echo_flask_app.py
contrib/examples/sensors/fibonacci_sensor.py
contrib/examples/sensors/sample_polling_sensor.py
contrib/examples/sensors/sample_sensor.py
contrib/examples/tests/test_action_isprime.py
contrib/hello_st2/sensors/sensor1.py
contrib/packs/tests/test_action_aliases.py

I ran flake8 on some contrib directories that the Makefile doesn't normally include.
This PR lets flake8 succeed running over those files as well.
It is mostly adding license headers, as well as fixing a few six imports.

Add license headers and other flake8 fixes for contrib

---

scripts/write-headers.sh

I tried running scripts/write-headers.sh on Mac OSX but the sed behavior, or perhaps the escaping behavior, was slightly different, so the headers were malformed. In particular `\n` did not add a newline as expected. So, I massaged the HEADER message such that injecting that newline was no longer necessary.

Fix running scripts/write-headers.sh on Darwin

---

CHANGELOG.rst
st2common/st2common/models/db/__init__.py

the `isMaster` MongoDB command is depreciated in future versions of mongo. `hello` is in the updated patch versions across a few major versions: `4.4.2: (and 4.2.10, 4.0.21, and 3.6.21)`
https://docs.mongodb.com/v4.4/reference/command/hello/#mongodb-dbcommand-dbcmd.hello
This minor update supports future MongoDB development

update db connect mongo connection test

---

CHANGELOG.rst
st2common/st2common/models/db/__init__.py

A follow-up to https://github.com/StackStorm/st2/pull/5302 where we replaced `isMaster` with `hello` for checking Mongo connection. Instead of mongodb version-specific `hello`, use `ping` instead that works with any mongo version as a safer alternative.
See https://www.mongodb.com/community/forums/t/how-to-use-the-new-hello-interface-for-availability/116748/
Credit goes to @blag for finding a better solution.
@lukepatrick would appreciate your feedback as well if we're good here.

Avoid mongodb compatibility regression by using 'ping' instead of 'hello' command

---

OWNERS.md

Jacob (@cognifloyd) was an active StackStorm community member for many years.
Being more involved around the Ansible, deployments, and Operations in the past, he started participating in the StackStorm project life more and contributed to the StackStorm core (people loved it!), Packaging, StackStorm-HA (K8s), helping with really massive efforts for the StackStorm-Exchange maintenance and ChatOps rework (https://github.com/StackStorm/discussions/issues/8) that includes development and intra-community collaboration with OpsDroid project to draw the future of st2chatops.
I'm also glad that as a Contributor and member of StackStorm Github org he jumped in and helped to triage lots of issues, applying tags, reviewing Pull Requests, following best standards for the open-source project …

Add Jacob (@cognifloyd) to the TSC Maintainers

---

OWNERS.md

AJ (@guzzijones) joined our community a while ago and became an active member of the open-source project.
He was a tester for several releases, participated in trying functionality and giving feedback for the `v3.5.0` performance improvements https://github.com/StackStorm/st2/pull/4846 working closely with @kami, provided fixes to st2: https://github.com/StackStorm/st2/pull/5267, https://github.com/StackStorm/st2/pull/5042, and also contributed to the Orquesta before: https://github.com/StackStorm/orquesta/pull/209, implementing `orquesta-rehearse` command to allow users run unit tests for workflow definition.
He is an active community member in Slack, TSC Meetings and also wrote blog posts about StackStorm:
* [StackStorm Dynamic Checkbox …

Add AJ (@guzzijones) to the TSC Maintainers

---

st2client/st2client/commands/action.py
st2client/st2client/commands/auth.py
st2client/st2client/commands/pack.py
st2client/st2client/commands/policy.py
st2client/st2client/commands/rule.py
st2client/st2client/commands/rule_enforcement.py
st2client/st2client/commands/sensor.py
st2client/st2client/commands/timer.py
st2client/st2client/commands/trace.py
st2client/st2client/commands/trigger.py
st2client/st2client/commands/triggerinstance.py
st2client/st2client/commands/webhook.py
st2common/st2common/services/datastore.py

Before this change, some places explicitly imported models from `st2client.models.<model>` and other places imported models from `st2client.models`. These `st2client.models` imports rely on the fact that `st2client/st2client/models/__init__.py` implicitly imports all models like:
```
from st2client.models.<model> import *  # noqa
```
Note the "# noqa" which silences our linters instead of dealing with the bad `import *` practice.
For external code, relying on the `from ... import *` in `st2client.models` is fine; And, doing so allows 3rd party code to have a much nicer interface. However, in ST2 code we should prefer explicit imports.

Prefer explicit imports from st2client.models

---

OWNERS.md

Carlos is one of the earliest community members and is known as someone who deeply cares about the StackStorm ChatOps and Open Source future.
He's a creator behind the Python-based [err-stackstorm](https://github.com/nzlosh/err-stackstorm) project as an alternative to the Javascript-based st2chatops.
Contributed to the numerous StackStorm-Exchange packs: `Consul`, `PowerDNS`, `syslog`, `icinga2`, `opsgenie`, `salt`, `prometheus`.
For the past half-year he became highly active in his StackStorm core contributions with significant efforts around the most recent `v3.5.0` release where he worked in a team with other TSC Members (@amanda11 @winem @Kami @blag) to ship the big [Plan: Python 3.8 support for Ubuntu 20.04 #68](https://github.com/StackStorm/discussions/issues/68). All these critical …

Add Carlos (@nzlosh) to TSC maintainers

---

st2api/st2api/controllers/v1/actions.py
st2api/tests/unit/controllers/v1/test_actions.py

Currently if PermissionError (or any other exception) occurs during removing files from disk, action delete operation deregisters the action from database but action files remains in filesystem i.e. this operation leaving st2 in an inconsistent state. So, it is required to rollback the operation and register action to database again if such case occurs.

Bug fix in modified action delete API

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
fixed-requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/util/jinja.py
st2common/st2common/util/param.py
tools/st2-analyze-links.py
tools/visualize_action_chain.py

Use Jinja sandboxed environment, so that any templates that attempt to access insecure code will be rejected.

Use Jinja sandboxed environment

---

CHANGELOG.rst
st2api/st2api/controllers/v1/actions.py
st2api/tests/unit/controllers/v1/test_actions.py
st2client/st2client/commands/action.py
st2client/st2client/models/core.py
st2client/tests/unit/test_models.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

* Action delete API modification to have option to delete action database entry without removing files from disk
* From CLI `st2 action delete <pack>.<action>` will delete database entry only
* From CLI `st2 action delete --remove-files <pack>.<action>` will delete database entry and files.
* If action DELETE method has additional argument as `{"remove_files": true}` in the body then it will remove related action files from disk along with database entry.
* `{"remove_files": false}` or no additional argument in action DELETE method body will remove only database entry.

Action delete API rework - support for action file deletion

---

st2common/st2common/rbac/types.py

Add RBAC permission types for key value pairs so the changes at https://github.com/StackStorm/st2-rbac-backend/pull/55 to introduce RBAC to KVP can pass CI.

Add RBAC permission types for key value pairs

---

st2common/st2common/openapi.yaml
st2common/st2common/rbac/types.py
st2common/tests/unit/test_rbac_types.py

The function get_permission_type uses the string value of ResourceType.KEY_VALUE_PAIR which is key_value_pair to return the enum for the permission type. Since the permissions are prefixed with KEY_VALUE and not KEY_VALUE_PAIR, get_permission_types return not found error.

Rename prefix of KEY_VALUE permission types to KEY_VALUE_PAIR

---

.github/workflows/ci.yaml
.github/workflows/orquesta-integration-tests.yaml
CHANGELOG.rst
Makefile
OWNERS.md
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
fixed-requirements.txt
requirements.txt
st2common/bin/st2ctl
st2common/in-requirements.txt
st2common/requirements.txt

Just seen on CentOS7/8 during package build process:
```
[wheelhouse: st2] [13:58:59]      Processing /tmp/wheelhouse/networkx-2.6.3-py3-none-any.whl
[wheelhouse: st2] [13:58:59]        File was already downloaded /tmp/wheelhouse/networkx-2.6.3-py3-none-any.whl
[wheelhouse: st2] [13:58:59]      ERROR: Package 'networkx' requires a different Python: 3.6.8 not in '>=3.7'
[wheelhouse: st2] [13:58:59]      WARNING: You are using pip version 20.3.3; however, version 21.2.4 is available.
[wheelhouse: st2] [13:58:59]      You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[wheelhouse: st2] [13:58:59]      make: *** [.stamp-wheelhouse] Error 1
ERROR: 1
Exited with code exit status 1
```
This PR pins networkx to versions lower than 2.6

Pin networkx to versions lower than 2.6 which doesn't support Python 3.6

---

scripts/populate-package-meta.sh

I noticed a python3 issue while reviewing st2-packaging logs (as `python` does not exist on newer distros), so here's the fix.

use python3 in scripts/populate-package-meta.sh

---

contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Update orquesta to v1.5.0 with a number of fixes for the st2 v3.6.0 release. The v1.5.0 release closes a security vulnerability with Jinja2 template and optimizes performance of workflow inspection.

Update orquesta to v1.5.0

---

CHANGELOG.rst
st2actions/tests/unit/test_workflow_engine.py
st2common/st2common/services/executions.py
st2common/tests/unit/services/test_workflow_service_retries.py

Making update_execution() atomic to avoid concurrent updates causing inconsistency.
In the below screenshot two concurrent updates to the execution object resulted in inconsistent data where overall execution is set to running, but the log field depicts the execution had succeeded.
How did this happen?
Two interleaved [update_execution()](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/executions.py#L191-L230) can cause this. 
| P1  | P2 |
| ------------- | ------------- |
| liveaction.status = running  | liveaction.status = succeeded |
| execution.status = running  | execution.status = running |
| [if condition](https://github.com/StackStorm/st2/blob/master/st2common/st2common/services/executions.py#L199) is not valid. Move forward. | [if …

Make update_execution() atomic

---

README.md

Update the StackStorm-Exchange reference from https://exchange.stackstorm.com to original https://exchange.stackstorm.org
Despite the current redirect set between the domains, there is no guarantee it'll work in the future.

Update the StackStorm-Exchange reference

---

CHANGELOG.rst

Let's use this PR to do add any final entries to the changelog for the 3.6 release.
StackStorm/st2#5286

Add changelog entries for 3.6 Release

---

README.md

Per https://github.com/StackStorm/discussions/issues/89 plan we've moved from Discourse forum to native GH Discussions.
The PR replaces the badge and URL in the `README.md` to use new GH Discussions.

Replace Forum badge with GH Discussions

---

OWNERS.md

Ankur (@rush-skills) was active in StackStorm community for the past several months, he also joined us in several TSC meetings and helped with the development, ideas and improvements around the project.
PRs:
- https://github.com/StackStorm/puppet-st2/pull/335
- https://github.com/StackStorm/puppet-st2/pull/337
- https://github.com/StackStorm/puppet-st2/pull/329
- https://github.com/StackStorm/puppet-st2/pull/330
- https://github.com/StackStorm/puppet-st2/pull/331
Taking part in the Discussions, Reviews, Slack and `#development` channels, asking questions, st2 Q/A topics, trying to discuss the tech ideas, - all this makes him a good teamplayer:
- https://github.com/StackStorm/st2/discussions/5278
- https://github.com/StackStorm/ansible-st2/pull/298
- …

Add Ankur Singh (@rush-skills) as a StackStorm Contributor

---

OWNERS.md

I'd like to highlight the StackStorm enhancements made by Khushboo (@khushboobhatia01) and propose adding her to the list of Contributors.
Between the open-source work, we've seen PRs for st2 core enhancements:
- https://github.com/StackStorm/st2/pull/5293
- https://github.com/StackStorm/st2/pull/5227
- https://github.com/StackStorm/st2/pull/5338
- https://github.com/StackStorm/st2/pull/5344
- https://github.com/StackStorm/st2/pull/5367
- https://github.com/StackStorm/st2/pull/5358
- https://github.com/StackStorm/st2/pull/5396
- https://github.com/StackStorm/st2/pull/5405
- https://github.com/StackStorm/st2/pull/5428
^^ really in-depth stuff!
Issues, bug reports, discussions:
- https://github.com/StackStorm/st2/discussions/5373
- https://github.com/StackStorm/st2/issues/5221
- …

Add Khushboo Bhatia (@khushboobhatia01) as a Contributor

---

OWNERS.md

Rick (@xod442) was StackStorm supporter and champion for a long time.
During the last couple of years we observed many blogs, tutorials, talks, and HOWTOs by Rick dedicated to st2:
- Tutorial: https://github.com/xod442/stackstorm-tutorial
- HOWTO: [Master the automation universe the easy way! Part 1: Introduction to StackStorm](https://developer.hpe.com/blog/master-the-automation-universe-the-easy-way-part-1-introduction-to-stack/)
- HOWTO: [Master the automation universe the easy way! Part 2: The Art of Packing! ](https://developer.hpe.com/blog/master-the-automation-universe-the-easy-way-part-2-the-art-of-packing/)
- [HPE OneView and ServiceNow integration with StackStorm](https://developer.hpe.com/blog/hpe-oneview-and-servicenow-integration-with-stackstorm/)
- [StackStorm in a docker …

Add Rick Kauffman (@xod442) as a Contributor

---

CHANGELOG.rst
contrib/runners/orquesta_runner/tests/unit/test_cancel.py
contrib/runners/orquesta_runner/tests/unit/test_pause_and_resume.py
st2common/st2common/services/action.py

This is required to track who cancelled/paused/resumed any execution. 
`"context" : { "user" : "stanley", "pack" : "examples", "workflow_execution" : "61a0887aac2049b57fed57de", "paused_by" : "stanley", "resumed_by" : "stanley" }`

Add status changed by user info to context

---

CHANGELOG.rst
st2actions/st2actions/cmd/actionrunner.py
st2actions/st2actions/cmd/scheduler.py
st2actions/st2actions/cmd/st2notifier.py
st2actions/st2actions/cmd/workflow_engine.py
st2api/st2api/cmd/api.py
st2auth/st2auth/cmd/api.py
st2common/st2common/service_setup.py
st2common/st2common/services/coordination.py
st2common/tests/unit/test_service_setup.py
st2reactor/st2reactor/cmd/garbagecollector.py
st2reactor/st2reactor/cmd/rulesengine.py
st2reactor/st2reactor/cmd/sensormanager.py
st2reactor/st2reactor/cmd/timersengine.py
st2stream/st2stream/cmd/api.py

Few services like worker, workflow engine, scheduler and notifier perform a shutdown sequence before exiting the process. This PR will ensure that the services deregister themselves from service registry on shutdown and then continue with shutdown sequence. 
(PR based on https://github.com/StackStorm/st2/discussions/5373 step 1)

Deregister services from service registry on shutdown

---

CHANGELOG.rst
st2common/st2common/services/executions.py

Fixes https://github.com/StackStorm/st2/issues/5483

Fix etcd lock error

---

CHANGELOG.rst
contrib/runners/orquesta_runner/tests/unit/test_cancel.py
contrib/runners/orquesta_runner/tests/unit/test_pause_and_resume.py
st2common/st2common/services/action.py

Reverts StackStorm/st2#5459
Looks like there is a regression from the previous PR which failed in e2e st2-self-check tests.
@khushboobhatia01 We can wait for the patch on top of the previous PR from you.
Alternatively, to unblock the builds, we can revert the PR until another iteration on this feature from your side.
-----
After running the st2-self-check which does some pause/resume workflows:
```
vagrant@stackstorm:~$  sudo ST2_AUTH_TOKEN=$(st2 auth st2admin -p 'Ch@ngeMe' -t) st2-self-check
```
Things will fail with `500` from API:
```
vagrant@stackstorm:~$ st2 execution list
ERROR: 500 Server Error: Internal Server Error
MESSAGE: Internal Server Error for url: http://127.0.0.1:9101/v1/executions/?limit=50&parent=null&sort_desc=True&include_attributes=id%2Caction.ref%2Ccontext.user%2Csta …
```

Revert "Add status changed by user info to context"

---

CHANGELOG.rst
st2common/bin/st2-self-check

When the test run contains several nested workflows the script assumes it's succeeded if at least a single sub-workflow was successful. Instead of that, the check should refer to the parent workflow with "status: succeeded".
Example
```bash
id: 61b105a82f44ed586b2d24d0
action.ref: tests.test_inquiry_chain
parameters: 
protocol: http
token: bbeb3f7d29e240ac83ce3d53fff90745
status: failed 
result_task: get_workflow_details_1
result: 
failed: true
return_code: 2
stderr: ""
stdout: ''
succeeded: false 
error: ""
traceback: None
failed_on: get_workflow_details_1
start_timestamp: Wed, 08 Dec 2021 19:21:12 UTC
end_timestamp: Wed, 08 Dec 2021 19:21:23 UTC
log: 
- status: requested
timestamp: '2021-12-08T19:21:12.277000Z'
- status: scheduled
timestamp: '2021-12-08T19:21:12.434000Z'
- status: …
```

Fix st2-self-check script reporting success on failed runs

---

CHANGELOG.rst

Adding CHANGELOG for recently merged action clone PR #5345.

Add CHANGELOG for action clone feature

---

Makefile

A follow-up for #5417 
Nightly checks are still failing, so we need to explicitly install wheel in the venv.
I'll test a bit first by modifying the GHA workflow used in PRs, and then revert the debug bits to leave only the tested fix.

install wheel to fix check-python-packages-nightly CI

---

CHANGELOG.rst
st2tests/st2tests/mocks/datastore.py

This allows people to test their code if they are already setting a ttl. This resolves #4880
I think we would also be fine with not issuing a log warning, but put that in for completeness.

Enable setting ttl for MockDatastoreService

---

CHANGELOG.rst
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt

Without pysocks PyPi package SOCKS proxies won't work with the following errors.
```
ERROR: Missing dependencies for SOCKS support.
```

#5460 - Include pysocks in st2client

---

CHANGELOG.rst
st2common/st2common/operators.py
st2common/tests/unit/test_operators.py

When i use the webui to make some timediff critera comparison in rules, it always return the  ``TypeError: '>' not supported between instances of 'float' and 'str'``
I tried so many value in critera form, it's just not work.
Then i found in `operators.py`, the `_timediff` is returned `(utc_now - diff_target_utc).total_seconds()` as a float number, the `timedelta.total_seconds()` is always return float type, but the critera-comparison is str or int
Just convert the critera value to float, it will be fine.

fix: timediff typo

---

CHANGELOG.rst
st2common/st2common/services/executions.py
st2common/st2common/services/workflows.py

String lock names are not supported by all the tooz drivers because of unsafe encode/decode and concatenation which results in error with string types.
Example:
- etcd3gw => https://opendev.org/openstack/tooz/src/branch/master/tooz/drivers/etcd3gw.py#L72 `TypeError: can't concat bytes to str`
- memcached => https://opendev.org/openstack/tooz/src/branch/master/tooz/drivers/memcached.py#L79 `TypeError: can't concat bytes to str`
- etcd3 => https://opendev.org/openstack/tooz/src/branch/master/tooz/drivers/etcd3.py#L70 `AttributeError: 'str' object has no attribute 'decode'`
Remaining drivers support both str and byte type
- consul => https://opendev.org/openstack/tooz/src/branch/master/tooz/drivers/consul.py#L295 `Safe decode`
- etcd => …

Use byte type lock name which is supported by all tooz drivers

---

CHANGELOG.rst
st2api/st2api/controllers/v1/action_views.py
st2api/tests/unit/controllers/v1/test_action_views.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

Adding ability to get action parameters by reference.

Adding get_by_ref for ParametersViewController

---

CHANGELOG.rst
st2common/st2common/operators.py
st2common/tests/unit/test_operators.py
st2reactor/st2reactor/rules/filter.py
st2reactor/tests/unit/test_filter.py

The new "multiple" operator is similar to "search" except it adds some additional features. It allows multiple evaluations of the same payload item by a rule. This solves a problem brought up in #2656 
Now evaluations such as the following are possible:
```
trigger.body.location.latitude:
type: multiple
condition: all2any
pattern:
item.value:
type: "lessthan"
pattern: 40
item.value#2:
type: "greaterthan"
pattern: 50
trigger.body.location.longitude:
type: multiple
condition: all2any
pattern:
item.value:
type: "greaterthan"
pattern: -90
item.value#2:
type: "lessthan"
pattern: -100
```
In this example the action for this criteria would occur when the latitude and longitude payload data falls outside the area specified, creating a simple box geo-fence.
There are four different criteria …

Added 'multiple' operator to allow complex criteria matching on payload items

---

CHANGELOG.rst
st2client/st2client/commands/policy.py
st2client/tests/unit/test_shell.py

This error occurs when run ```policy list``` with st2-client.
If the ```--pack``` option is given, it should return only the resources belonging to the provided pack.
However, there was no change in the output when the ```--pack``` option was specified or not.
Don't specify the pack option
```
st2 policy list
+---------------------------------+---------------------+-------------------------+---------+
| ref                             | resource_ref        | policy_type             | enabled |
+---------------------------------+---------------------+-------------------------+---------+
| testpack1.test.concurrency      | testpack1.test      | action.concurrency      | True    |
| testpack2.test.concurrency      | testpack2.test      | action.concurrency      | True    | …
```

Fix issue with pack option not working when running policy list cli

---

fixed-requirements.txt
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

pyOpenSSL 22.0.0 requires cryptography>=35.0 causing dependancy conflicts https://app.circleci.com/pipelines/github/StackStorm/st2/2631/workflows/9226c6bb-50c4-46fc-a71e-f707d7ce01bf/jobs/14228

Pin pyOpenSSL to <= 21.0.0

---

.github/workflows/ci.yaml
.github/workflows/orquesta-integration-tests.yaml
st2actions/st2actions/cmd/actionrunner.py
st2actions/st2actions/cmd/workflow_engine.py
st2common/st2common/transport/consumers.py

Currently when a SIGTERM signal is received by worker or workflow engine, sigterm handler runs in a new thread. Sigterm handler throws SystemExit exception which should be caught in the main thread for shutdown routine to be executed. 
(https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/cmd/actionrunner.py#L74 https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/cmd/workflow_engine.py#L75)
However the above expected behaviour doesn't happen always. When we have other green threads processing messages SystemExit exception can be caught by these thread. And if the try-except block doesn't re-raise the exception, the shutdown routine is never executed.
This PR will take care of raising the exception in main thread, so that it can be caught and shutdown routine …

Link shutdown routine and sigterm handler to main thread

---

CHANGELOG.rst
st2common/st2common/util/param.py
st2common/tests/unit/test_param_utils.py

check if the value is actually jinja and not a string like `{"someurl": "http://test?value={{test"}`

check if value is actually jinja before adding as template

---

.github/workflows/checks.yaml

The Changelog is important so the community can track what changes they might expect in the upcoming releases or developers could pinpoint the changes to a particular PR and diff.
We could naturally forget or new contributors might not know about updating Changelog. Additionally, we don't want to go to every PR and ask for a Changelog addition.
This GH Action (https://github.com/marketplace/actions/changelog-checker) will verify if `CHANGELOG.rst` was updated for every PR:
<details>
<summary>GH Actions view</summary>
</details>
For rare cases when it's needed to skip the check, assign `no changelog` label for the PR.

Add a Changelog Checker

---

CHANGELOG.rst
st2common/st2common/models/db/execution.py

We've seen increase in mongoDB memory usage whenever we try to fetch executions with filters.
- Query:
`db.action_execution_d_b.find({"action.ref": "sre.fleet_execution", "start_timestamp": {"$gt" : NumberLong("1638316000000000"), "$lt": NumberLong("1644192000000000")},"status" : "succeeded"}, {"context" : 1,"parameters" : 1,"action" : 1,"start_timestamp" : 1,"status" : 1,"runner.runner_parameters" : 1,"_id" : 1,"end_timestamp" : 1}).sort({"start_timestamp" : -1,"action.ref" : 1})`
- With above query it's expected that the compound index start_timestamp_-1_action.ref_1_status_1 should be used, but the query plan shows that action.ref_1 index is being used.
[old-query-plan.txt](https://github.com/StackStorm/st2/files/8021062/old-query-plan.txt)
- Execution stats from the old query plan 
> …

Change compound index to improve query performance

---

CHANGELOG.rst
contrib/runners/winrm_runner/tests/unit/test_winrm_base.py
contrib/runners/winrm_runner/winrm_runner/winrm_base.py

When winrm-ps-script runner type was used, found that we were unable to pass parameters successfully from Stackstorm to the PowerShell script. We noticed inconsistent parameter passing to the PowerShell scripts, seemingly being able to pass inputs to smaller scripts but not to larger ones.

WinRM parameter passing fails for larger scripts

---

.github/workflows/ci.yaml
CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/in-requirements.txt
st2actions/requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Fix build errors due to markupsafe 2.1.0 removing soft_unicode, which were breaking the ST2 package tests.
Also, updated the GHA workflow as problems found after requirements.txt was altered. Altered so that it only looks for a cache on exact match of key instead of partial, so that doesn't try and pick up cache from previous version of requirements.txt.

Fix build failures due to newer  MarkUpSafe

---

CHANGELOG.rst
Makefile
contrib/packs/actions/pack_mgmt/get_installed.py
contrib/runners/local_runner/tests/integration/test_localrunner.py
st2actions/st2actions/scheduler/handler.py
st2api/st2api/controllers/resource.py
st2api/tests/unit/controllers/v1/test_executions.py
st2common/bin/st2-purge-task-executions
st2common/bin/st2-purge-workflows
st2common/st2common/middleware/logging.py
st2reactor/st2reactor/container/hash_partitioner.py
test-requirements.txt

black v22.3.0 fixes an incompatibility with click, which is a transitive dep.
see: https://github.com/psf/black/issues/2964
I've had to update other projects recently for the same issue.
I just saw an error in CI that hit this issue, so let's update before anything else bites us.
see: https://github.com/StackStorm/st2/runs/5796530459?check_suite_focus=true
Also includes a minor fixture update (test_content_pack submodule) because I'm tired of Make complaining. There is no functional difference with the update. The test pack has newer commits because of CI updates on the exchange.

Bump black to v22.3.0 and update format

---

.github/workflows/microbenchmarks.yaml
.github/workflows/orquesta-integration-tests.yaml
CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

https://github.com/openstack/tooz/blob/174065f8750ff374e140fae956758b0b5ec2c473/requirements.txt#L9

Downgraded tenacity as tooz dependency on tenacity has always been < 7.0.0

---

OWNERS.md

I'd like to thank Ankur Singh (@rush-skills) for participating in the TSC meetings for the last year as a **Contributor**, providing his help and assistance in the project maintenance, and would like to propose @StackStorm/tsc promoting him to @StackStorm/maintainers.
A few highlights: Ankur participated in the maintenance tasks helping to keep the Puppet deployment up-to-date with the major st2 release initiatives and changes, helping maintaining the feature parity between the deployment methods:
* v3.7.0 - https://github.com/StackStorm/puppet-st2/issues/345
* v3.6.0 - https://github.com/StackStorm/puppet-st2/pull/341 closing the https://github.com/StackStorm/puppet-st2/issues/340 which is part of the bigger project plan https://github.com/StackStorm/community/issues/91
* v3.6.0 - …

Promote Ankur Singh (@rush-skills) from Contributor to TSC Maintainer

---

OWNERS.md

I'd like to highlight Yuri Dubler (@lm-ydubler) Contribution activity to the StackStorm project.
Initially, he came with a mission to submit a new StackStorm-Exchange integration pack for LogicMonitor. But because we were in the middle of StackStorm-Exchange refactoring where we were unable to accept new packs, he got involved in a massive work and assisted @cognifloyd in migrating the entire StackStorm-Exchange CI/CD from `CircleCI` to `Github Actions` (project plan: [ [RFC] Use Github Actions for StackStorm-Exchange CI and Maintenance #63 ](https://github.com/StackStorm/community/issues/63)):
* https://github.com/StackStorm-Exchange/ci/pull/118
* https://github.com/StackStorm-Exchange/ci/pull/117
* https://github.com/StackStorm-Exchange/ci/pull/120
* …

Add Yuri Dubler (@lm-ydubler) to the Contributors

---

OWNERS.md

Since we [Added Khushboo Bhatia (@khushboobhatia01) as a Contributor #5450 ](https://github.com/StackStorm/st2/pull/5450), we've seen Khushboo contributing more enhancements and fixes to the st2 core, doing some amazing work:
* https://github.com/StackStorm/st2/pull/5568 - diving deep into the bottleneck and improving the st2 performance :+1: 
* https://github.com/StackStorm/st2/pull/5463 - continue work on a significant stability improvement for the workflow engine
* https://github.com/StackStorm/st2/pull/5528 and https://github.com/StackStorm/st2/pull/5607 as a follow-up
* https://github.com/StackStorm/st2/pull/5554
* https://github.com/StackStorm/st2/pull/5555
* https://github.com/StackStorm/st2/pull/5529 doing a in-depth research and fixing the compatibility with the majority of …

Promote Khushboo Bhatia (@khushboobhatia01) from Contributor to TSC Maintainer

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt

st2client requires importlib-metadata which requires typing-extensions.
But typing-extensions v4.2.0 dropped support for python3.6, so pin it.
Our CI has been broken on st2 master since April 17: https://github.com/StackStorm/st2/actions/workflows/ci.yaml?page=2
Turns out it’s because of typing-extensions which dropped support for python 3.6 on April 17 with their 4.2.0 release: https://github.com/python/typing/blob/master/typing_extensions/CHANGELOG.md

pin typing-extensions<4.2 to fix st2client install

---

CHANGELOG.rst

There are two different/duplicate `Fixed` Changelog sections, so reorder and combine them.
Prepare changelog for next release
This PR will hold any final changelog adjustments. It will be merged just before cutting the final 3.7.0 release.

Prepare Release Notes for v3.7.0

---

OWNERS.md

@cognifloyd was an active StackStorm community member for many years with lots of contributions and proposals around st2 core, ansible, packs, and discussions.
Once joining the StackStorm TSC, he organized massive work to improve the entire StackStorm-Exchange:
1) CI/CD refactoring migrating CircleCI to GH Actions and improving the pack index update model to a more secure and stable. https://github.com/StackStorm/community/issues/63
2) New pack bootstrap, - creating automation for maintainers to set up a new pack with a single command. This now helps onboarding new packs really fast which was a pain point for many years. https://github.com/StackStorm-Exchange/exchange-incubator/pull/167
All this makes StackStorm-Exchange maintenance a breeze!
Jacob drove major contributions in the K8s …

Proposal: Promote Jacob Floyd (@cognifloyd) to Senior TSC Maintainers

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/requirements.txt
st2common/st2common/util/monkey_patch.py

When connecting to redis SSL via sentinel then 2 problems are encountered:
1. redis 3.5.3 did not support ssl parameters for sentinel, see https://github.com/redis/redis-py/pull/1419. So upping the version of redis library
2. When using eventlet and redis SSL then there are connection problems, due to the fact the redis library has expected timeouts, but monkey patched SSL library is throwing different exception. See https://github.com/eventlet/eventlet/issues/692. This causes problems on connecting to redis SSL via sentinel. It also is likely to be the cause of error: https://github.com/StackStorm/st2/issues/5337 as the stack trace encountered is the same.
Therefore when monkey patching SSL library, keep the exception raised on timeout to be socket.timeout.

Fix problems connecting to redis sentinel with SSL

---

CHANGELOG.rst
st2client/st2client/base.py

checking both 'http_proxy' and 'HTTP_PROXY' to get proxy info when using st2 command with --debug option.
Fixes #5137

make http/https_proxy env var checking case insensitive (address issue #5137)

---

contrib/debug/actions/print_ctx.py
contrib/debug/actions/python_version.py

This is very minor and should be quick to review.
Some files are currently not getting linted/checked with our Makefile. I discovered this issue when running linters with pants.

drop unused imports in contrib/debug/actions

---

contrib/runners/winrm_runner/winrm_runner/winrm_base.py
contrib/runners/winrm_runner/winrm_runner/winrm_command_runner.py
contrib/runners/winrm_runner/winrm_runner/winrm_ps_command_runner.py
lint-configs/python/.pylintrc
st2common/benchmarks/micro/test_mongo_field_types.py
st2common/bin/migrations/v3.1/st2-cleanup-policy-delayed.py

With `pants`, I'm running pylint on more of our codebase. So, I hit a few false positives that can just be ignored.
Also, orjson confuses pylint sometimes because pylint doesn't support type stubs (`.pyi`) like orjson provides. So, ignore that too.

Add misc pylint ignores for false positives

---

st2common/st2common/runners/base.py

A very minor refactor.
I noticed that we had a constant and weren't using it. So, let's use it.
https://github.com/StackStorm/st2/blob/8496bb2407b969f0937431992172b98b545f6756/st2common/st2common/constants/runners.py#L40-L41

use the runner.yaml constant

---

CHANGELOG.rst
st2common/st2common/util/monkey_patch.py

Extracted the st2-specific bits from #5674.
This allows setting `ST2_USE_DEBUGGER` as an env var instead of passing `--use-debugger` as a command line arg. An env var is more convenient in some cases, such as when using containerized/docker st2.

add ST2_USE_DEBUGGER env var to mirror --use-debugger arg

---

CHANGELOG.rst
st2client/st2client/base.py

Currently, st2client uses ``http_proxy`` to check os environment variable ``HTTPS_PROXY``, which is not correct.
This PR fixes this by using the correct variable ``https_proxy``.

fix use correct os environ to check HTTPS_PROXY

---

pyproject.toml

I'm working towards introducing [`pants`](https://www.pantsbuild.org/docs). Eventually I would like to use pants to run tests to take advantage of the fine-grained per-file caching of results that accounts for dependencies by python files (pants infers the deps by reading the python files). But, pants uses `pytest` to run tests not `nosetest`.
So, this is the first of several PRs that improves our compatibility with pytest. It adds a pytest config section to `pyproject.toml`. I also included `-l` (display local vars on test failure) because that is extremely helpful when I encounter a test failure via pytest.
Note: I do not have pytest support completely ironed out, but this is a step in that direction. Don't expect running all our tests with pytest to work yet.

Add pytest config section to pyproject.toml

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt
st2common/st2common/util/date.py

Problems using udatetime on python3.9 and it isn't supported.
It was proposed that ciso8601 is used instead.
Relates to https://github.com/StackStorm/st2/issues/5346

Move to ciso8601 for datetime

---

CHANGELOG.rst
conftest.py
st2api/tests/unit/controllers/v1/test_action_views.py
st2api/tests/unit/controllers/v1/test_executions_auth.py
st2api/tests/unit/controllers/v1/test_rule_views.py
st2api/tests/unit/controllers/v1/test_runnertypes.py
st2api/tests/unit/controllers/v1/test_traces.py
st2api/tests/unit/controllers/v1/test_triggertypes.py
st2auth/tests/unit/controllers/v1/test_token.py
st2common/st2common/models/db/__init__.py
st2common/st2common/util/monkey_patch.py
st2common/tests/unit/test_action_param_utils.py
st2common/tests/unit/test_db_base.py
st2common/tests/unit/test_db_fields.py
st2common/tests/unit/test_param_utils.py
st2common/tests/unit/test_purge_executions.py
st2common/tests/unit/test_purge_trigger_instances.py
st2common/tests/unit/test_reference.py
st2common/tests/unit/test_runners_utils.py
st2common/tests/unit/test_tags.py
st2reactor/tests/unit/test_enforce.py
st2reactor/tests/unit/test_rule_engine.py

I'm working towards introducing [`pants`](https://www.pantsbuild.org/docs). Eventually I would like to use pants to run tests to take advantage of the fine-grained per-file caching of results that accounts for dependencies by python files (pants infers the deps by reading the python files). But, pants uses `pytest` to run tests not `nosetest`.
This is another of several PRs that improves our compatibility with pytest. Others include: #5686, #5690, #5691
Note: I do not have pytest support completely ironed out, but this is a step in that direction. Don't expect running all our tests with pytest to work yet.
Tests hang (with endless cycles between green threads that can't figure out what to do) when mongoengine gets imported before the monkey patching. So, this adjusts our monkey_patching …

Adjust monkey_patching to work under pytest

---

st2client/tests/unit/test_formatters.py

I'm working towards introducing [`pants`](https://www.pantsbuild.org/docs). Eventually I would like to use pants to run tests to take advantage of the fine-grained per-file caching of results that accounts for dependencies by python files (pants infers the deps by reading the python files). But, pants uses `pytest` to run tests not `nosetest`.
This is another of several PRs that improves our compatibility with pytest. Others include: #5686, #5689, #5691
Note: I do not have pytest support completely ironed out, but this is a step in that direction. Don't expect running all our tests with pytest to work yet.
Capturing console output uses `capsys` under pytest.
So modify our homegrown console redirection so that it uses capsys when running under pytest.

Fix running st2client unit tests under pytest

---

st2tests/st2tests/base.py

I'm working towards introducing [`pants`](https://www.pantsbuild.org/docs). Eventually I would like to use pants to run tests to take advantage of the fine-grained per-file caching of results that accounts for dependencies by python files (pants infers the deps by reading the python files). But, pants uses `pytest` to run tests not `nosetest`.
This is another of several PRs that improves our compatibility with pytest. Others include: #5686, #5689, #5690
Note: I do not have pytest support completely ironed out, but this is a step in that direction. Don't expect running all our tests with pytest to work yet.
DBTestCase was relying on some unittest/nosetest implmentation details that are not available when running under pytest.
The purpose of those adjustments was: Keep the DB after a test …

Make DBTestCase compatible with pytest

---

CHANGELOG.rst
contrib/packs/tests/test_action_unload.py
st2actions/tests/unit/test_output_schema.py
st2api/tests/unit/controllers/v1/test_actions.py
st2api/tests/unit/controllers/v1/test_packs.py
st2common/tests/integration/test_register_content_script.py
st2common/tests/unit/test_aliasesregistrar.py
st2common/tests/unit/test_configs_registrar.py
st2common/tests/unit/test_content_utils.py
st2common/tests/unit/test_policies_registrar.py
st2common/tests/unit/test_resource_registrar.py
st2common/tests/unit/test_triggers_registrar.py
st2common/tests/unit/test_virtualenvs.py
st2tests/st2tests/fixtures/packs/dummy_pack_1/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_10/fixture.py
st2tests/st2tests/fixturesloader.py

In order to use the fine-grained caching, Pants needs to know which tests rely on which fixtures. We could add **extra** metadata to tie the tests to the fixtures, but that would be an additional maintenance burden that will become out-of-date. We can also include all fixtures for all tests, but then we don't benefit from the fine-grained per-file caching. However, pants can already infer dependencies based on python imports, so that is what this PR (and several follow-up PRs) takes advantage of.
This …

Use python imports to identify fixtures (part 1)

---

CHANGELOG.rst
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
st2api/tests/unit/controllers/v1/test_packs.py
st2api/tests/unit/controllers/v1/test_packs_views.py
st2common/tests/unit/services/test_workflow.py
st2common/tests/unit/test_config_loader.py
st2common/tests/unit/test_config_parser.py
st2common/tests/unit/test_pack_action_alias_unit_testing_utils.py
st2common/tests/unit/test_resource_registrar.py
st2tests/st2tests/fixtures/packs/dummy_pack_10/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_14/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_16/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_17/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_7/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_8/fixture.py
st2tests/st2tests/fixtures/packs/dummy_pack_9/fixture.py
st2tests/st2tests/fixtures/packs/pack_dir_name_doesnt_match_ref/fixture.py
st2tests/st2tests/fixtures/packs/test_content_version_fixture/fixture.py
st2tests/st2tests/fixturesloader.py

In order to use the fine-grained caching, Pants needs to know which tests rely on which fixtures. We could add **extra** metadata to tie the tests to the fixtures, but that would be an additional maintenance burden that will become out-of-date. We can also include all fixtures for all tests, but then we don't benefit from the fine-grained per-file caching. However, pants can already infer dependencies based on python imports, so that is what this PR (and several follow-up PRs) takes advantage of.
This …

Use python imports to identify fixtures (part 4/6)

---

CHANGELOG.rst
contrib/packs/tests/fixtures/__init__.py
contrib/packs/tests/test_action_download.py
st2common/tests/fixtures/local_runner/fixture.py
st2common/tests/integration/log_unicode_data.py
st2common/tests/integration/test_rabbitmq_ssl_listener.py
st2common/tests/integration/test_register_content_script.py
st2common/tests/integration/test_service_setup_log_level_filtering.py
st2common/tests/unit/test_crypto_utils.py
st2common/tests/unit/test_shell_action_system_model.py
st2common/tests/unit/test_spec_loader.py
st2tests/st2tests/fixtures/conf/fixture.py
st2tests/st2tests/fixtures/keyczar_keys/fixture.py
st2tests/st2tests/fixtures/packs/runners/fixture.py
st2tests/st2tests/fixtures/ssl_certs/fixture.py

In order to use the fine-grained caching, Pants needs to know which tests rely on which fixtures. We could add **extra** metadata to tie the tests to the fixtures, but that would be an additional maintenance burden that will become out-of-date. We can also include all fixtures for all tests, but then we don't benefit from the fine-grained per-file caching. However, pants can already infer dependencies based on python imports, so that is what this PR (and several follow-up PRs) takes advantage of.
This …

Use python imports to identify fixtures (part 5/6)

---

CHANGELOG.rst
contrib/runners/winrm_runner/tests/unit/fixtures/__init__.py
contrib/runners/winrm_runner/tests/unit/test_winrm_ps_script_runner.py
st2reactor/tests/fixtures/fixture/__init__.py
st2reactor/tests/fixtures/packs/__init__.py
st2reactor/tests/fixtures/packs/pack_with_rules/fixture.py
st2reactor/tests/fixtures/packs/pack_with_sensor/fixture.py
st2reactor/tests/unit/test_sensor_and_rule_registration.py
st2reactor/tests/unit/test_tester.py

In order to use the fine-grained caching, Pants needs to know which tests rely on which fixtures. We could add **extra** metadata to tie the tests to the fixtures, but that would be an additional maintenance burden that will become out-of-date. We can also include all fixtures for all tests, but then we don't benefit from the fine-grained per-file caching. However, pants can already infer dependencies based on python imports, so that is what this PR (and several follow-up PRs) takes advantage of.
This …

Use python imports to identify fixtures (part 6/6)

---

CHANGELOG.rst
contrib/schemas/sensor.json
st2common/bin/st2-generate-schemas
st2common/st2common/cmd/generate_schemas.py

I'm working towards introducing [`pants`](https://www.pantsbuild.org/docs). One of the first things we will use it for is linting / reformatting (it will run black, flake8, etc). Schema generation should happen more regularly, so we'll hook that up so pants runs it when it runs fmt and other tools.
When pants runs these tools, however, it (or rather PEX, which pants uses), it needs to import the python code. Our script, however, is a kebab-case-file, so python cannot import from it. (Eventually, this will not be a requirement. PEX has been updated to handle this, so pants just needs to have the new option plumbed in before we can use it. For now, though, pants can only run importable python files.)
Currently schema generation is often missed, so the schemas often get out of date. We have …

Refactor `st2-generate-schemas` to be importable

---

CHANGELOG.rst
st2common/st2common/cmd/validate_api_spec.py
st2common/st2common/models/api/pack.py
st2common/st2common/openapi.yaml
st2common/st2common/openapi.yaml.j2

I'm working towards introducing [`pants`](https://www.pantsbuild.org/docs). One of the first things we will use it for is linting / reformatting (it will run black, flake8, etc). Validation of our openapi schema should happen more regularly, so we'll hook that up so pants runs it when it runs lint tools
While hooking that up, I noticed parts of the validation commented out. So, I searched through the git history to figure out when and why.
Basically, it's just tech debt that no one had time to address. So, this is a step in that direction.
Fix and reenable prance-based openapi spec validation, but make our custom `x-api-model` validation optional as the spec is out-of-date.
This also fixes issues identified by the now-enabled spec validation.
Related: #3575 #3788

Fix and reenable prance-based openapi spec validation

---

st2common/tests/unit/test_db.py
st2tests/st2tests/config.py

pants runs each test file separately in pytest. So, if two files try to modify the same database at the same time, we'll get strange results.
So, modify the db name for each parallel test to ensure that they can run safely in parallel.
Once we integrate pants, we will configure (in pants.toml) `[pytest].execution_slot_var = "ST2TESTS_PARALLEL_SLOT"` to take advantage of the env var introduced here.
https://www.pantsbuild.org/docs/reference-pytest#section-execution-slot-var

make mongo tests safer to run in parallel

---

CHANGELOG.rst
pants.toml

This is part 2 of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107) and [06 Sept 2022](https://github.com/StackStorm/community/issues/108). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as manageable/reviewable as possible, introducing pants will take a series of …

Configure pantsbuild source roots

---

.gitignore
CHANGELOG.rst

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107) and [06 Sept 2022](https://github.com/StackStorm/community/issues/108). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as manageable/reviewable as possible, introducing pants will take a …

Adjust .gitignore to work better with pantsbuild

---

CHANGELOG.rst
pants.toml

This is part 3 of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107) and [06 Sept 2022](https://github.com/StackStorm/community/issues/108). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as manageable/reviewable as possible, introducing pants will take a series of …

Enable pantsbuild language backends

---

.github/workflows/pants.yaml
CHANGELOG.rst
pants.ci.toml

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107) and [06 Sept 2022](https://github.com/StackStorm/community/issues/108). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as manageable/reviewable as possible, introducing pants will take a …

Add GHA workflow to validate pants BUILD files

---

CHANGELOG.rst
pants.toml

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107) and [06 Sept 2022](https://github.com/StackStorm/community/issues/108). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as manageable/reviewable as possible, introducing pants will take a …

Configure `pants_ignore` and bump pants to v2.14.0rc1

---

CHANGELOG.rst
pants.toml

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107) and [06 Sept 2022](https://github.com/StackStorm/community/issues/108). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as manageable/reviewable as possible, introducing pants will take a …

Explicitly disable pantsbuild opt-in anonymous telemetry

---

.github/workflows/lint.yaml
CHANGELOG.rst

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107), [06 Sept 2022](https://github.com/StackStorm/community/issues/108), and [04 Oct 2022](https://github.com/StackStorm/community/issues/111). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as …

Add GHA workflow to lint with pantsbuild

---

CHANGELOG.rst
contrib/core/actions/send_mail/BUILD
contrib/examples/actions/BUILD
contrib/examples/actions/bash_ping/BUILD
contrib/examples/actions/bash_random/BUILD
contrib/linux/actions/BUILD
pants.toml
scripts/BUILD
st2actions/bin/BUILD
st2api/bin/BUILD
st2auth/bin/BUILD
st2common/bin/BUILD
st2common/bin/migrations/v2.1/BUILD
st2common/bin/migrations/v3.5/BUILD
st2common/tests/fixtures/BUILD
st2reactor/bin/BUILD
st2stream/bin/BUILD
st2tests/integration/BUILD
st2tests/st2tests/fixtures/packs/BUILD
st2tests/testpacks/errorcheck/actions/BUILD
tools/BUILD

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107), [06 Sept 2022](https://github.com/StackStorm/community/issues/108), and [04 Oct 2022](https://github.com/StackStorm/community/issues/111). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as …

Use shellcheck (via pantsbuild)

---

.github/workflows/lint.yaml
.github/workflows/pants.yaml
CHANGELOG.rst
pants

Github updated the default minor version of python 3.9.x The cache key did not include the minor version which broke things for us.
Luckily, this was already fixed in pantsbuild/actions#6. The fix requires an update to the `./pants` entrypoint/bootstrap script which was updated in pantsbuild/setup#128.
Based on [pants docs](https://www.pantsbuild.org/v2.14/docs/manual-installation#manual-installation), I updated `./pants` with:
```
curl -L -O https://static.pantsbuild.org/setup/pants && chmod +x ./pants
```

Update GHA pants-init action to fix build

---

CHANGELOG.rst
st2common/st2common/util/output_schema.py
st2common/tests/unit/test_util_output_schema.py

Add backward compatibility to secret masking introduced in #5319 to prevent security-relative issues. Migration to the new schema is required to take advantage of the full output schema validation.

Add backward compatibility to secret masking for output schema

---

CHANGELOG.rst
lint-configs/regex-lint.yaml
pants.toml

This is another part of introducing [`pants`](https://www.pantsbuild.org/docs), as discussed in the TSC Meetings on [12 July 2022](https://github.com/StackStorm/community/issues/105), [02 Aug 2022](https://github.com/StackStorm/community/issues/107), [06 Sept 2022](https://github.com/StackStorm/community/issues/108), and [04 Oct 2022](https://github.com/StackStorm/community/issues/111). Pants has fine-grained per-file caching of results for lint, fmt (like black), test, etc. It also has lockfiles that work well for monorepos that have multiple python packages. With these lockfiles CI should not break when any of our dependencies or our transitive dependencies release new versions, because CI will continue to use the locked version until we explicitly relock with updates.
To keep PRs as …

Use regex-lint to provide circular dependency checking in pants

---

BUILD
CHANGELOG.rst
contrib/core/BUILD
contrib/runners/winrm_runner/BUILD
lockfiles/st2-constraints.txt
pants.toml
requirements-pants.txt

Our 3rd party dependencies will be in a lockfile that looks like [`lockfiles/st2.lock`](https://github.com/st2sandbox/st2/blob/pants/lockfiles/st2.lock). But, before pants can generate that, we need to add several pieces of metadata including dependencies and python version constraints.
This PR focuses on registering all of our dependencies. Future PRs will add the python version constraints (aka interpreter …

Inform pants about 3rd party dependencies and constraints

---

CHANGELOG.rst
pants.toml

This updates to pants 2.14. We were on release candidates before.
pants 2.14 changed a default setting from `ignore` to `warning`, but most of the warnings are not actionable for us. Eventually, we should be able to address the warnings cleanly. For now, let's just ignore the warnings.
Alternatively, we could add `# pants: no-infer-dep` comments all over the place, which is not ideal.
We can revisit this setting in pants 2.16. A new feature under development for 2.16 should make cleaning up these warnings much easier, and therefore worth the effort.

Update to pants 2.14 (final)

---

CHANGELOG.rst
lockfiles/bandit.lock
lockfiles/black.lock
lockfiles/flake8.lock
pants.toml

Our 3rd party dependencies will be in a lockfile that looks like [`lockfiles/st2.lock`](https://github.com/st2sandbox/st2/blob/pants/lockfiles/st2.lock). But, before pants can generate that, we need to add several pieces of metadata including dependencies and python version constraints.
This PR focuses on registering our python version constraints (in `pants.toml`). Other PRs will add the dependencies (see …

Inform Pants about our target python versions (3.6 and 3.8)

---

.github/workflows/checks.yaml
.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/microbenchmarks.yaml
.github/workflows/orquesta-integration-tests.yaml
.github/workflows/pants.yaml

GHA just updated the ubuntu VM so that ubuntu-latest now points to 22.04.1 instead of 20.04.5
https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04/
https://github.com/actions/runner-images/issues/6399
We have pinned python 3.6.13 and 3.8.10 in our workflows. There are NO 3.6.* versions available on ubuntu 22.04 in GHA. The oldest 3.8 version available is 3.8.12 on ubuntu 22.04 in GHA. So, we need to use `ubuntu-20.04` instead of `ubuntu-latest` for our workflows at least until we can drop python 3.6 support in CI.

pin GHA runners to ubuntu-20.04

---

CHANGELOG.rst
contrib/core/tests/BUILD
contrib/packs/tests/BUILD
contrib/runners/orquesta_runner/tests/unit/BUILD
st2auth/tests/unit/BUILD
st2auth/tests/unit/controllers/v1/BUILD
st2client/tests/unit/BUILD
st2common/tests/unit/BUILD

Pants uses dependency inference, which the [docs](https://www.pantsbuild.org/docs/how-does-pants-work#dependency-inference) describe as:
> Pants analyzes your code's import statements to determine files' dependencies automatically. Dependency information is required for precise change detection and cache invalidation, but inference means that you don't need to declare dependencies manually (and hermetic …

pants: disambiguate test file dependencies

---

CHANGELOG.rst
contrib/examples/BUILD
lockfiles/st2.lock

In #5733, I configured pants to ignore several requirements files, including `contrib/examples/requirements.txt`:
https://github.com/StackStorm/st2/blob/f25df1f939ef894f87d4bb064ccaadd25c0bd321/pants.toml#L28-L29
One of the reasons I excluded that file, beyond what I described in #5733, was because it includes `requests` which is already included in the main requirements files: …

pants: register requirements for contrib/examples pack

---

CHANGELOG.rst
pylint_plugins/BUILD
pylint_plugins/api_models_test.py
pylint_plugins/fixtures/BUILD
pylint_plugins/fixtures/api_models.py
st2common/st2common/models/api/action.py
st2common/st2common/models/api/base.py
st2common/st2common/models/api/notification.py
st2common/st2common/models/api/trigger.py

In #5848, I will add a GHA workflow to run some tests via pants, starting with tests in `pylint_plugins/`. But, the current tests in pylint_plugins import from `st2common` because that was a quick way to throw together the tests. This is a problem because `pylint_plugins/` and `st2*` each use different resolves (and therefore separate lockfiles). That means that pants puts together the sandbox for running the …

use a fixture for pylint_plugins test

---

CHANGELOG.rst
Makefile
lockfiles/bandit.lock
lockfiles/flake8.lock
lockfiles/pants-plugins.lock
lockfiles/pytest.lock
lockfiles/twine.lock
pants-plugins/BUILD

This is a follow-up for #5842 which configured pants to find plugins in `pants-plugins/`.
This PR consists of 4 updates:
- Now that I'm writing tests, I need to enable installing the pants `testutils`.
- Finish configuring `interpreter_constraints` for `pants-plugins/`. I didn't realize that we had to configure this in both `pants.toml` (which I did in #5842) and in `pants-plugins/BUILD` (which this PR adds).
- …

Update metadata+lockfiles to support testing pants-plugins/

---

OWNERS.md

I'd like to highlight the open-source contributions made by Mark Mercado @mamercad.
Mark is leading the StackStorm adoption at @DigitalOcean ([Add DigitalOcean as an adopter #5836](https://github.com/StackStorm/st2/pull/5836)) and was helping a lot with fixing and improving the broken things here and there.
- https://github.com/StackStorm/ansible-st2/pull/319
- https://github.com/StackStorm/ansible-st2/pull/317
- https://github.com/StackStorm/ansible-st2/pull/307
- https://github.com/StackStorm/ansible-st2/pull/323
- https://github.com/StackStorm/ansible-st2/pull/327
- https://github.com/StackStorm/ansible-st2/pull/325
- https://github.com/StackStorm/ansible-st2/pull/326
@mamercad is adding StackStorm via `ansible-st2` to [1-click …

Add Mark Mercado (@mamercad) to the StackStorm Contributors

---

.github/workflows/lint.yaml
.github/workflows/pants.yaml
.github/workflows/test.yaml
CHANGELOG.rst

This adds a `Test` GHA workflow that uses pants to run tests. Our test suite does not support running via pytest (which is what pants uses), so this workflow only runs tests on `pylint_plugins/` and `pants-plugins/`. We can slowly expand this as we get more of our tests runnable under pytest.
The reason I'm doing this now: I want to add tests for plugins that will go in `pants-plugins/`, and I want to use pants …

GHA workflow to run (some) tests via pantsbuild

---

CHANGELOG.rst
contrib/schemas/BUILD
pants-plugins/README.md
pants-plugins/schemas/BUILD
pants-plugins/schemas/register.py
pants-plugins/schemas/rules.py
pants-plugins/schemas/rules_test.py
pants-plugins/schemas/target_types.py
pants.toml

This PR improves the DX (developer experience) by wiring up the `fmt` and `lint` goals to generate `contrib/schemas/*.json` if needed (or for lint, warn that it needs to be done).
This includes creating a `schemas` plugin for pants that adds a `schemas` target.
Today, if someone changes one of the files used to generate the schemas in `contrib/schemas`, they will probably forget to run the Makefile target the …

Add `pants-plugins/schemas` to streamline regenerating `contrib/schemas`

---

CHANGELOG.rst
st2common/st2common/conf/BUILD
st2common/st2common/conf/__init__.py
st2common/st2common/constants/BUILD

This is primarily a follow-up to:
- #5846
Unlike the simple BUILD config added in #5846, this PR refactors one constant so that pants can better use python imports to precisely detect who needs `st2common/st2common/conf/base.logging.conf`.
Before this PR, anything that uses any of the constants had a hard-coded dependency on `base.logging.conf`:
https://github.com/StackStorm/st2/blob/63f66b9595bf5b4e3974e7c5f327f …

Refactor `DEFAULT_LOGGING_CONF_PATH` calculation to allow fine-grained pants dep inference

---

CHANGELOG.rst
Makefile
pants-plugins/README.md
pants-plugins/api_spec/BUILD
pants-plugins/api_spec/register.py
pants-plugins/api_spec/rules.py
pants-plugins/api_spec/rules_test.py
pants-plugins/api_spec/target_types.py
pants.toml
st2common/st2common/BUILD
st2common/st2common/cmd/generate_api_spec.py
st2common/st2common/openapi.yaml

This PR improves the DX (developer experience) by wiring up:
- the `fmt` goal to generate `st2common/st2common/openapi.yaml` if needed (effectively runs `st2-generate-api-spec`), and
- the `lint` goal to validate `st2common/st2common/openapi.yaml` to make sure the generated schema is valid (effectively runs `st2-validate-api-spec`)
This includes creating a `api_spec` plugin for pants that adds a `api_spec` …

Add `pants-plugins/api_spec` to streamline regenerating `openapi.yaml`

---

BUILD
CHANGELOG.rst
conf/BUILD
pants-plugins/README.md
pants-plugins/sample_conf/BUILD
pants-plugins/sample_conf/register.py
pants-plugins/sample_conf/rules.py
pants-plugins/sample_conf/rules_test.py
pants-plugins/sample_conf/target_types.py
pants.toml
tools/BUILD
tools/config_gen.py

This PR improves the DX (developer experience) by wiring up the `fmt` and `lint` goals to generate `conf/st2.conf.sample` if needed (or for lint, warn that it needs to be done).
This includes creating a `sample_conf` plugin for pants that adds a `sample_conf` target.
Today, if someone changes one of the files used to generate `conf/st2.conf.sample`, they will probably forget to run the Makefile target the …

Add `pants-plugins/sample_conf` to streamline regenerating `conf/st2.conf.sample`

---

CHANGELOG.rst
st2common/st2common/util/pack_management.py

Openshift does not allow packs to be cloned to home directory as they are mounted at `/`. Proposing to use a directory `.st2packs` in home directory.

clone packs into user_home/.st2packs directory

---

.github/workflows/test.yaml
CHANGELOG.rst
pants-plugins/uses_services/BUILD
pants-plugins/uses_services/exceptions.py
pants-plugins/uses_services/mongo_rules_test.py
pants-plugins/uses_services/rabbitmq_rules.py
pants-plugins/uses_services/rabbitmq_rules_test.py
pants-plugins/uses_services/scripts/is_rabbitmq_running.py
st2common/tests/unit/BUILD
st2common/tests/unit/services/BUILD

This PR builds on #5864 to further improve the DX (developer experience) by failing as early as possible if the development (or CI) environment does not have the required services.
This PR adds checks for `rabbitmq`, like #5864 added `mongo` checks. I also have draft branch to add [`redis`](https://github.com/StackStorm/st2/tree/pants-plugins-uses_services-redis) checks.
Please see #5864 for a more detailed …

Update `pants-plugins/uses_services` to support checking for rabbitmq

---

.github/workflows/test.yaml
CHANGELOG.rst
contrib/runners/orquesta_runner/tests/integration/BUILD
pants-plugins/uses_services/BUILD
pants-plugins/uses_services/redis_rules.py
pants-plugins/uses_services/redis_rules_test.py
pants-plugins/uses_services/scripts/is_redis_running.py
st2tests/integration/orquesta/BUILD

This PR builds on #5864 and #5884 to further improve the DX (developer experience) by failing as early as possible if the development (or CI) environment does not have the required services.
This PR adds checks for `redis`, like #5864 added `mongo` checks and #5884 added `rabbitmq` checks.
Please see #5864 for a more detailed description of `pants-plugins/uses_services`. …

Update `pants-plugins/uses_services` to support checking for redis

---

CHANGELOG.rst
pants-plugins/BUILD
pants-plugins/README.md
pants-plugins/macros.py
pants.toml
st2actions/bin/BUILD
st2common/bin/BUILD
st2tests/st2tests/fixtures/generic/BUILD
st2tests/st2tests/fixtures/generic/actions/BUILD
st2tests/st2tests/fixtures/packs/BUILD

This PR adds our first pants macro: `st2_shell_sources_and_resources()`
I'm planning to add 3 more macros to help with building our `python_distribution` targets (for buildling wheels) in future PRs. This just introduces the concept of macros.
> Macros are useful to reduce boilerplate in BUILD files.
> ...
> Macros are defined in Python files that act like a normal BUILD file. They have access to all the symbols …

pants: Add `st2_shell_sources_and_resources()` macro to `pants-plugins/macros.py`

---

CHANGELOG.rst
pants-plugins/uses_services/mongo_rules_test.py
pants-plugins/uses_services/register.py

2 quick fixes for issues I noticed with the pants-plugins:
1. Shorten the timeout for `pants-plugins/uses_services` mongo tests where we expect the check to fail so that the tests go faster.
2. I forgot to register the rabbitmq and redis rules in `pants-plugins/uses_services` added in #5884 and #5893.

Pants: Misc `pants-plugins/uses_services` improvements

---

BUILD
CHANGELOG.rst
pants-plugins/macros.py

This PR adds pants macros that reduce boilerplate around defining `python_distribution()`:
- `st2_license()`
- `st2_component_python_distribution()`
- `st2_runner_python_distribution()`
The next PR will actually add those macros to the relevant BUILD files.
See #5890 for a description of pants macros and what is involved in using them in pants.
We need to add a LICENSE file to all of our wheels. When building …

pants: Add `st2_*_python_distribution()` macros to `pants-plugins/macros.py`

---

CHANGELOG.rst
st2common/st2common/runners/base.py

This is a minor feature request to expose the runner parameter 'debug' to all StackStorm actions as an environment variable. Feature request was discussed briefly in Slack.
This feature request allows the runner parameter 'debug' to be passed as an environment variable named ST2_ACTION_DEBUG to all st2 actions.

expose action parameter debug to all actions

---

CHANGELOG.rst
lockfiles/pants-plugins.lock
pants-plugins/api_spec/rules.py
pants-plugins/api_spec/rules_test.py
pants-plugins/api_spec/subsystem.py
pants-plugins/sample_conf/rules.py
pants-plugins/sample_conf/rules_test.py
pants-plugins/sample_conf/subsystem.py
pants-plugins/schemas/rules.py
pants-plugins/schemas/rules_test.py
pants-plugins/schemas/subsystem.py
pants.toml

This updates to pants to `2.15.0` which requires:
- regen the pants-plugins lockfile
- several changes to our `fmt` and `lint` plugins in pants-plugins.
The required plugin updates are described in the pants [Plugin upgrade guide](https://www.pantsbuild.org/v2.15/docs/plugin-upgrade-guide).
Here are some links to learn more about pants v2.15:
- https://blog.pantsbuild.org/pants-2-15/
- …

Upgrade pants from 2.14 to 2.15

---

CHANGELOG.rst
contrib/runners/orquesta_runner/tests/unit/BUILD
st2client/tests/BUILD
st2common/tests/unit/BUILD
st2tests/integration/orquesta/BUILD

This replaces a 4 `python_sources` targets with `python_test_utils`. I excluded the `test_*.py` files in `tests/unit` directories since those are already covered by `python_tests` targets. I didn't bother to add that exclude in `st2client/tests/BUILD` however, because we keep our actual tests under `tests/unit` or `tests/integration` not directly under `tests/`.
Generally, `python_test_utils` captures things …

Pants: reclassify test utils in BUILD metadata

---

CHANGELOG.rst
lockfiles/st2.lock
st2actions/conf/BUILD
st2client/BUILD
st2common/st2common/util/BUILD
st2common/st2common/util/concurrency.py
st2common/st2common/util/monkey_patch.py
tools/BUILD
tools/st2-analyze-links.py
tools/visualize_action_chain.py

I noticed a few deps that were not accounted for, so I added them to the BUILD metadata and regenerated the lockfile.
This re-introduces the `pysocks` dep to st2client so that the pants BUILD metadata also has the change introduced in:
- #5469
These deps are for tools that will never end up in a wheel, so pants will only ever use these if it has to run these tools for some reason:
- `pika` is used by …

Pants: add some missing external dependencies

---

CHANGELOG.rst
pants.toml
st2actions/BUILD
st2api/st2api/BUILD
st2api/st2api/controllers/BUILD
st2auth/st2auth/BUILD
st2auth/st2auth/backends/BUILD
st2reactor/st2reactor/container/BUILD
st2stream/st2stream/BUILD

Like #5925, which adds dependencies for the `python_distribution` for `st2common`, this PR adds the remaining dependencies for the other `st2*` component `python_distribution` targets. It also skips `st2tests` which requires quite a few more changes in #5929.
It also adds a note to `pants.toml` to make it clear that pants will generate a `setup.py` file for us.
- [Building …

Pants: add dependencies to the st2* `python_distributions` (except st2common/st2tests)

---

CHANGELOG.rst
st2actions/tests/unit/test_actions_registrar.py
st2common/tests/unit/BUILD
st2tests/BUILD
st2tests/st2tests/BUILD
st2tests/st2tests/fixtures/generic/fixture.py
st2tests/st2tests/fixtures/localrunner_pack/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_1/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_1/etc/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_2/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_3/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_7/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_9/BUILD
st2tests/st2tests/fixtures/packs/dummy_pack_9/actions/invalid_syntax.py
st2tests/st2tests/fixtures/packs/orquesta_tests/BUILD
st2tests/st2tests/fixtures/packs/pack_invalid_requirements/BUILD
st2tests/st2tests/fixtures/packs/runners/BUILD
st2tests/st2tests/fixtures/packs/runners/test_async_runner/BUILD
st2tests/st2tests/fixtures/packs/runners/test_polling_async_runner/BUILD
st2tests/st2tests/fixtures/packs/test_library_dependencies/BUILD
st2tests/st2tests/fixtures/specs/BUILD
st2tests/st2tests/fixtures/ssl_certs/BUILD
st2tests/st2tests/policies/meta/BUILD

Like #5925, which adds dependencies for the `python_distribution` for `st2common`, this PR adds the remaining dependencies for the `st2tests` component `python_distribution` targets. The remaining distributions deps are covered by #5928.
Thanks to the nature of `st2tests` the changes vary quite a bit between the BUILD files (ie each fixture is slightly different, so its deps are also a bit different). Also, …

Pants: add dependencies to the st2tests `python_distributions`

---

CHANGELOG.rst
contrib/runners/python_runner/tests/unit/test_pythonrunner.py
pants.toml
st2common/st2common/constants/pack.py
st2common/st2common/util/pack.py
st2common/st2common/util/sandboxing.py

I ran into an issue with dependency inference not understanding the "lib" directories. ST2 adds `<pack>/lib` to PYTHONPATH for both actions and sensors, and `<pack>/actions/lib` to PYTHONPATH for actions. Pants uses "source roots" to manage the PYTHONPATH, so we need a way for pants to detect those source roots when needed. So, I adjusted the `[source].root_patterns` setting in `pants.toml` to account for these …

Add pants source roots and a constant for pack common lib directory

---

CHANGELOG.rst
fixed-requirements.txt
lockfiles/bandit.lock
lockfiles/black.lock
lockfiles/pants-plugins.lock
lockfiles/st2.lock
lockfiles/twine.lock
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt

Current CI builds are failing when performing the st2client_install_check, see https://github.com/StackStorm/st2/actions/runs/5897223026/job/15996511713
Changes from when it first failed were zipp version got incremented, and that is where error is.
Fixed zipp version in requirements used by st2client and re-generated requirements.txt files and pants lock files.
Ran make .st2client_install_check manually to ensure that it now passes and pulls in a valid zipp version.

Fix zipp version to fix ST2 CI issues.

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/requirements.txt

Paramiko 2.10.1 is effect by:
https://github.com/paramiko/paramiko/issues/2017
That break cert-based SSH auth when using Paramiko, both are fixed in 2.10.5
This PR bumps Paramiko to 2.10.5 to fix this issue

Fix Cert-based SSH Auth Issues in Paramiko

---

CHANGELOG.rst
st2common/st2common/router.py

fix(st2common/router): don't log sensitive information

---

.circleci/config.yml

CircleCI started to fail on `deploy` step (https://app.circleci.com/pipelines/github/StackStorm/st2/4125/workflows/d62a5fd6-42c3-484f-acf7-5ba525ee22b9/jobs/15902)
with the following error:
```
ERROR:  Error installing package_cloud:
The last version of thor (~> 1.2) to support your Ruby & RubyGems was 1.2.2. Try installing it with `gem install thor -v 1.2.2` and then running the current command again
thor requires Ruby version >= 2.6.0. The current ruby version is 2.4.10.364.
```
Sync CircleCI config with `st2web` (https://github.com/StackStorm/st2web/blob/ba85bf2a495056ba4e1e22b8727a84baf4493c48/.circleci/config.yml#L153 config) with `ruby:2.6` where deployment worked OK.

CI: Update ruby 2.4 -> 2.6 to fix CircleCI Packagecloud deploy step

---

.github/workflows/orquesta-integration-tests.yaml
CHANGELOG.rst
scripts/ci/submit-codecov-coverage.sh

I forgot these changes in the last PR, and it was pointed out here:
https://github.com/StackStorm/st2/pull/6036#issuecomment-1775662190
Thanks for the patience

Fix Orquesta Integration Test Codecov Upload

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/requirements.txt
st2api/requirements.txt
st2auth/requirements.txt
st2common/requirements.txt
st2reactor/requirements.txt
st2stream/requirements.txt
test-requirements.txt

While writing a sensor for st2 - we hit this error:
```
stackstorm-docker-compose-st2sensorcontainer-1  | 2023-10-24 14:23:28,648 WARNING [-] Sensor "PollPagerDuty" run method raised an exception: maximum recursion depth exceeded while calling a Python object.
stackstorm-docker-compose-st2sensorcontainer-1  | Traceback (most recent call last):
stackstorm-docker-compose-st2sensorcontainer-1  |   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2reactor/container/sensor_wrapper.py", line 285, in run
stackstorm-docker-compose-st2sensorcontainer-1  |     self._sensor_instance.run()
stackstorm-docker-compose-st2sensorcontainer-1  |   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2reactor/sensor/base.py", line 121, in run
stackstorm-docker-compose-st2sensorcontainer-1  | …
```

Bump eventlet to fix setting SSLContext minimum_version property that results in RecursionErrors

---

CHANGELOG.rst
st2auth/st2auth/handlers.py
st2auth/tests/unit/test_handlers.py

Adding on to work in #6041 that fixed proxy auth mode for users connecting via st2web, it appears that the `st2` client (`st2client` container in the HA helm chart) connects directly to `st2auth` instead of connecting through nginx. As a result it is unable to authenticate with `st2auth` is in proxy mode as headers required for this to work are not present. We see `401 Client Error: Unauthorized` in this scenario. The `st2` client does however use basic auth and we can extract the username from that in this scenario to resolve the issue.
This change modifies the proxy auth handler to use the username from the `Authorization` header only in the case where proxy auth mode is enabled and when `remote_user` is not passed to the proxy auth handler function.

Fix st2 cli client auth in st2auth proxy mode

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
fixed-requirements.txt
requirements-pants.txt
requirements.txt
scripts/fixate-requirements.py
st2common/in-requirements.txt
st2common/requirements.txt

Update Orquesta to v1.6.0 to be included in the next st2 release.
Orquesta v1.6.0 comes with some updated dependencies.

Update Orquesta to v1.6.0

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2actions/requirements.txt
st2common/requirements.txt

Taking one dependency at a time into a separated PRs from https://github.com/StackStorm/st2/pull/6062 to see what could be merged safely ASAP.
This updates `gitpython==3.1.37` (security fixed) under py3.8 and `gitpython==3.1.18` (latest installable, but vulnerable) under py3.6
Checking the build artifacts for shipped gitpython versions:
- U18 (py3.6) - `gitpython==3.1.18`  [(build)](https://app.circleci.com/pipelines/github/StackStorm/st2/4214/workflows/b4932a80-0076-40da-8ab8-393998fbcf6f/jobs/16002?invite=true#step-109-835718_90)
- U20 (py3.8) - `gitpython==3.1.37` ([build](https://app.circleci.com/pipelines/github/StackStorm/st2/4214/workflows/b4932a80-0076-40da-8ab8-393998fbcf6f/jobs/16002/parallel-runs/1?filterBy=ALL&invite=true#step-109-834745_90))
- EL7 (py3.6) - …

Update gitpython (security)

---

CHANGELOG.rst
contrib/examples/sensors/echo_flask_app.py

Snyk Code Analytics High Finding in examples ‎contrib/examples/sensors/echo_flask_app.py: 
I think that is a low impact Security Finding because it's in the examples. 
https://cwe.mitre.org/data/definitions/79.html

 ‎contrib/examples/sensors/echo_flask_app.py Snyk Finding Cross-site Scripting (XSS)

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2client/requirements.txt

Extract from #6062 by @jk464 changes to update a single `importlib-metadata` dependency in this PR, as the other change related to `requests` in the beforementioned PR fails to build.
This will install importlib-metadata==4.10.1 (security fixed) under py3.8 and importlib-metadata==4.8.3 (latest available, vulnerable) under py3.6.
Address https://github.com/python/importlib_metadata/issues/361 under py3.8.
We should drop py3.6 support ASAP after v3.8.1 patch release.

Update importlib-metadata (security)

---

CHANGELOG.rst
contrib/runners/local_runner/local_runner/base.py

Fixes #5591.
For `local-shell-script` runners, the runner tries to ensure the `script_action` is executable by running: 
```
if script_action:
script_local_path_abs = self.entry_point
args = "chmod +x %s ; %s" % (script_local_path_abs, args)
sanitized_args = "chmod +x %s ; %s" % (
script_local_path_abs,
sanitized_args,
)
```
On readonly filesystems, such as when StackStorm is deployed in HA on Kubernetes - this `chmod +x` command fails:
```
stderr: "chmod: changing permissions of '/opt/stackstorm/packs/ansible/actions/ansible.py': Read-only file system
```
(Note since this command isn't `&&` with the actual action, that still runs fine - there's just an error logged in the action output)
This is fixed, by only running this block if the filesystem is read-writeable - by adding the …

For "local-shell-script" runner, on readonly filesystems, don't attempt to run chmod +x on script_action.

---

lockfiles/st2.lock

Update pants.lock following the StackStorm/st2-auth-ldap#111 update. This should fix CI failing:
https://github.com/StackStorm/st2/actions/runs/7168518561/job/19516889545?pr=6091#step:5:169

Update st2-auth-ldap sha in pants lock to fix CI

---

OWNERS.md

We were amazed by @mamercad code contributions during the last year when he while leading the StackStorm adoption at @DigitalOcean created ~20 (!) Pull Requests, improving many repositories and CI/CD processes. See 👉 [Add Mark Mercado (@mamercad) to the StackStorm Contributors #5852](https://github.com/StackStorm/st2/pull/5852).
There was more development since that, refactoring, fixing things and working towards the project needs. Some of that work landed in the `v3.8.1` release and will be useful for the `v3.9.0`:
- https://github.com/StackStorm/st2packaging-dockerfiles/pull/111
- https://github.com/StackStorm/st2packaging-dockerfiles/pull/112
- https://github.com/StackStorm/st2/pull/5851
- https://github.com/StackStorm/stackstorm-k8s/pull/358
- …

TSC: Promote Mark Mercado (@mamercad) from Contributors to Maintainers

---

OWNERS.md

Sravanthi is doing StackStorm automation at @Salesforce and they started helping StackStorm opensource. Just added multiple Python versions support matrix for StackStorm Exchange, removing python3.6 so all the packs are tested under `py3.8` and `py3.9` now which will help with the upcoming `v3.9.0` release:
- https://github.com/StackStorm-Exchange/ci/pull/145
- https://github.com/StackStorm-Exchange/stackstorm-git/pull/15
and other fixes and discussions:
- https://github.com/StackStorm/st2/pull/5536 closing https://github.com/StackStorm/st2/issues/5525
I hope it's just a beginning and looking forward to see more ongoing involvement from @sravs-dev and the group in  [StackStorm development and maintenance](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-to-become-a-maintaine …

Add Sravanthi Konduru(sravs-dev) to the Contributors

---

OWNERS.md

I'd like to highlight contributions made by Scott (@jk464). They were especially very helpful in the context of `v3.8.1` patch release and fixed lots of security issues:
- https://github.com/StackStorm/st2/pull/6061
- https://github.com/StackStorm/st2/pull/6062
- https://github.com/StackStorm/st2/pull/5994
- https://github.com/StackStorm/st2/pull/5963
- https://github.com/StackStorm/st2/pull/6073
- https://github.com/StackStorm/st2/pull/6017
He's also part of the community, participating in the TSC meetings, Slack and Github discussions and I'm looking forward to see @jk464 more helping with the [StackStorm core maintenance](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-to-become-a-maintainer), security and become part of the TSC.

Add Scott Swann (jk464) to Contributors

---

OWNERS.md

David Culbreth (@AndroxxTraxxon) is automating all the things at HEB and he helped StackStorm a lot with the `v3.8.1` patch release fixing broken stuff and his PRs will be useful for the upcoming `v3.9.0` that'll deal with the different Python versions in both orquesta and st2 core.
- https://github.com/StackStorm/orquesta/pull/253 (mega-PR)
- Update deprecated `collections` imports to `collections.abc` to be forward-compatible with Python3.10
- Migrate from `nosetest` to `pytest` for Python test runner
- Add Python versions 3.9, 3.10, and 3.11 to the test matrix
- https://github.com/StackStorm/st2/pull/5992 - helps supporting future python versions
- https://github.com/StackStorm/stackstorm.com/issues/20
- https://github.com/StackStorm/st2/discussions/5964
- …

Add David Culbreth (AndroxxTraxxon) to Contributors

---

OWNERS.md

Carlos (@nzlosh) is a StackStorm maintainer for years, was a release assistant for `v3.7.0`, fully led a `v3.8.0` and now helping with the `v3.8.1` patch release. In a meantime, he already participates in coordinating needs for the future `v3.9.0` release like Python deprecation and adding new versions and initiatives to support the different OS flavors.
- https://github.com/StackStorm/community/issues/110
- https://github.com/StackStorm/community/issues/68
- https://github.com/StackStorm/st2-packages/pull/700
- coordinating and implementing complex multi-step/multi-level projects
- https://github.com/StackStorm/community/issues/124
- https://github.com/StackStorm/community/issues/126
- https://github.com/StackStorm/st2/pull/6022
- [**StackStorm v3.9.0 Project …

Promote Carlos (@nzlosh) to Senior Maintainers

---

.circleci/config.yml
.github/workflows/ci.yaml
.github/workflows/orquesta-integration-tests.yaml
CHANGELOG.rst
contrib/linux/tests/test_action_dig.py
contrib/packs/tests/test_action_download.py
contrib/packs/tests/test_action_unload.py

Restore Pack integration testing (it was inadvertently skipped) and stop testing against `bionic` and `el7`.
Fixes #6135.

Restore Pack integration testing

---

CHANGELOG.rst
lockfiles/st2.lock
pants.toml
requirements-pants.txt

With this change, you can run `pants export --resolve=st2` to get a venv under `dist/export/python/virtualenvs/st2/<python version>`. The venv includes:
- editable installs of all of our st2* (st2api, st2auth, ...) and runners
- everything in `lockfiles/st2.lock`:
- `nose` so that you can run the tests.
- versions of `pymongo` and `mongoengine` that is compatible with our code
- **All unit tests pass with this**
Pex (used by pants) will create the venv with the first interpreter on the path that matches the interpreter_constraints in pants.toml. If you want to generate a venv with a particular python binary use this:
```
pants export --resolve=st2 --python-bootstrap-search-path=[] --python-bootstrap-search-path=/usr/bin/python3.9
```
_Replace `/usr/bin/python3.9` with the interpreter you …

Pantsbuild: Make exported venv useful for running nose

---

lockfiles/st2.lock

My Github Actions stopped working when debugging the amqp issue due to an outdated hash for the st2-auth-ldap in the st2.lock file used by pants. So I ran `pants generate-lockfiles --resolve=st2` and this is the result. Now the Github Actions passes the requirements setup and we're back to the amqp issue. 
Hope this makes your life a bit easier and saves you some time. :)

update pants st2.lock file

---

CHANGELOG.rst
lint-configs/regex-lint.yaml
lockfiles/bandit.lock
lockfiles/black.lock
lockfiles/flake8.lock
lockfiles/pants-plugins.lock
lockfiles/pylint.lock
lockfiles/pytest.lock
lockfiles/st2.lock
lockfiles/twine.lock
pants-plugins/README.md
pants.toml

Updating to pants 2.18 needed to wait for these which were released as part of 2.18.3:
- https://github.com/pantsbuild/pants/pull/20472 
- https://github.com/pantsbuild/pants/pull/20477
There is a new rust-based parser for python dependency inference, but in 2.18.2 it was spewing some confusing and inaccurate warnings with our code base. https://github.com/pantsbuild/pants/pull/20472 resolved those issues. We need to switch to the rust parser when we move to 2.18 or we risk a bigger transition with the move to 2.19, when the old python parser gets removed.
Now that those are merged, we get to use that new parser, and it feels much faster.

Upgrade Pantsbuild to 2.18

---

Makefile

- Do more of the tests before quitting
- drop duplicate test runs from Makefile
We already run nosetest so it doesn't stop on failure. But we run nosetest in a loop, and the loop exits on the first failure. So, CI is not providing a complete set of failures right now.
Fix this by delaying exit with failure till all components have been tested.
Also, stop running runner integration tests twice. Looping over `COMPONENTS_RUNNERS` is not helpful because runners are already included in `COMPONENTS_TEST` which is done first. Drop these duplicate trst runs to save CI time.

Improve testing logic in Makefile

---

.github/workflows/checks.yaml
.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/microbenchmarks.yaml
.github/workflows/orquesta-integration-tests.yaml
.github/workflows/pants.yaml
.github/workflows/test.yaml

- Revert "bump py 3.8.10->3.8.18 to workaround GHA failure"
- bump gha setup-python action to v5
- bump gha checkout action to v4
- bump gha cache action to v4
- bump gha upload-artifact action to v4
- bump gha pantsbuild/actions/init-pants action to v8
- GHA: bust python caches and account for full venv lock
- GHA: bust apt caches

Bump GHA actions

---

contrib/examples/actions/ubuntu_pkg_info/ubuntu_pkg_info.py
contrib/packs/actions/pack_mgmt/get_pack_dependencies.py
lint-configs/python/.pylintrc
lockfiles/pylint.lock
pylint_plugins/BUILD
pylint_plugins/api_models.py
pylint_plugins/api_models_test.py
pylint_plugins/db_models.py
pyproject.toml
st2actions/st2actions/container/base.py
st2common/bin/migrations/v3.5/st2-migrate-db-dict-field-values
st2common/st2common/services/action.py
test-requirements.txt

This extracts @nzlosh's pylint-related updates/fixes from #6157.
- update pylint
- Test: Bump pylint and astroid to latest 2.x
- Remove options to fix pylint Unknown option value warning.
- Fix Useless option value for W0142, W0232 and R0201
- Fix E0601: Using variable 'result' before assignment (used-before-assignment)
- fmt
- Fix E721 do not compare types
- Initialise variables to avoid E0601: Use before assignment.
- Bump pylint and astroid to support latest dnspython.
- Update pylint calls for support 3.1
- Fix E0601: used-before-assign lint errors.
- Disable false alert on import error.

Update pylint to 3.1.0

---

CHANGELOG.rst
st2actions/st2actions/policies/concurrency_by_attr.py
st2actions/st2actions/scheduler/handler.py
st2api/st2api/controllers/v1/triggers.py
st2client/st2client/base.py
st2client/st2client/config_parser.py
st2client/st2client/formatters/execution.py
st2client/st2client/shell.py
st2client/tests/unit/test_config_parser.py
st2client/tests/unit/test_shell.py
st2common/st2common/constants/meta.py
st2common/st2common/expressions/functions/version.py
st2common/st2common/logging/misc.py
st2common/st2common/persistence/db_init.py
st2common/st2common/services/coordination.py
st2common/st2common/services/trigger_dispatcher.py
st2common/st2common/util/api.py
st2common/st2common/util/loader.py
st2common/st2common/util/versioning.py
st2reactor/st2reactor/container/sensor_wrapper.py

This extracts @nzlosh's DeprecationWarning fixes from #6157. 
- Fix for DeprecationWarning: the imp module is deprecated in favour of importlib
- Fix for DeprecationWarning: This method will be removed in Python 3.12. Use 'parser.read_file()' instead.
- Fix semver DeprecationWarning: Function semver.match is deprecated and other semver warnings
- Fix semver patch strip function and replace deprecated self.assertItemsEqual with assert.
- Fix DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
- Fixed more DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
- Replace 'warn' with 'warning' method
- Skip test_warn_on_bad_config_permissions when run as root user.
- Skip test_get_cached_auth_token_invalid_permissions if run as root
- Skip …

Fix misc DeprecationWarnings

---

CHANGELOG.rst
fixed-requirements.txt
lockfiles/st2.lock
requirements-pants.txt
requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt
st2client/st2client/commands/pack.py
st2client/st2client/utils/interactive.py
st2common/requirements.txt
test-requirements.txt

This extracts @nzlosh's st2client requirements updates from #6157.
- Bump prompt-toolkit to 3.0.43 for py3.10 support
- Switch python-editor to editor for py3.10 support.
- Use pygment token in place of prompt_toolkit
- update pants requirements to align with fixed requirements
- Remove editor.EditorError since editor defaults to output redirection when binary not found.
- Update pygment to be included in st2client
- dependency tweak
- Update pygment pinning to avoid version conflicts in st2client.
- alphabetize requirements-pants.txt
- add changelog entry
- regenerate lockfiles/st2.lock

Update st2client deps: editor and prompt-toolkit

---

.github/workflows/orquesta-integration-tests.yaml
CHANGELOG.rst
fixed-requirements.txt
lockfiles/st2.lock
requirements-pants.txt
requirements.txt
st2actions/requirements.txt
st2api/requirements.txt
st2api/tests/unit/test_validation_utils.py
st2auth/requirements.txt
st2common/requirements.txt
st2common/st2common/config.py
st2reactor/requirements.txt
st2stream/requirements.txt
st2tests/st2tests/config.py
tools/config_gen.py

This extracts the `oslo.config` commits by @nzlosh from #6157.
- Bump oslo.config version for py3.10 support
- Fix ssl_cert_reqs choices and update data type of newer version of oslo.config
- Adjust expected msg in test for oslo.config update
- Black formatting
- Relax pants requirements for oslo.config
- Adjust comment in fixed-requirements.txt
- bump fixed-requirements.txt to match lockfiles/st2.lock
Lockfile diff:
```
Lockfile diff: lockfiles/st2.lock [st2]
==                    Upgraded dependencies                     ==
filelock                       3.13.4       -->   3.14.0
oslo-config                    1.12.1       -->   9.4.0
pytest                         8.1.1        -->   8.2.0
virtualenv                     20.26.0      -->   20.26.1
==                      Added …
```

Update `oslo.config` to prepare for python 3.10 support.

---

Makefile

When I attempt to run the `Makefile` locally on my M1 MacBook (unsure if that's related) I hit this error:
```
================== INSTALL RUNNERS ====================
echo -e "contrib/runners/action_chain_runner contrib/runners/announcement_runner contrib/runners/http_runner contrib/runners/inquirer_runner contrib/runners/local_runner contrib/runners/noop_runner contrib/runners/orquesta_runner contrib/runners/python_runner contrib/runners/remote_runner contrib/runners/winrm_runner" | tr -d "\n" | xargs -P 8 -d " " -n1 -i sh -c ". virtualenv-osx/bin/activate; cd {} ; python setup.py develop --no-deps"
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
sh: line 0: cd: contrib/runners/action_chain_runner: No such file or …
```

Fix issue with cd'ing in Makefile

---

CHANGELOG.rst
fixed-requirements.txt
requirements.txt
st2common/requirements.txt

Bump `tooz` to version `6.2.0` this contains the fix https://github.com/openstack/tooz/commit/d09659ed5b20298234ddc7c1ed75721725dade29 (https://github.com/openstack/tooz/compare/6.1.0...6.2.0) which fixes TLS on Redis Sentinel (which was broken in `6.1.0`)

Bump tooz to 6.2.0

---

st2common/st2common/content/bootstrap.py
st2common/st2common/util/monkey_patch.py
tools/launchdev.sh

While debugging some GHA instability, I found 3 minor things to improve or cleanup: 
- clean up tmux usage in `tools/launchdev.sh`
- Make sure eventlet patching happens early when running st2-register-content
- drop eventlet bug workaround as the bug was fixed upstream several releases ago.

Misc CI improvements/fixes

---

.gitignore
contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
st2api/tests/unit/controllers/v1/test_service_registry.py
st2client/tests/unit/test_commands.py
st2client/tests/unit/test_inquiry.py
st2common/st2common/services/coordination.py
st2common/st2common/transport/publishers.py
st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_error.yaml

This extracts several test changes and typo fixes by @nzlosh and @guzzijones from #6236.
I tried to preserve the history of changes and authorship, but with each change in a separate commit. So, it's probably best to review each commit.

test changes from #6236

---

.gitattributes
CHANGELOG.rst
contrib/chatops/tests/BUILD
contrib/core/tests/BUILD
contrib/examples/tests/BUILD
contrib/linux/tests/BUILD
contrib/packs/tests/BUILD
lockfiles/pants-plugins.lock
pants.toml
st2common/tests/unit/test_dist_utils.py

This updates from pants 2.22 to 2.23. The stable version of 2.23 has not been released yet, but with so many features that we need, it's worth using an alpha to unblock other developments.
I also added a `.gitattributes` file to try and improve the UX of fixing lockfile merge conflicts.
I also included 2 minor commits extracted from #6202:
- pants is already configured to ignore `dist_utils.py`, so also ignore `test_dist_utils.py`: 423472495f702f7c19a328dd62b35b0c42ac3a39
- Add `tags=["pack"]` to all of the pack tests so that we can easily run just the pack tests via pants: 77ee17c03accc48cc8d0d0cc28420945772f914f
Follow-up PRs will allow us to run all of the pack and unit tests via pants + pytest.
- https://github.com/pantsbuild/pants/blob/main/docs/notes/2.23.x.md
- …

Pants upgrade from 2.22.0 to 2.23.0a0

---

.github/workflows/test.yaml
CHANGELOG.rst
contrib/runners/orquesta_runner/tests/unit/test_basic.py
contrib/runners/orquesta_runner/tests/unit/test_context.py
contrib/runners/orquesta_runner/tests/unit/test_error_handling.py
pants.toml
st2actions/tests/unit/test_runner_container.py
st2api/tests/unit/controllers/v1/test_alias_execution.py
st2api/tests/unit/controllers/v1/test_auth.py
st2api/tests/unit/controllers/v1/test_executions.py
st2tests/st2tests/config.py

Adds a new env var for tests: `ST2TESTS_SYSTEM_USER`. When set, this will override `system_user.user` in st2 conf so that you can run tests on systems that do not have the `stanley` user. When running tests locally, use the following to set system user to the current user:
```
export ST2TESTS_SYSTEM_USER=$(id -un)
```
This follows the naming convention for test vars introduced in #5707 which introduced `ST2TESTS_PARALLEL_SLOT`.
These commits were extracted from my wip work in https://github.com/StackStorm/st2/pull/6202.

Add `ST2TESTS_SYSTEM_USER` env var to set `system_user.user` in tests

---

.github/workflows/ci.yaml
CHANGELOG.rst
Makefile
st2actions/tests/unit/test_policies.py
st2actions/tests/unit/test_worker.py
st2actions/tests/unit/test_workflow_engine.py
st2common/tests/unit/services/test_workflow_service_retries.py
st2common/tests/unit/test_service_setup.py
st2tests/st2tests/config.py

The graceful_shutdown tests have been very flaky using the `NoOpDriver`. Switching from `NoOpDriver` to `RedisDriver` will hopefully make our CI more stable.
This was discussed in a [TSC meeting](https://github.com/StackStorm/community/issues/141) and implemented by @FileMagic (#6223) and @guzzijones (#6236). I cherry-picked the redis-related parts of their excellent work. After stumbling through the cherry-picks (I missed a few things, and had to rebase/cherry-pick a few times), I refactored a few things:
- GHA: use the `redis` container defined in `services`, dropping the tasks that managed it manually.
- use `ST2TESTS_REDIS_*` as the format for new env vars instead of `ST2_OVERRIDE_COORDINATOR_REDIS_*`.
- fix a regression I added in #6241 that only became apparent once we stopped using …

Make unit tests use redis

---

CHANGELOG.rst
contrib/runners/orquesta_runner/tests/unit/BUILD
pants-plugins/uses_services/BUILD
pants-plugins/uses_services/mongo_rules.py
pants-plugins/uses_services/register.py
pants-plugins/uses_services/scripts/has_system_user.py
pants-plugins/uses_services/scripts/is_mongo_running.py
pants-plugins/uses_services/system_user_rules.py
pants-plugins/uses_services/system_user_rules_test.py
pants-plugins/uses_services/target_types.py
st2actions/tests/unit/BUILD
st2api/tests/unit/controllers/v1/BUILD
st2common/tests/unit/BUILD

Some of the tests require the `system_user.user` as an actual local user on the machine running pytest. That is now configurable with the `ST2TESTS_SYSTEM_USER` env var added in #6242. If someone forgot to set--or did not know they could set--the `ST2TESTS_SYSTEM_USER` env var, they will get really odd errors that are difficult to interpret and debug. So, this PR adds a pants-plugin feature to fail with an error message about setting that env var before pytest even runs tests that require the system_user.
This improves on the `pants-plugins/uses_services` plugin, which was added in these PRs (the PR descriptions can be helpful in understanding the `uses_services` plugin):
- #5864
- #5884
- #5893
- #5898
[`has_system_user.py`](https://github.com/StackStorm/st2/pull/6244/files#diff-718b51f3e …

pants: Add `system_user` detection to `pants-plugins/uses_services` (+ `mongo` detection improvements)

---

BUILD
CHANGELOG.rst
pants-plugins/macros.py
st2actions/conf/BUILD
st2api/conf/BUILD
st2auth/conf/BUILD
st2reactor/conf/BUILD
st2stream/conf/BUILD
st2tests/conf/BUILD
st2tests/st2tests/fixtures/conf/BUILD

This PR has commits cherry-picked from #6202 
I'm working towards getting pants to run our tests via pytest. While running unit tests, I found that the logging.conf files depend on python code, but pants cannot infer dependencies in conf files.
For example, this logging.conf snippet uses 3 classes from `st2common.logging.formatters`:
https://github.com/StackStorm/st2/blob/b534bf2089502ea865f5da654c16e21f781121e2/st2stream/conf/logging.conf#L32-L44
And this snippet uses `st2common.log.ConfigurableSyslogHandler`:
https://github.com/StackStorm/st2/blob/b534bf2089502ea865f5da654c16e21f781121e2/st2stream/conf/syslog.conf#L14-L18
Recording these dependencies for every conf file would be very repetitive, though, so I added 3 pants macros to simplify defining the dependencies in BUILD metadata:
- …

Pantsbuild: Add BUILD dependencies for logging.conf

---

.github/workflows/ci.yaml
.github/workflows/microbenchmarks.yaml
.github/workflows/orquesta-integration-tests.yaml
.github/workflows/test.yaml
CHANGELOG.rst
Makefile

Switches from Mongo 4.4 to Mongo 7.0 using work by @guzzijones cherry-picked from #6236.
Also updates the redis container definition in the orquesta workflow to be consistent with ci workflow changes added in #6245.

Update from Mongo 4.4 to Mongo 7 in CI

---

CHANGELOG.rst
contrib/core/BUILD
contrib/core/actions/send_mail/BUILD
st2common/tests/unit/services/test_packs.py
st2common/tests/unit/test_db.py
st2common/tests/unit/test_util_file_system.py
st2tests/st2tests/policies/meta/BUILD

This has a couple of commits extracted from #6202 where I'm working on getting all of our unit tests to run under pants+pytest.
1 test relied on `tests_config.parse_args()` happening when nose imported or ran earlier tests (similar to changes in #6241).
For the other test, pants does not copy BUILD files into the sandbox, so we need to completely ignore the BUILD files when they exist (ie when running nosetest or pytest directly instead of letting pants run it in a sandbox).
Plus there are a few file dep changes in BUILD metadata to support these.

Pants: Minor test refactor to support running under pants+pytest

---

.github/workflows/test.yaml
BUILD
BUILD.environment
CHANGELOG.rst
contrib/runners/python_runner/tests/unit/BUILD
pants.toml
st2tests/st2tests/fixtures/packs/BUILD

This PR has commits extracted from #6202 where I'm working on getting all of our unit tests to run under pants+pytest.
This PR focuses on managing the git submodule we use to test pack features, especially the content version selection that relies on `git worktree`. Pants runs processes like pytest in a sandbox, but the `.git` directory does not get copied into the sandbox. Plus, `.git` is generally ignored, so I had to find a way to work around the pants assumptions that ignore `.git` and copy the submodule bits into the sandbox.
This is the target that copies the `.git` directory for the submodule: 
https://github.com/StackStorm/st2/blob/a25bcfd9b7b04405cd6a64f631595a0d4ec024f3/BUILD#L105-L109
This relies on a few pants features, some of which are experimental (which means the interface …

Pants: Add BUILD metadata to handle git submodule

---

CHANGELOG.rst
contrib/runners/python_runner/tests/unit/test_output_schema.py

This was extracted from #6202 where I'm working on getting pants to run our tests with pytest.
The `runner.yaml` symlink is not registered in pants. So far, the test in this PR is the first file I've found that accesses that symlink. So, this PR makes the test just use the actual file instead of the symlink.
I put this commit in it's own PR because it doesn't fit with any of the other changes, and to see if anyone knows of a reason for the `runner.yaml` symlinks. The symlinks seem pointless to me, so I don't want to rely on them. Is there anything else that relies on these symlinks?

Adjust test to use `runner.yaml` file over the symlink

---

CHANGELOG.rst
contrib/runners/winrm_runner/tests/unit/test_winrm_base.py
contrib/runners/winrm_runner/winrm_runner/winrm_base.py

This PR implements a change to the shell initialisation process with pywinrm, utilizing the 65001 codepage, ensuring raw string responses are UTF-8 encoded.
Potential fix for #6034.

Open pywinrm shell sessions with UTF-8 codepage

---

CHANGELOG.rst
Makefile
fixed-requirements.txt
lockfiles/st2-constraints.txt
lockfiles/st2.lock
requirements.txt
st2client/requirements.txt
st2common/requirements.txt
st2tests/requirements.txt

Update `dnspython` to v2.6.1 to fix pack CI failing for py3.10 / py3.11 with `AttributeError: module 'collections' has no attribute 'MutableMapping'`.

Bump dnspython to 2.6.1 to fix pack CI failure on py3.10/py3.11

---

CHANGELOG.rst
contrib/chatops/BUILD
contrib/core/BUILD
contrib/debug/BUILD
contrib/default/BUILD
contrib/examples/BUILD
contrib/examples/actions/pythonactions/isprime.py
contrib/hello_st2/BUILD
contrib/linux/BUILD
contrib/packs/BUILD
pants-plugins/pack_metadata/python_rules/BUILD
pants-plugins/pack_metadata/python_rules/conftest.py
pants-plugins/pack_metadata/python_rules/python_module_mapper.py
pants-plugins/pack_metadata/python_rules/python_module_mapper_test.py
pants-plugins/pack_metadata/python_rules/python_pack_content.py
pants-plugins/pack_metadata/python_rules/python_pack_content_test.py
pants-plugins/pack_metadata/python_rules/python_path_rules.py
pants-plugins/pack_metadata/python_rules/python_path_rules_test.py
pants-plugins/pack_metadata/register.py
pants-plugins/pack_metadata/target_types.py
pants-plugins/uses_services/register.py
pants.toml

This PR has commits extracted from #6202 where I'm working on getting all of our unit tests to run under pants+pytest.
It is best to review each commit of this PR to make the review manageable (I rewrote history to simplify reviews). If this PR is still too large to review, I can try to split it into multiple PRs.
This has pants+pytest run pack tests directly instead of using `st2-run-pack-tests`, which has some issues detailed below.
This enhances `pants-plugins/pack_metadata` (introduced in #5868) so that it can inject the custom `PYTHONPATH` entries that StackStorm adds when running python in packs like actions and sensors. We have several special lib directories to support:
- `<pack>/lib` is the shared lib dir that gets added for both actions and sensors when …

Pants plugins: pack_metadata - python imports rules

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
CHANGELOG.rst
pants-plugins/uses_services/redis_rules.py
pants-plugins/uses_services/redis_rules_test.py
pants.toml
pylint_plugins/BUILD
st2actions/tests/unit/BUILD
st2actions/tests/unit/policies/BUILD
st2api/tests/unit/controllers/v1/BUILD
st2api/tests/unit/controllers/v1/test_triggertypes.py
st2common/st2common/services/coordination.py

This PR updates pants CI so pants+pytest will run all unit and pack tests in CI.
Other things in this PR:
- adjusts the CI workflow to ensure we're testing with the version of python we expect.
- splits the pants test CI into 3 jobs: pants-plugins tests, unit tests (with 4 shards of tests), and pack tests.
- adds some hints to use `ST2TESTS_REDIS_HOST` and `ST2TESTS_REDIS_PORT` env vars to error/warning messages when coordination backend isn't configured or when `pants-plugins/uses_services` can't find a running redis service. _I added this because I forgot about that, which made tests fail._
- adds `ensure_indexes = True` on one st2api triggertypes test that was failing because the index wasn't in mongo. My best guess is that the test relied on another test to create the indexes.
This …

Pants CI: Run all unit and pack tests

---

scripts/github/configure-rabbitmq.sh
scripts/github/prepare-integration.sh
tools/launchdev.sh

This PR just refactors some CI scripts to prepare for (a) running integration tests via pants, and (b) the PR where we enable configuring StackStorm via env vars (a new oslo_config feature). Since this is an internal-only change/refactor, I added the https://github.com/StackStorm/st2/labels/no%20changelog label.
It is probably easiest to review each commit+commit message of this PR as github's diff is confusing in at least one place.

Refactor some CI scripts

---

CHANGELOG.rst
contrib/runners/local_runner/tests/integration/test_localrunner.py
contrib/runners/orquesta_runner/tests/integration/BUILD
pants.ci.toml
pants.toml
st2actions/tests/integration/BUILD
st2api/tests/integration/BUILD
st2common/tests/fixtures/BUILD
st2common/tests/integration/BUILD
st2reactor/tests/integration/BUILD
st2tests/integration/orquesta/BUILD

This PR primarily makes this change, plus a few other minor things:
- BUILD metadata for integration tests, including explicit dependencies that could not be inferred and `uses=` config for our `pants-plugins/uses_services` plugin.
The other minor things I included are:
- Silence pants' remote cache warnings. GitHub Actions Caching has a really low API rate limit that we hit regularly. When we hit that, we get 429 errors that pants displays as warnings (LOTS of warnings). The warnings are not actionable--we can't do anything about GitHub's paltry rate limit--and there is basically no impact on our CI--pants just runs the process if it can't find it in the cache or the cache …

Pants: Add BUILD metadata for integration tests

---

CHANGELOG.rst
st2actions/st2actions/config.py
st2actions/st2actions/notifier/config.py
st2actions/st2actions/scheduler/config.py
st2actions/st2actions/workflows/config.py
st2api/st2api/config.py
st2api/tests/integration/test_gunicorn_configs.py
st2auth/st2auth/config.py
st2common/st2common/config.py
st2common/tests/integration/test_register_content_script.py
st2common/tests/integration/test_service_setup_log_level_filtering.py
st2reactor/st2reactor/cmd/trigger_re_fire.py
st2reactor/st2reactor/garbage_collector/config.py
st2reactor/st2reactor/rules/config.py
st2reactor/st2reactor/sensor/config.py
st2reactor/st2reactor/timer/config.py
st2reactor/tests/integration/test_garbage_collector.py
st2reactor/tests/integration/test_sensor_container.py
st2stream/st2stream/config.py
st2tests/st2tests/base.py
st2tests/st2tests/config.py

We have upgraded to a version of oslo_config that supports overriding conf vars via environment variables. That support is enabled by default, but it hardcodes the env var prefix `OS_`. Since oslo_config is designed for use within OpenStack, the OpenStack devs did not have a reason to make that prefix configurable. Using `OS_` does not make sense for the StackStorm project, so I changed the prefix to `ST2_` in this subclass:
https://github.com/StackStorm/st2/blob/4e8794c99a97fd92dda85f74ae0989e56dc715e4/st2common/st2common/config.py#L904-L908
To use this class, we have to update the `cfg.CONF` global to use our subclass instead of the default. This is done with a helper method: …

Add support for overriding `st2.conf` settings via env vars

---

CHANGELOG.rst
contrib/runners/orquesta_runner/tests/integration/BUILD
pants-plugins/uses_services/register.py
pants-plugins/uses_services/scripts/is_st2cluster_running.py
pants-plugins/uses_services/st2cluster_rules.py
pants-plugins/uses_services/st2cluster_rules_test.py
pants-plugins/uses_services/target_types.py
st2tests/integration/orquesta/BUILD

Today, we run a dev st2 cluster using `tools/launchdev.sh` for all integration tests. However, only a subset of the tests actually make use of the running service. The only tests that require the dev st2 cluster are orquesta runner integration tests (which run today as part of integration tests) and the orquesta integration tests (in `st2tests/integration/orquesta`) that today run in a separate Orquesta Tests CI job.
The rest of the integration tests actually start the `st2api` or other process as part of the test, so they ignore the dev cluster, meaning CI doesn't need to the overhead of running the full cluster to run those tests. Plus, when running the tests locally, you …

pants-plugins/uses_services: add support for uses=st2cluster in BUILD metadata

---

CHANGELOG.rst
pants-plugins/uses_services/exceptions.py
pants-plugins/uses_services/mongo_rules.py
pants-plugins/uses_services/mongo_rules_test.py
pants-plugins/uses_services/redis_rules.py
pants-plugins/uses_services/scripts/is_mongo_running.py
pants.toml

This lightly refactors `pants-plugins/uses_services` to make it easier to mention the `ST2_*` conf vars (introduced in #6277) in the instructions messages that the plugin prints when a service isn't running.
Then this PR updates the mongo rules to make use of the `ST2_DATABASE__*` conf vars if present. Thus, people can use `ST2_DATABASE__*` both in production and when testing to use whatever database they choose.
This only passes a subset of the possible `ST2_DATABASE__*` vars to tests. If anyone wants to add others, they need to review the tests to see if the tests override that setting or not. This is the config that tells pants to pass these vars to pytest: …

pants-plugins/uses_services: respect `ST2_DATABASE__*` vars

---

CHANGELOG.rst
conf/st2.conf.sample
conf/st2.dev.conf
pants-plugins/uses_services/rabbitmq_rules.py
pants-plugins/uses_services/rabbitmq_rules_test.py
pants.toml
st2actions/tests/integration/test_actions_queue_consumer.py
st2common/benchmarks/micro/test_publisher_compression.py
st2common/st2common/config.py
st2common/st2common/stream/listener.py
st2common/st2common/transport/actionalias.py
st2common/st2common/transport/actionexecutionstate.py
st2common/st2common/transport/announcement.py
st2common/st2common/transport/bootstrap_utils.py
st2common/st2common/transport/execution.py
st2common/st2common/transport/kombu.py
st2common/st2common/transport/liveaction.py
st2common/st2common/transport/publishers.py
st2common/st2common/transport/queues.py
st2common/st2common/transport/reactor.py
st2common/st2common/transport/workflow.py
st2common/st2common/util/queues.py
st2common/tests/unit/test_queue_consumer.py
st2common/tests/unit/test_state_publisher.py
st2common/tests/unit/test_transport.py
st2tests/st2tests/config.py

This adds a new option `[messaging].prefix` to configure the prefix used in RabbitMQ exchange and queue names.
Examples of how this affects our exchange/queue names:
| `prefix=st2` (default) | `prefix=st2dev` (launchdev.sh) | `prefix=foobar`        | **Type** |
|------------------------|--------------------------------|------------------------|----------|
| `st2.execution`        | `st2dev.execution`             | `foobar.execution`     | Exchange |
| `st2.sensor`           | `st2.sensor`                   | `foobar.sensor`        | Exchange |
| `st2.workflow.work`    | `st2dev.workflow.work`         | `foobar.workflow.work` | Queue    |
I recommend reviewing each commit …

Add new option `[messaging].prefix` to configure prefix of RabbitMQ exchange/queue names

---

CHANGELOG.rst
conf/st2.dev.conf
fixed-requirements.txt
pants-plugins/uses_services/redis_rules.py
pants-plugins/uses_services/redis_rules_test.py
pants-plugins/uses_services/scripts/is_redis_running.py
pants.toml
requirements.txt
st2tests/requirements.txt
st2tests/st2tests/config.py
tools/launchdev.sh

When running tests in parallel, the keys stored in redis for one test can mess up the expected redis keys needed by a different test. The community edition of redis has 16 logical databases, but if someone has more cores than that or uses pants remote test execution (with a default of 128 possible remote executors running in parallel), then 16 is not enough.
It turns out, the tooz redis driver already has a config option to support this: `namespace`. By default, the tooz driver uses `_tooz` as the key namespace. We can change that by passing a `namespace` query param in `[coordination].url`.
So, I updated the tests config to change the namespace using the pants-provided …

Make tests safer to run in parallel by changing the Redis key namespace

---

.github/workflows/test.yaml
CHANGELOG.rst
pants.toml

This adds 2 GHA jobs to the pants+pytest CI workflow:
- `integration-tests`
- `integration-st2cluster-tests`
Sadly, GHA is very repetitive, so a lot of the steps for these jobs are just copies of steps in other jobs. So, this should be fairly easy to review despite the line count.  Go through each commit to see why I made a few changes to some steps.
Currently, we run Makefile-based integration tests in CI and Orquesta CI workflows. For the pants+pytest CI, I opted to do 2 jobs instead of separate workflows. Also, I found that the only integration tests that require a running st2cluster (started with `tools/launchdev.sh`) are the orquesta tests. Since st2cluster is not required by most integration tests, I was able to simplify the setup and avoid starting it. This also means there will be …

pants ci: add integration tests jobs

---

.github/workflows/test.yaml
CHANGELOG.rst
scripts/ci/add-itest-user-key.sh
st2common/bin/st2-self-check
st2common/bin/st2ctl
st2reactor/tests/integration/test_sensor_watcher.py
tools/launchdev.sh

This adds a Pants-based CI job to run `st2-self-check` with a virtualenv generated by pants.
I recommend reviewing each commit.
The largest chunk of this PR is in 12af930 where I add the GHA job that runs st2-self-check.
Everything else is minor cleanup (or bugfixes) of several random scripts and a test.
I can split the unrelated changes into a separate PR if needed, but they're fairly small, so I hope we can just include them here.

Pants ci: Run self-check tests w/ venv generated by pants

---

.github/actions/setup-python/action.yaml
.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/microbenchmarks.yaml
.github/workflows/orquesta-integration-tests.yaml
.github/workflows/pants.yaml
.github/workflows/test.yaml
.pre-commit-config.yaml
CHANGELOG.rst
fixed-requirements.txt
lockfiles/bandit.lock
lockfiles/black.lock
lockfiles/flake8.lock
lockfiles/pylint.lock
lockfiles/st2.lock
lockfiles/twine.lock
pants.toml
requirements.txt
st2tests/requirements.txt
test-requirements.txt

This cherry-picks commits from #6236 by @nzlosh and @guzzijones.
This adds python 3.10 and 3.11 to:
- GHA workflow test matrixes
- pants interpreter_constraints and lockfiles
The vast number of additional tests in our test matrix made it difficult to ensure we included the new python versions everywhere required. So, I refactored the `matrix` in each workflow to let GitHub handle expanding the matrix for us.
While I was in the GHA workflows I noticed a couple of minor issues, so I fixed those as well:
- Fixed a typo in `.github/actions/setup-python` that was causing a lot of warnings to be listed under GHA annotations.
- Replaced `on.pull_request.type` with `on.pull_request.types`. "type" is not a valid key, so our workflows have just been using the default list of events: `opened, …

Add official support for python 3.10 and 3.11

---

fixed-requirements.txt
requirements.txt
st2actions/in-requirements.txt
st2actions/requirements.txt
st2client/in-requirements.txt
st2client/requirements.txt
st2common/in-requirements.txt
st2common/requirements.txt

Fix the lint CI job failure caused by a new version of urllib3 that does not support python 3.8. This is a transitive dep, so I just copied the locked version from `lockfiles/st2.lock` into our requirements files. I added it to any `in-requirements.txt` that included `requests`.

pin urllib3 to version in lockfiles/st2.lock

---

BUILD
CHANGELOG.rst
conf/st2.conf.sample
fixed-requirements.txt
lockfiles/st2.lock
requirements-pants.txt
requirements.txt
st2auth/in-requirements.txt
st2auth/requirements.txt
st2common/requirements.txt
st2tests/requirements.txt
test-requirements.txt

st2-packages.git has been injecting another dependency since 2016 (https://github.com/StackStorm/st2-packages/commit/d35c03e9044b3746a07cb6c99129ce7fabb96f6e):
```
git+https://github.com/StackStorm/st2-auth-backend-pam.git@master#egg=st2-auth-backend-pam
```
https://github.com/StackStorm/st2-packages/blob/7ed6bf12d101aa34456b711723be9f81d3be82d7/packages/st2/in-requirements.txt#L8
The legacy Makefile gets the dep indirectly via st2-packages.git, but that will be archived when we start using pants to build packages. So, this PR copies that requirement into `pants-requirements.txt` here (and to `st2auth/in-requirements.txt`):
https://github.com/StackStorm/st2/blob/f35044557da8677bcd2b379e8cf159de61d8179f/requirements-pants.txt#L81
Then, since pants can't infer a dep on plugins like this, we …

Copy dependency on st2-auth-backend-pam from st2-packages.git

---

CHANGELOG.rst
contrib/chatops/BUILD
contrib/chatops/tests/BUILD
contrib/core/BUILD
contrib/core/tests/BUILD
contrib/debug/BUILD
contrib/default/BUILD
contrib/examples/BUILD
contrib/examples/actions/windows/BUILD
contrib/examples/tests/BUILD
contrib/hello_st2/BUILD
contrib/linux/BUILD
contrib/linux/tests/BUILD
contrib/packs/BUILD
contrib/packs/tests/BUILD
pants-plugins/macros.py
pants-plugins/pack_metadata/python_rules/python_pack_content_test.py
pants-plugins/pack_metadata/target_types.py
pants.toml

There are several packs that get installed with st2 (Installing via the deb/rpm is the only official way to get these):
- `chatops`
- `core`
- `default`
- `linux`
- `packs`
Unlike exchange packs, these 5 packs are not git repos, so if anyone makes a change (for shame :wink:), there isn't a simple way to revert the pack without reinstalling the st2 rpm/deb.
There are 3 other packs in the st2 repo:
- `examples`
- The `examples` pack gets installed under `/usr/share/doc/st2/examples`. The official way to install that pack is to copy it manually: https://docs.stackstorm.com/start.html#start-deploy-examples
- `hello_st2`
- The `hello_st2` pack is only for a docs tutorial on creating packs, so there is no official way to install it: https://docs.stackstorm.com/reference/packs.html#creating-your- …

Pants+Packaging: Add `makeself_archive` for each pack to facilitate installation

---

CHANGELOG.rst
packaging/deb/scripts/post-install.sh
packaging/deb/scripts/post-remove.sh
packaging/deb/scripts/pre-install.sh
packaging/rpm/scripts/pre-install.sh

This PR is working towards doing packaging via pantsbuild. Eventually, I hope to archive and stop using st2-packages.git. This PR begins refactoring `packaging/{rpm,deb}/scripts/*.sh` cherry-picked in:
- #6313
This refactor PR focuses on removing code from the scripts including dead code, broken code, and legacy code that is now pointless. I recommend reviewing each commit, as the commit description explains what is being removed and why.

Packaging: remove dead/broken/legacy code from `packaging/{rpm,deb}/scripts`

---

BUILD
CHANGELOG.rst
contrib/core/actions/send_mail/BUILD
contrib/examples/actions/BUILD
contrib/examples/actions/bash_exit_code/BUILD
contrib/examples/actions/bash_random/BUILD
contrib/linux/actions/BUILD
packaging/deb/scripts/post-install.sh
packaging/deb/scripts/post-remove.sh
packaging/deb/scripts/pre-install.sh
packaging/rpm/scripts/pre-install.sh
pants-plugins/macros.py
pants.toml
scripts/BUILD
scripts/ci/BUILD
scripts/github/BUILD
st2actions/bin/BUILD
st2common/bin/BUILD
st2common/bin/migrations/v2.1/BUILD
st2common/tests/fixtures/BUILD
st2tests/integration/BUILD
st2tests/st2tests/fixtures/generic/actions/BUILD
st2tests/st2tests/fixtures/packs/BUILD
st2tests/st2tests/fixtures/ssl_certs/BUILD
st2tests/testpacks/errorcheck/actions/BUILD
tools/BUILD

The inconsistent formatting makes it harder to compare deb vs rpm scripts. At first I reformatted manually, but that will get lost quickly as we all make improvements. So, I added `shfmt` to format deb maintainer scripts / rpm scriptlets. To enable it I added the shfmt backend to `[GLOBAL].backend_packages` in `pants.toml`.
https://github.com/StackStorm/st2/blob/08fd2ba5d4e4cbeceae1af4ba7ef905480898fd3/pants.toml#L29
I want to keep this PR focused on packaging, so I added `skip_shfmt=True` to all the BUILD metadata for shell scripts that would be reformatted (other than `packaging/{rpm,deb}/scripts/*.sh`. Someone else can remove those `skip_shfmt` parameters to enable …

Packaging: Add shfmt to format deb maintainer scripts / rpm scriptlets

---

CHANGELOG.rst
packaging/deb/scripts/post-install.sh
packaging/rpm/scripts/post-install.sh

This PR is the last (planned) packaging PR that edits a deb maintainer script and an rpm scriptlet.
As noted in #6319, I did not expand the debhelper snippets and rpm macros that manage building the `/opt/stackstorm/st2` virtualenv. Instead of expanding them, this PR replaces them with logic that is uniform for both deb and rpm. This replacement avoids the dh_virtualenv debhelper that is unsupported upstream, and skips the complexity of using the external tool we used in rpms.
This PR makes the rpm/deb post-install scripts:
- run the pex to extract the virtualenv.
- added in #6307
- run the pack archives to install them in `/opt/stackstorm/packs` and …

Packaging: extract venv (from pex) and packs (from archives) during rpm/deb post-install

---

OWNERS.md

@skiedude has made a variety of contributions, including a major update for hubot-stackstorm (StackStorm/hubot-stackstorm#238, StackStorm/st2chatops#192) to support changes to Slack APIs, various fixes to our helm chart (StackStorm/stackstorm-k8s#403), CI (StackStorm/st2#6296, StackStorm/st2-packages#750), etc, and regular participation in the TSC meeting.
Check out a more complete list of contributions:
- [Stackstorm org PRs](https://github.com/search?q=org%3AStackStorm+author%3Askiedude&type=pullrequests)
- [StackStorm-Exchange org PRs](https://github.com/search?q=org%3AStackStorm-Exchange+author%3Askiedude&type=pullrequests)
Let's recognize his contributions by adding him as an official Contributor.  Thank you Jake Z!
@StackStorm/tsc please vote by approving this PR.

Add skiedude to Contributors

---

CHANGELOG.rst
contrib/runners/orquesta_runner/in-requirements.txt
contrib/runners/orquesta_runner/requirements.txt
fixed-requirements.txt
pants-plugins/release/rules.py
pants.toml
requirements.txt
st2actions/in-requirements.txt
st2actions/requirements.txt

This PR enables the `nfpm` backend in pants and updates `pants-plugins/release` so that it can inject the version number into the rpm/deb similar to how that plugin injects the version in python wheels that pants builds. To keep this PR focused on `pants-plugins/release`, it does not add any BUILD metadata like `nfpm_deb_package` or `nfpm_rpm_package`. Adding the BUILD metadata, and using the changes introduced in this PR, will come in follow-up PRs.
- [`nfpm` subsystem](https://www.pantsbuild.org/stable/reference/subsystems/nfpm)
- [`nfpm_deb_package` target](https://www.pantsbuild.org/stable/reference/targets/nfpm_deb_package)
- [`version_schema` …

Packaging: Inject st2 version into rpm/deb packages (pants-plugins/release)

---

CHANGELOG.rst
lockfiles/pants-plugins.lock
pants-plugins/release/BUILD
pants-plugins/release/packagecloud_rules.py
pants-plugins/release/requirements.txt
pants-plugins/release/rules.py
pants.toml

One of the key parts of packaging is assigning a release number for a given build. The only way to do that is to query packagecloud to see what the last release was and add 1 to that. We use a shell script to do that in st2-packages.git:
https://github.com/StackStorm/st2-packages/blob/master/.circle/packagecloud.sh
In this PR I rewrote that shell script in python in `pants-plugins/release` as pantsbuild `@rule`s. Then this builds on #6321 by Injecting the release number from packagecloud as the `release` field on `nfpm_deb_package` and `nfpm_rpm_package` targets.
[`latest_revision`](https://github.com/StackStorm/st2-packages/blob/8661602babefb201204b723e4330e0fd5a68988a …

Packaging: reimplement packagecloud release number script as a pants rule

---

CHANGELOG.rst
pants-plugins/release/register.py
pants-plugins/release/rules.py
pants-plugins/release/target_types.py

This is a follow-up to #6323, resolving the TODO explained in https://github.com/StackStorm/st2/pull/6323#discussion_r2012211865.
In `pants-plugins/release`, a new `distro_id` field is defined here:
https://github.com/StackStorm/st2/blob/00ff205ebefddc97ef6378a74ccaca7feaf353f9/pants-plugins/release/target_types.py#L22-L24
This field basically accepts an enum of `valid_choices`. These `valid_choices` should be a list of supported or soon-to-be-supported distros:
https://github.com/StackStorm/st2/blob/00ff205ebefddc97ef6378a74ccaca7feaf353f9/pants-plugins/release/target_types.py#L25-L33
And mark the field as `required` so that all BUILD targets have this field defined …

Packaging: Add `distro_id` field to `nfpm_deb_package` and `nfpm_rpm_package` targets

---

st2common/tests/unit/test_param_utils.py
st2common/tests/unit/test_stream_generator.py

This small PR migrates from `unittest.assertEquals` to `unittest.assertEqual` due to deprecations:
```python
DeprecationWarning: Please use assertEqual instead.
```

fix: migrate to unittest.assertEqual
