StackStorm/st2

- st2api/st2api/listener.py
We don't actually need shutdown methode there, but for consistency I still added
it (all the other worker classes written by us also have it).
> Fix "listener has no attribute shutdown"

- st2tests/integration/mistral/test_wiring.py
Action execution output has changed. The tests need to adapt.
> Fix mistral integration tests

- st2client/requirements.txt
- st2client/st2client/utils/jsutil.py
- st2client/tests/unit/test_formatters.py
- st2client/tests/unit/test_util_json.py
- Benefit of using this library is that some more key options open up.
- Subtle fix in the return of jsutil to improve rendering of dict values.
=== Output ===
* Without -k
```
$ st2 execution get 54822ea10640fd1b449fc5e7
STATUS: succeeded
RESULT:
{
"localhost": {
"stderr": "",
"succeeded": true,
"stdout": "PING google.com (74.125.239.136) 56(84) bytes of data.
64 bytes from nuq05s02-in-f8.1e100.net (74.125.239.136): icmp_seq=1 ttl=63 time=6.47 ms
64 bytes from nuq05s02-in-f8.1e100.net (74.125.239.136): icmp_seq=2 ttl=63 time=80.2 ms
64 bytes from nuq05s02-in-f8.1e100.net (74.125.239.136): icmp_seq=3 ttl=63 time=7.08 ms
64 bytes from nuq05s02-in-f8.1e100.net (74.125.239.136): icmp_seq=4 ttl=63 time=6.25 ms
64 bytes from nuq05s02-in-f8.1e100.net …
```
> Use jsonpath library to walk dict hierarchy.

- st2actions/st2actions/runners/localrunner.py
- st2common/st2common/models/system/action.py
- st2common/st2common/util/jsonify.py
* Add a json_loads utility method in st2common/util/jsonify.py
* Add test cases for utility method
* FabricRunner and LocalShellRunner to use utility method to transform
stdout and stderr streams
```
(virtualenv)~/stanley git:STORM-931/parse_json_in_results_shell_runners ❯❯❯ st2 run core.local shit                                                                                                                             ✭ ✱ ◼
.
+-----------------+-----------------------------+
| Property        | Value                       |
+-----------------+-----------------------------+
| id              | 54aee0740640fd77c6c9f312    |
| context         | {                           |
|                 |     "user": "lakshmi"       |
|                 | }                           |
| parameters …
```
> json loads 'stdout' and 'stderr' in shell & ssh runners

- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- Error raised in in processing params etc is now bubbled up as a result of the execution.
> ActionChainRunner stores error.

- st2actions/st2actions/container/base.py
This fixes a bug which was introduced with the recent runner refactorings.
All of the actions failed to complete successfuly and blew up with "Failed to execute action.". The problem is that we were returning actionexec_db object which didn't have the result populated yet.
```bash
2015-01-09 16:48:44,032 ERROR [-] execute_action failed. Message body : ActionExecutionDB(action="core.local", callback={}, context={'user': 'stanley'}, end_timestamp=None, id=54b0066b0640fd0bb55dee38, parameters={u'cmd': u'echo "aa"'}, result={}, start_timestamp="2015-01-09 16:48:43.969902+00:00", status="scheduled")
File "/data/stanley/st2actions/st2actions/worker.py", line 67, in _do_process_task
self.execute_action(body)
File "/data/stanley/st2actions/st2actions/worker.py", …
```
> Fix a bug with action runners not working

- st2client/st2client/formatters/doc.py
- st2client/st2client/utils/jsutil.py
- st2client/tests/unit/test_util_json.py
- mostly reverting a previous change. Since only parts are to be reverted creating new commits.
- With this the -j option does not introduce new control characters thus the output remains consumable json.
> cli json output changes

- st2actions/st2actions/runners/httprunner.py
Looks like I did not remove this line. I grepped and we don't have report_result in our code anymore.
> Remove report_result from http runner

- CHANGELOG.rst
- st2common/st2common/models/api/rule.py
- st2common/st2common/services/triggers.py
- st2common/tests/unit/test_trigger_services.py
- st2reactor/tests/unit/test_sensor_and_rule_registration.py
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_1.json
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_2.json
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_3.json
- st2tests/st2tests/fixturesloader.py
Currently, we don't create a trigger for each rule. This results in parameters
being equal for all triggers. The behavior we want is to reuse the same trigger
if the parameters are same. If they are different, we want a new trigger to be
created.
* _get_trigger_api_given_rule in st2common/services/triggers now returns the right
trigger API object.
* Add test cases to catch the bug.
* Add fixtures.
> RFR: New trigger should be created for each rule with different trigger parameters

- st2actions/st2actions/runners/localrunner.py
- st2actions/tests/integration/test_localrunner.py
- st2tests/st2tests/fixtures/localrunner_pack/actions/text_gen.py
- st2tests/st2tests/fixtures/localrunner_pack/actions/text_gen.yml
- Using Popen.wait() with STDOUT=subprocess.PIPE causes a deadlocal and it is
described as a warning in the docs as well. Basically, the child process blocks
on the buffer from being empty and the spawning process is wait for the child to
quite prior to reading - so deadlock.
- The solution is to use Popen.communicate(). Using this works great and large
data upto 10^6 chars can also be read. Rest of the system starts struggling but
that is not in scope of this commit.
- Using communicate leads to challenges with kill on a timeout. The timeout is placed
to avoid bad action from taking down the runners. The only way to cleanly handle the
kill of all the process is to use pkill. The specific way in which the shell command
is constructed implies that there is no child-parent relation. …
> Support local actions that output more than 65535 chars

- CHANGELOG.rst
- st2actions/st2actions/runners/python_action_wrapper.py
- st2actions/st2actions/runners/pythonrunner.py
* Print the exception to stderr and make sure exception shows in
action execution object.
> RFR: Set action status as failure on python action exceptions

- contrib/examples/actions/mistral-basic.json
- contrib/examples/actions/mistral-basic.yaml
- contrib/examples/actions/mistral-workbook-basic.json
- contrib/examples/actions/mistral-workbook-basic.yaml
- contrib/examples/actions/mistral-workbook-complex.json
- contrib/examples/actions/mistral-workbook-complex.yaml
- docs/source/mistral.rst
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2.py
- st2tests/integration/mistral/test_wiring.py
- st2tests/st2tests/fixtures/generic/actions/workflow_v2.json
- st2tests/st2tests/fixtures/generic/actions/workflow_v2_many_workflows.json
- st2tests/st2tests/fixtures/generic/workflows/workflow_v2.yaml
- st2tests/st2tests/fixtures/generic/workflows/workflow_v2_many_workflows.yaml
Add support of mistral workflow only (non-workbook) definition. Definition
with multiple workflows is not supported because the default workflow to
launch would be ambiguous.
> Add support of mistral workflow only definition

- docs/source/reference/packs.rst
Also fixes a spelling mistake.
Found by Aamir while doing pack development.
> [docs] Updating pack target directory

- CHANGELOG.rst
- st2actions/st2actions/container/service.py
- st2actions/st2actions/utils/param_utils.py
- st2actions/tests/unit/test_param_utils.py
- st2api/st2api/controllers/v1/actionviews.py
- st2common/st2common/content/utils.py
- st2common/st2common/models/utils/action_param_utils.py
- st2common/tests/unit/test_action_param_utils.py
- st2tests/st2tests/fixtures/generic/actions/action1.json
- st2tests/st2tests/fixtures/generic/runners/testrunner1.json
- all utils that st2api requires are moved to st2common.
- moved around some tests.
- migrated affected tests to using fixtures.
- verified fix by running st2api standalone.
> remove st2api dependency on st2actions

- contrib/examples/actions/mistral-workbook-basic.json
- st2actions/st2actions/runners/mistral/utils.py
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_dsl_transform.py
- st2actions/tests/unit/test_mistral_v2.py
- st2tests/st2tests/fixtures/generic/actions/workbook_v2_name_mismatch.json
- st2tests/st2tests/fixtures/generic/actions/workflow_v2_name_mismatch.json
- st2tests/st2tests/fixtures/generic/workflows/workflow_v2.yaml
- st2tests/st2tests/fixtures/generic/workflows/workflow_v2_many_workflows.yaml
If name of the mistral workbook or workflow is not the same as the action ref, raise an exception.
> Raise exception if workbook/workflow name is not equal to action_ref

- docs/source/conf.py
But for backward, refer previous build as it is, 0.6.0
> Use X.Y version in docs on v0.7

- st2api/st2api/controllers/v1/actions.py
- st2api/st2api/controllers/v1/rules.py
- st2api/st2api/controllers/v1/triggers.py
- st2api/tests/unit/controllers/v1/test_actions.py
- st2api/tests/unit/controllers/v1/test_rules.py
- st2api/tests/unit/controllers/v1/test_triggertypes.py
- st2common/st2common/exceptions/db.py
- st2common/st2common/models/api/base.py
- st2common/st2common/persistence/access.py
- st2common/st2common/persistence/action.py
- st2common/st2common/persistence/actionrunner.py
- st2common/st2common/persistence/base.py
- st2common/st2common/persistence/datastore.py
- st2common/st2common/persistence/history.py
- st2common/st2common/persistence/reactor.py
- On conflict identify the conflict object at the persistence layer.
- In process of trying to localize the uniqueness identification changes ended up having to change ContentPackResourceMixin to ContentPackResource i.e. subclass from Access.
- Changes to how errors are handled in the API. This way headers, original body etc are preserved.
- Updated all API sites to move from NotUniqueError to StackStormDBObjectConflictError and include the conflict-id as part of the abort call.
- Minor change from kls -> cls as per typical python norms.
> RFR: Include conflict id in API response

- conf/st2.conf
- st2common/st2common/config.py
- st2common/st2common/log.py
- By default the redirection is not performed.
- Enabling the redirection helps in debugging issues where the error is written to sys.stderr and in production stderr is typically redirected to dev/null.
> RFR: Configuration to redirect stderr to logs.

- st2actions/Makefile
- st2actions/packaging/rpm/st2actions-rhel6.spec
- st2api/Makefile
- st2api/packaging/rpm/st2api-rhel6.spec
- st2auth/Makefile
- st2auth/packaging/rpm/st2auth-rhel6.spec
- st2client/Makefile
- st2common/Makefile
- st2common/packaging/rpm/st2common-rhel6.spec
- st2reactor/Makefile
- st2reactor/packaging/rpm/st2reactor-rhel6.spec
This adds spec files and Make file targets for building rhel-rpms.  We will need an RHEL6 build host in conjunction with this.
> Adding rhel-rpm Makefile targets

- conf/st2.conf
- docs/source/install/deploy.rst
- st2auth/st2auth/config.py
- st2auth/st2auth/controllers/access.py
- st2tests/st2tests/config.py
As discussed a while ago.
Service catalog functionality will become even more important in the future where we support the scale out story and user can run API and other services on multiple servers potentially running in different regions.
This still needs corresponding webui changes - /cc @enykeev
> Update st2auth to return configured public URL to API endpoint on successful auth

- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/content/loader.py
- st2common/tests/unit/test_content_loader.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/st2reactor/bootstrap/sensorsregistrar.py
This branch allows user to register resources from a specific pack using register-content.py script by passing `--pack=<pack dir>` argument to the script.
Among other places, I will use this functionality in st2contrib to validate resources in a particular pack against the schema (this happens during registration).
> Allow user to register resources from a specific pack

- contrib/examples/actions/mistral-basic.yaml
- contrib/examples/actions/mistral-workbook-basic.yaml
- contrib/examples/actions/mistral-workbook-complex.yaml
- contrib/examples/actions/mistral-workbook-subflows.json
- contrib/examples/actions/mistral-workbook-subflows.yaml
- st2actions/st2actions/container/base.py
- st2actions/st2actions/handlers/mistral.py
- st2actions/st2actions/query/base.py
- st2actions/st2actions/query/mistral/v2.py
- st2actions/st2actions/runners/__init__.py
- st2actions/tests/unit/test_runner_container.py
- st2common/st2common/util/jsonify.py
- st2common/tests/unit/test_jsonify.py
- st2tests/integration/mistral/test_wiring.py
Refactor mistral query module to get workflow output from mistral API and save to the execution result. Refactor Querier to invoke post run when async action is completed. In the case of mistral, the post run update the task state and output on workflow action completion. This allows stitching of multiple workflow actions.
> Add workflow output to execution result and update mistral task

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- st2actions/st2actions/config.py
- st2common/st2common/config.py
This change makes Python binary which is used in virtual environments by Python runner actions configurable.
Previously we used system's default Python binary, but now we used the same binary which is used to run action runner (which is better anyway, good catch @phool).
> Default Python binary used by Python runner actions to be the one used by action runner

- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/unit/test_pythonrunner.py
Previously a cryptic error was returned to the user.
Ideally, down the road, we would have a schema per runner type (local and remote actions without entry_point are fine, but python actions require entry_point).
> Fix empty entry point python runner bug

- st2reactor/st2reactor/container/sensor_wrapper.py
Currently we explicitly perform it in the sensors, but with this change, we don't need to do this anymore.
Originally, the idea was not to perform it in the wrapper and the sensors who need it must explicitly opt-in (in general blocking is not an issue here since sensors run in a separate process).
And if this ever becomes a problem, we can also make it opt-in (or opt-out) via sensor metadata or via base-class.
> Perform eventlet monkey patching in the sensor wrapper

- tools/st2_deploy.sh
A change was made in https://github.com/StackStorm/st2/commit/239d6f453f937f51328e7c9f35a8076f81910ea2 than needs to be moved to the st2_deploy.sh command. Repairs actions not properly registering on first-install, needing to run `st2ctl reload` to repair.
/cc @Kami @DoriftoShoes
> register_content to pass appropriate flags.

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/download.py
- requirements.txt
This should fix a bug / issue encountered by @jfryman.
> 1) During my first pass, I attempted to model in Puppet installation of individual packs one at a time (e.g.: for each pack, I executed a unique st2 action execute packs=XXX). This created a really interesting lock in the system... where all of the pack installs at the same time pounced all over each other and failed. I tried to debug this a bit, but couldn't find anything. I can pretty easily reproduce it though.
> Fix a bug / race condition occurring during concurrent pack installation

- st2actions/st2actions/query/mistral/v2.py
Mistral API stores task result, input, and output as text. Modify the
mistral query module for results tracker to try converting the text to
json.
> Try to json load mistral task result/input/output

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2common/st2common/models/system/actionchain.py
- st2common/tests/unit/test_actionchain_schema.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_vars.json
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_output.json
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_publish.json
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_vars.json
- st2tests/st2tests/fixtures/generic/actionchains/no_default_chain.json
- Proper schema for ActionChain
- Schema validation catches malformed yaml/json
- default node is now optional
- support for vars
```
{
"vars": {
"strtype": "{{system.a}}",
"inttype": 1
},
"chain": [
{
"name": "c1",
"ref": "wolfpack.a2",
"params":
{
"inttype": "{{inttype}}",
"strtype": "{{strtype}}",
"booltype": true
}
}
],
"default": "c1"
}
```
- support for output variable per action_node
```
{
"chain": [
{
"name": "c1",
"ref": "wolfpack.a2",
"params":
{
"inttype": "{{inttype}}",
"strtype": "{{strtype}}",
"booltype": true
},
"output":
{
"o1": "{{c1.foo.bar}}"
},
"on-success": "c2"
},
{
"name": "c2",
"ref": "wolfpack.a2",
"params":
{
"strtype": "{{o1}}"
}
}
],
"default": "c1"
}
```
Note : Full result of `c1` is still available and variables published by `c1` are in the global context.
> Actionchain improvements

- st2reactor/st2reactor/container/sensor_wrapper.py
Include a traceback when sensor.run throws and also log the same message.
> Sensor error reporting improvements

- CHANGELOG.rst
- docs/source/webhooks.rst
- st2actions/st2actions/runners/httprunner.py
- st2api/st2api/controllers/v1/webhooks.py
- st2api/tests/unit/controllers/v1/test_auth.py
- st2common/st2common/hooks.py
- st2common/st2common/middleware/auth.py
- st2common/st2common/util/auth.py
This pull request allows user to also pass authentication token via `?x-auth-token` query parameter (in addition to passing the token via header).
This popped up while I worked on the webhooks documentation (#1022). Previously webhooks were unauthenticated, but now they require same authentication as other API methods. This means webhooks won't work with 3rd party services such as Github which only allow you to manipulate URL and query parameters, but not headers.
In the past @enykeev has also asked for this feature. IIRC, Server-Sent Events don't allow you to send custom headers which means we can't authenticate those requests.
> Allow user to pass auth token via query string

- docs/source/actions.rst
This PR adds additional details around some of the built-in parameters, what they do, and mention that they can be overwritten.
/cc https://stackstorm.atlassian.net/browse/STORM-939
> Add detail for built-in parameters to Action Metadata

- tools/st2ctl
packs.{load,install} actions already call st2ctl reload with "--register-" prefix.
Encountered by cleavoy and dennybaa on IRC.
> Fix register content bug

- CHANGELOG.rst
- st2common/st2common/services/triggers.py
- st2reactor/st2reactor/container/utils.py
- st2reactor/tests/unit/test_rule_engine.py
This was a regression introduced in v0.7.
Also, for the love of a flying spaghetti monster, in the future, please use keyword args everywhere. It's easy and cheap and it makes issues like this a lot easier to spot during code reviews.
Spotted by cleavoy on IRC.
> Fix a bug with rule matching not working for any trigger with parameters

- docs/source/actions.rst
- st2actions/st2actions/bootstrap/runnersregistrar.py
- st2actions/st2actions/runners/fabricrunner.py
- st2actions/st2actions/runners/localrunner.py
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/unit/test_fabricrunner.py
- st2actions/tests/unit/test_pythonrunner.py
- st2client/st2client/commands/action.py
- st2common/st2common/models/system/action.py
- st2common/tests/fixtures/localrunner/escaping_test_command_2.txt
- st2common/tests/unit/test_shell_action_system_model.py
This change allows user to specify environment variables which are accessible to the command / scripts executed by the following runners: `run-local`, `run-local-script`, `run-remote`, `run-remote-script`, `run-python`.
In addition to that, I've added a change which makes specifying simple objects via CLI easier:
Existing approach (using JSON):
```bash
st2 run core.remote hosts=localhost env='{"key1": "val1", "key2": "val2"}' cmd='echo "ponies ${key1} ${key2}"'
```
New approach (using comma delimited string of `key=value` pairs):
```bash
st1 run core.local env="key1=foo1333,key2=foo244" cmd='echo "ponies ${key1} ${key2}"'
```
Existing approach is still supported for more complicated objects where key=value pair syntax is not sufficient.
> Allow user to provide environment variables by passing "env" parameter to the runners

- st2common/st2common/services/triggers.py
- st2common/tests/unit/test_trigger_services.py
Yet another of those nasty never ending trigger bug fixes.
Some of the Trigger database objects have `parameters` attribute set to empty dict
({}) and others don't have this attribute so we need to do double check.
Previously, an exception would be thrown since in some cases (no `parameters` attribute in the db), Trigger object wasn't found.
Honestly though, we should also do a better job with enforcing schema and data consistency in the database.
Exception:
```bash
File "/data/stanley/st2reactor/st2reactor/bootstrap/rulesregistrar.py", line 78, in _register_rules_from_pack
rule_db = RuleAPI.to_model(rule_api)
File "/data/stanley/st2common/st2common/models/api/rule.py", line 149, in to_model
trigger_db = TriggerService.create_trigger_db_from_rule(rule) …
```
> [WIP] Fix a bug when retrieving some triggers which have no parameters

- CHANGELOG.rst
- contrib/core/actions/local.json
- contrib/core/actions/local_sudo.json
- contrib/core/actions/remote.json
- contrib/core/actions/remote_sudo.json
- docs/source/cli.rst
- docs/source/index.rst
- docs/source/install/sources.rst
- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2actions/st2actions/bootstrap/runnersregistrar.py
- st2actions/st2actions/runners/fabricrunner.py
- st2actions/st2actions/runners/localrunner.py
- st2client/st2client/commands/action.py
- st2client/st2client/formatters/table.py
- st2common/st2common/models/system/action.py
- st2common/tests/unit/test_action_system_models.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/st2reactor/bootstrap/sensorsregistrar.py
This pull request allows user to override authentication information for remote actions on per action basis.
Currently, when we run remote actions, we use information from the config (username and private key) to log in to the remote server. This is fine for a common case and in an ideal world where "stanley" user account is created during a bootstrap process (e.g. using cloud-init, custom image or similar approach).
In addion to the "ideal world scenario" this approach has multiple limitations and breaks under the following scenarios:
1. You use different credentials or set of credentials for different servers or group of servers.
2. There is a "chicken and the egg" problem when bootstrapping a server using some of the cloud provider APIs.
Some of the providers return a random root …
> Allow user to override authentication information for remote runner actions on per action basis

- st2actions/st2actions/runners/mistral/utils.py
- st2tests/st2tests/fixtures/generic/workflows/wf_post_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_pre_xform.yaml
If there is no action input, do not add the parameters key.
> Fix mistral DSL transformer where action has no input

- st2api/st2api/controllers/v1/rules.py
- st2common/st2common/constants/auth.py
- st2common/st2common/hooks.py
- st2common/st2common/middleware/auth.py
- st2common/st2common/models/api/base.py
* Remove `x-auth-token` from kwargs inside jsexpose if one is provided via query parameters
* Fix query param handling in the rules controller (previously we would throw an exception if user passed in a query parameter)
```
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 442, in handle_one_response
result = self.application(self.environ, start_response)
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/pecan/middleware/recursive.py", line 56, in __call__
return self.application(environ, start_response)
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/pecan/core.py", line 762, in __call__
return super(Pecan, self).__call__(environ, start_response)
File …
```
> Query string fixes

- st2common/st2common/models/api/reactor.py
* Doing so implies st2 sensor list works.
* Not sure if the enabled property is actually honored by the back-end so setting enabled=false may not actually have any impact.
> Add enabled property to get the API working.

- CHANGELOG.rst
- docs/source/cli.rst
- st2client/st2client/commands/action.py
This pull request allows user to easily send all the environment variables which are accessible to the CLI as ``env`` parameter to the action being executed.
Keep in mind that some common environment variables which are set in a login shell such as ``PWD``, ``PATH`` and others are ignored. The feature is there to make it easier for user to send user-defined environment variables (e.g. different credentials, path to credential files, etc.) and not the ones which are defined by login script / shell. On top of that, sending some of those variables (e.g. ``PATH``, ``PYTHONPATH``, etc.) could interfere and break the action itself.
See #1034 for more information.
> Add support to action run command to inherit all the environment variables

- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_actionexecutions.py
Try to load st2-context as JSON. Throw exception if unable to load it as JSON.
> Refactor st2-context processing to be more robust

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/st2actions/utils/param_utils.py
- st2common/st2common/config.py
- st2common/st2common/models/utils/action_param_utils.py
- st2common/st2common/util/casts.py
- st2reactor/st2reactor/rules/enforcer.py
- st2reactor/st2reactor/sensor/config.py
- st2reactor/tests/unit/test_enforce.py
- st2tests/st2tests/fixtures/generic/rules/rule1.json
- st2tests/st2tests/fixtures/generic/rules/rule2.json
- st2tests/st2tests/fixturesloader.py
- Action params should be cast to their proper types as described in the metadata prior to scheduling an action.
- This way actions executed from rules can be of various types.
> Cast params prior to rule execution

- .flake8
- st2actions/st2actions/utils/param_utils.py
- st2actions/tests/integration/test_localrunner.py
- st2common/st2common/operators.py
- st2common/st2common/util/schema/__init__.py
- test-requirements.txt
We didn't pin pep8 to a specific version so when a new version of pep8 which reports new violations was released, tests started to fail.
> Pin pep8 to a specific version, clean up violations reported by new version

- st2actions/st2actions/container/base.py
- st2actions/st2actions/query/mistral/v2.py
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/st2actions/runners/fabricrunner.py
- st2actions/st2actions/runners/httprunner.py
- st2actions/st2actions/runners/localrunner.py
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2actions/tests/unit/test_mistral_v2.py
- st2actions/tests/unit/test_pythonrunner.py
- st2actions/tests/unit/test_runner.py
- st2actions/tests/unit/test_runner_container.py
- st2common/st2common/util/action_db.py
- st2common/tests/unit/test_action_db_utils.py
Add mistral execution ID and workflow name to the context on action
execution of the main workflow. Refactor all runners to include context
in the output of the run method. Refactor the asyn worker to use the
same context to build the query context.
> Add mistral reference to context on action execution

- CHANGELOG.rst
- st2api/st2api/controllers/resource.py
* Use count() method on queryset which has a better runtime. 
https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/queryset/queryset.py#L47 <- caches result.
https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/queryset/queryset.py#L97 <- no caching of result.
> Improve history call

- st2common/st2common/validators/api/action.py
`_is_valid_pack` also returns `False` if a pack directory exists, but it doesn't contain `actions/` directory so we should also make that clear in the error message.
> More friendly error message on action API validation fails

- requirements.txt
- st2common/st2common/constants/rules.py
- st2reactor/st2reactor/rules/datatransform.py
- st2reactor/st2reactor/rules/filter.py
- st2reactor/tests/unit/test_filter.py
- Use jsonpath to lookup payload instead of jinja2
- validate support for bool, int and float in criteria
> Rule criteria lookup

- st2actions/tests/integration/test_localrunner.py
* Skipped test requires for the user running the test to have sudo privileges
on the box. This will require changes on the box so skipping.
> Skip broken test

- CHANGELOG.rst
- docs/source/cli.rst
- st2client/st2client/commands/action.py
- st2client/st2client/commands/resource.py
- st2client/st2client/exceptions/base.py
- st2client/st2client/exceptions/operations.py
- st2client/st2client/shell.py
```
(virtualenv)~/stanley git:STORM-960/exit_code_when_fail ❯❯❯ st2 rule create -j bad_rule.json                 ✭ ✱ ◼
ERROR: Expecting property name: line 2 column 3 (char 4)
(virtualenv)~/stanley git:STORM-960/exit_code_when_fail ❯❯❯ echo $?                                        ⏎ ✭ ✱ ◼
2
(virtualenv)~/stanley git:STORM-960/exit_code_when_fail ❯❯❯ st2 action get twilio.get_sms                    ✭ ✱ ◼
Action "twilio.get_sms" is not found.
(virtualenv)~/stanley git:STORM-960/exit_code_when_fail ❯❯❯ echo $?                                        ⏎ ✭ ✱ ◼
2
(virtualenv)~/stanley git:STORM-960/exit_code_when_fail ❯❯❯
```
> RFR: Print exit_code when operations fail on CLI commands

- st2common/st2common/util/isotime.py
- st2common/tests/unit/test_isotime.py
Noticed it while working on / testing new aws notifications sensor.
> Fix and expand isotime regex

- CHANGELOG.rst
- st2actions/st2actions/utils/param_utils.py
- st2actions/tests/unit/test_param_utils.py
Previously we ended up in an infinite loop if rendering a param failed.
> Fix an infinite loop bug inside template rendering

- st2actions/st2actions/runners/mistral/v2.py
Pass the st2 context (i.e. original action execution, API endpoint, auth
token, etc.) to mistral using the env kwargs in start_workflow.
Previously, the st2 context is passed as start params and the custom
action in mistral has to get the st2 context directly from the database.
> Pass st2 context via env kwargs in mistral on start_workflow

- contrib/examples/actions/mistral-workbook-multiple-subflows.json
- contrib/examples/actions/mistral-workbook-multiple-subflows.yaml
The workflow exposes several flaws in mistral integration:
- internal workflow call doesn't create another execution. First `task1` should be a child of `call_internal_workflow` and the second `task1` and `task2` should be childs of `call_internal_workflow_multiple_tasks`.
- mistral workflow called from another mistral workflow (`call_external_workflow`) doesn't have task name in its context. For comparison, `call_action_chain` execution has it.
> Add another example of mistral workflow

- CHANGELOG.rst
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2.py
Before this PR, nested mistral workflows kicked off via st2 (we call it external workflows) had a problem with task name. 
Example workflow:
https://gist.github.com/lakshmi-kannan/492ca36919de99e6e1bf
LiveAction DB objects: (Pay attention to the 'context' fields)
https://gist.github.com/lakshmi-kannan/d65b09700d26d74f71dd
LiveActionDB objects after fix:
https://gist.github.com/lakshmi-kannan/3d5d859e1cacc7670788
> RFR: Hack to get task name for mistral nested workflows

- st2common/st2common/fields.py
- st2common/st2common/models/db/action.py
- st2common/tests/unit/test_db_fields.py
With this change we now store values of ``ComplexDateTimeField`` fields as number of microseconds since the epoch internally in MongoDB.
MongoEngine's version of ``ComplexDateTimeField`` stores it as a comma delimited string (e.g. ``2011,06,08,20,26,24,192284``) which results in a wrong sort order when lleading zeros are present.
This should fix an issue with action execution tests intermediate failures.
Storing is as a number should also be more efficient in terms of storage space and retrieval / querying speed.
This should fix the bug with action execution tests failing.
TODO:
> Store value of ComplexDateTimeField as number of microseconds since the epoch in the db

- CHANGELOG.rst
- docs/source/cli.rst
- st2client/st2client/commands/action.py
- st2client/tests/unit/test_action.py
This pull request adds a new CLI command for re-running an existing action (new action is ran with the same set of the input parameters as the existing one).
As discussed in the first iteration it's implemented fully as a client side feature. If more people think it's a good idea to also have this functionality in the UI, we can change it and implement it on the server side.
Implementing it as a new endpoint on the server is fully backward compatible. CLI syntax will stay the same, only thing which will change is the internal implementation of the command.
> New CLI command for re-running an action

- st2actions/st2actions/runners/actionchainrunner.py
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
- st2client/st2client/commands/action.py
- st2client/st2client/commands/resource.py
Allows user to filter action executions based on the value of `start_timestamp` attribute.
Use can either use "greater than" or "lower than" filter.
TODO:
> [WIP] Time based action execution filterting

- CHANGELOG.rst
- docs/source/actions.rst
- docs/source/index.rst
- docs/source/runners.rst
- scripts/generate-runner-parameters-documentation.py
- st2actions/st2actions/bootstrap/runnersregistrar.py
- st2actions/st2actions/runners/fabricrunner.py
- st2actions/st2actions/runners/httprunner.py
- st2actions/st2actions/runners/localrunner.py
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/integration/test_localrunner.py
- st2actions/tests/unit/test_http_runner.py
- st2common/st2common/constants/runners.py
With this change HTTP runner now parses a body if a response contains a known Content-Type.
For now, we only parse JSON responses with Content-Type of `application/json`.
To make it easier for the user, I've also added `parsed` flag to the result. This flag indicates if the response body has been parsed or not.
In the future, we can also add support for parsing other content-types, e.g. XML and HTML (e.g. with xmltodict and beautifulsoup library).
XML and HTML don't really directly map to a dictionary, so this feature would probably be an opt-in via a runner parameter.
On a semi related note - unless I've failed at grepping, we don't have any tests for the HTTP runner.
> Update HTTP runner to parse JSON response body if Content-Type is application/json

- st2actions/st2actions/runners/mistral/utils.py
- st2actions/tests/unit/test_mistral_dsl_transform.py
- st2tests/st2tests/fixtures/generic/workflows/wf_post_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_pre_xform.yaml
Modify mistral DSL transformer to strip curly braces from strings for
inline parameters of actions. This only applies to inline parameters
that are YAQL expressions only.
> Fix mistral DSL transformer on inline parameters

- st2actions/st2actions/cmd/actionrunner.py
- st2actions/st2actions/cmd/st2resultstracker.py
- st2api/st2api/cmd/api.py
- st2common/bin/bootstraprmq.py
- st2common/st2common/transport/bootstrap.py
- st2common/st2common/transport/execution.py
- st2common/st2common/transport/utils.py
- st2reactor/st2reactor/cmd/rulesengine.py
- st2reactor/st2reactor/cmd/sensormanager.py
* Command to bootstrap rabbitmq. For now only exchanges are created.
* Command is called from all start/launch scripts.
Note : Since it is a bootstrap step decided to keep it outside. Similar to the registercontent step just that it is configuring an external component.
Fixes : https://stackstorm.atlassian.net/browse/STORM-1020
> [RFR] Bootstrap rabbit

- contrib/examples/actions/workflows/mistral-basic.yaml
- contrib/examples/actions/workflows/mistral-handle-error.yaml
- contrib/examples/actions/workflows/mistral-repeat-with-items.yaml
- contrib/examples/actions/workflows/mistral-repeat.yaml
- contrib/examples/actions/workflows/mistral-workbook-basic.yaml
- contrib/examples/actions/workflows/mistral-workbook-complex.yaml
- contrib/examples/actions/workflows/mistral-workbook-multiple-subflows.yaml
- contrib/examples/actions/workflows/mistral-workbook-subflows.yaml
- docs/source/mistral.rst
- st2actions/st2actions/query/mistral/v2.py
- st2actions/st2actions/runners/mistral/utils.py
- st2tests/st2tests/fixtures/generic/workflows/wb_post_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wb_pre_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_post_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_pre_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/workbook_v2.yaml
- st2tests/st2tests/fixtures/generic/workflows/workbook_v2_many_workflows.yaml
- st2tests/st2tests/fixtures/generic/workflows/workbook_v2_many_workflows_no_default.yaml
- st2tests/st2tests/fixtures/generic/workflows/workflow_v2.yaml
- st2tests/st2tests/fixtures/generic/workflows/workflow_v2_many_workflows.yaml
Mistral changed YAQL delimiter from {} to <% %>.  Refactor the DSL transformer, tests, and examples accordingly.
> Rebase mistral DSL transformers, tests, and examples

- st2debug/st2debug/cmd/submit_debug_info.py
Abort if user tries to run debug tool in non-review mode and gpg binary is not available.
> st2debug improvements

- contrib/examples/actions/mistral-basic.json
- contrib/examples/actions/mistral-handle-error.json
- contrib/examples/actions/mistral-handle-retry.json
- contrib/examples/actions/mistral-repeat-with-items.json
- contrib/examples/actions/mistral-repeat.json
- contrib/examples/actions/mistral-workbook-basic.json
- contrib/examples/actions/mistral-workbook-complex.json
- contrib/examples/actions/mistral-workbook-multiple-subflows.json
- contrib/examples/actions/mistral-workbook-subflows.json
- contrib/examples/actions/workflows/mistral-handle-retry.yaml
Make the workflow and task parameters immutable so they are not displayed in CLI/UI.  Fix the retry example to run the delete-file task after the retry task.
> Fix mistral examples

- st2common/st2common/operators.py
- st2common/tests/unit/test_operators.py
- st2reactor/st2reactor/rules/filter.py
- st2reactor/tests/unit/test_filter.py
Not too happy with the changes. Things work but the op_func always assume there is a value and there is criteria_pattern. exists and nexists don't fit into this category. We'll need a better interface. I am still thinking about this.
> RFR: Add support for exists and nexists operators

- conf/st2.conf
- docs/source/install/config.rst
- st2api/st2api/app.py
- st2api/st2api/config.py
- st2api/st2api/controllers/root.py
- st2api/st2api/controllers/v1/root.py
- st2api/st2api/templates/index.html
- st2auth/st2auth/app.py
- st2auth/st2auth/config.py
- st2client/st2client/commands/action.py
- st2common/st2common/config.py
- st2common/st2common/hooks.py
- st2tests/st2tests/config.py
- tools/st2_deploy.sh
WebUi files are only served if `serve_webui` option is enabled. In documentation we will encourage users to disable this option in production and use something like nginx or Apache to serve static webui files there.
TODO:
Blocked by:
* https://github.com/StackStorm/st2incubator/pull/65
> Update st2api server to also server webui static files

- tools/st2_deploy.sh
Configured the fix by running it on a fresh Fedora 21 box.
> Fix st2_deploy.sh installation failure on Fedora 21

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2common/st2common/util/jinja.py
- st2reactor/st2reactor/rules/datatransform.py
- st2reactor/tests/unit/test_data_transform.py
Refactored render_values used in action_chain to st2common to avoid code dupes. Improved tests.
> RFR: Allow rendering of non-string parameters in rule

- contrib/linux/actions/cp.yaml
- contrib/linux/actions/mv.yaml
- contrib/linux/actions/rm.yaml
- contrib/linux/actions/scp.yaml
The trailing '-' was squashing the white space between the arguments.
> Removing suppression of white space

- docs/source/start.rst
The command:
st2 key create user stanley
does not work; the command
st2 key set user stanley
does what the description describes (creates ``user=stanley`` key-value pair)
> st2 key create user stanley -> st2 key set user stanley

- st2api/st2api/app.py
```
resp = requests.get('http://localhost:9101/v1/actions/linux%2Erm')
>>> resp = requests.get('http://localhost:9101/v1/actions/linux.mp3')
>>> print(resp.json())
{u'faultstring': u'The resource could not be found.'}
>>>
|             |         "type": "boolean",
lakshmi [17:48]
Feb 28 01:39:32 localhost st2api[17184]: ERROR 140049251479056 [-] Controller 'get_one' defined does not support content_type 'audio/x-pn-realaudio'. Supported type(s): ['application/json']
Feb 28 01:39:59 localhost st2api[17184]: ERROR 140049251479056 [-] Controller 'get_one' defined does not support content_type 'audio/mpeg'. Supported type(s): ['application/json']
```
> Disable content-type guessing from URL path in pecan app

- st2common/st2common/models/system/action.py
```
(virtualenv)~/stanley git:linux_pack_improvements ❯❯❯ st2 run linux.lsof_pids hosts=localhost pids=20430 username=stanley                                                                                                       ✭ ✱ ◼
.
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 54f0fcd10640fd02810515cc                                     |
| action.ref      | linux.lsof_pids                                              |
| context.user    | lakshmi                                                      |
| parameters      | { …
```
> More explicit error when sudo requires password for actions

- docs/source/install/index.rst
- docs/source/packs.rst
- docs/source/start.rst
* Installer - mention 'latest'.
* Packs - more details on `pacsk.load register`
* Quick Start - mention to setup virtual env when deploying examples,
or else they won't work.
> Small docs updates

- CHANGELOG.rst
- st2common/st2common/services/action.py
- st2common/st2common/util/schema/__init__.py
- st2common/tests/unit/test_json_schema.py
JSON schema doesn't support default values, so previously, is a parameter specified `required: True` and `default: "some value"`, schema validator would still fail if user didn't provide a value for this parameter.
This pull request fixes that and makes schema validator not fail in that case.
> Make action parameters schema not fail validation if required attribute specifies a default value and no value is provided

- st2common/bin/registercontent.py
- st2common/st2common/content/bootstrap.py
- tools/launchdev.sh
- tools/st2ctl
By default, register content will only output logs that has level ERROR or above. If "-v" or "--verbose" is included, the log level will change to DEBUG.
```
Examples:
st2ctl reload -v
st2ctl reload --verbose
st2ctl clean -v
st2ctl clean --verbose
```
> Add verbose flag to register content in st2ctl

- tools/st2ctl
Add basic check args to st2ctl. If check args fail, st2ctl will print usage information.
> Add check args and print usage to st2ctl

- tools/st2_deploy.sh
Fedora 21 installation was failing on the uninstall step for the packages.  This makes the grep more specific to help avoid this situation.
> More specific grep to avoid uninstalling non StackStorm packages

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
When running st2api with auth enabled, we didn't correctly preserve the username of the authenticated user who has triggered the action execution (we always just used a default value of ``stanley``).
@enykeev said he has updated a ticket with this issue, but I couldn't find the ticket.
> Correctly preserve the username of the user who has triggered the action execution

- st2tests/integration/mistral/test_wiring.py
Add coverage for the use of with-items in the mistral integration tests. The with-items statement handles action execution differently.
> Add with-items use case to mistral integration tests

- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2actions/st2actions/bootstrap/runnersregistrar.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/log.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/st2reactor/bootstrap/sensorsregistrar.py
Pull request #1173 added "log level higher than" based filtering, but this didn't really help much since most of the "offending" messages contain log level `AUDIT` and `AUDIT` level > `ERROR` level which means those messages were still logged (and there were hundreds of them).
With this pull request, we now exclude messages with level `AUDIT` and `DEBUG` when not running in `verbose` mode.
In addition to that, we now print out everything under level INFO - we still want user to know that something is indeed happening.
Imo, the default output now looks a lot more sensible:
```
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ ./st2common/bin/registercontent.py --config-file conf/st2.conf --register-all
2015-03-02 23:08:23,078 INFO [-] Connecting to database "st2" @ …
```
> Content registration message filtering improvements

- contrib/examples/actions/chains/publish_data.yaml
- contrib/examples/actions/chains/test_quickstart.yaml
- contrib/examples/actions/echochain.meta.yaml
- contrib/examples/actions/echochain_param.meta.yaml
- contrib/examples/actions/publish_data.meta.yaml
- contrib/examples/actions/test_quickstart.meta.yaml
- docs/source/actionchain.rst
- docs/source/actions.rst
- docs/source/roadmap.rst
- docs/source/start.rst
> Fixes for ActionChain docs and examples

- docs/source/rules.rst
1. Format and text - minor changes
2. Incorrect example rule path fixed
3. Since the same rule is used by Quick Start, user may get an error creating it. Added a small piece that handles this scenario
4. Moved commands that list rules into separate section (separate from creation)
5. Ordered operators by type (more or less)
6. In "long description" for a few operators was missing
(Side note: why do we need to describe operators twice? Isn't summary enough? Or is it to have static link to them?)
7. Removed reference to Getting Started (we are repeating the steps here + likely someone gets to this page after getting started
8. Rule creation removed from Rule Location section and moved rule location to be under Managing Rules
9. Moved what's next to the bottom
> Testing the page - changes

- docs/source/conf.py
Let's cross the t's on how we deploy and reference docs. 
* one docs/source/conf.py [1]
* Two build jobs.
Picture worth 1000 words. 
* <stable_version> branch cut, __versioin__ updated to new <stable_version>, e.g. from 0.9dev to 0.9.
* On master, __version__ incremented to next dev version, e.g. from 0.9dev to 0.10dev.
* Create a new s3./<stable_version> bucket and 's3/<next_version>.dev buckets
* Cut a new <stable_version> branch, switch stable build to it.
* "Build Stable" keeps building s3/root and s3/<stable_version>. s3/root now contains new stable version.
* Increment version on master to <next_version>.dev, switch master build to it. 
* "Build Master" keeps building s3/latest and s3/<next_version>.dev s3/latest now contains new latest version.
* All previous docs are intact, and …
> Fix doc version on master.

- CHANGELOG.rst
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2common/st2common/models/db/__init__.py
This pull request includes the following changes.
* Allow user to retrieve executions without the `result` attribute by passing `?exclude_result=1` query parameter to the `/actionexecutions/` endpoint.
* New endpoints:
* `GET /actionexecutions/<id>/result` - retrieve execution result object
* `GET /actionexecutions/<id>/stdout` - retrieve raw value of the execution result `stdout` attribute
* `GET /actionexecutions/<id>/stderr` - retrieve raw value of the execution result `stderr` attribute
Other changes:
* Technical debt cleanup 
* Removed awful pecan controller hackery and replaced it with nested controllers.
* Tried to remove as much as the kwargs abuse and magical code as I could.
TBW
Currently, if an action generates a lot of output (`stdout`, `stderr`), retrieving all the actions …
> Allow user to exclude result from /actionexecutions, new endpoints for retrieving execution result, stdout and stderr

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/st2client/commands/resource.py
1. We now automatically infer action type (workflow / non-workflow) when using `execution get` command. If execution refers to a workflow, `--tasks` option is implied and the output formatted accordingly. If user wants a raw (non formatted output), they can use the existing `-d` flag or a new `--raw` flag. For backward compatibility reasons, `--tasks` option wasn't removed and is still there.
2. Print an error if user uses `--tasks` option with a non-workflow action (tasks doesn't make sense there).
Example outputs - https://gist.github.com/Kami/6702083a1a05e0b47f19
> Execution get improvements - automatically infer action type from the execution and format user-friendly output accordingly

- st2actions/st2actions/query/mistral/v2.py
Mistral renamed wf_name to workflow_name and execution_id to workflow_execution_id in the task object.
> Rename attributes in mistral task entry

- CHANGELOG.rst
- st2actions/st2actions/runners/httprunner.py
- st2actions/tests/unit/test_http_runner.py
We didn't parse the body if the JSON content-type header also contained a charset.
> Fix http runner json body parsing bug

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/st2client/formatters/table.py
With fix
```
$ st2 execution get 54f8d0010640fd2d7cd58ad7
id: 54f8d0010640fd2d7cd58ad7
action.ref: default.nested_wf
start_timestamp: 2015-03-05T21:52:01.798774Z
end_timestamp: 2015-03-05T21:52:12.077042Z
+-----------------------------+-----------+------+-------------------+-------------------------------+
| id                          | status    | task | action            | start_timestamp               |
+-----------------------------+-----------+------+-------------------+-------------------------------+
| + 54f8d0010640fd2d918c93f5  | succeeded | 1    | default.simple_wf | Thu, 05 Mar 2015 21:52:01 UTC |
|    54f8d0020640fd2d918c93f8 | succeeded | 1    | core.local        | Thu, 05 Mar 2015 21:52:01 UTC |
|    54f8d0030640fd2d918c93fb | succeeded | 2    | core.local …
```
> Adjust column width

- requirements.txt
- tools/st2_deploy.sh
Update requirements.txt and st2_deploy.sh to use the st2-0.8.1 branch for mistral.
> Update mistral version to st2-0.8.1

- tools/st2_deploy.sh
Only max_pool_size is required. Not to be confused with MySQL's max connection, this setting limits each mistral process to 50 client connections.
> Update database connection settings for mistral

- st2common/st2common/fields.py
- st2common/tests/unit/test_db_fields.py
* By assigning datetime.now in case of None we end up assigning a value to end_timestamp
> [RFR] Avoid unnecessary timestamp

- test-requirements.txt
We want to use flake8 < 2.4 since newer version of flake8 pips pep8 (finally!) to a different / incompatible version we do.
This fixes build failures.
> Fix dependency conflicts

- CHANGELOG.rst
- st2common/st2common/models/system/action.py
- test-requirements.txt
As noted in https://github.com/StackStorm/st2/pull/1149#issuecomment-77754610 we return the same error message if we can't execute a command on the remote server either if we can't connect to the remote server due to an authentication issue (invalid username / password / key) or if a remote user can't execute sudo (e.g. sudo not available for that user or it requires a password)
This is of course wrong and confusing. This pull request fixes that.
As you can see, the way we check for that is really awful, but because of the way fabric works, there is no nicer way to do that. Only way to distinguish between those two errors is based on the traceback value.
See bellow for an example.
Invalid authentication information:
```
{
"xxx": {
"failed": true, 
"traceback": "  File …
```
> Distinguish between invalid auth info and missing passwordless sudo remote runner error

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2client/st2client/commands/action.py
- test-requirements.txt
This pull request includes two fixes.
1. Throw a more user-friendly error if action chain runner fails to parse definition file
Before:
```bash
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 54fc88440640fd0b9e5de1ed                                     |
| action.ref      | bsides.information_collection                                |
| context.user    | stanley                                                      |
| parameters      |                                                              |
| status          | failed …
```
> Throw a more user-friendly error is action chain runner fails to parse definition file, report top-level errors in the CLI better

- CHANGELOG.rst
- contrib/examples/actions/chains/publish_data.yaml
- contrib/examples/actions/publish_data.meta.yaml
- docs/source/actionchain.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_publish.json
- test-requirements.txt
Previously, user was unable to access action parameters inside the "publish" scope. This limitation made any things harder.
Here is an example of a work-flow where I use this functionality:
Metadata:
```yaml
...
parameters:
ip_address:
type: "string"
description: "IP address of a remote server to collect the informatiom from"
required: true
```
Workflow:
```yaml
---
chain:
-
name: "create_temporary_directory"
ref: "core.remote_sudo"
params:
hosts: "{{ ip_address }}"
cmd: "mktemp -d"
publish:
temp_dir: "{{ create_temporary_directory[parameters.ip_address].stdout }}"
on-success: "retrieve_logged_users"
...
```
TODO:
> [RFR] Update action chain runner - allow users to access action parameters inside "publish" scope

- tools/visualize_action_chain.py
I had this script laying around locally for a while now. I decided to clean it up a bit and add it to the repo.
I believe james created a similar thing so it might make sense to combine those scripts together.
Generated visualization file looks like this ([here](https://github.com/Kami/stackstorm-bsides-demo/blob/master/packs/bsides/actions/workflows/information_collection.yaml) is a work-flow used as an input):
> Add a script for visualizing action chain workflows

- CHANGELOG.rst
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/unit/test_pythonrunner.py
Note: If we plan to get 0.8.2 out today, we should also include this bug fix.
> Fix stdout reporting and interception for python runner actions

- CHANGELOG.rst
- st2actions/tests/unit/test_fabricrunner.py
- st2common/st2common/models/system/action.py
- st2common/tests/unit/test_action_system_models.py
The runner ignored environment variables and authentication settings supplied as parameters (it always just used default global authentication settings).
We should also get this into the 0.8.2 release.
> Fix a bug in the run-remote-script runner

- st2actions/st2actions/worker.py
- st2actions/tests/unit/test_worker.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/db/action.py
- st2common/st2common/services/executions.py
- st2common/st2common/util/action_db.py
- st2common/st2common/util/system_info.py
- st2common/tests/unit/test_system_info.py
* runner_info is now included in the execution result. This helps track the runner an action executed on.
```
st2 execution get 54ff64460640fd0be8d21030 -dj
{
"action": {
"ref": "core.local"
},
"context": {
"user": "stanley"
},
"end_timestamp": "2015-03-10T21:38:14.788372Z",
"id": "54ff64460640fd0be8d21030",
"liveaction": {
"action": "core.local",
"callback": {},
"id": "54ff64460640fd0be8d2102f",
"runner_info": {
"hostname": "vagrant-ubuntu-trusty-64",
"pid": 3071
}
},
"parameters": {
"cmd": "date"
},
"result": {
"stderr": "",
"stdout": "Tue Mar 10 21:38:14 UTC 2015\n",
"succeeded": true
},
"start_timestamp": "2015-03-10T21:38:14.411289Z",
"status": "succeeded"
}
```
* Add some logs to help track start of an ActionExecution.
* Added some more tests.
> Execution tracking

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_invalid_action.json
Previously this was also considered as a task error, but now it bubbles up as a top-level action-chain error. This way it's consistent with the way we handle other action-chain errors (/cc @manasdk).
Before:
```bash
id: 550068e70640fd6ed48e7513
action.ref: bsides.notify_administrators
status: failed
start_timestamp: 2015-03-11T16:10:15.662128Z
end_timestamp: 2015-03-11T16:10:15.836978Z
result: 
{
"tasks": [
{
"name": "retrieve_archive_cdn_url_from_datastore", 
"workflow": null, 
"created_at": "2015-03-11T16:10:15.826694+00:00", 
"updated_at": "2015-03-11T16:10:15.835345+00:00", 
"state": "failed", 
"result": {
"traceback": "Traceback (most recent call last):
File "/data/stanley/st2actions/st2actions/runners/actionchainrunner.py", line 190, in run
params=resolved_params)
File …
```
> Report a more user-friendly error if action-chain task references an invalid action ; report a top level error

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2common/st2common/content/loader.py
Previously you got a really confusing error if workflow definition contained an invalid type.
We have similar problem in other places and that's a stop gap solution for now. Ideally, we would also leverage json / yaml schema for that.
Before:
```bash
id: 5500776b0640fd6ed48e7529
action.ref: bsides.notify_administrators
status: failed
start_timestamp: 2015-03-11T17:12:11.202264Z
end_timestamp: 2015-03-11T17:12:11.821527Z
result: Message: type object argument after ** must be a mapping, not list
Traceback:   File "/data/stanley/st2actions/st2actions/container/base.py", line 100, in _do_run
runner.pre_run()
File "/data/stanley/st2actions/st2actions/runners/actionchainrunner.py", line 138, in pre_run
raise runnerexceptions.ActionRunnerPreRunError(message) …
```
> Throw a more user-friendly error if action chain definition contains invalid type

- CHANGELOG.rst
- st2actions/st2actions/runners/fabricrunner.py
run-remote-script actions without entry_point don't make sense.
This would save @jfryman and I at least 30 minutes :P
Before:
```bash
id: 5500c10d0640fd0d53077989
status: failed
result: 
{
"xxx": {
"failed": true, 
"traceback": "  File "/data/stanley/st2common/st2common/models/system/action.py", line 395, in _sudo
'return_code': output.return_code,
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/fabric/network.py", line 639, in host_prompting_wrapper
return func(*args, **kwargs)
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/fabric/operations.py", line 1095, in sudo
stderr=stderr, timeout=timeout, shell_escape=shell_escape,
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/fabric/operations.py", line 895, in _run_command …
```
> Throw if a run-remote-script action is missing an entry_point parameter

- st2client/st2client/commands/action.py
Before
```
root@vm-st2-03:/home/stackstorm/repo/maestro/packs/citeis-test/actions# st2 run cities-test.run_load_modified -h
ERROR: Unable to print help for action "cities-test.run_load_modified". 'NoneType' object has no attribute 'runner_type'
root@vm-st2-03:/home/stackstorm/repo/maestro/packs/citeis-test/actions#
```
After
```
(virtualenv)~/st2 git:STORM-1174/fix_bug_in_cli_run_help ❯❯❯ st2 run core.locale -h
Action "core.locale" is not found. Do "st2 action list" to see list of available actions.
(virtualenv)~/st2 git:STORM-1174/fix_bug_in_cli_run_help ❯❯❯
```
> RFR: Raise ResourceNotFound execption if action not found

- st2common/st2common/models/api/base.py
Fix for #1261 - now we use debug log level instead.
> Don't log an exception and traceback in st2auth on invalid credentials

- tools/purge_executions.py
```
(virtualenv)~/st2 git:STORM-1146/purge_execs_ops_tool ❯❯❯ tools/purge_executions.py --timestamp "2015-03-16T14:31:59.702134Z"
Purging executions older than timestamp: 2015-03-16T14:31:59.702134Z
(virtualenv)~/st2 git:STORM-1146/purge_execs_ops_tool ❯❯❯ tools/purge_executions.py --timestamp "2015-03-16T14:31:59.702134Z"
Purging executions older than timestamp: 2015-03-16T14:31:59.702134Z
(virtualenv)~/st2 git:STORM-1146/purge_execs_ops_tool ❯❯❯
```
> RFR: Tool to purge executions older than some timestamp

- docs/source/actionchain.rst
Minor changes... `parameters` -> `params`.
> Syntax fixes in ActionChain documentation

- docs/source/install/config.rst
- st2actions/conf/logging.conf
- st2actions/conf/logging.resultstracker.conf
- st2api/conf/logging.conf
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/actions.py
- st2api/st2api/controllers/v1/actionviews.py
- st2api/st2api/controllers/v1/datastore.py
- st2api/st2api/controllers/v1/executionviews.py
- st2api/st2api/controllers/v1/rules.py
- st2api/st2api/controllers/v1/runnertypes.py
- st2api/st2api/controllers/v1/stream.py
- st2api/st2api/controllers/v1/triggers.py
- st2api/st2api/controllers/v1/webhooks.py
- st2api/tests/unit/controllers/v1/test_stream.py
- st2auth/conf/logging.conf
- st2auth/st2auth/controllers/access.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/log.py
- st2common/st2common/logging/filters.py
- st2common/st2common/logging/formatters.py
- st2common/st2common/logging/handlers.py
- st2common/st2common/models/api/base.py
- st2common/st2common/util/misc.py
- st2common/tests/unit/test_logger.py
- st2common/tests/unit/test_model_base.py
- st2reactor/conf/logging.rulesengine.conf
- st2reactor/conf/logging.sensorcontainer.conf
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
This pull request introduces support for structured log messages with additional context information.
Structured logs by itself are really not all that useful if you just wrap `message` attribute in a JSON object. They become more useful when you include additional contextual information (you can then query, filter, etc. based on the presence and value of those additional attributes / contextual information).
I've considered using `structlog` and discussed it with @lakshmi-kannan, but I believe the custom formatters + extra attribute approach I went with is better in this case. We already use logging module from Python stdlib and this approach just builds on top of that.
All of the existing logging code and infrastructure (filters, formatters, handlers, etc.) will still work. If we want …
> [RFC] [WIP] Structured logging with contexual information

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/delete.py
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- contrib/packs/actions/pack_mgmt/unload.py
- st2actions/st2actions/runners/python_action_wrapper.py
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/unit/test_pythonrunner.py
- st2common/st2common/content/utils.py
Previously packs.setup_virtualenv command didn't work correctly if user used multiple packs search paths (`content.packs_base_paths` setting).
> Fix packs.setup_virtualenv so it works correctly if user specified multiple packs search paths

- CHANGELOG.rst
- st2common/st2common/exceptions/sensors.py
- st2reactor/bin/st2sensorcontainer
- st2reactor/st2reactor/cmd/sensormanager.py
- tools/st2ctl
```
(virtualenv)~/st2 git:STORM-1153/sensor_container_messages ❯❯❯ virtualenv/bin/python ./st2reactor/bin/st2sensorcontainer --config-file conf/st2.conf --sensor-name=GitCommitSensor
2015-03-19 20:19:25,836 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-03-19 20:19:26,052 INFO [-] Registering exchanges...
2015-03-19 20:19:26,227 INFO [-] registered exchange st2.execution.
2015-03-19 20:19:26,293 INFO [-] registered exchange st2.liveaction.
2015-03-19 20:19:26,325 INFO [-] registered exchange st2.trigger.
2015-03-19 20:19:26,339 INFO [-] registered exchange st2.trigger_instances_dispatch.
2015-03-19 20:19:26,483 INFO [-] Found 0 sensors.
2015-03-19 20:19:26,484 ERROR [-] Sensor GitCommitSensor not found in db.
File …
```
> RFR - Fix exit_codes returned by SensorContainer

- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
This PR fixes a typo in the file list for the st2common RPM spec files.
> Fixed path /usr/share/stackstorm in file list

- CHANGELOG.rst
- conf/st2.conf
- st2common/st2common/util/api.py
- st2common/tests/unit/test_util_api.py
- st2debug/tests/integration/fixtures/configs/st2.conf
- st2reactor/st2reactor/container/process_container.py
- st2tests/conf/st2.conf
Previously, sensors used api listen host and port setting to obtain a public URL to the API.
Obviously this wasn't a good idea and it wouldn't work if sensor container ran on a different host or similar (well, you could get it to work, but you would need to use different values for `api.host` setting on different servers which is nasty). This pull request fixes that and makes it use `auth.api_url` setting.
This way it's also consistent with other code and we only have one placed where a public URL to the API is configured.
Installation documentation already mentions that this setting needs to be configured correctly because it's also used in other places so no changes are needed there.
> [0.8.3] Fix api url used by sensors

- docs/source/rules.rst
Here is a first pass at changes for the Rules page. My goal here is to ensure that there is a basic flow to each of the pages:
* Detailed description of each section
* Deep dive into context specific sections
This adds a beginning section that describes each portion of a rule in greater depth, hopefully providing additional context to users.
I also intend to rip out the part in this document with built-in sensors, and create a cross-link. However, leaving for now to limit scope. 
:eyes: and :book: appreciated.
> Flow/Grammar changes for Rules

- CHANGELOG.rst
- conf/st2.dev.conf
- conf/st2.prod.conf
- st2common/st2common/triggers.py
This PR suppresses logs such as 
```
2015-03-18 12:05:19,221 140286007899952 WARNING triggers [-] TriggerType creation of TriggerTypeAPI[payload_schema={u'type': u'object', u'properties': {u'status': {}, u'start_timestamp': {}, u'parameters': {}, u'action_name': {}, u'result': {}, u'execution_id': {}}}, pack=u'core', description=u'Trigger encapsulating the completion of an action execution.', name=u'st2.generic.actiontrigger'] failed with uniqueness conflict. Exception : Tried to save duplicate unique keys (E11000 duplicate key error index: st2.trigger_type_d_b.$pack_1_name_1  dup key: { : "core", : "st2.generic.actiontrigger" })
2015-03-18 12:05:19,222 140286007899952 ERROR base [-] API call failed.
File …
```
> RFR: GET /triggertypes before POST /triggertypes for internal ones

- conf/st2.dev.conf
- conf/st2.prod.conf
- docs/source/authentication.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/install/deploy.rst
- docs/source/install/index.rst
- docs/source/upgrade_notes.rst
- tools/st2_deploy.sh
> Update st2_deploy to configure authentication service with test credentials

- st2common/st2common/models/system/action.py
rm -f the script. This might fix the problem we are seeing in st2build001.
> Fabric capture stderr stdout in logs.

- tools/st2_deploy.sh
St2 now ships with auth on by default.  We need to get a token in order for the test command to work.
> Added auth token to deploy script

- CHANGELOG.rst
- st2common/st2common/util/action_db.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
```
(virtualenv)~/st2 git:remove_obnoxious_error_log_runner_not_found ❯❯❯ ST2_CONF=~/st2.dev.conf tools/launchdev.sh startclean                                                                                                        ✭ ◼
MongoDB shell version: 2.6.3
connecting to: st2
[object Object]
Starting all st2 servers...
Changing working directory to /home/lakshmi/st2/tools/.....
Using st2 config file: /home/lakshmi/st2.dev.conf
Using content packs base dir: /opt/stackstorm/packs
There are screens on:
30711.st2-sensorcontainer	(03/26/2015 11:13:18 PM)	(Detached)
30705.st2-actionrunner	(03/26/2015 11:13:18 PM)	(Detached)
2 Sockets in /var/run/screen/S-lakshmi.
Killing existing st2 screen sessions...
Starting screen session st2-api...
Starting screen session st2-actionrunner...
starting …
```
> RFR: Cleanup registration logs for actions and rules

- CHANGELOG.rst
- docs/source/cli.rst
- st2client/st2client/commands/access.py
This way we can simply use this option when retrieving a token inside different scripts (it's more robust and less fragile than awk foo :))
Note: Sadly we will only be able to switch to using this flag once 0.9 is out.
```bash
st2 auth test1 -p testpassword
+----------+----------------------------------+
| Property | Value                            |
+----------+----------------------------------+
| user     | test1                            |
| token    | a9dae5a11b0542f7a9110da2176d26e7 |
| expiry   | 2015-03-28T17:31:06.274051Z      |
+----------+----------------------------------+
st2 auth test1 -p testpassword -t
0280826688c74bb9bd541c26631df298
```
> Add "-t" / "--only-token" option to the st2 auth command

- st2common/st2common/logging/formatters.py
- st2common/tests/unit/test_logger.py
This pull request updates GELF log formatter to use a custom JSON encoder which knows how to serialize objects.
Previously we didn't do that so `json.dumps` call would fail if `extra` attribute contained an object.
TODO:
> Fix GelfLogFormatter so it knows how to serialize objects

- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2actions/st2actions/bootstrap/runnersregistrar.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/base.py
- st2common/st2common/services/triggers.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/tests/fixtures/packs/pack_with_rules/rules/rule_with_the_same_timer.yaml
- st2reactor/tests/fixtures/packs/pack_with_rules/rules/rule_without_action.yaml
- st2reactor/tests/unit/test_sensor_and_rule_registration.py
Model validation is rather expensive operation that is only needed in a limited number of cases (usually, when we add new documents to the system).
Right now, we are revalidating all the actions and executions we return during GET requests. This drastically affects response time (up to several seconds of TTFB) harming usability in a major way.
This patch would require us to explicitly validate every model manually the moment it is created.
The patch resulting in 2x reduction of response time for `limit=50` over the collection of 1214 action execution records and 10x reduction for the whole collection of 363 actions.
> Make model validation optional

- st2client/st2client/commands/action.py
- st2client/st2client/models/core.py
```
$ st2 execution cancel 552bfe2332ed3539b8a2b849
Action cannot be canceled. State = succeeded.
```
```
st2 execution cancel 552c1ab932ed3540af5d6e4f
Action cannot be canceled. State = failed.
```
```
$ st2 execution cancel 552c1d3732ed3540af5d6e52
Action is already in "canceled" state.
```
```
$ st2 execution cancel 552c1e4932ed3540af5d6e54
action execution with id 552c1e4932ed3540af5d6e54 canceled.
```
> st2 execution cancel <id>

- conf/logrotate.conf
This PR introduces a logrotate file that will eventually be placed on systems to encourage good health and hygiene of logs on a system.
Things I don't love:
* Restarting components: Can't `HUP` currently and let go of file descriptors for old log files. As such, a component restart is in order. But, I don't necessarily want to restart the entire component just to release a log file.
* ActionRunner PID files: This is interesting... old log files from runners will just collect here because two new log files are created for each runner. I'm doing some ops trickery there to cleanup old files, but also ugly.
> [COMMENT] Logrotate Rules

- tools/st2-inject-trigger-instances.py
```
---
'st2.load.test1':
k1: "v1"
k2: "v2"
'st2.load.test2':
k3: "v3"
k4: "v4"
```
```
(virtualenv)~/st2 git:load_test_tools ❯❯❯ tools/st2-inject-trigger-instances.py --rate=5 --duration=1 --schema_file=load-test-triggers.yaml
Triggers=['st2.load.test1', 'st2.load.test2']
st2.load.test1: Emitted 142 triggers in 1 seconds
st2.load.test2: Emitted 125 triggers in 1 seconds
(virtualenv)~/st2 git:load_test_tools ❯❯❯
```
> RFR: Load test tools - Inject trigger instances into st2. 

- CHANGELOG.rst
- conf/logrotate.conf
- docs/source/install/config.rst
- st2actions/conf/logging.conf
- st2actions/conf/logging.notifier.conf
- st2actions/conf/logging.resultstracker.conf
- st2actions/st2actions/cmd/actionrunner.py
- st2actions/st2actions/cmd/st2notifier.py
- st2actions/st2actions/cmd/st2resultstracker.py
- st2api/conf/logging.conf
- st2api/st2api/cmd/api.py
- st2auth/conf/logging.conf
- st2common/st2common/logging/misc.py
- st2common/st2common/signal_handlers.py
- st2reactor/conf/logging.rulesengine.conf
- st2reactor/conf/logging.sensorcontainer.conf
- st2reactor/st2reactor/cmd/rulesengine.py
- st2reactor/st2reactor/cmd/sensormanager.py
- tools/st2ctl
With this pull request all the Python service processes now re-open log files when receiving `SIGUSR1` signal.
To test it start the st2api service and run the commands listed bellow.
Screen 1:
```bash
tail -F logs/st2api.log
```
Screen 2:
```bash
python ./st2client/st2client/shell.py runner list - you should see new messages in the log file
rm logs/st2api.log
python ./st2client/st2client/shell.py runner list - you should see no new messages in the log file since the process is still referencing the old file handle
kill -USR1 <st2api pid>
python ./st2client/st2client/shell.py runner list - you should see new messages in the log file because SIGUSR1 causes process to reopen the log files
```
TODO:
> Re-open log files on SIGUSR1 signal

- contrib/tests/actions/chains/test_packs_pack.yaml
- contrib/tests/actions/test_packs_pack.meta.yaml
Tests almost all actions on packs page, except for:
- st2 run packs.install register=all repo_url=https://github.com/StackStorm/st2incubator.git - installing all packs as part of sanity seems too much
- st2 run packs.restart_component servicename=st2sensorcontainer - I didn't find the way to reliably test that this action does something
- st2 action list --pack=docker, st2 sensor list --pack=docker, st2 trigger list --pack=docker - since they are not parts of packs pack
> Added test_packs_pack

- contrib/examples/actions/workflows/mistral-workbook-complex.yaml
- st2actions/st2actions/handlers/mistral.py
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2.py
- st2tests/integration/mistral/test_wiring.py
Mistral added an action execution endpoint. Action result should be posted as output to the action execution endpoint instead of the task endpoint.
> Fix mistral callback handler

- st2common/packaging/rpm/st2common.spec
We need to create /etc/logrotate.d in the buildroot.
> added mkdir for logrotate.d

- conf/st2.conf.sample
- st2actions/st2actions/notifier.py
- st2api/st2api/controllers/exp/aliasexecution.py
- st2api/tests/unit/controllers/exp/test_action_alias.py
- st2api/tests/unit/controllers/exp/test_alias_execution.py
- st2common/st2common/config.py
- st2common/st2common/content/aliasesregistrar.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/content/loader.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/db/action.py
- st2common/tests/unit/test_aliasesregistrar.py
- st2tests/st2tests/fixtures/aliases/aliases/alias1.yaml
- st2tests/st2tests/fixtures/aliases/aliases/alias2.yaml
- st2tests/st2tests/fixtures/aliases/aliases/alias3.yaml
- st2tests/st2tests/fixtures/dummy_pack_1/aliases/alias1.yaml
- st2tests/st2tests/fixtures/dummy_pack_1/aliases/alias2.yaml
- st2tests/st2tests/fixturesloader.py
- No need to change the Action metadata to inclued channel and message.
- User is also pass through the notifications system.
> Chatops alias updates

- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2.py
When auth is turned on, in order for Mistral to be able to launch st2 actions, the API calls to st2 from Mistral requires a token. The runner container generates a temporary token for authenticated calls. This auth token is passed to Mistral under st2_context in the environment on workbook and workflow execution.
> Pass runner generated auth token to Mistral

- tools/st2_deploy.sh
The change is fully backward compatible since we default to installing mistral by default, but user now has a chance to opt-out.
> Allow user to skip mistral installation when using st2_deploy

- docs/source/auth_usage.rst
Since almost each installation page will require similar explanation, I am moving this fragment into separate page, to include into multiple pages
> Added auth_usage fragment to be used with various pages

- docs/source/authentication.rst
The paragraph about authentication usage is useful for multiple pages; thus moved it to the separate page and including here
> Changed the page to use auth_usage.rst

- tools/self-check
- tools/st2-setup-examples
- tools/st2-setup-tests
- tools/st2_deploy.sh
This adds an installs script for the examples pack and fixes a path issue on the tests install script.  A self-check script was also added.  The self-check script runs all of the tests in the tests pack.
Sample output of self-check:
```
root@st2stage201:/home/phool# ./self-check 
Attempting Test tests.test_packs_pack...OK!
Attempting Test tests.test_quickstart...OK!
Attempting Test tests.test_quickstart_key...OK!
Attempting Test tests.test_quickstart_rules...OK!
SUCCESS: All tests passed!
```
> Examples installer & self-check v1

- st2actions/st2actions/runners/windows_script_runner.py
- st2actions/tests/fixtures/windows/net_share_C_stdout.txt
- st2actions/tests/unit/test_windows_runners.py
Previously, the path was hard-coded to "C:\\" so it would only work with shares which shared the whole C drive.
This pull request fixes that and it now works with an arbitrary directory or drive share.
> Use full absolute path to the share directory in the Windows script runner

- requirements.txt
Since `linux` is now a system pack, we need it's requirements to be part of system requirements. This is definitely a work around for now. We need to come up with a better way to ship packs with st2.
> RFR: Add linux pack requirements to st2 requirements

- st2tests/integration/mistral/base.py
If multiple tasks are specified for on-error task defaults and fail is in the list, the WF will fail immediately without waiting for the other tasks to finish.
> Fix mistral test case where task status is not updated yet

- st2client/st2client/commands/resource.py
- st2client/st2client/shell.py
Previously (with auth enabled):
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ python ./st2client/st2client/shell.py execution get 1
Action Execution "1" is not found.
```
Now:
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ python ./st2client/st2client/shell.py execution get 1
ERROR: 401 Client Error: Unauthorized
MESSAGE: Unauthorized
```
> Correct propagate "unauthorized exceptions" in the CLI "get" commands

- contrib/examples/actions/chains/publish_data.yaml
This PR changes the default port in one of the example ActionChain workflows from `:9101`, being served via `st2api` to `:8080`, which is the listener port for `st2web`.
/cc https://github.com/StackStorm/st2/pull/1362
> Update ActionChain Example with new HTTPServer Port

- st2client/st2client/commands/action.py
The auth token is not passed to underlying functions in the `st2 execution get` command in the CLI.
> Pass auth token to underlying functions in st2 execution get

- CHANGELOG.rst
- st2actions/st2actions/cmd/actionrunner.py
- st2common/st2common/constants/triggers.py
- st2common/st2common/triggers.py
- st2common/tests/unit/test_internal_trigger_types_registrar.py
- st2reactor/st2reactor/cmd/sensormanager.py
- st2tests/st2tests/base.py
With this, also refactored code into a class. Config is not read during import time. This should save us from import dependencies. 
Seems to work in dev env. I am going to see if I can add some tests for the class. 
```
~/st2 git:master ❯❯❯ mongo                                                                                             ✭ ✱ ◼
MongoDB shell version: 2.6.3
connecting to: test
> use st2
switched to db st2
> show db.trigger_d_b.find()
2015-04-28T05:39:10.278+0000 don't know how to show [db.trigger_d_b.find()] at src/mongo/shell/utils.js:729
> show db.trigger_d_b.find()
2015-04-28T05:39:13.094+0000 don't know how to show [db.trigger_d_b.find()] at src/mongo/shell/utils.js:729
> db.trigger_d_b.find()
{ "_id" : ObjectId("553f1cd56d0aff6cae840d2b"), "name" : "polling_event", …
```
> RFR - Use Authed APIs for internal trigger registration

- st2client/st2client/utils/httpclient.py
* Specifying ST2_AUTH_URL and ST2_API_URL with or without trailing slash has no impact
on the behavior. Previously Specifying a trailing slash would cause st2client to
fail.
> Make url in st2client trailing slash agnostic

- st2tests/integration/mistral/test_examples.py
Due to the way how Mistral handles task defaults for on-error, the notify task can still be in RUNNING state even though the WF is completed.
> Fix the test_handle_error test

- st2actions/st2actions/runners/windows_command_runner.py
- st2actions/st2actions/runners/windows_script_runner.py
Create a new PIPE for stdin in the Windows runners.
Note: We don't actually send anything over this PIPE, this is just a work-around for an obscure failure.
> Workaround for stdin bug in Windows runners

- contrib/packs/actions/download.yaml
- contrib/packs/actions/pack_mgmt/download.py
The recommended behavior is to have all certificates checked for
validity before performing a clone. However, there are times when
this is outright not possible (development with a self-signed cert,
for example).
This commit updates the `packs.download` command, introducing a new
attribute `verifyssl`. By default, the behavior is to continue checking
SSL certificate validity, but now it is possible to clone with an
invalid certificate and proceed along without a care in the world.
Be careful using this... especially in the context of Infra as Code.
> Allow option to bypass SSL Certificate Check

- st2auth/conf/apache.sample.conf
Based on IRC report from @chrisssss.
In previous version, st2common.logging and st2auth.cmd had more priority than python's own cmd.py and logging.py which resulted in problems with Pecan.core and PDB modules.
Also, to avoid authentication being applied to preflight requests, we need to make an exception for OPTIONS requests.
Other common problems include an absence of `stanley` group and lack of privileges to write into log folder, though it seems they should be addressed on a case-by-case basis.
> Update apache config sample

- contrib/packs/actions/pack_mgmt/download.py
We didn't propagate `verifyssl` argument to the _clone_repo method.
> Fix broken packs.download action

- docs/source/webhooks.rst
Clarify (with an example) how to match on the trigger payload which is emitted by a generic or a custom webhook trigger inside a rule criteria.
> Webhook trigger payload clarification improvements

- CHANGELOG.rst
- st2reactor/st2reactor/rules/enforcer.py
Before this change:
```bash
015-05-07 16:56:17,262 140034745491280 ERROR engine [-] Exception enforcing rule RuleDB(action=ActionExecutionSpecDB@140034739839824(ref="sdlcm", parameters="{u'change': u'{trigger.body.change}'}"), criteria={u'trigger.body.change': {u'pattern': u'', u'type': u'exists'}}, description="firing the CR submit case from /v1/webhooks/Sdlcm/sdlcm", enabled=True, id=554a7b0b0ba1603bd4571511, name="wh_sdlcm", tags=[], trigger="core.7bfd8485-8c52-4778-ab9e-ae247c1217dd"): 'NoneType' object has no attribute 'parameters'
File "/usr/lib/python2.7/dist-packages/st2reactor/rules/engine.py", line 59, in enforce_rules
enforcer.enforce()  # Should this happen in an eventlet pool?
File "/usr/lib/python2.7/dist-packages/st2reactor/rules/enforcer.p …
```
> Throw a better error when enforcing a rule if referenced action doesn't exist

- .travis.yml
- Makefile
- scripts/travis.sh
With this pull request we now also build documentation on Travis. In addition to that, I split things out so we now run 4 builds in parallel (flake8, pylint, docs, tests) instead of running everything sequentially in a single build.
Well, in reality we now actually run 8 builds because we run every task under Python 2.6 and 2.7 (2 x 4), but I will optimize this once we switch to tox (the way Travis works it's not possible to do that without something like tox).
This means the builds should now complete faster (fingers crossed).
> Optimize and speed up Travis builds

- st2auth/conf/htpasswd_dev
st2.dev.conf references it but the file was not included in the repo.
> Add missing st2auth dev httpasswd file

- st2client/st2client/models/core.py
I plan to use this functionality inside actions inside the ``st2`` pack. Returning actual Python objects from the ``st2`` actions makes little sense since common currency in StackStorm (workflows, etc). are simple types + dict and you can't do anything with those custom objects before converting them to a dictionary.
If you think this should really only leave in st2 pack, I can also move it there.
> Add "to_dict" method to the Resource class

- .travis.yml
- scripts/travis.sh
Builds should now complete even faster.
If there is ever an issue with cache some how getting corrupted, pip should automatically take care of it, but if it doesn't, you can manually nuke it on this page  - https://travis-ci.org/StackStorm/st2 (Settings -> Cache).
> Cache pip packages in Travis

- st2common/st2common/hooks.py
Recent API refactoring probably accidentally removed (or didn't add back) this part.
Without a traceback, most of the errors are pretty much useless.
Before:
```bash
015-05-11 18:20:03,463 DEBUG [-] API call failed: object of type 'NoneType' has no len()
2015-05-11 18:20:03,463 INFO [-] POST /exp/aliasexecution result={
"faultstring": "Internal Server Error"
} (remote_addr='127.0.0.1',method='POST',result='{\n    "faultstring": "Internal Server Error"\n}',status_code='500 Internal Server Error',path='/exp/aliasexecution')
```
After:
```bash
2015-05-11 18:26:19,155 DEBUG [-] Traceback (most recent call last):
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/pecan/core.py", line 625, in __call__
self.invoke_controller(controller, args, kwargs, state)
File …
```
> Log traceback on API error

- CHANGELOG.rst
- Makefile
- st2actions/st2actions/resultstracker.py
- st2common/st2common/models/db/reactor.py
- st2reactor/tests/unit/test_rule_matcher.py
Previously, rules engine would explode if a TriggerInstance dictionated payload contained a dot or $ in the key name.
```bash
640fd7215ce2f1a', u'end_timestamp': u'2015-05-11T21:33:10.971247Z'}}, 'execution_id': '555124210640fd7d31ab0409'}}
File "/data/stanley/st2common/st2common/transport/consumers.py", line 59, in _process_message
self._handler.process(body)
File "/data/stanley/st2reactor/st2reactor/rules/worker.py", line 32, in process
datetime.datetime.utcnow())
File "/data/stanley/st2reactor/st2reactor/container/utils.py", line 62, in create_trigger_instance
return TriggerInstance.add_or_update(trigger_instance)
File "/data/stanley/st2common/st2common/persistence/base.py", line 83, in add_or_update
model_object = …
```
> Allow dots in trigger instance payload (bug fix)

- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
:cherries:-pick of https://github.com/StackStorm/st2/commit/92063f8347b356c483fdb48310d34387e0767a76.
> Fix a bug with alias parser - make sure it works correctly with the default values and also works if param_stream is none or not provided (we should still parse format stream in that case).
> Fix a bug with alias parser

- CHANGELOG.rst
- docs/source/auth_usage.rst
- st2auth/st2auth/controllers/access.py
- st2auth/tests/unit/test_token.py
- st2common/st2common/exceptions/access.py
- st2common/st2common/services/access.py
Fixes: https://github.com/StackStorm/st2/issues/1467
```
(virtualenv)~/st2 git:ttl_greater_than_max ❯❯❯ st2 auth -p <hidden> testu -l 5000000                                       ✭ ✱ ◼
MESSAGE: TTL specified 5000000 is greater than max allowed 86400.
(virtualenv)~/st2 git:ttl_greater_than_max ❯❯❯
```
```
(virtualenv)~/st2 git:ttl_greater_than_max ❯❯❯ st2 auth -p <hidden> testu -l 10                                            ✭ ✱ ◼
+----------+----------------------------------+
| Property | Value                            |
+----------+----------------------------------+
| user     | testu                            |
| token    | 0cc9261fc08c419294576f22cf15e0ca |
| expiry   | 2015-05-12T17:17:52.196630Z      | …
```
> RFR: Return HTTP BAD REQUEST when TTL requested for token > Max configured TTL

- contrib/examples/actions/echochain.meta.yaml
- st2actions/st2actions/bootstrap/runnersregistrar.py
- st2actions/st2actions/container/base.py
- st2actions/st2actions/runners/__init__.py
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
Without skip_notify:
```
~/st2 git:chain_inherit_notifications ❯❯❯ st2 run examples.echochain                                                  ⏎ ✭ ✱ ◼
..
id: 555223ff6d0aff6d610ca22f
action.ref: examples.echochain
start_timestamp: 2015-05-12T16:02:07.610206Z
end_timestamp: 2015-05-12T16:02:10.853135Z
+--------------------------+-----------+------+------------+----------------------+
| id                       | status    | task | action     | start_timestamp      |
+--------------------------+-----------+------+------------+----------------------+
| 555223ff6d0aff6d6779609b | succeeded | c1   | core.local | Tue, 12 May 2015     |
|                          |           |      |            | 16:02:07 UTC         |
| 555224006d0aff6d6779609f | succeeded | c2   | core.local …
```
> RFR - Tasks in action chain inherit notify from chain

- CHANGELOG.rst
- st2common/st2common/util/casts.py
- st2common/tests/unit/test_casts.py
We serialize arrays to strings using two different approaches - either as JSON or raw Python string, same as we do with dicts.
The problem with that is, that we didn't take JSON serialization into account when casting a parameter for an action which means things would blow up and not work if you passed in array serialized as JSON.
TODO:
> Fix handling of arrays which are passed as string inside the action-chain workflows

- docs/source/start.rst
Datastore was embedded in the Define a rule section, although it seems quite independent. Instead, I separated it to be a separate subsection (also referencing it in the https://github.com/StackStorm/st2/blob/master/contrib/tests/README.md)
> Separated more visibly a Datastore section of quick start

- CHANGELOG.rst
- contrib/examples/actions/chains/echochain_task_failure.yaml
- contrib/examples/actions/chains/echochain_top_level_failure.yaml
- contrib/examples/actions/echochain_task_failure.meta.yaml
- contrib/examples/actions/echochain_top_level_failure.meta.yaml
- st2actions/st2actions/worker.py
- st2client/st2client/commands/action.py
- st2client/st2client/models/core.py
In short this saves everyone an additional command (previously you needed to run `execution get` to retrieve the error message and the error and traceback attributes were also "hidden" among other data).
Before:
After (top level workflow failure):
After (task level workflow failure):
This partly solves #1315, but not fully. We still need to account for a case when there is no top level error but a task fails. I will make that change shortly.
> Display error message when running an execution when a workflow action fails

- CHANGELOG.rst
- st2actions/st2actions/notifier.py
- st2actions/tests/unit/test_notifier.py
We don't want to expose LiveAction id to users. LiveAction is an internal data model. This PR fixes that. 
I went with the approach to consume Execution updates from queue but decided against it because we want the system to deal with LiveAction objects which are there for this purpose. This minimizes the chance of us messing up the execution object. 
We can port this to 0.9.1.
> Notify & action triggers should contain Execution id as opposed to LiveAction id.

- st2actions/st2actions/notifier.py
- st2actions/tests/unit/test_notifier.py
* Including the payload means client can use this info to better understand
the results.
> Include runner_ref in the notification trigger payload.

- docs/source/actions.rst
- docs/source/runners.rst
According to [RUNNER_TYPES](https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/bootstrap/runnersregistrar.py#L62) there are no such Action Runners like [`local-script-cmd`](https://github.com/StackStorm/st2/blob/master/docs/source/runners.rst#local-command-runner-local-script-cmd)
and [`local-script`](https://github.com/StackStorm/st2/blob/master/docs/source/actions.rst#available-runners)
Seems documentation typo.
> `local-shell-cmd` documentation fix

- instructables/chatops.md
This change follws the change made in https://github.com/StackStorm/st2workroom/commit/ce4e9446230debdb15aa388c37dcdcd8e9d659a9,
which only mounts the needed directory for pack development
on a local machine. This omits the directories `vcs`, `static`,
and `virtualenvs` from being mounted on the local machine.
Fixes errors observed by @dzimine during bootstrap testing
of the https://github.com/StackStorm/st2workroom project.
> Modifying artifact directory to mount only packs

- contrib/examples/sensors/sample_polling_sensor.py
Resolves "Class "SimplePollingSensor" doesn't implement required "update_trigger" method from the base class" error when running sensor using "st2sensorcontainer --config-file=/etc/st2/st2.conf --sensor-name=SimplePollingSensor"
> Fixing STORM-1193

- contrib/examples/sensors/sample_sensor.py
Resolves "Class "SimpleSensor" doesn't implement required "update_trigger" method from the base class" error when running sensor using "st2sensorcontainer --config-file=/etc/st2/st2.conf --sensor-name=SimpleSensor"
> Fixing STORM-1193 - part 2

- st2api/st2api/controllers/root.py
Setting up my st2workroom. Wile with this, fixing broken link in api root.
Doc version is two-digit (0.9).
IMAO, the root should not return html, but a proper json with the links to the next level resources. `GET https://api.github.com/` to see what I mean.
> Fix doc link in st2api

- st2reactor/st2reactor/rules/enforcer.py
Currently, a known limitation is that trigger payload which is matched against in the rules engine can't contain special Jinja2 characters such as "{{", unless you are referencing variable in a datastore inside the payload.
For example, the following would fail:
```bash
curl -X POST http://127.0.0.1:9101/v1/webhooks/sample -H "Content-Type: application/json" -d '{"a": "{{ foo.bar }}"}'
```
(we try to reference attribute "bar" of variable "foo" which is not defined / available inside the template context)
If the payload contains those special characters, they need to be explicitly escaped inside the payload before sending trigger into the system.
Before this change, a really cryptic exception was thrown which made it hard to figure out the root cause. This pull request doesn't solve the …
> Throw a better exception if we fail to templatize trigger payload in the rule enforcer

- st2api/st2api/controllers/exp/aliasexecution.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
This pull request adds support for implicit "key=value" command format for action aliases.
This means that by default, if you want to make action available via ChatOps, you just need to create an alias file and you don't need to define any format strings since the "key=value" format is available by default.
For example (alias definition):
```yaml
---
name: "st2-sensors-list"
action_ref: "st2.sensors.list"
description: "List available StackStorm sensors."
```
And lets say this action takes "pack" and "limit" parameter. With this change, the following command now works out of the box:
`!st2-sensors-list pack=examples limit=2`
They way it's implemented, we merge "key=value" parameters with parameters parsed from a custom format. 
This allows users to mix and match parameters and use commands …
> Implicit "key=value" command format support for action aliases

- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
Addresses the issue mentioned in this comment - https://github.com/StackStorm/st2/pull/1496#issuecomment-103560158
> Allow users to correctly mix and match "format string" and "key=value" action alias parameters

- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/content/aliasesregistrar.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/st2reactor/bootstrap/sensorsregistrar.py
- tools/diff-db-disk.py
```
(virtualenv)/m/s/s/st2 git:add_diff_tool ❯❯❯ tools/diff-db-disk.py --actions --pack-dir=/opt/stackstorm/packs/cicd-docker  ✭ ✱
(virtualenv)/m/s/s/st2 git:add_diff_tool ❯❯❯ tools/diff-db-disk.py --actions --pack-dir=/opt/stackstorm/packs/cicd-docker --verbose
******************************************************************************
Checking if artifact cicd-docker.git_checkout_branch is present in both disk and db.
Artifact cicd-docker.git_checkout_branch exists in both disk and db.
Performing content diff for artifact cicd-docker.git_checkout_branch.
******************************************************************************
Checking if artifact cicd-docker.build_image is present in both disk and db.
Artifact cicd-docker.build_image exists in both disk and db.
Performing …
```
> Diff tool to show diff between what's on disk vs what's in db content wise. 

- tools/st2_deploy.sh
The test action run at the end of st2_deploy is causing permissions issues on the token file for the Stanley user.  It needs to be run as stanley, not root.
> WIP: token_perm_fix

- st2client/st2client/shell.py
If user doesn't have read and write permissions, we will now simply always authenticate and retrieve a new auth token on every CLI invocation instead of caching the retrieved token and re-using it on subsequent requests.
> Update st2client so it doesn't explode if the user doesn't have read / write permissions to ~/.st2/token file

- st2api/st2api/controllers/exp/aliasexecution.py
- st2api/tests/unit/controllers/exp/test_alias_execution.py
- st2common/st2common/models/api/action.py
This pull request adds support for a more flexible and future-proof format for specifying ChatOps command.
`name` attribute is now only used as a primary key for a particular alias and the command format is specified using `formats` attribute.
This notation is more flexible and allows users to group related formats together in a single metadata file. Previously, if a user wanted to use formats which are specified bellow, they would need to create multiple alias metadata files.
Note: Getting this to work required moving more logic into the client which resulted in more coupling between the client and the server. Sadly there is no way around it if we want to support this notation with the current hubot approach.
Lets say we have the following alias definition:
```yaml
---
name: …
```
> Support for improved ChatOps command format notation

- st2api/st2api/controllers/exp/aliasexecution.py
- st2common/st2common/models/api/action.py
In addition to that, tokenzation (splitting command string into command name and arguments) now also happens on the client and this data gets sent to the API endpoint.
See related PR for more information.
Related PRs:
* https://github.com/StackStorm/hubot-stanley/pull/11
> Add support for whitespaces in the action alias command names

- contrib/tests/actions/chains/test_packs_pack.yaml
1. changed verification step to use json format for output (since one of the periodic failures is too narrow field format in the output; instead of fighting it,it's more convenient to use json)
2. changed test_packs_setup_virtualenv success criteria (text changed in the message)
3. changed test_packs_load_register_all success criteria - now it reports 4 items ("aliases" was not previously there)
> Changes to test_packs_pack

- tools/st2ctl
Turns out --register-aliases already exists. So only need to add the help string.
> [STORM-1340] register aliases help description.

- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/load.yaml
- docs/source/alias.rst
- docs/source/aliases.rst
- docs/source/index.rst
Doc for aliases. This PR is general and not ChatOps specific but does liberally callout to ChatOps for example purposes.
This PR starts us off with having some docs for Action Alias. As we notice more behaviors and details or answer user question will add more content to the docs.
> [STORM-1339] Alias docs

- st2reactor/bin/st2-trigger-refire
- st2reactor/st2reactor/cmd/trigger_re_fire.py
* Need to have access to id of the trigger instance.
* script needs access to mongodb and rabbitmq
Usage
```
$ st2reactor/bin/st2-trigger-refire -t 5566588332ed3528eccc8a1d
'Trigger re-fired'
```
```
$ st2reactor/bin/st2-trigger-refire -h
usage: st2-trigger-refire [-h] [--config-dir DIR] [--config-file PATH]
[--nouse-debugger]
[--trigger-instance-id TRIGGER_INSTANCE_ID]
[--use-debugger] [--verbose] [--version]
[--noverbose]
optional arguments:
-h, --help            show this help message and exit
--config-dir DIR      Path to a config directory to pull *.conf files from.
This file set is sorted, so as to provide a
predictable parse order if individual options are
over-ridden. The set is parsed after the file(s)
specified via previous --config-file, arguments hence
over-ridden options in …
```
> Ability to refire a trigger

- contrib/tests/actions/chains/test_quickstart_rules.yaml
There is a bug with actiontrigger parsing when the nested object has Jinja templating.  This PR redirects output to /dev/null for the two tasks that have output that would trigger this bug.  This is a work-around until the platform bug is fixed.
> Temporarily silencing rule create and get tasks

- st2reactor/st2reactor/rules/datatransform.py
- st2reactor/st2reactor/rules/enforcer.py
- st2reactor/tests/unit/test_data_transform.py
Payload render in cases where the payload itself contains tokens from a rule etc is incorrect and also causes failure.
Apart from that there is no real reason to render these token. If a value is to be rendered eventually that will be handled at actionexecution time anyway.
> Skip payload render

- st2client/st2client/shell.py
We didn't check if the file exists when checking for the token file permissions which means "_cache_auth_token" method would always return None if the file didn't exist which means token would never be cached.
> Fix a CLI token file permission check bug

- st2actions/conf/console.conf
- st2api/conf/console.conf
- st2auth/conf/console.conf
- st2reactor/conf/console.conf
This commit adds console logger configs to each of the components
within this project. These configs are meant to be used with
containerized configurations, where log messages are piped only
to STDOUT as general practice. (See http://12factor.net/logs)
> Adding console based logger configs

- instructables/chatops.md
This PR updates ChatOps instructables to download the Hubot pack from the `st2contrib` repository as opposed to the `st2incubator` repository.
> Update ChatOps docs with updated Hubot pack

- CHANGELOG.rst
- docs/source/rules.rst
- st2api/st2api/controllers/v1/triggers.py
- st2api/tests/unit/controllers/v1/test_triggerinstances.py
- st2client/st2client/client.py
- st2client/st2client/commands/keyvalue.py
- st2client/st2client/commands/noop.py
- st2client/st2client/commands/triggerinstance.py
- st2client/st2client/models/reactor.py
- st2client/st2client/shell.py
* - [X]  Tests for timestamp filter in API
* - [X] Docs
```
(virtualenv)/m/s/s/st2 git:STORM-1385/trigger_instances_list ❯❯❯ http localhost:9101/v1/triggerinstances                                                                                                                                             ⏎ ✭ ✱ ◼
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: http://127.0.0.1:9101/
Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count
Connection: keep-alive
Content-Length: 872
Content-Type: application/json; charset=UTF-8
Date: Mon, 01 Jun 2015 23:20:17 GMT
X-Limit: 100
X-Total-Count: 4
[
{
"id": "556ce89f32ed35231a8b5400",
"occurrence_time": …
```
> RFR: Support for st2 triggerinstance (get | list)

- st2api/st2api/controllers/exp/actionalias.py
- st2api/st2api/controllers/exp/aliasexecution.py
- st2api/st2api/controllers/resource.py
- st2api/tests/unit/controllers/exp/test_action_alias.py
- st2client/st2client/client.py
- st2client/st2client/commands/action_alias.py
- st2client/st2client/models/action_alias.py
- st2client/st2client/models/core.py
- st2client/st2client/shell.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/db/actionalias.py
This pull request adds CLI comments for viewing action aliases (list, get).
In addition to that, I made some other changes so it's consistent with other content pack resources (actions, rules, etc.):
* Also allow user to retrieve action alias by ref
* Update supported query param filters
* Add `enabled` attribute to the ActionAlias model
> Action alias CLI commands and minor consistency changes

- contrib/core/actions/send_mail/send_mail
- contrib/core/actions/sendmail.yaml
Although "body" is a required parameter, results of actions can be empty
or contain all whitespace characters. Sometimes it's only desireable to
receive an email if the action actually had output (similar to cron) and
this can now be done by setting this parameter to False.
> send_empty_body parameter in sendmail action

- CHANGELOG.rst
- st2api/st2api/controllers/v1/rules.py
- st2api/tests/unit/controllers/v1/test_rules.py
- st2common/st2common/models/api/rule.py
- st2common/st2common/validators/api/reactor.py
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_1.yaml
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_2.yaml
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_3.yaml
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_invalid_parameters.yaml
This pull request adds support for validating parameters for system triggers (webhook, timers) during rule creation.
Previously, rule creation would proceed normally even if user didn't provide all or provided invalid parameters for a system trigger.
For example:
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ python st2client/st2client/shell.py rule create rule.yaml 
MESSAGE: Additional properties are not allowed (u'until' was unexpected)
Failed validating 'additionalProperties' in schema:
{'additionalProperties': False,
'properties': {'delta': {'type': 'integer'},
'timezone': {'type': 'string'},
'unit': {'enum': ['weeks',
'days',
'hours',
'minutes',
'seconds']}},
'required': ['unit', 'delta'],
'type': 'object'}
On instance: …
```
> Validate parameters for system triggers during rule creation

- st2actions/st2actions/runners/localrunner.py
- st2common/st2common/util/green/shell.py
- st2common/st2common/util/shell.py
This pull request refactors local runner to use `st2common.util.green.shell.run_command` function and as such, reduces code duplication.
This will also help by substantially reducing code duplication in #1491 branch.
> Reduce duplicated code and refactor local runner to use run_command function

- st2api/st2api/controllers/v1/triggers.py
- st2api/tests/unit/controllers/v1/test_triggerinstances.py
- st2client/st2client/client.py
- st2client/st2client/commands/triggerinstance.py
- st2client/st2client/models/core.py
[X]  - CLI change
```
(virtualenv)/m/s/s/st2 git:STORM-1367/reemit_trigger_instances ❯❯❯ http POST http://localhost:9101/v1/triggerinstances/556f9d4632ed352054607408/re_emit                                                                                                  ✭ ✱ ◼
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: http://127.0.0.1:9101/
Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count
Connection: keep-alive
Content-Length: 239
Content-Type: application/json; charset=UTF-8
Date: Thu, 04 Jun 2015 00:35:39 GMT
{
"message": "Trigger instance 556f9d4632ed352054607408 succesfully re-sent.",
"payload": {
"__context": {
"original_id": …
```
> RFR - TriggerInstance API controller to support re_emit

- instructables/chatops.md
This PR updates the instructions for ChatOps to call out attention to the port Hubot runs on. Needed to ensure conflict with `st2web` is avoided.
> Updates to reflect changes to Hubot port

- contrib/examples/actions/echochain.meta.yaml
- contrib/examples/actions/local.yaml
- contrib/examples/actions/mistral-basic-two-tasks-with-notifications.yaml
- st2actions/tests/unit/test_mistral_v2.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/notification.py
- st2common/st2common/models/system/actionchain.py
- st2common/tests/unit/services/test_action.py
- st2common/tests/unit/test_notification_helper.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_notifications.yaml
* actionchain already uses 'on-success' and similar therefore making
sure that notification which can also exist in an actionchain task use
'on-success'. All instances like Action & LiveAction can contain
notfication schema have been updated for sake of consistency.
* The preferred value is 'on_success' however mistral DSL has already
taken the approach to use '-' and not '_'. To avoid confusion and
inconsistency to user better to stick with '-'.
* All the internal proeprties though use '_' since '-' being the 'minus'
operator should not be used in a property name.
> Notification consistency

- contrib/packs/actions/download.yaml
- contrib/packs/actions/info.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/pack_mgmt/info.py
- contrib/packs/aliases/pack_deploy.yaml
- contrib/packs/aliases/pack_info.yaml
- st2api/st2api/controllers/exp/aliasexecution.py
- st2api/tests/unit/controllers/exp/test_alias_execution.py
- st2common/st2common/models/utils/action_param_utils.py
- st2tests/st2tests/fixtures/aliases/actions/action1.yaml
- st2tests/st2tests/fixtures/aliases/aliases/alias2.yaml
This commit introduces several new fixes for the existing Pack deployment
actions. Namely:
* Do not overwrite config.txt on existing pack installations
* Allow short repo_url for GitHub shortcuts (repo_url=StackStorm/st2contrib)
* Deploy from monorepo repositories and single-pack repositories
- Introduces subtree flag, for used when packs are nested within top-level packs directory
* Tag each download with Git information
- Used to introspect versions of deployed packs
> Pack deployment chatops

- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/workflows/install.yaml
Moved over from #1576 to merge on the correct branch. 
```
This PR fixes two bugs introduced in #1570 / #1571
* Double .git extension
* SSH protocol downloads via Git
In certain circumstances, the repo_url passed into the packs.download
action is returns a double .git.git extension. Contains fix to only
append .git suffix if doesn't already exist.
In #1570, the protocol for Git was changed from SSH -> HTTPS. In cases
where a git-helper is not installed (ref: st2workroom), the protocol
needs to be reverted to avoid credential prompts.
```
> Packs repair 0.11

- st2api/st2api/controllers/exp/aliasexecution.py
* Include user context so downstream AUTH_TOKEN is setup correctly.
> Include user context on firing an execution via alias execution.

- CHANGELOG.rst
- docs/source/rules.rst
- st2actions/tests/unit/policies/test_concurrency_by_attr.py
- st2client/st2client/models/reactor.py
- st2client/st2client/shell.py
See:
* https://github.com/StackStorm/st2/pull/1554#discussion_r31784141
* https://github.com/StackStorm/st2/pull/1554#discussion_r31784041
> Trigger instance typo and command name consistency fix

- st2api/st2api/controllers/v1/executionviews.py
- st2client/st2client/commands/action.py
- st2tests/st2tests/fixtures/executions/trigger_instance.yaml
This will let users track the sequence of what happened after a particular trigger was dispatched.
> Adding ability in API and CLI to filter executions based on the trigger instance id

- instructables/chatops.md
This PR updates the ChatOps instructions to reflect changes with `0.11.0`
> Updating ChatOps instructions for 0.11.0

- st2actions/tests/unit/policies/test_concurrency.py
- st2actions/tests/unit/policies/test_concurrency_by_attr.py
Manually step thru the process to avoid time outs.
> Fix unit tests for the concurrency policies

- conf/st2.dev.conf
- docs/source/conf.py
- docs/source/install/config.rst
* skip versions ending with 0 as our CI/CD don't grok them yet.
This is a hack but does the trick. I can have bug to remind us to remove it once CI/CD fixed.
> Fix docs version selector.

- tools/st2_deploy.sh
This is a fix for a missing dependency problem on the jsonschema pip package.  Previously, functools32 was not getting installed.
> Update pip and rehash

- st2common/st2common/logging/formatters.py
- st2common/tests/unit/test_logger.py
This pull request fixes a bug which would cause the masking could to modify the original dictionary in place instead of modifying a copy of it and using a copy to interpolate the log message.
> Fix a bug with secrets masking

- CHANGELOG.rst
- st2common/st2common/fields.py
- st2common/st2common/util/isotime.py
- st2common/tests/unit/test_action_db_utils.py
- st2common/tests/unit/test_db_fields.py
We were not handling the values correctly (sometimes we used local instead of UTC time) which means that sometimes the result would be a datetime object in a local instead of a UTC timezone.
> Fix a bug in ComplexDateTimeField

- st2exporter/st2exporter/exporter/dumper.py
- st2exporter/tests/unit/test_dumper.py
- tools/launchdev.sh
```
(virtualenv)/m/s/s/st2 git:STORM-1445/export_by_date ❯❯❯ ls /opt/stackstorm/exports                                                                                                                                                                  ⏎ ✭ ✱ ◼
2015-06-15
(virtualenv)/m/s/s/st2 git:STORM-1445/export_by_date ❯❯❯ ls /opt/stackstorm/exports/2015-06-15/st2-executions-2015-06-15T21:58:50.375516Z.json                                                                                                         ✭ ✱ ◼
/opt/stackstorm/exports/2015-06-15/st2-executions-2015-06-15T21:58:50.375516Z.json
(virtualenv)/m/s/s/st2 git:STORM-1445/export_by_date ❯❯❯ cat /opt/stackstorm/exports/2015-06-15/st2-executions-2015-06-15T21:58:50.375516Z.json …
```
> RFR: Create subfolders based on date in exports dir.

- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/load.yaml
- tools/st2ctl
One of the problems described in #1619 is that `packs.install` reloads only `actions` by default, bringing problems (especially in ChatOps) when installed pack contains aliases or sensors:
```
st2 run packs.install packs=st2-google repo_url=jfryman/st2-google
```
This PR brings possibility to pass several `register` components.
If not provided `register=actions,aliases,sensors` is default value.
```sh
st2 run packs.load register=actions
st2 run packs.install packs=hubot register=aliases,rules
st2 run packs.load register=rules,sensors
```
which would trigger reload with many arguments (only 1 was accepted before):
```sh
st2ctl reload --register-aliases --register-rules
```
> Pass many 'register' components for 'packs.install', 'packs.load', 'st2ctl reload' #1619

- st2actions/st2actions/runners/cloudslang/cloudslang_runner.py
in cloudslang runner the --if flag was appended twice.
> --if was apended twice

- tools/st2ctl
st2ctl was missing an if clause which means `restart-component` action didn't work / wasn't available for `st2notifier` service.
> Fix st2ctl restart-component action for st2notifier service

- CHANGELOG.rst
- st2api/st2api/cmd/api.py
- st2api/st2api/signal_handlers.py
- st2common/st2common/util/wsgi.py
This pull request implements graceful API WSGI server shutdown. On shutdown (or CTRL-C / SIGINT signal), we stop receiving new requests and give existing active requests some time to shut down (2 seconds by default) before we kill requests which still didn't finish.
This is needed since we support long-running requests (stream endpoint). Previously, if there was an active long-running request, it would block API server from gracefully shutting down and we would need to send `SIGTERM` to the server to kill it.
This is also important and will be utilized when we support requests draining and zero-impact and zero-downtime (rolling) upgrades / restarts.
Note: This is something @enykeev were passively trying to figure out in the past.
> Graceful API WSGI server shutdown

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/download.py
Previously, if an existing pack which was installed had no config file we would still to try to move it over to new location which would cause installation (download action) to fail.
Resolves #1653.
> Fix reinstallation of a pack with no config

- docs/source/install/config.rst
- st2actions/tests/integration/test_localrunner.py
- st2reactor/st2reactor/container/process_container.py
- tools/st2_deploy.sh
If `SETENV` option is not set and user runs local runner action under a different user, environment variables which are specified as parameter or available to the system user won't be available to the action since sudo will clean the environment variables.
This pull request "fixes" that by documenting that `SETENV` sudoers option needs to be set system user.
Related to #1646
> Document SETENV sudo requirement for system (stanley) user

- CHANGELOG.rst
- docs/source/sensors.rst
- st2reactor/st2reactor/cmd/sensormanager.py
- st2reactor/st2reactor/sensor/config.py
* We only guarantee uniqueness of ref and not of name therefore to
target a single sensor it is better to use sensor_ref.
> Provide sensor_ref instead of sensor_name to run a single sensor

- docs/source/roadmap.rst
- st2actions/st2actions/query/base.py
- st2client/st2client/commands/action.py
This pull request fixes two bugs:
1. CLI throwing an exception when displaying a result for a failed Mistral workflow run.
2. CLI not displaying `end_timestamp` attribute for Mistral workflows. In this case the problem lied in the querier module - we never set `end_timestamp` attribute for a LiveActionDB object which has completed.
> CLI, Mistral "end_timestamp" bug fix

- st2common/st2common/services/triggers.py
- st2common/st2common/triggers.py
- st2common/tests/unit/test_register_internal_trigger.py
* Previously internal trigger registration was via the API which automatically
handled shadow trigger registration. Since that was skipped to registering
in st2api the shadow trigger registration was also dropped leading to regressions.
* Added registration back in and also some basic test to validate shadow trigger
creation.
Testing -
Validated that creation of `notify_hubot` from the hubot pack works.
```
$ st2 rule create notify_hubot.yaml
+-------------+--------------------------------------------------------+
| Property    | Value                                                  |
+-------------+--------------------------------------------------------+
| id          | 5592174132ed355332f81a8e                               |
| name        | chatops.notify_hubot …
```
> Create shadow tigger on internal trigger registration

- contrib/core/actions/send_mail/send_mail
- contrib/core/actions/sendmail.yaml
This PR updates the core.smtp action to take Content-Type parameters of both text/html and text/plain. This repairs issues when attempting to send plain text, and having linefeeds not being respected.
Reported from IRC via hikertechy
Analog of https://github.com/StackStorm/st2/pull/1663 for master branch.
> Parameterize Content-Type for SMTP action

- contrib/packs/actions/pack_mgmt/download.py
- st2common/tests/unit/test_pack_management.py
* If a pack is missing then fail the install
* Some refactors in code to fix latent issues
Failure to install missing pack -
```
$ st2 run packs.install packs=bitcon
........
id: 5594731032ed3558b5db84ec
action.ref: packs.install
status: failed
error: st2.actions.python.DownloadGitRepoAction: WARNING  bitcon is missing. Expected location "/home/manas/st2contrib/packs/bitcon".
File "/mnt/st2repos/st2/st2actions/st2actions/runners/python_action_wrapper.py", line 116, in <module>
obj.run()
File "/mnt/st2repos/st2/st2actions/st2actions/runners/python_action_wrapper.py", line 61, in run
output = action.run(**self._parameters)
File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 70, in run
return self._validate_result(result=result, …
```
> Fail on missing pack

- instructables/chatops.md
Related to https://github.com/StackStorm/st2workroom/pull/39, this commit fixes an incorrectly formatted object that caused puppet run errors.
> Fix incorrect ChatOps example

- st2api/st2api/controllers/v1/actions.py
- st2common/st2common/models/api/action.py
If a user didn't specify a value for `enabled` attribute when updating an action, an exception would be throw and 500 internal server error returned to the user.
This pull request fixes that by specifying a default value inside the API model and not inside the controller (previously, the controller would only set it on create, but not on update).
> Fix a bug with actions update API endpoint throwing on missing "enabled" attribute

- st2actions/tests/unit/test_actions_registrar.py
- st2actions/tests/unit/test_param_utils.py
- st2actions/tests/unit/test_queue_consumers.py
- st2actions/tests/unit/test_runner_container.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/auth.py
- st2common/st2common/models/api/base.py
- st2common/st2common/models/api/execution.py
- st2common/st2common/models/api/keyvalue.py
- st2common/st2common/models/api/notification.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/api/rule.py
- st2common/st2common/models/api/tag.py
- st2common/st2common/models/api/trigger.py
- st2common/st2common/models/utils/sensor_type_utils.py
- st2common/tests/unit/test_db.py
- st2exporter/st2exporter/exporter/dumper.py
- st2reactor/st2reactor/rules/tester.py
- st2reactor/tests/unit/test_filter.py
- st2reactor/tests/unit/test_rule_matcher.py
This branch updates all the `to_model` methods on the API models and other related code to pass all the model arguments to the constructor instead of performing a late variable assignment on the model instance.
Late variable assignment shouldn't be used unless there is a good and valid use case for it (same as with the decorators) since it breaks many assumptions and "static" analysis. We don't know if and when variable will be set which makes constructors useless.
For example, if I want to create a new attribute based on the value of other attributes and assign it inside the constructor, I can't do that when using late variable assignment approach. Only way to get this to kinda consistently work with a late variable assignment is to instead implement `__getattribute__`, but that's a hack …
> Fix late-assignment of the variables on the model instances

- tools/st2ctl
Looks like st2auth is missing from the restart-component checks, so you are unable to restart only that component.
@Kami ?
> adds st2auth to the list of components that can be restarted

- .coveragerc
- .travis.yml
- Makefile
- README.md
- scripts/travis.sh
I started to dig into Coveralls.io problem we recently discussed before with @lakshmi-kannan, when only files from one st2package were included in coverage report, but had more fun and curiosity and optimized travis builds also.
Surprising that some bits of code were incompatible with Python2.6, despite 2.6 is included in Travis build matrix.
> Fix Coveralls & Optimize Travis builds

- docs/source/install/docker.rst
As reported in https://github.com/StackStorm/st2contrib/issues/240,
not all environments are treated equally. Many environment fall into a
scenario where a custom CA must be trusted by the OS and Applications,
or else validation will fail and connections will be rejected. To that
end, this commit adds detail on how to configure the underlying Python
`requests` library to load a custom SSL CA bundle into the OpenSSL trust
chain.
h/t @amaline :tophat:
> Additional detail on configuring trusted SSL CA

- tools/st2ctl
This PR adds a new flag to our old trusty `st2ctl` command, which is bound to be with us for some time longer.
In lieu of this, we're about to add real, honest to goodness init scripts for all of our services to the native packages. However, it's going to take a bit of :frog: jumping around to get to the final state.
This first commit adds an internal-only flag to the init script. giA bit ugly, but it's a way to allow testing to happen in parallel while not breaking existing behavior.
> Add NG_INIT flag for migration to init scripts

- tools/st2_deploy.sh
Fixes #1696, adds EPEL repo for RHEL7/CentOS7 installations via `st2_deploy.sh`
Tried different ways, like [install erlang rpm only](https://www.rabbitmq.com/install-rpm.html), but adding EPEL is the best way.
> Fixes missing Erlang dependency for RHEL7/CentOS7 installation

- .scrutinizer.yml
- README.md
* code rating badge [![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/armab/st2/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/armab/st2/?branch=master)
* does the same build as Travis: `make requirements .flake8 .pylint .docs`
* mark as failed only if ^^ flake/pylint builds errored (same as before, nothing new)
* future intent:
* remove from Travis code style checks, leave only real Tests (Unit, Integration, etc)
* role separation: if Scrutinizer failed - code style, if Travis failed - tests
* more parallelization when new Travis tests will be added
* [Errored Pull Request example](https://github.com/armab/st2/pull/7)
* [Errored log/report](https://scrutinizer-ci.com/g/armab/st2/inspections/708d945a-2906-4fe0-9f44-7ef410714e13) (looks pretty clear)
----
PS. To …
> Add Scrutinizer

- scripts/travis.sh
Exit immediately if any command in `scripts/travis.sh` exits with a non-zero status.
My fail with recent changes, see: 
https://travis-ci.org/StackStorm/st2/jobs/71310549#L156
> Fix Travis build script

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
Display only the human friendly message from the jsonschema validation error. Remove the unicode prefix in the string.
```
~/st2$ st2 run core.local
MESSAGE: 'cmd' is a required property
~/st2$ st2 run default.ping count=x
MESSAGE: Additional properties are not allowed ('count' was unexpected)
```
> Display friendly message for error in action parameters validation

- st2auth/st2auth/backends/keystone.py
- st2auth/tests/unit/test_auth_backends.py
Not sure how I would go about doing the tests as it needs a keystone endpoint. Should I just mock it?
> add keystone auth backend

- docs/source/authentication.rst
> add keystone backend info to the docs

- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionalias.py
- st2api/st2api/controllers/v1/actions.py
- st2api/st2api/controllers/v1/policies.py
- st2api/st2api/controllers/v1/rules.py
- st2api/st2api/controllers/v1/triggers.py
- st2common/st2common/exceptions/db.py
- st2common/st2common/hooks.py
- st2common/st2common/persistence/base.py
This pull request refactors `ContentPackResourceController._get_by_ref_or_id` method to throw a correct `StackStormDBObjectNotFoundError` exception.
This way we can get rid of now unnecessary try / except blocks when calling `_get_by_ref_or_id` and we can simply translate this exception into 404 inside the JSON error response hooks.
@enykeev made the JSONErrorResponseHook refactor ago. This hook is now the place where all the exceptions should be translated to a correct status code and error message. This is good since we previously didn't have a centralized way to translate and handle API exceptions and means we can get rid of a lot of duplicated code.
In the future, when working on new controllers we should make sure we throw correct exceptions there and translate it into an error …
> Minor ContentPackResourceController refactoring and improvements

- st2api/st2api/controllers/v1/actionexecutions.py
It was utterly confusing when I was reading the code to call liveaction as execution. So here's something.
> Rename execution variable to liveacton in action execution controller

- docs/source/aliases.rst
Found while working today at a client site. Copy-paste of this block fails, because `description` is a required field.
> Adding required description to ActionAlias example

- st2common/st2common/models/db/stormbase.py
- st2common/st2common/util/mongoescape.py
- st2common/tests/unit/test_action_db_utils.py
- st2common/tests/unit/test_mongoescape.py
- st2common/tests/unit/test_persistence.py
The DB model permanently changed the dict result when escaping the characters for persistence and then cascade the changes to other components. The fix makes a copy of the dict before escaping.
> Fix escaped liveaction result

- tools/st2_deploy.sh
This commit adds a test that matches the test in `st2_bootstrap.sh`, allowing the installer to run on Debian systems.
> Adds proper Debian test in st2_deploy.sh

- instructables/chatops.md
Prior to 0.12 it seems like a description was not required, but it is now.
> Action alias requires a description

- contrib/packs/actions/pack_mgmt/unload.py
* Leaving behind rules and action-aliases of a pack when the pack is incorrect.
Removing all the content is the correct behavior.
> Unregister rules and aliases if the pack is uninstalled

- tools/st2ctl
RHEL/CentOS6 uses Python 2.6 as the system Python. We need to explicitly point to the python2.7 binary in order for this to work out of the box on those hosts.
> Use python2.7 explicitly

- CHANGELOG.rst
- st2actions/st2actions/bootstrap/runnersregistrar.py
* Fabric doesn't behave well with eventlets especially when parallel is
set to True. Parallel basically executes a command on a bunch of hosts.
Parallel uses multiprocessing and calls fork(). We don't understand the
root cause yet. Fabric has other issues as well. So until we use
Paramiko straight and replace our SSH runner, let's disable parallel
SSH execution.
> RFR: Disable parallel execution of SSH actions

- tools/st2-self-check
Resolves Issue #1740
The st2-self-check script needed better error handling.
Failure:
```
ttempting Test tests.test_packs_pack...ERROR!
Attempting Test tests.test_quickstart...OK!
Attempting Test tests.test_quickstart_key...OK!
Attempting Test tests.test_quickstart_local_script_actions...OK!
Attempting Test tests.test_quickstart_passive_sensor...OK!
Attempting Test tests.test_quickstart_polling_sensor...OK!
Attempting Test tests.test_quickstart_python_actions...OK!
Attempting Test tests.test_quickstart_remote_script_actions...OK!
Attempting Test tests.test_quickstart_rules...ERROR!
Attempting Test tests.test_timer_rule...ERROR!
Attempting Test tests.test_windows_runners...ERROR!
Attempting Example examples.mistral_examples...ERROR!
st2-self-check failed.  See above.  Also check the …
```
> st2-self-check error handling

- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
Kind of a workaround as it would be better to stop the sensor, delete the venv, create it and register the sensor again so it cleaner.
On sensor registration, sensorcontainer kills the old one and launches the new one so there seems to be no side effects for this.
```
2015-07-29 21:43:35,644 140695903024464 INFO log [-] Container shutting down. Invoking cleanup on sensors.
2015-07-29 21:43:35,932 139779226957136 INFO log [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-07-29 21:43:35,972 139779226957136 INFO log [-] Using partitioner default with sensornode sensornode1.
2015-07-29 21:43:35,973 139779226957136 INFO log [-] Found 2 registered sensors in db scan.
2015-07-29 21:43:35,973 139779226957136 INFO log [-] Setting up container to run 2 sensors.
2015-07-29 …
```
> Try to delete the virtualenv before creating it. fixes #1757

- docs/README.md
- docs/source/mistral.rst
- docs/source/start.rst
Syntax fix (policy keyword gone), and add more links.
Also, fix 'how to refer a section' in README.md.
> Small fix in Mistral docs.

- st2client/Makefile
This fixes the shebang on the st2 CLI for systems that use something other than Python 2.7 as the system Python version.
> St2client py27

- st2actions/st2actions/container/base.py
- st2actions/st2actions/worker.py
- st2actions/tests/unit/test_runner_container.py
- st2actions/tests/unit/test_worker.py
Fixes: https://github.com/StackStorm/st2/issues/1717
Several things were uncovered with this bug report.
1) A non UTF-8 string '\x82' in stdout causes mongo to throw an
exception when updating the results. We don't have a check
for validating if string is UTF-8 in document schema.
So this must be some mongo internal validation. We should
figure out if we can turn it off.
2) An exception thrown is caught by worker and liveaction
object is updated but the execution object is not. This
results in execution state shown as `running` even though
liveaction status is `failed`.
3) While fixing this, I also noticed that when an action is
canceled, we don't execute the execution object status to
`canceled` which also is consistent with the bug report.
```
(virtualenv)/m/s/s/st2 git:master ❯❯❯ st2 …
```
> RFR: Update execution object when liveaction is updated

- docs/README.md
- docs/source/mistral.rst
- docs/source/start.rst
Syntax fix (policy keyword gone), and add more links.
Also, fix 'how to refer a section' in README.md.
> Small fix in Mistral docs cherry-pick for 0.12.1

- st2actions/st2actions/utils/param_utils.py
- st2actions/tests/unit/test_param_utils.py
- st2tests/st2tests/fixtures/generic/actions/action_4_action_context_param.yaml
- st2tests/st2tests/fixtures/generic/runners/testrunner1.yaml
Fixes #1654 , when runner parameters were not overridden with "falsey" action parameters (0, False, etc), so this meta was buggy:
```yaml
---
name: "test"
runner_type: "local-shell-cmd"
description: "Action that tests timeout."
enabled: true
entry_point: ""
parameters:
timeout:
cmd:
default: "echo 'TIMEOUT: {{timeout}}'"
```
(extracted from #1712 )
> Action: fix default parameters override

- st2client/Makefile
> Add path to Python binary to be added to spec file

- st2debug/st2debug/cmd/submit_debug_info.py
This change allows user to include additional context (name, email and optional email) when submitting debug info.
Keep in mind that this is opt-in and user is not required to provide this info.
> Allow user to include additional context when submitting debug info

- requirements.txt
* tooz 1.21.0 breaks test and unleashes monsters from the pits of hell. So until
the gods have mercy on us and fix the break freeze to last known version.
* Test test_over_threshold (tests.unit.policies.test_concurrency.ConcurrencyPolicyTest)
woudl simply block.
> Freeze tooz version

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actions.py
- st2common/st2common/hooks.py
- st2common/st2common/models/api/base.py
I just cherry-picked some general API improvements and fixes from my other branch.
The biggest one is correctly returning 404 if user hits a URL which doesn't exist, but partially maps to an existing controller. Previously, an internal error was thrown.
Keep in mind that this PR only fixes it for controllers which don't abuse kwargs. Controllers which abuse kwargs will silently accept all the arguments and 404 won't be thrown (I will fix this some other time).
> Misc API improvements and fixes

- docs/source/install/config.rst
- st2actions/st2actions/config.py
- st2actions/st2actions/runners/fabric_runner.py
- st2tests/st2tests/config.py
* Setting is not enabled by default but exposed as configuration to avoid
any odd behavior - Since it is fabric afterall.
* Fabric support for ssh_config is limited and should only really be used
for simple things like ports (http://docs.fabfile.org/en/1.4.0/usage/execution.html#leveraging-native-ssh-config-files)
> Support to allow ssh_config for fabric based runners.

- .travis.yml
- Makefile
- scripts/travis/build.sh
- scripts/travis/prepare-integration.sh
- scripts/travis/setup-mistral.sh
Adds existing mistral tests to Travis.
As I remember there were some mistral installation problems before (dependencies). This addition might be useful to identify and react on mistral-related issues faster and it's just cool to have more tests in Travis.
---
[`scripts/travis/setup-mistral.sh`](https://github.com/armab/st2/blob/c2a8b002b92f554d7bd967f9ab5de665bf9d1064/scripts/travis/setup-mistral.sh) uses code from [`st2_deploy.sh`](https://github.com/StackStorm/st2/blob/master/tools/st2_deploy.sh)
The thing I'm afraid of is synchronization with original `st2_deploy.sh`. I couldn't find an easy way to reuse bash functions from that script.
Not sure if it worth to rewrite a bit `st2_deploy.sh` and use Pythonish way `if __name__ == '__main__':` (you got the idea) to allow reusing functions …
> Mistral itests in Travis

- st2debug/st2debug/cmd/submit_debug_info.py
Now we don't prompt user for additional context when running in an interactive mode (`--yes`) flag.
> Submit debug info script improvements

- CHANGELOG.rst
- st2reactor/st2reactor/container/process_container.py
- st2reactor/tests/unit/test_process_container.py
This pull request adds support for automatically restarting sensor processes which die to the sensor container.
Sensor process is only restarted if it dies / exists with a non-zero status code and we only attempt to restart it 2 times before giving up. To prevent a thundering herd effect, we also add a small delay before restarting a sensor.
From our personal experience, most of the random / unexpected sensor deaths (IRC, Slack, Github, etc.) are related to errors such as  the server side connection being terminated, network issue or some other error which results into an uncaught exception. In most cases, you can simply recover from those errors by restarting the sensor container and therefore restarting the dead sensor.
Yes, in some specific cases, sensors could also be made more robust …
> Automatically restart sensors which die inside the sensor containainer

- st2actions/tests/unit/test_executions.py
- st2api/tests/unit/controllers/v1/test_action_views.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
- st2tests/st2tests/config.py
- st2tests/st2tests/fixtures/dummy_pack_1/pack.yaml
- st2tests/st2tests/fixtures/dummy_pack_2/pack.yaml
- st2tests/st2tests/fixtures/dummy_pack_3/pack.yaml
- st2tests/st2tests/fixtures/executions/actions.yaml
- st2tests/st2tests/fixtures/executions/chain.yaml
- st2tests/st2tests/fixtures/executions/liveactions.yaml
- st2tests/st2tests/fixtures/executions/rule.yaml
- st2tests/st2tests/fixtures/history_views/filters.yaml
This pull request updates `packs_base_path` in the tests config to point to the `st2tests/fixtures/` directory.
This way we can test resource loading and a lot of other things without needing to mock a bunch of stuff.
In addition to that, #1785 adds constraint that the entry point files needs to be located inside the pack. Before this change, a lot of tests violated this constraint causing failures and a lot of pain.
Note 1: This changes are cherry-pick from #1785 since I also need them in the RBAC branch.
Note 2: Eventually, I will move packs to `st2tests/fixtures/packs/` directory, but now it's not that time :P
> Update st2tests fixtures

- docs/source/install/index.rst
- docs/source/install/puppet.rst
This PR adds the initial configuration documentation for installing StackStorm via Puppet. First of a few CM focused documents incoming.
> Adding initial Puppet docs

- docs/source/install/all_in_one.rst
Merged https://github.com/StackStorm/st2/pull/1806 too quickly. Shame on me. This PR fixes error introduced by `aspell`.
Also, ReStructured Text should be less opinionated. Silly error. :smiley:
> Fix documentation: elongate header.

- CHANGELOG.rst
- st2client/st2client/models/core.py
An extra keyword token is now passed to the managers which is causing trigger_instance re_emit to break. Gosh, abusing kwargs.
> RFR: Fix trigger-instance manager to handle kwargs passed down

- CHANGELOG.rst
- contrib/examples/actions/echochain.meta.yaml
- contrib/examples/actions/local.yaml
- contrib/examples/actions/mistral-basic-two-tasks-with-notifications.yaml
- instructables/chatops.md
- st2actions/st2actions/notifier/notifier.py
- st2actions/tests/unit/test_mistral_v2.py
- st2api/st2api/controllers/v1/aliasexecution.py
- st2common/st2common/models/api/notification.py
- st2common/st2common/models/db/notification.py
- st2common/tests/unit/services/test_action.py
- st2common/tests/unit/test_db_liveaction.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_with_notifications.yaml
I think I got all the changes done. Preliminary backward compatiblity testing seems to pass but I am not confident yet. Will run more tests tomorrow. 
Related:
* - [X] hubot-stackstorm - https://github.com/StackStorm/hubot-stackstorm/pull/34/files
* - [X] chatops instructables - https://github.com/StackStorm/st2/commit/7b82e811f738e2611f405814baa8eb98e58c752b
> RFR -  Rename notify channels to routes

- CHANGELOG.rst
- st2common/st2common/constants/triggers.py
- st2common/st2common/persistence/keyvalue.py
- st2reactor/st2reactor/container/process_container.py
- st2reactor/st2reactor/container/utils.py
- st2reactor/st2reactor/rules/worker.py
- st2reactor/tests/unit/test_process_container.py
We were publishing the triggers with just name before. This failed lookup when creating trigger instances. So basically this feature never worked before. 
I added tests for sensor spawn and exit but for KVP, the code has multiple levels of abstraction.
> Fix bug in triggers emitted on key value pair changes and sensor spawn/exit.

- CHANGELOG.rst
- st2actions/st2actions/runners/remote_script_runner.py
- st2common/st2common/models/system/action.py
- st2common/st2common/models/system/paramiko_script_action.py
- st2common/tests/unit/test_paramiko_script_action_model.py
Tried a bunch of approaches and settled on this approach. (See PR https://github.com/StackStorm/st2/pull/1824)
```
(virtualenv)/m/s/s/st2 git:paramiko_remote_script_sudo ❯❯❯ st2 run fixtures.streamwriter-script-remote hosts=localhost stream=stdout sudo=false
.
id: 55ce3efe32ed354d080341a1
result:
{
"localhost": {
"succeeded": true,
"stderr": "",
"stdout": "STREAM IS STDOUT."
}
}
(virtualenv)/m/s/s/st2 git:paramiko_remote_script_sudo ❯❯❯ st2 run fixtures.streamwriter-script-remote hosts=localhost stream=stdout sudo=true
.
id: 55ce3f0532ed354d080341a3
result:
{
"localhost": {
"succeeded": true,
"stderr": "",
"stdout": "STREAM IS STDOUT."
}
}
(virtualenv)/m/s/s/st2 …
```
> RFR - Fix sudo in Paramiko remote script runner

- st2common/st2common/util/mongoescape.py
- st2common/tests/unit/test_mongoescape.py
Fix mongoescape util to handle escaped chars in nested list of dicts.
> Fix mongoescape util to handle complex dict

- st2actions/bin/st2actionrunner
- st2actions/bin/st2notifier
- st2actions/bin/st2resultstracker
- st2common/bin/paramiko_ssh_evenlets_tester.py
- st2common/bin/st2-bootstrap-rmq
- st2common/bin/st2-register-content
- st2common/st2common/content/bootstrap.py
- st2common/st2common/script_setup.py
- st2common/st2common/service_setup.py
- st2reactor/bin/st2-rule-tester
- st2reactor/bin/st2-trigger-refire
- st2reactor/bin/st2rulesengine
- st2reactor/bin/st2sensorcontainer
This pull request adds common CLI script setup code which can be used by all the CLI scripts.
I needed a similar functionality in the `st2-apply-rbac-definitions` script and instead of increasing the technical debt and just copy and pasting some code over I did a minor refactor :P
> Common CLI script setup and teardown code

- st2actions/st2actions/handlers/mistral.py
Mistral callback handler removed tasks from the result therefore the WF is unable to access output for the ActionChain actions.
> Fix result for ActionChain actions in Mistral

- contrib/default/actions/README.md
- contrib/default/pack.yaml
- contrib/default/rules/README.md
- contrib/default/sensors/README.md
- st2common/packaging/debian/install
- st2common/packaging/debian/preinst
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
This pull request makes sure that the directory for the "default" pack which we create during the installation has a "pack.yaml" file.
If a pack directory doesn't contain pack.yaml file, that directory is not treated as a pack (rightly so since pack.yaml makes a pack). This breaks many things. Among others, it means that the content from this pack won't be loaded when register-content is used.
This issue was originally discovered by @enykeev while trying to use the new "data_files" functionality - he was not able to create new files in the "default" pack because we could not find a corresponding `PackDB` model in the database (as noted above, the directory didn't contain "pack.yaml" which means PackDB model wasn't not created when the register content script was ran).
P.S. Yes you read it …
> Make sure that the "default" pack which we create during installation has a pack.yaml file

- contrib/linux/actions/wait_for_ssh.py
Previously, we returned `False` if a timeout was reached which means the action would exit with a zero status code instead of non-zero.
This means that if the action was used inside a workflow, `on-success` would be called instead of `on-failure`.
Inside one of out workflows we were lucky, because "retries * sleep delay" was >= default runner action timeout (600 seconds) so the exception was still thrown, but in this case it was because of the runner action timeout.
> linux.wait_for_ssh should throw on timeout

- st2client/st2client/commands/trace.py
- st2client/st2client/models/reactor.py
See the output to see what the client does.
```
$ st2 trace list
+--------------------------+----------------------------------------------------+-------------------------------+
| id                       | trace_tag                                          | start_timestamp               |
+--------------------------+----------------------------------------------------+-------------------------------+
| 55d3c9b132ed35435dd6a68f | trigger_instance-55d3c9b132ed35435dd6a68e          | Wed, 19 Aug 2015 00:11:29 UTC |
| 55d3c9ac32ed35435dd6a68d | trigger_instance-55d3c9ac32ed35435dd6a68c          | Wed, 19 Aug 2015 00:11:24 UTC |
| 55d3c9a732ed35435dd6a68b | trigger_instance-55d3c9a732ed35435dd6a68a          | Wed, 19 Aug 2015 00:11:19 UTC |
| 55d3c9a532ed35435dd6a689 | …
```
> Some pretty cli for trace

- CHANGELOG.rst
- tools/st2ctl
This is a simple workaround for a problem described here - https://github.com/StackStorm/st2/issues/1841#issuecomment-132733152
> I am not planning to use mistral and by default, mistral is not installed. But, st2ctl script doesn't start st2web service unless mistral is installed. https://github.com/StackStorm/st2/blob/master/tools/st2ctl#L184 . It fails when mistral service is tried to start and it exits before starting st2web.
The solution is not ideal since "st2ctl start" will still exit with non-zero if Mistral is not installed, but at least st2web will still be started.
Ideal / proper solution would be to detect if Mistral is installed / available and only start it if it is. That solution requires a lot more work though, especially if we want to do it the right way.
> [st2ctl] Start st2web before Mistral

- docs/source/install/ansible.rst
- docs/source/install/index.rst
Initial docs showing how to install StackStorm with Ansible, from [`ansible-st2`](https://github.com/StackStorm/ansible-st2) repo.
English syntax-check is welcome :)
----
The bad thing about `.rst` table, have no idea how to make multi-line `description` column, to avoid scrolling here:
> Ansible installer docs

- st2client/st2client/commands/trace.py
* Some argument munging to make sure that for a single trace components
are included
* Relax the words user can use for ActionExecution and TriggerInstance. It
is all contextual and about getting out of a users way.
> Bring back tableview of components with trace list

- CHANGELOG.rst
- st2api/st2api/app.py
- st2api/tests/unit/controllers/v1/test_base.py
- st2common/st2common/constants/api.py
- st2common/st2common/hooks.py
Example:
```
(virtualenv)/m/s/s/st2 git:support_trace_id_in_cli_run ❯❯❯ grep "a64fd291-f9cf-4797-89e8-b4a58c8f12db" logs/st2api.log
2015-08-19 16:42:38,875 140597257636112 INFO log [-] a64fd291-f9cf-4797-89e8-b4a58c8f12db -  GET /v1/rules with filters={} (remote_addr='127.0.0.1',method='GET',filters={},request_id='a64fd291-f9cf-4797-89e8-b4a58c8f12db',path='/v1/rules')
(virtualenv)/m/s/s/st2 git:support_trace_id_in_cli_run ❯❯❯
```
```
(virtualenv)/m/s/s/st2 git:support_trace_id_in_cli_run ❯❯❯ http http://localhost:9101/v1/rules             ✭ ✱ ◼
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token,X-Request-ID
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: http://127.0.0.1:9101/
Access-Control-Expose-Headers: …
```
> RFR: Add X-Request-ID API headers so we can trace request in logs easily.

- CHANGELOG.rst
- st2actions/st2actions/runners/pythonrunner.py
- st2common/st2common/util/sandboxing.py
- st2common/tests/unit/test_util_sandboxing.py
Previously, we didn't add `<path to virtualenv>/bin` directory to the "$PATH" environment variable which is set for the sandboxed Python runner process (good catch @manasdk!).
This means that if the Python action tried to access a binary / script which was installed inside a virtual environment bin directory (e.g. ansible Python package installs ansible binary, etc.) or if they wanted to spawn a new python process, a default system version would be used instead of the one which is specific to the virtual environment.
Once this issue is resolved, workaround described at https://github.com/StackStorm/st2contrib/issues/273 won't be needed anymore.
@manasdk and I discussed this change and decided to skip inclusion in v0.13.0. This change needs a bit more testing so we can be sure it doesn't …
> Correctly set "PATH" environment variable for the sandboxed Python runner process

- st2actions/st2actions/runners/__init__.py
* using execution_id is the right behavior
> Hide liveaction from everywhere as much as possible

- st2api/tests/unit/controllers/v1/test_alias_execution.py
- st2common/st2common/models/api/action.py
```
(virtualenv)/m/s/s/st2 git:notification_channel_leftovers ❯❯❯ ag -C 5 "notification_channel"                             ✭ ◼
st2api/st2api/controllers/v1/aliasexecution.py
100-        return parser.get_extracted_param_value()
101-
102-    def _get_notify_field(self, payload):
103-        on_complete = NotificationSubSchema()
104-        route = (getattr(payload, 'notification_route', None) or
105:                 getattr(payload, 'notification_channel', None))
106-        on_complete.routes = [route]
107-        on_complete.data = {
108-            'user': payload.user,
109-            'source_channel': payload.source_channel
110-        }
st2common/st2common/models/api/action.py
542-            "source_channel": {
543-                "type": "string",
544- …
```
> RFR: s/notification_channel/notification_route leftovers

- docs/source/config/authentication.rst
- docs/source/config/webui.rst
- docs/source/config/windows_runners.rst
- docs/source/install/deb.rst
- docs/source/install/on_complete.rst
- docs/source/install/rpm.rst
- docs/source/packs.rst
- docs/source/runners.rst
- docs/source/start.rst
Configuration related docs were moved to the config folder and broke a number of links in the docs in the process.
> Fix links in docs

- tools/st2ctl
This commit removes postgresql from the list of processes queried when running `st2ctl status`.
> Filter PostgreSQL from st2ctl process list.

- requirements.txt
Had to fork pecan and manually cherry pick the change from later version.
> Fix `packs/views/file` endpoint throwing error on binary data

- .travis.yml
- scripts/travis/build.sh
Sadly Scrutinizer gets stuck too many times or fails with errors unrelated to our changes :/
> Re-enable pylint, lint and docs checks on TravisCI

- requirements.txt
Using "-e" (editable) option with pip results in pip cloning a repo in the /root directory and creating a symlink from there into dist-packages.
This doesn't work well with the actions started by action runner. This manifested itself with `packs.install` action being broken (reload step failed because we failed to import pecan).
Note: This issue was originally reported by a user on slack-community channel. After a bunch of troubleshooting I managed to reproduced it on a fresh installation.
```
root@sewubuntu2:~# st2 run core.local cmd='whoami ; echo $PYTHONPATH; python -c "import pecan;print pecan;"'
.
id: 55dc738c516ea443c0aa5798
status: failed
result: 
{
"succeeded": false, 
"failed": true, 
"return_code": 1, 
"stderr": "Traceback (most recent call last):
File "<string>", line 1, in …
```
> Fix pecan install issue / regression introduced in v0.13.0

- CHANGELOG.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2client/st2client/commands/action.py
This pull request updates `st2 run`, `st2 execution run` and `st2 execution re-run` commands to exit with a non-zero status code when running in a non-async mode if the action failed.
I believe not exiting with non-zero code also masked the pecan regression introduced in v0.13.0. We have tests in `st2tests` for `packs.install`, but `st2 run` exited with zero so we didn't detect this issue.
@enykeev had some concerns that there might be a reason why we don't already do that. 
If there is indeed a good reason for this not being a default behavior, we can introduce a new flag (e.g. ``--exit-on-failure`` or similar), but I'm not too big of a fan of that since it's not consistent with other operations (e.g. get in-existent action).
Another concern was how to differentiate between CLI errors …
> [CLI] Update CLI to exit with non-zero if the action fails

- instructables/chatops.md
This PR is to redirect users who are finding their way to the ChatOps instructable to the All-in-one Installer.
This hopefully will make adoption much easier.
Reported by silopolis on stackstorm_community.
> add link to updated docs for ChatOps/Installation

- Makefile
* This is critical for productivity! Requirements targets are slow.
`make .pytests` - use that to run tests without requirements. 
`make pytests` - use that to run tests with requirements. This is coverage but that ain't hurting anyone.
> Need nay must have a make target to run test without requirements

- CHANGELOG.rst
- st2actions/st2actions/runners/remote_script_runner.py
- st2actions/tests/unit/test_paramiko_remote_script_runner.py
- st2tests/st2tests/config.py
Noticed this issue in st2build001. To use the new runner in st2build001, we need this patch in 0.13.1.
> cwd for remote_script should use cwd runner param

- contrib/linux/actions/workflows/diag_loadavg.yaml
It refers to `slack` pack not installed by default, thus failing. 
Should redo it with proper notification.
> Fix linux.diag_loadavg

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_rules.py
- st2common/st2common/models/api/rule.py
- st2tests/st2tests/fixtures/generic/rules/rule_no_enabled_attribute.yaml
I personally couldn't reproduce it since we set a default value in the RuleAPI jsonschema, so the default value (`True`) should be used.
In any case I pushed a change so we now follow the same pattern as we do for actions.
> Don't explode if user doesn't include "enabled" attribute when creating a rule

- CHANGELOG.rst
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
This issue was originally discovered by @enykeev a while ago, but I some how missed the JIRA comment - https://gist.github.com/enykeev/b535696c7ba88c2042cf.
As far as the correctness goes - the result was correct from the code and DB perspective, but not something a user would expect. The reason why was correct from the code perspective is that we did `-start_timestamp` ordering which means if you used `timestamp_gt` filter and `limit 1` we would always return first item from the result set which is always the very latest execution.
This pull request changes the behavior so it's more in line with what a user would expect:
```bash
curl http://127.0.0.1:9101/v1/executions | jq .[].start_timestamp
"2015-08-31T09:41:52.775853Z"
"2015-08-31T09:41:41.508933Z"
"2015-08-31T09:41:23.218543Z" …
```
> Fix executions start_timestamp_lt and start_timestamp_gt filtering

- tools/launchdev.sh
Usage improvements -
Usage: `tools/launchdev.sh [start|stop|restart|startclean] [-r runner_count] [-s]`
Note : `tools/launchdev.sh [start|stop|restart|startclean] [runner_count]` is now deprecated.
> Some options for launchdev

- tools/st2ctl
Redirect to /dev/null instead of /tmp/st2_startup.log
> No more st2_startup.log

- .travis.yml
- scripts/travis/setup-mistral.sh
* Synchronize Mistral Installation script for Travis with recent `st2_deploy` changes.
* PR for st2 [`master`](https://github.com/StackStorm/st2/tree/master) branch now should use  `MISTRAL_STABLE_BRANCH="master"`
* Otherwise use `MISTRAL_STABLE_BRANCH="st2-0.13.0"`
Fixes #1925
> Fix Travis builds for Mistral

- st2common/st2common/models/db/__init__.py
- st2common/st2common/persistence/base.py
- st2common/st2common/rbac/migrations.py
- st2common/tests/unit/test_rbac.py
* Implemented an insert method and used that to add Roles to the system to avoid exceptions.
* The insert method is clear but the same could've been achieved by adding the log_as_debug property to add_or_update method. 
There is already an update method but that is different from add_or_update. We may still need to iterate on the 2 methods and see which way to go. I am not motivated to invest more time here as we may be moving away from mongo anyway so why bother.
> [RFR] Insert with log_error as debug flag

- tools/st2_deploy.sh
Community fix, covers issue when users trying to run `st2_deploy.sh` from user with insufficient rights.
> Check if st2_deploy.sh is launched from superuser

- contrib/core/actions/send_mail/send_mail
- contrib/core/actions/sendmail.yaml
In the send_mail script, BODY was grabbing everything by using $@, including the new content_type parameter. So to fix, the two parameters needed switched.
Also, it looks as though BODY was still being set, although empty, which was throwing off the send_empty_body tests. New tests have been made and verified.
> Sendmail Action Fixes

- st2common/st2common/models/api/rule.py
As for now, in order to create a rule that doesn't send any parameters to the action, we need to specify an empty object as the parameters:
action:
parameters: {}
> Some cases (e.g. core.st2.IntervalTimer) don't require sending parameters to the action

- st2api/st2api/controllers/v1/rules.py
- st2api/st2api/controllers/v1/ruleviews.py
- st2api/tests/unit/controllers/v1/test_rule_views.py
- st2common/st2common/models/api/rule.py
- st2tests/st2tests/fixtures/generic/actions/action2.yaml
- st2tests/st2tests/fixtures/generic/rules/rule4.yaml
- st2tests/st2tests/fixtures/generic/rules/rule5.yaml
- st2tests/st2tests/fixtures/generic/triggertypes/triggertype1.yaml
* Adds extra properties for UI display purpose and returns a RuleViewAPI object
**[API] rules/views**
```
$ http localhost:9101/rules/views/default.rule-99
{
"action": {
"description": "Action that executes an arbitrary Linux command on the localhost.",
"parameters": {
"cmd": "date"
},
"ref": "core.local"
},
"criteria": {},
"enabled": true,
"id": "55e93d6732ed3558db7790df",
"name": "rule-99",
"pack": "default",
"ref": "default.rule-99",
"tags": [],
"trigger": {
"description": "Notification trigger.",
"parameters": {},
"ref": "core.st2.generic.notifytrigger",
"type": "core.st2.generic.notifytrigger"
},
"uid": "rule:default:rule-99"
}
```
**[API] rules**
```
$ time http localhost:9101/rules/default.rule-99
{
"action": {
"parameters": {
"cmd": "date"
},
"ref": "core.local"
},
"criteria": {}, …
```
> [RFR] View controller for rules

- st2common/Makefile
By default, the system python is used during virtualenv creation.  This sets the pythno_binary config option for rhel deployments explicity to python2.7
> Adding python_binary path for rhel6 support

- tools/st2-setup-tests
This fixes the "[Errno 40] Too many levels of symbolic links" issue we observed on the build server.
The problem was that we switched the Python binary, but we didn't re-create the whole virtualenv which would result in weirdness and failures. Now we delete and re-create virtualenv on every script invocation.
> Delete pack virtualenv directory in the st2-setup-tests script

- st2actions/Makefile
- st2api/Makefile
- st2auth/Makefile
- st2client/Makefile
- st2common/Makefile
- st2debug/Makefile
- st2exporter/Makefile
- st2reactor/Makefile
We need local wheels for each of the components so that "st2bundle" can be created.
> Makefiles update: publish st2* wheels into the wheelhouse

- contrib/packs/actions/install.meta.yaml
This commit changes the `packs.install` action metadata from * to `None` with `required: true`. This forces the user to explicitly download packs they want/need versus accidentally getting everything.
> Change `packs.install` meta action to require pack

- instructables/chatops.md
This PR updates the ChatOps instructable to use the correct env variables for `ST2_AUTH_URL`.
h/t @alustweiss on `stackstorm-community`
> Update chatops instructable

- contrib/linux/README.md
This commit adds an example of how to consume the `file_watch_sensor` in the `config.yaml` for the Pack.
> Add example to file_watch_sensor

- st2reactor/st2reactor/sensor/base.py
Very tiny cosmetic change for better IDE support when writing [new Sensors](http://docs.stackstorm.com/sensors.html#authoring-a-sensor)
> Add pydoc for BaseSensor

- CHANGELOG.rst
- st2common/st2common/logging/misc.py
- st2reactor/st2reactor/container/sensor_wrapper.py
* Fix sensor container service so the ``config`` argument is correctly passed to the sensor instances in the system packs. Previously, this argument didn't get passed correctly to the FileWatchSensor from the system linux pack.
* Make sure sensor processes correctly pick up parent ``--debug`` flag. This makes debugging a lot easier since user simply needs to start sensor container with ``--debug`` flag and all the sensor logs with level debug or higher will be routed to the container log.
> Sensor container fixes

- CHANGELOG.rst
- st2actions/tests/unit/test_param_utils.py
- st2common/st2common/models/utils/action_param_utils.py
Previously, `cast_params` would explode with an unexpected error if the provided action didn't exist locally.
This pull request fixes it to throw a ValueError if the action doesn't exist.
This was discovered by @alustweiss on Slack when trying to schedule an execution using hubot and the action referenced in the alias didn't exist (https://gist.github.com/indiggio/aac040b391c0f99a2ead)
> Fix cast params bug

- st2actions/Makefile
- st2api/Makefile
- st2auth/Makefile
- st2client/Makefile
- st2common/Makefile
- st2debug/Makefile
- st2exporter/Makefile
- st2reactor/Makefile
make ST2PKG_VERSION lazily parsed from __init__.py if not defined
> st2 packaging updates

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/info.py
This branch fixes two issues:
1. Make sure action exits with non-zero if pack doesn't exist or if it doesn't contain a valid `.gitinfo` file
2. Correctly search all the pack search paths defined in the config. Previously we only searched ``/opt/stackstorm/packs`` which was hard coded so the action also wouldn't work if the user used a custom packs dir.
This resolves #1986
> Fix "packs.info" action

- contrib/examples/pack.yaml
Caught by @enykeev.
(As mentioned in the other pr which adds a missing pack.yaml to default pack, not having a pack.yaml breaks all kinds of things)
> Add missing pack.yaml to examples pack

- st2client/st2client/commands/action.py
- st2client/st2client/commands/action_alias.py
- st2client/st2client/commands/rule.py
- st2client/st2client/commands/sensor.py
- st2client/st2client/commands/trigger.py
* Overtly verbose listing commands don't provide much value so reducing
the headers to mostly ref, name and description. In some cases enabled
is also included. The general idea is that the list should only be
an overview and provide just enough information to locate an object
quickly and for complete information dig into the objects with get
commands.
```
(virtualenv)manas@st2dev:~/st2$ st2 action list
+-----------------------------------------------------+----------+---------------------------------------------------------------+
| ref                                                 | pack     | description                                                   |
+-----------------------------------------------------+----------+---------------------------------------------------------------+ …
```
> Change headers for cli list commands for consistency

- st2api/st2api/controllers/v1/packviews.py
- st2api/st2api/gunicorn_config.py
- st2api/tests/unit/controllers/v1/test_packs_views.py
Fixed as per https://www.keycdn.com/blog/a-guide-to-http-cache-headers/
* ETag and Cache-Control are the HTTP 1.1 way of handling intermediate caches
* Reduce the max-age to 90s from 24Hrs. This is ok since the browser will request the value but will not necessarily end up retrieving content if content has not changed. However, a backend request will still be made.
> ETag and Last-Modified headers for files

- st2api/in-requirements.txt
Introducing dependencies without adding them into appropriate `in-requirements.txt` can cause inconsistency of packages in the future https://github.com/StackStorm/st2/commit/0ae8fd08bda9ff40d14bb6a79fb92f187e542a9d#diff-8d5ef5953c18fe21054d0958e6e79160R20. @m4dcoder 
New packaging has separate components which are *st2api*, *st2common*, *st2actions* etc.
These components are bundled with their own separate virtual environment, thus missing including dependency into specific `in-requirements.txt` will result in "missing module", even if the global (toplevel) `requirements.txt` contain it...
> fixing in-requirements.txt for previously add mistralclient into st2api

- st2api/st2api/wsgi.py
- st2auth/st2auth/wsgi.py
- st2common/st2common/config.py
- st2common/st2common/models/db/__init__.py
- st2common/st2common/persistence/db_init.py
- st2common/st2common/service_setup.py
- st2reactor/st2reactor/container/sensor_wrapper.py
Initial connection to the database are a bit more resilient with some retry attempts. In some scenarios as the services are coming up it is likely that the DB has not started yet and providing some retry capabilities makes services startup a little more resilient.
Note : This changes does nothing for cases where DB goes down while services are running. That is still likely to require a restart and manifest strangely.
> Retry db connection

- st2common/st2common/services/triggers.py
When retrieving triggers using st2 trigger get, no tags where shown even though they were define in the sensor yaml file.  With these changes tags for triggers are properly stored when registering sensors.
> Add tags support in trigger API

- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2.py
- st2actions/tests/unit/test_mistral_v2_auth.py
- st2common/st2common/config.py
This PR builds on #2002 and updates Mistral runner to use `get_full_public_api_url` function to retrieve a base URL to the API endpoint.
This function and underlying `auth.api_url` config option was added quite a while back. It's purpose was and is to serve as a single source of truth for the public base API URL (think static URL registry). All the clients which need to talk to the API endpoint on the public interface should use this value. Like other clients, Mistral is also just another API client so it should use the same value. If for some reason Mistral needs to talk on a private / different interface we should introduce a new option instead of "abusing" api.host and api.port option (one of the reasons for introducing another option in the past was that listen settings don't always …
> Update mistral handler to use get_full_public_api_url() function

- contrib/packs/actions/pack_mgmt/download.py
- st2common/packaging/debian/postinst
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
* The right permissions for installed packs are assigned at package
install time. Trying to achieve this via git was a non-starter and
likely the wrong approach anyway.
> Assign expected permissions at install time.

- contrib/packs/actions/load.yaml
* opt/stackstorm/packs permission is set to 770 therefore st2ctl needs to run as root
> Run st2ctl reload as sudo

- contrib/packs/actions/pack_mgmt/download.py
- st2common/packaging/debian/postinst
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
* 770 is restrictive and causes local scripts to fail. Switching to 775 should unblock those features. We can work out how to properly support this so that packs can be more secure.
> Switch packs to 775

- st2common/packaging/debian/postinst
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
* Looks like AMI does have examples deployed by default
> fix permissions for examples

- st2common/packaging/debian/install
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
- st2common/setup.py
This way it's consistent with other scripts which are already installed there (trigger-refire, etc.).
On top of that, it easier for user to execute those scripts since they don't need to know the full path.
Eventually, we can also update st2ctl and st2_deploy.sh to use scripts from /usr/bin/.
TODO (eventually):
> Make sure scripts from st2common/bin/* are installed into /usr/bin

- st2common/st2common/rbac/syncer.py
- st2common/st2common/rbac/types.py
- st2common/tests/unit/test_rbac_syncer.py
As discussed on Slack, I'm not a big fan of this approach, but because of the way whole auth and user-creation works (lazy) that's the best option we have right now.
Ideally, eventually we would move from lazy user account creation to something else (e.g. sync defined users or similar).
> [WIP] Update RBAC syncer so role assignments for users which doesn't exist in the DB are still created

- CHANGELOG.rst
- st2actions/st2actions/runners/ssh/paramiko_ssh.py
- st2actions/tests/unit/test_paramiko_ssh.py
From the commit "When consuming stdout and stderr byte streams from paramiko
channel, consume all the raw bytes and then decode. Decoding
chunk as they come won't work because utf-8 is variable
length encoding. When we want to support streaming, this
is going to be a pain."
> Paramiko STDOUT/STDERR UTF-8 decode bug fix. 

- docs/source/_includes/runner_parameters/remote_shell_cmd.rst
- docs/source/_includes/runner_parameters/remote_shell_script.rst
- st2actions/st2actions/runners/ssh/paramiko_ssh.py
- st2actions/tests/unit/test_paramiko_ssh.py
- st2common/st2common/bootstrap/runnersregistrar.py
We already have documentation which clarifies that this parameter needs to contain key material and not a path, and we also have docs with examples which show how to use `@` CLI notation, but users are still stumbling on this so we should do something to mitigate this and save both (ourselves and them) some time.
> Throw more user-friendly exception if uses passes path, not content for the "private_key" parameter

- CHANGELOG.rst
- st2client/st2client/shell.py
- st2client/tests/unit/test_shell.py
This pull request improves token caching in the CLI - it now supports caching tokens for different users.
This means you can easily use multiple CLI config via `ST2_CONFIG_FILE` option or similar without disabling token cache.
On top of that it also adds some tests.
> CLI per user token cache

- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
* values with spaces can be represented either by single or double quotes
> Support single quote in actionaliasexecution

- CHANGELOG.rst
- docs/source/runners.rst
- docs/source/troubleshooting/ssh.rst
- st2actions/st2actions/runners/localrunner.py
- st2actions/st2actions/runners/ssh/paramiko_ssh.py
- st2common/st2common/models/system/action.py
- st2common/st2common/util/misc.py
- st2common/tests/unit/test_misc_utils.py
Found this issue by enabling paramiko on build002. 
It appears Fabric is already stripping '\r' or '\n' or '\r\n' characters from stdout and stderr. https://github.com/fabric/fabric/blob/master/fabric/io.py#L121
70808a0 removes the duplicate stripping from our fabric interface code. 
84aec38 mimics the stripping behavior in both local runner and paramiko runner.
> RFR - Strip '\r' or '\r\n' chars from stdout and stderr

- CHANGELOG.rst
- st2client/requirements.txt
- st2client/st2client/commands/action.py
- st2client/st2client/formatters/execution.py
- st2client/tests/fixtures/execution_get_default.txt
- st2client/tests/unit/test_formatters.py
* Include parameters for it is annoying to not know what the parameters were; lesson learned while working with the CLI in prod
* yaml >> json
__Before__
* Run a command
```
$ st2 run core.local uname
.
id: 560d8c3932ed357fe4f1d4b5
result:
{
"stderr": "",
"succeeded": true,
"stdout": "Linux"
}
```
* View previous execution
```
$ st2 execution get 560d82b032ed357f9a189273
id: 560d82b032ed357f9a189273
result:
{
"stderr": "",
"succeeded": true,
"stdout": "Thu Oct  1 12:00:00 PDT 2015"
}
```
__After__
* Run a command
```
$ st2 run core.local uname
.
id: 560d8bc532ed357fe4f1d4b2
parameters:
cmd: uname
result:
failed: false
return_code: 0
stderr: ''
stdout: Linux …
```
> Execution cli params

- st2common/st2common/rbac/migrations.py
- st2common/st2common/service_setup.py
That's about as ghetto as it gets, but until we invest in a proper schema / data migration framework that's what we are left with.
> Add RBAC migration for deleting a bad (mistyped) role

- CHANGELOG.rst
- st2common/st2common/models/system/paramiko_command_action.py
- st2common/tests/unit/test_paramiko_command_action_model.py
* Local user and remote user do not have to match since anyway the command  will be excuting over ssh.
> Paramiko sudo handling

- CHANGELOG.rst
- st2client/st2client/shell.py
- st2client/tests/unit/test_shell.py
This bug fixes the issue with credentials in the CLI config having precedence over the token specified as en environment variable or as a command line argument.
> Fix token priority and precedence in the CLI commands

- tools/st2ctl
Removes `set -e` on error, which allows services to start/stop cleanly when NG_INIT=true
> No more fail on error for st2ctl

- st2common/st2common/models/db/notification.py
https://github.com/StackStorm/st2/issues/2018
Fixes this log line which is horribly confusing!
```
on_complete="NotificationSubSchema@140374782839888(message="None", data="{u'user': u'lakstorm', u'source_channel': u'chatops_ci'}", routes="[u'notify.default']")(**deprecated**) channels="[u'notify.default']")"
```
> Fix notification model logging to show routes

- tools/st2_deploy.sh
Initially we set PIP=`which pip`. This is empty for ubuntu. After installation, we don't set PIP variable again. So this script was failing. 
For RHEL/Fedora etc, we set PIP=pip2.7 explicitly. So for those, we should be good.
> Fix pip path ubuntu post python-pip installation

- st2common/st2common/services/triggers.py
* Oddly .first() did not return the value that [0] did eventhough
there is a value. It happened for a specific type so likely something
to do with the query and perhaps a bug in mongoengine.
> Switch to using index based lookup instead of first

- st2api/st2api/controllers/v1/executionviews.py
Filter request times out on our staging server with half a million of execution records (more precisely, it takes him 220 seconds to complete while default http timeout is 30).
This PR reverts the changes done in 8307cf7 since we don't have compound keys anymore.
> Speed up filters aggregation

- contrib/packs/aliases/pack_deploy.yaml
This commit adjusts the ordering of aliases for the pack installation action, ensuring that all of the actions work properly.
Fixes #2052
> Adjust alias ordering for packs.install

- CHANGELOG.rst
- docs/source/_includes/runner_parameters/http_request.rst
- st2actions/st2actions/runners/httprunner.py
- st2actions/tests/unit/test_http_runner.py
- st2common/st2common/bootstrap/runnersregistrar.py
Add an immutable runner parameter named verify_ssl_cert for the http runner and set it to False so the user knows that for HTTPS requests SSL cert is not verified. Pass the value to requests.reqest in the HTTPClient.
> Change http runner to not verify ssl cert for https requests

- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/executionviews.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
- st2tests/st2tests/fixtures/history_views/filters.yaml
Since #2059 was not enough to bring filter view performance up to an expected level, we can additionally specify filters we want st2web to query.
Currently, UI only shows four types while server queries and sends nine.
> Control the list of filters from frontend

- docs/source/config/authentication.rst
- docs/source/index.rst
- docs/source/rbac.rst
- docs/source/tutorials/index.rst
- docs/source/tutorials/rbac.rst
This pull request adds docs for the enterprise LDAP backend and clarifies which features are only available in the enterprise edition.
Other changes:
* Moved RBAC "tutorial" from instructables/ to the new Tutorials section in the docs.
> Add docs for the enterprise LDAP backend, enterprise version availability

- CHANGELOG.rst
- st2actions/st2actions/runners/ssh/parallel_ssh.py
- st2actions/st2actions/runners/ssh/paramiko_ssh.py
- st2actions/tests/unit/test_parallel_ssh.py
- st2common/st2common/constants/secrets.py
* Set `return_code` to `-9` on command timeout - this way it's consistent with local runner and old fabric based runner
* If the timeout happens include stdout and stderr which was consumed so far
* Include original exception error message in the `error` attribute of the result object
* Strip environment variable which contains the action specific auth token for the error returned to the user
> Remote runner improvements

- docs/source/install/sources.rst
Those two deps ( `libffi-dev` and `libssl-dev` ) are required for cryptography and pyOpenSSL.
The problem occurs when installing from source inside of a docker container (ubuntu:14.04).
> Add missing dependencies for requests[security]

- st2actions/st2actions/runners/ssh/parallel_ssh.py
Before:
```bash
st2 run core.remote hosts=localhost cmd="echo 'baaaar'; sleep 10" timeout=4
...
id: 561d26ef0640fd213a4b2fd3
status: failed
parameters: 
cmd: echo 'baaaar'; sleep 10
hosts: localhost
timeout: 4
result: 
localhost:
error: 'Failed executing command "export ST2_ACTION_PACK_NAME=core ST2_ACTION_EXECUTION_ID=561d26ef0640fd213a4b2fd3 ST2_ACTION_AUTH_TOKEN=******** ST2_ACTION_API_URL=http://127.0.0.1:9101/v1 && cd /tmp && echo ''baaaar''; sleep 10" on host "localhost": Command didn''t finish in 4 seconds'
failed: true
return_code: -9
stderr: ''
stdout: baaaar
succeeded: false
traceback: "  File "/data/stanley/st2actions/st2actions/runners/ssh/parallel_ssh.py", line 258, in _run_command
(stdout, stderr, exit_code) = client.run(cmd, timeout=timeout)
File …
```
> Better tracebacks in the remote runner result object

- contrib/examples/actions/chains/mistral_examples.yaml
- contrib/examples/actions/mistral_examples.meta.yaml
The mistral_examples WF is mostly used for health check and doesn't need to include all the mistral examples. Only selected examples are included here to test that mistral is installed and configured correctly.
> Modify the mistral_examples chain to run only selected examples

- CHANGELOG.rst
- docs/source/upgrade_notes.rst
- st2api/st2api/controllers/v1/webhooks.py
- st2common/packaging/debian/install
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
- st2common/st2common/services/triggerwatcher.py
- st2common/st2common/transport/reactor.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/st2reactor/timer/base.py
- tools/migrate_messaging_setup.py
- tools/st2_deploy.sh
* Sleeping for 4s between message retrievals causes unnecessary latency.
Reducing to 0 since this is for co-oprative yields anyway so length
should not matter. If it does I promise you we have a much larger problem.
* An ability to define Qs as exclusive to a connection.
* Processing old messages leads to unpredicatable behavior. With the
TriggerWatcher consumers the idea is to 1st read from DB and then
start consuming messages. However, non exclusive Qs cause old messages
to be consumed leading to bugs and unpredicatbale behavior. e.g. and
old create/update/delete might be processed.
* SensorWrapper should not share Qs. This would mean that the messages
end up being distributed across sensor_wrappers. Each sensor_wrapper
should get all messages and choose to process them or not.
Testing …
> (RFR) Reduce watcher sleep

- tools/st2ctl
To normalize behaviors across different OSes, this commit ensures that the environment is properly sourced.
> Ensure st2ctl sources global env

- st2common/st2common/models/db/__init__.py
- st2common/st2common/persistence/trigger.py
- st2reactor/conf/logging.rulesengine.conf
Turns out the check to validate if delete_by_reference actually deleted a TriggerDB was missing. Check brought in therefore should now fix the regression.
> Do not raise delete trigger event on an update of a rule

- contrib/examples/rules/sample_rule_with_webhook.yaml
* On RHEL7 writing to /tmp does not work. Not sure why but it fails causing
test failures. Therefore writing to ~ which should always be allowed.
> Write webhook file to home

- docs/source/install/all_in_one.rst
https://github.com/StackStorm/st2workroom/blob/master/stacks/st2.yaml#L21 has no stack `st2express`, but does have `st2`.
Fixes the following first install issue:
```
[logikal] git clone https://github.com/StackStorm/st2workroom.git st2workroom
cd st2workroom
vagrant up st2expressCloning into 'st2workroom'...
remote: Counting objects: 6520, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 6520 (delta 18), reused 0 (delta 0), pack-reused 6471
Receiving objects: 100% (6520/6520), 14.98 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (3880/3880), done.
Checking connectivity... done.
[logikal] cd st2workroom
[st2workroom] vagrant up st2express                                                                                                      master
Installing the 'dotenv' …
```
> docs/install: reference correct stack

- docs/source/mistral.rst
Update links to Mistral's developer documentation and move the WF execution cancellation section.
> Update mistral docs

- tools/st2_deploy.sh
Failing because `which virtualenv` was used before virtualenv 
got installed.
> Set VIRTUALENV after packages installed

- st2actions/st2actions/runners/windows_script_runner.py
By default powershell would run a script and will NOT quit, waiting for user's commands. Which means powershell process will never quit.
Adding "powershell.exe -InputFormat None" resolves that issue
Also added it on top, so that it's more visible
> Making powershell run in definitely non-interactive mode

- st2client/st2client/shell.py
* Disable SSL warnings before any code path allow the method
to quite the moment it is established that config can be read.
Should be a fairly harmless fix and help with the Ux but by no means is this a stopper. Can possibly pick up after release.
> Disable SSL warnings as early as possible

- st2client/st2client/client.py
- st2common/st2common/config.py
- st2exporter/conf/st2exporter.dev.conf
* Usually mistral binds to 127.0.0.1 and localhost may not
re-direct to 127.0.0.1 therefore safer to use 127.0.0.1.
> Use 127.0.0.1 instead of localhost

- docs/source/reference/packs.rst
* Empty `pack.yaml` lead to a broken pack.
> include reference to pack.yaml

- docs/source/chatops/chatops.rst
- docs/source/chatops/index.rst
- docs/source/config/chatops.rst
- docs/source/config/config.rst
- docs/source/config/index.rst
* moved things around to make key articles show in the left TOC.
* add link from config section.
@jfryman take a look. Sphinx doesn't like 2nd level headers in index, if it finds them there, than the toctree-included files go one level under, and disappear from the nav on the left. I changed the structure to show key points on the left nav with least possible harm to the story. Adjust as needed.
> Adjusted structure for good Nav on the left.

- st2actions/bin/runners.sh
Debian keeps `systemctl` in `/bin`, CentOS/RHEL keeps it in `/usr/bin`. CentOS/RHEL symlinks `/bin` to `/usr/bin`, so this change enables Jessie compatibility.
> Make runners.sh actually work (on Jessie)

- contrib/examples/rules/notify_slack.yaml
- contrib/examples/rules/sample_rule_with_actiontrigger.yaml
- contrib/examples/rules/sample_rule_with_timer.yaml
- contrib/examples/rules/sample_rule_with_webhook.yaml
- docs/source/chatops/notifications.rst
- docs/source/rules.rst
- docs/source/start.rst
1. File name == rule name avoid confusion
2. Remove the unnecessary ``sample.`` prefix.
3. Updated affected docs
> Rename rules and rearrange yaml to flow consistently

- st2actions/packaging/debian/install
Same change as in StackStorm/st2#2077.
Accidentally added a commit I shouldn't have to #2142 , this rectifies that.
> Add bindir to st2actions for debian packages

- docs/source/chatops/aliases.rst
This info is part of the action documentation but I could not find it here and only learned about it after asking in the community slack channel.
> Adding info on action_context variables set by action aliases

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2common/st2common/models/api/base.py
- st2common/st2common/service_setup.py
- st2common/st2common/util/debugging.py
A while back, I was debugging and checking why the output of `st2 execution list` command on our build servers is so slow.
It turns out, most of the time is spend reading data (notably the result attribute which is really large in our case since a lot of workflow actions produce tons of data) from the DB and sending all of this data over wire.
``st2 execution list`` command doesn't even display ``result`` and ``trigger_instance`` attribute by default so it makes no sense to request it.
Similar story for ``st2 execution get`` - we don't use ``trigger_instance`` by default and if user only requests one attribute using --attr option it makes no sense to also request and download other data.
> Improve speed of "execution list" and "execution get" commands

- docs/source/install/all_in_one.rst
- docs/source/install/index.rst
- docs/source/upgrade_notes.rst
* Explain that enterprise license will be entered in same all-in-one installer for users who land on installer page after getting the license.
* Put migration notes and warnings.
> Docs for enterprise license and migration

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/st2client/formatters/table.py
- st2client/st2client/utils/color.py
With this change we now display elapsed time in seconds when using "execution list" and "execution get" commands for all the actions in the "running" state.
This was big annoyance for me every time I was checking things on our build server where we have a lot of long running actions - previously I would need to check current time and start timestamp, but now you can see elapsed time in a glance.
> [CLI] Display elapsed time for running actions / workflows

- contrib/core/actions/announcement.yaml
- st2actions/st2actions/runners/announcementrunner.py
- st2actions/tests/unit/test_announcementrunner.py
- st2api/st2api/listener.py
- st2common/st2common/bootstrap/runnersregistrar.py
- st2common/st2common/models/api/trace.py
- st2common/st2common/transport/announcement.py
An attempt to generalize the idea of st2 posting a message to stream consumer.
It is intended to be drop-in replacement for `hubot.post_results` that will allow us to switch to using streams in hubot without redesigning the whole pipeline top to bottom.
It is also intended to be used as a general way of sending notifications to the public as opposed to `Notification` mechanic for reacting on events within st2 internally. Currently internal Notifications becoming external Announcements by means of rules. Announcements could also be called directly as a part of workflow, same way `hubot.post_message` and `slack.post_message` work right now.
> Introduce Announcements

- CHANGELOG.rst
- pylint_plugins/api_models.py
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2common/st2common/log.py
- st2common/st2common/models/system/actionchain.py
- st2common/st2common/models/utils/action_param_utils.py
- st2common/st2common/util/jinja.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_action_call_no_params.yaml
- st2tests/st2tests/fixtures/generic/actionchains/chain_broken_on_failure_path_static_task_name.yaml
- st2tests/st2tests/fixtures/generic/actionchains/chain_broken_on_success_path_static_task_name.yaml
- st2tests/st2tests/fixtures/generic/actionchains/chain_publish_params_rendering_failure.yaml
This pull request includes some action chain validation improvements.
1. Perform on-success and on-failure task name validation during run time. Previously validation happened during run time which means develop-feedback loop was very slow if user was testing workflow with long running tasks and there was, for en example, typo in the take name referenced in on-success / on-failure. This should speed up the whole develop - test loop since this issues are now detected during "pre_run" phase.
2. Throw more friendly exception when action parameter or "publish" parameter resolving fails. Now we also include task where the exception occurred, parameter name and the actual template string value.
> Action chain validation improvements

- st2reactor/st2reactor/container/manager.py
* Previous behavior was to reload the sensor on any update.
* This change handles the sensor being disabled by only unloading if enabled is set to False.
> Handle sensor being updated with an enabled status of False

- st2reactor/st2reactor/container/process_container.py
* Eliminates a race condition where the process could be respawned before `_delete_sensor` is called.
> Delete sensor from process container before terminating

- CHANGELOG.rst
- contrib/core/actions/http.yaml
- docs/source/runners.rst
- docs/source/upgrade_notes.rst
- st2actions/st2actions/runners/httprunner.py
This changes the type of headers and params ``core.http`` action parameters type from ``string`` to ``object``.
I assume the action was defined before CLI supported complex type so action defined type as string instead of object. This is invalid and incorrect use of the types - the type should indeed be object (dict) since the runner shouldn't be responsible of figuring out and parsing the parameters.
This change is backward incompatible, but I think it's fine. I wanted to make it backward compatible since we support list for parameter `type` attribute but things broke, horrible. I got the CLI to work, but everything else broke down.
On a related note - I think we should also make a change so user can't specify a list for action parameter `type` attribute since things (parameter casting, …
> Change headers and params core.http action parameters type to object

- CHANGELOG.rst
- pylint_plugins/api_models.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_actions.py
- st2api/tests/unit/controllers/v1/test_rules.py
- st2common/st2common/constants/triggers.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/base.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/api/policy.py
- st2common/st2common/models/api/rbac.py
- st2common/st2common/models/api/rule.py
- st2common/st2common/models/api/sensor.py
- st2common/st2common/models/api/trace.py
- st2common/st2common/models/api/trigger.py
- st2common/st2common/models/system/actionchain.py
- st2common/st2common/services/action.py
- st2common/st2common/util/schema/__init__.py
- st2common/st2common/util/schema/action_params.json
- st2common/st2common/validators/api/reactor.py
- st2common/tests/unit/test_api_model_base.py
- st2common/tests/unit/test_api_model_validation.py
- st2common/tests/unit/test_db.py
- st2common/tests/unit/test_model_base.py
- st2reactor/st2reactor/timer/base.py
- st2tests/st2tests/fixtures/generic/rules/date_timer_rule_invalid_parameters.yaml
This pull request introduces support for default values on API model (we already support this for action parameters).
Most of the API models already defined "default" attributes in the JSON schema, but those attributes were actually ignored and not used. Not using those attributes means we need to assign default value in multiple places - you can see a bunch of `getattr` in to_model, etc. This also resulted in a lot of bugs in the past ("rule" has no property enabled, etc.).
That's obviously bad since default values needs to spread and set all around the code base. This pull request resolves this and introduces a consistent interface - default attribute will be set on the model API instance after "model.validate()" is called if the JSON schema defined a default value. This means no more …
> Support for default values on the API models

- CHANGELOG.rst
- conf/logrotate.conf
```bash
-rw-r--r-- 1 root root  14G Nov 10 21:44 st2notifier.log
```
:P
Will cherry pick onto v1.1.1.
> Add missing entry for st2notifier service to logrotate config

- st2common/st2common/models/api/action.py
- st2common/st2common/models/db/actionalias.py
Extending the ChatOps schema, as discussed: 
1. Support custom ack and result parameters.
2. Support aliases.
This PR is complete, but I'm putting it on hold until the changes in hubot-stackstorm are ready to merge as well.
> Modifying the ActionAlias schema

- CHANGELOG.rst
- conf/st2.conf.sample
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2.py
- st2actions/tests/unit/test_mistral_v2_auth.py
- st2common/st2common/config.py
- st2common/st2common/util/api.py
- st2common/tests/unit/test_util_api.py
This change allows operator to configure which URL Mistral uses to talk back to the StackStorm API.
For backward compatibility and by default, it uses full public API url. If needed, user can configure it to use a different URL (e.g. internal URL or local URL on single server deployments).
This should resolve #2203
> Allow Mistral to talk to the StackStorm API using a non public URL

- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/base.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/api/policy.py
- st2common/st2common/models/api/rbac.py
- st2common/st2common/models/api/rule.py
- st2common/st2common/models/api/sensor.py
- st2common/st2common/models/api/trace.py
- st2common/st2common/models/api/trigger.py
- st2common/st2common/models/system/actionchain.py
- st2common/st2common/services/action.py
- st2common/st2common/util/schema/__init__.py
- st2common/st2common/validators/api/reactor.py
- st2common/tests/unit/test_api_model_validation.py
- st2reactor/st2reactor/timer/base.py
This pull request updates schema validation so a default value of None is allowed regardless of the attribute type. Keep in mind that this is only relevant if the attribute with a default value is not provided by the user.
For example, the following will work:
```python
'id': {
'description': 'The unique identifier for the action runner.',
'type': 'string',
'default': None
}
```
And if user provides no value for the `id` attribute, default value of `None` will be used.
This was done for backward compatibility reasons and to make working with some common cases easier.
> JSON schema validators change - allow default value of None regardles of the attribute type

- st2actions/tests/unit/test_mistral_v2_auth.py
Fix unit test to accomdate the additional insecure flag in the authenticate method for the mistralclient.
> Fix mistral auth test

- docs/source/upgrade_notes.rst
We got confused ourselves on the change of YAQL from `$.__env` to `env()`, clarifying with example.
> Docs: clarify env() in upgrade notes

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/aliasexecution.py
- st2api/tests/base.py
- st2api/tests/unit/controllers/v1/test_alias_execution.py
- st2api/tests/unit/controllers/v1/test_alias_execution_rbac.py
- st2common/st2common/util/api.py
This pull request fixes the value of "user" attribute in the "context" of live action created by the alias execution API.
Previously, ``user`` was incorrectly set to system user (``stanley``) instead of the authenticated user which triggered the execution. Not setting the user correctly means RBAC and some other things won't work correctly - token which gets created by the action runner and is available for the duration of the action execution will be tied to the system user (which has no permissions by default) instead of the authenticated user (in workroom case, we create a special use which is used for ChatOps by hubot and we grant that user admin role).
This issue was spotted by @enykeev.
> Fix the value of "user" attribute in the context of execution created by alias execution API endpoint

- docs/source/rbac.rst
This pull request clarifies who is the effective user for RBAC purpose for executions which are triggered via rule and ChatOps.
> Document effective user for the RBAC purposes for executions triggered via rules and ChatOps

- st2common/st2common/constants/pack.py
Without the change, `chatops.format_result` throws an error
```
Virtual environment (/opt/stackstorm/virtualenvs/chatops) for pack "chatops" doesn't exist. If you haven't
installed a pack using "packs.install" command, you can create a new virtual environment using
"st2 run packs.setup_virtualenv packs=chatops" command
```
> Add chatops pack to sandboxing constants

- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
We have several problems with the way ActionAliasFormatParser is implemented now:
1. In hubot we have a regex pattern matching for chatops commands, which in some edge cases isn't caught by the back-end parser. This results in hubot sending a legitimate command which is not recognized or executed. 
2. The parser doesn't match multi-word commands if they aren't quoted or multi-line commands ever. It limits user's flexibility in passing long arguments or making a bot more responsive and, again, "human-like".
3. It would be nice to have full support for regexes in aliases in general: we'll be able to create more flexible commands.
4. @enykeev's catch: there's no support for default params in the middle of the string (his example was `st2 list {{ limit=999 }} actions`).
This PR solves all of …
> Modifying ActionAliasFormatParser to support more flexible chatops

- st2actions/st2actions/runners/actionchainrunner.py
* 	Check if name specified in default is valid. 
* 	Add more data to the error message to help get to the error faster.
Tested a few scenarios (names of chains roughly reflect the test)
1. chain_tests.bad_task_param
2. chain_tests.broken_default
3. chain_tests.broken_fail
4. chain_tests.broken_publish
5. chain_tests.broken_success
6. chain_tests.normal
7. chain_tests.incorrect_action_ref
8. chain_tests.missing_action_ref
9. chain_tests.no_default
The changes here help with `chain_tests.broken_default` and `chain_tests.missing_action_ref`
> Action chain error reporting

- st2api/st2api/controllers/v1/aliasexecution.py
- st2api/tests/unit/controllers/v1/test_alias_execution.py
- st2api/tests/unit/controllers/v1/test_alias_execution_rbac.py
- st2common/st2common/models/utils/action_alias_utils.py
- st2common/st2common/util/jinja.py
- st2common/tests/unit/test_action_alias_utils.py
1. Sending HTTP 201 instead of 200.
2. Formatting ack with jinja if the format string is specified.
3. Sending more context along with the execution id and formatted string for a client to use if desired.
Tests are TBD; I’m submitting this to review and to provide context for the hubot-stackstorm PR that will follow.
> Ack message formatting in AliasExecution

- contrib/chatops/actions/format_result.py
Ultimately I’d like announcement not to fire at all if the body is empty, but it’s a solid first step.
Unfortunately, we can’t use Mistral at this time due to a very high overhead, so as a temporary (I hope) measure I’ll make a corresponding `hubot-stackstorm` PR to skip empty messages.
> Chatops: Make formatter return empty string if result output is disabled

- test-requirements.txt
New version of astroid library on which pylint depends on was released. This version horribly breaks everything.
I just saved you all an hour or more of debugging time :P
> Pin astroid pylint dependency to a working version

- CHANGELOG.rst
- st2client/st2client/commands/trace.py
```
$ st2 trace get 565cd03232ed3551d6e16e77 -j
{
"id": "565cd03232ed3551d6e16e77",
"start_timestamp": "2015-11-30T22:39:46.309136Z",
"trace_tag": "st2.IntervalTimer-348cf727-8489-46c2-9bf6-64501dc98241"
}
[
{
"id": "565cd03232ed3551d6e16e76",
"type": "trigger-instance",
"updated_at": "2015-11-30T22:39:46.309204Z"
}
]
```
```
$ st2 trace get 565cd03232ed3551d6e16e77 -j
{
"action_executions": [],
"id": "565cd03232ed3551d6e16e77",
"rules": [],
"start_timestamp": "2015-11-30T22:39:46.309136Z",
"trace_tag": "st2.IntervalTimer-348cf727-8489-46c2-9bf6-64501dc98241",
"trigger_instances": [
{
"object_id": "565cd03232ed3551d6e16e76",
"updated_at": "2015-11-30T22:39:46.309204Z"
}
]
}
```
> Fix json representation of trace in cli

- st2common/st2common/models/api/action.py
Discussed this with @jfryman yesterday: StackStorm execution details URL will be appended to the end of the ack message by default unless specifically disabled with `append_url: false`.
> Append_url parameter in ack messages

- circle.yml
First meetup with packages CI. Let's see how things work on real `st2`.
- Build packages based on `st2-packages` repo
- Build Docker images from `st2-dockerfiles` repo
- Tagged Docker images for each branch:
- 'latest' tag for 'master' branch
- '1.1.1' tag for 'v1.1.1' branch
- Upload StackStorm component Images to Docker Hub https://hub.docker.com/r/stackstorm/
- Works only for `master` branch pushes for now
> Note that Docker build/deployment stage will be part of Staging server later. Now it's included here for better visbility (have latest Docker Hub images as a bonus).
----
That's what I had for delivery today, so delivering.
Next is work on pushing to Bintray staging repos.
> Include first testing CircleCI config

- circle.yml
See: https://circleci.com/docs/configuration#per-branch-notifications
However this can fully work only when we'll propagate `circle.yml` configs to entire `st2` repository/all branches.
> CircleCI Chat Notification only for major branches

- CHANGELOG.rst
- st2common/st2common/models/db/trigger.py
This pull request adds missing indexes on `trigger_instances_d_b` collection (hitting GET /trigger_instances returned 500 in case there was a lot of data since no index was used).
I also applied "hot fix" on the build server.
```
db.trigger_instance_d_b.createIndex( { occurrence_time: 1 } );
db.trigger_instance_d_b.createIndex( { trigger: 1 } );
db.trigger_instance_d_b.createIndex( { occurrence_time: -1, trigger: 1 } );
```
> Add missing trigger instance indexes

- st2actions/st2actions/handlers/mistral.py
- st2actions/tests/unit/test_mistral_v2.py
The new timeout status causes zombie mistral workflows because the callback handler did not know how to handle the new state.
> Add new entries to mistral status map

- circle.yml
Synchonizing with stackstorm/st2-packages#37 changes
This PR provides support to upload created packages to Bintray staging repos via CircleCI:
* `wheezy_staging`: https://bintray.com/stackstorm/wheezy_staging
* `trusty_staging`: https://bintray.com/stackstorm/trusty_staging
* `jessie_staging`: https://bintray.com/stackstorm/jessie_staging
It builds packages for every push into `st2` `master` (aka `unstable`) branch for the moment. Once we add this file into branch like `v1.1.X` - it enable rules to build/upload `stable` packages.
[![6qfygra 1](https://cloud.githubusercontent.com/assets/1533818/11601183/171c7398-9ada-11e5-8b15-5d852b01c49c.png)](https://circleci.com/gh/StackStorm/st2-packages/167#artifacts)
https://circleci.com/gh/StackStorm/st2-packages/167#artifacts
^^ FYI CircleCI …
> [CircleCI Testing] Enable Bintray uploads

- st2actions/tests/unit/test_execution_cancellation.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
- st2common/st2common/services/action.py
- st2common/tests/unit/services/test_action.py
This bug only manifests currently for the mistral runner. Since the action is in requested state, the workflow execution has not started. The container service invokes cancel for a workflow that doesn't exists and fails.
> Fix cancellation of actions in non-running state

- circle.yml
> For code see: https://github.com/StackStorm/st2-packages/pull/42
~~Web Hook with build metadata to notify `st2 staging box`~~ (cc @lakshmi-kannan) when packages are ready/uploaded into Bintray staging repos:
> `wheezy_staging`: https://bintray.com/stackstorm/wheezy_staging
`trusty_staging`: https://bintray.com/stackstorm/trusty_staging
`jessie_staging`: https://bintray.com/stackstorm/jessie_staging
~~Required ENV variables in CircleCI WEB UI:~~
~~* `ST2_HOOK_URL`~~
~~* `ST2_API_KEY`~~
Example payload received by `st2` box (tested):
```json
{
"packages":[
{
"version":"1.3dev",
"revision":"7",
"distro":"wheezy"
},
{
"version":"1.3dev",
"revision":"8",
"distro":"jessie"
},
{
"version":"1.3dev",
"revision":"8",
"distro":"trusty"
}
],
"circle":{
"CIRCLE_BUILD_NUM":"367", …
```
> [CircleCI Testing] Produce payload after the build for integration with st2

- CHANGELOG.rst
- docs/source/traces.rst
- st2client/st2client/commands/trace.py
- st2client/tests/unit/test_trace_commands.py
- st2common/st2common/models/api/trace.py
- st2common/st2common/models/db/trace.py
- st2common/st2common/services/trace.py
- st2tests/st2tests/fixtures/generic/traces/trace_for_test_enforce.yaml
- st2tests/st2tests/fixtures/traces/traces/trace_execution.yaml
- st2tests/st2tests/fixtures/traces/traces/trace_multiple_components.yaml
- st2tests/st2tests/fixtures/traces/traces/trace_one_each.yaml
- st2tests/st2tests/fixtures/traces/traces/trace_one_each_dup.yaml
* Ability to skip noop triggers. This should help reduce noise
```
(virtualenv)manas@st2dev:~/st2$ st2 trace get 5668aea232ed353b0c46de89
id: 5668aea232ed353b0c46de89
trace_tag: trigger_instance-5668aea232ed353b0c46de88
start_timestamp: 2015-12-09T22:43:46.889177Z
+--------------------------+------------------+---------------------------+---------------------------+
| id                       | type             | ref                       | updated_at                |
+--------------------------+------------------+---------------------------+---------------------------+
| 5668aea232ed353b0c46de88 | trigger-instance | fixtures.test_passive_tri | 2015-12-09T22:43:46.88924 |
|                          |                  | gger.dummy                | 1Z                        |
| …
```
> More trace improvements

- CHANGELOG.rst
- docs/source/rules.rst
- st2reactor/st2reactor/cmd/rule_tester.py
- st2reactor/st2reactor/rules/filter.py
- st2reactor/st2reactor/rules/matcher.py
- st2reactor/st2reactor/rules/tester.py
- st2reactor/tests/unit/test_tester.py
- st2tests/st2tests/fixtures/generic/rules/rule1.yaml
- st2tests/st2tests/fixtures/generic/triggerinstances/trigger_instance_2.yaml
* Rule tester now support objects already present in the DB.
* This tool now works with both objects from the file system and objects
from the DB in any combination.
* Bringing DB support required config-file support, leading to oslo.config,
leading to the litany of troubles with oslo config and argparse in same app.
This has evolved into some compromises and a not so friendly help interface
but the rule-tester is atleast more capable.
* There is some extra logging and rule_tester specific extra_info making the
output somewhat verbose but it possibly leads to more usable tool.
* Using DB implies config now needs to be supplied. This also means lots of ugly log statements unfortunately. Also, even if DB connection is not required the way common_setup work we will enable it anyway. Can try …
> Validate ti rule

- CHANGELOG.rst
- conf/st2.tests.conf
- st2common/st2common/bootstrap/actionsregistrar.py
- st2common/st2common/bootstrap/aliasesregistrar.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/bootstrap/policiesregistrar.py
- st2common/st2common/bootstrap/rulesregistrar.py
- st2common/st2common/bootstrap/sensorsregistrar.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/content/loader.py
- st2common/tests/integration/test_register_content_script.py
- st2common/tests/unit/test_content_loader.py
- st2tests/st2tests/fixtures/dummy_pack_4/pack.yaml
This pull request adds `--register-fail-on-failure` flag to the resource registrar script. This value defaults to `False` so it's fully backward compatible and the default behavior doesn't change.
If this flag is provided, registrar will fail and exit with non-zero if a registration of any resource fails (validation error, etc.)
This will come handy in a new st2contrib test task which I'm working on - this task will fail if any of the resource registration fails (we don't want broken definitions in the repo and we want to fail early and loudly).
P.S. Yes I know those files new more refactoring love, there is sadly still tons of duplicated code (I already did some of the refactoring in the past, but it needs a lot more love).
> Add flag to register content script to fail on failure

- st2tests/st2tests/mocks/sensor.py
When testing a pack unit test for a sensor that calls `get_logger` in it's `__init__` method, I observed a traceback:
```
File "/st2contrib/packs/plexxi/tests/test_plexxi_event_sensor.py", line 31, in test_run
sensor = self.get_sensor_instance()
File "/st2/st2tests/st2tests/base.py", line 440, in get_sensor_instance
instance = self.sensor_cls(**kwargs)  # pylint: disable=not-callable
File "/st2contrib/packs/plexxi/sensors/plexxi_event_sensor.py", line 78, in __init__
self._logger = self._sensor_service.get_logger(name=self.__class__.__name__)
File "/st2/st2reactor/st2reactor/container/sensor_wrapper.py", line 71, in get_logger
logger_name = '%s.%s' % (self._sensor_wrapper._logger.name, name)
AttributeError: 'MockSensorWrapper' object has no attribute …
```
> Bug Fix: add get_logger function to MockSensorService

- conf/st2.tests1.conf
- st2common/tests/integration/test_register_content_script.py
- st2tests/st2tests/fixtures/packs_1/dummy_pack_4/pack.yaml
This PR adds a regression test case for this scenario - https://github.com/StackStorm/st2/pull/2298.
It makes sure the script doesn't throw if a pack directory is missing directory for some resource which is to be registered (sensors/, etc.).
> Add a regression test case for register content script

- CHANGELOG.rst
- docs/source/development/pack_testing.rst
- st2common/tests/unit/test_unit_testing_mocks.py
- st2tests/st2tests/mocks/sensor.py
This pull request updates `MockSensorService.get_logger` method to return an instance of `Mock` class. This allows user to assert that a particular message has been logged / logger method has been called with particular arguments (you can find an example of how to do that in the tests below).
The reason why I have decided to simply use Mock class instead of re-inventing the wheel is that it does the job and it exposes a familiar Mock interface.
> Add missing MockSensorService.get_logger method

- st2actions/st2actions/runners/nooprunner.py
The noop runner is missing the get_runner function that is needed during runner import.
> Add get_runner function to noop runner

- st2common/st2common/util/param.py
- st2common/tests/unit/test_param_utils.py
As a result of #2288, we have a regression when action parameter without default `p1: {}` overrides runner parameter with default value `p1: {default: '...'}` resulting in a final parameter rendering as `None` instead of runner parameter default.
Kudos to @manasdk 
STORM-1924 #resolve
> Fix param dependency override regression

- circle.yml
Synchronize repo naming.
This will upload CentOS7 packages to https://bintray.com/stackstorm/el7_staging Bintray repository.
Related to https://github.com/StackStorm/st2-packages/pull/47
> Follow Bintray repo naming for Centos/RHEL builds

- contrib/core/actions/send_mail/send_mail
In text/plain version, the newline characters show literally in the body of the email.  This solution achieves the desired "double-spaced" formatting.
> Remove newline characters in sendmail

- docs/source/policies.rst
* typo in YAML for *concurreny.attr*
* there are no users in Redis
> Fix typos in Policy Wiki

- docs/source/chatops/chatops.rst
In my ST2 installation (Ubuntu 14.04, using 'curl -sSL https://install.stackstorm.com/ | sudo sh'), the Hubot instance runs in a Docker container, and is controlled via /etc/init.d/docker-hubot.
> Fix Hubot restart command

- Makefile
- requirements.txt
- scripts/fixate-requirements.py
#2322 was causing workroom to fail in a weird manner (I couldn't track down the root cause in a short time frame I spend debugging it).
For now, I just decided to not include `virtualenv` in top-level `requirements.txt`.
This won't affect the new packages packages since they use package / component specific `requirements.txt` file (and not the top-level one), but it will prevent workroom failures.
In the future, we should also dig in, track down the root cause and see why this is causing the workroom failure.
> Skip virtualenv from top-level generated requirements.txt file

- contrib/examples/actions/workflows/mistral-env-var.yaml
- docs/source/actions.rst
- docs/source/auth_usage.rst
- docs/source/authentication.rst
- docs/source/chatops/chatops.rst
- docs/source/start.rst
- st2client/README.rst
There will be a lot of confusion next couple of month related to this new schema and how port and path corelate and when you should use one or the other.
The rule of thumb I used while making this commit and suggesting you should use when in doubt is rather simple:
> `https://example.org/api` is a public url and should be used for external services talking to st2 (webhooks, browsers, off-server or potentially off-server running services like hubot).
>`http://localhost:9101/` is a private url and should be used for testing or wiring between internal components (so it is ok to use it as a mock in tests, example when testing custom auth is properly set up or to route the request from nginx to st2api).
There's a ton of potentially tricky situations where it's not immediately clear whether it …
> Fix docs mentioning 9100 and 9101 ports

- docs/source/config/config.rst
Updated the list of parameters passed in the example of  RotatingFileHandler args in the "Configure Logging" section of config.rst due to the args list had a additional empty parameter which will throw run time error.
> Updated the "Configure Logging" section

- st2tests/integration/mistral/test_examples.py
The output of the mistral example was changed recently but the test is not updated.
> Fix test for mistral example

- contrib/examples/actions/workflows/mistral-workbook-complex.yaml
Add wait-before to one of the tasks in mistral-workbook-complex to workaround a mistral bug until it is fixed (https://bugs.launchpad.net/mistral/+bug/1530982).
> Add wait-before to mistral example to workaround known bug

- docs/source/conf.py
Quick fix for missed 1.2 version. Need a better fix.
> Fix missing 1.2 version in docs selector

- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
* Previously the execution would be left in a requested state. This way the
execution is put in a failed state and the reasoning is provided.
> Mark execution as failed on ParamExecption

- CHANGELOG.rst
- docs/source/actionchain.rst
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2common/st2common/bootstrap/runnersregistrar.py
- st2common/st2common/util/jinja.py
* Action chain vars are published in the result of an action chain under the `published` property.
* Also, added support for a special `__context` property that can be used in ActionChain, Rules, AliasExecution and Notification sections. This property will help with debugging.
```
---
chain:
-
name: "c1"
ref: "core.local"
params:
cmd: "date"
publish:
date: "{{c1.stdout}}"
on-success: "c2"
on-failure: "c4"
-
name: "c2"
ref: "core.local"
params:
cmd: "echo \"c2: parent exec is {{action_context.parent.execution_id}}.\""
publish:
context: "{{__context}}"
on-success: "c3"
on-failure: "c4"
-
name: "c3"
ref: "core.local"
params:
cmd: "echo c3"
on-failure: "c4"
-
name: "c4"
ref: "core.local"
params:
cmd: "echo fail c4"
default: "c1"
```
```
"result": {
"published": {
"context": "{'date': u'Mon …
```
> Publish action chain vars

- CHANGELOG.rst
- st2client/st2client/commands/keyvalue.py
This pull request allows users to specify datastore item expiration (TTL) via ``--ttl`` option when using ``st2 key set`` command (e.g. ``st2 key set key1 value1 --ttl=60``).
It also updates ``key get`` and ``key set`` command to display ``expire_timestamp`` attribute.
This resolves #2343
> Allow user to specify TTL via "--ttl" option when using "st2 key set" command

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_executions_simple.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/execution.py
- st2common/st2common/util/schema/__init__.py
- st2common/tests/unit/services/test_action.py
- st2common/tests/unit/test_json_schema.py
- st2tests/st2tests/fixtures/generic/actions/local.yaml
JSON schema throws exception if None is passed explicitly to an optional parameter for an action execution.
> Fix explicit none to optional argument on action execution

- CHANGELOG.rst
- docs/source/authentication.rst
This pull request documents previously undocumented feature which was only used by st2web.
We decide to document it, because there are more scenarios where you can't specify auth token / API key in the headers (e.g. third party services which don't allow you to send custom headers) and where this approach comes handy.
Resolves #2328.
> Document how to send auth token / API key in the query param

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actions.py
- st2api/tests/unit/controllers/v1/test_actions.py
- st2common/st2common/exceptions/action.py
- st2common/st2common/util/schema/__init__.py
- st2common/st2common/validators/api/action.py
- st2common/tests/unit/services/test_action.py
- st2tests/st2tests/fixtures/generic/actions/action1.yaml
- st2tests/st2tests/fixtures/generic/actions/action2.yaml
- st2tests/st2tests/fixtures/generic/actions/action3.yaml
- st2tests/st2tests/fixtures/generic/actions/action_4_action_context_param.yaml
- st2tests/st2tests/fixtures/generic/actions/async_action1.yaml
- st2tests/st2tests/fixtures/generic/actions/local.yaml
- st2tests/st2tests/fixtures/generic/actions/workbook_v2_many_workflows.yaml
Validate that only a selected set of attributes can be overriden for any runner parameters. It does't make sense to let an action parameter override the type in the runner parameter. Also, this will fix a bug where a partial dict in the action parameter will completely override the runner parameter. In the case where type is not defined in the action parameter, the runner parameter will no longer have a type after the override.
> Fix overrides of runner parameter attributes

- CHANGELOG.rst
- docs/source/_includes/runner_parameters/http_request.rst
- st2common/st2common/bootstrap/runnersregistrar.py
The type for the headers param should be object.
> Fix type for the headers param in the http-request runner

- contrib/linux/actions/cp.yaml
- contrib/linux/actions/file_touch.yaml
- contrib/linux/actions/lsof.yaml
- contrib/linux/actions/lsof_pids.yaml
- contrib/linux/actions/netstat.yaml
- contrib/linux/actions/netstat_grep.yaml
- contrib/linux/actions/pkill.yaml
- contrib/linux/actions/rsync.yaml
- contrib/linux/actions/scp.yaml
- contrib/linux/actions/vmstat.yaml
The position attribute cannot be overridden for the cmd parameter in the run-remote runner.
> Fix parameter override in actions of linux pack

- st2tests/integration/mistral/test_wiring.py
On cancel, the mistral querier no longer waits for tasks to complete due to the runaway action triggers bug.
> Fix mistral integration test on workflow cancellation

- st2common/bin/st2ctl
Explicit `#!/bin/bash` is preferred for tests in `st2-packages`
See:
https://circleci.com/gh/armab/st2-packages/404
https://github.com/StackStorm/st2-packages/pull/64
> Change shebang in new st2ctl

- CHANGELOG.rst
- st2actions/tests/unit/test_actionchain.py
- st2common/st2common/models/utils/action_param_utils.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_invalid_parameter_type_passed_to_action.yaml
With this pull request we now throw a more friendly error message when casting a parameter value to the type defined in the schema fails.
Previously, if casting would fail (e.g. value doesn't contain the right type), a very cryptic error similar to the one below was returned.
```python
return ast.literal_eval(x)
File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
return _convert(node_or_string)
File "/usr/lib/python2.7/ast.py", line 79, in _convert
raise ValueError('malformed string')
ValueError: malformed string
```
Keep in mind that the actual error message could be different because it depends on the actual value (`ast.literval_eval` will throw a different error depending on the value).
Now error now includes the offending parameter name, value and type as shown below:
```python …
```
> Throw a more friendly error message if casting a param value fails

- st2actions/st2actions/config.py
--always-copy breaks on RHEL boxes. And also this shouldn't be enabled by default because old packages don't require them.
> Remove --always-copy from default options

- CHANGELOG.rst
- st2actions/st2actions/runners/remote_script_runner.py
- st2actions/st2actions/runners/ssh/paramiko_ssh_runner.py
- st2actions/tests/unit/test_paramiko_remote_script_runner.py
Before this fix, remote script runner based on the new paramiko SSH runner would throw an exception instead of correctly reporting an error if a top-level error occurred (e.g. copying artifacts to remote hosts failed or similar).
I noticed this issue on the build server yesterday and it's quite easy to replicate it.
```bash
error: '''bool'' object has no attribute ''get'''
traceback: "  File "/data/stanley/st2actions/st2actions/container/base.py", line 116, in _do_run
(status, result, context) = runner.run(action_params)
File "/data/stanley/st2actions/st2actions/runners/remote_script_runner.py", line 97, in run
status = self._get_result_status(result, cfg.CONF.ssh_runner.allow_partial_failure)
File "/data/stanley/st2actions/st2actions/runners/ssh/paramiko_ssh_runner.py", line 169, in …
```
> Fix a bug with the top-level error reporting in the new SSH runner

- st2client/st2client/commands/action.py
With this change we now also display action parameters by default when using "st2 execution get" on workflow actions.
This will save everyone from issuing another command or using "-d" option. It's also worth mentioning that "-d" is not exactly the same since it includes a lot of other noise and doesn't really satisfy "at a glance" requirement.
Before:
After:
I get irritated by this every time I'm debugging st2workroom test issues. I always need to execute another command to figure out if the execution refers to Ubuntu / RHEL. With this change, it will save me (and other people) that hassle.
> Display action parameters in "st2 execution get" output for workflow actions

- CHANGELOG.rst
- st2actions/st2actions/container/base.py
- st2tests/integration/mistral/test_wiring.py
Cancellation of task execution was not communicated to mistral workflow which leaves the workflow execution in RUNNING state.
> Fix execution cancellation for task of mistral workflow

- st2tests/integration/mistral/test_wiring.py
The two tests were using the same key value pair and conflict with each other when run concurrently.
> Fix integration test for mistral workflow rerun

- contrib/examples/actions/mistral-test-rerun.yaml
- contrib/examples/actions/workflows/mistral-test-rerun.yaml
- st2tests/integration/mistral/test_wiring.py
Use temp file instead of st2 datastore to hold the value for the switch.
> Fix integration test for mistral rerun

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actions.py
- st2api/tests/unit/controllers/v1/test_actions.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/notification.py
- st2common/tests/unit/test_db.py
- st2common/tests/unit/test_notification_helper.py
Original bug: https://github.com/StackStorm/st2/issues/2378 (Thanks @ charlottestjohn).
Summary:
1. Register action with notify
2. Remove notify section from meta. Register notify again.
3. Check action. You'll still see notify section 
Repro: 
See https://gist.github.com/lakshmi-kannan/3891705755dbafa8b82c for repro. 
What happened?
We use embedded document model for notify in action model. If notify is unspecified, we set notify to None. Mongoengine interprets `None` as unmodified field therefore doesn't delete the embedded document. 
Solution: We now explicitly set the embedded document to {} instead of None. 
TODO:
> RFR: When notify is not specified, mongoengine requires an empty doc

- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
Fixes #2399
Fixes another unfiled bug with parser not recognizing spaces at the
beginning of the string (where `acl {{ a }}` would match both `acl 123`
and `acl123`).
Needs a bit of testing with Hubot.
> ChatOps argument parsing fix

- circle.yml
Since https://github.com/StackStorm/st2-packages/pull/65 is complete, we can start building `el6` packages and deploying them to https://bintray.com/stackstorm/el6_staging.
Don't merge it yet. Needs +1 CircleCI container, see:
https://stackstorm.slack.com/archives/stackstorm/p1452692070023864
> Build el6: RHEL6/CentOS6 packages

- Makefile
The latest pip version 8.0.0 is causing problem on making requirements.
> Fix pip version temporary for make

- CHANGELOG.rst
- st2common/st2common/logging/misc.py
Releasing a lock is not necessary fatal - it could simple indicate that the lock wasn't acquired in the first place.
Part of #2398
> Ignore lock release errors when re-opening log files

- st2common/bin/st2ctl
Provides fix for https://github.com/StackStorm/st2/pull/2367/files#r49736848
when `service` command is not available under `CentOS7` (replaced by `systemctl`).
Tested/Verified.
> Detect service manager for new st2ctl

- st2api/tests/unit/controllers/v1/test_executions_simple.py
- st2common/st2common/models/api/base.py
- st2common/st2common/rbac/decorators.py
In a lot of scenarios before those changes, API incorrectly returned status code 500 (internal server error) instead of 400.
Fixed scenarios:
1. RBAC decorator previously threw an invalid Exception if user didn't pass a required id argument to get / put / delete controller method
2. Internal server error was incorrectly thrown if `ValueError` exception was thrown during input data object validation (`ValueError` indicates validation error).
Before:
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ curl -X PUT http://127.0.0.1:9101/v1/apikeys/
{
"faultstring": "Internal Server Error"
}(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ 
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ python ./st2client/st2client/shell.py execution re-run …
```
> API status code improvements

- st2client/st2client/commands/action.py
- st2client/tests/unit/test_shell.py
Get rid of mutually exclusive args since positional parameters cannot exist in mutually exclusives.
Doing so also means that a user can provide `--task` and `--parameters` together. The API guards against this condition by throwing back an error so that nothing bad actually happens.
Perhaps a better approach would be to have a standalone `st2 execution re-run-workflow --tasks <task-name>` however that is a much bigger change and could be handled later.
In case parameters and tasks are mixed -
```
$ st2 execution re-run 569f2c7932ed352e386fc284 cmd=hostname --tasks y
ERROR: 500 Server Error: Internal Server Error
MESSAGE: Parameters override is not supported when re-running task(s) for a workflow. for url: http://127.0.0.1:9101/v1/executions/569f2c7932ed352e386fc284/re_run
```
> Get rid of mutually exclusive args in re-run

- contrib/examples/actions/mistral-test-rerun-subflow.yaml
- contrib/examples/actions/workflows/mistral-test-rerun-subflow.yaml
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2_rerun.py
- st2tests/integration/mistral/test_wiring.py
On re-run of mistral workflow, task name can be fully qualified. The mistral runner will drill down to get the task ID in the subworkflow to initiate the re-run of the task.
> Implement re-run of task in subworkflow for mistral

- contrib/examples/actions/mistral-test-rerun-subflow-with-items.yaml
- contrib/examples/actions/mistral-test-rerun-with-items.yaml
- contrib/examples/actions/workflows/mistral-test-rerun-subflow-with-items.yaml
- contrib/examples/actions/workflows/mistral-test-rerun-with-items.yaml
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2_rerun.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
- st2client/st2client/commands/action.py
- st2client/st2client/models/core.py
- st2client/tests/unit/test_shell.py
- st2tests/integration/mistral/test_wiring.py
Add option to st2 execution re-run to either re-run all or only failed iterations for with-items task for mistral workflow.
> Add support to handle re-run of with-items task for mistral workflow

- st2client/setup.py
dist_utils relies on some functionality which is only available in newer versions of pip. Right now there is a bug / issue where old version of pip is used on packs virtual environments on Ubuntu.
This is a temporary work around until we ensure that a more recent version of virtualenv is installed everywhere where st2client is installed (system wide and virtualenv used by packs).
> Manually specify dependencies in st2client setup.py

- st2auth/st2auth/cmd/api.py
I also set register_internal_trigger_types=False to be more explicit.
> Do not run RBAC migrations as part of auth startup

- contrib/chatops/actions/format_execution_result.py
Our ChatOps pack uses a fresh Jinja environment without our custom filters for execution results, as @emptywee pointed out. Switching to jinja_utils from st2common adds additional filters and makes the environment consistent with other places where we use Jinja across st2.
@enykeev: please test and confirm. I’m not sure why you didn’t choose to use jinja from st2common to begin with, so I’m not gonna merge without your +1.
> ChatOps formatting: use Jinja from st2common

- st2common/st2common/triggers.py
It looks like if there is a conflict in trigger type registration, we simply bubbled up the exception to the point the API process shut down. Now we catch the exception, log as a warning and move on. 
This should address intermittent build failures in circle ci such as https://circleci.com/gh/StackStorm/st2-packages/310
> Handle exception if trigger registration fails

- st2common/st2common/services/action.py
* Checking if notify is empty got a little more involved commit
0070e1aafd8019e6440ce1538e0e6bcfb2b531fc.
* Specifiying {} means we get back an empty NotificationSubSchema
back and this means that a simply checking the truthy value of
NotificationSchema is now incorrect because of how mongoengine
interprests {} for embedded documents.
> Fix check for if notify is empty

- circle.yml
Part of upstream rename https://github.com/StackStorm/st2-packages/pull/131
We also have `circle.yml` in `v1.3` and `v1.3.1` branches to fix. Do it later, once we merge upstream changes/test.
> Rename st2bundle to st2

- st2auth/st2auth/wsgi.py
- tools/launchdev.sh
By trying to fix a nasty import level registration in https://github.com/StackStorm/st2/pull/2437, I accidentally broke wsgi method for spinning auth. This PR fixes that. 
I also make changes to launchdev so uwsgi auth can be spun up for quick testing. With auth enabled, I am able to get token just fine.
> Register oslo opts in uwsgi config for auth

- CHANGELOG.rst
- st2client/st2client/client.py
- st2client/st2client/utils/httpclient.py
- st2client/tests/unit/test_client.py
Right now we only allow user to pass a string (path to the CA bundle) as a value for the `cacert` argument.
`requests` also allows user to pass in a boolean, but we don't support this use case right now. If boolean `Rrue` is passed for the `verify` argument requests will use bundled CA bundle or CA bundle from the system store (http://docs.python-requests.org/en/latest/user/advanced/#ca-certificates).
I know that the argument is named `cacert` so also allowing user to pass in boolean values makes for a bit of a confusing API, but I don't have many other options right now which don't require bigger refactoring.
Related to https://github.com/StackStorm/st2contrib/pull/376
> Allow user to specify a boolean for a "cacert" argument value

- st2actions/st2actions/runners/python_action_wrapper.py
* calling db_setup prior to parsing config means that default values of
connection settings are used. These default value are usually correct
in dev environments making it hard to catch the issue locally.
Luckily we had a quirky enough CI which broke the assumption and picked
up the failure.
> Call db_setup after config is parsed

- tools/launchdev.sh
* ps -e differ on linux ubuntu14 and osx which means something that works
in one place will not work at another. On ubuntu14 the -e only returns the
binary name as opposed to the full command string which osx provides more
information.
* ps -ef is more or less the same atleast in the regard we really care so
sufficient to continue supporting both osx and u14 as development environments.
> Make ps somewhat portable

- circle.yml
To clarify/synchronize: 
- CircleCI build is triggered only when you push changes to `master` or `vX.Y` like `v0.13` branch
- CircleCI build is never triggered when you push changes in patch `vX.Y.Z` branch like `v0.13.3`
- Package version is always obtained from local file [`st2common/st2common/__init__.py`](https://github.com/StackStorm/st2/blob/master/st2common/st2common/__init__.py#L16)
- Docker TAG is always:
- `latest` for `master` branch
- obtained from version [`st2common/st2common/__init__.py`](https://github.com/StackStorm/st2/blob/master/st2common/st2common/__init__.py#L16) for branches like `v0.13`
- See: https://hub.docker.com/r/stackstorm/st2api/tags/
> Tested all the logic once again on my own `st2` fork.
Related to another change in `st2-packages` repo: …
> Synchronize circle.yml with st2 CI process & versioning for master

- conf/nginx/st2.conf
I was thinking if this is the right place for mistral ngnix configuration. Best would be to have such a thing in mistral fork and ship multiple configurations. I am not a nginx expert. It also looks like st2web configuration is here. Oh well! 
```
vagrant@pkgtestingbox:~$ http --verify=no https://192.168.1.17/mistral_api/v2/executions
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 850
Content-Type: application/json; charset=UTF-8
Date: Fri, 05 Feb 2016 00:39:33 GMT
Front-End-Https: on
Server: nginx/1.4.6 (Ubuntu)
X-Content-Type-Options: nosniff
{
"executions": [
{
"created_at": "2016-02-04 23:19:34.523955",
"description": "",
"id": "1c254559-a9ae-4e7e-a98a-e3b20076b495",
"input": "{\"cmd\": \"date\"}",
"output": "{\"stdout\": \"Thu Feb  4 15:19:35 PST 2016\"}",
"params": …
```
> Ngnix rule for mistral_api redirect

- CHANGELOG.rst
- st2api/st2api/controllers/v1/webhooks.py
- st2api/tests/unit/controllers/v1/test_webhooks.py
This pull request works on top of #2473 and adds support for determining body type based on the `Content-Type` header value.
Now that we have this code in place we could also easily add support for other Content-Types in the future if needed. (e.g. YAML or XML).
> Allow webhooks endpoint request body to also be url encoded form data

- st2common/st2common/hooks.py
Response body generated by those controllers can contain a lot and / or binary data.
Resolves #2476.
> Don't log the response body of the file(s) controllers

- contrib/chatops/actions/templates/default.j2
As reported in https://github.com/StackStorm/st2/issues/2456. I have no idea why that replace is even there, so I’ll test for a while and merge if nothing’s broken. If anyone knows anything about this mysterious replace, speak up, but even @enykeev does not. :P
> ChatOps pack: don't replace /n with @

- circle.yml
Currently we upload packages to 5 Bintray repos in parallel.
Same we do for 7 Docker containers, uploaded to Docker Hub in parallel.
This saves time, the improvement is huge.
Existing problem described in stackstorm/st2-packages#74: when any of parallel jobs fail - we don't show failed exit code with current basic bash `& wait` implementation, which means in CI deploy task always marked as "succeeded".
Correct behavor is fixed with help of `parallel` tool, which is right way and catches exit code from all the jobs.
See: [GNU Parallel Man](https://www.gnu.org/software/parallel/man.html)
-----
Researched/experimented a bit with bashing and `xjobs`, `xargs`, `parallel`, `pexec` tools.
`parallel` is the best fit here.
See https://github.com/StackStorm/st2-packages/pull/164
> Fix CircleCI Bintray parallel uploads

- CHANGELOG.rst
- st2common/st2common/log.py
- st2reactor/st2reactor/container/sensor_wrapper.py
__Updates__
* Make sure the `getLogger()` call does not append more then one `st2.` prefix to the logger name to preserve the logging name hierarchy. This code from `st2reactor/st2reactor/container/sensor_wrapper.py` was creating loggers prefixed with `st2.st2.` because `self._sensor_wrapper._logger.name` is already prefixed with `st2.` and the call to `getLogger` would prefix an additional `st2.`:
```
def get_logger(self, name):
"""
Retrieve an instance of a logger to be used by the sensor class.
"""
logger_name = '%s.%s' % (self._sensor_wrapper._logger.name, name)
logger = logging.getLogger(logger_name)
logger.propagate = True
return logger
```
* Include the pack name in the logger named used by sensors since `self._class_name` does not have to be unique across packs
The current default …
> Sensor Logging Fixes

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/tests/fixtures/execution_get_attributes.txt
- st2client/tests/fixtures/execution_get_default.txt
- st2client/tests/fixtures/execution_get_detail.txt
- st2client/tests/unit/test_formatters.py
This should make it easier to see, at a glance, how long it took for the execution to complete and potentially adjust the action timeouts accordingly.
> Include number of elapsed seconds for completed executions in "st2 execution get" CLI command output

- st2common/bin/st2ctl
Testing `st2`/`st2ctl` under Docker with different distros. Part of https://github.com/StackStorm/st2/issues/2409 checks. Fixes: 
Debian wheezy Docker: 
As said before https://github.com/StackStorm/st2/pull/2445, both `mistral-api` and `mistral-server` are handled by `service mistral`.
Instead of `service mistral-api restart` the correct command is `service mistral restart` which handles both.
Instead of adding them in components to start/stop, show `mistral-server` and `mistral-api` statuses separated in `st2ctl status`:
```sh
...
mistral-server PID: 16318
mistral-api PID: 16305
mistral-api PID: 16327
mistral-api PID: 16332
```
Debian Wheezy Docker:
https://gist.github.com/lakshmi-kannan/890933d2823b541701e7 cc @lakshmi-kannan
`initctl: Unable to connect to Upstart: Failed to connect to …
> Various improvements for new st2ctl

- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_action_alias_utils.py
Fixes #2295
@pixelrebel reported a use case where an argument that’s technically not optional (i.e. doesn’t have a default value) is placed inside an optional regex group:
```
update {{hostname}}( {{count}} times)? 
```
With a string like `update google.com` our parser extracts `{{count}}` from the alias and sets the value to “” because it can’t be matched to anything. While a string like this is something you shouldn’t really do in the first place, it’s pretty easy to introduce support for it, and the use case is legit, so I suggest we go for it.
This is a small fix that doesn’t affect parser logic, so it should be fine as soon as Travis is finished, but I’ll wait for someone else to LGTM this first.
> ChatOps: Fixing null optional arguments error

- st2api/st2api/controllers/v1/webhooks.py
- st2api/tests/unit/controllers/v1/test_webhooks.py
- st2common/st2common/util/http.py
- st2common/tests/unit/test_util_http.py
This pull request fixes a bug reported in #2504 and makes sure we also correctly take into account any optional option such as charset which can also be present in the `Content-Type` header value.
Resolves #2504.
> Fix "Content-Type" parsing bug in the webhooks API endpoint

- CHANGELOG.rst
- contrib/linux/actions/wait_for_ssh.py
- contrib/linux/actions/wait_for_ssh.yaml
@jon-middleton originally reported on the Slack community channel that this action uses an incorrect path to the default SSH key file used to authenticate.
The problem is that path is hard-coded in the action parameter default value while it should really be read from the config file since the path is user-configurable and installation specific.
In addition to that, I noticed this action needs some love so I also made some other improvements which make this action more generic and generally usable.
1. Support for password based authentication (previously only key based authentication was supported)
2. Support for non-default SSH ports (previously only 22 was supported)
3. Support for non RSA key types (previously only RSA keys were supported)
4. If neither `password` nor `keyfile` …
> Various improvements in the linux.wait_for_ssh action

- contrib/chatops/actions/post_message.yaml
- contrib/chatops/pack.yaml
This commit adds the `color` parameter to the `chatops.post_message` action. This allows you to specify a particular color for the message when using Slack.
> Allow specifying color for messages posted to Slack via chatops

- CHANGELOG.rst
- st2api/st2api/controllers/v1/webhooks.py
- st2api/tests/unit/controllers/v1/test_webhooks.py
* Leading or trailing slashes in the url coming from the rule
would cause the API to reject webhook requests.
* Normailzing the url to not include trailing or leading / means
that the match is / agnostic and StackStorm does not end tripping
over some silly /.
* URL normalization basically mean multiple version of the URL map
to the same URL.
* Each unique URL gets it own Trigger. Even though the controller
treats `sample`, `/sample` and `sample/` different it still
represents 3 different triggers. Therefore it is necessary to
match the normalized version to all 3 triggers. This is done by
holding a match between normalized to a list of triggers.
> Normalize url in trigger parameters

- CHANGELOG.rst
- Makefile
- contrib/chatops/actions/format_execution_result.py
- contrib/examples/actions/pythonactions/isprime.py
- contrib/examples/tests/test_action_isprime.py
- contrib/packs/actions/check_auto_deploy_repo.py
- contrib/packs/actions/expand_repo_name.py
- contrib/packs/actions/pack_mgmt/delete.py
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- contrib/packs/actions/pack_mgmt/unload.py
- contrib/packs/tests/test_action_check_auto_deploy_repo.py
- contrib/packs/tests/test_action_expand_repo_name.py
- st2actions/st2actions/runners/python_action_wrapper.py
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/st2actions/runners/utils.py
- st2actions/tests/unit/test_pythonrunner.py
- st2common/tests/unit/test_unit_testing_mocks.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- st2tests/st2tests/base.py
- st2tests/st2tests/mocks/action.py
This pull request updates base `Action` class to utilize `action_service` argument and expose datastore management methods via this `action_service` instance variable.
Using `action_service` makes it consistent with sensors and also allows us to expand and add additional functionality to action service in the future.
In addition to that, it includes some other changes:
* Make sure that we pass mock action service and datastore to the Action instance which is available to action unit tests.
* Add some more test for BaseActionTestCase
* Random lint fixes and cleanup
> Python runner actions datastore access changes, action unit testing fixes and lint cleanup

- CHANGELOG.rst
- st2common/st2common/log.py
- st2common/st2common/util/misc.py
This pull request fixes issue reported in #2485.
It makes sure `filename`, `module`, `funcName` and `lineno` `LogRecord` attributes correctly point to the function / method which called the underlying logger method.
Previously they incorrectly pointed to the `log.py` file and `decorate_log_method` function.
I'm not too big of a fan of the implementation, but after doing some more research online it doesn't seem like there are any better and nicer alternatives possible :/
If it ever turns out that this adds too big of a performance overhead (unlikely since the same functionality exists and it's turned on by default in Python stdlib), we can revert this change or look into alternatives (e.g. only add caller info if the format string uses any of those log record attributes).
> Fix "decorate_log_method", make sure LogRecord attributes reflect the correct caller

- contrib/examples/actions/workflows/mistral-with-items-concurrency.yaml
- st2tests/integration/mistral/test_examples.py
Adjust the timing in the workflow to accomodate for delayed in execution due to load.
> Adjust timing in mistral concurrency test

- CHANGELOG.rst
- st2common/st2common/operators.py
- st2common/tests/unit/test_operators.py
This pull request includes the following changes:
1. It introduces new ``matchglob`` criteria operator which provides support for Unix shell-style wildcards (* and ?). This operator should be preferred over ``matchregex`` for simple string matches since it's a lot more straight forward.
2. Update ``matchregex`` operator so `.` character also matches new lines. In most cases where you work with multi line strings you want ``.`` character to also match new lines so that's a more sensible default behavior (people got burnt by this in the past).
This change is backward incompatible (it will make existing regexes a bit less greedy), but I will document this with examples in the upgrade notes and it's unlikely that it's going to badly affect existing regexes (in most cases it will allow users …
> Introduce new "matchwildcard" criteria operator, update "matchregex" so dot (.) also matches new lines

- CHANGELOG.rst
- contrib/linux/actions/rm.yaml
- st2tests/st2tests/base.py
This change makes "-v" (verbose) flag for `linux.rm` action configurable. For backward compatibility reasons it defaults to true.
I noticed `st2cd.st2workroom_st2enterprise_test` tests recently started failing with the following error - https://gist.github.com/Kami/101e707a66f54930c6cd. I believe this is related to the error @lakshmi-kannan found and worked-around in the past (we didn't fully fix it though since it would require writing our own streaming based parser which is an over kill right now).
I believe the issue pops ups because some of the file recently added to the workroom repo contains a non-ascii character in the name so a simple work-around would be to pass `verbose: false` parameter to this action in our workflows. This way what was being done (which includes file names) …
> Allow user to turn off verbose flag in the "linux.rm" action

- conf/nginx/st2.conf
`st2web` has `index.html` as index entrypoint.
Removing unneeded pieces, probably oversight with copy-paste.
> Remove index.php from default nginx for st2web

- st2common/st2common/persistence/auth.py
This operation results in the same underlying query, but it allows us to use profiling stuff I added a while back (profiling stuff doesn't work when using `.objects()` document method to retrieve stuff from the database).
> Use query instead of objects mongoengine filter

- CHANGELOG.rst
- st2actions/st2actions/cmd/actionrunner.py
- st2actions/st2actions/cmd/st2notifier.py
- st2actions/st2actions/cmd/st2resultstracker.py
- st2api/st2api/cmd/api.py
- st2auth/st2auth/cmd/api.py
- st2common/bin/paramiko_ssh_evenlets_tester.py
- st2common/st2common/log.py
- st2common/st2common/util/monkey_patch.py
- st2exporter/st2exporter/cmd/st2exporter_starter.py
- st2reactor/st2reactor/cmd/garbagecollector.py
- st2reactor/st2reactor/cmd/rulesengine.py
- st2reactor/st2reactor/cmd/sensormanager.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- tools/diff-db-disk.py
- tools/st2-analyze-links.py
- tools/st2-inject-trigger-instances.py
Previously, `--use-debugger` flag was not correctly propagated and checked in the child sensor processes which means `thread` module was still patched and this broke remote debugging support (some remote debugger like the pydev and pycharm one rely on thread module not being patched).
Some references:
* https://ask.openstack.org/en/question/815/how-do-i-debug-nova-service-with-eclipse-and-pydev/
* http://debugopenstack.blogspot.si/
I didn't test this end to end since I don't have PyDev installed locally, but I tested it using netcat and it seems to be working. In any case, I will ask Ethan or someone with PyDev to test those changes.
This was reported by Ethan on the IRC.
I also asked Ethan to write a guest blog post on remote debugging sensors with PyDev once this issue has been resolved …
> Make sure "--use-debugger" flag is taken into account in the sensor process

- st2api/st2api/cmd/api.py
- st2common/st2common/triggers.py
Those operations are idempotent so we can simply ignore those errors (e.g. this could occur when using gunicorn with more than 1 worker).
> Ignore conflict / "object already exist" errors during internal trigger types registration

- st2actions/st2actions/cmd/st2notifier.py
- st2actions/st2actions/notifier/config.py
- st2actions/tests/integration/test_notifier.py
- st2common/st2common/constants/scheduler.py
- st2common/st2common/constants/timer.py
- st2reactor/st2reactor/cmd/rulesengine.py
- st2reactor/st2reactor/rules/config.py
- st2reactor/tests/integration/test_rules_engine.py
Ways to disable timer and action rescheduler. This is useful in HA scenarios where these services that are hosted in shared containers do not scale the same way as co-services.
e.g. timer and rulesengine run in the same process st2rulesengine. Timer pretty much needs to be singleton but rulesengine are designed to share the work. The short term solution is to be able to disable timer in certain st2rulesengine containers.
Note : By default there will be no change.
> Ability to disable services

- st2actions/st2actions/handlers/mistral.py
- st2actions/st2actions/query/mistral/v2.py
- st2actions/st2actions/runners/mistral/v2.py
- st2common/st2common/config.py
- st2common/st2common/validators/workflow/mistral/v2.py
Follow up to https://review.openstack.org/#/c/286942/3
This will allow StackStorm to use mistral-api with a self signed SSL cert
> Setup insecure and cacert properties for mistral

- st2common/st2common/models/utils/action_alias_utils.py
@emptywee came up with an alias that has empty strings as defaults:
`{{ secgroup='default' }} {{ flavor='epsilon.2x4x50' }} {{ rhn_channel='' }} {{ ref_server='' }} {{ reboot=true }} devqa deploy {{ hostlist }} zone {{ zone }} project {{ project }}`
While that’s not how I would do it, it’s still a legitimate use case and we should include it, hence this PR.
I’ve also reworked the parser to try and make it more readable. None of the logic has changed (except for inclusion of empty strings, that is), just splitting the code into snippets.
> ChatOps: allowing empty strings as default values

- st2debug/st2debug/cmd/submit_debug_info.py
- st2debug/tests/integration/test_submit_debug_info.py
Follow up for PR #2529, as requested by @Kami.
* Following errors are handled when specify a custom config:
* Config file does not exist
* Config file is not valid YAML
* YAML is not a dict
* Changed `yaml.load` to `yaml.safe_load` to avoid potential for privilege escalation when a non-privileged user is allowed to execute the script as root.
* Added missing docstring for `add_user_info`.
* Added tests to verify that shell command files are created and that the output is correctly written to the files.
* Added tests to verify that custom config does override default options.
Let me know if there are any other test cases you'd like added.
> st2-submit-debug-info #2529 Follow Up

- contrib/core/actions/send_mail/send_mail
- contrib/core/actions/sendmail.yaml
For my use case, I'm writing a workflow that'll
1. query an API and write the results to a file; and
2. email the file as an attachment.
This patch enables `core.sendmail` to send file attachments. There are two things of note here:
1. The `attachments` parameter is a comma-separated `string`instead of an `array`. This can be changed when we have better support for array serialization for shell scripts. (see [discussion](https://stackstorm-community.slack.com/archives/community/p1456864311005045))
2. Only files found locally on the StackStorm host may be sent as attachments currently. We could change `core.sendmail` to a `remote-shell-script` instead of `local-shell-script` with a default host of localhost to make this more flexible. Thoughts?
```
..
id: 56d60990fb3b871d916f8043
status: …
```
> Add support for file attachments in core.sendmail

- conf/nginx/st2.conf
I've also made some changes to Stream API endpoint to fix backward compatibility and make it more compact.
> Fix cryptic error messages in nginx config

- conf/st2.dev.conf
- tools/launchdev.sh
Change the API endpoint address to 0.0.0.0 for the gunicorn config otherwise st2web will not be able to access the API endpoint. Add allow_origin entry to the development st2 configuration file.
> Fix API config for development

- circle.yml
> Part of https://github.com/StackStorm/st2-packages/pull/227
* pushing to `master` of `st2` repo will generate packages based on `master` of `st2-packages`
* pushing to `v1.3` of `st2` repo will generate packages based on `v1.3` of `st2-packages`
* If there is no `v1.3` branch in `st2-packages` repo, then `master` will be used as a fallback
* ^^ This race case would happen after automating branch creation in `st2-packages` repo (`st2` branch was created, but `st2-packages` branch wasn't created yet)
----
From this point `st2` and `st2-packages` repos should have the same branches `vX.Y`.
cc @manasdk to include automated branch creation in `st2-packages` repo as part of release machinery (same as you do for `st2web`).
> Add support for st2-packages branching (master)

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- st2actions/st2actions/config.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/config.py
- st2common/st2common/content/bootstrap.py
- st2common/st2common/util/virtualenvs.py
This flag is to be used in a distributed StackStorm setup where action runner services run on multiple hosts.
In the distributed deployment context, (right now) it's up to operator to ensure register-content script with this flag is ran on every host where action runner service is running. This can be tied into the whole "content distribution" story - user can hook it up as a last step of their "deploy content to the server" story.
TODO:
> Add "--register--setup-virtualenvs" flag to the register-content script

- CHANGELOG.rst
- fixed-requirements.txt
- requirements.txt
- st2api/tests/unit/controllers/v1/test_rules.py
- st2common/in-requirements.txt
- st2common/st2common/constants/triggers.py
- st2common/st2common/validators/api/reactor.py
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_invalid_parameters_1.yaml
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_invalid_parameters_2.yaml
- st2tests/st2tests/fixtures/generic/rules/cron_timer_rule_invalid_parameters_3.yaml
This pull request updates our JSON schema validation code so that the CronTimer now also accepts other cron-like notation (`a-b`, `*/a`, etc.) which is supported by `CronTrigger` in apscheduler (http://apscheduler.readthedocs.org/en/3.0/modules/triggers/cron.html#api).
In addition to that, it also introduces additional validation for CronTimer parameters - this is required since we now allow arbitrary strings for parameter values, but not any arbitrary string is valid `CronTimer` argument value.
> Support crontab like notation for CronTimer trigger

- CHANGELOG.rst
- contrib/chatops/actions/format_execution_result.py
- contrib/chatops/actions/post_message.yaml
- contrib/chatops/actions/workflows/post_result.yaml
- st2api/st2api/controllers/v1/aliasexecution.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/db/actionalias.py
- st2tests/st2tests/fixtures/aliases/aliases/alias1.yaml
- st2tests/st2tests/fixtures/aliases/aliases/alias2.yaml
Different chat adapters have special capabilities which are sometimes very handy and nice. Slack has attachment colors and parsing/unfurling options for better formatting; HipChat has Connect features; and so on.
It’s hard for users to add support for those right now, because you have to modify the schema and the DB connector in st2, and only then submit a PR to `hubot-stackstorm` utilizing the new parameter. More importantly, if we had a lot of requests for this, our schema would be overblown with rarely used parameters.
A solution for this,—which has been discussed some weeks ago, but I only got around to it now,—is an `extras` object inside the alias with a “free” schema. It will allow people to easily add support for extra features with relative ease and without modifying `st2` (which …
> [RFR] Add the `extra` field to action aliases

- CHANGELOG.rst
- contrib/packs/actions/deploy.yaml
- contrib/packs/actions/workflows/deploy.yaml
- contrib/packs/aliases/pack_deploy.yaml
A clean up to the ChatOps aliases for pack deployment in the packs pack.
The current way turned out to be a little hard of the fingers when deploying a pack which had no subtree. As you need to type `my-pack` twice. This removes this requirement.
> Clean up the ChatOps aliases pack deployment

- circle.yml
To obfuscate this a bit we'll move it to an environment variable.
> Use Environment variable for webhook URL

- st2reactor/st2reactor/rules/enforcer.py
- st2reactor/st2reactor/rules/filter.py
- st2reactor/st2reactor/rules/tester.py
- st2reactor/tests/fixtures/rule.yaml
- st2reactor/tests/unit/test_tester.py
```
$ st2reactor/bin/st2-rule-tester --rule-ref default.rule4 --trigger-instance-id 56ec763832ed35226d5b9094
2016-03-18 15:41:08,350 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2016-03-18 15:41:08,383 INFO [-] Validating rule default.rule4 for st2.generic.actiontrigger.
2016-03-18 15:41:08,407 INFO [-] 1 rule(s) found to enforce for st2.generic.actiontrigger.
2016-03-18 15:41:08,413 INFO [-] Action parameters resolved to:
2016-03-18 15:41:08,414 INFO [-] 	i1: core.local
2016-03-18 15:41:08,415 INFO [-] 	i3: date
2016-03-18 15:41:08,415 INFO [-] 	i2: core.local
2016-03-18 15:41:08,416 INFO [-] === RULE MATCHES ===
```
```
$ st2reactor/bin/st2-rule-tester --rule-ref default.rule4 --trigger-instance-id 56ec763832ed35226d5b9094
2016-03-18 15:56:59,768 INFO [-] …
```
> Rule tester improvements

- st2common/st2common/log.py
Need to pass `excludes` to `_add_exclusion_filters()` 
Confirmed w/ @lakshmi-kannan that this was introduced when fixing a issue with logging and config loading here: 51204cb81bf42bd4e977711f0b8444eef4704fee
> Fix excludes handling.

- circle.yml
Reverts StackStorm/st2#2587
env variable didn't worked in that section, see : 
https://circleci.com/gh/StackStorm/st2/911
> Revert "Use Environment variable for webhook URL"

- st2client/st2client/commands/rule_enforcement.py
- st2common/st2common/models/api/rule_enforcement.py
- st2common/st2common/models/db/rule_enforcement.py
- st2reactor/st2reactor/rules/enforcer.py
- st2reactor/tests/unit/test_enforce.py
Record failures to enforce rules due to missing actions or parameter validation errors. A RuleEnforcement object will be created for failed enforcements that do not lead to an ActionExecution creation.
Includes CLI, API model and DB model changes apart from capturing the error message in RuleEnforcer in the `failure_reason` property.
```
$ st2 rule-enforcement get 56f1b4e832ed3570a924c5ff
+---------------------+--------------------------------------------+
| Property            | Value                                      |
+---------------------+--------------------------------------------+
| id                  | 56f1b4e832ed3570a924c5ff                   |
| rule.ref            | default.passive_trigger_rule_2             |
| trigger_instance_id | 56f1b4e832ed3570a924c5fa …
```
> Rule enforcement updates

- contrib/core/actions/send_mail/send_mail
Want to be able to easily tell if an email was sent. The current message "Successfully sent mail" is misleading when we actually skip sending mail since the body is empty and we've selected not to send an empty body.
Of course, I'm open to changing the wording.
> Improve output for core.sendmail when nothing sent

- CHANGELOG.rst
- st2reactor/st2reactor/rules/filter.py
- st2reactor/tests/unit/test_filter.py
This pull request fixes a bug with criteria comparison of falsy pattern values.
Previously, if a falsy value was provided for a pattern (e.g. number 0), comparison would fail since we incorrectly assumed criteria pattern is not provided and cast it to `None`.
This fixes bug described in #2600.
> Fix rule criteria comparison for falsy criteria pattern values

- circle.yml
`--depth 1` means no branch info therefore the checkout will fail.
> Fix branch checkout logic

- st2common/st2common/transport/announcement.py
This PR fixes running announcements through WebUI with empty `trace-tag`. WebUI passes an empty dict into `trace_context` instead of `None`, and it can’t match the assertion in code.
> Fix sending announcements through WebUI

- contrib/packs/aliases/pack_deploy.yaml
During continued use of the new deploy pack I noticed that the old formatting was not functional and all the parameters were ending up as a space separated in `{{branch}}`.
So a PR to remove the old formating and remove the unneeded `{{branch}}` from `pack deploy {{repo_name}} {{branch=master}}`.
If there is another way to achieve this, happy to update the PR....
> Remove formating for old packs.pack_deploy alias as it was non-functional

- st2common/st2common/util/gunicorn_workers.py
This includes a custom sync worker implementation which includes a work-around for shutdown related issues when using sync worker in combination with eventlet monkey patching,.
> Add a custom gunicorn sync worker implementation which works around some issues

- st2common/st2common/util/loader.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/tests/unit/test_sensor_wrapper.py
The error message which was reported previously was confusing and it wasn't immediately clear what is going on.
Now we throw a more specific and user-friendly error message so this should hopefully make it more obvious that either the sensor class file or the pack directory is missing.
> Throw a more user-friendly exception if sensor instance fails to start due to the missing sensor class file

- CHANGELOG.rst
- st2common/bin/st2-run-pack-tests
When this flag is provided, the script prints more information which should help with debugging / troubleshooting.
> Add "-v" (verbose) flag to st2-run-pack-tests script

- CHANGELOG.rst
- fixed-requirements.txt
- requirements.txt
This new features includes support for additional key exchanges algorithms. In addition to that it also includes various improvements and bug fixes (http://www.paramiko.org/changelog.html).
I have deployed the same change to st2build002 to make sure it doesn't introduce any regressions.
Resolves #2614.
> Upgrade paramiko to v1.16.0

- CHANGELOG.rst
- conf/st2.tests.conf
- conf/st2.tests1.conf
- st2common/st2common/content/bootstrap.py
- st2common/tests/integration/test_register_content_script.py
- tools/st2ctl
I've discussed HA deployment where action runner processes run on multiple servers with @codyaray yesterday and noticed I forgot to add this flag to st2ctl in #2576.
On a related note - (afaik) we still need to document opinionated git flow and how to use this flag when using HA deployment and having action runners deployed on multiple servers.
> Add missing "--register-setup-virtualenvs" flag to st2ctl

- tools/direct_queue_publisher.py
* Exisiting tool queue_producer published to an exchange. This is
for direct publishing to a queue.
* Written on top of pika instead of kombu as this was simpler to write
given code samples on rabbitmq tutorial site
> Tools that publishes messages directly to a Q

- st2common/st2common/models/db/actionalias.py
- st2common/st2common/models/utils/action_alias_utils.py
Discussed this with @jjm on Slack today.
This method comes handy when using `assertMatchesExactlyOneFormatString` and verifying that an alias contains no overlapping format strings which could cause issues.
When testing format strings one by one, you sadly still need to know the implementation details (is it a dict or a list) so that's not ideal and I think it would be good for us to a move to a "dict with key per format string" approach we've discussed the other day (this way inside the tests you could be like `format_string = action_alias_db.get_format_string(name='pack_with_branch')` or similar).
This would provide for a better abstraction and no need for user to know the implementation details.
/cc @emedvedev @manasdk (notably the last part aka moving to dict with key model)
> Add "get_format_strings" utility method to the ActionAliasDB class

- st2common/st2common/util/virtualenvs.py
Include stderr in the error message in virtualenvs.py when the pip command fails.
> Include stderr in the error message in virtualenvs.py when the pip command fails.

- CHANGELOG.rst
- st2common/st2common/util/casts.py
- st2common/st2common/util/jinja.py
- st2reactor/tests/unit/test_enforce.py
- st2tests/st2tests/fixtures/generic/rules/rule_none_no_use_none_filter.yaml
- st2tests/st2tests/fixtures/generic/rules/rule_use_none_filter.yaml
- st2tests/st2tests/fixtures/generic/traces/trace_for_test_enforce_2.yaml
- st2tests/st2tests/fixtures/generic/traces/trace_for_test_enforce_3.yaml
- st2tests/st2tests/fixturesloader.py
This is a work-around for issue described at #2621.
This is a short-term workaround until we switch from Jinja to a better system which supports types which means we won't need to do nasty and potentially error prone casting anymore.
/cc @jjm
> Workaround for correctly casting None values to None type in rule action parameters

- st2common/bin/st2ctl
This is my proposed fix to the issue outlined in #2550: st2ctl will give an “unknown service” error if one of the packages (chatops in that case) wasn’t installed.
The script makes a `status` call before start/stop, and if the exit code is 1, the service is not shown in the list. I checked on RHEL6 and Ubuntu that `1` is only given when the service doesn’t exist, otherwise it gives other codes.
Can be tested by removing the st2chatops package or stopping the service and then trying to stop it again.
Includes st2chatops, so trumps #2550.
> Make st2ctl ignore services that aren't installed

- st2common/bin/st2ctl
- tools/st2ctl
Last time I forgot to update the new st2ctl script :/
Is `tools/st2ctl` still used by something? If not, we should get rid of it ASAP.
> Add missing --register-setup-virtualenvs flag to the new st2ctl script

- st2api/st2api/app.py
- st2api/st2api/gunicorn_config.py
- st2auth/st2auth/app.py
- st2auth/st2auth/gunicorn_config.py
- st2stream/st2stream/app.py
- st2stream/st2stream/gunicorn_config.py
The problem was that we performed eventlet monkey patching inside master instead
of only inside workers which broke signal handling (master never received
signals so it never shut down).
> Fix a bug with gunicorn master process not shutting down

- st2common/st2common/transport/bootstrap_utils.py
This exchange was not being registered with rabbitmq, causing "no exchange s2.announcement in vhost" errors.
> Register ANNOUNCEMENT_XCHG in bootstrap_utils.py

- contrib/chatops/actions/workflows/post_result.yaml
There’s a bug where Jinja renderer returns a list instead of a string, resulting in a formatting glitch. 
Reported by Tracy Teague on the community channel.
> Formatting fix for the chatops message

- Makefile
- conf/st2.dev.conf
- conf/st2_kvstore_demo.crypto.key.json
- st2api/st2api/controllers/v1/keyvalue.py
- st2api/tests/unit/controllers/v1/test_kvps.py
- st2client/st2client/commands/keyvalue.py
- st2client/st2client/commands/resource.py
- st2client/st2client/models/core.py
- st2client/tests/unit/test_commands.py
- st2common/in-requirements.txt
- st2common/st2common/config.py
- st2common/st2common/exceptions/keyvalue.py
- st2common/st2common/models/api/keyvalue.py
- st2common/st2common/models/db/keyvalue.py
- st2common/st2common/util/crypto.py
- st2common/tests/unit/test_crypto_utils.py
- st2common/tests/unit/test_keyvalue_lookup.py
- st2tests/conf/st2_kvstore_tests.crypto.key.json
- st2tests/st2tests/config.py
- tools/st2-generate-symmetric-crypto-key.py
This PR allows encrypted items to be stored in key value store. The encryption is symmetric AES256 encryption and we use keyczar to do this. The encryption key is global for all keys. So StackStorm admin can decrypt all the keys. However, with RBAC, we'll make sure only intended user (and admin) can decrypt the user's keys. 
```
(virtualenv)vagrant@st2dev /mnt/src/storm/st2 (secrets_kv_store●●)$ st2 key set foo bar                                                                                                                                                       [ruby-1.9.3p484]
+------------------+-------+
| Property         | Value |
+------------------+-------+
| name             | foo   |
| value            | bar   |
| expire_timestamp |       |
+------------------+-------+ …
```
> Secrets in kv store phase #0

- contrib/packs/actions/workflows/deploy.yaml
The promised PR to fix the issue with out dated Mistral publishing in `packs.deploy` workflow.
As outlined in StackStorm/st2/issues/2660.
> Use new Mistral task function to publish results.

- fixed-requirements.txt
- requirements.txt
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/keyvalue.py
- st2api/tests/unit/controllers/v1/test_jsexpose_decorator.py
- st2common/st2common/models/api/base.py
- st2common/st2common/util/api.py
Looks like @lakshmi-kannan missed or ignored my comments in the secrets PR so I decided to make some improvements to `jsexpose` myself :P
1. Update jsexpose so it knows how to handle `bool` type. Perhaps better and more explicit name for this argument would be `cast_funcs`, but that's something we can rename in the future aka separate PR.
2. Update jsexpose so it always consumes keyword arguments first. This way it works correctly if not all of the arguments are provided and we don't need to abuse "**kwargs" in the method signature.
3. Update jsexpose to handle more edge cases and invalid HTTP requests. The code which performs those checks is hacky, but it's better than not having anything and silently swallowing and ignoring invalid requests. As mentioned below, proper solution is moving …
> Update jsexpose so it knows how to handle "bool" type, various improvements and fixes

- st2common/st2common/hooks.py
Now we have two ways to enable per-service debug mode (`--debug` flag or config option) so we need to use this method to correctly determine if debugging is enabled.
> Use is_debugging_enabled method to determine if debugging is enabled

- st2common/st2common/persistence/base.py
Even though we logged the whole message (including traceback) under DEBUG log level it still confused a lot of users and made it look like a fatal error.
Before:
```bash
2016-05-02 22:33:52,529 DEBUG [-] Conflict while trying to save in DB.
File "/data/stanley/st2common/st2common/persistence/base.py", line 120, in insert
model_object = cls._get_impl().insert(model_object)
File "/data/stanley/st2common/st2common/models/db/__init__.py", line 207, in insert
instance = self.model.objects.insert(instance)
File "/data/stanley/virtualenv/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 307, in insert
raise NotUniqueError(message % unicode(err))
NotUniqueError: Could not save document (E11000 duplicate key error index: st2.role_d_b.$name_1 …
```
> Don't include traceback when logging "NotUnique" error as debug

- CHANGELOG.rst
- st2actions/st2actions/runners/ssh/parallel_ssh.py
- st2actions/st2actions/runners/ssh/paramiko_ssh.py
- st2actions/st2actions/runners/ssh/paramiko_ssh_runner.py
- st2actions/tests/unit/test_paramiko_ssh.py
- st2actions/tests/unit/test_paramiko_ssh_runner.py
- st2common/st2common/bootstrap/runnersregistrar.py
- st2common/st2common/constants/runners.py
Note: This PR is based on #2666.
This pull request updates remote runner so user can now also specify a path to the private key file for the `private_key` remote runner argument.
This resolves security concerns from #2662.
We are currently working on secrets in datastore story which goal is to solve some of the issues like that, but I still see value in allowing users to specify a path to the key file. A lot of organizations already have a code / configuration management in place or managing secret files on disk so it makes sense to allow users to re-use that functionality instead of forcing them to use datastore secrets which is StackStorm specific functionality.
In addition to that, I also fixed support for password protected keys (see …
> Support for path to the private key file for the "private_key" argument

- CHANGELOG.rst
- st2common/st2common/content/bootstrap.py
- st2common/tests/integration/test_register_content_script.py
Reported / caught by @codyaray on Slack.
> Allow "--register-all" and "--register-setup-virtualenvs" register content script flags to be used together

- CHANGELOG.rst
- st2tests/st2tests/action_aliases.py
- st2tests/st2tests/actions.py
- st2tests/st2tests/pack_resource.py
- st2tests/st2tests/sensors.py
This PR adds "get_fixture_content" method to the base pack resource test classes. This method enforces fixture file location conventions and allows user to load raw fixture content from a fixture file on disk.
We discussed this on a st2contrib PR recently - the functionality is very simple, but we still think there is value in it since it enforces fixture file location convention (`<pack path>/tests/fixtures/`).
> Add "get_fixture_content" method to the base pack resource test classes

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/unload.py
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/pack_config_schema.py
- st2api/st2api/controllers/v1/packs.py
- st2api/st2api/controllers/v1/root.py
- st2api/tests/unit/controllers/v1/test_pack_config_schema.py
- st2api/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/constants/pack.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/db/__init__.py
- st2common/st2common/models/db/pack.py
- st2common/st2common/persistence/base.py
- st2common/st2common/persistence/pack.py
- st2common/st2common/rbac/decorators.py
- st2common/st2common/services/packs.py
- st2common/tests/unit/test_resource_registrar.py
- st2tests/st2tests/fixtures/dummy_pack_1/config.schema.yaml
- st2tests/st2tests/fixtures/pack_invalid_requirements/pack.yaml
This is a first iteration of the improvement pack configuration story.
It includes support for optional pack config schema. Pack configuration which will be supplied by the user (that's the second iteration of the improved pack configuration story and is TBD) will be validated against the schema provided by the pack author when loading pack configuration.
Pack schema follows action parameters format and the schema file looks like that:
```yaml
---
attributes:
api_key:
type: "string"
secret: true
required: true
api_secret:
type: "string"
secret: true
required: true
region:
type: "string"
required: false
```
(I'm open to feedback, we could rename `attributes` to something else, we could also get rid of it and have config items as top-level object, but I'm not too big of a fan of that …
> Pack config schema support

- st2common/st2common/transport/bootstrap_utils.py
This used to work because whenever a Q is created on an exchange it ends up being registered if the exchange is not already present. However, always better to explicitly register these exchanges up-front.
> Register all RMQ exchanges

- st2common/st2common/bootstrap/aliasesregistrar.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/bootstrap/policiesregistrar.py
- st2common/st2common/bootstrap/rulesregistrar.py
- st2common/st2common/bootstrap/ruletypesregistrar.py
- st2common/st2common/hooks.py
- st2common/st2common/models/db/__init__.py
- st2common/st2common/persistence/trigger.py
- st2common/st2common/services/keyvalues.py
- st2common/st2common/services/packs.py
- st2common/st2common/services/triggers.py
- st2common/tests/unit/test_db.py
- st2common/tests/unit/test_db_action_state.py
- st2common/tests/unit/test_db_liveaction.py
- st2common/tests/unit/test_db_marker.py
- st2common/tests/unit/test_db_rule_enforcement.py
- st2common/tests/unit/test_executions.py
- st2common/tests/unit/test_persistence.py
- st2common/tests/unit/test_reference.py
- st2tests/st2tests/base.py
I noticed this while working on some related changes.
Right now we throw `ValueError` instead of `StackStormDBObjectNotFoundError` inside base model `.get` method when object is not found. This means that in many places we need to capture this exception and then re-throw `StackStormDBObjectNotFoundError`.
This can be solved by throwing `StackStormDBObjectNotFoundError` directly. In comparison to `ValueError`, this exception is also more specific.
If the `ValueError` was selected intentionally (e.g. some other code path also throws ValueError and we want to capture all those exceptions), please let me know.
> Update the base model code to throw StackStormDBObjectNotFoundError exception if an object is not found, update affected code

- st2api/st2api/controllers/v1/actions.py
Timing graph for GET https://192.168.10.16/api/v1/actions API request that returns around 1600 actions looks like that:
Applying throttling to it (Good 3G preset, 40ms latency, 1.5Mbps in, 750Kbps out) to get the picture better representing real world use:
In general, TTFB can be round down to the time server takes to prepare the answer (contact db, query data, apply transforms) and `content download` is obviously the time it takes for browser to pull this data from server. Browsers can't parse JSON from a stream so the time to first pixel rendered is always bigger than that.
By excluding fields like `parameters` and `notify`, you can reduce it to ![](https://s3.amazonaws.com/f.cl.ly/items/0B3p0i473n3l161b0L21/Screen%20Shot%202016-05-17%20at%202.36.23%20PM.png)
Personally, I'd rather …
> Fix delay caused by loading a huge set of actions

- CHANGELOG.rst
- requirements.txt
- st2client/in-requirements.txt
- st2client/requirements.txt
Originally reported in #2689 (thanks!).
We never encountered this issue (and tests didn't catch it) since when using package installation method, `st2client` uses the same virtual environment as other components and `appscheduler` (used by `st2reactor`) depends on `pytz` so the dependency was also satisfied for `st2client`.
The issue would only manifest itself if user manually installed `st2client` outside st2 virtual environment.
> Add missing pytz dependency to st2client

- st2common/bin/st2ctl
This PR reverts #2625, since RHEL6 isn’t compatible. We still need a solution of the original problem (services that aren’t installed showing up as errors on st2ctl commands), but currently I don’t have a better solution than checking exit codes, and this is a blocker, so we should revert now and worry about error messages later.
I’ll wait for @DoriftoShoes before merging, hopefully he’ll have some ideas. :)
> Revert #2625

- Makefile
- test-requirements.txt
By default, I am turning on colors so I can spot an error easily. 
Optionally, by specifying NOSE_TIME=1 you get detailed drill down of how much time each test took!
Yellow indicates a bad test and red indicates an abomination. 
https://www.evernote.com/l/ANGmYg7IwnJGaYrloBvo_ItyD3GmrbzJ5j4
> JUST_FOR_FUN: Add colors and timing info to nosetests

- requirements.txt
- st2client/in-requirements.txt
- st2client/st2client/shell.py
To activate autocomplete, perform `eval "$(register-python-argcomplete st2client/st2client/shell.py)"` or `eval "$(register-python-argcomplete st2)"` in your shell (depending on how you're planning to call it).
It will become a part packaging process when we figure out we're happy with autocomplete in general.
Please note that I've added +x and hashbang to shell.py. You may have your own opinion on the matter.
> Add basic autocomplete support to st2 CLI client

- CHANGELOG.rst
- st2api/st2api/controllers/v1/auth.py
- st2api/tests/unit/controllers/v1/test_auth_api_keys.py
- st2client/st2client/commands/auth.py
- st2client/st2client/commands/resource.py
Implements feature request https://github.com/StackStorm/st2/issues/2692
`st2 apikey list -dy > apikeys.yaml`
`st2 apikey load apikeys.yaml`
Note : Going with `load` instead of re-using `create` is to avoid any confusion. Creation will always create a new ApiKey while load will assume the key_hash was properly generated by a StackStorm instance and that the user already has a matching ApiKey. To preserve the distinction between a new key is desired and that an existing key is being loaded the 2 separate verbs are preferred.
Appropriate fixes made in the API layer.
> [RFR] Ability to load apikeys from a file.

- st2client/st2client/client.py
- st2client/st2client/commands/resource.py
- st2client/st2client/config_parser.py
- st2client/st2client/models/core.py
- st2client/st2client/shell.py
- st2client/st2client/utils/httpclient.py
- st2client/tests/unit/test_auth.py
- st2client/tests/unit/test_config_parser.py
As requested in https://github.com/StackStorm/st2-packages/issues/283, the PR adds support for API key to st2client and allows user to store said key in `~/.st2/config`.
> Add API key support to st2client

- CHANGELOG.rst
- st2client/st2client/commands/rule.py
```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ st2 --debug rule list --pack=fixtures                                   master ✭ ✱ ◼
curl -X GET -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.10.0' 'http://127.0.0.1:9101/v1/rules/?limit=50'
+---------------------------------+-----------+---------------------------------+---------+
| ref                             | pack      | description                     | enabled |
+---------------------------------+-----------+---------------------------------+---------+
| examples.notify_slack           | examples  | Sample rule firing on action    | True    |
|                                 |           | completion.                     |         |
| …
```
> Fix a regression in filtering rules by pack

- st2debug/st2debug/cmd/submit_debug_info.py
- st2debug/st2debug/utils/fs.py
- st2debug/tests/integration/test_submit_debug_info.py
Currently `submit_debug_info.py` doesn't clean up the the temp files it creates. This PR adds a finally statement to remove the temp files created by the `create_archive` function.
Added a remove_dir function to `st2debug/utils/fs.py` for consistency with the `remove_file` function.
> Remove temp files created by submit_debug_info

- fixed-requirements.txt
- requirements.txt
New version of amqp was released (https://pypi.python.org/pypi/amqp/2.0.0) and it appears to be breaking some end to end tests.
> Pin kombu and amqp dependency

- CHANGELOG.rst
- st2actions/tests/unit/test_actionchain.py
- st2common/st2common/models/utils/action_param_utils.py
- st2common/st2common/util/casts.py
- st2common/st2common/util/compat.py
- st2common/tests/unit/test_casts.py
This pull request introduces some improvements in the string parameter casting:
* Treat `None` as-is and return early
* On non-string and None type, throw a more user-friendly exception (previously, `to_unicode` would throw a very cryptic exception)
* Include additional info in the existing log message
Reported by @jjm. Looking at the code and history, it looks like this bug was there for a long time, but it only manifested under specific conditions so we never noticed it before.
@jjm was also "lucky" to encounter this issue, since it would only manifest itself under a specific scenario - the way we do ChatOps string matching right now is a bit nasty (we also match a whitespace and then strip additional whitespace so for a matched parameter value of `" "` actual value of `""` would be …
> String casting improvements

- st2api/st2api/controllers/v1/keyvalue.py
- st2api/tests/unit/controllers/v1/test_kvps_rbac.py
- st2client/st2client/commands/keyvalue.py
- st2common/st2common/models/api/keyvalue.py
- st2common/st2common/util/api.py
This pull request includes access control and other new features, related improvements and fixes for  the datastore API endpoints.
1. Allow administrators to list all the datastore items (including user scoped ones) by specifying `all` for the `scope` query parameter.
2. When using decrypt option in the list API endpoint, require the user to be an administrator or the user is listing user-scoped items for themselves.
3. When using decrypt option in the get one API endpoint, require the user to be an administrator or the user is retrieving a user-scoped item for themselves.
4. Allow administrator to set a user-scoped item for an arbitrary user.
5. Allow administrator to delete a user-scoped item for an arbitrary user.
6. Some code cleanup (we don't need to catch …
> Access control and other new features and improvements for the datastore API endpoints

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/keyvalue.py
- st2client/st2client/commands/action.py
- st2client/tests/unit/test_action.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/keyvalue.py
- st2common/st2common/rbac/utils.py
This ties to the pack configuration v2 story.
This pull request allows administrator to specify a user who's context will be used when running and re-running an action.
Right now inheriting a user context basically only means using datastore values for that user when using a dynamic config value, but now we have a framework in place so we can expand it in the future (e.g. it could also means inheriting that user's permissions, etc.).
I also refactored some of the RBAC code since the same logic is now used in two places so it makes sense to refactor it in some common place.
In addition to that, I also cleaned / fixed some code (One of the methods expected an API object, but in one place we passed in a DB object, it mostly worked out of pure luck because objects look mostly the same. That's …
> Allow admin to specify an user who's context will be used when running / re-running an action

- CHANGELOG.rst
- st2common/st2common/services/triggers.py
This is a terrible work-around for bug reported in #2730.
As described in that bug report, sometimes rule creation fails because finding a corresponding TriggerDB object by trigger parameters fails. I managed to track it down to an issue when unicode-literals are used for Python values (it's easy to reproduce it, check the bug report and insert debugger when trigger look up fails - if you try to look it up when parameters contain unicode literals it fails, but if you encode it to string literals it passes).
The most bizarre thing is that this doesn't happen always - sometimes dictionary can contain all unicod e literals and it works just fine - I have no idea why, but it looks like a weird bug with unicode literals and internal query cache handling in pymongo / mongoengine.
Yes, I know …
> Implement a work-around for CronTimer rule creation

- CHANGELOG.rst
- st2common/st2common/models/api/execution.py
- st2common/st2common/models/db/execution.py
- st2common/st2common/services/executions.py
- st2common/tests/unit/test_executions_util.py
While discussing #2706 we figured there is a few new timestamps we would like to add to execution record to improve user's understanding of the flow and make it easier to debug indeterminate set of problems (primarily performance related I would guess).
Problem is, there is quite a few execution states already and there's going to be even more if we are to focus on the problem seriously. Storing timestamps related to this state changes as a properties of the execution itself will quickly bloat the execution object beyond reason.
An obvious solution to the problem is to create another data structure that would hold this expanding set of data in a linear fashion.
The idea is, for every execution state mutation, we creating a log entry with the state execution transitions to and the …
> Execution log

- st2common/bin/st2ctl
- tools/st2ctl
The `--register-fail-on-failure` option that I [learned about yesterday|https://stackstorm-community.slack.com/archives/community/p1465382685000395] is pretty useful. We should expose this option through `st2ctl reload`.
Our content management story currently deploys packs with ansible and triggers `st2ctl reload --register-all` (and in some playbooks `--register-setup-virtualenvs` as well). So right now it fails silently if the content can't be loaded. Would be nice if we could just pass this flag through directly so it returns the error to ansible to display. 
Or you can say, no, just use the `st2-register-content` script directly for more flags. That's fine too. :)
> Support --register-fail-on-failure in st2ctl

- contrib/packs/linux/actions/sleep_until.yaml
Added a new action that just sleeps until a specified time using the Linux `sleep` and `date` commands.
- existing pack, new action
> Adding linux.sleep_until action

- CHANGELOG.rst
- st2client/st2client/formatters/table.py
- st2client/tests/unit/test_shell.py
This pull request fixes bug described in #2740.
> Fix "-a all" flag for "st2 execution list" command

- CHANGELOG.rst
- st2actions/st2actions/runners/ssh/parallel_ssh.py
- st2actions/tests/unit/test_parallel_ssh.py
Bastion support is currently broken because the bastion_host parameter isn't being used when creating a ParamikoSSHClient.
Fixes https://github.com/StackStorm/st2/issues/2543.
> fix bastion ssh support

- CHANGELOG.rst
- conf/st2.dev.conf
- st2api/st2api/controllers/base.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/auth.py
- st2api/tests/unit/controllers/v1/test_auth_api_keys.py
- st2client/st2client/commands/auth.py
* Use the mask_secrets property from API config
* Provide API support for admin to override masking
Note : `--show-secrets` is not supported for `st2 apikey get`. This feature is meant to enable token export.
With and without `--show-secrets`
```
(virtualenv)vagrant@st2dev:~/st2$ st2 apikey list -dy
-   created_at: '2016-06-17T00:08:05.555610Z'
enabled: true
id: 57633f65d9d7ed1fc39c019e
key_hash: '********'
metadata: {}
uid: '********'
user: stanley
(virtualenv)vagrant@st2dev:~/st2$ st2 apikey list -dy --show-secrets
-   created_at: '2016-06-17T00:08:05.555610Z'
enabled: true
id: 57633f65d9d7ed1fc39c019e
key_hash: f157ebc6ae10f87af9205b31e9492d156fbd036b12686d97c69536b04d8c05327d80fc467ffc7de6f0f518b86e860a8d06aff289ed81a66bdcb160b8f23a1add
metadata: {}
uid: …
```
> Use mask_secrets properly

- CHANGELOG.rst
- st2actions/st2actions/runners/ssh/parallel_ssh.py
- st2actions/st2actions/runners/ssh/paramiko_ssh.py
- st2actions/tests/unit/test_parallel_ssh.py
- st2actions/tests/unit/test_paramiko_ssh.py
```
vagrant@st2test:~$ st2 run core.remote hosts=localhost cmd=date username=vagrant private_key=/home/vagrant/.ssh/test_rsa_pp
.
id: 5763024955fc8c18adf74f00
status: failed
parameters:
cmd: date
hosts: localhost
private_key: '********'
username: vagrant
result:
error: "Unable to connect to any one of the hosts: [u'localhost'].
connect_errors={
"localhost": {
"failed": true,
"traceback": "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/parallel_ssh.py\", line 241, in _connect\n    client.connect()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/ssh/paramiko_ssh.py\", line 144, in connect\n    self.client = self._connect(host=self.hostname, socket=self.bastion_socket)\n  File …
```
> Clear error message when passphrase not supplied with encrypted private key

- st2common/st2common/rbac/migrations.py
This code is now obsolete in v1.5 and not needed anymore.
> Remove RBAC migration code which is not required anymore

- st2api/st2api/controllers/resource.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
Change of `falsy` check was causing some UI queries to break.
> Fix execution list

- st2common/st2common/util/param.py
- st2common/tests/unit/test_param_utils.py
When attempting to use an array that contains variables a `maximum recursion depth exceeded` error would be raised from Jinja. This commit fixes that bug and extends the unit test to cover lists with variables.
> Fix: Array With Variable

- CHANGELOG.rst
- st2common/st2common/util/param.py
- st2common/tests/unit/test_param_utils.py
- st2tests/st2tests/fixtures/generic/actions/action_user_default.yaml
For background, see https://stackstorm.atlassian.net/browse/STORM-2195
```
root@st2test:/home/vagrant# st2 run core.local cmd="user.date_cmd"
MESSAGE: Dependecy unsatisfied in user for url: http://127.0.0.1:9101/v1/executions
root@st2test:/home/vagrant# s
```
```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ st2 run core.local cmd="{{user.date_cmd}}"                              master ✭ ✱ ◼
.
id: 5769c625d9d7ed15e61f17eb
parameters:
cmd: '{{user.date_cmd}}'
result:
failed: false
return_code: 0
stderr: ''
stdout: Tue Jun 21 22:56:37 UTC 2016
succeeded: true
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯
```
> RFR: Render user params (jinja) in API

- contrib/examples/actions/print_config.py
- contrib/examples/actions/print_config.yaml
- contrib/examples/config.schema.yaml
As suggested by @lakshmi-kannan in the blog post draft.
This works fine for now, but in case we will add more actions in the future which utilize a different config things will start to clash so we will need to figure out a better approach (e.g. move it to a separate pack or similar).
> Move sample improved pack config to examples pack

- CHANGELOG.rst
- contrib/examples/triggers/sample-trigger.yaml
- st2common/st2common/bootstrap/triggersregistrar.py
- st2common/st2common/models/utils/sensor_type_utils.py
- st2common/st2common/services/triggers.py
- st2common/tests/unit/test_sensor_type_utils.py
- st2common/tests/unit/test_triggers_registrar.py
This was originally reported by @codyaray in https://github.com/StackStorm/st2contrib/pull/475#issuecomment-229139710 (thanks!).
There was a bug so corresponding `TriggerDB` object was not created. I updated the code to use the same code path and function which other code which creates triggers uses. I also added a regression test case.
The function we use right now is not 100% ideal since we only operate with a single trigger type in this scenario, but we have tests now so in the future we can do a small refactor to improve it.
> Fix trigger registration bug

- CHANGELOG.rst
- st2common/st2common/models/db/__init__.py
- st2common/st2common/persistence/base.py
- st2common/st2common/services/triggers.py
- st2reactor/st2reactor/container/utils.py
- st2reactor/tests/unit/test_container_utils.py
With this change we now try to look up TriggerDB objects by id / uid if either of those fields is available.
This way we can avoid lookup by type and parameters dictionary which fails in some scenarios. There are at least two bugs related "by parameters dictionary" lookup. One is related to unicode caching bug in mongoengine (I've added a nasty hack / work-around for it a while back) and the other one is yet to be tracked down.
My goal also is to confirm that id / uid field is always available so we can get rid of parameters dictionary lookup all together (that's something I wanted to do more than a year ago and I believe now it's finally possible to do that without much effort).
This hopefully resolves issue described in #2765.
> Look up TriggerDB objects by id / uid if available

- CHANGELOG.rst
- st2common/st2common/util/config_loader.py
- st2common/tests/unit/test_config_loader.py
- st2tests/st2tests/fixtures/dummy_pack_1/config.schema.yaml
- st2tests/st2tests/fixtures/dummy_pack_4/config.schema.yaml
- st2tests/st2tests/fixtures/dummy_pack_5/config.schema.yaml
This pull request adds support for default values from config schema.
This means that if a config schema declares particular config item as "required" and that item also contains a default value and that item is not provided in the config, default value from the config schema is used. This is exactly the same behavior as we use with action parameters.
This behavior is not required to be able to utilize dynamic config values using the new config notation, but it's nice and consistent with action parameters. In addition to that, as mentioned in the blog post and other places, we plan to utilize config schema for more things (type validation, etc.) in the future.
> Support for default config values from the config schema

- st2api/st2api/controllers/v1/actionexecutions.py
That's another way of solving https://github.com/StackStorm/st2/pull/2787 that plays much better with specifics of rerun implementation in st2web.
By avoiding the merge on an api side, user is getting full control over execution parameters without introduction of any additional special types.
> Add flag to prevent parameter merging during rerun

- st2common/st2common/models/utils/action_param_utils.py
- st2common/tests/unit/test_action_param_utils.py
Back in https://github.com/StackStorm/st2/pull/690/files#diff-950f03378fda3eb80bbc01142a430fd7R31 @m4dcoder presumably decided that if certain parameter is set as required on a runner level, it should end up being required even after we add action parameters to the mix. In reality, user can set default value for this parameter on an action level and thus lift the requirement.
Strictly speaking, parameter should never have truthy values of `require` and `default` simultaneously, but that change is more on par with linting actions during registration and therefore outside the scope of this PR.
Resolves https://github.com/StackStorm/st2web/issues/307
STORM-2201
> Correctly resolve parameter's required property

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_base.py
- st2common/st2common/util/api.py
- Correctly cast `no_merge` query param to boolean
- Update regular expression so we correctly handle some more pecan edge cases and return 404 instead of 500 on invalid paths
> Various fixes

- Makefile
- scripts/travis/build.sh
- st2common/st2common/util/jinja.py
- st2common/st2common/util/templating.py
- st2tests/integration/mistral/test_wiring.py
- test-requirements.txt
This pull request runs bandit security linter (https://github.com/openstack/bandit) on our code base as part of our build.
The idea behind bandit is a good one, but right now it doesn't report any real issues in our code bases (just false positives). I also have some doubts how useful it is in more "advanced" non-web based projects where most choices are deliberate, but we will see down the road.
> Run "bandit" linter on the code base

- README.md
The [current link](https://docs.stackstorm.com/install/sources.html) leads to a 404.
> Fix link for installation from sources

- CHANGELOG.rst
- Makefile
- fixed-requirements.txt
- pylint_plugins/db_models.py
- requirements.txt
- st2common/st2common/models/api/action.py
- st2common/st2common/models/db/stormbase.py
- st2common/st2common/services/rbac.py
- st2common/tests/unit/test_db.py
- st2common/tests/unit/test_db_model_uids.py
- st2common/tests/unit/test_keyvalue_lookup.py
This pull request upgrades to latest version of `pymongo` and `mongoengine`.
We wanted to do this many times before, but there are some backward incompatible changes in the newer versions and we never spent enough time digging in and addressing those issues so it never happened.
With the latest version of those libraries, StackStorm now also supports MongoDB 3.x. I think this is very important since MongoDB 3.x addresses and improves a lot of things (especially with a new storage engine). In the near future we should recommend MongoDB 3.x for new users, install MongoDB 3.x with the installer and come up with an upgrade scenario and document for an existing users which want to upgrade from 2.x to 3.x (there are some backward incompatible changes which require some work on the user side). …
> Upgrade to the latest version of pymongo and mongoengine

- st2common/bin/st2-perform-model-migrations
First, I'll be writing a migration wrapper script that calls out specific migration scripts for each version. Each version specific migration script will call the python migration scripts. 
This script will be used only for upgrade_testing workflows. 
1. Patch versions won't have data model migrations. Only major and minor versions would.
2. We won't support downgrade migrations i.e. if you are going from 1.5 to 1.4, you can deal with shit yourself.
~~I don't yet know how to address upgrading to skipped versions. Like say 1.4 to 1.6. This would mean that we should run migration scripts for 1.4 -> 1.5 and 1.5 -> 1.6. Maybe we can skip this for initial pass and abort the script with a positive exit code.~~
^ I solved this by some bash magic. Now I call migrate_to_${major}_${minor} in a loop …
> Model migrations -- bash script

- st2actions/conf/syslog.conf
args() for the auditHandler referred to a non-existent directory. If users change `st2.conf` to use syslog.actionrunner.conf, it breaks, and st2actionrunner won't work.
> Changed default actionrunner syslog.conf to use ConfigurableSyslogHandler

- CHANGELOG.rst
- conf/st2.conf.sample
- conf/st2.dev.conf
- conf/st2.package.conf
- conf/st2.prod.conf
- conf/st2.tests.conf
- conf/st2.tests1.conf
- contrib/chatops/actions/templates/default.j2
- st2common/st2common/config.py
- st2common/st2common/models/db/execution.py
- st2common/st2common/services/executions.py
- st2common/tests/unit/test_executions_util.py
We want to be able to display the execution history web url in chatops messages on ACK as well as after final results. 
https://github.com/StackStorm/hubot-stackstorm/issues/120
1. When an action is kicked off we do give out the execution id link. This is because https://github.com/StackStorm/hubot-stackstorm/blob/master/scripts/stackstorm.js#L245 but it unfortunately depends on an env variable https://github.com/StackStorm/st2chatops/blob/master/st2chatops.env#L36. So mostly we get “localhost” based URL. See  https://stackstorm.slack.com/archives/chatopsci/p1468963585000061 (private link). 
2. When an action completes, we don’t share the execution URL. This is obv looking at this https://github.com/StackStorm/st2/blob/master/contrib/chatops/actions/templates/default.j2#L15. 
So it looks …
> Execution model to contain web_url field for chatops sake

- CHANGELOG.rst
- st2client/st2client/models/core.py
The problem was that `HTTPclient.query` method does some nasty stuff and wasn't updated when we added support for API keys.
I'm not a fan of the current and existing approach, but sadly there is not much I can do until we dedicate to invest enough time to totally refactor and improve the client library.
Resolves #2815.
> Fix CLI commands so they all support "--api-key" option

- st2api/st2api/controllers/v1/actionexecutions.py
This change https://github.com/StackStorm/st2/pull/2831/files#diff-212b279de225b603d0bc7fe4e00ae449R224 broken the controller because of kwargs abuse in both CLI https://github.com/StackStorm/st2/blob/master/st2client/st2client/utils/httpclient.py#L75 and the controller simply passing the kwargs :/
I fixed controller arguments to explicitly call out what's needed. 
Spun up an instance and hand patched to test the changes
```
vagrant@st2test:~$ st2 run packs.install packs=circle_ci
.................
id: 5797e5e955fc8c2686399ac9
action.ref: packs.install
parameters:
packs:
- circle_ci
start_timestamp: 2016-07-26T22:36:25.183147Z
end_timestamp: 2016-07-26T22:37:00.040937Z
+--------------------------+-------------------------+--------------------------+----------------------- …
```
> Explicit kwargs pass to _get_children method

- CHANGELOG.rst
- st2api/st2api/config.py
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/triggers.py
- st2api/tests/unit/controllers/v1/test_actions.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
- st2client/st2client/commands/action.py
- st2client/st2client/commands/rule.py
- st2client/st2client/commands/rule_enforcement.py
- st2client/st2client/commands/trace.py
- st2client/st2client/commands/triggerinstance.py
- st2tests/st2tests/config.py
As discussed in #2803 and #2806, this PR makes maximum page size aka maximum value of `?limit` query parameter configurable by the StackStorm administrator.
For backward compatibility and safety reasons (to prevent DDoS, etc.) we still default this value to `100`, but if user as a need to use a lower / higher value, they can now tune this setting.
> Allow max_page size (value of ?limit param) to be configured by the administrator

- CHANGELOG.rst
- st2common/bin/st2ctl
- st2common/st2common/content/bootstrap.py
- st2common/tests/integration/test_register_content_script.py
This is something which has been discussed before.
Not failing on failure is not a good default behavior since it makes it easy to miss (important) errors. On top of that, it's also not a good practice to have "broken" resource metadata or similar laying on the system.
This will make it easier to spot errors and potential issues and hopefully also reduce some support overhead and "wtf" moments.
For backward compatibility reasons, ``--register-fail-on-failure`` flag was left there and new ``--register-no-fail-on-failure`` flag was added for users who desire the old behavior.
Resolves #2828
> Update st2-register-content to fail on failue (exit with non-zero) by default

- st2actions/st2actions/runners/python_action_wrapper.py
- st2actions/st2actions/runners/pythonrunner.py
- st2actions/tests/unit/test_pythonrunner.py
- st2common/st2common/constants/error_codes.py
- st2common/st2common/exceptions/invalidstatus.py
- st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py
**Changed files:**
- st2actions/st2actions/runners/python_action_wrapper.py
- st2actions/st2actions/runners/pythonrunner.py
- st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py
- st2actions/tests/unit/test_pythonrunner.py
**Test Cases:**
_Modified_:
- test_simple_action_without_status
- test_stdout_interception_and_parsing
_New_:
- test_simple_action_with_status_succeeded
- test_simple_action_with_status_failed
- test_simple_action_with_status_failed_result_none
**Caveats:**
~~- Assumption: User must provide status as "succeeded" or "failed" (case insensitive). It may fail otherwise. No check for this.~~
> [RFR]: Enhancement: python action should be allowed to return status #2742

- st2api/st2api/controllers/v1/actions.py
- st2api/st2api/controllers/v1/auth.py
- st2api/st2api/controllers/v1/keyvalue.py
- st2api/st2api/controllers/v1/policies.py
- st2api/st2api/controllers/v1/rules.py
- st2api/st2api/controllers/v1/runnertypes.py
- st2api/st2api/controllers/v1/triggers.py
- st2common/st2common/models/api/base.py
- st2common/tests/unit/test_api_model_base.py
Allows creating controllers with optional body and reuse the same controller for url's of any depth.
Controller with this signature
```
@jsexpose(body_cls=..., arg_types=[str, int, str])
def post(self, body, type, id, property):
```
will successfully handle all this rest calls
```
POST /document/112/header/ -> post(body=({...} or None), type='document', id=112, property='header')
POST /document/112/ -> post(body=({...} or None), type='document', id=112, property=None)
POST /document/ -> post(body=({...} or None), type='document', id=None, property=None)
```
> Making jsexpose more flexible

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
- st2client/st2client/commands/action.py
Add execution list sort ordering as requested in [issue 2837](https://github.com/StackStorm/st2/issues/2837) 
Added command line argument -s | --sort asc|desc (ascending is the current default sort order)
Added check for 'desc' in api (to mesh with overrides for -tg or -tl)
> Enhancement: add option to sort in descending order - ascending is default

- st2common/st2common/models/db/__init__.py
- st2tests/st2tests/base.py
MongoDB 3.2 doesn't like this operation when running it after connection has been established, but it works fine when running this code as part of the service setup phase since we run it inside the `db_setup` method.
This change doesn't negatively affect tests in any way.
Will cherry pick it into v1.6 branch.
> Don't remove extra indexes when running tests

- .travis.yml
- scripts/travis/build.sh
- scripts/travis/create-and-mount-ramdisk.sh
- scripts/travis/install-and-run-mongodb.sh
This pull request updates Travis file so we now run unit and integration tests with MongoDB 2.4, 2.6 and 3.2.
In the future we should drop official support for versions < 3.2 since they are quite old now.
In addition to the MongoDB change, I also updated the script to create a ramdisk and use this for MongoDB data dir. In theory, this should speed things up a bit, but probably not by much since we are running on a shared environment.
Note: If it turns out that the whole build now takes too long because we run 4 additional jobs, we can update the build configuration and only run tests with MongoDB 3.2.
> Use and run unit and integration tests with MongoDB 2.4, 2.6 and 3.2

- scripts/fixate-requirements.py
Using PIP 8.1.2 with _fixate-requirements.py_ currently results in the following due to internal changes in PIP:
```
File "scripts/fixate-requirements.py", line 174, in <module>
skip=skip)
File "scripts/fixate-requirements.py", line 117, in write_requirements
requirements = merge_source_requirements(sources)
File "scripts/fixate-requirements.py", line 96, in merge_source_requirements
if req.req.project_name in projects:
AttributeError: 'Requirement' object has no attribute 'project_name'
```
See: https://github.com/pypa/pip/issues/3687
This change should be backward compatible with earlier versions of pip. Tested with 7.1.2 and 8.1.2.
> Make fixate-requirements.py PIP 8.1.2 Compatible

- CHANGELOG.rst
- st2client/st2client/commands/action.py
This change allows user to cancel multiple executions using a single invocation of ``st2 execution cancel`` command.
It uses the same notation as many other well known CLI commands (e.g. `git cherry-pick sha1 sha2 sha2`, etc.).
For example:
```bash
st2 execution cancel 57a9707b0640fd0a5f8b15c4 57a96e070640fd0a5f8b158e 57a96e270640fd0a5f8b1594
```
This would save me some typing yesterday when dealing with the workflows. The change itself is fully backward compatible and works the same as before when only a single execution id is provided.
> Allow user to cancel multiple executions using st2 execution cancel command

- CHANGELOG.rst
- contrib/packs/actions/load.yaml
If there are a lot of packs and resources on disk `packs.load` with a default timeout will fail because resource registration takes longer.
This was constantly happening on the build server.
In the future we should also have a look if we can some how optimize and speed up the load process. We could perhaps batch insert stuff into database, but we first need to measure if database insertion really is the bottleneck...
> Bump timeout from 60 to 100 second for packs.load command

- st2client/st2client/models/core.py
one-line fix for STORM-2263: re-emit the trigger fails with 401 because the auth token is not passed.
PS. I don't know enough of CLI unit tests to see how to get it covered, so skipping this part, sorry.
> Fix trigger-instance re-emit

- CHANGELOG.rst
- st2actions/tests/unit/test_pythonrunner.py
- st2common/st2common/util/loader.py
- st2tests/st2tests/resources/packs/pythonactions/actions/test.py
This PR changes Python plugin (module) loading code so the module is still loaded even if the module name clashes with another module which is already in `PYTHONPATH`.
The change should be fully backward compatible, but it still needs some more testing to make sure it doesn't break some existing behavior.
This change affects Python runner actions and sensors and resolves #2650.
> Change Python module loading code

- CHANGELOG.rst
- st2actions/tests/unit/test_actions_registrar.py
- st2common/st2common/util/schema/action_params.json
- st2tests/st2tests/fixtures/generic/actions/action_invalid_param_type.yaml
This pull request fixes validation for `type` attribute of action parameters.
Existing JSON schema was incorrect so we allowed any string value and not just valid types. Since this wasn't caught before it looks like we didn't have any tests for this edge case.
This was originally discovered and reported by @LindsayHill in https://github.com/StackStorm/st2contrib/pull/532.
> Fix validation of "type" attribute for action parameters

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/unload.py
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/rules.py
- st2common/st2common/models/api/rule.py
- st2common/st2common/util/api.py
This pull request addresses #2869 and allows users to still list and retrieve rules even if a rule in a database references a trigger which has been deleted because a pack which provides that trigger has been removed.
This is a pretty common use case which we don't handle right now - we only clean up triggers for rules which belong to the pack which is uninstalled. If there is a pack A and pack B with a rule which references a trigger inside a pack A and user uninstalls pack A, rule inside a Pack B won't be deleted (that's of course when user is working via the API and / or using `packs.uninstall` command).
One option would be to also clean up all the rules which reference a trigger from the pack which is being uninstalled (even the rules from other packs). I personally think that's a …
> Rules API robustness improvements

- CHANGELOG.rst
- st2api/st2api/controllers/v1/sensors.py
- st2api/tests/unit/controllers/v1/test_sensortypes.py
- st2tests/st2tests/fixtures/packs/dummy_pack_1/sensors/my_sensor.yaml
This pull request fixes an issue reported in #2878.
We introduced a regression recently because we had no test case for a sensor disable / enable scenario (this has now also been fixed).
> Fix disabling and enabling a sensor through an API

- st2actions/st2actions/runners/httprunner.py
- OS: CentOS 7
```
[root@ac58573ad609 ~]# rpm -qa | grep st2
st2-1.7dev-19.x86_64
st2web-1.7dev-2.x86_64
st2chatops-1.7dev-1.x86_64
st2mistral-1.7dev-20.x86_64
```
Starting from [requests](https://github.com/kennethreitz/requests) v2.11.0, any header values with type of other than str seems to be not accepted any more. Without this change, http_runner throughs an error if you set any body parameter:
```
[root@ac58573ad609 /]# st2 run core.http method=POST url="http://httpbin.org/post" body="hoge"
.
id: 57bd7ae1bf4c610064eda266
status: failed
parameters:
body: hoge
method: POST
url: http://httpbin.org/post
result:
error: Header value 4 must be of type str or bytes, not <type 'int'>
traceback: "  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/container/base.py", line 98, …
```
> Fix bug: header value must be str

- fixed-requirements.txt
- requirements.txt
Something we should have done before to avoid backward incompatible changes related issues such as this one - https://github.com/StackStorm/st2/pull/2880.
> Pin requests to a more specific version

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/tests/unit/test_commands.py
We didn't correctly handle `exclude_attributes` API query parameter if user selected to display a child attribute of either `result` or `trigger_instance` object when using `st2 execution get` command.
For example, `--attr result` worked, but `--attr result.stdout` didn't because we incorrectly excluded `result` attribute from the API response in the second scenario.
This PR fixes that.
Resolves #2858.
> Fix handling of result and trigger_instance attribute in st2 execution get command

- st2api/st2api/controllers/resource.py
Problem: while working on https://github.com/StackStorm/st2/pull/2842, I've encounter strange lining issues related to missing config section (see [full traceback](https://github.com/StackStorm/st2/pull/2844#issuecomment-236864688) down below).
Per @kami proposal, I'm going to make `max_limit` a property to prevent pylint from trying to resolve it.
> Fix linting errors related to missing config section

- CHANGELOG.rst
- st2api/st2api/controllers/v1/traces.py
- st2api/tests/unit/controllers/v1/test_traces.py
- st2client/st2client/commands/trace.py
- st2common/st2common/models/db/trace.py
This pull request updates traces list API endpoint and ``st2 trace list`` CLI commands so it works in the manner user expects it to and so it's consistent with the ``st2 execution list`` command and related API endpoint:
1. Update default sort order for the API endpoint - now traces are sorted by start_timestamp (descending) first and trace_tag second
2. Fix ``-n`` parameter and make sure traces are sorted correctly (descending order) when this parameter is supplied
3. Allow user to specify sort order through the API and CLI (e.g. ``st2 trace list -n 5 --sort asc``)
Closes #2855.
> Various traces API and CLI improvements

- st2api/st2api/controllers/v1/actionalias.py
- st2api/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
- st2common/st2common/rbac/resolvers.py
- st2common/st2common/rbac/types.py
This pull request updates the code so a new global "action_alias_match" permission is required to be able to call new "action alias match" API endpoint.
Part of #2895 #2904
> RBAC for new "action alias match" API endpoint

- CHANGELOG.rst
- st2common/st2common/util/param.py
- st2common/tests/unit/test_param_utils.py
This pull request adds support for using Jinja notation for action default parameter values for parameters of type object.
This issue (lack of feature / support for objects) was caught and reported by @code-ape on Slack.
He had an action similar to the one below:
```yaml
---
name: example
pack: examples
description: Example
runner_type: http-request
enabled: true
parameters:
driveraddress:
type: string
required: true
default: "10.255.4.15:3000" 
host:
type: string
required: true
port:
type: integer
required: true
params:
type: object
immutable: true
default:
host: "{{host}}"
port: "{{port}}"
url:
type: string
immutable: true
default: "http://{{driveraddress}}/api/gen-payload/ve"
```
This didn't work since default values for `params` parameter was not rendered since existing code didn't …
> Add support for Jinja template notation for default parameter values for object parameters

- CHANGELOG.rst
- fixed-requirements.txt
- st2actions/tests/unit/test_actions_registrar.py
- st2common/st2common/models/api/action.py
- st2common/st2common/models/api/execution.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/api/policy.py
- st2tests/st2tests/fixtures/generic/actions/action_invalid_parameter_name.yaml
While looking into #2907 I noticed our code is broken / incorrect everywhere where we use `patternProperties` functionally of json schema.
We limit valid names for property to any valid word character (`\w` - `a-Z0-0_`), but we don't specify `'additionalProperties': False`. Not specifying that means that any other name which doesn't fall into that (e.g. parameter name which contains a dash or any other character which falls outside of `\w`) will be considered as additional property and no validation will be performed for that property/
For one, this means we allow dashes and other special characters which causes issue because for example, Jinja doesn't support dashes in the variable names, etc. In addition to that, it's dangerous (and not user-friendly) since we don't perform any …
> Only allow word characters and don't allow slashes in action parameter names

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/tests/unit/test_action.py
This answers #2903.
This PR allows a user to input an array of dicts or other complicated types of arrays from the CLI. It will first attempt to json load the parameter and if that fails it reverts back to separating the values by commas.
> Adding ability to json load array from CLI

- st2actions/tests/unit/test_actions_registrar.py
- st2common/st2common/bootstrap/actionsregistrar.py
This pull request builds on top of #2908 and update the exception to be more user-friendly.
Original json schema exception is very unfriendly and it's not immediately obvious what is going on (invalid parameter name).
> Throw more user-friendly exception on invalid action parameter name

- CHANGELOG.rst
- conf/st2.conf.sample
- st2api/st2api/config.py
- st2api/st2api/controllers/v1/traces.py
- st2api/tests/unit/controllers/v1/test_traces.py
- st2client/st2client/__init__.py
- st2client/st2client/commands/action.py
- st2client/st2client/commands/trace.py
- st2client/tests/unit/test_commands.py
- st2common/st2common/__init__.py
- st2common/st2common/models/db/trace.py
- st2common/st2common/util/param.py
- st2common/tests/unit/test_operators.py
- st2common/tests/unit/test_param_utils.py
Includes the following changes:
* #2886 
* #2887
* #2898 - Logrotate bug fix (already cherry-picked into v2.0 branch)
* #2906
> [DONT MERGE] Release branch for StackStorm v2.0.1 release

- CHANGELOG.rst
- st2client/st2client/commands/keyvalue.py
When a `user` argument was passed to the `st2 key delete` command it was not correctly passed to the API endpoint so it wasn't possible for an administrator to delete a user-scoped datastore item which belongs to a different user.
Resolves #2921.
> Fix --user / -u argument when using st2 key delete command

- st2common/st2common/config.py
- st2common/st2common/script_setup.py
- st2common/st2common/service_setup.py
- st2common/st2common/transport/bootstrap.py
- st2common/st2common/transport/bootstrap_utils.py
This PR adds connection retry to RabbitMQ transport. This will recover from issues where RabbitMQ is unavailable immediately on startup.
> Adding connection retry for RabbitMQ

- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/config.yaml
- st2api/st2api/controllers/v1/packs.py
- st2client/st2client/commands/pack.py
- st2client/st2client/commands/resource.py
- st2client/st2client/models/core.py
- st2common/st2common/config.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/services/packs.py
This PR adds:
1. A config entry that allows you to specify a pack index or a list of indexes. It defaults to our main index in the Exchange, but if there's some security concerns in a large enterprise, they can maintain their own index, or even a local one on the same host, or use both at the same time and have both their own packs and Exchange packs available for discovery. (Oh boy, @armab will geek out about the multiple indexes part.)
2. Helper functions in `st2common` for (1) fetching and combining the indexes, and (2) the index search.
3. The `pack/search` API endpoint that supports getting a single pack object by its name, or listing all packs matching a query.
4. The corresponding CLI commands (`st2 pack search <query>` and `st2 pack show <pack>`).
5. Changes to the …
> Pack search and working with pack indexes

- st2common/st2common/bootstrap/runnersregistrar.py
- st2common/st2common/content/bootstrap.py
- st2common/tests/integration/test_register_content_script.py
```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ nosetests -sv st2common/tests/integration/test_register_content_script.py
test_register_all_and_register_setup_virtualenvs (tests.integration.test_register_content_script.ContentRegisterScriptTestCase) ... ok
test_register_from_pack_action_metadata_fails_validation (tests.integration.test_register_content_script.ContentRegisterScriptTestCase) ... ok
test_register_from_pack_fail_on_failure_pack_dir_doesnt_exist (tests.integration.test_register_content_script.ContentRegisterScriptTestCase) ... ok
test_register_from_pack_success (tests.integration.test_register_content_script.ContentRegisterScriptTestCase) ... ok
test_register_from_packs_doesnt_throw_on_missing_pack_resource_folder (tests.integration.test_register_content_script.ContentRegisterScr …
```
> Fail on runner registration, cleanup configs

- CHANGELOG.rst
- st2api/st2api/controllers/resource.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
- st2common/st2common/models/api/base.py
- st2common/st2common/util/api.py
- st2common/tests/unit/test_logging.py
This pull request addresses two issues:
1. It fixes handling of `ValidationError` exception in the. Previously if exception was thrown due to an invalid ID being provided in the query string internal error was returned, not bad request error is returned.
2. It allows users to filter "get all" API responses on multiple resource ids by providing a comma delimited string value for the query parameter (e.g. `?id=1,2,3,4`).
This allows users to write more efficient clients and also reduces some overhead on the API. Previously user would either need to request all the objects and do late filtering locally or by performing multiple get one requests (one for each resource / object).
I'm personally not a fan id comma delimited string approach (HTTP already solves that by allowing client to provide …
> API exception handling fixes, allow user to filter get all responses on multiple resources id

- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2api/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
- st2common/st2common/rbac/resolvers.py
- st2common/st2common/rbac/types.py
This introduces basic RBAC for pack management API endpoints.
Right now all the permissions are "global" which for example means that user can either install all the packs or none.
In the future we can introduce support for globs / lists or similar we can also improve this (e.g. ability to only install a set of packs, but then again for RBAC installations, you should mirror the index and only include whitelisted packages you have audited so this might be of little use).
> RBAC for pack managemenet API endpoints

- st2api/st2api/controllers/v1/root.py
- st2api/st2api/controllers/v1/timer.py
- st2api/st2api/controllers/v1/timers.py
- st2api/tests/unit/controllers/v1/test_timers.py
- st2client/st2client/client.py
- st2client/st2client/commands/timer.py
- st2client/st2client/models/timer.py
- st2client/st2client/shell.py
- st2tests/st2tests/fixtures/timers/triggers/cron1.yaml
- st2tests/st2tests/fixtures/timers/triggers/date1.yaml
- st2tests/st2tests/fixtures/timers/triggers/interval1.yaml
- st2tests/st2tests/fixtures/timers/triggers/interval2.yaml
- st2tests/st2tests/fixtures/timers/triggers/interval3.yaml
Fixes: https://github.com/StackStorm/st2/issues/2935
```
(virtualenv)vagrant@st2dev /m/s/s/st2 ❯❯❯ st2 timer list                                                   STORM-2935/st2_timers_list ✭ ✱ ◼
+--------------------------+------+------------------------+------------------------+------------------------+
| id                       | pack | name                   | type                   | parameters             |
+--------------------------+------+------------------------+------------------------+------------------------+
| 58111229d9d7ed401851a354 | core | 762c3cdc-b712-4164     | core.st2.IntervalTimer | {u'unit': u'seconds',  |
|                          |      | -847b-ae94ab9c2a3a     |                        | u'delta': 5}           | …
```
> Support st2 timers list

- CONTRIBUTING.rst
Minor fix to CONTRIBUTING.rst so that a proper callout box is shown. The sphinx-style callout doesn't show up well when viewed in Github (which presumably is the primary use case for this).
> Add proper callout box for Python dependencies section

- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/tests/test_action_download.py
Two changes here:
1. Versions can also point to branches now (i.e. `st2 pack install sensu=development`).
2. Checking out commits / tags that aren't tips of the branches will not detach HEAD. Instead it will put you on the right branch and point to N commits back. 
(2) is important to figure out where in the history you actually are. If I checked out a specific version, `Your branch is behind 'origin/master' by 3 commits` is a pretty useful message. `HEAD detached at c46a25c` is not a useful message.
It also helps you work with your pack more effectively, since it's pretty easy to update your pack with fast-forwarding or even start a new branch from that particular commit if you want to. Detached HEAD would require you to figure out which branch it belonged to, do a merge or a checkout to …
> Pack management: branch checkouts

- contrib/core/actions/sendmail.yaml
Having `enum` in the `content_type` schema, restricts users from adding extras like `text/plain; charset="utf-8"`  
If we want to keep the restriction, I suppose we could add a `charset` argument to the send_mail script?
> Remove enum to allow for extra content-type arguments, like charset

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_pack_config_schema.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/constants/pack.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/db/pack.py
- st2common/st2common/util/versioning.py
- st2common/tests/integration/test_register_content_script.py
- st2common/tests/unit/test_resource_registrar.py
- st2common/tests/unit/test_versioning_utils.py
- st2tests/st2tests/fixtures/packs/dummy_pack_10/pack.yaml
- st2tests/st2tests/fixtures/packs/dummy_pack_11/pack.yaml
- st2tests/st2tests/fixtures/packs/dummy_pack_12/pack.yaml
- st2tests/st2tests/fixtures/packs/dummy_pack_9/pack.yaml
This pull request works on top of https://github.com/StackStorm/st2/pull/2988 and makes some changes @emedvedev and I discussed.
> Various pack schema changes

- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/test_mistral_querier_v2.py
- st2common/st2common/util/loader.py
- st2common/tests/fixtures/mock_runner/dist_utils.py
- st2common/tests/fixtures/mock_runner/mock_runner.py
- st2common/tests/fixtures/mock_runner/query/mock_runner.py
- st2common/tests/fixtures/mock_runner/runner.yaml
- st2common/tests/unit/test_util_loader.py
The frequent reloading of runner modules at runtime leads to random errors complaining the self instance of super(RunnerType, self).pre_run(...) is not instance type of the runner type. This PR address this issue by loading the runner modules only once and storing a copy of the module for reuse.
> Fix runner loader

- contrib/linux/actions/workflows/diag_loadavg.yaml
Updated single quotes to escaped doubled quotes to prevent bash syntax error for diag_loadavg workflow.
> Updated single quotes to escaped doubled quotes for loadavg workflow

- contrib/packs/actions/download.yaml
- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/workflows/install.yaml
- contrib/packs/tests/fixtures/stackstorm-test/pack.yaml
- contrib/packs/tests/fixtures/stackstorm-test2/pack.yaml
- contrib/packs/tests/fixtures/stackstorm-test3/pack.yaml
- contrib/packs/tests/test_action_download.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/util/pack.py
@emedvedev and I discussed this on Slack.
I still think all the checks should (also) happen during the pack register phase because that's the phase all the packs go through (not just the ones installed using `packs.install`, but also ones which follow opinionated git flow and skip `packs.install` all together), but that's a temporary middle group solution for now.
It's also worth nothing that even though checks should happen during register phase it's nothing wrong with also having the same check during the packs install phase - it allows us to fail faster and provide better user experience. We just need to make sure we are not duplicating code all over the place which is kinda true for `packs.install` right now which still needs refactor and robustness love.
Example output:
```bash
id: …
```
> Validate pack compatibility with running StackStorm version during packs.install

- st2common/st2common/garbage_collection/executions.py
- st2common/st2common/garbage_collection/trigger_instances.py
- st2common/st2common/models/db/__init__.py
This wasn't possible in older versions of mongoengine (pymongo), but for a while now we have been using and depending on a newer version where this information is available.
> Update "delete_by_query" method to return a number of deleted objects

- contrib/packs/actions/pack_mgmt/download.py
- st2common/st2common/constants/pack.py
- st2common/st2common/services/packs.py
1. Move common code from pack actions to st2common so it can be re-used elsewhere
2. Of user specifies an invalid version (ref) when installing a pack, print available versions.
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ python ./st2client/st2client/shell.py pack  install "vsphere=1.1.2"
[  failed   ] download pack
id: 582072430640fd7108bbca06
action.ref: packs.install
parameters: 
packs:
- vsphere=1.1.2
status: failed
error: Traceback (most recent call last):
File "/data/stanley/st2common/st2common/runners/python_action_wrapper.py", line 211, in <module>
obj.run()
File "/data/stanley/st2common/st2common/runners/python_action_wrapper.py", line 126, in run
output = action.run(**self._parameters)
File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line …
```
> Various pack management improvements

- contrib/packs/actions/pack_mgmt/download.py
> Fixes bug described in StackStorm/st2-packages#363
`--all` flag is not available for older `git` versions shipped with `EL6`, so use `-a` instead.
* git version 1.7.1 (`CentOS6`):
```sh
-a                    list both remote-tracking and local branches
```
* version 2.7.4:
```sh
-a, --all
List both remote-tracking branches and local branches.
```
> Fix old git syntax compatibility

- st2client/st2client/models/core.py
@kami: @LindsayHill updated the docs: https://github.com/StackStorm/st2docs/pull/305. But this is what changed the behavior: https://github.com/StackStorm/st2/pull/503/files#diff-212b279de225b603d0bc7fe4e00ae449R127. IMHO we should change it back to `name` otherwise it will confuse users: https://github.com/StackStorm/st2/issues/2948. Also the doc. needs more love. 
```
>>> from st2client.client import Client
>>> from st2client.models import KeyValuePair
>>> client = Client(base_url='http://localhost')
>>> client.keys.update(models.KeyValuePair(name='os_keystone_endpoint', value='http://localhost:5000/v2.0'))
File "<stdin>", line 1, in <module>
NameError: name 'models' is not defined
name 'models' is not defined
>>> …
```
> Changing `name_or_id` back to `name` in get_by_name()

- contrib/packs/actions/pack_mgmt/download.py
Expanded all the ugly git shortcuts, this should fix RHEL6.
> Support ancient git versions in packs.download

- fixed-requirements.txt
- requirements.txt
After @emedvedev fixing https://github.com/StackStorm/st2/pull/3008,
there was another one with `gitpython` library infinite loop (starting from [this line](https://github.com/StackStorm/st2/blob/ca19e2045f941196e3817eb19f5ddf15c4f6098f/contrib/packs/actions/pack_mgmt/download.py#L100)) which blocked the builds for `EL6` with timeout during the pack download.
Luckily, spending entire day with @enykeev debugging it, simple `gitpython` library upgrade worked as a last minute fix.
Let's see If this finishes [EL6 epopeya](https://github.com/StackStorm/st2-packages/issues/363).
> Fix ancient git EL6 bug with newer gitpython

- CHANGELOG.rst
- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/tests/test_action_download.py
- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2client/st2client/commands/pack.py
- st2client/st2client/models/core.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/models/db/pack.py
- st2common/tests/unit/test_resource_registrar.py
- st2tests/st2tests/fixtures/packs/dummy_pack_1/pack.yaml
1. Add new `contributors` field to the pack model and metadata file. This field follows the format of the same named field in the Node.js / npm package.json file. The value is optional and can contain a list of people who have contributed to the pack.
Before that, we only had an author field and a lot of pack these days have more than one contributor, but we had no good way to indicate that and give credit where credit is due.
2. Update `force` parameter in the `packs.download` and `packs.install` action to also remove the lock file if one exists. This allows user to force install a pack and clean-up a stuck lock without needing to SSH into the server in case for some reason lock wasn't correctly cleaned up / released.
3. Allow user to pass `--force` flag to `st2 pack install` command.
> Various pack related changes

- .flake8
- .pylintrc
This change would allow pylint and flake8 to utilize our rc files automatically by leveraging their existing search path. This allows developers to leave their existing rc files untouched and use these "automatically" for the ST2 project.
> Add symlinks for flake8 and pylint rc files

- st2client/st2client/commands/pack.py
- st2client/st2client/commands/resource.py
```
usage: st2 pack [-h] {list,get,show,search,install,remove,register,config} ...
A group of related integration resources: actions, rules, and sensors.
positional arguments:
{list,get,show,search,install,remove,register,config}
List of commands for managing packs.
list                Get the list of packs.
get                 Get information about an installed pack.
show                Get information about an available pack from the
index.
search              Search the index for a pack with any attribute
matching the query.
install             Install new packs.
remove              Remove packs.
register            Register a pack: sync all file changes with DB.
config              Configure a pack based on config schema.
optional arguments:
-h, --help            show this help …
```
> Improve descriptions in pack CLI

- CHANGELOG.rst
- contrib/packs/actions/load.yaml
- contrib/packs/actions/pack_mgmt/register.py
- contrib/packs/actions/workflows/install.yaml
- contrib/packs/actions/workflows/uninstall.yaml
- st2client/st2client/commands/pack.py
This pull request updates `packs.install` and `packs.register` action to only register resources from packs which are being installed.
Before that, we registered resources from all the packs on install. This could take a very long time in case user had a lot of packs and resources locally. This new change makes the user experience better since the whole process completes faster.
Before:
```bash
(virtualenv)vagrant@vagrant-ubuntu-trusty-64:/data/stanley$ time python ./st2client/st2client/shell.py pack install datadog consul
2016-11-10 10:02:06,123  WARNING - Auth API server is not available, skipping authentication.
[ succeeded ] download pack
[ succeeded ] make a prerun
[ succeeded ] install pack dependencies
[ succeeded ] register pack
[  failed   ] restart sensor container
id: …
```
> On packs.install only register resources from installed pack(s)

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
This commit makes changes to the st2api so that the entire execution
object is returned to API calls that attempt to cancel execution
objects that are already cancelled, instead of returning a simple
error message.
Previously, an API call to this API would result in the following error message:
```
~>curl -X DELETE -H  'Connection: keep-alive' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'User-Agent: python-requests/2.11.1' -H  'X-Auth-Token: c64c7c82be38408f9dc406ceb2640d77' -H  'Content-Length: 0' http://127.0.0.1:9101/v1/executions/57fee1b6c506f479b9c58e97
{
"faultstring": "Action is already in \"canceled\" state."
}
```
Now, the API will return a full execution object, as shown [here](https://gist.github.com/Mierdin/cf97f23ddd9ada1d4965b089b6561d24).
This fixes …
> Return entire execution object if execution is already canceled

- st2common/st2common/bootstrap/runnersregistrar.py
Change `info` level logging of runner register to `debug` so that output is consistent with other loaders.
> Make Runner Loader Have Consistent Output

- st2api/st2api/app.py
- st2common/st2common/hooks.py
- st2stream/st2stream/app.py
There's an inconsistency in handling the `x-auth-token` query param when sending it to the server with disabled auth makes /stream endpoint return 400 due to different controller signature.
> Move auth enable check to the hook itself

- fixed-requirements.txt
- requirements.txt
This version drops support for MongoDB < 2.4, but this doesn't affect us since we install and require MongoDB > 3.0 by default for a while now.
Older StackStorm installations uses 2.4 or 2.6 which is still supported.
> Upgrade pymongo to 3.3.0 (latest stable version)

- CHANGELOG.rst
- st2common/st2common/models/db/execution.py
Fixes #2876 
Dramatically improves TTFB of the /executions/views/filters request by preparing indexes for the fields ahead of time.
For our production set of 99k executions, before the change:
```
$ curl -w "@curl-format.txt" -o /dev/null -s 172.168.50.50:9101/v1/executions/views/filters
time_namelookup:  0.000
time_connect:  0.000
time_appconnect:  0.000
time_pretransfer:  0.000
time_redirect:  0.000
time_starttransfer:  60.616
----------
time_total:  60.616
```
after
```
$ curl -w "@curl-format.txt" -o /dev/null -s 172.168.50.50:9101/v1/executions/views/filters
time_namelookup:  0.000
time_connect:  0.000
time_appconnect:  0.000
time_pretransfer:  0.000
time_redirect:  0.000
time_starttransfer:  0.080
----------
time_total:  0.080
```
The change has very tiny footprint comparing to …
> Add indexes for distinct fields

- contrib/packs/actions/pack_mgmt/download.py
- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2client/st2client/commands/pack.py
- st2common/st2common/bootstrap/ruletypesregistrar.py
Cherry picked just the CLI syntax change from #3020.
Resolves #3001
I'm also working on some other related improvements and fixes.
> New pack register CLI command syntax and various other pack register API endpoint improvements

- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
This fixes a bug in the result object of the packs register API endpoint.
The "registered count" values were not correctly being added together when registering multiple packs. Instead of adding the values together, the count from the last pack registered always overwrote the result.
> Fix registered content counts returned by the packs register API endpoint

- st2common/st2common/jinja/filters/data.py
It is my impression that this filter is mainly used to produce readable representation of the object. Unless `default_flow_style` is strictly defined, yaml dumper would pick the one it seem appropriate producing quite different formatting for pretty similar kind of input.
Flow style
```
{author: st2-dev, description: StackStorm pack management, email: info@stackstorm.com,
name: st2, version: 0.1.2}
```
vs block style
```
author: st2-dev
description: st2 content pack containing github integrations
email: info@stackstorm.com
keywords:
- github
- git
- scm
name: github
version: 0.4.0
```
> Set default_flow_style for yaml jinja filter

- conf/st2.dev.conf
- conf/st2.package.conf
- conf/st2.prod.conf
- conf/st2.tests.conf
- conf/st2.tests1.conf
Originally reported in #community.
User uncommented only `webui_base_url = https://mywebhost.domain` without uncommenting `[webui]` section, ex:
```ini
webui_base_url = https://mywebhost.domain
```
See: https://github.com/StackStorm/hubot-stackstorm/issues/129#issuecomment-262007128
With this small change it looks safer, more obvious and less error-prone default.
> Uncomment [webui] section in st2.conf

- contrib/packs/aliases/pack_install.yaml
Teeny tiny typo :) Or maybe not even a typo, the PR might’ve been opened when we still had `#` as a tentative version separator.
> Fix a typo in the pack install alias

- contrib/packs/aliases/pack_install.yaml
`=` is not acceptable in Action Alias as separator between `pack=version` because of https://docs.stackstorm.com/chatops/aliases.html#key-value-parameters
So adjusting description accordingly.
> Fix description for 'pack install' Alias

- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/tests/test_action_download.py
- Make st2 pack.install work with file:///path/to/local/git/repo.
- Add unit tests to cover permutations.
> Make pack install work with local git repo

- st2common/st2common/runners/python_action_wrapper.py
This fixes the issue inside BWC packs reported by @samirsss.
Sadly it means we need to revert one of the Python runner performance improvements. Some of the third part libraries such as paramiko and cryptography depend on `pkg_resources` functionality which is not available in much faster `entrypoints` library fork.
There are ways around that, but doing that would take me multiple days so I decided to revert the change for now. In the future, I do plan to look into it again though since it offers quite good speedups (500-600ms) for the average case where more advanced pkg_resources functionality is not used.
I will probably do something along the lines of using `entrypoints` for the common functionality which is already available in `entrypoints` and when additional more advanced …
> Fix "pkg_resources" related import issues

- st2common/st2common/constants/pack.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/util/pack.py
- st2common/tests/unit/test_resource_registrar.py
- st2common/tests/unit/test_versioning_utils.py
This adds back pack version normalization (+ extra tests, etc.) from https://github.com/StackStorm/st2/pull/2990.
This way the upgrade to v2.1.0 will be more smooth and break less backward compatibility. We will still advise users to update their pack metadata when they get a chance since non-valid semver version strings are deprecated and we will fully drop support for it in one of the next major releases.
Will cherry pick into v2.1.
> Add pack back pack version normalization

- st2common/st2common/runners/python_action_wrapper.py
This pull request works on top of https://github.com/StackStorm/st2/pull/3075.
The work-around in that PR worked fine locally, but not with actual packages inside production. The problem was that I used a very safe, but also a very restrictive path check which works locally, but not with packages which use a virtualenv  for st2 so paths are different.
Here is an example of actual BASE_DIR and SCRIPT_PATH with packages:
* /opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners
* /opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners
Luckily we now also have en end to end test in addition to unit test which caught this.
> Workaround for Python action runner subprocess sys.path pollution (take 2)

- st2common/st2common/runners/python_action_wrapper.py
Cherry pick of https://github.com/StackStorm/st2/pull/3088 for v2.1.
> Workaround for Python action runner subprocess sys.path pollution (take 2) (v2.1)

- CHANGELOG.rst
Re-shuffled the v2.1 changelog entries to consolidate the pack management-related changes under one list.
/cc @dzimine
> Combine pack management changelog entries

- st2common/bin/st2-self-check
Git clone fails on second attempt as the s2tests folder is not deleted: `fatal: destination path 'st2tests' already exists and is not an empty directory.`
> Add step to delete st2tests dir. in st2-self-check script

- st2common/st2common/util/actionalias_matching.py
- st2common/tests/unit/test_util_actionalias_matching.py
exception and provide sane default values.  Normalised representation keys provided as strings types to be returned as list types.
Unit tests were added to test the results of display only dictionaries and representation only dictionaries.
> Fixes #3063. Stopped directly accessing dict keys to avoid KeyError

- st2actions/tests/unit/policies/test_retry_policy.py
- st2common/st2common/services/executions.py
Was just looking / debugging some stuff to make sure that the execution contains policy related context and noticed we don't actually have any test which verifies that the context is present and correct so I added some.
> Add some additional tests for retry policy

- CHANGELOG.rst
- st2common/st2common/models/api/pack.py
- st2common/st2common/util/pack.py
- st2common/tests/unit/test_resource_registrar.py
- st2tests/st2tests/fixtures/packs/dummy_pack_13/pack.yaml
- st2tests/st2tests/fixtures/packs/dummy_pack_14/pack.yaml
Default jsonschema exceptions are not that friendly so this pull request updates the code to throw a more user-friendly error in case pack ref / name contains invalid characters.
It's also worth noting that this pattern is becoming more common  in our code base (wrap original jsonschema exception and throw something more user-friendly) so we should probably come up with some kind of consistent "approach" / "conventions" for handling it consistently through the code base.
> Throw more user-friendly exception on invalid pack name

- st2debug/st2debug/cmd/submit_debug_info.py
In addition to log files and stdout/stderr, I had the need to run a shell script as a `shell_command` when running submit_debug_info.py to generate a debug bundle.  The use case for the shell script is to create and then collect various additional files outside of the purview of st2 and place them in the tmp****** directory to be included in the archive. 
In order to do so effectively, I needed the shell script to reliably know the path to the temporary directory.  This change sets the `output_path` as the working directory of the subprocess which executes the shell command.  Ex: `/tmp/tmpp0qiO5/commands`
> submit-debug-info: pass the `output_path` as the shell command working directory

- circle.yml
This change is needed to start experimenting with moving away from Travis. Circle would refuse to run PRs with updated circle.yml unless we remove `branches.only` from the master version.
> Run circle for every PR

- st2common/st2common/models/system/action.py
- st2common/tests/unit/test_shell_action_system_model.py
Previously, unicode parametera are unable to pass for the `local-shell-scripts` type Actions, like this.
```
[dooga@localhost ~]$ st2 action get default.test
+-------------+--------------------------+
| Property    | Value                    |
+-------------+--------------------------+
| id          | 5850f582e138233f0387c9b2 |
| uid         | action:default:test      |
| ref         | default.test             |
| pack        | default                  |
| name        | test                     |
| description |                          |
| enabled     | True                     |
| entry_point | test.sh                  |
| runner_type | local-shell-script       |
| parameters  | {                        |
|             |     "param": {           |
|             |         "type": …
```
> Correction to be able to pass unicode parameters to Actions

- CHANGELOG.rst
- contrib/packs/actions/load.yaml
Part of https://github.com/StackStorm/st2/issues/3112.
Not loading rules by default was intentional, but not loading triggers was an oversight - we missed it when we added support for new triggers resource type.
> Update packs.load to register triggers by default

- CHANGELOG.rst
- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
This pull request fixes pack register API endpoint to register different resource types in the exact same order as we use in `st2-register-content`.
Not registering it in the same order can cause multiple issues:
1. Output which it not consistent with `st2-register-content`. This could be confusing because both scripts fail on failure by default, but they could fail with a different error in case a different resource register order is used (e.g. one fails with an error inside action metadata first and other fails with an error inside rule).
2. Rules could get registered before sensors / triggers which would cause an error (trigger doesn't exist).
This addresses an issue indirectly reported in https://gist.github.com/lakshmi-kannan/6493c0d303df0622145730cf6b8e2b22. @lakshmi-kannan reported …
> Use the same registration order inside the packs register API as we do in st2-register-content

- CHANGELOG.rst
- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2client/st2client/commands/pack.py
This pull request fixes "get one" packs API endpoint - it would return no items if the pack name didn't match a ref.
The method itself was fine, but the actual problem was RBAC - rbac defaulted to using "get_by_name_or_id" instead of "get_by_ref_or_id".
> Fix "get one" packs API endpoint

- CHANGELOG.rst
Underline for v2.1.1 changelog not long enough, causing v2.1 doc builds to fail.
> Fixed heading underline length

- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/tests/resources/test_sensor_with_typo.py
- st2reactor/tests/unit/test_sensor_wrapper.py
When we re-throw a more user-friendly exception we didn't include the original stack trace which would make some issues harder to debug (it didn't include additional stack trace which would point user to the offending line in the sensor file and similar).
Caught by @enykeev.
> Include original traceback when re-throwing an exception inside the sensor wrapper

- CHANGELOG.rst
- st2actions/st2actions/policies/retry.py
- st2actions/tests/unit/policies/test_retry_policy.py
Retry policy is not supported for action executions under workflows. Let specific workflow engine handles retries where applicable. Currently, action execution will retry on failure and timeout but workflow fails immediately.
> Fix retry policy

- st2actions/st2actions/policies/concurrency.py
- st2actions/st2actions/policies/concurrency_by_attr.py
- st2actions/tests/unit/policies/test_concurrency.py
- st2actions/tests/unit/policies/test_concurrency_by_attr.py
While evaluating the concurrency policies, the live action was published again and led to duplicate executions. This patch fixes the concurrency policies to only publish if the live action state is changed to cancelling.
> Fix duplication action execution in concurrency policies

- CHANGELOG.rst
- st2auth/st2auth/backends/__init__.py
This pull request updates `get_backend_instance` method to include more context and throw a more user-friendly exception when retrieving an auth backend instance fails.
Previously, the error didn't include configured auth backend name, etc. which made it harder and more time consuming to debug issues such as typos, misconfiguration and similar in the st2 config.
Before:
```bash
2017-01-06 13:21:23,210 INFO [-] Creating st2auth: StackStorm v2.2dev as Pecan app.
2017-01-06 13:21:23,328 DEBUG [-] found extension EntryPoint.parse('flat_file = st2auth_flat_file_backend.flat_file:FlatFileAuthenticationBackend')
2017-01-06 13:21:23,329 ERROR [-] (PID=14210) ST2 Auth API quit due to exception.
File "/data/stanley/st2auth/st2auth/cmd/api.py", line 87, in main …
```
> Throw more user-friendly exception when instantiating auth backend

- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py
Mistral list function for task execution no longer returns result. This patch iterates through the list and make additional calls to get task result. Merge this patch just before st2's mistral fork syncs with upstream.
> Fix mistral API call to get task result

- contrib/examples/actions/mistral-jinja-st2kv-system-scope-encrypted.yaml
- contrib/examples/actions/mistral-jinja-st2kv-system-scope.yaml
- contrib/examples/actions/workflows/mistral-jinja-st2kv-system-scope-encrypted.yaml
- contrib/examples/actions/workflows/mistral-jinja-st2kv-system-scope.yaml
- st2common/st2common/util/workflow/mistral.py
- st2common/tests/unit/test_util_mistral_dsl_transform.py
- st2tests/integration/mistral/test_st2kv.py
- st2tests/st2tests/fixtures/generic/workflows/wf_has_jinja_st2kv_post_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_has_jinja_st2kv_pre_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_jinja_mixed_context_ref1.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_jinja_mixed_context_ref2.yaml
Mistral added jinja evaluation and breaks st2kv rendering via jinja. This patch wraps any jinja as raw if there is any st2kv reference.
> Fix mistral upstream integration

- CHANGELOG.rst
- contrib/runners/mistral_v2/mistral_v2.py
- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_cancel.py
Use the newly introduced CANCELLED state in mistral for workflow cancellation. Currently, st2 put the workflow in a PAUSED state in mistral.
> Refactor mistral to support new CANCELLED status

- contrib/linux/actions/traceroute.sh
> Reported in Slack community by @livelace
Original `traceroute.sh` which is part of `linux.traceroute` action doesn't preserve line separators, what's confusing for users, thinking that StackStorm itself eat some line separators.
@livelace By design StackStorm shows what he get from the script via stdout, stderr and exit code.
This small change should fix `linux.traceroute` action.
```sh
./traceroute.sh google.com
traceroute to google.com (216.58.209.174), 30 hops max, 60 byte packets ...ae-3-3201.bar1.Budapest1.Level3.net (4.69.201.158) 24.733 ms 24.775 ms 24.971 ms 8 72.14.243.192 (72.14.243.192) 24.934 ms 24.892 ms 24.850 ms 9 209.85.243.119 (209.85.243.119) 45.224 ms 25.112 ms 25.077 ms 10 66.249.95.61 (66.249.95.61) 25.038 ms 25.150 ms 25.224 ms 11 bud02s21-in-f174.1e100.net …
```
> Fix linux.traceroute stdout formatting

- st2client/st2client/commands/action_alias.py
- st2client/st2client/models/action_alias.py
Fixes a small typo caught by @LindsayHill in #3165.
> Fix typo in the CLI help output

- st2tests/integration/mistral/test_wiring.py
The format of state_info has been changed. A bug report has been filed at launchpad. This is a temporary fix to get CI to pass. https://bugs.launchpad.net/mistral/+bug/1662350
> Fix mistral integration test for state_info

- CHANGELOG.rst
- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py
- st2actions/tests/integration/test_resultstracker.py
- st2common/st2common/exceptions/resultstracker.py
- st2common/st2common/query/base.py
Add option in querier plugin to specify whether state object should be deleted if an error occur during query. This allows querier to recover in case of unexpected environment related exceptions. Mistral querier is refactored to delete state object on workflow completion or when the workflow or task references no longer exists.
> Let querier plugin decide to delete state object on error

- st2client/st2client/commands/auth.py
Fixing an issue caused in post-merge by https://github.com/StackStorm/st2/pull/3123.
This wasn't caught by CI because that PR was done via a fork, and some CircleCI checks are disabled for forks. Submitting this to the main repo to ensure this still works.
> Import configparser from 'six' rather than stdlib

- contrib/examples/actions/mistral-jinja-branching.yaml
- contrib/examples/actions/mistral-jinja-env-var.yaml
- contrib/examples/actions/mistral-jinja-repeat-with-items.yaml
- contrib/examples/actions/workflows/mistral-jinja-branching.yaml
- contrib/examples/actions/workflows/mistral-jinja-env-var.yaml
- contrib/examples/actions/workflows/mistral-jinja-repeat-with-items.yaml
Add examples on how to use Jinja expresssions to branch in workflow, iterate thru with-items, and access the variables returned from the env() filter.
> Add more Jinja examples for Mistral
