StackStorm/st2

- st2api/st2api/cmd/api.py
- st2api/st2api/listener.py
> Update listener to stop processing messages in the generator when shutdown is called

- docs/source/rules.rst
- st2reactor/tests/unit/test_data_transform.py
- Test for hyphenated key
- Docs
> Support minus criteria

- CHANGELOG.rst
- docs/source/rules.rst
- st2common/st2common/operators.py
- st2common/tests/unit/test_operators.py
Adds new ``startswith``, ``istartswith``, ``endswith`` and ``iendswith`` convenience comparison operators which make criteria more readable.
> Add new rule criteria operators: startswith, istartswith, endswith, iendswith

- st2actions/st2actions/runners/fabricrunner.py
> Avoid dereferencing none.

- st2common/tests/unit/test_jsonify.py
Totally forgot to check in the tests file :/
> Add test cases for json.loads

- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2common/st2common/constants/system.py
- st2common/st2common/services/keyvalues.py
- st2common/tests/unit/test_keyvalue_lookup.py
- st2reactor/st2reactor/rules/datatransform.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_typed_system_params.json
- 'utility' to do keyvalue lookup which support hierarchical key structure (kind of)
- support for key values stored in datastore in actionchains
> Keyvalue lookup support in actionchains

- README.md
This PR brings in the overview of the project to the repository, in the event that the entry point for new users is via GitHub. Will help provide additional context about the goals of the project.
> Beef up Readme

- st2common/st2common/models/system/action.py
- Remote script action
```
$ st2 run default.data_gen hosts="st2master001" chars=1000 -a
+-----------------+-----------------------------+
| Property        | Value                       |
+-----------------+-----------------------------+
| id              | 54b6d5600640fd62c48bac2c    |
| context         | {                           |
|                 |     "user": "stanley"       |
|                 | }                           |
| parameters      | {                           |
|                 |     "chars": 1000,          |
|                 |     "hosts": "st2master001" |
|                 | }                           |
| status          | scheduled                   |
| start_timestamp | 2015-01-14T20:45:20.943512Z |
| result          |                             |
| action …
```
> Report error as structured data in fabric runner.

- st2api/Makefile
- st2auth/Makefile
- st2common/Makefile
- st2reactor/Makefile
Fixing whitespace errors due to expandtab in vim.
> Changed spaces to tabs in spec files

- docs/source/reference/packs.rst
> Fix community contributions docs - add missing fork step

- CHANGELOG.rst
- st2actions/st2actions/container/base.py
- st2actions/st2actions/utils/param_utils.py
- st2actions/tests/unit/test_param_utils.py
- st2tests/st2tests/fixtures/generic/actions/action_system_default.json
- Support for specifying system variable stored in kv-store as default values of variables.
> Resolve system variables in actions

- Makefile
- st2api/packaging/rpm/st2api-rhel6.spec
- st2auth/packaging/rpm/st2auth-rhel6.spec
- st2client/Makefile
- st2client/setup.py
- st2common/Makefile
- st2common/packaging/rpm/st2common-rhel6.spec
- st2reactor/packaging/rpm/st2reactor-rhel6.spec
> Adding RHEL6 packaging support to v0.7

- contrib/examples/actions/mistral-basic.yaml
- contrib/examples/actions/mistral-workbook-basic.yaml
- contrib/examples/actions/mistral-workbook-complex.yaml
- contrib/examples/actions/mistral-workbook-subflows.yaml
Mistral changed how task result is accessed.
> Update mistral workflow examples

- docs/source/index.rst
- docs/source/webhooks.rst
- st2api/st2api/controllers/v1/webhooks.py
- st2client/st2client/client.py
- st2client/st2client/commands/webhook.py
- st2client/st2client/models/webhook.py
- st2client/st2client/shell.py
Webhook documentation, CLI commands for listing webhooks.
> Webhook documentation, CLI commands for listing webhooks

- CHANGELOG.rst
- st2actions/tests/unit/test_actions_registrar.py
- st2common/st2common/models/api/action.py
- st2tests/st2tests/fixtures/generic/actions/action-with-no-parameters.yaml
Previously schema validation would fail. If action contains no parameters it should also not contain `parameters` attribute in the metadata file.
Spotted by @jfryman 
```
2015-01-30 07:57:31,153 DEBUG [-] Loading action from /opt/stackstorm/packs/rackspace/actions/list_vm_images.yaml.
2015-01-30 07:57:31,161 ERROR [-] Unable to register action: /opt/stackstorm/packs/rackspace/actions/list_vm_images.yaml
File "/usr/lib/python2.7/dist-packages/st2actions/bootstrap/actionsregistrar.py", line 121, in _register_actions_from_pack
self._register_action(pack, action)
File "/usr/lib/python2.7/dist-packages/st2actions/bootstrap/actionsregistrar.py", line 97, in _register_action
action_api = ActionAPI(**content)
File …
```
> Allow user to register actions without parameters

- st2api/setup.py
Previous templates/ directory was not included.
> Fix a packaging bug and make sure we also include templates directory

- st2actions/st2actions/query/mistral/v2.py
- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_actionchain.py
- st2actions/tests/unit/test_mistral_v2.py
* Change action chain runner result output matches unified format proposed by @enykeev 
* Change mistral runner result output matches unified format proposed by @enykeev 
/cc #1045
> Unified workflow result output

- st2actions/st2actions/runners/httprunner.py
> Http runner style refactor

- docs/source/cli.rst
> Document CLI command -j and -k flags

- .travis.yml
- Makefile
- st2actions/tests/integration/test_localrunner.py
* Including itests in build guarantees that build fails when itests break. 
* Fixed broken tests.
> Include itests

- st2common/st2common/services/action.py
* Presumably something to do with rabbitmq connections.
> Skip publishing of action execution creation.

- st2common/st2common/services/action.py
> Revert "Skip publishing of action execution creation."

- st2common/st2common/transport/publishers.py
* There are some limits on number of channels per connection around 64K. Also, Rabbitmq
supports roughly 2000 connections per node. With this change it effectively means that we
use only 64K channels in parallel per connection. Seems unlikley we ever hit this limit
since the channel is cleaned-up immediately and rmq reuses channel numbers.
* However, what we really require is for the channel to be created per exchange or a channel
pool per exchange per process. With producer pool + connection pool it is hard to work out
such a combination so this gross mechanism for now.
> Create a new channel for every publish

- st2api/tests/unit/controllers/v1/test_actionexecutions.py
Rearranging the code in the hope that next time a failure hits we may have some more information.
> Re-arrange test code.

- contrib/packs/actions/pack_mgmt/download.py
See: https://stackstorm.atlassian.net/browse/STORM-1065
> Fix bug where rerunning pack install creates a recursive dir inside pack

- st2client/st2client/commands/action.py
> Don't specify a width - we should default to the terminal width

- CHANGELOG.rst
- st2api/st2api/controllers/v1/datastore.py
- st2api/tests/unit/controllers/v1/test_kvps.py
- st2client/st2client/commands/datastore.py
- st2client/st2client/models/core.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/tests/unit/test_sensor_wrapper.py
> Sensor wrapper global datastore access

- st2actions/st2actions/query/mistral/v2.py
I'll cherry pick this change into hotfix branch for CITIES off sha 3376d9bc0a9c1377d6daf36381e57125a3654716
> Handle mistral connection errors; don't delete state

- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/rules.py
- st2api/tests/unit/controllers/v1/test_rules.py
Rule doesn't contain a pack attribute so the controller shouldn't inherit from ContentPackResourceController.
> Fix retrieving a rule by name

- CHANGELOG.rst
- docs/source/rules.rst
Related: https://github.com/StackStorm/st2/pull/1117
> Docs and changelog for exists/nexists operators

- contrib/examples/actions/workflows/mistral-basic.yaml
- contrib/examples/actions/workflows/mistral-handle-error.yaml
- contrib/examples/actions/workflows/mistral-handle-retry.yaml
- contrib/examples/actions/workflows/mistral-workbook-basic.yaml
- contrib/examples/actions/workflows/mistral-workbook-complex.yaml
- docs/source/mistral.rst
- docs/source/workflows.rst
Update documentation and examples for Mistral workflows.
> Update mistral documentation

- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/workflows/install.yaml
This is nice to have so that we can test our own separately and don't have to only commit to master.
Thanks
Daniel
> Allow for specifying the branch for packs.install

- st2actions/st2actions/runners/actionchainrunner.py
* don't see it being referenced in st2, st2web or st2client.js
> Drop mistral_execution_id from chain.

- st2common/packaging/debian/install
Misplaced linux pack on deb, fixing...
> Fix deb install package.

- st2api/st2api/controllers/root.py
- tools/st2_deploy.sh
> Fixes in st2_deploy

- docs/source/troubleshooting.rst
/var/logs/st2/logs/st2actionrunner.*.log -> /var/log/st2/logs/st2actionrunner.*.log
> Log path fix

- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
- st2tests/st2tests/fixtures/generic/actionchains/chain_broken_paths.json
- st2tests/st2tests/fixtures/generic/actionchains/no_default_chain_2.json
* Report failure in looking up next nodes
* Preserve order in default node lookup
> Action chain fixes

- docs/source/index.rst
- docs/source/webui.rst
Proof-reading and fact-checking is required. Also, any suggestions on formatting are welcome.
> [RFR] Add Web UI documentation

- st2api/st2api/controllers/v1/executionviews.py
- tools/launchdev.sh
> Avoid showing filters for workflow records

- contrib/examples/actions/workflows/mistral-repeat.yaml
- tools/upgrade-mistral-wf-0.8
This is an upgrade tool that parses 0.7 workflows and spits out 0.8 compatible workflows. This is for the users out there that we may not know about (HI! :wave:) that may be using Mistral, giving them a painless way to upgrade when the time comes.
> Mistral v0.8 Workflow Upgrade Tool

- CHANGELOG.rst
Add category for few missed changes.
> Minor edit to 0.8 change log

- st2actions/st2actions/runners/actionchainrunner.py
- st2actions/tests/unit/test_actionchain.py
* Fix exception error message
* Add some additional asserts which make sure we are testing the right case and that the tests return expected error message
> Action chain test improvements

- docs/source/conf.py
See #1210 against master for explanations.
> Fix docs versions, forever.

- tools/db_cleanup.sh
Simple command to just handle DB cleanup. Taken from `st2ctl` and `st2_express.sh`.
> adding tool to clean/setup dbs

- contrib/core/actions/stormbot_say/stormbot_say
For details see Jira issue #STORM-1171
> stormbot_say to handle the situation when required keys are missing

- Makefile
- tools/launchdev.sh
See: https://github.com/StackStorm/st2incubator/pull/81
> Changes needed for running automated mistral integ tests

- st2tests/integration/mistral/test_wiring.py
See: https://bugs.launchpad.net/nova/+bug/1084611
See: https://gist.github.com/lakshmi-kannan/b6edfff5b788fa7f2eff
> Skip mistral test_cpu_count

- CHANGELOG.rst
- st2common/st2common/exceptions/sensors.py
- st2reactor/st2reactor/cmd/sensormanager.py
- tools/st2ctl
See:
```
(virtualenv)~/st2 git:STORM-1153/sensor_container_messages ❯❯❯ virtualenv/bin/python ./st2reactor/bin/st2sensorcontainer --config-file conf/st2.conf
2015-03-19 17:06:45,091 INFO [-] Connecting to database "st2" @ "0.0.0.0:27017" as user "None".
2015-03-19 17:06:45,116 INFO [-] Registering exchanges...
2015-03-19 17:06:45,129 INFO [-] registered exchange st2.execution.
2015-03-19 17:06:45,130 INFO [-] registered exchange st2.liveaction.
2015-03-19 17:06:45,131 INFO [-] registered exchange st2.trigger.
2015-03-19 17:06:45,132 INFO [-] registered exchange st2.trigger_instances_dispatch.
2015-03-19 17:06:45,166 INFO [-] Found 0 sensors.
2015-03-19 17:06:45,166 ERROR [-] (PID:14606) SensorContainer quit due to exception.
File …
```
> RFR - More user friendly error messages when sensorcontainer quits

- CHANGELOG.rst
- conf/st2.dev.conf
- conf/st2.prod.conf
- st2common/st2common/util/api.py
- st2common/tests/unit/test_util_api.py
- st2debug/tests/integration/fixtures/configs/st2.conf
- st2reactor/st2reactor/container/process_container.py
- st2tests/conf/st2.conf
Same as #1284 but changes against master branch.
> [master] Fix api url used by sensors

- CHANGELOG.rst
- docs/source/packs.rst
- docs/source/reference/packs.rst
- docs/source/sensors.rst
- st2common/st2common/exceptions/sensors.py
- st2common/st2common/persistence/reactor.py
- st2common/st2common/services/sensor_watcher.py
- st2common/st2common/transport/reactor.py
- st2common/st2common/transport/utils.py
- st2common/tests/unit/test_sensor_watcher.py
- st2reactor/st2reactor/cmd/sensormanager.py
- st2reactor/st2reactor/container/manager.py
- st2reactor/st2reactor/container/process_container.py
- st2reactor/tests/unit/test_process_container.py
- tools/launchdev.sh
- tools/st2ctl
TODO:
[ ] - Refactor sensor_watcher and trigger_watcher https://github.com/StackStorm/st2/issues/1293 
(I promise to work on this next)
[X] - Tests 
[X] - Update docs
[X] - st2ctl fixes
[X] - Changelog
> RFR: Dynamically loading/unloading sensors

- tools/st2_deploy.sh
This PR creates a variable for the downloads server and sets it to the new public downloads server.
> Moved download server to variable and pointed to downloads server

- docs/source/start.rst
I corrected a few spelling mistakes during checking out the Quickstart tutorial.
> Correcting a few spelling mistakes.

- docs/source/mistral.rst
> RFR - Mistral docs: publish variables

- st2common/packaging/debian/postinst
Corrected site-packages path to point to /usr/lib/python2.7
> Removed local from path

- docs/source/start.rst
> Spelling mistake fix

- Makefile
- st2client/st2client/commands/datastore.py
This comes handy in a local development environment.
> Add Makefile target for cleaning the MonoDB and RabbitMQ instance

- CHANGELOG.rst
- contrib/packs/actions/workflows/install.yaml
- tools/st2ctl
> RFR: Fix packs install

- contrib/tests/actions/chains/test_quickstart.yaml
- contrib/tests/actions/chains/test_quickstart_key.yaml
- contrib/tests/actions/chains/test_quickstart_rules.yaml
- contrib/tests/actions/quickstart.meta.yaml
- contrib/tests/actions/test_quickstart_key.meta.yaml
- contrib/tests/actions/test_quickstart_rules.meta.yaml
This PR adds the st2 auth token as a parameter to be passed in to the quickstart workflows.
> Added auth token

- conf/st2.prod.conf
- tools/st2ctl
* Validated on a deployed system that this st2ctl actually works.
> update st2ctl and prod config to get st2notifier to run st2notifier

- st2api/st2api/controllers/v1/datastore.py
See https://github.com/StackStorm/st2/pull/1357
> Value in KVP should be string

- docs/source/conf.py
- docs/source/install/deb.rst
- docs/source/install/index.rst
- docs/source/install/rpm.rst
Pointing docs at downloads instead of ops.
> Updating download url in docs

- st2actions/st2actions/runners/fabricrunner.py
This was the root cause of the build failure.
> Fix a bug with the fabric runner code not checking for the new runner names

- contrib/core/actions/windows_cmd.yaml
- contrib/examples/actions/windows_uptime.json
- docs/source/install/windows_runners.rst
- st2actions/st2actions/bootstrap/runnersregistrar.py
* Get rid of the experimental concept, make windows runners non-experimental (they are registered by default now).
* Fix a bug in core windows actions.
> Windows runner changes

- docs/source/install/on_complete.rst
This pull request depends on pull request #1375
I am including auth_usage.rst, which provides description on how to use authentication
> added authentication-related explanation

- tools/st2_deploy.sh
> Install Window runner dependencies in st2_deploy

- st2client/setup.py
> Ignore comments in the st2client requirements file inside setup.py

- tools/self-check
```
root@st2stage201:/home/phool# ./self-check 
Attempting Test tests.test_packs_pack...ERROR!
Attempting Test tests.test_quickstart...OK!
Attempting Test tests.test_quickstart_key...OK!
Attempting Test tests.test_quickstart_rules...OK!
Attempting Example examples.mistral_examples...OK!
############################################################# 
###################################################   ####### 
###############################################   /~\   #####
############################################   _- `~~~', ####
##########################################  _-~       )  ####
#######################################  _-~          |  ####
####################################  _-~            ;  #####
##########################  __---___-~              |   ##### …
```
> Added examples to self-check

- tools/st2_deploy.sh
Also:
use DOWNLOAD_SERVER variable
> switch st2 apt repo to http

- st2common/packaging/debian/install
Add install of self-check script in debian catalog.
> add_self_check_deb

- st2client/tests/base.py
- st2client/tests/unit/test_auth.py
> Fix ST2_AUTH_TOKEN affecting unit tests

- docs/source/datastore.rst
> Fix docs for the "st2 key load" command

- tools/st2_bootstrap.sh
This PR adds the script that lives on the download servers for st2_deploy.sh deployments.
> Added st2_bootstrap

- instructables/chatops.md
Placing here for publishing link in a blog.
> Move chatops.md from blogs to public repo.

- docs/source/troubleshooting.rst
> Moving self-verification to this section

- st2client/st2client/models/access.py
- st2client/st2client/models/action.py
- st2client/st2client/models/reactor.py
This makes the whole repl st2client experience more pleasant.
> Add missing "_repr_attributes" class variable

- CHANGELOG.rst
- docs/source/auth_usage.rst
- st2auth/st2auth/controllers/access.py
- st2auth/tests/unit/test_token.py
- st2common/st2common/exceptions/access.py
- st2common/st2common/services/access.py
See https://github.com/StackStorm/st2/pull/1469
> RFR: TTL fixes ported to 0.9.1

- CHANGELOG.rst
- docs/source/install/deb.rst
- docs/source/install/rpm.rst
- docs/source/upgrade_notes.rst
- tools/st2_deploy.sh
* Add changelog section and update with changes
* Fix all docs to contain 0.9.1
* Change default version to 0.9.1 in st2_deploy.sh
> Bump up all straggling versions to 0.9.1

- CHANGELOG.rst
- contrib/packs/actions/download.yaml
- contrib/packs/actions/pack_mgmt/download.py
- docs/source/auth_usage.rst
- docs/source/install/deb.rst
- docs/source/install/rpm.rst
- docs/source/upgrade_notes.rst
- st2auth/st2auth/controllers/access.py
- st2auth/tests/unit/test_token.py
- st2client/st2client/__init__.py
- st2common/st2common/__init__.py
- st2common/st2common/exceptions/access.py
- st2common/st2common/models/utils/action_alias_utils.py
- st2common/st2common/services/access.py
- st2common/tests/unit/test_action_alias_utils.py
- tools/st2_deploy.sh
> Changes for v0.9.1 release

- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actions.py
- st2api/st2api/controllers/v1/actionviews.py
- st2api/st2api/controllers/v1/policies.py
- st2api/st2api/controllers/v1/root.py
- st2api/st2api/controllers/v1/sensors.py
- st2api/st2api/controllers/v1/triggers.py
- st2api/tests/unit/controllers/v1/test_policies.py
- st2client/st2client/client.py
- st2client/st2client/commands/policy.py
- st2client/st2client/models/policy.py
- st2client/st2client/shell.py
- st2client/tests/unit/test_shell.py
- st2common/st2common/models/api/policy.py
- st2common/st2common/models/db/policy.py
- st2common/st2common/models/system/common.py
- st2common/st2common/persistence/policy.py
- st2common/tests/unit/test_db_policy.py
- st2tests/st2tests/base.py
- st2tests/st2tests/fixtures/generic/policies/policy_1.yaml
- st2tests/st2tests/fixtures/generic/policies/policy_2.yaml
- st2tests/st2tests/fixtures/generic/policytypes/policy_type_1.yaml
- st2tests/st2tests/fixtures/generic/policytypes/policy_type_2.yaml
- st2tests/st2tests/fixturesloader.py
Add appropriate DB, persistence, and API models, REST controllers, and CLI operations for PolicyType and Policy.
> Add PolicyType and Policy models

- st2reactor/st2reactor/sensor/base.py
Methods are: add_trigger, update_trigger, remove_trigger
> Added basic comments into 3 methods

- docs/source/actionchain.rst
- docs/source/workflows.rst
> Document how to pass data between action-chain workflows

- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/content/aliasesregistrar.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/st2reactor/bootstrap/sensorsregistrar.py
- tools/diff-db-disk.py
#mergefail. See https://github.com/StackStorm/st2/pull/1501
> Diff tool to show diff between what's on disk vs what's in db content wise.

- contrib/tests/actions/chains/test_quickstart_rules.yaml
```
lakshmi@st2stage201:~$ st2 execution re-run 555db682ce36d20fe1748ded
.......
id: 555dfc52ce36d20fe1748df3
action.ref: tests.test_quickstart_rules
start_timestamp: 2015-05-21T15:40:02.424644Z
end_timestamp: 2015-05-21T15:40:16.109322Z
+--------------------------+-----------+----------------------+------------+----------------------+
| id                       | status    | task                 | action     | start_timestamp      |
+--------------------------+-----------+----------------------+------------+----------------------+
| 555dfc52ce36d20fddc402c5 | succeeded | setup_sample_rule_wi | core.local | Thu, 21 May 2015     |
|                          |           | th_webhook_exists    |            | 15:40:02 UTC         |
| 555dfc53ce36d20fddc402c7 | succeeded | …
```
> E2E tests - test_quickstart_rule - Rules now belong in a pack

- tools/st2-self-check
Resolving errors:
Attempting Test tests.test_packs_pac...ERROR!
Attempting Test k...ERROR!
Attempting Test tests.test_quickstar...ERROR!
Attempting Test t...ERROR!
Attempting Test tests.test_quickstar...ERROR!
Attempting Test t_key...ERROR!
Attempting Test tests.test_quickstar...ERROR!
Attempting Test t_rules...ERROR!
> Added width to action list - it is failing due to narrow field otherwise

- st2reactor/st2reactor/container/utils.py
- st2reactor/st2reactor/rules/engine.py
- st2reactor/st2reactor/rules/worker.py
* Add a global try-except
* some cosmetic changes and comment to explain behavior.
> Rules engine resiliency

- docs/source/overview.rst
Took another pass based on feedback from IRC.
> Clarification around Sensors in Overview

- docs/source/install/docker.rst
This PR includes documentation updates to take advantage of newly published docker containers.
> Update docker instructions

- tools/st2-setup-tests
Switching the tests installer script to use the new st2tests repo.  Also made the pack name a command line arg.
> Switch st2-setup-tests to use new st2tests repo

- st2actions/st2actions/notifier.py
- st2actions/st2actions/scheduler.py
Use a background scheduler instead of blocking scheduler so it yields to the notifier to do work.
> Use background scheduler in the notifier

- CHANGELOG.rst
- tools/st2_bootstrap.sh
- tools/st2_deploy.sh
> Bump straggling versions

- contrib/packs/actions/download.yaml
- contrib/packs/actions/info.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/pack_mgmt/info.py
- contrib/packs/aliases/pack_deploy.yaml
- contrib/packs/aliases/pack_info.yaml
- st2api/st2api/controllers/exp/aliasexecution.py
- st2api/tests/unit/controllers/exp/test_alias_execution.py
- st2common/st2common/models/utils/action_param_utils.py
- st2tests/st2tests/fixtures/aliases/actions/action1.yaml
- st2tests/st2tests/fixtures/aliases/aliases/alias2.yaml
Making sure https://github.com/StackStorm/st2/pull/1570 ends up on master
> Pack deployment chatops

- contrib/packs/actions/workflows/install.yaml
- tools/st2ctl
* Aliases are registered by default. Aliases are passive and harmless if enabled by default.
> Reload aliases by default

- contrib/packs/actions/pack_mgmt/download.py
* use boolean rather than regex to fix bug
> Fix bug in packs.download

- contrib/packs/actions/pack_mgmt/delete.py
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/pack_mgmt/info.py
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- contrib/packs/actions/pack_mgmt/unload.py
- contrib/packs/actions/pack_mgmt/virtualenv_setup_prerun.py
* Shallow clone the repo
* Rename class and refactor to make linter happy
* Add config headers
> `Packs` pack cleanup

- conf/st2.dev.conf
- docs/source/conf.py
- docs/source/install/config.rst
* skip versions ending with 0 as our CI/CD don't grok them yet.
> Fix docs version selector

- tools/st2_deploy.sh
Appeasing the benevolent dictator
> switch pip install to easy_install

- st2client/st2client/commands/action_alias.py
* `list` -  fixed it and now works
* `get` - added attribute display order
> Some fixes to the st2 action-alias * commands

- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/st2reactor/sensor/base.py
- st2reactor/tests/resources/test_sensor.py
- st2reactor/tests/unit/test_sensor_wrapper.py
Re-create PR https://github.com/StackStorm/st2/pull/1617 for 0.11.2
> Fix subclass check 112

- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/st2reactor/sensor/base.py
- st2reactor/tests/resources/test_sensor.py
- st2reactor/tests/unit/test_sensor_wrapper.py
* isinstance is obviously the wrong check in this case since we are comparing
types therefore using issubclass.
> Use issubclass instead of isinstance check

- contrib/packs/actions/install.meta.yaml
- contrib/packs/actions/workflows/install.yaml
> Allow user to pass "subtree" parameter to packs.install action

- contrib/examples/actions/windows_uptime.json
- contrib/examples/actions/windows_uptime.yaml
seems the only object that uses json
> Converted windows_uptime.json to windows_uptime.yaml

- docs/source/actions.rst
> Added CloudSlang to runners list

- tools/visualize_action_chain.py
* Traverse the on-failure path just like the on-success path
* Keep track of processed node to avoid loops
A workflow like - 
```
---
vars:
slack_fail_channel: "#stackstorm"
slack_ok_channel: "#thunderdome"
test_lock_name: "chatops.lock"
chain:
-
name: "get_lock"
ref: "core.local"
params:
cmd: "st2 key get key=\"chatops.lock\" | grep value"
on-failure: "set_lock"
notify:
on-success:
message: "[CHATOPS_ITESTS]\n STATUS: LOCK_EXISTS."
channels: ["slack_thunderdome"]
-
name: "set_lock"
ref: "core.local"
params:
cmd: "st2 key set key=\"{{test_lock_name}}\" value=\"1\""
on-success: "get_build_server"
on-failure: "slack_lock_acquire_failure"
notify:
on-failure:
message: "[CHATOPS_ITESTS]\n STATUS: Failed to acquire lock."
channels: ["slack_thunderdome"]
-
name: "slack_lock_failure"
ref: …
```
> The on-failure path is now traversed during visualization

- conf/st2.conf.sample
- conf/st2.dev.conf
- conf/st2.prod.conf
- st2debug/tests/integration/fixtures/configs/st2.conf
- st2reactor/st2reactor/sensor/config.py
- st2tests/conf/st2.conf
- tools/config_gen.py
* Remove unused config
* Fix all st2.conf files
* Update st2.conf.sample
> Sensor config cleanup

- .travis.yml
- Makefile
- test-requirements.txt
HTML coverage reports will be available in $repo_root/cover/*.html
XML coverage report will be in $repo_root/coverage.xml
> RFR: Coverage reports html

- docs/source/runners.rst
Most importantly exit code -9 - which unless you know that it's a TIMEOUT_EXIT_CODE = -9 constant defined for runners, is very mysterious exit code.
> Added short explanation of exit codes.

- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
This pull request also allows user to retrieve pack by a name (name is a pack PK).
In addition to that, I've made some related refactoring on the base `ResourceController`.
> Allow user to also retrieve pack by name

- st2actions/st2actions/bootstrap/actionsregistrar.py
- st2actions/st2actions/runners/actionchainrunner.py
- st2common/st2common/content/aliasesregistrar.py
- st2common/st2common/content/loader.py
- st2common/st2common/content/policiesregistrar.py
- st2common/st2common/transport/reactor.py
- st2debug/st2debug/cmd/submit_debug_info.py
- st2debug/st2debug/processors.py
- st2reactor/st2reactor/bootstrap/rulesregistrar.py
- st2reactor/st2reactor/bootstrap/sensorsregistrar.py
* Cleans up some informational errors in scrutinizer
> Fix assert coding style

- st2actions/st2actions/container/base.py
- st2actions/st2actions/runners/mistral/utils.py
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/triggers.py
- st2common/st2common/models/api/action.py
- st2common/st2common/util/config_parser.py
- st2reactor/st2reactor/cmd/rulesengine.py
* Extra paranthesis removed and indents fixed
> Cleanup coding style

- CHANGELOG.rst
- st2actions/st2actions/container/base.py
- st2actions/st2actions/worker.py
- st2actions/tests/unit/test_runner_container.py
- st2actions/tests/unit/test_worker.py
See: https://github.com/StackStorm/st2/pull/1767
> RFR: Port fix for issue_1717 to 0.12.1

- docs/source/install/docker.rst
Fix syntax
Add note about using the PATH variable in supervisor configuration files.
> Note on setting PATH with supervisord

- CHANGELOG.rst
- docs/source/install/config.rst
- st2actions/st2actions/config.py
- st2actions/st2actions/runners/fabric_runner.py
- st2tests/st2tests/config.py
Merging https://github.com/StackStorm/st2/pull/1793 on v0.12.2
> Ssh config v0.12

- CHANGELOG.rst
Hygiene and so that http://docs.stackstorm.com/changelog.html is updated.
> Update Changelog with updates from patch releases.

- CHANGELOG.rst
- requirements.txt
- st2auth/st2auth/backends/flat_file.py
Porting over https://github.com/StackStorm/st2/pull/1800
> Auth backend port + tooz

- CHANGELOG.rst
- st2actions/st2actions/container/base.py
- st2actions/st2actions/runners/mistral/utils.py
- st2actions/tests/unit/test_mistral_dsl_transform.py
- st2actions/tests/unit/test_mistral_v2.py
- st2actions/tests/unit/test_runner_container.py
- st2client/st2client/commands/action.py
- st2common/st2common/models/utils/action_param_utils.py
- st2common/tests/unit/test_action_param_utils.py
- st2tests/st2tests/fixtures/generic/actions/local.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_has_unexpected_param.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_missing_required_param.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_post_xform.yaml
- st2tests/st2tests/fixtures/generic/workflows/wf_pre_xform.yaml
Throw exception if required parameters are not given and if unexpected parameters are present.
> Validate action parameters in tasks of Mistral WF

- st2actions/st2actions/runners/ssh/paramiko_ssh.py
> RFR: oslo_config is the right import

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_auth.py
- st2auth/st2auth/controllers/auth.py
- st2common/st2common/hooks.py
- st2common/st2common/middleware/auth.py
> Return correct content type on an error inside the auth hook

- Makefile
- contrib/linux/actions/checks/check_loadavg.py
- contrib/linux/actions/checks/check_processes.py
- contrib/linux/actions/service.py
> Run lint on Python actions inside the linux pack, fix existing violations

- CHANGELOG.rst
- docs/source/actions.rst
- st2client/st2client/commands/action.py
Examples:
https://gist.github.com/lakshmi-kannan/43ad4fec2cc12918571c
> RFR: Add trace_tag support to st2 run

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions_simple.py
- st2client/st2client/commands/action.py
- st2common/st2common/exceptions/api.py
- st2common/st2common/exceptions/trace.py
- st2common/st2common/models/db/trace.py
- st2common/st2common/services/action.py
- st2common/tests/unit/services/test_trace_injection_action_services.py
- st2tests/st2tests/fixtures/traces/actions/chain1.yaml
- st2tests/st2tests/fixtures/traces/executions/traceable_execution.yaml
- st2tests/st2tests/fixtures/traces/liveactions/traceable_liveaction.yaml
- st2tests/st2tests/fixtures/traces/runners/actionchain.yaml
```
(virtualenv)/m/s/s/st2 git:support_trace_id_in_cli_run ❯❯❯ st2 run core.local date --trace-id='55d4c36f32ed3554acf2db4'
MESSAGE: Unable to find Trace with id="55d4c36f32ed3554acf2db4"
(virtualenv)/m/s/s/st2 git:support_trace_id_in_cli_run ❯❯❯
(virtualenv)/m/s/s/st2 git:master ❯❯❯ st2 run core.local cmd=date --trace-tag="OohLaLaLa"                            ⏎ ✭ ✱ ◼
.
id: 55d3d5bf32ed3530544a753d
result:
{
"stderr": "",
"succeeded": true,
"stdout": "Tue Aug 18 18:02:55 PDT 2015
"
}
(virtualenv)/m/s/s/st2 git:master ❯❯❯ st2 trace list --trace-tag OohLaLaLa                                             ✭ ✱ ◼
+-------------------+-------------------------------------------------------+
| Property …
```
> RFR: Support trace_id in CLI run

- CHANGELOG.rst
- contrib/examples/sensors/sample_polling_sensor.py
- contrib/examples/sensors/sample_sensor.py
- docs/source/index.rst
- docs/source/sensors.rst
- docs/source/traces.rst
* Updated docs
* Updated sensor sample
* Updated changelog
> Trace docs

- docs/source/troubleshooting.rst
Preview: 
https://www.evernote.com/l/ANFWbxZ_k_BH3p5NXiEFBIJFJHC5XESCHCsB/image.png
> RFR: Add info about support in docs

- st2actions/st2actions/notifier/notifier.py
- st2api/st2api/controllers/v1/webhooks.py
- st2api/tests/unit/controllers/v1/test_webhooks.py
- st2reactor/st2reactor/timer/base.py
- st2reactor/tests/unit/test_timer.py
* trace support for webhook, timer and notify triggers
> RFR: Trace other trigger

- CHANGELOG.rst
- st2common/st2common/models/system/action.py
- st2common/st2common/util/action_db.py
- st2common/tests/unit/test_action_db_utils.py
- st2common/tests/unit/test_paramiko_script_action_model.py
- st2common/tests/unit/test_shell_action_system_model.py
st2tests PR: https://github.com/StackStorm/st2tests/pull/26
> Postional arguments need to be quoted

- docs/source/conf.py
- docs/source/sensors.rst
* This will check for broken cross-references and fail sphinx if one found.
> Docs auto-check broken cross-references.

- st2api/st2api/controllers/v1/packviews.py
I'll need this for the icons and overall makes sense.
> Returning 404 rather than failing on a non-existent file

- st2client/st2client/shell.py
> Print a better error message if we are unable to read / write auth token from / to the cache

- tools/launchdev.sh
Related: https://github.com/StackStorm/st2/pull/1714
> Clean log dir if it exists

- tools/st2_deploy.sh
The released version requirements.txt differs from master now therefore the download is also versioned.
> Pull requirements.txt from specific release

- tools/st2_deploy.sh
CP changes from https://github.com/StackStorm/st2/pull/1880 to v0.13.1
> Use versioned requirements

- requirements.txt
- st2common/st2common/constants/types.py
- st2common/st2common/models/db/trigger.py
- st2common/st2common/util/bencode.py
- st2common/tests/unit/test_db_model_uids.py
This pull request fixes `get_uid` method on the `TriggerDB` model (previously wrong resource type constant was used and parameters weren't included in the UID).
In addition to that it adds some tests for get_uid methods.
> UID fixes and tests

- docs/source/install/all_in_one.rst
Love it.  Minor nit ... Prequisites:  When I first read this it sounded like I needed a physical server which of course is not the case due to the prepackaged options....  I suggest we add something mentioning that we have at least a VMDK and AMI option now as well here..
This PR imports the https://github.com/StackStorm/st2/pull/1887 to next release.
> Update all_in_one.rst in v0.13.1 branch

- st2reactor/st2reactor/timer/base.py
- st2reactor/tests/unit/test_timer.py
* Trigger in timer trigger is a dict so access properties as a dict.
* Update tests to reflect the internals
> Fix timer trigger regression

- tools/st2_deploy.sh
Not sure if there is a better way to do update the branch or if this is even required.
> Update mistral branch

- tools/st2-analyze-links.py
Can generate an ugly image like -
> Linkanalyzer

- contrib/examples/actions/chains/mistral_examples.yaml
(cherry picked from commit 1cdb4f267c91821fae2df83ffc6186988b602701)
> Remove a Mistral example that is causing deadlock in DB

- st2tests/integration/mistral/test_examples.py
(cherry picked from commit 90a4c6258dc5530121be9c0c2c956cb361e3937d)
> newlines are now stripped.

- tools/st2_deploy.sh
The first quick&dirty st2_deploy.sh fix to make it work smoothly on RHEL6-family linux distros. Tested on RHEL6.4+ and CentOS 7. Worked like a charm for me. Feel free to review and refactor if you feel the need.
> St2 deploy script with RHEL6 support using IUS repository for python27

- tools/st2-setup-examples
- tools/st2-setup-tests
The test setup script was using the system python to create the virtualenv.  this explicitly uses python2.7.
> Virtualenv2.7

- st2api/st2api/wsgi.py
Copied from st2auth and modified. Works in st2express.
> wsgify st2api

- CHANGELOG.rst
- st2client/st2client/commands/action_alias.py
> Allow action-alias delete and create from CLI

- st2auth/st2auth/backends/__init__.py
As talked on https://github.com/StackStorm/st2/pull/1984
> Add keystone to the BACKEND_MODULES, Fixes #1983

- st2actions/Makefile
- st2api/Makefile
- st2auth/Makefile
- st2client/Makefile
- st2common/Makefile
- st2debug/Makefile
- st2exporter/Makefile
- st2reactor/Makefile
minor fix of the release of debian packages
> st2 packaging: release fix in version string

- st2common/packaging/debian/postinst
- st2common/packaging/rpm/st2common-rhel6.spec
- st2common/packaging/rpm/st2common.spec
* Last change was obvious in a hurry
> Skip chmod of examples

- st2client/st2client/config_parser.py
- st2client/st2client/shell.py
- st2client/tests/unit/test_config_parser.py
> Add "silence_ssl_warnings" CLI config option

- st2common/st2common/rbac/decorators.py
- st2common/st2common/rbac/utils.py
- st2common/tests/unit/test_rbac_utils.py
* Add new methods for checking is a user is system administrator
* Update "is_admin" methods to also account for system admin role (system_admin rule is a superset of admin role)
> RBAC fixes and improvements

- tools/st2_deploy.sh
This just adds scientific linux to the list of DISTRO_NAME so the right packages get installed
> adding scientific linux support to st2_deploy script. This just adds SL to the list of DISTRO_NAME so the right packages are installed

- docs/source/_themes/sphinx_rtd_theme/layout.html
This PR adds tracking analytics to the `docs.stackstorm.com` site.
/cc @epowell101
> Add AC tracking changes

- CHANGELOG.rst
- st2actions/st2actions/runners/remote_command_runner.py
- st2actions/st2actions/runners/remote_script_runner.py
- st2actions/st2actions/runners/ssh/parallel_ssh.py
- st2actions/tests/unit/test_paramiko_remote_script_runner.py
- st2common/st2common/bootstrap/runnersregistrar.py
- st2common/st2common/models/system/action.py
- st2common/st2common/models/system/paramiko_command_action.py
- st2common/st2common/models/system/paramiko_script_action.py
- st2common/tests/unit/test_paramiko_command_action_model.py
- st2common/tests/unit/test_paramiko_script_action_model.py
Spent several hours on this and tested various cases. Seems to work now. But would appreciate more eyes and testing.  cc: @manasdk , @Kami
> RFR: Env variables support paramiko

- instructables/configuring_rbac.rst
This is tutorial style docs as opposed to a reference which is already present http://docs.stackstorm.com/latest/rbac.html
> RBAC Tutorial

- fixed-requirements.txt
- requirements.txt
Adds SSL support and removes annoying insecure platform warnings.
> Include security options in Requests library

- requirements.txt
> Revert "Include security options in Requests library"

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/config.yaml
* use chgrp to switch pack ownership to configure pack_owner group
* config to allow specification of pack owner group
> Pack permissions

- docs/source/install/puppet.rst
This PR updates the list of supported operating systems for the Puppet module.
> Update supported OSes for Puppet Module

- Makefile
- conf/st2.conf.sample
- docs/source/config/windows_runners.rst
- tools/config_gen.py
- tools/log_watcher.py
- tools/purge_executions.py
- tools/st2-analyze-links.py
- tools/st2-inject-trigger-instances.py
In the sample config change we now group options in the "common" and "standalone" group so it's more clear which options apply when (wsgi vs standalone mode).
> Update Windows runner docs, update sample config

- contrib/hello-st2/actions/greet.yaml
- contrib/hello-st2/aliases/alias1.yaml
- contrib/hello-st2/policies/policy1.yaml
- contrib/hello-st2/rules/rule1.yaml
- docs/source/reference/packs.rst
Add in references to policies and action alias
> Pack contrib docs

- docs/source/install/vagrant.rst
> syntax fixes for Vagrant docs

- tools/st2-setup-tests
> RFR - Add ability to specify branch for st2tests

- st2actions/bin/runners.sh
@Kami you are too fast to merge.
I'm to fix :)
> fix for runners.sh

- st2client/st2client/formatters/table.py
Fixes some regressions introduced when adding "elapsed" feature.
> [CLI] Table improvements

- st2actions/tests/unit/test_notifier.py
- st2common/st2common/models/db/action.py
- st2common/st2common/models/db/execution.py
- st2common/st2common/models/db/liveaction.py
> Escape action parameters before saving to db

- contrib/examples/rules/notify_slack.yaml
- contrib/examples/rules/sample_rule_with_actiontrigger.yaml
- contrib/examples/rules/sample_rule_with_timer.yaml
- contrib/examples/rules/sample_rule_with_webhook.yaml
- docs/source/chatops/notifications.rst
- docs/source/rules.rst
- docs/source/start.rst
This way st2tests will pass with v1.1.1.
> Cherry pick samples renaming changes

- st2common/st2common/transport/connection_retry_wrapper.py
This way we should also get the traceback back.
> Use log.exception inside rabbit retry code

- st2actions/st2actions/query/mistral/v2.py
- st2actions/tests/unit/test_mistral_querier_v2.py
- st2common/st2common/util/workflow/mistral.py
Minor code refactoring and unit tests added.
> Minor fix to retry in mistral querier

- st2api/st2api/controllers/v1/aliasexecution.py
As previously discussed with the extended schema.
> Support "representation+value" objects in format strings

- docs/source/install/all_in_one.rst
> fixed a minor typo

- pylint_plugins/api_models.py
- st2actions/st2actions/runners/ssh/paramiko_ssh_runner.py
Cherry picked good / non-breaking changes from #2249.
> Pylint improvements

- CHANGELOG.rst
- contrib/core/actions/noop.yaml
- st2actions/st2actions/runners/nooprunner.py
- st2actions/tests/integration/test_nooprunner.py
- st2common/st2common/bootstrap/runnersregistrar.py
- st2tests/st2tests/fixtures/generic/actions/noop.yaml
This PR introduces a runner that does *absolutely nothing*. Yup!
I need this as a stub and placeholder when all I need to do is send a notification, but it's inappropriate to do in the context of the task I am currently in.
:eyes: and other critiques are most certainly appreciated.
> No-Op runner

- CHANGELOG.rst
- st2client/st2client/commands/rule.py
```
$ st2 rule list
+------------------------------+---------+-------------+---------+
| ref                          | pack    | description | enabled |
+------------------------------+---------+-------------+---------+
| default.passive_trigger_rule | default | jdlksdj     | True    |
+------------------------------+---------+-------------+---------+
```
```
$ st2 rule list
+------------------------------+--------------------------------+------------+---------+
| ref                          | trigger.ref                    | action.ref | enabled |
+------------------------------+--------------------------------+------------+---------+
| default.passive_trigger_rule | fixtures.test_passive_trigger. | core.local | True    |
|                              | dummy …
```
> Rework rule list columns

- CHANGELOG.rst
- st2api/st2api/controllers/v1/rules.py
- st2client/st2client/commands/rule.py
- st2client/tests/unit/test_auth.py
- st2client/tests/unit/test_ssl.py
- st2common/st2common/models/db/rule.py
Action and trigger filters for rule list
```
st2 rule list --trigger=<trigger_type_ref>
```
```
st2 rule list --action=<action_ref>
```
> Rule filters

- st2client/st2client/commands/rule.py
If trigger and action are desired in rule display use `st2 rule list --iftt`
> Provide an iftt switch for rule list display

- st2common/st2common/bootstrap/actionsregistrar.py
- st2common/st2common/bootstrap/aliasesregistrar.py
- st2common/st2common/bootstrap/policiesregistrar.py
- st2common/st2common/bootstrap/rulesregistrar.py
- st2common/st2common/bootstrap/sensorsregistrar.py
Fixes regression reported in https://github.com/StackStorm/st2/pull/2291#issuecomment-164944170
> Ignore missing type directories

- st2client/setup.py
> Update st2client description and classifiers

- docs/source/actions.rst
not sure of the destination you had in mind
> looks like md syntax snuck its way in

- fixed-requirements.txt
- st2actions/in-requirements.txt
trying to fix virtualenv dependency https://github.com/StackStorm/st2-packages/issues/50
> added virtualenv dependency

- docs/source/actions.rst
- st2common/st2common/util/schema/__init__.py
Add enum to the list of overridable attributes and update documentation.
> Fix runner param override

- CHANGELOG.rst
- st2actions/st2actions/query/mistral/v2.py
- st2actions/tests/unit/test_mistral_querier_v2.py
> Fix runaway action triggers caused by workflow state miscalculation

- st2api/in-requirements.txt
- st2auth/in-requirements.txt
Reverts StackStorm/st2#2390
Sudden dependency issues
> Revert "Add gunicorn and uwsgi as requirements"

- st2reactor/conf/syslog.garbagecollector.conf
> Add missing syslog logging config for st2garbagecollector service

- CHANGELOG.rst
- st2actions/st2actions/container/base.py
- st2actions/st2actions/runners/mistral/v2.py
- st2actions/tests/unit/test_mistral_v2_rerun.py
I noticed some "issues" while reviewing other PRs so I decided  to address those.
1. Refactor the code a bit to make it easier to read and follow
2. Make sure temporary action-specific token is also deleted when user cancels an action (previously token was only deleted if action succeeded / failed / timed out and wasn't canceled)
> Runner container improvements and fixes

- st2common/bin/st2ctl
Small fix missed in https://github.com/StackStorm/st2/pull/2385
> Fix for new st2ctl restart-component

- Makefile
- fixed-requirements.txt
- requirements.txt
This is st2 part of https://github.com/StackStorm/st2workroom/pull/318 change.
> Make sure we specify min pip version

- st2client/setup.py
This is a backport of #2423 for 1.3.1.
> st2client dist_utils fix backport for v1.3.1

- tools/st2-self-check
* inclusion of parameters in the output shifted the status field lower
> Look at first 20 lines

- tools/st2-self-check
Picking up the self-check-script change inorder to respin.
> v1.3 self check update

- st2auth/in-requirements.txt
See https://stackstorm.slack.com/archives/packages/p1453781176000182
> Add bcrypt dependency to st2auth

- tools/st2-self-check
(cherry picked from commit b65a0c7ee9ca8f923633a0efbdfcf32c08b228ec)
> Fix grep clauses and also avoid noise

- st2common/bin/st2ctl
Answering https://github.com/StackStorm/st2-packages/issues/134 - that's what I mean.
> 1.3.1 fix: Run some st2ctl commands without sudo

- st2common/bin/st2ctl
Cherry-picking https://github.com/StackStorm/st2/pull/2445 to master.
> Run some st2ctl commands without sudo

- tools/launchdev.sh
__Updates__
* If *use_gunicorn* is True then kill the associated st2api and st2auth processes
* Fix typos
> Stop gunicorn processes in st2stop()

- conf/nginx/st2.conf
as discussed and decided here https://stackstorm.slack.com/archives/stackstorm/p1454528615004799
> Add nginx configuration

- st2common/bin/st2ctl
still want to keep them visible.
> Fix components list in st2ctl

- conf/st2.package.conf
** I'll merge the changes to 1.3 branch as well. **
Disable auth by default.
See https://github.com/StackStorm/st2docs/pull/36#discussion_r51930668
> Disable auth by default in packages

- conf/nginx/st2.conf
Cherry pick https://github.com/StackStorm/st2/pull/2468
> Ngnix rule for mistral_api redirect

- conf/nginx/st2.conf
> Revert "Ngnix rule for mistral_api redirect"

- circle.yml
(cherry picked from commit 498ff0c)
See: https://github.com/StackStorm/st2/pull/2453
> Synchronize circle.yml with st2 CI process/versioning for v1.3.2

- st2api/st2api/controllers/v1/webhooks.py
replaced lines 84-90 with 84-93 - this enables external webhooks to POST the request body as either application/json or regular web-form-style querystring encoded fields. I'm using this on a number of client servers for the last month and it works fine.
> Update webhooks.py to enable form POSTs

- st2actions/setup.py
don't merge this please, it requires to be insync with packages.
> remove runners.sh from st2actions setup.py

- circle.yml
(cherry picked from commit 1b63111)
See: https://github.com/StackStorm/st2/pull/2483
> Fix CircleCI Bintray parallel uploads (1.3.2)

- circle.yml
Experimental deployments to PackageCloud
Part of experiment from `st2-packages` https://github.com/StackStorm/st2-packages/pull/140 to deploy to both Bintray and PackageCloud and see how it works, pros/cons/compare.
> Experimental Deployments to PackageCloud

- conf/nginx/st2.conf
- conf/st2.package.conf
- requirements.txt
- st2actions/in-requirements.txt
- st2common/bin/st2ctl
v1.3.2 was created before we started making changes to v1.3.
> v1.3.2 update v1.3

- st2common/bin/st2ctl
Cherry picked from https://github.com/StackStorm/st2/pull/2490
> Various improvements for new st2ctl (1.3.2)

- circle.yml
Experimental deployments to PackageCloud https://github.com/StackStorm/st2/pull/2493
(cherry picked from commit 663a94d)
> Include packagecloud deployments (1.3.2)

- pylint_plugins/api_models.py
- st2actions/st2actions/runners/__init__.py
Cherry picked some improvements from #2249.
Some bugs still haven't been fixed in the latest version of pylint and astroid so we still can't upgrade.
> Lint improvements

- st2common/bin/st2-run-pack-tests
Needed for https://github.com/StackStorm/st2contrib/pull/396
> Add etc folder to pack python path for testing handlers

- circle.yml
Remove Bintray deployments in favor of PackageCloud
> Remove Bintray deployments (master)

- circle.yml
(cherry picked from commit 9c2cb7e)
> Remove Bintray deployments (v1.3.3)

- circle.yml
> Part of StackStorm/st2-packages#227
Cherry pick of https://github.com/StackStorm/st2/pull/2569 for `v1.3.3`
> Add support for st2-packages branching (v1.3.3)

- st2common/tests/unit/test_virtualenvs.py
- st2tests/st2tests/fixtures/dummy_pack_2/requirements.txt
Some basics tests for pack virtualenv creations.
> Tests for pack virtualenv creation

- st2common/st2common/operators.py
- st2common/tests/unit/test_operators.py
Addresses issue https://github.com/StackStorm/st2/issues/2557
> Add imatchregex, searchregex, and isearchregex operators.

- lint-configs/python/.pylintrc
- st2api/st2api/controllers/base.py
- st2api/st2api/controllers/v1/webhooks.py
- st2client/st2client/utils/date.py
- st2common/st2common/models/api/policy.py
- st2common/st2common/models/db/action.py
- st2common/st2common/models/db/trigger.py
- st2common/st2common/models/system/action.py
- st2common/st2common/services/sensor_watcher.py
- st2common/st2common/services/triggerwatcher.py
- st2common/st2common/util/date.py
- st2reactor/st2reactor/container/partitioners.py
- test-requirements.txt
This pull request builds on top #2249.
Sadly there are still quite some false positives which needed to be disabled.
> Upgrade pylint to v1.5.5

- CHANGELOG.rst
Add LDAP backend and mistral changes to the log.
> Update change log

- st2common/bin/st2ctl
cherry pick of https://github.com/StackStorm/st2/pull/2625
> Cherry pick stctl changes

- st2common/bin/st2ctl
st2actionrunners aren't starting on el6 with the service manager check
> Remove service check

- contrib/chatops/actions/workflows/post_result.yaml
> Fix for publishing `extra` in post_message

- CHANGELOG.rst
- contrib/packs/actions/pack_mgmt/unload.py
- st2auth/st2auth/wsgi.py
- st2common/st2common/config.py
- st2common/st2common/models/db/__init__.py
- st2common/st2common/persistence/db_init.py
- st2common/st2common/service_setup.py
- st2reactor/st2reactor/cmd/trigger_re_fire.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- tools/diff-db-disk.py
- tools/migrate_rules_to_include_pack.py
* Expose all parameters for SSL/TLS support with mongodb
> SSL support for mongodb connections

- contrib/chatops/actions/workflows/post_result.yaml
Update 1.4 packages with the chatops workflow fix (see https://github.com/StackStorm/st2/pull/2642)
> Fix the post_result workflow with extra

- st2client/st2client/shell.py
Fixed a couple of minor typos in help strings. No code functionality changes
> Fixed typos in help strings in shell.py

- dev_docs/Troubleshooting_Guide.rst
Changes:
+ Created folder dev_docs
+ Add Troubleshooting_Guide.rst in Q&A format
> Troubleshooting doc for st2 dev

- contrib/packs/actions/workflows/deploy.yaml
This PR cherry-picks fixes from #2661 into v1.4 branch.
Reported by @jjm
> Cherry pick deploy workflow fixes

- st2api/st2api/controllers/base.py
- st2api/st2api/controllers/controller_transforms.py
- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/rbac.py
- st2api/st2api/controllers/v1/rules.py
- st2api/tests/unit/controllers/v1/test_rules.py
- st2client/st2client/commands/rule.py
```
$ st2 rule list
+----------------------------------------+----------+----------------------------------------+---------+
| ref                                    | pack     | description                            | enabled |
+----------------------------------------+----------+----------------------------------------+---------+
| examples.notify_slack                  | examples | Sample rule firing on action           | True    |
|                                        |          | completion.                            |         |
| examples.sample_rule_with_actiontrigge | examples | Sample rule firing on action           | True    |
| r                                      |          | completion.                            |         |
| examples.sample_rule_with_timer        | …
```
> support rules filtering by enabled/disabled

- CHANGELOG.rst
- st2common/bin/st2ctl
- st2common/st2common/bootstrap/sensorsregistrar.py
- st2common/st2common/bootstrap/triggersregistrar.py
- st2common/st2common/content/bootstrap.py
- tools/st2ctl
Follow-up PR for StackStorm/st2#2682.
This is entirely untested... but it sure looks thorough!
I don't have a StackStorm dev environment setup yet. 😢  What's the latest suggestion with [st2workroom/st2dev](https://docs.stackstorm.com/development/index.html#setting-up-a-development-environment) in a [native packaged](https://docs.stackstorm.com/install/deb.html) world? What's the team using nowadays? Or is this still valid?
> Add "--register-triggers" option to register content script and st2ctl

- contrib/default/actions/workflows/README.md
Folder is needed to make flow happy
> add workflows folder

- st2api/st2api/controllers/resource.py
- st2api/tests/unit/controllers/v1/test_executions_filters.py
Cherrypick https://github.com/StackStorm/st2/pull/2761
> [v1.5] Fix execution list

- st2actions/st2actions/cmd/actionrunner.py
Fixes https://github.com/StackStorm/st2/issues/2746.
> monkey patch actionrunner earlier to fix ssh proxycommand support

- CHANGELOG.rst
- st2common/st2common/util/param.py
- st2common/tests/unit/test_param_utils.py
- st2tests/st2tests/fixtures/generic/actions/action_user_default.yaml
Cherry pick changes from https://github.com/StackStorm/st2/pull/2763
> Render user params (jinja) in API

- st2common/bin/migrations/v1.5/st2-migrate-datastore-to-include-scope-secret.py
Cherry pick https://github.com/StackStorm/st2/pull/2768
> Explicit messages for script

- st2common/bin/st2-self-check
- st2common/setup.py
This PR adds back a working version of the self check script.
> Adding back self check script

- st2api/st2api/controllers/v1/webhooks.py
- st2common/st2common/models/api/trigger.py
- st2common/st2common/util/jsonify.py
- st2reactor/st2reactor/container/sensor_wrapper.py
- st2reactor/st2reactor/timer/base.py
- st2reactor/tests/unit/test_sensor_wrapper.py
This pull request fixes some issued introduced by #2800.
Sadly those issues were not caught by unit and integration tests, they were only caught by end to end tests which don't run for every PR.
The root cause of some of the issues is that the code relied on the internal mongoengine functionality which has changed.
> Mongoengine related fixes

- CHANGELOG.rst
- st2actions/st2actions/notifier/notifier.py
- st2actions/st2actions/scheduler.py
- st2actions/tests/unit/policies/test_base.py
- st2client/st2client/commands/policy.py
This was originally reported at https://github.com/StackStorm/st2/issues/2797#issuecomment-232146181
> Make sure that we don't apply policies which are disabled

- contrib/chatops/actions/templates/default.j2
Our Slack CI tests caught it but really we should have unit tests to validate it. Let me unbreak master and then here is a JIRA  https://stackstorm.atlassian.net/browse/STORM-2236 (sorry, internal link) to add a test for this jinja that I'll pick next.
> Oh my space

- st2actions/tests/unit/test_action_runner_worker.py
Simple test for #2823 which verifies that the right dispatcher class is used.
> Add test for ActionsQueueConsumer

- contrib/chatops/actions/workflows/post_result.yaml
> format_execution_result no longer returns a tuple

- st2reactor/st2reactor/rules/filter.py
fixed small typo in error log message
> small log typo fix

- .travis.yml
- CHANGELOG.rst
- Makefile
- fixed-requirements.txt
I need to make the same change in st2-packages, etc. and make sure it works there end to end.
> Upgrade to latest version of pip (8.1.2)

- conf/logrotate.conf
This fixes the "mysterious" st2actionrunner service manager file is deleted issue.
It was originally caught by vp on Slack (thanks!).
I will also cherry-pick this into v2.0.0 and publish new packages once they are built.
> Fix logrotate bug

- CHANGELOG.rst
- st2client/st2client/commands/keyvalue.py
- st2common/st2common/config.py
- st2common/st2common/script_setup.py
- st2common/st2common/service_setup.py
- st2common/st2common/transport/bootstrap.py
- st2common/st2common/transport/bootstrap_utils.py
This PR contains additional changes and fixes we want to include in the v2.0.1 release.
> Additional changes for v2.0.1 release

- contrib/packs/actions/create.meta.yaml
- contrib/packs/actions/render_template.py
- contrib/packs/actions/render_template.yaml
- contrib/packs/actions/templates/pack.yaml.j2
- contrib/packs/actions/templates/pack.yml.j2
- contrib/packs/actions/workflows/create.yaml
- st2api/st2api/controllers/v1/actions.py
- st2api/st2api/controllers/v1/packs.py
- st2client/st2client/commands/pack.py
- st2client/st2client/models/core.py
- st2common/st2common/models/api/base.py
- st2common/st2common/models/api/pack.py
```
(virtualenv)vagrant@arkham:/dock/st2$ st2 pack create thing --author="enykeev" --version="0.0.1" --description="some description"
[ succeeded ] create directory
[ succeeded ] change permissions
[ succeeded ] change ownership
[ succeeded ] render pack.yml
[ succeeded ] save pack.yml
[ succeeded ] create subdirectories
(virtualenv)vagrant@arkham:/dock/st2$ cat /opt/stackstorm/packs/thing/pack.yml
---
name: thing
description: some description
version: 0.0.1
author: enykeev
(virtualenv)vagrant@arkham:/dock/st2$ ls -lah /opt/stackstorm/packs/thing
total 24K
drwxrwxr-x 5 vagrant stanley 4.0K Oct  4 10:54 .
drwxr-xr-x 7 vagrant vagrant 4.0K Oct  4 10:54 ..
drwxrwxr-x 2 vagrant stanley 4.0K Oct  4 10:54 actions
-rwxrwxr-x 1 vagrant stanley   78 Oct  4 11:22 pack.yml
drwxrwxr-x 2 vagrant …
```
> Pack intialization

- conf/st2.conf.sample
- conf/st2.dev.conf
- contrib/packs/actions/get_config.py
- contrib/packs/actions/get_config.yaml
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/workflows/create.yaml
- contrib/packs/config.yaml
- st2api/st2api/controllers/v1/packs.py
- st2client/st2client/commands/pack.py
- st2client/st2client/models/core.py
- st2common/st2common/config.py
- st2common/st2common/content/utils.py
- st2common/st2common/models/api/pack.py
Just so we can continue to work on the same branch and not interfere with each other.
> Pack improvements

- circle.yml
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
> It's ubunty trusty and we want 3.2

- contrib/core/actions/pause.py
- contrib/core/actions/pause.yaml
- contrib/core/pack.yaml
- Expansion of Core Actions
Addition of pause action allowing for a random pause between steps of a workflow.
action can take fixed duration and wait that long or using boolean random field will pause for up to that time in seconds
> Addition of pause core action

- fixed-requirements.txt
- requirements.txt
- st2api/st2api/controllers/v1/pack_configs.py
- st2client/in-requirements.txt
- st2client/requirements.txt
- st2client/st2client/client.py
- st2client/st2client/commands/pack.py
- st2client/st2client/models/config.py
- st2client/st2client/models/core.py
- st2client/st2client/utils/interactive.py
- st2client/tests/unit/test_interactive.py
- st2common/st2common/models/api/pack.py
- tools/launchdev.sh
Due to a multitude of requests both from inside and outside the team, I humbly present you interactive pack configuration.
[![asciicast](https://asciinema.org/a/8dnn9oenfiokqwsojybbnxva7.png)](https://asciinema.org/a/8dnn9oenfiokqwsojybbnxva7)
> Interactive pack configuration

- fixed-requirements.txt
- requirements.txt
- st2api/st2api/controllers/v1/pack_configs.py
- st2client/in-requirements.txt
- st2client/requirements.txt
- st2client/st2client/client.py
- st2client/st2client/commands/pack.py
- st2client/st2client/models/config.py
- st2client/st2client/models/core.py
- st2client/st2client/utils/interactive.py
- st2client/tests/unit/test_interactive.py
- st2common/st2common/models/api/pack.py
- tools/launchdev.sh
Retargeting https://github.com/StackStorm/st2/pull/2964 to a proper branch.
> Interactive pack configuration (retargeting)

- fixed-requirements.txt
- requirements.txt
- st2client/in-requirements.txt
- st2client/requirements.txt
Crumbs from https://github.com/StackStorm/st2/pull/2978
> Add missing dependency

- st2client/st2client/commands/resource.py
Just cutting down on some redundant code with a simpler structure for overriding commands
> Simplify command override decisions

- CHANGELOG.rst
- st2common/st2common/services/datastore.py
- st2common/tests/unit/test_datastore.py
> Adding timeout Datastore Client object based on Token TTL

- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/keyvalue.py
- st2common/st2common/rbac/utils.py
> Fix typo - is_provider -> is_provided

- contrib/packs/actions/pack_mgmt/download.py
- st2common/st2common/bootstrap/base.py
- st2common/st2common/util/pack.py
Just a small thing so we don't need to duplicate the same logic in multiple places.
> Use utility function for retrieving pack metadata

- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/tests/test_action_download.py
> Add more tests for pack actions

- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2client/st2client/commands/pack.py
- st2common/st2common/services/packs.py
- st2common/st2common/util/misc.py
- st2common/tests/unit/test_misc_utils.py
* Improved error message
* Pack search is now case insensitive by default. This makes it more useful and easier to find things.
> Various pack API changes

- contrib/runners/python_runner/runner.yaml
The description is confusing to some users since it only reflects CLI specifics.
Fixes https://github.com/StackStorm/st2web/issues/280
> Python runner env description

- st2debug/st2debug/cmd/submit_debug_info.py
> Use yaml.safe_dump instead of yaml.dump

- st2client/st2client/commands/pack.py
> fix CLI help for pack install

- st2common/bin/st2-self-check
```
[vagrant@st2test ~]$ sudo ST2_AUTH_TOKEN=$(st2 auth st2admin -p pass -t) /opt/stackstorm/st2/bin/st2-self-check
Cloning into 'st2tests'...
Installing asserts,fixtures,tests
remote: Counting objects: 126, done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 126 (delta 24), reused 82 (delta 13), pack-reused 0
Receiving objects: 100% (126/126), 651.32 KiB | 263.00 KiB/s, done.
Resolving deltas: 100% (24/24), done.
Installing examples...........
id: 584085c655fc8c34845b16a6
parameters:
packs:
- examples
- tests
- asserts
- fixtures
- webui
result:
exit_code: 0
result: 'Successfuly set up virtualenv for the following packs: examples, tests, asserts, fixtures, webui'
stderr: 'st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv …
```
>  Fix self-check-script for new pack management

- CHANGELOG.rst
- contrib/runners/python_runner/python_runner.py
- contrib/runners/python_runner/tests/unit/test_pythonrunner.py
- st2common/st2common/runners/python_action_wrapper.py
- st2common/st2common/util/monkey_patch.py
- st2tests/st2tests/resources/packs/pythonactions/actions/python_paths.py
> Workaround for Python action runner subprocess sys.path pollution

- CHANGELOG.rst
- st2common/st2common/constants/pack.py
- st2common/st2common/models/api/pack.py
- st2common/st2common/util/pack.py
- st2common/tests/unit/test_resource_registrar.py
- st2common/tests/unit/test_versioning_utils.py
Cherry pick of https://github.com/StackStorm/st2/pull/3085 for v2.1.
> Add pack back pack version normalization (v2.1)

- st2common/st2common/models/api/pack.py
> Add deprecation warning on non-semver version 

- st2common/st2common/models/api/pack.py
Picking up @dzimine's changes for 2.1.
> Deprecation warning

- st2client/st2client/commands/pack.py
- st2client/st2client/models/core.py
- st2client/st2client/utils/terminal.py
Fixes STORM-2530
```
(virtualenv)vagrant@arkham:/dock/st2$ st2client/st2client/shell.py pack install https://github.com/stackstorm-exchange/stackstorm-github
[ succeeded ] download pack
[ succeeded ] make a prerun
[ succeeded ] install pack dependencies
[ succeeded ] register pack
+-------------+-------------------------------------------------+
| Property    | Value                                           |
+-------------+-------------------------------------------------+
| name        | github                                          |
| description | st2 content pack containing github integrations |
| version     | 0.6.0                                           |
| author      | StackStorm, Inc.                                | …
```
> Show which packs has been installed

- CHANGELOG.rst
> Sync master changelog with v2.1 branch

- CHANGELOG.rst
Changelog entry for change in https://github.com/StackStorm/st2/pull/3012.
> Update changelog for core.http action change

- CHANGELOG.rst
- st2common/st2common/models/system/action.py
- st2common/tests/unit/test_shell_action_system_model.py
PR which includes some small changes on top of #3116:
* Support for Python 3
* Changelog entry
> Userlocalhost bugfix/unables to handle unicode

- st2debug/tests/integration/test_submit_debug_info.py
This adds tests for change in #3081.
> Add tests for submit-debut-info changes

- CHANGELOG.rst
> Sync up master changelog with v2.1 branch

- CHANGELOG.rst
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_callback.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_cancel.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_policy.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_rerun.py
- st2actions/st2actions/policies/concurrency.py
- st2actions/st2actions/policies/concurrency_by_attr.py
- st2actions/tests/unit/policies/test_concurrency.py
- st2actions/tests/unit/policies/test_concurrency_by_attr.py
- st2common/st2common/policies/concurrency.py
- st2common/tests/unit/test_policies_registrar.py
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workbook_v2_call_workflow_action.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/workbook_v2_call_workflow_action.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/workbook_v2_many_workflows_no_default.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workbook_v2.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workbook_v2_call_workflow_action.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workbook_v2_many_workflows.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workbook_v2_many_workflows_no_default.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workflow_v2.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/actions/workflows/xformed_workflow_v2_many_workflows.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/policies/cancel_on_concurrency.yaml
- st2tests/st2tests/fixtures/packs/mistral_tests/policies/cancel_on_concurrency_by_attr.yaml
Cancels mistral workflow when a subtask has been cancelled due to concurrency policy. Previously, the mistral workflow is not cancelled and orphaned as running in mistral.
> Fix cancel policy

- conf/HA/st2.conf.sample
- conf/st2.package.conf
- conf/st2.prod.conf
- st2actions/tests/unit/test_paramiko_ssh.py
- st2common/st2common/runners/paramiko_ssh.py
> fixed small typos in comments

- CHANGELOG.rst
- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_auth.py
- st2actions/st2actions/handlers/mistral.py
Fix how mistral client and resource managers are being used in the mistral runner. Authentication has changed in the mistral client. Fix unit test accordingly.
> Fix usage of mistral client in mistral runner

- st2client/requirements.txt
- st2client/setup.py
This is to address https://github.com/StackStorm/st2/issues/3166
> Updated version of six to 1.10.0 to make sure its compatible with the newer versions of steuptools.

- CHANGELOG.rst
- contrib/examples/actions/mistral-jinja-workbook-complex.yaml
- contrib/examples/actions/workflows/mistral-jinja-workbook-complex.yaml
- st2tests/integration/mistral/test_wiring.py
Add an integration test to test jinja expressions in mistral workflows.
> Add integration test for jinja evaluation in mistral

- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py
Fix use case where workflow is canceled but tasks is in idle state. Clean up state determination for additional use cases.
> Fix mistral workflow state determination

- CHANGELOG.rst
This pull request adds changelog entry for #3144.
> Add changelog entry for #3144 (st2-run-pack-tests script changes)

- CHANGELOG.rst
> Update release date for 2.2.0 so it reflects actual release date (master)

- CHANGELOG.rst
> Update release date for 2.2.0 so it reflects actual release date (v2.2 branch)

- conf/st2.dev.conf
> Disable CORS in development config

- st2api/st2api/controllers/base.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/aliasexecution.py
- st2api/st2api/controllers/v1/keyvalue.py
- st2api/st2api/controllers/v1/packviews.py
- st2api/st2api/controllers/v1/rules.py
- st2common/st2common/rbac/decorators.py
- st2common/st2common/rbac/utils.py
- st2common/st2common/util/api.py
- st2common/tests/unit/test_rbac_utils.py
Tried to clean it up a little bit and bring `pecan.request` closer to the action.
> [NO MERGE] RBAC refactoring

- st2common/st2common/services/datastore.py
Couple of docstring typos in get_value/set_value
> Fixed docstring typos

- st2common/bin/st2-run-pack-tests
https://github.com/StackStorm/st2/pull/3318 fix for master branch.
> Fix dependency version specified in st2-run-pack-tests-tool (master)

- st2common/st2common/rbac/types.py
Added missing API descriptions, and added small language cleanup.
Required to resolve https://github.com/StackStorm/ipfabric-docs/issues/77
> added missing API descriptions

- CHANGELOG.rst
> Sync changelog with v2.2.1 release

- st2api/st2api/controllers/resource.py
- st2api/st2api/controllers/v1/actionviews.py
- st2api/st2api/controllers/v1/pack_config_schemas.py
- st2api/st2api/controllers/v1/policies.py
- st2api/st2api/controllers/v1/rbac.py
- st2api/st2api/controllers/v1/ruleviews.py
- st2api/st2api/controllers/v1/timers.py
- st2api/st2api/controllers/v1/traces.py
- st2api/st2api/controllers/v1/triggers.py
- st2common/st2common/openapi.yaml
> (RBAC enable) Fix when permission_type is not provided with API call

- contrib/runners/announcement_runner/runner.yaml
- contrib/runners/cloudslang_runner/runner.yaml
- contrib/runners/http_runner/runner.yaml
- contrib/runners/windows_command_runner/runner.yaml
- contrib/runners/windows_script_runner/runner.yaml
Minor typo/language changes to metadata for runners, cleaning up some descriptions
> Runner metadata updates

- CHANGELOG.rst
- st2common/st2common/services/keyvalues.py
- st2common/tests/unit/test_keyvalue_lookup.py
> Properly cast numbers in keyvalues

- CHANGELOG.rst
- contrib/chatops/CHANGES.md
- contrib/chatops/pack.yaml
This pull request adds changelog entry and updates pack version field for changes in #3425.
> Changelog entry for ChatOps pack changes (3425)

- CHANGELOG.rst
- contrib/examples/actions/pythonactions/forloop_get_github_page.py
- contrib/examples/actions/pythonactions/forloop_increase_index_and_check_condition.py
- contrib/examples/actions/pythonactions/forloop_parse_github_repos.py
- contrib/examples/actions/pythonactions/forloop_push_github_repos.py
- contrib/examples/pack.yaml
This pull request adds a changelog entry and cleans up some style (use 4 spaces for a tab, etc.) for change in #3328.
> Changelog entry, style cleanup for 3328

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_rules.py
- st2common/st2common/router.py
- st2tests/st2tests/fixtures/generic/rules/rule space.yaml
Fixes #3459 and fixes StackStorm/st2web#357
> Adding percent parsing and various debug messages

- st2actions/tests/unit/test_worker.py
Change the while loop into a for loop to ensure the test exit after set time.
> Fix while loop in worker shutdown unit test

- CHANGELOG.rst
Putting in a more accurate release date.
I expected release artifacts be ready before this date, but we should announce it on Monday / Tuesday.
> Udpate release date

- st2common/st2common/models/db/liveaction.py
- st2common/st2common/models/db/rbac.py
Index fix from #3493 for master.
> Fix context field index (master)

- CHANGELOG.rst
- st2actions/st2actions/notifier/notifier.py
- st2actions/tests/unit/policies/test_concurrency.py
- st2actions/tests/unit/policies/test_concurrency_by_attr.py
- st2actions/tests/unit/test_notifier.py
- st2actions/tests/unit/test_policies.py
- st2actions/tests/unit/test_rescheduler.py
- st2tests/st2tests/mocks/execution.py
- st2tests/st2tests/mocks/liveaction.py
Fixes: https://github.com/StackStorm/st2/issues/3487
> Notifier to scan executions queue and not liveaction queue

- CHANGELOG.rst
- contrib/examples/actions/chains/regex_jinja_filter.yaml
- contrib/examples/actions/regex_jinja_filter.meta.yaml
- st2common/st2common/jinja/filters/regex.py
- st2common/st2common/util/jinja.py
- st2common/tests/unit/test_jinja_render_regex_filters.py
Closes https://github.com/StackStorm/st2/issues/3343
> Implement new regex_substring jinja filter

- CHANGELOG.rst
> Update changelog with v2.3.1 release info

- .circle/add-itest-user.sh
- Makefile
- circle.yml
- st2client/st2client/base.py
CircleCI 2.0 introroduces workflows: https://circleci.com/docs/2.0/workflows/
Experimenting/adding workflows on top of https://github.com/StackStorm/st2/pull/3547 to see if we can run Unit + Integration tests in another parallel/independent to st2-packages workflow sub-task.
Also incorporating Unit + Integration CI timing improvements from https://github.com/StackStorm/st2/pull/3545
> Experimental/circle 2.0 (with workflows)

- CHANGELOG.rst
- conf/st2.conf.sample
- conf/st2.dev.conf
- conf/st2.package.conf
- conf/st2.prod.conf
- conf/st2.tests.conf
- conf/st2.tests1.conf
- contrib/packs/actions/pack_mgmt/download.py
- contrib/packs/actions/pack_mgmt/search.py
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- contrib/packs/config.schema.yaml
- st2api/st2api/controllers/v1/packs.py
- st2common/st2common/config.py
- st2common/st2common/services/packs.py
- st2common/st2common/util/virtualenvs.py
- st2common/tests/unit/test_virtualenvs.py
Fixes #3137 
* - [X] Pack Download should be able to work with a proxy
* - [X] Pack dependencies install should be able to work with a proxy
* - [X] Allow env variables like http_proxy, https_proxy etc 
* - [X] Docs https://github.com/StackStorm/st2docs/pull/551
User needs to set environment variables ``https_proxy`` or ``http_proxy`` for st2api and st2actionrunner processes. See https://github.com/StackStorm/st2docs/pull/551
```
ubuntu@st2test:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DROP       tcp  --  anywhere             anywhere             tcp dpt:http
DROP …
```
> Proxy support for pack install

- .travis.yml
- Makefile
- circle.yml
- test-requirements.txt
This includes changes from #3545 for v2.3 branch so we have a consistent environment.
Merging it will probably trigger a new v2.3dev packages build, but that's not a problem.
> Travis changes for v2.3 branch

- st2api/st2api/controllers/v1/auth.py
- st2api/tests/unit/controllers/v1/test_auth_api_keys.py
> Fix st2 apikey generation when auth is disabled

- CHANGELOG.rst
> Add changelog entry for #3593

- fixed-requirements.txt
- requirements.txt
- st2client/requirements.txt
- st2client/setup.py
- st2common/in-requirements.txt
> Revert requests and certifi upgrade as a work-around for #3603

- CHANGELOG.rst
> Add changelog entry for #3594

- CHANGELOG.rst
- contrib/examples/actions/chains/invoke_mistral_with_jinja.yaml
- contrib/examples/actions/invoke_mistral_with_jinja.yaml
- contrib/runners/mistral_v2/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2.py
- st2api/st2api/controllers/v1/timers.py
- st2client/st2client/commands/action.py
- st2client/st2client/commands/policy.py
- st2client/st2client/commands/rbac.py
- st2client/st2client/commands/rule.py
- st2client/st2client/commands/rule_enforcement.py
- st2client/st2client/commands/timer.py
- st2client/st2client/commands/trace.py
- st2client/st2client/commands/triggerinstance.py
- st2client/st2client/models/core.py
- st2client/st2client/utils/interactive.py
- st2client/tests/unit/test_interactive.py
- st2client/tests/unit/test_models.py
- st2common/st2common/util/jinja.py
- st2common/st2common/util/workflow/mistral.py
- st2common/tests/unit/test_util_jinja.py
- st2tests/integration/mistral/test_wiring.py
Some additional changes for v2.3.2 after we decided to fix the backward incompatible change we accidentally included in v2.3.1 and wait a couple of more days with v2.3.2.
> More changes for v2.3.2

- CHANGELOG.rst
> Sync master changelog with v2.3.2 release / branch

- CHANGELOG.rst
Changelog entry for https://github.com/StackStorm/st2-packages/pull/477.
> Add changelog entry for MongoDB 3.4 change

- contrib/runners/mistral_v2/query/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_querier_v2.py
The use of last query time lead to edge cases where some tasks are not queried again. Instead of using the last query time, the task record stored in the liveaction result is compared to identified whether it needs to be retrieved again.
> Refactor how mistral querier determines which tasks to query

- CHANGELOG.rst
- st2client/st2client/commands/action.py
Changelog entry for https://github.com/StackStorm/st2/pull/3670.
> Changelog entry for #3670

- CHANGELOG.rst
> Put chanelog entry under the correct release

- CHANGELOG.rst
> [2.4 branch] Move filters entry to the correct section

- CHANGELOG.rst
- st2client/st2client/commands/action.py
Small style change and changelog entry for #3704.
> Changelog entry for #3704

- .travis.yml
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_auth.py
The interface for the authenticate method has changed. Fix the unit tests associated with the interface change.
> Fix call to keystone auth in mistral runner

- CHANGELOG.rst
- contrib/runners/mistral_v2/callback/mistral_v2.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_auth.py
- contrib/runners/mistral_v2/tests/unit/test_mistral_v2_callback.py
- st2actions/tests/unit/test_execution_cancellation.py
- st2api/st2api/controllers/v1/packs.py
- st2api/tests/unit/controllers/v1/test_packs_rbac.py
- st2common/st2common/openapi.yaml
- st2common/st2common/openapi.yaml.j2
- st2common/st2common/services/action.py
Changes for v2.4.1
- https://github.com/StackStorm/st2/pull/3696
- https://github.com/StackStorm/st2/pull/3721
- https://github.com/StackStorm/st2/pull/3726
- https://github.com/StackStorm/st2/pull/3727
> v2.4.1 changes

- CHANGELOG.rst
Add the v2.4.1 header and start fresh with "In Development".
> Update change log post v2.4.1 release

- CHANGELOG.rst
This PR adds changelog entry for #3746.
> Update changelog for #3746

- CHANGELOG.rst
- contrib/core/actions/http.yaml
- contrib/examples/actions/weather.yaml
- contrib/linux/actions/check_loadavg.yaml
- contrib/linux/actions/check_processes.yaml
> Add missing type for the parameters with enum

- CHANGELOG.rst
- st2client/st2client/commands/action.py
- st2client/st2client/commands/auth.py
- st2client/st2client/commands/keyvalue.py
- st2client/st2client/commands/pack.py
- st2client/st2client/commands/resource.py
- st2client/st2client/commands/trigger.py
- st2client/st2client/commands/triggerinstance.py
- st2common/st2common/constants/error_messages.py
Made some minor typo/grammar/language fixes to help strings and error messages
Also fixes #3135
> Tidied up help and error messages

- CHANGELOG.rst
Changelog entry for https://github.com/StackStorm/st2/pull/3789.
> Changelog entry for #3789

- CHANGELOG.rst
> Minor changelog typo

- st2api/st2api/controllers/v1/aliasexecution.py
- st2api/tests/unit/controllers/v1/test_alias_execution.py
- st2common/st2common/models/utils/action_alias_utils.py
- st2common/tests/unit/test_util_actionalias_matching.py
For some reason Travis CI got stuck and didn't continue building PR #3884 so I overrided that check and merged it manually.
It turned out there were some small lint violations which this PR fixes.
> Fix lint violations from 3884

- CHANGELOG.rst
- contrib/runners/python_runner/tests/unit/test_pythonrunner.py
- st2api/st2api/controllers/v1/rules.py
- st2api/tests/unit/controllers/v1/test_policies_rbac.py
- st2api/tests/unit/controllers/v1/test_rules.py
- st2common/st2common/exceptions/rbac.py
- st2common/st2common/models/api/base.py
- st2common/st2common/models/db/stormbase.py
- st2common/st2common/models/db/trigger.py
- st2common/st2common/rbac/utils.py
- st2common/st2common/router.py
- st2common/st2common/runners/utils.py
- st2common/st2common/services/datastore.py
- st2common/tests/unit/test_db_model_uids.py
- st2tests/st2tests/resources/packs/pythonactions/actions/pascal_row.py
v2.5.1 release was postponed so I decided to include a couple of more changes (bug fixes) in v2.5.1:
* https://github.com/StackStorm/st2/pull/3864
* https://github.com/StackStorm/st2/pull/3893
Once this PR has been merged I will change milestone in those PRs from v2.6.0 to v2.5.1
> More changes for v2.5.1

- st2client/st2client/commands/action.py
- st2client/tests/unit/test_action.py
- st2client/tests/unit/test_command_actionrun.py
Re-implements changes from #3909 into the v2.5 release branch
> Cherry pick changes from #3909 into v2.5

- CHANGELOG.rst
Adds missing changelog entry for #3909
> Added CHANGELOG entry for `--auto-dict` flag

- contrib/examples/sensors/echo_flask_app.py
Fix the port to be an integer. Use the format function for string formatting.
ref #3667
> Update the port to be an integer.

- st2api/st2api/controllers/v1/actionviews.py
- st2api/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
Fix for issue reported in #3941.
Related PR: #3939
> Fix /v1/actions/views/overview API endpoint (RBAC)

- CHANGELOG.rst
- fixed-requirements.txt
- requirements.txt
Went over change logs and I didn't find any breaking changes.
All the tests also appear to pass.
> Update various internal dependencies to latest stable versions

- CHANGELOG.rst
- st2client/st2client/commands/action.py
Add "paused" to possible execution status.
> Add 'paused' to a list of available statuses in ST2 CLI

- st2common/setup.py
Add an entry for the st2-track-result command line utility into the setup script.
> Add the st2-track-result utility to setup

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_packs.py
- st2client/st2client/models/core.py
Good catch by @LindsayHill.
Resolves #4082.
We should also cherry pick this into v2.7 branch and release v2.7.1 this week.
> Fix "st2 pack search" CLI command

- .gitmodules
- .travis.yml
- CHANGELOG.rst
- Makefile
- contrib/packs/actions/pack_mgmt/setup_virtualenv.py
- contrib/packs/actions/setup_virtualenv.yaml
- contrib/runners/action_chain_runner/tests/unit/test_actionchain_pause_resume.py
- contrib/runners/python_runner/tests/unit/test_pythonrunner.py
- scripts/fixate-requirements.py
- st2api/tests/unit/controllers/v1/test_packs.py
- st2client/st2client/models/core.py
- st2common/bin/st2-run-pack-tests
- st2common/st2common/util/virtualenvs.py
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_cancel.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_last_task_failed_with_no_next_task.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_context_access.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_error.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_init_vars.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_no_more_task.yaml
- st2tests/st2tests/fixtures/packs/action_chain_tests/actions/chains/test_pause_resume_with_published_vars.yaml
- st2tests/st2tests/fixturesloader.py
Included changes:
* https://github.com/StackStorm/st2/pull/4071
* https://github.com/StackStorm/st2/pull/4077
* https://github.com/StackStorm/st2/pull/4078
* https://github.com/StackStorm/st2/pull/4083
* https://github.com/StackStorm/st2/pull/4085
* https://github.com/StackStorm/st2/pull/4087
Only #4083 and #4087 are the ones which actually affect end users.
> Changes for the v2.7.1 release

- pylint_plugins/db_models.py
- st2common/st2common/router.py
- st2common/st2common/util/monkey_patch.py
- st2common/st2common/util/shell.py
- test-requirements.txt
This pull request updates flake8 and pylint to the latest stable version.
It also required some code changes and work-around since new version of pylint detects more issues.
> Upgrade various test and dev dependencies (flake8, pylint)

- CHANGELOG.rst
It looks like changelog entries some how got mixed up - likely during the merge conflict resolution.
> Fix changelog (master)

- CHANGELOG.rst
Changelog entry for https://github.com/StackStorm/st2/pull/4127.
> Add a changelog entry for #4127

- CHANGELOG.rst
> Update changelog with v2.7.2 release information

- Makefile
- contrib/runners/python_runner/python_runner/python_runner.py
- st2actions/st2actions/container/base.py
- st2common/st2common/metrics/base.py
- st2common/st2common/metrics/drivers/statsd_driver.py
- st2common/st2common/services/action.py
- st2common/st2common/util/action_db.py
- st2common/tests/unit/test_metrics.py
- st2reactor/st2reactor/rules/engine.py
- st2reactor/st2reactor/rules/worker.py
> Completing Initial Metrics Integration

- .github/ISSUE_TEMPLATE.md
I've simplified the issue template a little. Goal is still to have a template, but to get more useful content in the snippet displayed when issues are auto-posted to Slack.
> Simplified issue template

- CHANGELOG.rst
Changelog entry for changes in #4165.
> Add changelog entry for #4165

- .travis.yml
- contrib/runners/python_runner/tests/integration/test_python_action_process_wrapper.py
- st2actions/tests/unit/test_paramiko_ssh.py
- st2actions/tests/unit/test_runner_container.py
- st2actions/tests/unit/test_worker.py
- st2auth/st2auth/handlers.py
- st2auth/tests/unit/controllers/v1/test_token.py
- st2auth/tests/unit/test_handlers.py
- st2common/st2common/runners/paramiko_ssh.py
- st2stream/st2stream/controllers/v1/stream.py
- st2stream/tests/unit/controllers/v1/test_rbac_for_supported_endpoints.py
- st2stream/tests/unit/controllers/v1/test_stream.py
- tox.ini
This pull request contains code fixes and changes which are needed to get unit tests for `st2auth`, `st2actions` and `st2stream` component / package to pass.
> Python 3 fixes and changes for st2auth, st2actions, st2stream

- contrib/examples/actions/orchestra-st2-ctx.yaml
- contrib/examples/actions/workflows/orchestra-st2-ctx.yaml
- contrib/runners/orchestra_runner/orchestra_runner/orchestra_runner.py
- contrib/runners/orchestra_runner/tests/unit/test_orchestra_basic.py
- st2actions/tests/unit/test_workflow_engine.py
- st2common/st2common/models/db/workflow.py
- st2common/st2common/services/workflows.py
- st2common/tests/unit/services/test_workflow.py
- st2common/tests/unit/services/test_workflow_cancellation.py
- st2common/tests/unit/services/test_workflow_write_conflict.py
- st2common/tests/unit/test_db_task.py
- st2tests/integration/orchestra/test_wiring.py
- st2tests/st2tests/base.py
Pass st2 runtime context such as action exectuion ID into the workflow execution context.
> Pass st2 runtime context to workflow execution context

- CHANGELOG.rst
Add changelog entry for Orchestra to let user knows the feature is beta.
> Add changelog entry for Orchestra

- Makefile
- contrib/examples/actions/orchestra-st2kv.yaml
- contrib/examples/actions/workflows/orchestra-st2kv.yaml
- contrib/runners/orchestra_runner/functions/st2kv.py
- contrib/runners/orchestra_runner/orchestra_runner/orchestra_runner.py
- contrib/runners/orchestra_runner/setup.py
- contrib/runners/orchestra_runner/tests/integration/test_functions.py
- contrib/runners/orchestra_runner/tests/unit/test_functions.py
- contrib/runners/orchestra_runner/tests/unit/test_orchestra_basic.py
- scripts/travis/prepare-integration.sh
- st2actions/tests/unit/test_workflow_engine.py
- st2common/st2common/util/keyvalue.py
- st2common/tests/unit/test_util_keyvalue.py
This PR adds st2kv custom expression function for orchestra rendering.
~Refactor ST2API to use st2common implementation~ (Too messy)
~Delayed rendering to avoid secret being recorded in WorkflowExecution~ Will happen in another PR
> Adding st2kv function

- st2common/st2common/services/workflows.py
Move the update of the task execution before the action execution is requested. Currently, the task execution is updated after the request and there are cases where the action execution completed very quickly and the completion of the action execution is processed first. When completion is processed, the task execution is also updated and this causees conflict with the previous task execution update.
> Fix race between task and action execution

- contrib/examples/actions/orchestra-examples.yaml
- contrib/examples/actions/workflows/orchestra-examples.yaml
- st2common/bin/st2-self-check
* Adding orchestra-examples workflow and action definitions
* Adding orchestra to st2-self-check
Closes #4202
> Adding Orchestra to Self Check

- CHANGELOG.rst
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions.py
- st2common/st2common/openapi.yaml
- st2common/st2common/openapi.yaml.j2
Changes from #4226 for v2.8.0 release.
> ?include_attributes regression fix for /v1/executions API endpoint, update openapi.yaml (v2.8)

- st2common/st2common/openapi.yaml
- st2common/st2common/openapi.yaml.j2
Very small typo in API description field.
> Fix typo in API description

- CHANGELOG.rst
- contrib/runners/http_runner/http_runner/runner.yaml
> Sync changelog with v2.8.1 release

- .travis.yml
- scripts/travis/install-and-run-mongodb.sh
- scripts/travis/install-coverage-dependencies.sh
- scripts/travis/mongod.conf
- scripts/travis/submit-codecov-coverage.sh
- st2common/st2common/models/db/__init__.py
- st2common/st2common/models/db/actionalias.py
- st2common/st2common/models/db/sensor.py
- st2common/st2common/models/db/workflow.py
- st2common/st2common/rbac/migrations.py
- st2common/tests/unit/test_rbac_syncer.py
- st2tests/st2tests/base.py
Some small coverage / build related improvements:
1. Move my fork with bugfix for codecov-python library to StackStorm organization
2. Run "make play" during build. This prints out various environment information which helps with troubleshooting various build related issues.
3. Add back various MongoDB performance optimizations and re-enable "notablescan" option which will warn us if some query is not using an index.
4. Fix issues with missing indexes and queries which resulted in full table scans instead of using the index
> More coverage improvements

- conf/HA/nginx/st2.conf.controller.sample
- conf/HA/st2.conf.sample
`[stream]` and `[workflow_engine]` sections missing from example HA `/etc/st2/st2.conf`.
`/stream` missing from HA controller example nginx config
> Added stream and workflow_engine HA example configs

- contrib/runners/orquesta_runner/tests/unit/test_basic.py
- contrib/runners/orquesta_runner/tests/unit/test_pause_and_resume.py
- contrib/runners/orquesta_runner/tests/unit/test_policies.py
- st2actions/st2actions/notifier/notifier.py
- st2actions/st2actions/scheduler.py
- st2actions/st2actions/workflows/workflows.py
- st2actions/tests/unit/policies/test_base.py
- st2common/st2common/services/policies.py
- st2common/st2common/services/workflows.py
- st2common/st2common/transport/consumers.py
- st2common/st2common/transport/queues.py
- st2common/tests/unit/test_policies_registrar.py
- st2common/tests/unit/test_queue_consumer.py
- st2tests/st2tests/fixtures/packs/orquesta_tests/policies/retry_sequential_on_failure.yaml
Implement queue consumer that can handle variable message types. Relocate handling of action execution completion to workflow engine. Add policy application to the workflow engine for workflow tasks.
> Relocate orquesta logic from notifier to the workflow engine

- .travis.yml
Travis have made changes to the APT add-on, and the safe listed APT sources.
https://blog.travis-ci.com/2018-08-29-addressing-reported-mitm-rce
> Travis: Manually add MongoDB repo

- st2common/st2common/models/db/__init__.py
Add the workflow database models to the list of models to ensure indexes.
> Add workflow to the list of models for indexing

- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Pin orquesta in st2common requirements to v0.2 release tag.
> Update orquesta to v0.2 in requirements

- st2actions/README.md
as above. Remove outdated README with broken links
> Remove outdated st2actions README

- Makefile
- st2common/st2common/cmd/generate_api_spec.py
- st2common/st2common/cmd/validate_api_spec.py
- st2common/st2common/openapi.yaml
- st2common/st2common/openapi.yaml.j2
- st2common/st2common/util/spec_loader.py
- st2reactor/tests/integration/test_sensor_watcher.py
Duplicate entry prevents openapi docs generation
> Fixing openapi definition

- contrib/runners/orquesta_runner/tests/unit/test_output_schema.py
- contrib/runners/python_runner/tests/unit/test_output_schema.py
> Fix typo in test output schema function

- CHANGELOG.rst
- contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
- contrib/runners/orquesta_runner/orquesta_runner/runner.yaml
- contrib/runners/orquesta_runner/tests/unit/test_notify.py
- st2common/st2common/exceptions/workflow.py
- st2common/st2common/models/db/workflow.py
- st2common/st2common/services/workflows.py
- st2tests/st2tests/fixtures/packs/orquesta_tests/actions/notify.yaml
Add a runner option named notify to allow user to specify notification on task completion.
> Add option to notify on orquesta task completion

- CHANGELOG.rst
- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/orquesta_runner/orquesta_runner.py
- contrib/runners/orquesta_runner/requirements.txt
- contrib/runners/orquesta_runner/tests/unit/test_context.py
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
- st2common/st2common/services/workflows.py
- st2tests/st2tests/fixtures/packs/orquesta_tests/actions/default-value-from-action-context.yaml
- st2tests/st2tests/fixtures/packs/orquesta_tests/actions/runtime-context.yaml
- st2tests/st2tests/fixtures/packs/orquesta_tests/actions/subworkflow-default-value-from-action-context.yaml
- st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/runtime-context.yaml
- st2tests/st2tests/fixtures/packs/orquesta_tests/actions/workflows/subworkflow-default-value-from-action-context.yaml
Fix access to st2 context in various locations of the workflow definition.  Fix access to api_user in the action context from the task action metadata.
> Fix context related bugs in orquesta

- .circleci/config.yml
Circle CI support suggested that change may help with the awful intermedaite Circle CI related issues we have been seeing for over a week now.
https://discuss.circleci.com/t/setup-remote-docker-connection-failures/26434
> Try temporary workaround for Circle CI build failure issues

- st2client/st2client/models/core.py
- st2client/tests/unit/test_client_liveaction.py
See #4442
This is my first PR for stackstorm, I tried to make this PR look like the other active PRS, but if I am missing anything or doing something wrong please let me know!
> Add get_children method to st2client for liveactions

- contrib/examples/actions/pythonactions/fibonacci.py
- contrib/examples/actions/pythonactions/forloop_parse_github_repos.py
- contrib/examples/actions/pythonactions/forloop_push_github_repos.py
- scripts/fixate-requirements.py
- st2api/st2api/controllers/exp/validation.py
- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/st2api/controllers/v1/aliasexecution.py
- st2api/st2api/controllers/v1/timers.py
- st2auth/st2auth/handlers.py
- st2client/st2client/commands/auth.py
- st2client/st2client/commands/pack.py
- st2client/st2client/commands/resource.py
- st2common/bin/st2-self-check
- st2common/bin/st2-track-result
- st2common/st2common/bootstrap/actionsregistrar.py
- st2common/st2common/router.py
- st2common/st2common/runners/paramiko_ssh.py
- st2common/st2common/services/sensor_watcher.py
- st2common/st2common/services/triggerwatcher.py
- st2common/st2common/transport/connection_retry_wrapper.py
- st2common/st2common/util/virtualenvs.py
- st2common/st2common/util/workflow/mistral.py
- st2common/st2common/validators/workflow/mistral/v2.py
More fixes for some minor Python 3 related issues uncovered by end to end tests.
> More Python 3 compatibility fixes

- st2actions/tests/unit/test_scheduler.py
This test covers the case when two schedulers pick up the same execution
and ensures the task is not picked up twice.
> Add test to cover scheduler race condition.

- st2api/st2api/controllers/v1/actionexecutions.py
- st2api/tests/unit/controllers/v1/test_executions.py
- st2client/st2client/commands/action.py
- st2client/st2client/models/core.py
- st2client/tests/unit/test_client_executions.py
- st2common/st2common/models/api/execution.py
- st2common/st2common/models/db/execution.py
- st2common/st2common/openapi.yaml
- st2common/st2common/openapi.yaml.j2
This commit adds necessary changes to st2client and st2api to accommodate delay
on re-run of actions.
> Adding delay to re-run

- CHANGELOG.rst
Add changelog entries for workflow output, task with items, and scheduler changes.
> Add changelog entries for Orquesta related changes

- fixed-requirements.txt
- requirements.txt
- st2client/requirements.txt
- st2common/requirements.txt
- test-requirements.txt
Just some house keeping for v3.0.0.
> Update dependencies to latest stable versions

- README.md
This pull request adds short section on how to report security issues to the readme.
> Add section on how to report security issues to the readme

- CHANGELOG.rst
- Makefile
- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- st2api/st2api/controllers/v1/keyvalue.py
- st2api/tests/unit/controllers/v1/test_kvps.py
- st2common/st2common/rbac/utils.py
- st2tests/st2tests/api.py
Included changes for the v2.9.2 release:
* https://github.com/StackStorm/st2/pull/4476
> Changes for v2.9.2 release

- CHANGELOG.rst
- st2api/st2api/controllers/v1/keyvalue.py
- st2api/tests/unit/controllers/v1/test_kvps.py
- st2common/st2common/rbac/utils.py
- st2tests/st2tests/api.py
Included changes for the v2.10.1 release:
* https://github.com/StackStorm/st2/pull/4476
> Changes for v2.10.1 release

- tools/launchdev.sh
Add arguments to the launchdev scripts to launch more than one schedulers and workflow engines. By default, only one scheduler and one workflow engine is launched.
> Update launchdev script to launch many schedulers and workflow engines

- tools/submit-per-service-metrics-to-statsd
Small change to the submit per process metrics script so it also includes Mistral processes (mistral-server, mistral-api).
> Update submit metrics script to also include mistral processes

- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update orquesta to version 0.4 to include fixes on CPU usage, interpretation of quoted strings and boolean values in shorthand publish, with items variable with the word "in" that conflict with syntax, and other docs updates.
> Update orquesta to version 0.4

- st2common/tests/unit/test_virtualenvs.py
> Fix typo in a test of st2common

- CHANGELOG.rst
Update changelog section for the recent 2.10.2 release.
> Update changelog for patch 2.10.2

- CHANGELOG.rst
- contrib/examples/actions/workflows/orquesta-join.yaml
- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
- st2common/st2common/services/workflows.py
Update orquesta dependency to commit with the fix. Minor refactoring to include the fix. Modify existing test to cover use case.
> Minor bug fix to orquesta for overwritten context on task join

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_base.py
- st2common/st2common/middleware/cors.py
PR to minor branch for changes in 2.10.3.
> 2.10.3 security patch

- st2api/tests/unit/controllers/v1/test_base.py
Just some additional test cases for fix in #4577 (to make sure there are no issues hiding in some edge cases).
> Add some additional asserts for origin header

- CHANGELOG.rst
Add changelog entry from the v2.10.3 patch release.
> Update changelog for v2.10.3

- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update orquesta version in requirements to include a number of fixes related to with items task.
> Update orquesta version in requirements

- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update orquesta dependency in requirements.txt to v0.5.
> Update orquesta version to v0.5

- st2client/README.rst
Per #4683 - st2client/README.rst was out of date and needed some love.
> Update out of date st2client/README.rst and add some additional info

- CHANGELOG.rst
- Makefile
- conf/HA/nginx/st2.conf.blueprint.sample
- conf/HA/nginx/st2.conf.controller.sample
- fixed-requirements.txt
- requirements.txt
- st2client/in-requirements.txt
- st2client/requirements.txt
- st2client/st2client/commands/action.py
- st2client/st2client/models/core.py
- st2client/tests/unit/test_models.py
- st2common/st2common/models/db/execution_queue.py
- st2common/tests/unit/test_db.py
- st2tests/st2tests/base.py
This pull request includes two additional fixes for v3.0.1 release:
1. https://github.com/StackStorm/st2/pull/4686
2. https://github.com/StackStorm/st2/pull/4690
> Additional changes for v3.0.1

- CHANGELOG.rst
Add v3.0.1 section and add appropriate entries to master branch after the patch release.
> Update changelog post v3.0.1 patch release

- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update orquesta to v1.0.0 in requirements.txt.
> Update orquesta version in requirements.txt

- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update the orquesta version in requirements.txt with the fix to address issue where fork from a cycle do not get executed more than once.
> Update orquesta version to fix cycle with fork in workflow

- .travis.yml
Forgot to revert this change as part of #4751
> Revert testing change

- contrib/runners/action_chain_runner/dist_utils.py
- contrib/runners/announcement_runner/dist_utils.py
- contrib/runners/http_runner/dist_utils.py
- contrib/runners/inquirer_runner/dist_utils.py
- contrib/runners/local_runner/dist_utils.py
- contrib/runners/mistral_v2/dist_utils.py
- contrib/runners/noop_runner/dist_utils.py
- contrib/runners/orquesta_runner/dist_utils.py
- contrib/runners/python_runner/dist_utils.py
- contrib/runners/remote_runner/dist_utils.py
- contrib/runners/winrm_runner/dist_utils.py
- st2actions/dist_utils.py
- st2api/dist_utils.py
- st2auth/dist_utils.py
- st2client/dist_utils.py
- st2common/dist_utils.py
- st2debug/dist_utils.py
- st2exporter/dist_utils.py
- st2reactor/dist_utils.py
- st2stream/dist_utils.py
- st2tests/dist_utils.py
Update all the dist_utils instances in the project as a result of changes made to scripts/dist_utils.py. When `make` is run, these instances are copied from scripts/dist_utils.py at https://github.com/StackStorm/st2/blob/master/Makefile#L916.
> Update all dist_utils instances

- CHANGELOG.rst
- contrib/examples/actions/orquesta-task-retry-exhausted.yaml
- contrib/examples/actions/orquesta-task-retry.yaml
- contrib/examples/actions/workflows/orquesta-task-retry-exhausted.yaml
- contrib/examples/actions/workflows/orquesta-task-retry.yaml
- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
- st2tests/integration/orquesta/test_wiring_task_retry.py
Update orquesta requirements to commit with the task retry feature. Add orquesta integration tests to cover task retry.
> Add support for orquesta task retry

- .circleci/config.yml
* Added el8 to the circleci build
> Add el8 rpm package builds to CircleCI

- CHANGELOG.rst
- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update orquesta to the commit version with the fix that enforces with items task to have action defined and throw exception if action is misindented.
> Update orquesta to version that has the syntax fix for with items task

- .github/ISSUE_TEMPLATE/support_request.md
> Fix typos in support request template

- CHANGELOG.rst
This PR just merges the 2 `changed` sections for the current changes.
> Merge changed sections in the CHANGELOG

- OWNERS.md
It's great to see AJ Jonen (@guzzijones) in StackStorm community for several months helping with st2 core, being active at Forums, trying pushing the Web UI fixes and being involved making the Orquesta workflow engine better.
- Web UI:
- PR Fixing CI (https://github.com/StackStorm/st2web/pull/753)
- PR Updated deprecated cryptiles (https://github.com/StackStorm/st2web/pull/751)
- PR to Remove Gulp util (https://github.com/StackStorm/st2web/pull/756)
- Bug report:  Inquiry not displaying line breaks as `<br>` (https://github.com/StackStorm/st2web/issues/739)
- StackStorm core:
- Issue #4851: Remove github repo depencencies
- Issue #4928: Polling Sensor token has expired.
- Bug report #4887: Large json input object cause double run tasks 
- PR fix #4886: New feature to make scheduling …
> Add AJ Jonen (@guzzijones) to the list of StackStorm Contributors

- OWNERS.md
I am unable to devote enough time to this project. It would be better for other active contributors to be on the TSC.
> Remove LindsayHill from TSC

- CHANGELOG.rst
- contrib/runners/orquesta_runner/in-requirements.txt
- contrib/runners/orquesta_runner/requirements.txt
- requirements.txt
- st2common/in-requirements.txt
- st2common/requirements.txt
Update orquesta version to release v1.2.0 that includes various bug fixes.
> Update orquesta verison to v1.2.0

- .github/workflows/ci.yaml
- .gitignore
- .travis.yml
- CHANGELOG.rst
- Makefile
- scripts/travis/install-requirements.sh
- scripts/travis/permissions-workaround.sh
- scripts/travis/prepare-integration.sh
- scripts/travis/rabbitmq.config
- scripts/travis/submit-codecov-coverage.sh
- scripts/travis/time-command.sh
- tox.ini
PR to PR #5098. Opening this is a separate PR so I (hopefully) don't confuse things too much.
> Keep enough Travis configuration to run integration tests

- .github/workflows/ci.yaml
- .github/workflows/orquesta-integration-tests.yaml
- CHANGELOG.rst
- Makefile
- fixed-requirements.txt
- requirements.txt
- st2actions/tests/unit/policies/test_concurrency.py
- st2actions/tests/unit/policies/test_concurrency_by_attr.py
- st2common/tests/fixtures/print_to_stdout_stderr_sleep.sh
- st2common/tests/integration/test_service_setup_log_level_filtering.py
- st2common/tests/integration/test_util_green.py
- st2common/tests/unit/test_service_setup.py
- st2tests/requirements.txt
- st2tests/st2tests/config.py
This PR adds some more tests for ``st2common.util.green.shell.run_command()`` function.
> Add some more tests for run_command() function

- instructables/chatops.md
We don't need this file anymore, and probably won't need it in the future. Let's get rid of it.
> Remove old and unused instructables directory and ChatOps file

- CHANGELOG.rst
This PR is needed because I forgot to merge #5378 in time and the new release branch has already been created.
> Changelog 3.6

- contrib/runners/action_chain_runner/action_chain_runner/__init__.py
- contrib/runners/announcement_runner/announcement_runner/__init__.py
- contrib/runners/http_runner/http_runner/__init__.py
- contrib/runners/inquirer_runner/inquirer_runner/__init__.py
- contrib/runners/local_runner/local_runner/__init__.py
- contrib/runners/noop_runner/noop_runner/__init__.py
- contrib/runners/orquesta_runner/orquesta_runner/__init__.py
- contrib/runners/python_runner/python_runner/__init__.py
- contrib/runners/remote_runner/remote_runner/__init__.py
- contrib/runners/winrm_runner/winrm_runner/__init__.py
- st2actions/st2actions/__init__.py
- st2api/st2api/__init__.py
- st2auth/st2auth/__init__.py
- st2client/st2client/__init__.py
- st2common/st2common/__init__.py
- st2reactor/st2reactor/__init__.py
- st2stream/st2stream/__init__.py
- st2tests/st2tests/__init__.py
This is a fix for issue: https://github.com/StackStorm/st2/issues/5455
Closes #5455
> fix wrong quotes (for black) in version string

- .github/workflows/ci.yaml
- .github/workflows/microbenchmarks.yaml
- .github/workflows/orquesta-integration-tests.yaml
- fixed-requirements.txt
- test-requirements.txt
- Removes two out-of-date requirements from fixed-requirements.txt that are no longer needed anywhere except for in tests.
- Harmonizes remaining differences by updating test-requirements.txt
> update test-requirements.txt to match fixed-requirements.txt

- CHANGELOG.rst
Add changelog for st2-auth-ldap [PR](https://github.com/StackStorm/st2-auth-ldap/pull/100).
> Add changelog for ldap backend

- CHANGELOG.rst
- st2api/tests/unit/controllers/v1/test_webhooks.py
- st2auth/tests/unit/controllers/v1/test_sso.py
- st2common/st2common/router.py
…oded
Opened in favor of https://github.com/StackStorm/st2/pull/5513
> Deserialize payload to str when content type is www-form-urlencoded

- OWNERS.md
Hey everyone - between 3 kids and moving on to other things, it's time to move on. It was fun. I learned a ton and wish everyone best of luck in the future.
> Move JP from TSC to Friends

- ADOPTERS.md
- README.md
Some readme enhancements to clarify ADOPTERS.md and add call to action so users can contribute adding their company to the list.
> Enhancements to Adopters.md
